'use strict';

/**
 * Question pool: 4 categories × 5 questions each.
 * Options are intentionally close in domain to force team debate.
 * SECURITY: The `answer` field is stripped by sanitizeRoom() before
 * sending to clients. It is only used server-side for evaluation.
 * text_tr / options_tr are Turkish translations sent alongside English.
 */
const QUESTIONS = {
  general: [
    {
      id: 'gen_01',
      text: 'Which organ in the human body produces bile?',
      text_tr: 'İnsan vücudunda safra üreten organ hangisidir?',
      options: {
        A: 'Pancreas',
        B: 'Gallbladder',
        C: 'Liver',
        D: 'Spleen',
        E: 'Duodenum',
      },
      options_tr: {
        A: 'Pankreas',
        B: 'Safra kesesi',
        C: 'Karaciğer',
        D: 'Dalak',
        E: 'Onikiparmak bağırsağı',
      },
      answer: 'C',
      explanation: 'The liver produces bile; the gallbladder only stores and concentrates it.',
    },
    {
      id: 'gen_02',
      text: 'What is the chemical symbol for Tungsten?',
      text_tr: 'Tungsten\'in kimyasal sembolü nedir?',
      options: {
        A: 'Tu',
        B: 'Wg',
        C: 'Tn',
        D: 'W',
        E: 'Wo',
      },
      options_tr: {
        A: 'Tu',
        B: 'Wg',
        C: 'Tn',
        D: 'W',
        E: 'Wo',
      },
      answer: 'D',
      explanation: 'From its German name "Wolfram". Tungsten is used in light bulb filaments.',
    },
    {
      id: 'gen_03',
      text: 'Which planet in our solar system has the most confirmed moons?',
      text_tr: 'Güneş sistemimizde en fazla onaylanmış uyduya sahip gezegen hangisidir?',
      options: {
        A: 'Jupiter',
        B: 'Neptune',
        C: 'Uranus',
        D: 'Saturn',
        E: 'Mars',
      },
      options_tr: {
        A: 'Jüpiter',
        B: 'Neptün',
        C: 'Uranüs',
        D: 'Satürn',
        E: 'Mars',
      },
      answer: 'D',
      explanation: 'Saturn surpassed Jupiter in 2023 with 146 confirmed moons.',
    },
    {
      id: 'gen_04',
      text: 'Who actually coined the term "Survival of the Fittest" in the context of evolution?',
      text_tr: 'Evrim bağlamında "En Uygun Olanın Hayatta Kalması" ifadesini gerçekte kim ortaya attı?',
      options: {
        A: 'Charles Darwin',
        B: 'Alfred Russel Wallace',
        C: 'Thomas Huxley',
        D: 'Herbert Spencer',
        E: 'Ernst Haeckel',
      },
      options_tr: {
        A: 'Charles Darwin',
        B: 'Alfred Russel Wallace',
        C: 'Thomas Huxley',
        D: 'Herbert Spencer',
        E: 'Ernst Haeckel',
      },
      answer: 'D',
      explanation:
        'Herbert Spencer coined the phrase in 1864. Darwin later adopted it from Spencer in later editions of "On the Origin of Species".',
    },
    {
      id: 'gen_05',
      text: 'Which country was the first to grant women the right to vote in national elections?',
      text_tr: 'Ulusal seçimlerde kadınlara oy hakkı tanıyan ilk ülke hangisidir?',
      options: {
        A: 'Finland',
        B: 'Australia',
        C: 'Norway',
        D: 'Denmark',
        E: 'New Zealand',
      },
      options_tr: {
        A: 'Finlandiya',
        B: 'Avustralya',
        C: 'Norveç',
        D: 'Danimarka',
        E: 'Yeni Zelanda',
      },
      answer: 'E',
      explanation: 'New Zealand granted women the right to vote in 1893, preceding all other nations.',
    },
  ],

  sports: [
    {
      id: 'spo_01',
      text: 'Which country hosted the first FIFA World Cup in 1930?',
      text_tr: '1930\'daki ilk FIFA Dünya Kupası\'na hangi ülke ev sahipliği yaptı?',
      options: {
        A: 'Brazil',
        B: 'Argentina',
        C: 'Chile',
        D: 'Italy',
        E: 'Uruguay',
      },
      options_tr: {
        A: 'Brezilya',
        B: 'Arjantin',
        C: 'Şili',
        D: 'İtalya',
        E: 'Uruguay',
      },
      answer: 'E',
      explanation: 'Uruguay hosted and won the first World Cup in 1930.',
    },
    {
      id: 'spo_02',
      text: 'How many players are on the field per side in a standard polo match?',
      text_tr: 'Standart bir polo maçında her takımdan kaç oyuncu sahada yer alır?',
      options: {
        A: '3',
        B: '4',
        C: '5',
        D: '6',
        E: '7',
      },
      options_tr: {
        A: '3',
        B: '4',
        C: '5',
        D: '6',
        E: '7',
      },
      answer: 'B',
      explanation: 'Polo is played with 4 players per team, each on horseback.',
    },
    {
      id: 'spo_03',
      text: 'In which year did Muhammad Ali defeat Sonny Liston to become World Heavyweight Champion for the first time?',
      text_tr: 'Muhammed Ali, ilk kez Dünya Ağır Sıklet Şampiyonu olmak için Sonny Liston\'ı hangi yılda yendi?',
      options: {
        A: '1960',
        B: '1962',
        C: '1964',
        D: '1966',
        E: '1968',
      },
      options_tr: {
        A: '1960',
        B: '1962',
        C: '1964',
        D: '1966',
        E: '1968',
      },
      answer: 'C',
      explanation: 'Ali (then Cassius Clay) defeated Liston by TKO in 1964.',
    },
    {
      id: 'spo_04',
      text: 'What is the maximum score achievable in a single game of ten-pin bowling?',
      text_tr: 'On-pin bowlingde tek bir oyunda elde edilebilecek maksimum puan nedir?',
      options: {
        A: '200',
        B: '250',
        C: '270',
        D: '300',
        E: '330',
      },
      options_tr: {
        A: '200',
        B: '250',
        C: '270',
        D: '300',
        E: '330',
      },
      answer: 'D',
      explanation: 'A perfect game of 12 consecutive strikes scores 300 points.',
    },
    {
      id: 'spo_05',
      text: 'Which athlete has won the most Olympic gold medals in a single Olympic Games?',
      text_tr: 'Tek bir Olimpiyat Oyunları\'nda en fazla altın madalya kazanan sporcu kimdir?',
      options: {
        A: 'Carl Lewis',
        B: 'Mark Spitz',
        C: 'Usain Bolt',
        D: 'Eric Heiden',
        E: 'Michael Phelps',
      },
      options_tr: {
        A: 'Carl Lewis',
        B: 'Mark Spitz',
        C: 'Usain Bolt',
        D: 'Eric Heiden',
        E: 'Michael Phelps',
      },
      answer: 'E',
      explanation:
        'Michael Phelps won 8 gold medals at the 2008 Beijing Olympics, surpassing Spitz\'s record of 7 (1972).',
    },
  ],

  history: [
    {
      id: 'his_01',
      text: 'The Battle of Thermopylae (480 BC) was a stand by a Greek force led primarily by which city-state?',
      text_tr: 'Thermopylae Savaşı (MÖ 480) ağırlıklı olarak hangi şehir devletinin liderliğindeki Yunan kuvvetleri tarafından verildi?',
      options: {
        A: 'Athens',
        B: 'Corinth',
        C: 'Thebes',
        D: 'Sparta',
        E: 'Argos',
      },
      options_tr: {
        A: 'Atina',
        B: 'Korint',
        C: 'Teba',
        D: 'Sparta',
        E: 'Argos',
      },
      answer: 'D',
      explanation: 'King Leonidas of Sparta led 300 Spartans (plus allies) against the Persian army at Thermopylae.',
    },
    {
      id: 'his_02',
      text: 'Which treaty formally ended World War I?',
      text_tr: 'Birinci Dünya Savaşı\'nı resmen sona erdiren antlaşma hangisidir?',
      options: {
        A: 'Treaty of Brest-Litovsk',
        B: 'Treaty of Saint-Germain',
        C: 'Treaty of Versailles',
        D: 'Treaty of Trianon',
        E: 'Treaty of Lausanne',
      },
      options_tr: {
        A: 'Brest-Litovsk Antlaşması',
        B: 'Saint-Germain Antlaşması',
        C: 'Versay Antlaşması',
        D: 'Trianon Antlaşması',
        E: 'Lozan Antlaşması',
      },
      answer: 'C',
      explanation:
        'The Treaty of Versailles (1919) ended WWI with Germany. Other treaties in the list also ended WWI but with different nations.',
    },
    {
      id: 'his_03',
      text: 'Which civilization built the city of Machu Picchu?',
      text_tr: 'Machu Picchu şehrini hangi medeniyet inşa etmiştir?',
      options: {
        A: 'Aztec',
        B: 'Olmec',
        C: 'Toltec',
        D: 'Maya',
        E: 'Inca',
      },
      options_tr: {
        A: 'Aztekler',
        B: 'Olmekler',
        C: 'Toltekler',
        D: 'Mayalar',
        E: 'İnkalar',
      },
      answer: 'E',
      explanation:
        'Machu Picchu was built by the Inca Empire in the 15th century in present-day Peru.',
    },
    {
      id: 'his_04',
      text: 'Which of the following structures was built BEFORE the Ottoman Conquest of Istanbul (1453)?',
      text_tr: 'Aşağıdaki yapılardan hangisi İstanbul\'un Osmanlı fethinden (1453) ÖNCE inşa edilmiştir?',
      options: {
        A: 'Rumeli Fortress',
        B: 'Anatolian Fortress',
        C: 'Tiled Kiosk (Çinili Köşk)',
        D: 'Fatih Mosque',
        E: 'Theodosius Cistern',
      },
      options_tr: {
        A: 'Rumeli Hisarı',
        B: 'Anadolu Hisarı',
        C: 'Çinili Köşk',
        D: 'Fatih Camii',
        E: 'Theodosius Sarnıcı',
      },
      answer: 'E',
      explanation:
        'The Theodosius Cistern was built in the 5th century AD by the Byzantine Empire. Rumeli Fortress (1452) and Anatolian Fortress (1394) were Ottoman-built siege preparations. The Tiled Kiosk (1472) and Fatih Mosque (1470) were built after the conquest.',
    },
    {
      id: 'his_05',
      text: 'Who was the last Pharaoh of Ancient Egypt?',
      text_tr: 'Antik Mısır\'ın son Firavunu kimdir?',
      options: {
        A: 'Nefertiti',
        B: 'Hatshepsut',
        C: 'Cleopatra VII',
        D: 'Ramesses III',
        E: 'Ptolemy XIII',
      },
      options_tr: {
        A: 'Nefertiti',
        B: 'Hatşepsut',
        C: 'Kleopatra VII',
        D: 'III. Ramses',
        E: 'XIII. Ptolemy',
      },
      answer: 'C',
      explanation:
        'Cleopatra VII (69–30 BC) was the last active ruler of the Ptolemaic Kingdom of Egypt before Roman annexation.',
    },
  ],

  cinema_music: [
    {
      id: 'cin_01',
      text: 'What was the first feature-length animated film ever released?',
      text_tr: 'Sinema tarihinde yayımlanan ilk uzun metrajlı animasyon filmi hangisidir?',
      options: {
        A: 'Bambi',
        B: 'Pinocchio',
        C: 'Fantasia',
        D: 'Snow White and the Seven Dwarfs',
        E: 'Dumbo',
      },
      options_tr: {
        A: 'Bambi',
        B: 'Pinokyo',
        C: 'Fantasia',
        D: 'Pamuk Prenses ve Yedi Cüceler',
        E: 'Dumbo',
      },
      answer: 'D',
      explanation: 'Snow White and the Seven Dwarfs (1937) was the first feature-length animated film by Disney.',
    },
    {
      id: 'cin_02',
      text: 'Which composer wrote the opera "The Magic Flute" (Die Zauberflöte)?',
      text_tr: '"Sihirli Flüt" (Die Zauberflöte) operasını besteleyen kimdir?',
      options: {
        A: 'Ludwig van Beethoven',
        B: 'Johann Sebastian Bach',
        C: 'George Frideric Handel',
        D: 'Franz Joseph Haydn',
        E: 'Wolfgang Amadeus Mozart',
      },
      options_tr: {
        A: 'Ludwig van Beethoven',
        B: 'Johann Sebastian Bach',
        C: 'George Frideric Handel',
        D: 'Franz Joseph Haydn',
        E: 'Wolfgang Amadeus Mozart',
      },
      answer: 'E',
      explanation: 'Mozart composed The Magic Flute in 1791, the year of his death.',
    },
    {
      id: 'cin_03',
      text: 'Which film won the very first Academy Award for Best Picture?',
      text_tr: 'İlk Academy Award En İyi Film ödülünü kazanan film hangisidir?',
      options: {
        A: 'It Happened One Night',
        B: 'All Quiet on the Western Front',
        C: 'Grand Hotel',
        D: 'Wings',
        E: 'Cimarron',
      },
      options_tr: {
        A: 'Bir Gece Oldu',
        B: 'Batı Cephesinde Yeni Bir Şey Yok',
        C: 'Grand Hotel',
        D: 'Wings',
        E: 'Cimarron',
      },
      answer: 'D',
      explanation:
        'Wings (1927) won Best Picture (then called "Outstanding Picture") at the 1st Academy Awards in 1929.',
    },
    {
      id: 'cin_04',
      text: 'Which actress holds the record for the most Academy Award wins for Best Actress?',
      text_tr: 'En İyi Kadın Oyuncu Oscar\'ını en fazla kazanan oyuncu kimdir?',
      options: {
        A: 'Meryl Streep',
        B: 'Cate Blanchett',
        C: 'Bette Davis',
        D: 'Katharine Hepburn',
        E: 'Audrey Hepburn',
      },
      options_tr: {
        A: 'Meryl Streep',
        B: 'Cate Blanchett',
        C: 'Bette Davis',
        D: 'Katharine Hepburn',
        E: 'Audrey Hepburn',
      },
      answer: 'D',
      explanation: 'Katharine Hepburn won 4 Best Actress Oscars (1933, 1967, 1968, 1981), the all-time record.',
    },
    {
      id: 'cin_05',
      text: 'The iconic opening bassline of "Under Pressure" (1981) by Queen & David Bowie was later sampled by which rapper without permission?',
      text_tr: 'Queen & David Bowie\'nin "Under Pressure" (1981) şarkısının ikonik bas ritmi, hangi rapçi tarafından izinsiz sample alındı?',
      options: {
        A: 'Tupac Shakur',
        B: 'The Notorious B.I.G.',
        C: 'Jay-Z',
        D: 'Vanilla Ice',
        E: 'Ice Cube',
      },
      options_tr: {
        A: 'Tupac Shakur',
        B: 'The Notorious B.I.G.',
        C: 'Jay-Z',
        D: 'Vanilla Ice',
        E: 'Ice Cube',
      },
      answer: 'D',
      explanation:
        'Vanilla Ice sampled the riff in "Ice Ice Baby" (1990). He initially denied it, claiming a slight difference, before eventually settling.',
    },
  ],
};

module.exports = { QUESTIONS };
