'use strict';

const anime = [
  {
    id: 'ani_01',
    text: 'Which anime series features the ninja Naruto Uzumaki, who has a nine-tailed fox sealed inside him?',
    text_tr: 'İçinde dokuz kuyruklu tilki mühürlü olan ninja Naruto Uzumaki\'yi konu alan anime hangisidir?',
    options: { A: 'Bleach', B: 'One Piece', C: 'Naruto', D: 'Dragon Ball Z', E: 'Fairy Tail' },
    options_tr: { A: 'Bleach', B: 'One Piece', C: 'Naruto', D: 'Dragon Ball Z', E: 'Fairy Tail' },
    answer: 'C',
    explanation: 'Naruto, created by Masashi Kishimoto, follows Naruto Uzumaki, who has the Nine-Tails Fox (Kurama) sealed within him.',
  },
  {
    id: 'ani_02',
    text: 'Which Studio Ghibli film follows a young girl named Chihiro who becomes trapped in a spirit world?',
    text_tr: 'Hangi Studio Ghibli filminde ruhlar dünyasına sıkışan Chihiro adlı genç bir kız anlatılır?',
    options: { A: 'Princess Mononoke', B: 'My Neighbor Totoro', C: 'Nausicaä of the Valley of the Wind', D: 'Spirited Away', E: 'Castle in the Sky' },
    options_tr: { A: 'Prenses Mononoke', B: 'Komşum Totoro', C: 'Rüzgarlı Vadi\'nin Nausicaä\'sı', D: 'Ruhların Kaçışı (Spirited Away)', E: 'Gökyüzündeki Kale' },
    answer: 'D',
    explanation: 'Spirited Away (2001), directed by Hayao Miyazaki, follows 10-year-old Chihiro trapped in a spirit realm.',
  },
  {
    id: 'ani_03',
    text: 'In "Attack on Titan", what are the giant humanoid creatures that devour humans called?',
    text_tr: '"Attack on Titan"da insanları yiyen devasa insansı yaratıklara ne ad verilir?',
    options: { A: 'Giants', B: 'Colossi', C: 'Titans', D: 'Devourers', E: 'Goliaths' },
    options_tr: { A: 'Devler', B: 'Koloslar', C: 'Titanlar', D: 'Yiyiciler', E: 'Golyatlar' },
    answer: 'C',
    explanation: 'In Attack on Titan (Shingeki no Kyojin), the giant humanoids threatening humanity are called Titans.',
  },
  {
    id: 'ani_04',
    text: 'Who is the creator of the manga "One Piece"?',
    text_tr: '"One Piece" mangasının yaratıcısı kimdir?',
    options: { A: 'Akira Toriyama', B: 'Tite Kubo', C: 'Masashi Kishimoto', D: 'Eiichiro Oda', E: 'Hajime Isayama' },
    options_tr: { A: 'Akira Toriyama', B: 'Tite Kubo', C: 'Masashi Kishimoto', D: 'Eiichiro Oda', E: 'Hajime Isayama' },
    answer: 'D',
    explanation: 'One Piece has been serialized by Eiichiro Oda in Weekly Shōnen Jump since 1997.',
  },
  {
    id: 'ani_05',
    text: 'Which anime is set in a world where most people have superpowers called "Quirks"?',
    text_tr: 'İnsanların çoğunun "Quirk" adı verilen süper güçlere sahip olduğu bir dünyada geçen anime hangisidir?',
    options: { A: 'Demon Slayer', B: 'My Hero Academia', C: 'Black Clover', D: 'Hunter x Hunter', E: 'Mob Psycho 100' },
    options_tr: { A: 'Demon Slayer', B: 'My Hero Academia', C: 'Black Clover', D: 'Hunter x Hunter', E: 'Mob Psycho 100' },
    answer: 'B',
    explanation: 'My Hero Academia (Boku no Hero Academia) is set in a world where roughly 80% of people have "Quirks".',
  },
  {
    id: 'ani_06',
    text: 'What Japanese term is used for a person who draws manga professionally?',
    text_tr: 'Profesyonel olarak manga çizen kişi için kullanılan Japonca terim nedir?',
    options: { A: 'Seiyū', B: 'Mangaka', C: 'Otaku', D: 'Sensei', E: 'Sakuga' },
    options_tr: { A: 'Seiyū', B: 'Mangaka', C: 'Otaku', D: 'Sensei', E: 'Sakuga' },
    answer: 'B',
    explanation: 'A "mangaka" is a manga artist. A "seiyū" is a voice actor.',
  },
  {
    id: 'ani_07',
    text: 'What does the word "seiyū" mean in the anime industry?',
    text_tr: 'Anime endüstrisinde "seiyū" kelimesi ne anlama gelir?',
    options: { A: 'Director', B: 'Voice actor', C: 'Animator', D: 'Screenwriter', E: 'Producer' },
    options_tr: { A: 'Yönetmen', B: 'Seslendirme sanatçısı', C: 'Animatör', D: 'Senarist', E: 'Yapımcı' },
    answer: 'B',
    explanation: 'A "seiyū" is a voice actor, a highly professionalized career in Japan.',
  },
  {
    id: 'ani_08',
    text: 'Manga aimed primarily at young teenage boys is called what?',
    text_tr: 'Öncelikle genç ergen erkeklere yönelik mangaya ne ad verilir?',
    options: { A: 'Shōjo', B: 'Seinen', C: 'Josei', D: 'Shōnen', E: 'Kodomo' },
    options_tr: { A: 'Shōjo', B: 'Seinen', C: 'Josei', D: 'Shōnen', E: 'Kodomo' },
    answer: 'D',
    explanation: '"Shōnen" targets teenage boys; "shōjo" targets teenage girls; "seinen" and "josei" target adult men and women.',
  },
  {
    id: 'ani_09',
    text: 'Which magazine has serialized Naruto, One Piece, Bleach, Dragon Ball and My Hero Academia?',
    text_tr: 'Naruto, One Piece, Bleach, Dragon Ball ve My Hero Academia\'yı yayımlayan dergi hangisidir?',
    options: { A: 'Weekly Shōnen Magazine', B: 'Weekly Shōnen Jump', C: 'Weekly Shōnen Sunday', D: 'Young Jump', E: 'Afternoon' },
    options_tr: { A: 'Weekly Shōnen Magazine', B: 'Weekly Shōnen Jump', C: 'Weekly Shōnen Sunday', D: 'Young Jump', E: 'Afternoon' },
    answer: 'B',
    explanation: 'Shueisha\'s Weekly Shōnen Jump is the most influential manga anthology, home to the "big three" and their successors.',
  },
  {
    id: 'ani_10',
    text: 'Who created the "Dragon Ball" manga?',
    text_tr: '"Dragon Ball" mangasını kim yarattı?',
    options: { A: 'Akira Toriyama', B: 'Osamu Tezuka', C: 'Yoshihiro Togashi', D: 'Rumiko Takahashi', E: 'Naoki Urasawa' },
    options_tr: { A: 'Akira Toriyama', B: 'Osamu Tezuka', C: 'Yoshihiro Togashi', D: 'Rumiko Takahashi', E: 'Naoki Urasawa' },
    answer: 'A',
    explanation: 'Akira Toriyama began Dragon Ball in 1984; he also designed characters for the Dragon Quest and Chrono Trigger games.',
  },
  {
    id: 'ani_11',
    text: 'Which filmmaker co-founded Studio Ghibli and directed "My Neighbor Totoro" and "Princess Mononoke"?',
    text_tr: 'Studio Ghibli\'nin kurucularından olan ve "Komşum Totoro" ile "Prenses Mononoke"yi yöneten sinemacı kimdir?',
    options: { A: 'Isao Takahata', B: 'Mamoru Hosoda', C: 'Hayao Miyazaki', D: 'Makoto Shinkai', E: 'Satoshi Kon' },
    options_tr: { A: 'Isao Takahata', B: 'Mamoru Hosoda', C: 'Hayao Miyazaki', D: 'Makoto Shinkai', E: 'Satoshi Kon' },
    answer: 'C',
    explanation: 'Miyazaki founded Ghibli in 1985 with Isao Takahata and producer Toshio Suzuki.',
  },
  {
    id: 'ani_12',
    text: 'Which Studio Ghibli film, directed by Isao Takahata, follows two siblings struggling to survive in wartime Japan?',
    text_tr: 'Isao Takahata\'nın yönettiği; savaş dönemi Japonya\'sında hayatta kalmaya çalışan iki kardeşi anlatan Studio Ghibli filmi hangisidir?',
    options: { A: 'Spirited Away', B: 'Grave of the Fireflies', C: 'The Wind Rises', D: 'Ponyo', E: 'Whisper of the Heart' },
    options_tr: { A: 'Ruhların Kaçışı', B: 'Ateşböceklerinin Mezarı', C: 'Rüzgâr Yükseliyor', D: 'Ponyo', E: 'Kalbin Fısıltısı' },
    answer: 'B',
    explanation: 'Grave of the Fireflies (1988) is set in Kobe during and after the American firebombing.',
  },
  {
    id: 'ani_13',
    text: 'Which 2016 anime film by Makoto Shinkai became a worldwide hit about two teenagers who swap bodies?',
    text_tr: 'Makoto Shinkai\'nin, beden değiştiren iki gencin hikâyesini anlatan ve dünya çapında hit olan 2016 anime filmi hangisidir?',
    options: { A: 'Weathering with You', B: 'Your Name.', C: '5 Centimeters per Second', D: 'A Silent Voice', E: 'The Garden of Words' },
    options_tr: { A: 'Weathering with You', B: 'Your Name. (Kimi no Na wa)', C: '5 Centimeters per Second', D: 'A Silent Voice', E: 'The Garden of Words' },
    answer: 'B',
    explanation: '"Your Name." (Kimi no Na wa, 2016) became one of the highest-grossing anime films ever.',
  },
  {
    id: 'ani_14',
    text: 'The 1988 film "Akira", a landmark of anime, is set in which fictional city?',
    text_tr: 'Anime\'nin bir dönüm noktası olan 1988 yapımı "Akira" filmi, hangi kurgusal şehirde geçer?',
    options: { A: 'Neo-Kyoto', B: 'Neo-Tokyo', C: 'Midgar', D: 'Neo-Yokohama', E: 'Neo-Osaka' },
    options_tr: { A: 'Neo-Kyoto', B: 'Neo-Tokyo', C: 'Midgar', D: 'Neo-Yokohama', E: 'Neo-Osaka' },
    answer: 'B',
    explanation: 'Katsuhiro Otomo directed and wrote "Akira", set in a dystopian Neo-Tokyo in 2019.',
  },
  {
    id: 'ani_15',
    text: 'Which mecha anime, created by Hideaki Anno in 1995, features teenagers piloting biomechanical "Evangelions"?',
    text_tr: 'Hideaki Anno\'nun 1995\'te yarattığı; gençlerin biyomekanik "Evangelion"ları kullandığı mecha anime hangisidir?',
    options: { A: 'Mobile Suit Gundam', B: 'Neon Genesis Evangelion', C: 'Code Geass', D: 'Gurren Lagann', E: 'RahXephon' },
    options_tr: { A: 'Mobile Suit Gundam', B: 'Neon Genesis Evangelion', C: 'Code Geass', D: 'Gurren Lagann', E: 'RahXephon' },
    answer: 'B',
    explanation: 'Neon Genesis Evangelion, produced by Gainax, redefined the mecha genre with heavy psychological themes.',
  },
  {
    id: 'ani_16',
    text: 'In "Death Note", what is the name of the shinigami who drops the notebook into the human world?',
    text_tr: '"Death Note"ta not defterini insan dünyasına düşüren shinigaminin adı nedir?',
    options: { A: 'Rem', B: 'Ryuk', C: 'Sidoh', D: 'Gelus', E: 'Armonia' },
    options_tr: { A: 'Rem', B: 'Ryuk', C: 'Sidoh', D: 'Gelus', E: 'Armonia' },
    answer: 'B',
    explanation: 'Ryuk drops his Death Note out of boredom; Light Yagami finds it and begins killing criminals.',
  },
  {
    id: 'ani_17',
    text: 'In "Death Note", what is the alias of the world\'s greatest detective who hunts Kira?',
    text_tr: '"Death Note"ta Kira\'nın peşine düşen, dünyanın en büyük dedektifinin takma adı nedir?',
    options: { A: 'N', B: 'M', C: 'L', D: 'Watari', E: 'K' },
    options_tr: { A: 'N', B: 'M', C: 'L', D: 'Watari', E: 'K' },
    answer: 'C',
    explanation: 'The detective goes only by the single letter "L"; his real name, L Lawliet, is revealed later.',
  },
  {
    id: 'ani_18',
    text: 'Which long-running franchise features a boy named Ash Ketchum (Satoshi) trying to become a Pokémon Master?',
    text_tr: 'Ash Ketchum (Satoshi) adlı bir çocuğun Pokémon Ustası olmaya çalışmasını konu alan uzun soluklu seri hangisidir?',
    options: { A: 'Digimon', B: 'Pokémon', C: 'Yu-Gi-Oh!', D: 'Beyblade', E: 'Monster Rancher' },
    options_tr: { A: 'Digimon', B: 'Pokémon', C: 'Yu-Gi-Oh!', D: 'Beyblade', E: 'Monster Rancher' },
    answer: 'B',
    explanation: 'The Pokémon anime began in 1997, based on the Nintendo games by Satoshi Tajiri.',
  },
  {
    id: 'ani_19',
    text: 'In the "Fullmetal Alchemist" world, what is the fundamental law that alchemists must obey?',
    text_tr: '"Fullmetal Alchemist" evreninde simyacıların uyması gereken temel yasa nedir?',
    options: {
      A: 'The law of infinite creation',
      B: 'The law of equivalent exchange',
      C: 'The law of conservation of souls',
      D: 'The three laws of transmutation',
      E: 'The rule of forbidden circles',
    },
    options_tr: {
      A: 'Sonsuz yaratım yasası',
      B: 'Eşdeğer takas (equivalent exchange) yasası',
      C: 'Ruhların korunumu yasası',
      D: 'Üç dönüşüm yasası',
      E: 'Yasak çemberler kuralı',
    },
    answer: 'B',
    explanation: 'To obtain something, something of equal value must be lost; this drives the Elric brothers\' story.',
  },
  {
    id: 'ani_20',
    text: 'Which anime follows Monkey D. Luffy, a boy whose body gained rubber properties after eating a Devil Fruit?',
    text_tr: 'Bir Şeytan Meyvesi yedikten sonra bedeni lastik özelliği kazanan Monkey D. Luffy\'yi konu alan anime hangisidir?',
    options: { A: 'Fairy Tail', B: 'One Piece', C: 'Black Clover', D: 'Hunter x Hunter', E: 'Toriko' },
    options_tr: { A: 'Fairy Tail', B: 'One Piece', C: 'Black Clover', D: 'Hunter x Hunter', E: 'Toriko' },
    answer: 'B',
    explanation: 'Luffy ate the Gomu Gomu no Mi and dreams of becoming the Pirate King in One Piece.',
  },
  {
    id: 'ani_21',
    text: 'The manga collectively called the "Big Three" of Weekly Shōnen Jump in the 2000s were One Piece, Naruto and which third series?',
    text_tr: '2000\'lerde Weekly Shōnen Jump\'ın "Büyük Üçlü"sü olarak anılan mangalar One Piece, Naruto ve hangi üçüncü seriydi?',
    options: { A: 'Bleach', B: 'Fairy Tail', C: 'Hunter x Hunter', D: 'Dragon Ball', E: 'Reborn!' },
    options_tr: { A: 'Bleach', B: 'Fairy Tail', C: 'Hunter x Hunter', D: 'Dragon Ball', E: 'Reborn!' },
    answer: 'A',
    explanation: 'Tite Kubo\'s Bleach completed the "Big Three" of that era.',
  },
  {
    id: 'ani_22',
    text: 'In "Demon Slayer", what is the name of the protagonist whose sister Nezuko is turned into a demon?',
    text_tr: '"Demon Slayer"da kız kardeşi Nezuko iblise dönüşen baş karakterin adı nedir?',
    options: { A: 'Zenitsu Agatsuma', B: 'Inosuke Hashibira', C: 'Tanjiro Kamado', D: 'Giyu Tomioka', E: 'Kyojuro Rengoku' },
    options_tr: { A: 'Zenitsu Agatsuma', B: 'Inosuke Hashibira', C: 'Tanjiro Kamado', D: 'Giyu Tomioka', E: 'Kyojuro Rengoku' },
    answer: 'C',
    explanation: 'Tanjiro Kamado joins the Demon Slayer Corps to cure Nezuko and avenge his family.',
  },
  {
    id: 'ani_23',
    text: 'Which studio animated "Demon Slayer" and is known for its high-quality digital effects work?',
    text_tr: '"Demon Slayer"ı animeleştiren ve yüksek kaliteli dijital efekt çalışmasıyla tanınan stüdyo hangisidir?',
    options: { A: 'MAPPA', B: 'ufotable', C: 'Madhouse', D: 'Bones', E: 'Wit Studio' },
    options_tr: { A: 'MAPPA', B: 'ufotable', C: 'Madhouse', D: 'Bones', E: 'Wit Studio' },
    answer: 'B',
    explanation: 'ufotable also produces the Fate series and is famous for blending 2D and 3D effects.',
  },
  {
    id: 'ani_24',
    text: 'In "Jujutsu Kaisen", the protagonist Yuji Itadori swallows a cursed object that is a finger of which powerful curse?',
    text_tr: '"Jujutsu Kaisen"de baş karakter Yuji Itadori, hangi güçlü lanetin parmağı olan lanetli bir nesneyi yutar?',
    options: { A: 'Mahito', B: 'Jogo', C: 'Ryomen Sukuna', D: 'Geto', E: 'Kenjaku' },
    options_tr: { A: 'Mahito', B: 'Jogo', C: 'Ryomen Sukuna', D: 'Geto', E: 'Kenjaku' },
    answer: 'C',
    explanation: 'Yuji swallows one of Sukuna\'s 20 fingers and becomes the "vessel" for the King of Curses.',
  },
  {
    id: 'ani_25',
    text: 'In "Chainsaw Man", the protagonist Denji merges with a chainsaw devil named what?',
    text_tr: '"Chainsaw Man"de baş karakter Denji, adı ne olan bir testere şeytanıyla birleşir?',
    options: { A: 'Power', B: 'Pochita', C: 'Makima', D: 'Aki', E: 'Beam' },
    options_tr: { A: 'Power', B: 'Pochita', C: 'Makima', D: 'Aki', E: 'Beam' },
    answer: 'B',
    explanation: 'Pochita, Denji\'s pet chainsaw devil, becomes his heart, letting him transform into Chainsaw Man.',
  },
  {
    id: 'ani_26',
    text: 'The anime "Cowboy Bebop" follows the crew of which spaceship?',
    text_tr: '"Cowboy Bebop" animesi, hangi uzay gemisinin mürettebatını takip eder?',
    options: { A: 'The Outlaw Star', B: 'The Bebop', C: 'The Swordfish', D: 'The Nirvana', E: 'The Macross' },
    options_tr: { A: 'The Outlaw Star', B: 'The Bebop', C: 'The Swordfish', D: 'The Nirvana', E: 'The Macross' },
    answer: 'B',
    explanation: 'Spike, Jet, Faye, Ed and the dog Ein are bounty hunters aboard the Bebop; Shinichirō Watanabe directed the 1998 series.',
  },
  {
    id: 'ani_27',
    text: 'Which director made the psychological anime films "Perfect Blue", "Millennium Actress" and "Paprika"?',
    text_tr: '"Perfect Blue", "Millennium Actress" ve "Paprika" adlı psikolojik anime filmlerini yapan yönetmen kimdir?',
    options: { A: 'Mamoru Oshii', B: 'Satoshi Kon', C: 'Katsuhiro Otomo', D: 'Shinichirō Watanabe', E: 'Hideaki Anno' },
    options_tr: { A: 'Mamoru Oshii', B: 'Satoshi Kon', C: 'Katsuhiro Otomo', D: 'Shinichirō Watanabe', E: 'Hideaki Anno' },
    answer: 'B',
    explanation: 'Satoshi Kon (1963–2010) was renowned for blurring dream and reality; "Paprika" influenced the film "Inception".',
  },
  {
    id: 'ani_28',
    text: 'Which 1995 film directed by Mamoru Oshii, based on a Masamune Shirow manga, is a landmark cyberpunk anime?',
    text_tr: 'Masamune Shirow mangasına dayanan, Mamoru Oshii\'nin yönettiği ve bir siberpunk anime dönüm noktası olan 1995 filmi hangisidir?',
    options: { A: 'Serial Experiments Lain', B: 'Ghost in the Shell', C: 'Ergo Proxy', D: 'Psycho-Pass', E: 'Texhnolyze' },
    options_tr: { A: 'Serial Experiments Lain', B: 'Ghost in the Shell', C: 'Ergo Proxy', D: 'Psycho-Pass', E: 'Texhnolyze' },
    answer: 'B',
    explanation: 'Ghost in the Shell follows Major Motoko Kusanagi of Public Security Section 9 and influenced films like "The Matrix".',
  },
  {
    id: 'ani_29',
    text: 'Which magical-girl anime, first aired in 1992, follows Usagi Tsukino as she transforms to fight evil?',
    text_tr: '1992\'de yayına başlayan; Usagi Tsukino\'nun kötülükle savaşmak için dönüşmesini konu alan sihirli kız animesi hangisidir?',
    options: { A: 'Cardcaptor Sakura', B: 'Sailor Moon', C: 'Magic Knight Rayearth', D: 'Puella Magi Madoka Magica', E: 'Pretty Cure' },
    options_tr: { A: 'Cardcaptor Sakura', B: 'Sailor Moon', C: 'Magic Knight Rayearth', D: 'Puella Magi Madoka Magica', E: 'Pretty Cure' },
    answer: 'B',
    explanation: 'Sailor Moon (Bishōjo Senshi Sailor Moon), created by Naoko Takeuchi, popularized the magical-girl genre worldwide.',
  },
  {
    id: 'ani_30',
    text: 'Osamu Tezuka, often called the "God of Manga", created which robotic boy hero in the 1950s-60s?',
    text_tr: 'Sıklıkla "Manganın Tanrısı" diye anılan Osamu Tezuka, 1950-60\'larda hangi robot çocuk kahramanı yarattı?',
    options: { A: 'Doraemon', B: 'Astro Boy', C: 'Gigantor', D: 'Mazinger Z', E: '8 Man' },
    options_tr: { A: 'Doraemon', B: 'Astro Boy (Tetsuwan Atom)', C: 'Gigantor', D: 'Mazinger Z', E: '8 Man' },
    answer: 'B',
    explanation: 'Astro Boy (Tetsuwan Atom) also became one of the first popular Japanese TV anime in 1963.',
  },
  {
    id: 'ani_31',
    text: 'In "Hunter x Hunter", the main character Gon is searching for whom?',
    text_tr: '"Hunter x Hunter"da ana karakter Gon kimi arıyor?',
    options: { A: 'His lost sister', B: 'His father, Ging', C: 'His missing mentor', D: 'A legendary treasure', E: 'His rival Killua' },
    options_tr: { A: 'Kayıp kız kardeşini', B: 'Babası Ging\'i', C: 'Kayıp akıl hocasını', D: 'Efsanevi bir hazineyi', E: 'Rakibi Killua\'yı' },
    answer: 'B',
    explanation: 'Gon Freecss becomes a Hunter to find his father Ging, a legendary Hunter who left him as a baby.',
  },
  {
    id: 'ani_32',
    text: 'Which anime\'s protagonist, Saitama, can defeat any opponent with a single punch?',
    text_tr: 'Baş karakteri Saitama, herhangi bir rakibi tek yumrukla yenebilen anime hangisidir?',
    options: { A: 'Mob Psycho 100', B: 'One-Punch Man', C: 'The Disastrous Life of Saiki K.', D: 'Assassination Classroom', E: 'Kill la Kill' },
    options_tr: { A: 'Mob Psycho 100', B: 'One-Punch Man', C: 'Saiki K.\'nın Feci Hayatı', D: 'Suikast Sınıfı', E: 'Kill la Kill' },
    answer: 'B',
    explanation: 'One-Punch Man began as a webcomic by the artist known as ONE, later redrawn by Yusuke Murata.',
  },
  {
    id: 'ani_33',
    text: 'What is the signature battle cry of the phrase system in "JoJo\'s Bizarre Adventure" for its psychic manifestations?',
    text_tr: '"JoJo\'nun Tuhaf Macerası"nda psişik tezahürler için kullanılan terim nedir?',
    options: { A: 'Personas', B: 'Stands', C: 'Nen', D: 'Quirks', E: 'Semblances' },
    options_tr: { A: 'Persona\'lar', B: 'Stand\'ler', C: 'Nen', D: 'Quirk\'ler', E: 'Semblance\'lar' },
    answer: 'B',
    explanation: 'From Part 3 onward, characters in JoJo manifest fighting spirits called "Stands", each with unique powers.',
  },
  {
    id: 'ani_34',
    text: 'Which anime features Edward and Alphonse Elric, brothers who lose parts of their bodies in a failed alchemical ritual?',
    text_tr: 'Başarısız bir simya ritüelinde bedenlerinin parçalarını kaybeden kardeşler Edward ve Alphonse Elric\'i konu alan anime hangisidir?',
    options: { A: 'The Promised Neverland', B: 'Fullmetal Alchemist', C: 'D.Gray-man', D: 'Blue Exorcist', E: 'Seraph of the End' },
    options_tr: { A: 'The Promised Neverland', B: 'Fullmetal Alchemist', C: 'D.Gray-man', D: 'Blue Exorcist', E: 'Seraph of the End' },
    answer: 'B',
    explanation: 'Fullmetal Alchemist was created by Hiromu Arakawa; the 2009 series "Brotherhood" closely follows the manga.',
  },
  {
    id: 'ani_35',
    text: 'Which term refers to a direct-to-video anime release, historically bypassing TV and cinema?',
    text_tr: 'Tarihsel olarak TV ve sinemayı atlayarak doğrudan videoya çıkan anime yayınları için kullanılan terim nedir?',
    options: { A: 'OP', B: 'OVA', C: 'ED', D: 'ONA (originally)', E: 'PV' },
    options_tr: { A: 'OP', B: 'OVA', C: 'ED', D: 'ONA (ilk anlamıyla)', E: 'PV' },
    answer: 'B',
    explanation: '"OVA" stands for Original Video Animation. "ONA" is Original Net Animation, released online.',
  },
  {
    id: 'ani_36',
    text: 'Which studio is known for "Cowboy Bebop", "Fullmetal Alchemist: Brotherhood" and "My Hero Academia"?',
    text_tr: '"Cowboy Bebop", "Fullmetal Alchemist: Brotherhood" ve "My Hero Academia" ile tanınan stüdyo hangisidir?',
    options: { A: 'Sunrise', B: 'Bones', C: 'Toei Animation', D: 'Pierrot', E: 'A-1 Pictures' },
    options_tr: { A: 'Sunrise', B: 'Bones', C: 'Toei Animation', D: 'Pierrot', E: 'A-1 Pictures' },
    answer: 'B',
    explanation: 'Studio Bones was founded in 1998 by former Sunrise staff.',
  },
  {
    id: 'ani_37',
    text: 'The "Gundam" franchise, which launched the "real robot" genre, first aired in which year?',
    text_tr: '"Gerçekçi robot" türünü başlatan "Gundam" serisi ilk kez hangi yıl yayınlandı?',
    options: { A: '1972', B: '1979', C: '1985', D: '1991', E: '1995' },
    options_tr: { A: '1972', B: '1979', C: '1985', D: '1991', E: '1995' },
    answer: 'B',
    explanation: 'Mobile Suit Gundam (Kidō Senshi Gundam) premiered in 1979, created by Yoshiyuki Tomino.',
  },
  {
    id: 'ani_38',
    text: 'In "My Hero Academia", the number-one hero and eventual mentor to Izuku Midoriya is known by what name?',
    text_tr: '"My Hero Academia"da bir numaralı kahraman ve Izuku Midoriya\'nın akıl hocası olan kişi hangi adla bilinir?',
    options: { A: 'Endeavor', B: 'All Might', C: 'Hawks', D: 'Eraser Head', E: 'Best Jeanist' },
    options_tr: { A: 'Endeavor', B: 'All Might', C: 'Hawks', D: 'Eraser Head', E: 'Best Jeanist' },
    answer: 'B',
    explanation: 'All Might, "the Symbol of Peace", passes his Quirk "One For All" to Midoriya.',
  },
  {
    id: 'ani_39',
    text: 'The anime "Spy x Family" centers on a spy, an assassin and a telepathic child forming what?',
    text_tr: '"Spy x Family" animesi; bir casus, bir suikastçı ve telepatik bir çocuğun ne oluşturmasını konu alır?',
    options: { A: 'A detective agency', B: 'A fake family', C: 'A rock band', D: 'A mercenary squad', E: 'A cooking team' },
    options_tr: { A: 'Bir dedektiflik bürosu', B: 'Sahte bir aile', C: 'Bir rock grubu', D: 'Bir paralı asker ekibi', E: 'Bir yemek ekibi' },
    answer: 'B',
    explanation: 'Loid (Twilight) builds a fake family with Yor and Anya to complete a mission, unaware of each other\'s secrets.',
  },
  {
    id: 'ani_40',
    text: 'The 2023 hit "Frieren: Beyond Journey\'s End" follows an elf mage reflecting on the passage of time after what event?',
    text_tr: '2023 yapımı "Frieren: Yolculuğun Ötesi", bir elf büyücünün hangi olaydan sonra zamanın akışı üzerine düşünmesini konu alır?',
    options: {
      A: 'Losing her magic',
      B: 'The death of her hero party\'s leader',
      C: 'A war between kingdoms',
      D: 'Being exiled from her homeland',
      E: 'The defeat of the Demon King, decades earlier',
    },
    options_tr: {
      A: 'Büyüsünü kaybetmesi',
      B: 'Kahraman ekibinin liderinin ölümü',
      C: 'Krallıklar arası bir savaş',
      D: 'Anayurdundan sürgün edilmesi',
      E: 'Onlarca yıl önce İblis Kralı\'nın yenilgisi',
    },
    answer: 'E',
    explanation: 'After the hero Himmel dies of old age, the near-immortal Frieren sets out to understand the humans she travelled with.',
  },
  {
    id: 'ani_41',
    text: 'Which anime follows Light Yagami, a student who gains the power to kill anyone whose name he writes in a notebook?',
    text_tr: 'Bir deftere adını yazdığı herkesi öldürme gücü kazanan öğrenci Light Yagami\'yi konu alan anime hangisidir?',
    options: { A: 'Code Geass', B: 'Death Note', C: 'Future Diary', D: 'Terror in Resonance', E: 'Monster' },
    options_tr: { A: 'Code Geass', B: 'Death Note', C: 'Future Diary', D: 'Terror in Resonance', E: 'Monster' },
    answer: 'B',
    explanation: 'Death Note (2006), based on the manga by Tsugumi Ohba and Takeshi Obata.',
  },
  {
    id: 'ani_42',
    text: 'Which Studio Ghibli film features a moving castle powered by a fire demon named Calcifer?',
    text_tr: 'Calcifer adlı bir ateş iblisiyle çalışan yürüyen bir şatoyu konu alan Studio Ghibli filmi hangisidir?',
    options: { A: 'Kiki\'s Delivery Service', B: 'Howl\'s Moving Castle', C: 'The Cat Returns', D: 'Tales from Earthsea', E: 'Arrietty' },
    options_tr: { A: 'Kiki\'nin Taşımacılık Servisi', B: 'Yürüyen Şato', C: 'Kedilerin Dönüşü', D: 'Yerdeniz Öyküleri', E: 'Arrietty' },
    answer: 'B',
    explanation: 'Howl\'s Moving Castle (2004), directed by Miyazaki, is based on the novel by Diana Wynne Jones.',
  },
  {
    id: 'ani_43',
    text: 'What is the fighting energy system called in "Hunter x Hunter"?',
    text_tr: '"Hunter x Hunter"daki savaş enerjisi sistemine ne ad verilir?',
    options: { A: 'Ki', B: 'Chakra', C: 'Nen', D: 'Reiatsu', E: 'Haki' },
    options_tr: { A: 'Ki', B: 'Chakra', C: 'Nen', D: 'Reiatsu', E: 'Haki' },
    answer: 'C',
    explanation: 'Nen lets users manipulate their aura; "Chakra" is from Naruto, "Reiatsu" from Bleach, "Haki" from One Piece.',
  },
  {
    id: 'ani_44',
    text: 'In "Naruto", what is the name of the ninja village where the main characters live?',
    text_tr: '"Naruto"da ana karakterlerin yaşadığı ninja köyünün adı nedir?',
    options: { A: 'Sunagakure', B: 'Konohagakure', C: 'Kirigakure', D: 'Iwagakure', E: 'Kumogakure' },
    options_tr: { A: 'Sunagakure', B: 'Konohagakure', C: 'Kirigakure', D: 'Iwagakure', E: 'Kumogakure' },
    answer: 'B',
    explanation: 'Konohagakure, "the Village Hidden in the Leaves", is the Land of Fire\'s ninja village.',
  },
  {
    id: 'ani_45',
    text: 'Which anime by Kyoto Animation follows a high-school light-music club and the band "Hōkago Tea Time"?',
    text_tr: 'Kyoto Animation yapımı olan; bir lise hafif müzik kulübünü ve "Hōkago Tea Time" grubunu konu alan anime hangisidir?',
    options: { A: 'Lucky Star', B: 'K-On!', C: 'Nichijou', D: 'Hyouka', E: 'Sound! Euphonium' },
    options_tr: { A: 'Lucky Star', B: 'K-On!', C: 'Nichijou', D: 'Hyouka', E: 'Sound! Euphonium' },
    answer: 'B',
    explanation: 'K-On! (2009) became a huge commercial success and a landmark of the "cute girls doing cute things" genre.',
  },
  {
    id: 'ani_46',
    text: 'The dere-type character archetype who is cold or hostile on the outside but warm underneath is called what?',
    text_tr: 'Dışarıdan soğuk veya düşmanca ama içeriden sıcak olan "dere" karakter arketipine ne ad verilir?',
    options: { A: 'Yandere', B: 'Kuudere', C: 'Tsundere', D: 'Dandere', E: 'Himedere' },
    options_tr: { A: 'Yandere', B: 'Kuudere', C: 'Tsundere', D: 'Dandere', E: 'Himedere' },
    answer: 'C',
    explanation: '"Tsundere" combines "tsun-tsun" (aloof) with "dere-dere" (lovey-dovey). "Yandere" adds obsessive, often violent devotion.',
  },
  {
    id: 'ani_47',
    text: 'Which sports anime is about a short volleyball player, Shōyō Hinata, who idolizes "the Little Giant"?',
    text_tr: '"Küçük Dev"e hayran olan kısa boylu voleybolcu Shōyō Hinata\'yı konu alan spor animesi hangisidir?',
    options: { A: 'Kuroko\'s Basketball', B: 'Haikyū!!', C: 'Blue Lock', D: 'Ace of Diamond', E: 'Free!' },
    options_tr: { A: 'Kuroko\'s Basketball', B: 'Haikyū!!', C: 'Blue Lock', D: 'Ace of Diamond', E: 'Free!' },
    answer: 'B',
    explanation: 'Haikyū!!, by Haruichi Furudate, follows Karasuno High\'s volleyball team.',
  },
  {
    id: 'ani_48',
    text: 'In "Attack on Titan", the power to transform into a Titan is tied to which people?',
    text_tr: '"Attack on Titan"da Titan\'a dönüşme gücü hangi halka bağlıdır?',
    options: { A: 'The Marleyans', B: 'The Eldians', C: 'The Ackermans', D: 'The people of Hizuru', E: 'The Walldians only' },
    options_tr: { A: 'Marleyalılar', B: 'Eldialılar', C: 'Ackerman\'lar', D: 'Hizuru halkı', E: 'Yalnızca Duvar halkı' },
    answer: 'B',
    explanation: 'Only Eldians ("Subjects of Ymir") can become Titans; the nine "Titan Shifters" hold special forms.',
  },
  {
    id: 'ani_49',
    text: 'Which studio, formed in 2011, animated "Jujutsu Kaisen", "Chainsaw Man" and the final seasons of "Attack on Titan"?',
    text_tr: '2011\'de kurulan; "Jujutsu Kaisen", "Chainsaw Man" ve "Attack on Titan"ın son sezonlarını animeleştiren stüdyo hangisidir?',
    options: { A: 'Wit Studio', B: 'MAPPA', C: 'CloverWorks', D: 'Trigger', E: 'Production I.G' },
    options_tr: { A: 'Wit Studio', B: 'MAPPA', C: 'CloverWorks', D: 'Trigger', E: 'Production I.G' },
    answer: 'B',
    explanation: 'Wit Studio animated Attack on Titan\'s first three seasons; MAPPA took over for the final season.',
  },
  {
    id: 'ani_50',
    text: 'Which Ghibli film, Miyazaki\'s first, features princess Nausicaä in a post-apocalyptic world of toxic jungle?',
    text_tr: 'Miyazaki\'nin ilk filmi olan; zehirli ormanlı kıyamet sonrası bir dünyada prenses Nausicaä\'yı konu alan Ghibli filmi hangisidir?',
    options: {
      A: 'Castle in the Sky',
      B: 'Nausicaä of the Valley of the Wind',
      C: 'The Wind Rises',
      D: 'Princess Mononoke',
      E: 'Porco Rosso',
    },
    options_tr: {
      A: 'Gökyüzündeki Kale',
      B: 'Rüzgarlı Vadi\'nin Nausicaä\'sı',
      C: 'Rüzgâr Yükseliyor',
      D: 'Prenses Mononoke',
      E: 'Kızıl Domuz (Porco Rosso)',
    },
    answer: 'B',
    explanation: 'Nausicaä (1984) predates the formal founding of Ghibli but is usually counted with its films; its success led to the studio.',
  },
  {
    id: 'ani_51',
    text: 'Which anime is about a shinigami named Ichigo Kurosaki who gains the power to see and fight Hollows?',
    text_tr: 'Hollow\'ları görme ve onlarla savaşma gücü kazanan bir shinigami olan Ichigo Kurosaki\'yi konu alan anime hangisidir?',
    options: { A: 'Blue Exorcist', B: 'Bleach', C: 'Soul Eater', D: 'Noragami', E: 'Yu Yu Hakusho' },
    options_tr: { A: 'Blue Exorcist', B: 'Bleach', C: 'Soul Eater', D: 'Noragami', E: 'Yu Yu Hakusho' },
    answer: 'B',
    explanation: 'Bleach, by Tite Kubo, ran from 2004; a new anime adapting the final arc began in 2022.',
  },
  {
    id: 'ani_52',
    text: 'What is the term for the sequence at the start of an anime episode, usually with the theme song?',
    text_tr: 'Bir anime bölümünün başında, genellikle jenerik şarkısıyla gelen kısım için kullanılan terim nedir?',
    options: { A: 'ED', B: 'OP', C: 'PV', D: 'CM', E: 'BD' },
    options_tr: { A: 'ED', B: 'OP', C: 'PV', D: 'CM', E: 'BD' },
    answer: 'B',
    explanation: '"OP" (opening) plays at the start; "ED" (ending) plays over the credits.',
  },
  {
    id: 'ani_53',
    text: 'The "isekai" genre is defined by a protagonist who does what?',
    text_tr: '"Isekai" türü, baş karakterin ne yapmasıyla tanımlanır?',
    options: {
      A: 'Time-travels to the past',
      B: 'Is transported to or reborn in another world',
      C: 'Gains amnesia',
      D: 'Discovers they are a robot',
      E: 'Switches genders',
    },
    options_tr: {
      A: 'Geçmişe zaman yolculuğu yapar',
      B: 'Başka bir dünyaya taşınır veya orada yeniden doğar',
      C: 'Hafızasını kaybeder',
      D: 'Robot olduğunu keşfeder',
      E: 'Cinsiyet değiştirir',
    },
    answer: 'B',
    explanation: '"Isekai" means "different world". Examples include Sword Art Online, Re:Zero and That Time I Got Reincarnated as a Slime.',
  },
  {
    id: 'ani_54',
    text: 'In "Re:Zero", the protagonist Subaru\'s power is the ability to do what upon dying?',
    text_tr: '"Re:Zero"da baş karakter Subaru\'nun gücü, öldüğünde ne yapabilmesidir?',
    options: {
      A: 'Possess another body',
      B: 'Return to a fixed earlier point in time',
      C: 'Read minds',
      D: 'Copy any spell he has seen',
      E: 'Become invisible',
    },
    options_tr: {
      A: 'Başka bir bedene geçmek',
      B: 'Belirli bir önceki zamana geri dönmek',
      C: 'Zihin okumak',
      D: 'Gördüğü herhangi bir büyüyü kopyalamak',
      E: 'Görünmez olmak',
    },
    answer: 'B',
    explanation: '"Return by Death" sends Subaru back to a checkpoint whenever he dies, but he cannot tell anyone about it.',
  },
  {
    id: 'ani_55',
    text: 'The manga "Berserk" was created by which author, who died in 2021 leaving it unfinished?',
    text_tr: '"Berserk" mangası, 2021\'de ölerek eseri yarım bırakan hangi yazar tarafından yaratıldı?',
    options: { A: 'Kentaro Miura', B: 'Yukito Kishiro', C: 'Takehiko Inoue', D: 'Kaoru Mori', E: 'Sui Ishida' },
    options_tr: { A: 'Kentaro Miura', B: 'Yukito Kishiro', C: 'Takehiko Inoue', D: 'Kaoru Mori', E: 'Sui Ishida' },
    answer: 'A',
    explanation: 'Miura began Berserk in 1989; his assistants and friend Kouji Mori have continued it from his notes.',
  },
  {
    id: 'ani_56',
    text: 'Which anime follows Thorfinn, a young Viking seeking revenge against the mercenary Askeladd?',
    text_tr: 'Paralı asker Askeladd\'dan intikam almak isteyen genç Viking Thorfinn\'i konu alan anime hangisidir?',
    options: { A: 'Vinland Saga', B: 'Golden Kamuy', C: 'Drifters', D: 'Kingdom', E: 'Record of Ragnarok' },
    options_tr: { A: 'Vinland Saga', B: 'Golden Kamuy', C: 'Drifters', D: 'Kingdom', E: 'Record of Ragnarok' },
    answer: 'A',
    explanation: 'Vinland Saga, by Makoto Yukimura, is a historical epic set in 11th-century England and Scandinavia.',
  },
  {
    id: 'ani_57',
    text: 'Which studio, known for "Gurren Lagann" and "Kill la Kill", was founded by ex-Gainax staff in 2011?',
    text_tr: '"Gurren Lagann" ve "Kill la Kill" ile tanınan; 2011\'de eski Gainax çalışanları tarafından kurulan stüdyo hangisidir?',
    options: { A: 'Trigger', B: 'Shaft', C: 'P.A. Works', D: 'David Production', E: 'Doga Kobo' },
    options_tr: { A: 'Trigger', B: 'Shaft', C: 'P.A. Works', D: 'David Production', E: 'Doga Kobo' },
    answer: 'A',
    explanation: 'Studio Trigger, formed by Hiroyuki Imaishi and Masahiko Otsuka, is known for energetic, exaggerated animation.',
  },
  {
    id: 'ani_58',
    text: 'In "Code Geass", the power granted to Lelouch by C.C., which compels absolute obedience, is called what?',
    text_tr: '"Code Geass"ta C.C.\'nin Lelouch\'a verdiği; mutlak itaate zorlayan güce ne ad verilir?',
    options: { A: 'The Contract', B: 'Geass', C: 'The Command', D: 'The Sceptre', E: 'The Code' },
    options_tr: { A: 'The Contract', B: 'Geass', C: 'The Command', D: 'The Sceptre', E: 'The Code' },
    answer: 'B',
    explanation: 'Lelouch\'s Geass lets him give any single command once per person, which they must obey.',
  },
  {
    id: 'ani_59',
    text: 'Which classic 1970s-80s anime, an adaptation of a Swiss novel, is directed by Isao Takahata and set in the Alps?',
    text_tr: 'Bir İsviçre romanının uyarlaması olan; Isao Takahata\'nın yönettiği ve Alpler\'de geçen klasik 1970-80\'ler animesi hangisidir?',
    options: { A: 'Anne of Green Gables', B: 'Heidi, Girl of the Alps', C: '3000 Leagues in Search of Mother', D: 'The Dog of Flanders', E: 'Future Boy Conan' },
    options_tr: { A: 'Yeşilin Kızı Anne', B: 'Alpler\'in Kızı Heidi', C: 'Anneni Ararken', D: 'Flandra\'nın Köpeği', E: 'Gelecek Çocuk Conan' },
    answer: 'B',
    explanation: '"Heidi, Girl of the Alps" (1974) featured layout work by a young Hayao Miyazaki.',
  },
  {
    id: 'ani_60',
    text: 'What does "shōjo" manga primarily target?',
    text_tr: '"Shōjo" mangası öncelikle kimi hedefler?',
    options: { A: 'Adult men', B: 'Teenage girls', C: 'Young children', D: 'Adult women', E: 'Teenage boys' },
    options_tr: { A: 'Yetişkin erkekler', B: 'Genç kızlar (ergen)', C: 'Küçük çocuklar', D: 'Yetişkin kadınlar', E: 'Genç erkekler (ergen)' },
    answer: 'B',
    explanation: 'Classic shōjo includes Sailor Moon, Fruits Basket and Ouran High School Host Club.',
  },
  {
    id: 'ani_61',
    text: 'Which anime and manga follows the Joestar family across generations and is known for dramatic poses and sound effects?',
    text_tr: 'Joestar ailesini nesiller boyunca takip eden; dramatik pozları ve ses efektleriyle bilinen anime ve manga hangisidir?',
    options: { A: 'Baki the Grappler', B: 'JoJo\'s Bizarre Adventure', C: 'Fist of the North Star', D: 'Hokuto no Ken', E: 'Grappler Baki' },
    options_tr: { A: 'Baki the Grappler', B: 'JoJo\'s Bizarre Adventure', C: 'Kuzey Yıldızının Yumruğu', D: 'Hokuto no Ken', E: 'Grappler Baki' },
    answer: 'B',
    explanation: 'Hirohiko Araki\'s JoJo has run since 1987 across nine parts; "ZA WARUDO" and "MUDA MUDA MUDA" are famous lines.',
  },
  {
    id: 'ani_62',
    text: 'The anime "Steins;Gate" is centered on the accidental invention of a device that can send messages where?',
    text_tr: '"Steins;Gate" animesi, kaza sonucu icat edilen; mesajları nereye gönderebilen bir cihaz etrafında döner?',
    options: { A: 'To parallel universes', B: 'To the past', C: 'To the future', D: 'Into people\'s dreams', E: 'To the afterlife' },
    options_tr: { A: 'Paralel evrenlere', B: 'Geçmişe', C: 'Geleceğe', D: 'İnsanların rüyalarına', E: 'Öbür dünyaya' },
    answer: 'B',
    explanation: 'The "Phone Microwave" sends texts ("D-Mails") to the past, altering the present in unpredictable ways.',
  },
  {
    id: 'ani_63',
    text: 'In Mamoru Hosoda\'s film "Wolf Children", the two children can transform into which animal?',
    text_tr: 'Mamoru Hosoda\'nın "Wolf Children" filminde iki çocuk hangi hayvana dönüşebilir?',
    options: { A: 'Foxes', B: 'Wolves', C: 'Bears', D: 'Deer', E: 'Dogs' },
    options_tr: { A: 'Tilkiler', B: 'Kurtlar', C: 'Ayılar', D: 'Geyikler', E: 'Köpekler' },
    answer: 'B',
    explanation: 'In "Wolf Children" (2012), Hana raises two children who are half wolf after their werewolf father dies.',
  },
  {
    id: 'ani_64',
    text: 'What is the name of the blue robotic cat from the future in the long-running children\'s series by Fujiko F. Fujio?',
    text_tr: 'Fujiko F. Fujio\'nun uzun soluklu çocuk serisindeki, gelecekten gelen mavi robot kedinin adı nedir?',
    options: { A: 'Jibanyan', B: 'Doraemon', C: 'Nyanko-sensei', D: 'Meowth', E: 'Luna' },
    options_tr: { A: 'Jibanyan', B: 'Doraemon', C: 'Nyanko-sensei', D: 'Meowth', E: 'Luna' },
    answer: 'B',
    explanation: 'Doraemon, from the 22nd century, helps the boy Nobita with gadgets from his fourth-dimensional pocket.',
  },
  {
    id: 'ani_65',
    text: 'In "One Piece", what is the name of the legendary treasure that pirates seek?',
    text_tr: '"One Piece"te korsanların aradığı efsanevi hazinenin adı nedir?',
    options: { A: 'The Rio Poneglyph', B: 'The One Piece', C: 'The Ancient Weapons', D: 'The Road Ponneglyphs', E: 'The Grand Line' },
    options_tr: { A: 'Rio Poneglyph', B: 'One Piece', C: 'Kadim Silahlar', D: 'Road Poneglyph\'ler', E: 'Grand Line' },
    answer: 'B',
    explanation: 'The treasure left by Gol D. Roger, the "Pirate King", is itself called the One Piece.',
  },
  {
    id: 'ani_66',
    text: 'Which anime depicts children on a farm who discover it is really a facility raising them as food for demons?',
    text_tr: 'Bir çiftlikteki çocukların, aslında iblislere yem olarak yetiştirildikleri bir tesiste olduklarını keşfetmelerini konu alan anime hangisidir?',
    options: { A: 'Made in Abyss', B: 'The Promised Neverland', C: 'Deadman Wonderland', D: 'Elfen Lied', E: 'Gunslinger Girl' },
    options_tr: { A: 'Made in Abyss', B: 'The Promised Neverland', C: 'Deadman Wonderland', D: 'Elfen Lied', E: 'Gunslinger Girl' },
    answer: 'B',
    explanation: 'The Promised Neverland, by Kaiu Shirai and Posuka Demizu, follows orphans Emma, Norman and Ray plotting to escape.',
  },
  {
    id: 'ani_67',
    text: 'What is the primary streaming service historically most associated with legal anime distribution in the West?',
    text_tr: 'Batı\'da yasal anime dağıtımıyla tarihsel olarak en çok özdeşleşen streaming servisi hangisidir?',
    options: { A: 'Hulu', B: 'Crunchyroll', C: 'Disney+', D: 'HBO Max', E: 'Peacock' },
    options_tr: { A: 'Hulu', B: 'Crunchyroll', C: 'Disney+', D: 'HBO Max', E: 'Peacock' },
    answer: 'B',
    explanation: 'Crunchyroll began in 2006 and, after merging with Funimation, is the dominant Western anime platform.',
  },
  {
    id: 'ani_68',
    text: 'Which anime, animated by Madhouse, is about a genius who tries to reform a corrupt world, drawing an obvious comparison to "Death Note"?',
    text_tr: 'Madhouse yapımı olan; bir dâhinin yozlaşmış bir dünyayı düzeltmeye çalışmasını konu alan ve "Death Note" ile açık bir kıyas yapılan anime hangisidir?',
    options: { A: 'Code Geass', B: 'Death Note', C: 'Monster', D: 'Psycho-Pass', E: 'No Game No Life' },
    options_tr: { A: 'Code Geass', B: 'Death Note', C: 'Monster', D: 'Psycho-Pass', E: 'No Game No Life' },
    answer: 'B',
    explanation: 'Madhouse produced the "Death Note" anime (2006); the question describes Light Yagami\'s premise.',
  },
  {
    id: 'ani_69',
    text: 'The term "otaku" broadly refers to what?',
    text_tr: '"Otaku" terimi genel olarak neyi ifade eder?',
    options: {
      A: 'A professional animator',
      B: 'An obsessive fan, often of anime and manga',
      C: 'A convention organizer',
      D: 'A manga editor',
      E: 'A cosplay competition judge',
    },
    options_tr: {
      A: 'Profesyonel bir animatör',
      B: 'Genellikle anime ve manga konusunda takıntılı bir hayran',
      C: 'Bir fuar organizatörü',
      D: 'Bir manga editörü',
      E: 'Bir cosplay yarışması jürisi',
    },
    answer: 'B',
    explanation: 'In Japan "otaku" can apply to any obsessive hobbyist and once carried a strongly negative connotation.',
  },
  {
    id: 'ani_70',
    text: 'Which anime features a high-school student, Yūji, who joins Tokyo Jujutsu High to fight Curses?',
    text_tr: 'Lise öğrencisi Yūji\'nin Lanetlerle savaşmak için Tokyo Jujutsu Lisesi\'ne katılmasını konu alan anime hangisidir?',
    options: { A: 'Blue Exorcist', B: 'Jujutsu Kaisen', C: 'Bleach', D: 'Twin Star Exorcists', E: 'Noragami' },
    options_tr: { A: 'Blue Exorcist', B: 'Jujutsu Kaisen', C: 'Bleach', D: 'Twin Star Exorcists', E: 'Noragami' },
    answer: 'B',
    explanation: 'Jujutsu Kaisen (2020), by Gege Akutami, quickly became one of the best-selling manga worldwide.',
  },
  {
    id: 'ani_71',
    text: 'Which mecha franchise, created by Shoji Kawamori, is famous for combining transforming jets, pop music and love triangles?',
    text_tr: 'Shoji Kawamori\'nin yarattığı; dönüşen jetleri, pop müziği ve aşk üçgenlerini birleştirmesiyle ünlü mecha serisi hangisidir?',
    options: { A: 'Gundam', B: 'Macross', C: 'Aura Battler Dunbine', D: 'Patlabor', E: 'Escaflowne' },
    options_tr: { A: 'Gundam', B: 'Macross', C: 'Aura Battler Dunbine', D: 'Patlabor', E: 'Escaflowne' },
    answer: 'B',
    explanation: 'The Super Dimension Fortress Macross (1982) was partly adapted into the Western "Robotech".',
  },
  {
    id: 'ani_72',
    text: 'In "Fruits Basket", members of the Sohma family transform into animals of what when hugged by the opposite sex?',
    text_tr: '"Fruits Basket"te Sohma ailesinin üyeleri, karşı cinsten biri sarıldığında hangi grubun hayvanlarına dönüşür?',
    options: { A: 'The Western zodiac', B: 'The Chinese zodiac', C: 'Mythical beasts', D: 'Household pets', E: 'Farm animals' },
    options_tr: { A: 'Batı burçları', B: 'Çin zodyağı', C: 'Efsanevi yaratıklar', D: 'Ev hayvanları', E: 'Çiftlik hayvanları' },
    answer: 'B',
    explanation: 'Each cursed Sohma is possessed by a spirit of the Chinese zodiac (plus the cat).',
  },
  {
    id: 'ani_73',
    text: 'Which anime by Trigger follows Ryuko Matoi, who wields half of a "Scissor Blade" and wears a sentient uniform?',
    text_tr: 'Trigger yapımı olan; bir "Scissor Blade"in yarısını kullanan ve bilinçli bir üniforma giyen Ryuko Matoi\'yi konu alan anime hangisidir?',
    options: { A: 'Little Witch Academia', B: 'Kill la Kill', C: 'Darling in the Franxx', D: 'Promare', E: 'BNA' },
    options_tr: { A: 'Little Witch Academia', B: 'Kill la Kill', C: 'Darling in the Franxx', D: 'Promare', E: 'BNA' },
    answer: 'B',
    explanation: 'Kill la Kill (2013) is set at Honnōji Academy, where power is granted by "Life Fibers" woven into clothing.',
  },
  {
    id: 'ani_74',
    text: 'The 2018 film "Mirai" and 2021\'s "Belle" were directed by whom?',
    text_tr: '2018 yapımı "Mirai" ve 2021 yapımı "Belle" filmlerini kim yönetti?',
    options: { A: 'Makoto Shinkai', B: 'Mamoru Hosoda', C: 'Naoko Yamada', D: 'Masaaki Yuasa', E: 'Hiromasa Yonebayashi' },
    options_tr: { A: 'Makoto Shinkai', B: 'Mamoru Hosoda', C: 'Naoko Yamada', D: 'Masaaki Yuasa', E: 'Hiromasa Yonebayashi' },
    answer: 'B',
    explanation: 'Hosoda, of Studio Chizu, also directed "Summer Wars", "Wolf Children" and "The Boy and the Beast".',
  },
  {
    id: 'ani_75',
    text: 'In "Attack on Titan", the three concentric defensive walls are named Maria, Rose and what?',
    text_tr: '"Attack on Titan"da iç içe geçmiş üç savunma duvarının adları Maria, Rose ve hangisidir?',
    options: { A: 'Sina', B: 'Ymir', C: 'Paradis', D: 'Eren', E: 'Historia' },
    options_tr: { A: 'Sina', B: 'Ymir', C: 'Paradis', D: 'Eren', E: 'Historia' },
    answer: 'A',
    explanation: 'From outermost to innermost: Wall Maria, Wall Rose, Wall Sina.',
  },
  {
    id: 'ani_76',
    text: 'Which anime, adapted from a Yoshihiro Togashi manga, features the "spirit detective" Yusuke Urameshi?',
    text_tr: 'Bir Yoshihiro Togashi mangasından uyarlanan; "ruh dedektifi" Yusuke Urameshi\'yi konu alan anime hangisidir?',
    options: { A: 'YuYu Hakusho', B: 'Flame of Recca', C: 'Rurouni Kenshin', D: 'Inuyasha', E: 'Shaman King' },
    options_tr: { A: 'YuYu Hakusho', B: 'Flame of Recca', C: 'Rurouni Kenshin', D: 'Inuyasha', E: 'Shaman King' },
    answer: 'A',
    explanation: 'YuYu Hakusho (1990–94) began after Yusuke dies saving a child and is given a chance to return to life.',
  },
  {
    id: 'ani_77',
    text: 'The "shōnen" battle trope where a character powers up dramatically to reverse a losing fight is often nicknamed what in the West?',
    text_tr: 'Bir karakterin kaybettiği bir dövüşü tersine çevirmek için dramatik biçimde güç kazanmasını anlatan shōnen klişesine Batı\'da genellikle ne denir?',
    options: { A: 'The "reset button"', B: 'The "power of friendship" / "asspull"', C: 'The "filler arc"', D: 'The "time skip"', E: 'The "retcon"' },
    options_tr: { A: '"Reset button"', B: '"Dostluğun gücü" / "asspull"', C: '"Filler arc"', D: '"Time skip"', E: '"Retcon"' },
    answer: 'B',
    explanation: 'Fans jokingly attribute sudden comebacks to "the power of friendship"; an unearned one is derisively called an "asspull".',
  },
  {
    id: 'ani_78',
    text: 'Which anime, animated by Bones, features Saitama and his cyborg disciple Genos in Hero Association City?',
    text_tr: 'Bones yapımı olan; Saitama ve sayborg çırağı Genos\'u Kahraman Derneği şehrinde konu alan anime hangisidir?',
    options: { A: 'Mob Psycho 100', B: 'One-Punch Man (season 1)', C: 'My Hero Academia', D: 'Concrete Revolutio', E: 'Tiger & Bunny' },
    options_tr: { A: 'Mob Psycho 100', B: 'One-Punch Man (1. sezon)', C: 'My Hero Academia', D: 'Concrete Revolutio', E: 'Tiger & Bunny' },
    answer: 'B',
    explanation: 'Madhouse animated One-Punch Man\'s acclaimed first season (2015); later seasons moved to J.C.Staff.',
  },
  {
    id: 'ani_79',
    text: 'Which anime film holds the record as one of the highest-grossing Japanese films, adapting the "Mugen Train" arc of a hit series?',
    text_tr: 'Bir hit serinin "Mugen Train" arkını uyarlayan ve en çok hasılat yapan Japon filmlerinden biri olarak rekora sahip anime filmi hangisidir?',
    options: {
      A: 'Jujutsu Kaisen 0',
      B: 'Demon Slayer: Kimetsu no Yaiba – The Movie: Mugen Train',
      C: 'One Piece Film: Red',
      D: 'Dragon Ball Super: Broly',
      E: 'My Hero Academia: Heroes Rising',
    },
    options_tr: {
      A: 'Jujutsu Kaisen 0',
      B: 'Demon Slayer: Kimetsu no Yaiba – Sonsuz Tren',
      C: 'One Piece Film: Red',
      D: 'Dragon Ball Super: Broly',
      E: 'My Hero Academia: Heroes Rising',
    },
    answer: 'B',
    explanation: 'The 2020 "Mugen Train" film became the highest-grossing film in Japanese box-office history at the time.',
  },
  {
    id: 'ani_80',
    text: 'In "Naruto", which technique is Naruto\'s spinning ball of chakra taught to him by Jiraiya?',
    text_tr: '"Naruto"da, Jiraiya\'nın ona öğrettiği; dönen bir chakra topu olan teknik hangisidir?',
    options: { A: 'Chidori', B: 'Rasengan', C: 'Amaterasu', D: 'Shadow Clone', E: 'Kamui' },
    options_tr: { A: 'Chidori', B: 'Rasengan', C: 'Amaterasu', D: 'Gölge Klonu', E: 'Kamui' },
    answer: 'B',
    explanation: 'The Rasengan was invented by Naruto\'s father, the Fourth Hokage. Chidori is Sasuke\'s signature move.',
  },
  {
    id: 'ani_81',
    text: 'Which anime and manga follows a swordsman named Himura Kenshin, a former assassin in Meiji-era Japan?',
    text_tr: 'Meiji dönemi Japonya\'sında eski bir suikastçı olan kılıç ustası Himura Kenshin\'i konu alan anime ve manga hangisidir?',
    options: { A: 'Samurai Champloo', B: 'Rurouni Kenshin', C: 'Blade of the Immortal', D: 'Dororo', E: 'Sword of the Stranger' },
    options_tr: { A: 'Samurai Champloo', B: 'Rurouni Kenshin', C: 'Ölümsüzün Kılıcı', D: 'Dororo', E: 'Yabancının Kılıcı' },
    answer: 'B',
    explanation: 'Rurouni Kenshin, by Nobuhiro Watsuki, follows the wandering swordsman who vows never to kill again.',
  },
  {
    id: 'ani_82',
    text: 'Which studio is famous for its lush, emotional style in films like "A Silent Voice" and shows like "Violet Evergarden"?',
    text_tr: '"A Silent Voice" gibi filmler ve "Violet Evergarden" gibi dizilerdeki zengin, duygusal tarzıyla ünlü stüdyo hangisidir?',
    options: { A: 'P.A. Works', B: 'Kyoto Animation', C: 'Shaft', D: 'Ufotable', E: 'CoMix Wave Films' },
    options_tr: { A: 'P.A. Works', B: 'Kyoto Animation', C: 'Shaft', D: 'Ufotable', E: 'CoMix Wave Films' },
    answer: 'B',
    explanation: 'Kyoto Animation ("KyoAni") is celebrated for character animation and backgrounds; "A Silent Voice" (2016) was directed by Naoko Yamada.',
  },
  {
    id: 'ani_83',
    text: 'Which anime follows the "Elric" brothers and was fully adapted a second time in 2009 as "Brotherhood" to match the manga\'s ending?',
    text_tr: '"Elric" kardeşleri konu alan ve mangasının sonuyla uyuşması için 2009\'da "Brotherhood" olarak ikinci kez baştan uyarlanan anime hangisidir?',
    options: { A: 'Soul Eater', B: 'Fullmetal Alchemist', C: 'Hellsing', D: 'Claymore', E: 'Trinity Blood' },
    options_tr: { A: 'Soul Eater', B: 'Fullmetal Alchemist', C: 'Hellsing', D: 'Claymore', E: 'Trinity Blood' },
    answer: 'B',
    explanation: 'The 2003 anime diverged from the still-running manga; "Brotherhood" retold the story faithfully.',
  },
  {
    id: 'ani_84',
    text: 'In "Dragon Ball Z", what is the name of Goku\'s signature energy-wave attack?',
    text_tr: '"Dragon Ball Z"de Goku\'nun imza enerji dalgası saldırısının adı nedir?',
    options: { A: 'Kamehameha', B: 'Final Flash', C: 'Galick Gun', D: 'Special Beam Cannon', E: 'Spirit Bomb' },
    options_tr: { A: 'Kamehameha', B: 'Final Flash', C: 'Galick Gun', D: 'Special Beam Cannon', E: 'Ruh Bombası' },
    answer: 'A',
    explanation: 'The Kamehameha, learned from Master Roshi, is Goku\'s trademark move.',
  },
  {
    id: 'ani_85',
    text: 'The "slice of life" genre in anime is best described as focusing on what?',
    text_tr: 'Anime\'deki "slice of life" (yaşamdan kesitler) türü en iyi neye odaklanmasıyla tanımlanır?',
    options: {
      A: 'Epic battles between armies',
      B: 'Everyday life and mundane events',
      C: 'Solving murder mysteries',
      D: 'Interstellar exploration',
      E: 'Historical warfare',
    },
    options_tr: {
      A: 'Ordular arası destansı savaşlar',
      B: 'Gündelik hayat ve sıradan olaylar',
      C: 'Cinayet gizemleri çözmek',
      D: 'Yıldızlararası keşif',
      E: 'Tarihsel savaşlar',
    },
    answer: 'B',
    explanation: 'Slice-of-life shows such as "Non Non Biyori" and "Aria" emphasize atmosphere and small daily moments over plot.',
  },
  {
    id: 'ani_86',
    text: 'Which anime centers on Eren Yeager, who vows to kill every Titan after one eats his mother?',
    text_tr: 'Bir Titan annesini yedikten sonra tüm Titanları öldürmeye yemin eden Eren Yeager\'ı konu alan anime hangisidir?',
    options: { A: 'Attack on Titan', B: 'Kabaneri of the Iron Fortress', C: 'God Eater', D: 'Seraph of the End', E: 'Claymore' },
    options_tr: { A: 'Attack on Titan', B: 'Kabaneri of the Iron Fortress', C: 'God Eater', D: 'Seraph of the End', E: 'Claymore' },
    answer: 'A',
    explanation: 'Attack on Titan (Shingeki no Kyojin) ran from 2013 to 2023 and was created by Hajime Isayama.',
  },
  {
    id: 'ani_87',
    text: 'Which anime and light novel series is about Kirito being trapped in the VR MMORPG "Aincrad"?',
    text_tr: 'Kirito\'nun sanal gerçeklik MMORPG\'si "Aincrad"da mahsur kalmasını konu alan anime ve light novel serisi hangisidir?',
    options: { A: 'Log Horizon', B: 'Sword Art Online', C: '.hack//Sign', D: 'Overlord', E: 'No Game No Life' },
    options_tr: { A: 'Log Horizon', B: 'Sword Art Online', C: '.hack//Sign', D: 'Overlord', E: 'No Game No Life' },
    answer: 'B',
    explanation: 'In SAO, 10,000 players are trapped in a game where dying in-game kills them in reality.',
  },
  {
    id: 'ani_88',
    text: 'The 2021 anime "Ranking of Kings" (Ōsama Ranking) follows Bojji, a young prince who is what?',
    text_tr: '2021 yapımı "Ranking of Kings" (Ōsama Ranking) animesi, genç prens Bojji\'yi konu alır; Bojji nasıl biridir?',
    options: {
      A: 'Deaf and physically weak',
      B: 'Secretly a demon',
      C: 'Blind but immensely strong',
      D: 'An android built by the king',
      E: 'Cursed to never age',
    },
    options_tr: {
      A: 'Sağır ve fiziksel olarak zayıf',
      B: 'Gizlice bir iblis',
      C: 'Kör ama son derece güçlü',
      D: 'Kral tarafından yapılmış bir android',
      E: 'Asla yaşlanmamaya lanetlenmiş',
    },
    answer: 'A',
    explanation: '"Ranking of Kings", animated by Wit Studio, follows the deaf, frail prince Bojji and his shadow-creature friend Kage.',
  },
  {
    id: 'ani_89',
    text: 'Which anime film, directed by Miyazaki, features the pig-faced World War I flying ace Porco Rosso?',
    text_tr: 'Miyazaki\'nin yönettiği; domuz yüzlü Birinci Dünya Savaşı pilot ası Porco Rosso\'yu konu alan anime filmi hangisidir?',
    options: { A: 'The Wind Rises', B: 'Porco Rosso', C: 'Castle in the Sky', D: 'Kiki\'s Delivery Service', E: 'The Boy and the Heron' },
    options_tr: { A: 'Rüzgâr Yükseliyor', B: 'Kızıl Domuz (Porco Rosso)', C: 'Gökyüzündeki Kale', D: 'Kiki\'nin Taşımacılık Servisi', E: 'Çocuk ve Balıkçıl' },
    answer: 'B',
    explanation: 'Porco Rosso (1992) follows a bounty-hunter seaplane pilot in the Adriatic, cursed to look like a pig.',
  },
  {
    id: 'ani_90',
    text: 'In "One Piece", what is the name of Luffy\'s pirate crew?',
    text_tr: '"One Piece"te Luffy\'nin korsan tayfasının adı nedir?',
    options: { A: 'The Red Hair Pirates', B: 'The Straw Hat Pirates', C: 'The Heart Pirates', D: 'The Whitebeard Pirates', E: 'The Beast Pirates' },
    options_tr: { A: 'Kızıl Saç Korsanları', B: 'Hasır Şapka Korsanları', C: 'Kalp Korsanları', D: 'Beyazsakal Korsanları', E: 'Canavar Korsanları' },
    answer: 'B',
    explanation: 'Named for Luffy\'s straw hat, a gift originally from the pirate "Red-Haired" Shanks.',
  },
  {
    id: 'ani_91',
    text: 'The 2022 anime "Cyberpunk: Edgerunners", set in the world of a CD Projekt game, was animated by which studio?',
    text_tr: 'Bir CD Projekt oyununun dünyasında geçen 2022 yapımı "Cyberpunk: Edgerunners" animesi, hangi stüdyo tarafından yapıldı?',
    options: { A: 'MAPPA', B: 'Studio Trigger', C: 'Wit Studio', D: 'Bones', E: 'Sunrise' },
    options_tr: { A: 'MAPPA', B: 'Studio Trigger', C: 'Wit Studio', D: 'Bones', E: 'Sunrise' },
    answer: 'B',
    explanation: 'Trigger animated the Netflix series set in Night City; it revived interest in the game after a rocky launch.',
  },
  {
    id: 'ani_92',
    text: 'Which term describes a Japanese comic, whether or not it has been animated?',
    text_tr: 'Bir Japon çizgi romanını, animeleştirilmiş olsun ya da olmasın tanımlayan terim hangisidir?',
    options: { A: 'Anime', B: 'Manga', C: 'Manhwa', D: 'Doujinshi', E: 'Light novel' },
    options_tr: { A: 'Anime', B: 'Manga', C: 'Manhwa', D: 'Doujinshi', E: 'Light novel' },
    answer: 'B',
    explanation: 'Manga are Japanese comics; "manhwa" is the Korean equivalent. "Doujinshi" are self-published fan works.',
  },
  {
    id: 'ani_93',
    text: 'Which 2011 anime by Gen Urobuchi deconstructs the magical-girl genre with a dark tale of Madoka and Homura?',
    text_tr: 'Gen Urobuchi\'nin 2011 yapımı; Madoka ve Homura\'nın karanlık hikâyesiyle sihirli kız türünü yapıbozuma uğratan animesi hangisidir?',
    options: { A: 'Yuki Yuna Is a Hero', B: 'Puella Magi Madoka Magica', C: 'Magical Girl Raising Project', D: 'Day Break Illusion', E: 'Flip Flappers' },
    options_tr: { A: 'Yuki Yuna Is a Hero', B: 'Puella Magi Madoka Magica', C: 'Magical Girl Raising Project', D: 'Day Break Illusion', E: 'Flip Flappers' },
    answer: 'B',
    explanation: 'Studio Shaft\'s Madoka Magica revealed that becoming a magical girl carries a horrific hidden cost.',
  },
  {
    id: 'ani_94',
    text: 'What are the main characters of "Attack on Titan" who use vertical maneuvering equipment to fight Titans collectively called?',
    text_tr: '"Attack on Titan"da dikey manevra ekipmanıyla Titanlarla savaşan ana karakterlerin bağlı olduğu birime ne ad verilir?',
    options: { A: 'The Military Police', B: 'The Garrison', C: 'The Survey Corps (Scout Regiment)', D: 'The Warriors', E: 'The Yeagerists' },
    options_tr: { A: 'Askeri İnzibat', B: 'Garnizon', C: 'Keşif Birliği (Survey Corps)', D: 'Savaşçılar', E: 'Yeager\'cılar' },
    answer: 'C',
    explanation: 'The Survey Corps ventures outside the Walls; Levi and Erwin are its most famous members.',
  },
  {
    id: 'ani_95',
    text: 'Which anime centers on a group of former childhood friends haunted by the death of a girl named Menma?',
    text_tr: 'Menma adlı bir kızın ölümünün peşini bırakmadığı, eski çocukluk arkadaşlarından oluşan bir grubu konu alan anime hangisidir?',
    options: {
      A: 'Anohana: The Flower We Saw That Day',
      B: 'Clannad',
      C: 'Your Lie in April',
      D: 'Angel Beats!',
      E: 'Erased',
    },
    options_tr: {
      A: 'Anohana: O Gün Gördüğümüz Çiçek',
      B: 'Clannad',
      C: 'Nisan Yalanın',
      D: 'Angel Beats!',
      E: 'Erased',
    },
    answer: 'A',
    explanation: 'Anohana (2011), animated by A-1 Pictures, is a well-known "cry" anime about grief and reconciliation.',
  },
  {
    id: 'ani_96',
    text: 'Which anime, set at U.A. High School, follows students training to become licensed professional heroes?',
    text_tr: 'U.A. Lisesi\'nde geçen ve lisanslı profesyonel kahraman olmak için eğitim gören öğrencileri konu alan anime hangisidir?',
    options: { A: 'Assassination Classroom', B: 'My Hero Academia', C: 'Little Witch Academia', D: 'Classroom of the Elite', E: 'Charlotte' },
    options_tr: { A: 'Suikast Sınıfı', B: 'My Hero Academia', C: 'Little Witch Academia', D: 'Seçkinlerin Sınıfı', E: 'Charlotte' },
    answer: 'B',
    explanation: 'Class 1-A at U.A. includes Midoriya, Bakugo, Todoroki and Uraraka.',
  },
  {
    id: 'ani_97',
    text: 'Which 2023 Miyazaki film, his first in a decade, is known in English as "The Boy and the Heron"?',
    text_tr: 'Miyazaki\'nin on yıl aradan sonraki ilk filmi olan; İngilizce "The Boy and the Heron" olarak bilinen 2023 filmi hangisidir?',
    options: {
      A: 'How Do You Live?',
      B: 'The Wind Rises',
      C: 'Earwig and the Witch',
      D: 'From Up on Poppy Hill',
      E: 'When Marnie Was There',
    },
    options_tr: {
      A: 'Sen Yaşamayı Nasıl Yaşarsın? (Kimi-tachi wa Dō Ikiru ka)',
      B: 'Rüzgâr Yükseliyor',
      C: 'Earwig ve Cadı',
      D: 'Gelincik Tepesinden',
      E: 'Marnie Buradayken',
    },
    answer: 'A',
    explanation: 'The Japanese title "Kimi-tachi wa Dō Ikiru ka" ("How Do You Live?") comes from a 1937 novel that appears in the film.',
  },
  {
    id: 'ani_98',
    text: 'The mascot creature Kyubey, which offers wishes at a terrible price, appears in which anime?',
    text_tr: 'Dilekleri korkunç bir bedelle sunan maskot yaratık Kyubey, hangi animede görülür?',
    options: { A: 'Puella Magi Madoka Magica', B: 'Sailor Moon', C: 'Cardcaptor Sakura', D: 'Nyan Koi!', E: 'Konosuba' },
    options_tr: { A: 'Puella Magi Madoka Magica', B: 'Sailor Moon', C: 'Cardcaptor Sakura', D: 'Nyan Koi!', E: 'Konosuba' },
    answer: 'A',
    explanation: 'Kyubey grants a wish in exchange for a girl becoming a magical girl, hiding the true nature of the bargain.',
  },
  {
    id: 'ani_99',
    text: 'What is the term for anime episodes that pad a series with side-stories not found in the source manga?',
    text_tr: 'Bir seriyi, kaynak mangada bulunmayan yan hikâyelerle uzatan anime bölümleri için kullanılan terim nedir?',
    options: { A: 'Recap episodes', B: 'Filler', C: 'OVAs', D: 'Specials', E: 'Cold opens' },
    options_tr: { A: 'Özet bölümler', B: 'Filler', C: 'OVA\'lar', D: 'Özel bölümler', E: 'Soğuk açılışlar' },
    answer: 'B',
    explanation: 'Long-running shows like Naruto and Bleach are infamous for "filler" arcs that let the manga get ahead.',
  },
  {
    id: 'ani_100',
    text: 'Which anime follows Ken Kaneki, a student who becomes a half-ghoul after a deadly date in Tokyo?',
    text_tr: 'Tokyo\'da ölümcül bir randevunun ardından yarı-gulyabani hâline gelen öğrenci Ken Kaneki\'yi konu alan anime hangisidir?',
    options: { A: 'Parasyte', B: 'Tokyo Ghoul', C: 'Ajin: Demi-Human', D: 'Deadman Wonderland', E: 'Devilman Crybaby' },
    options_tr: { A: 'Parasyte', B: 'Tokyo Ghoul', C: 'Ajin: Demi-Human', D: 'Deadman Wonderland', E: 'Devilman Crybaby' },
    answer: 'B',
    explanation: 'Tokyo Ghoul, by Sui Ishida, follows Kaneki after an organ transplant from a ghoul leaves him caught between two worlds.',
  },
];

module.exports = { anime };
