'use strict';

const cinema = [
  {
    id: 'cin_01',
    text: 'Which film won the Academy Award for Best Picture at the 92nd Oscars (2020)?',
    text_tr: '92. Oscar Ödülleri\'nde (2020) En İyi Film ödülünü hangi yapım kazandı?',
    options: { A: '1917', B: 'Joker', C: 'The Irishman', D: 'Parasite', E: 'Once Upon a Time in Hollywood' },
    options_tr: { A: '1917', B: 'Joker', C: 'İrlandalı', D: 'Parazit', E: 'Bir Zamanlar Hollywood\'da' },
    answer: 'D',
    explanation: 'Parasite (Bong Joon-ho, 2019) became the first non-English-language film to win Best Picture.',
  },
  {
    id: 'cin_02',
    text: 'Who directed The Dark Knight (2008)?',
    text_tr: 'Kara Şövalye (2008) filminin yönetmeni kimdir?',
    options: { A: 'Zack Snyder', B: 'Tim Burton', C: 'Christopher Nolan', D: 'J.J. Abrams', E: 'Ridley Scott' },
    options_tr: { A: 'Zack Snyder', B: 'Tim Burton', C: 'Christopher Nolan', D: 'J.J. Abrams', E: 'Ridley Scott' },
    answer: 'C',
    explanation: 'Christopher Nolan directed The Dark Knight, widely considered one of the greatest superhero films ever made.',
  },
  {
    id: 'cin_03',
    text: 'Which TV series features the fictional drug "Blue Sky" methamphetamine?',
    text_tr: 'Hangi dizi "Mavi Gök" adlı kurgusal metamfetamini içerir?',
    options: { A: 'Narcos', B: 'Breaking Bad', C: 'The Wire', D: 'Ozark', E: 'Weeds' },
    options_tr: { A: 'Narcos', B: 'Breaking Bad', C: 'The Wire', D: 'Ozark', E: 'Weeds' },
    answer: 'B',
    explanation: 'Breaking Bad\'s Walter White produces notoriously pure "blue" meth, a central plot element.',
  },
  {
    id: 'cin_04',
    text: 'How many seasons does the original run of "Friends" (1994–2004) have?',
    text_tr: '"Friends" (1994–2004) dizisinin orijinal yayın döneminde kaç sezonu vardır?',
    options: { A: '8', B: '9', C: '10', D: '11', E: '12' },
    options_tr: { A: '8', B: '9', C: '10', D: '11', E: '12' },
    answer: 'C',
    explanation: 'Friends ran for 10 seasons on NBC, concluding with one of the most-watched series finales in TV history.',
  },
  {
    id: 'cin_05',
    text: 'Which director made "The Godfather" (1972)?',
    text_tr: '"Baba" (1972) filminin yönetmeni kimdir?',
    options: { A: 'Martin Scorsese', B: 'Brian De Palma', C: 'Sidney Lumet', D: 'Francis Ford Coppola', E: 'William Friedkin' },
    options_tr: { A: 'Martin Scorsese', B: 'Brian De Palma', C: 'Sidney Lumet', D: 'Francis Ford Coppola', E: 'William Friedkin' },
    answer: 'D',
    explanation: 'Francis Ford Coppola directed The Godfather, which won Best Picture at the 1973 Academy Awards.',
  },
  {
    id: 'cin_06',
    text: 'Which film currently holds the all-time worldwide box office record (as of 2025)?',
    text_tr: '2025 itibarıyla tüm zamanların dünya geneli gişe rekorunu hangi film elinde bulundurmaktadır?',
    options: { A: 'Avengers: Endgame', B: 'Titanic', C: 'Avatar', D: 'The Lion King (2019)', E: 'Spider-Man: No Way Home' },
    options_tr: { A: 'Yenilmezler: Oyunun Sonu', B: 'Titanik', C: 'Avatar', D: 'Aslan Kral (2019)', E: 'Spider-Man: Eve Dönüş Yok' },
    answer: 'C',
    explanation: 'Avatar (2009, re-released 2022) holds the all-time box office record with over $2.92 billion worldwide.',
  },
  {
    id: 'cin_07',
    text: 'In Game of Thrones, which house has the words "Winter is Coming"?',
    text_tr: 'Game of Thrones\'ta "Kış Geliyor" sözleri hangi evin sloganıdır?',
    options: { A: 'House Lannister', B: 'House Baratheon', C: 'House Stark', D: 'House Targaryen', E: 'House Tully' },
    options_tr: { A: 'Lannister Hanesi', B: 'Baratheon Hanesi', C: 'Stark Hanesi', D: 'Targaryen Hanesi', E: 'Tully Hanesi' },
    answer: 'C',
    explanation: '"Winter is Coming" is the official motto of House Stark of Winterfell.',
  },
  {
    id: 'cin_08',
    text: 'Which streaming service produced the original series "Stranger Things"?',
    text_tr: '"Stranger Things" orijinal dizisini hangi yayın platformu üretti?',
    options: { A: 'HBO Max', B: 'Amazon Prime', C: 'Disney+', D: 'Netflix', E: 'Hulu' },
    options_tr: { A: 'HBO Max', B: 'Amazon Prime', C: 'Disney+', D: 'Netflix', E: 'Hulu' },
    answer: 'D',
    explanation: 'Stranger Things is a Netflix original series created by the Duffer Brothers, premiering in 2016.',
  },
  {
    id: 'cin_09',
    text: 'Which actor played Tony Stark / Iron Man in the MCU?',
    text_tr: 'MCU\'da Tony Stark / Demir Adam rolünü hangi aktör canlandırdı?',
    options: { A: 'Chris Evans', B: 'Mark Ruffalo', C: 'Robert Downey Jr.', D: 'Chris Hemsworth', E: 'Jeremy Renner' },
    options_tr: { A: 'Chris Evans', B: 'Mark Ruffalo', C: 'Robert Downey Jr.', D: 'Chris Hemsworth', E: 'Jeremy Renner' },
    answer: 'C',
    explanation: 'Robert Downey Jr. portrayed Tony Stark/Iron Man from Iron Man (2008) through Avengers: Endgame (2019).',
  },
  {
    id: 'cin_10',
    text: 'In which city is the TV series "Breaking Bad" primarily set?',
    text_tr: '"Breaking Bad" dizisi ağırlıklı olarak hangi şehirde geçmektedir?',
    options: { A: 'Phoenix', B: 'Las Vegas', C: 'Albuquerque', D: 'Tucson', E: 'El Paso' },
    options_tr: { A: 'Phoenix', B: 'Las Vegas', C: 'Albuquerque', D: 'Tucson', E: 'El Paso' },
    answer: 'C',
    explanation: 'Breaking Bad is set in Albuquerque, New Mexico, where creator Vince Gilligan grew up.',
  },
  {
    id: 'cin_11',
    text: 'Which film won the first Academy Award for Best Animated Feature in 2002?',
    text_tr: '2002\'de ilk En İyi Animasyon Filmi Oscar\'ını hangi yapım kazandı?',
    options: { A: 'Monsters, Inc.', B: 'Ice Age', C: 'Shrek', D: 'Spirited Away', E: 'Jimmy Neutron' },
    options_tr: { A: 'Canavarlar Şirketi', B: 'Buz Devri', C: 'Shrek', D: 'Sen Götür Beni', E: 'Jimmy Neutron' },
    answer: 'C',
    explanation: 'Shrek won the first-ever Best Animated Feature Oscar at the 74th Academy Awards (2002).',
  },
  {
    id: 'cin_12',
    text: 'How many episodes are in the final season (Season 8) of Game of Thrones?',
    text_tr: 'Game of Thrones\'un son sezonunda (8. sezon) kaç bölüm vardır?',
    options: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    options_tr: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    answer: 'C',
    explanation: 'Season 8 of Game of Thrones consisted of only 6 episodes, which disappointed many fans expecting a longer final season.',
  },
  {
    id: 'cin_13',
    text: 'Who played Walter White\'s partner Jesse Pinkman in Breaking Bad?',
    text_tr: 'Breaking Bad\'da Walter White\'ın ortağı Jesse Pinkman\'ı kim canlandırdı?',
    options: { A: 'Giancarlo Esposito', B: 'Dean Norris', C: 'Aaron Paul', D: 'Jonathan Banks', E: 'Bob Odenkirk' },
    options_tr: { A: 'Giancarlo Esposito', B: 'Dean Norris', C: 'Aaron Paul', D: 'Jonathan Banks', E: 'Bob Odenkirk' },
    answer: 'C',
    explanation: 'Aaron Paul won three Primetime Emmy Awards for Outstanding Supporting Actor for his role as Jesse Pinkman.',
  },
  {
    id: 'cin_14',
    text: 'Which Stanley Kubrick film is based on a Stephen King novel?',
    text_tr: 'Hangi Stanley Kubrick filmi bir Stephen King romanına dayanmaktadır?',
    options: { A: 'A Clockwork Orange', B: 'Full Metal Jacket', C: 'Eyes Wide Shut', D: 'The Shining', E: '2001: A Space Odyssey' },
    options_tr: { A: 'Otomatik Portakal', B: 'Tam Metal Ceket', C: 'Gözleri Tamamen Kapalı', D: 'Cinnet', E: '2001: Uzay Yolu Macerası' },
    answer: 'D',
    explanation: 'The Shining (1980) was adapted from Stephen King\'s 1977 novel of the same name, though King famously disliked Kubrick\'s adaptation.',
  },
  {
    id: 'cin_15',
    text: 'Which Turkish TV series became a global hit on Netflix starting around 2020?',
    text_tr: 'Hangi Türk televizyon dizisi 2020 civarında Netflix\'te küresel bir fenomene dönüştü?',
    options: { A: 'Diriliş: Ertuğrul', B: 'Çukur', C: 'Kara Para Aşk', D: 'Ezel', E: 'Fatih Harbiye' },
    options_tr: { A: 'Diriliş: Ertuğrul', B: 'Çukur', C: 'Kara Para Aşk', D: 'Ezel', E: 'Fatih Harbiye' },
    answer: 'A',
    explanation: 'Diriliş: Ertuğrul (Resurrection: Ertugrul) gained massive international viewership especially in Muslim-majority countries after hitting Netflix.',
  },
  {
    id: 'cin_16',
    text: 'The line "You talking to me?" is from which classic film?',
    text_tr: '"Benimle mi konuşuyorsun?" repliği hangi klasik filmden alınmıştır?',
    options: { A: 'Goodfellas', B: 'The Deer Hunter', C: 'Raging Bull', D: 'Taxi Driver', E: 'Serpico' },
    options_tr: { A: 'Sıradan İnsanlar', B: 'Avcı', C: 'Öfkeli Boğa', D: 'Taksi Şoförü', E: 'Serpico' },
    answer: 'D',
    explanation: 'Robert De Niro delivered this iconic improvised line in Taxi Driver (1976, dir. Martin Scorsese).',
  },
  {
    id: 'cin_17',
    text: 'Which actress has won the most Academy Awards for acting?',
    text_tr: 'Oyunculuk dalında en fazla Oscar kazanan kadın aktris kimdir?',
    options: { A: 'Meryl Streep', B: 'Cate Blanchett', C: 'Katharine Hepburn', D: 'Bette Davis', E: 'Ingrid Bergman' },
    options_tr: { A: 'Meryl Streep', B: 'Cate Blanchett', C: 'Katharine Hepburn', D: 'Bette Davis', E: 'Ingrid Bergman' },
    answer: 'C',
    explanation: 'Katharine Hepburn won 4 Best Actress Oscars (1934, 1968, 1969, 1982), the all-time record for any actor.',
  },
  {
    id: 'cin_18',
    text: 'In "The Office" (US), who is the regional manager of Dunder Mifflin Scranton?',
    text_tr: '"The Office" (ABD) dizisinde Dunder Mifflin Scranton şubesinin bölge müdürü kimdir?',
    options: { A: 'Jim Halpert', B: 'Dwight Schrute', C: 'Michael Scott', D: 'Andy Bernard', E: 'Ryan Howard' },
    options_tr: { A: 'Jim Halpert', B: 'Dwight Schrute', C: 'Michael Scott', D: 'Andy Bernard', E: 'Ryan Howard' },
    answer: 'C',
    explanation: 'Michael Scott, played by Steve Carell, is the lovably incompetent regional manager throughout most of The Office.',
  },
  {
    id: 'cin_19',
    text: 'Which film features the character Jack Dawson played by Leonardo DiCaprio?',
    text_tr: 'Leonardo DiCaprio\'nun Jack Dawson karakterini canlandırdığı film hangisidir?',
    options: { A: 'The Aviator', B: 'Titanic', C: 'Inception', D: 'The Great Gatsby', E: 'Catch Me If You Can' },
    options_tr: { A: 'Aviator', B: 'Titanik', C: 'Başlangıç', D: 'Muhteşem Gatsby', E: 'Beni Yakalarsan Yakala' },
    answer: 'B',
    explanation: 'Leonardo DiCaprio played Jack Dawson in James Cameron\'s Titanic (1997), which won 11 Academy Awards.',
  },
  {
    id: 'cin_20',
    text: 'Which HBO series is set in the fictional theme park "Westworld"?',
    text_tr: 'Hangi HBO dizisi kurgusal "Westworld" tema parkında geçmektedir?',
    options: { A: 'Devs', B: 'Westworld', C: 'Halt and Catch Fire', D: 'Black Mirror', E: 'Humans' },
    options_tr: { A: 'Devs', B: 'Westworld', C: 'Halt and Catch Fire', D: 'Black Mirror', E: 'Humans' },
    answer: 'B',
    explanation: 'Westworld (HBO, 2016–2022) explores AI consciousness in a futuristic Western-themed amusement park.',
  },
  {
    id: 'cin_21',
    text: 'Which director is known for films like "Pulp Fiction" and "Kill Bill"?',
    text_tr: '"Ucuz Roman" ve "Kill Bill" gibi filmlerle tanınan yönetmen kimdir?',
    options: { A: 'Robert Rodriguez', B: 'David Fincher', C: 'Quentin Tarantino', D: 'Guy Ritchie', E: 'Paul Thomas Anderson' },
    options_tr: { A: 'Robert Rodriguez', B: 'David Fincher', C: 'Quentin Tarantino', D: 'Guy Ritchie', E: 'Paul Thomas Anderson' },
    answer: 'C',
    explanation: 'Quentin Tarantino is renowned for his nonlinear narratives, stylized violence, and sharp dialogue.',
  },
  {
    id: 'cin_22',
    text: 'In "The Sopranos," what is Tony Soprano\'s occupation that serves as his cover?',
    text_tr: '"Sopranos\'ta" Tony Soprano\'nun sahte mesleği nedir?',
    options: { A: 'Restaurant owner', B: 'Car dealer', C: 'Waste management consultant', D: 'Construction contractor', E: 'Real estate developer' },
    options_tr: { A: 'Restoran sahibi', B: 'Araba satıcısı', C: 'Atık yönetimi danışmanı', D: 'İnşaat müteahhidi', E: 'Gayrimenkul geliştiricisi' },
    answer: 'C',
    explanation: 'Tony Soprano officially works as a "waste management consultant," a front for his mob activities.',
  },
  {
    id: 'cin_23',
    text: 'Which 2019 film directed by Martin Scorsese features De Niro, Pacino and Pesci together?',
    text_tr: 'Martin Scorsese\'nin yönettiği 2019 yapımı hangi filmde De Niro, Pacino ve Pesci bir arada yer almaktadır?',
    options: { A: 'Casino', B: 'Goodfellas', C: 'The Irishman', D: 'The Departed', E: 'Gangs of New York' },
    options_tr: { A: 'Casino', B: 'Sıradan İnsanlar', C: 'İrlandalı', D: 'Kaçış Noktası', E: 'New York Çeteleri' },
    answer: 'C',
    explanation: 'The Irishman (2019) reunited Scorsese with De Niro and Pesci, and featured Al Pacino for the first time in a Scorsese film.',
  },
  {
    id: 'cin_24',
    text: 'What is the name of the coffee shop in "Friends"?',
    text_tr: '"Friends" dizisindeki kafenin adı nedir?',
    options: { A: 'Perk\'s', B: 'Central Perk', C: 'Coffee Corner', D: 'The Grind', E: 'Java City' },
    options_tr: { A: 'Perk\'s', B: 'Central Perk', C: 'Coffee Corner', D: 'The Grind', E: 'Java City' },
    answer: 'B',
    explanation: 'Central Perk is the iconic Manhattan coffee house where the six Friends main characters regularly hang out.',
  },
  {
    id: 'cin_25',
    text: 'Who played the Joker in "The Dark Knight" (2008)?',
    text_tr: '"Kara Şövalye" (2008) filminde Joker rolünü kim canlandırdı?',
    options: { A: 'Jared Leto', B: 'Joaquin Phoenix', C: 'Jack Nicholson', D: 'Heath Ledger', E: 'Mark Hamill' },
    options_tr: { A: 'Jared Leto', B: 'Joaquin Phoenix', C: 'Jack Nicholson', D: 'Heath Ledger', E: 'Mark Hamill' },
    answer: 'D',
    explanation: 'Heath Ledger posthumously won the Academy Award for Best Supporting Actor for his portrayal of the Joker.',
  },
  {
    id: 'cin_26',
    text: 'In which year was the first episode of "Black Mirror" broadcast?',
    text_tr: '"Black Mirror"ın ilk bölümü hangi yılda yayınlandı?',
    options: { A: '2009', B: '2010', C: '2011', D: '2012', E: '2013' },
    options_tr: { A: '2009', B: '2010', C: '2011', D: '2012', E: '2013' },
    answer: 'C',
    explanation: 'Black Mirror premiered on Channel 4 in the UK on 4 December 2011 with the episode "The National Anthem."',
  },
  {
    id: 'cin_27',
    text: 'Which film won Best Picture at the 2017 Oscars after a famous envelope mix-up?',
    text_tr: 'Ünlü zarf karışıklığı sonrasında 2017 Oscar En İyi Film ödülünü hangi yapım kazandı?',
    options: { A: 'Hell or High Water', B: 'Hidden Figures', C: 'La La Land', D: 'Moonlight', E: 'Manchester by the Sea' },
    options_tr: { A: 'Ne Pahasına Olursa', B: 'Gizli Rakamlar', C: 'La La Land', D: 'Ay Işığı', E: 'Manchester by the Sea' },
    answer: 'D',
    explanation: 'Moonlight won Best Picture after La La Land was incorrectly announced first — one of Hollywood\'s most memorable Oscar moments.',
  },
  {
    id: 'cin_28',
    text: 'Which series follows chemistry teacher Walter White who turns to drug manufacturing?',
    text_tr: 'Uyuşturucu üretimine yönelen kimya öğretmeni Walter White\'ı konu alan dizi hangisidir?',
    options: { A: 'Ozark', B: 'Weeds', C: 'Better Call Saul', D: 'Breaking Bad', E: 'Narcos: Mexico' },
    options_tr: { A: 'Ozark', B: 'Weeds', C: 'Daha İyi Çağır Saul\'u', D: 'Breaking Bad', E: 'Narcos: Meksika' },
    answer: 'D',
    explanation: 'Breaking Bad (2008–2013) follows the transformation of high school chemistry teacher Walter White into drug kingpin "Heisenberg."',
  },
  {
    id: 'cin_29',
    text: 'What does "MCU" stand for?',
    text_tr: '"MCU" kısaltması neyi ifade eder?',
    options: { A: 'Marvel Cinematic Universe', B: 'Marvel Comics Universe', C: 'Marvel Cinematic Union', D: 'Major Cinema Universe', E: 'Marvel Creative Universe' },
    options_tr: { A: 'Marvel Sinematik Evreni', B: 'Marvel Çizgi Roman Evreni', C: 'Marvel Sinematik Birliği', D: 'Büyük Sinema Evreni', E: 'Marvel Yaratıcı Evreni' },
    answer: 'A',
    explanation: 'MCU stands for Marvel Cinematic Universe, the shared media franchise produced by Marvel Studios.',
  },
  {
    id: 'cin_30',
    text: 'Which actress plays Daenerys Targaryen in Game of Thrones?',
    text_tr: 'Game of Thrones\'ta Daenerys Targaryen rolünü hangi aktris canlandırır?',
    options: { A: 'Sophie Turner', B: 'Maisie Williams', C: 'Natalie Dormer', D: 'Emilia Clarke', E: 'Lena Headey' },
    options_tr: { A: 'Sophie Turner', B: 'Maisie Williams', C: 'Natalie Dormer', D: 'Emilia Clarke', E: 'Lena Headey' },
    answer: 'D',
    explanation: 'Emilia Clarke portrayed Daenerys Targaryen from Season 1 through the series finale in 2019.',
  },
  {
    id: 'cin_31',
    text: 'Which Coen Brothers film won Best Picture at the 2008 Oscars?',
    text_tr: 'Coen Kardeşler\'in hangi filmi 2008 Oscar\'ında En İyi Film ödülünü kazandı?',
    options: { A: 'Fargo', B: 'True Grit', C: 'No Country for Old Men', D: 'Burn After Reading', E: 'The Big Lebowski' },
    options_tr: { A: 'Fargo', B: 'Gerçek Cesaret', C: 'Yaşlılar İçin Yer Yok', D: 'Okuyunca Yak', E: 'Büyük Lebowski' },
    answer: 'C',
    explanation: 'No Country for Old Men swept the 2008 Oscars, winning Best Picture, Director, Adapted Screenplay, and Supporting Actor (Javier Bardem).',
  },
  {
    id: 'cin_32',
    text: 'Who created the TV series "Lost" (2004–2010)?',
    text_tr: '"Lost" (2004–2010) televizyon dizisini kim yarattı?',
    options: { A: 'Damon Lindelof & Carlton Cuse', B: 'J.J. Abrams, Damon Lindelof & Jeffrey Lieber', C: 'Vince Gilligan', D: 'David Chase', E: 'Matthew Weiner' },
    options_tr: { A: 'Damon Lindelof ve Carlton Cuse', B: 'J.J. Abrams, Damon Lindelof ve Jeffrey Lieber', C: 'Vince Gilligan', D: 'David Chase', E: 'Matthew Weiner' },
    answer: 'B',
    explanation: 'Lost was created by J.J. Abrams, Damon Lindelof, and Jeffrey Lieber for ABC, premiering in 2004.',
  },
  {
    id: 'cin_33',
    text: 'In "The Silence of the Lambs," what is Hannibal Lecter\'s profession?',
    text_tr: '"Kuzuların Sessizliği" filminde Hannibal Lecter\'ın mesleği nedir?',
    options: { A: 'Surgeon', B: 'Neurologist', C: 'Psychiatrist', D: 'Forensic scientist', E: 'Professor of literature' },
    options_tr: { A: 'Cerrah', B: 'Nörolog', C: 'Psikiyatrist', D: 'Adli tıp uzmanı', E: 'Edebiyat profesörü' },
    answer: 'C',
    explanation: 'Dr. Hannibal Lecter is a brilliant psychiatrist who is also a cannibalistic serial killer.',
  },
  {
    id: 'cin_34',
    text: 'Which studio produced the animated film "Spirited Away" (2001)?',
    text_tr: '"Sen Götür Beni" (2001) animasyon filmini hangi stüdyo üretti?',
    options: { A: 'Toei Animation', B: 'Madhouse', C: 'Studio Ghibli', D: 'Pierrot', E: 'Gainax' },
    options_tr: { A: 'Toei Animation', B: 'Madhouse', C: 'Studio Ghibli', D: 'Pierrot', E: 'Gainax' },
    answer: 'C',
    explanation: 'Spirited Away was produced by Studio Ghibli and directed by Hayao Miyazaki; it became the highest-grossing anime film of all time.',
  },
  {
    id: 'cin_35',
    text: 'Which Netflix series is about a group of teens who discover a time-bending bunker in a German town?',
    text_tr: 'Bir grup gencin Alman kasabasında zamanı büken bir sığınak keşfettiğini anlatan Netflix dizisi hangisidir?',
    options: { A: '1899', B: 'Ragnarök', C: 'Dark', D: 'Barbarians', E: 'Tribes of Europa' },
    options_tr: { A: '1899', B: 'Ragnarök', C: 'Dark', D: 'Barbarlar', E: 'Avrupa Kabileleri' },
    answer: 'C',
    explanation: 'Dark (2017–2020) is a German sci-fi thriller about time travel set in the fictional town of Winden.',
  },
  {
    id: 'cin_36',
    text: 'Which director made "Schindler\'s List" (1993)?',
    text_tr: '"Schindler\'in Listesi" (1993) filminin yönetmeni kimdir?',
    options: { A: 'Oliver Stone', B: 'Steven Spielberg', C: 'Barry Levinson', D: 'Rob Reiner', E: 'Sydney Pollack' },
    options_tr: { A: 'Oliver Stone', B: 'Steven Spielberg', C: 'Barry Levinson', D: 'Rob Reiner', E: 'Sydney Pollack' },
    answer: 'B',
    explanation: 'Steven Spielberg directed Schindler\'s List, which won seven Academy Awards including Best Picture and Best Director.',
  },
  {
    id: 'cin_37',
    text: 'What is the highest-rated TV series of all time on IMDb (as of 2025)?',
    text_tr: '2025 itibarıyla IMDb\'de tüm zamanların en yüksek puanlı dizisi hangisidir?',
    options: { A: 'The Sopranos', B: 'Game of Thrones', C: 'Breaking Bad', D: 'The Wire', E: 'Band of Brothers' },
    options_tr: { A: 'Sopranos', B: 'Game of Thrones', C: 'Breaking Bad', D: 'The Wire', E: 'Band of Brothers' },
    answer: 'C',
    explanation: 'Breaking Bad holds the top spot on IMDb\'s highest-rated TV series list with a rating of 9.5/10.',
  },
  {
    id: 'cin_38',
    text: 'Which film features the memorable line "I\'ll be back"?',
    text_tr: '"Geri döneceğim" repliğinin geçtiği film hangisidir?',
    options: { A: 'Predator', B: 'Total Recall', C: 'Commando', D: 'The Terminator', E: 'RoboCop' },
    options_tr: { A: 'Predator', B: 'Gerçek Hatıralar', C: 'Komando', D: 'Terminatör', E: 'RoboCop' },
    answer: 'D',
    explanation: 'Arnold Schwarzenegger\'s iconic "I\'ll be back" line appears in The Terminator (1984, dir. James Cameron).',
  },
  {
    id: 'cin_39',
    text: 'Which show features the fictional country of Westeros?',
    text_tr: 'Kurgusal Westeros ülkesinin geçtiği dizi hangisidir?',
    options: { A: 'The Witcher', B: 'Game of Thrones', C: 'Wheel of Time', D: 'Vikings', E: 'The Last Kingdom' },
    options_tr: { A: 'Büyücü', B: 'Game of Thrones', C: 'Zaman Çarkı', D: 'Vikingler', E: 'Son Krallık' },
    answer: 'B',
    explanation: 'Westeros is the fictional continent in George R.R. Martin\'s series "A Song of Ice and Fire," adapted into Game of Thrones.',
  },
  {
    id: 'cin_40',
    text: 'Who directed "Inception" (2010)?',
    text_tr: '"Başlangıç" (2010) filmini kim yönetmiştir?',
    options: { A: 'Ridley Scott', B: 'David Fincher', C: 'Denis Villeneuve', D: 'Christopher Nolan', E: 'Steven Soderbergh' },
    options_tr: { A: 'Ridley Scott', B: 'David Fincher', C: 'Denis Villeneuve', D: 'Christopher Nolan', E: 'Steven Soderbergh' },
    answer: 'D',
    explanation: 'Christopher Nolan wrote and directed Inception, starring Leonardo DiCaprio as a thief who steals information from dreams.',
  },
  {
    id: 'cin_41',
    text: 'Which actor played Bryan Cranston\'s character\'s boss Gus Fring in Breaking Bad?',
    text_tr: 'Breaking Bad\'da Bryan Cranston\'ın karakterinin patronu Gus Fring\'i hangi aktör canlandırdı?',
    options: { A: 'Mark Margolis', B: 'Steven Michael Quezada', C: 'Giancarlo Esposito', D: 'Raymond Cruz', E: 'Matt Jones' },
    options_tr: { A: 'Mark Margolis', B: 'Steven Michael Quezada', C: 'Giancarlo Esposito', D: 'Raymond Cruz', E: 'Matt Jones' },
    answer: 'C',
    explanation: 'Giancarlo Esposito portrayed Gustavo "Gus" Fring, the calculating drug distributor and fast food restaurateur.',
  },
  {
    id: 'cin_42',
    text: 'What year did the TV series "The Crown" first premiere on Netflix?',
    text_tr: '"The Crown" dizisi Netflix\'te ilk olarak hangi yılda yayınlandı?',
    options: { A: '2015', B: '2016', C: '2017', D: '2018', E: '2019' },
    options_tr: { A: '2015', B: '2016', C: '2017', D: '2018', E: '2019' },
    answer: 'B',
    explanation: 'The Crown premiered on Netflix on 4 November 2016, beginning with Queen Elizabeth II\'s early reign.',
  },
  {
    id: 'cin_43',
    text: 'Which film is famous for the shower scene featuring actress Janet Leigh?',
    text_tr: 'Janet Leigh\'in oynadığı duş sahnesiyle ünlü film hangisidir?',
    options: { A: 'Rebecca', B: 'Rear Window', C: 'Vertigo', D: 'Psycho', E: 'The Birds' },
    options_tr: { A: 'Rebecca', B: 'Arka Pencere', C: 'Tefrika', D: 'Sapık', E: 'Kuşlar' },
    answer: 'D',
    explanation: 'Alfred Hitchcock\'s Psycho (1960) features the iconic shower scene, filmed in 70 shots over seven days.',
  },
  {
    id: 'cin_44',
    text: 'In "Money Heist" (La Casa de Papel), what is the main villain\'s alias?',
    text_tr: '"Para Avcıları" (La Casa de Papel) dizisinde ana karakterin takma adı nedir?',
    options: { A: 'Tokyo', B: 'Berlin', C: 'The Professor', D: 'Nairobi', E: 'Moscow' },
    options_tr: { A: 'Tokyo', B: 'Berlin', C: 'Profesör', D: 'Nairobi', E: 'Moskova' },
    answer: 'C',
    explanation: 'Álvaro Morte plays "The Professor" (El Profesor), the genius mastermind who plans the heists in La Casa de Papel.',
  },
  {
    id: 'cin_45',
    text: 'Which Turkish film director made "Once Upon a Time in Anatolia" (2011)?',
    text_tr: '"Bir Zamanlar Anadolu\'da" (2011) filmini hangi Türk yönetmen çekmiştir?',
    options: { A: 'Fatih Akın', B: 'Ferzan Özpetek', C: 'Nuri Bilge Ceylan', D: 'Semih Kaplanoğlu', E: 'Yeşim Ustaoğlu' },
    options_tr: { A: 'Fatih Akın', B: 'Ferzan Özpetek', C: 'Nuri Bilge Ceylan', D: 'Semih Kaplanoğlu', E: 'Yeşim Ustaoğlu' },
    answer: 'C',
    explanation: 'Nuri Bilge Ceylan directed "Bir Zamanlar Anadolu\'da," which won the Grand Prix at the 2011 Cannes Film Festival.',
  },
  {
    id: 'cin_46',
    text: 'Which series follows a former spy named Raymond "Red" Reddington who works with the FBI?',
    text_tr: 'FBI ile iş birliği yapan eski casus Raymond "Red" Reddington\'ı konu alan dizi hangisidir?',
    options: { A: 'Homeland', B: 'The Americans', C: 'Alias', D: 'The Blacklist', E: 'Covert Affairs' },
    options_tr: { A: 'Homeland', B: 'Amerikalılar', C: 'Alias', D: 'Kara Liste', E: 'Gizli İşler' },
    answer: 'D',
    explanation: 'The Blacklist (NBC, 2013–2023) stars James Spader as Raymond "Red" Reddington, one of the FBI\'s most wanted fugitives turned informant.',
  },
  {
    id: 'cin_47',
    text: 'Which film holds the record for most Academy Award wins ever (tied at 11)?',
    text_tr: 'Tüm zamanların en fazla Oscar kazanan filmi olma rekorunu (11 ödülle) kim/kimlerle ortak tutar?',
    options: { A: 'Schindler\'s List, Titanic, Return of the King', B: 'Ben-Hur, Titanic, The Lord of the Rings: The Return of the King', C: 'Ben-Hur, Avatar, Titanic', D: 'All About Eve, La La Land, Titanic', E: 'Amadeus, Titanic, Return of the King' },
    options_tr: { A: 'Schindler\'in Listesi, Titanik, Yüzüklerin Efendisi', B: 'Ben-Hur, Titanik, Yüzüklerin Efendisi: Kralın Dönüşü', C: 'Ben-Hur, Avatar, Titanik', D: 'All About Eve, La La Land, Titanik', E: 'Amadeus, Titanik, Kralın Dönüşü' },
    answer: 'B',
    explanation: 'Ben-Hur (1959), Titanic (1997), and The Lord of the Rings: The Return of the King (2003) all won 11 Oscars each — the all-time record.',
  },
  {
    id: 'cin_48',
    text: 'In "Squid Game," what is the prize money for the winner?',
    text_tr: '"Squid Game" dizisinde kazananın alacağı para ödülü nedir?',
    options: { A: '10 billion won', B: '20 billion won', C: '45.6 billion won', D: '100 billion won', E: '50 billion won' },
    options_tr: { A: '10 milyar won', B: '20 milyar won', C: '45,6 milyar won', D: '100 milyar won', E: '50 milyar won' },
    answer: 'C',
    explanation: 'The prize in Squid Game is ₩45.6 billion (approximately $38 million USD), funded by 1,000 won per eliminated player.',
  },
  {
    id: 'cin_49',
    text: 'Who plays the lead role in the 2019 film "Joker"?',
    text_tr: '2019 yapımı "Joker" filminde başrol kim oynamaktadır?',
    options: { A: 'Jared Leto', B: 'Heath Ledger', C: 'Joaquin Phoenix', D: 'Mark Hamill', E: 'Jack Nicholson' },
    options_tr: { A: 'Jared Leto', B: 'Heath Ledger', C: 'Joaquin Phoenix', D: 'Mark Hamill', E: 'Jack Nicholson' },
    answer: 'C',
    explanation: 'Joaquin Phoenix won the Academy Award for Best Actor for his portrayal of Arthur Fleck/Joker in Todd Phillips\'s Joker (2019).',
  },
  {
    id: 'cin_50',
    text: 'Which year was the first season of "Survivor" broadcast in the USA?',
    text_tr: '"Survivor"ın ilk sezonu ABD\'de hangi yılda yayınlandı?',
    options: { A: '1998', B: '1999', C: '2000', D: '2001', E: '2002' },
    options_tr: { A: '1998', B: '1999', C: '2000', D: '2001', E: '2002' },
    answer: 'C',
    explanation: 'Survivor premiered on CBS on May 31, 2000, and became one of the most successful reality TV franchises globally.',
  },
  {
    id: 'cin_51',
    text: 'Which animated series features the character Homer Simpson?',
    text_tr: 'Homer Simpson karakterinin yer aldığı animasyon dizisi hangisidir?',
    options: { A: 'Family Guy', B: 'American Dad', C: 'King of the Hill', D: 'The Simpsons', E: 'Bob\'s Burgers' },
    options_tr: { A: 'Aile Adamı', B: 'Amerikan Babası', C: 'Tepenin Kralı', D: 'Simpsonlar', E: 'Bob\'un Burgerleri' },
    answer: 'D',
    explanation: 'The Simpsons (Fox, 1989–present) is the longest-running American animated series and primetime scripted TV series.',
  },
  {
    id: 'cin_52',
    text: 'Which Korean film directed by Bong Joon-ho won the Palme d\'Or at Cannes 2019?',
    text_tr: 'Bong Joon-ho\'nun yönettiği hangi Kore filmi 2019 Cannes Palme d\'Or\'unu kazandı?',
    options: { A: 'Okja', B: 'Snowpiercer', C: 'The Host', D: 'Parasite', E: 'Memories of Murder' },
    options_tr: { A: 'Okja', B: 'Kardan Adam Treni', C: 'Misafir', D: 'Parazit', E: 'Bir Cinayetin Anıları' },
    answer: 'D',
    explanation: 'Parasite won the Palme d\'Or at Cannes 2019, and went on to also win 4 Academy Awards including Best Picture.',
  },
  {
    id: 'cin_53',
    text: 'What is the name of the fictional high school in "Glee"?',
    text_tr: '"Glee" dizisindeki kurgusal listenin adı nedir?',
    options: { A: 'West McKinley High', B: 'William McKinley High School', C: 'East Lima High', D: 'McKinley Academy', E: 'Springfield High' },
    options_tr: { A: 'West McKinley Lisesi', B: 'William McKinley Lisesi', C: 'Doğu Lima Lisesi', D: 'McKinley Akademisi', E: 'Springfield Lisesi' },
    answer: 'B',
    explanation: 'Glee is set at the fictional William McKinley High School in Lima, Ohio.',
  },
  {
    id: 'cin_54',
    text: 'Which 2014 film stars Benedict Cumberbatch as Alan Turing?',
    text_tr: 'Benedict Cumberbatch\'in Alan Turing rolünü canlandırdığı 2014 yapımı film hangisidir?',
    options: { A: 'Ex Machina', B: 'The Theory of Everything', C: 'The Imitation Game', D: 'Steve Jobs', E: 'Enigma' },
    options_tr: { A: 'Ex Machina', B: 'Her Şeyin Teorisi', C: 'İmitasyon Oyunu', D: 'Steve Jobs', E: 'Enigma' },
    answer: 'C',
    explanation: 'The Imitation Game (2014) depicts Alan Turing\'s work breaking the German Enigma code during World War II.',
  },
  {
    id: 'cin_55',
    text: 'Which HBO series is set in the fictional city of Baltimore, focusing on the drug war?',
    text_tr: 'Kurgusal Baltimore şehrinde geçen ve uyuşturucu savaşını anlatan HBO dizisi hangisidir?',
    options: { A: 'Oz', B: 'The Wire', C: 'The Shield', D: 'Homicide', E: 'The Corner' },
    options_tr: { A: 'Oz', B: 'The Wire', C: 'Kalkan', D: 'Homicide', E: 'Köşe' },
    answer: 'B',
    explanation: 'The Wire (HBO, 2002–2008) is widely regarded as one of the greatest TV dramas ever made, exploring institutional dysfunction in Baltimore.',
  },
  {
    id: 'cin_56',
    text: 'Which actress played Katniss Everdeen in "The Hunger Games" film series?',
    text_tr: '"Açlık Oyunları" film serisinde Katniss Everdeen rolünü hangi aktris canlandırdı?',
    options: { A: 'Shailene Woodley', B: 'Kristen Stewart', C: 'Emma Watson', D: 'Jennifer Lawrence', E: 'Hailee Steinfeld' },
    options_tr: { A: 'Shailene Woodley', B: 'Kristen Stewart', C: 'Emma Watson', D: 'Jennifer Lawrence', E: 'Hailee Steinfeld' },
    answer: 'D',
    explanation: 'Jennifer Lawrence played Katniss Everdeen in all four Hunger Games films (2012–2015).',
  },
  {
    id: 'cin_57',
    text: 'Which series features dragons and a fight for the Iron Throne?',
    text_tr: 'Ejderhalar ve Demir Taht için mücadeleyi konu alan dizi hangisidir?',
    options: { A: 'The Last Kingdom', B: 'Vikings', C: 'Game of Thrones', D: 'Merlin', E: 'Camelot' },
    options_tr: { A: 'Son Krallık', B: 'Vikingler', C: 'Game of Thrones', D: 'Merlin', E: 'Camelot' },
    answer: 'C',
    explanation: 'Game of Thrones (HBO, 2011–2019) is based on George R.R. Martin\'s A Song of Ice and Fire fantasy novel series.',
  },
  {
    id: 'cin_58',
    text: 'Who directed "Interstellar" (2014)?',
    text_tr: '"Yıldızlararası" (2014) filminin yönetmeni kimdir?',
    options: { A: 'J.J. Abrams', B: 'Alfonso Cuarón', C: 'Ridley Scott', D: 'Christopher Nolan', E: 'Danny Boyle' },
    options_tr: { A: 'J.J. Abrams', B: 'Alfonso Cuarón', C: 'Ridley Scott', D: 'Christopher Nolan', E: 'Danny Boyle' },
    answer: 'D',
    explanation: 'Interstellar (2014) was written and directed by Christopher Nolan, featuring Matthew McConaughey as an astronaut exploring wormholes.',
  },
  {
    id: 'cin_59',
    text: 'In "Westworld," who plays the character Dr. Robert Ford, creator of the park?',
    text_tr: '"Westworld"de parkın yaratıcısı Dr. Robert Ford rolünü kim oynamaktadır?',
    options: { A: 'Ed Harris', B: 'Anthony Hopkins', C: 'Jeffrey Wright', D: 'James Marsden', E: 'Ben Barnes' },
    options_tr: { A: 'Ed Harris', B: 'Anthony Hopkins', C: 'Jeffrey Wright', D: 'James Marsden', E: 'Ben Barnes' },
    answer: 'B',
    explanation: 'Anthony Hopkins plays Dr. Robert Ford, the visionary and enigmatic creator of Westworld.',
  },
  {
    id: 'cin_60',
    text: 'Which Pixar film is set in a world where superheroes are forced to live as ordinary citizens?',
    text_tr: 'Hangi Pixar filmi, süper kahramanların sıradan vatandaşlar olarak yaşamaya zorlandığı bir dünyada geçmektedir?',
    options: { A: 'Up', B: 'Monsters, Inc.', C: 'Brave', D: 'The Incredibles', E: 'Cars' },
    options_tr: { A: 'Yukarı Bak', B: 'Canavarlar Şirketi', C: 'Cesur', D: 'İnanılmazlar', E: 'Arabalar' },
    answer: 'D',
    explanation: 'The Incredibles (2004) follows a family of superheroes trying to live quietly under a government superhero relocation program.',
  },
  {
    id: 'cin_61',
    text: 'Which Turkish film director won the Palme d\'Or at Cannes for "Winter Sleep" (2014)?',
    text_tr: '"Kış Uykusu" (2014) filmiyle Cannes\'da Altın Palmiye kazanan Türk yönetmen kimdir?',
    options: { A: 'Semih Kaplanoğlu', B: 'Zeki Demirkubuz', C: 'Nuri Bilge Ceylan', D: 'Ferzan Özpetek', E: 'Derviş Zaim' },
    options_tr: { A: 'Semih Kaplanoğlu', B: 'Zeki Demirkubuz', C: 'Nuri Bilge Ceylan', D: 'Ferzan Özpetek', E: 'Derviş Zaim' },
    answer: 'C',
    explanation: 'Nuri Bilge Ceylan\'s "Kış Uykusu" (Winter Sleep) won the Palme d\'Or at the 2014 Cannes Film Festival.',
  },
  {
    id: 'cin_62',
    text: 'What is the name of the fictional prison in "Prison Break"?',
    text_tr: '"Prison Break" dizisindeki kurgusal cezaevinin adı nedir?',
    options: { A: 'Riverbend Prison', B: 'Fox River State Penitentiary', C: 'Sona', D: 'Miami-Dade Correctional', E: 'Oswego Prison' },
    options_tr: { A: 'Riverbend Cezaevi', B: 'Fox River Eyalet Cezaevi', C: 'Sona', D: 'Miami-Dade Islah Evi', E: 'Oswego Cezaevi' },
    answer: 'B',
    explanation: 'Fox River State Penitentiary in Illinois is the main setting for the first two seasons of Prison Break.',
  },
  {
    id: 'cin_63',
    text: 'Which actor won the Best Actor Oscar for "The Revenant" (2016)?',
    text_tr: '"The Revenant" (2016) filmiyle En İyi Erkek Oyuncu Oscar\'ını kim kazandı?',
    options: { A: 'Michael Fassbender', B: 'Matt Damon', C: 'Bryan Cranston', D: 'Eddie Redmayne', E: 'Leonardo DiCaprio' },
    options_tr: { A: 'Michael Fassbender', B: 'Matt Damon', C: 'Bryan Cranston', D: 'Eddie Redmayne', E: 'Leonardo DiCaprio' },
    answer: 'E',
    explanation: 'Leonardo DiCaprio finally won his first Oscar for Best Actor for The Revenant at the 88th Academy Awards.',
  },
  {
    id: 'cin_64',
    text: 'Who created the animated series "South Park"?',
    text_tr: '"South Park" animasyon dizisini kim yarattı?',
    options: { A: 'Seth MacFarlane', B: 'Mike Judge', C: 'Trey Parker & Matt Stone', D: 'Seth Green', E: 'Dan Harmon' },
    options_tr: { A: 'Seth MacFarlane', B: 'Mike Judge', C: 'Trey Parker ve Matt Stone', D: 'Seth Green', E: 'Dan Harmon' },
    answer: 'C',
    explanation: 'South Park was created by Trey Parker and Matt Stone and has aired on Comedy Central since 1997.',
  },
  {
    id: 'cin_65',
    text: 'In which country is the drama series "Narcos" primarily set during its first two seasons?',
    text_tr: '"Narcos" drama dizisi ilk iki sezonunda ağırlıklı olarak hangi ülkede geçmektedir?',
    options: { A: 'Mexico', B: 'Bolivia', C: 'Peru', D: 'Colombia', E: 'Panama' },
    options_tr: { A: 'Meksika', B: 'Bolivya', C: 'Peru', D: 'Kolombiya', E: 'Panama' },
    answer: 'D',
    explanation: 'The first two seasons of Narcos follow Pablo Escobar and the Medellín Cartel in Colombia.',
  },
  {
    id: 'cin_66',
    text: 'Which film features the character "Forrest Gump" and the famous line about a box of chocolates?',
    text_tr: '"Forrest Gump" karakterinin ve çikolatalar hakkındaki ünlü sözün yer aldığı film hangisidir?',
    options: { A: 'Big', B: 'Cast Away', C: 'Philadelphia', D: 'Forrest Gump', E: 'Apollo 13' },
    options_tr: { A: 'Büyük', B: 'Issız Ada', C: 'Philadelphia', D: 'Forrest Gump', E: 'Apollo 13' },
    answer: 'D',
    explanation: 'Tom Hanks starred in Forrest Gump (1994), which won 6 Academy Awards including Best Picture and Best Actor.',
  },
  {
    id: 'cin_67',
    text: 'Which series features a chemistry teacher-turned-meth kingpin in New Mexico?',
    text_tr: 'Yeni Meksika\'da uyuşturucu baronuna dönüşen bir kimya öğretmenini anlatan dizi hangisidir?',
    options: { A: 'Ozark', B: 'Better Call Saul', C: 'Breaking Bad', D: 'Bloodline', E: 'Rectify' },
    options_tr: { A: 'Ozark', B: 'Daha İyi Çağır Saul\'u', C: 'Breaking Bad', D: 'Kan Bağı', E: 'Rectify' },
    answer: 'C',
    explanation: 'Breaking Bad follows Walter White\'s transformation from chemistry teacher to drug lord "Heisenberg" in Albuquerque, New Mexico.',
  },
  {
    id: 'cin_68',
    text: 'What is the name of the space station in the film "Gravity" (2013)?',
    text_tr: '"Yerçekimi" (2013) filmindeki uzay istasyonunun adı nedir?',
    options: { A: 'Mir', B: 'Skylab', C: 'ISS (International Space Station)', D: 'Salyut', E: 'Freedom' },
    options_tr: { A: 'Mir', B: 'Skylab', C: 'UUİ (Uluslararası Uzay İstasyonu)', D: 'Salyut', E: 'Özgürlük' },
    answer: 'C',
    explanation: 'Gravity (dir. Alfonso Cuarón) is set aboard the International Space Station (ISS) after a catastrophic debris storm.',
  },
  {
    id: 'cin_69',
    text: 'Which 1994 film features a briefcase containing a mysterious glowing object?',
    text_tr: 'Gizemli parlayan bir nesne içeren çantanın yer aldığı 1994 yapımı film hangisidir?',
    options: { A: 'The Usual Suspects', B: 'Se7en', C: 'Pulp Fiction', D: 'Natural Born Killers', E: 'True Romance' },
    options_tr: { A: 'Olağan Şüpheliler', B: 'Yedi', C: 'Ucuz Roman', D: 'Doğuştan Katiller', E: 'Gerçek Romantizm' },
    answer: 'C',
    explanation: 'In Pulp Fiction (1994), the briefcase with a golden glow (its contents never revealed) is one of cinema\'s great MacGuffins.',
  },
  {
    id: 'cin_70',
    text: 'Which actress plays "Cersei Lannister" in Game of Thrones?',
    text_tr: 'Game of Thrones\'ta "Cersei Lannister" rolünü hangi aktris canlandırmaktadır?',
    options: { A: 'Natalie Dormer', B: 'Michelle Fairley', C: 'Lena Headey', D: 'Carice van Houten', E: 'Diana Rigg' },
    options_tr: { A: 'Natalie Dormer', B: 'Michelle Fairley', C: 'Lena Headey', D: 'Carice van Houten', E: 'Diana Rigg' },
    answer: 'C',
    explanation: 'Lena Headey portrays the cunning and ruthless Queen Cersei Lannister throughout all 8 seasons of Game of Thrones.',
  },
  {
    id: 'cin_71',
    text: 'Which Oscar-winning film is about a real-life hostage rescue in Iran in 1979–1980?',
    text_tr: 'Hangi Oscar ödüllü film, 1979–1980 yıllarında İran\'daki gerçek bir rehin kurtarma operasyonunu konu almaktadır?',
    options: { A: 'Zero Dark Thirty', B: 'Lincoln', C: 'Argo', D: 'Munich', E: 'Syriana' },
    options_tr: { A: 'Sıfır Karanlık Otuz', B: 'Lincoln', C: 'Argo', D: 'Münih', E: 'Syriana' },
    answer: 'C',
    explanation: 'Argo (dir. Ben Affleck, 2012) won Best Picture for its dramatization of the Canadian Caper during the Iran hostage crisis.',
  },
  {
    id: 'cin_72',
    text: 'What is the name of the serial killer in "Dexter"?',
    text_tr: '"Dexter" dizisindeki seri katilin tam adı nedir?',
    options: { A: 'Dexter Bennett', B: 'Dexter Warren', C: 'Dexter Morgan', D: 'Dexter Collins', E: 'Dexter Hammond' },
    options_tr: { A: 'Dexter Bennett', B: 'Dexter Warren', C: 'Dexter Morgan', D: 'Dexter Collins', E: 'Dexter Hammond' },
    answer: 'C',
    explanation: 'Dexter Morgan (played by Michael C. Hall) is a blood spatter analyst for Miami Metro PD who secretly kills murderers.',
  },
  {
    id: 'cin_73',
    text: 'Which franchise includes films set in the fictional country of Wakanda?',
    text_tr: 'Kurgusal Wakanda ülkesinde geçen filmleri içeren yapım hangisidir?',
    options: { A: 'X-Men', B: 'The Avengers', C: 'Black Panther (MCU)', D: 'Justice League', E: 'Fantastic Four' },
    options_tr: { A: 'X-Men', B: 'Yenilmezler', C: 'Black Panther (MCU)', D: 'Adalet Birliği', E: 'Fantastik Dörtlü' },
    answer: 'C',
    explanation: 'Wakanda is the fictional African nation featured in Marvel\'s Black Panther (2018), the first MCU film to win multiple Oscars.',
  },
  {
    id: 'cin_74',
    text: 'Which show features the theme song "The Rains of Castamere"?',
    text_tr: '"Castamere\'nin Yağmurları" temasının yer aldığı dizi hangisidir?',
    options: { A: 'The Witcher', B: 'Vikings', C: 'Game of Thrones', D: 'Marco Polo', E: 'Knightfall' },
    options_tr: { A: 'Büyücü', B: 'Vikingler', C: 'Game of Thrones', D: 'Marco Polo', E: 'Şövalye Düşüşü' },
    answer: 'C',
    explanation: '"The Rains of Castamere" is a piece of in-world music in Game of Thrones that symbolizes the Lannisters\' dominance.',
  },
  {
    id: 'cin_75',
    text: 'Which 2001 film directed by Ridley Scott depicts the Battle of Mogadishu?',
    text_tr: 'Ridley Scott\'ın yönettiği 2001 yapımı hangi film Mogadişu Muharebesi\'ni anlatmaktadır?',
    options: { A: 'Saving Private Ryan', B: 'Lone Survivor', C: 'Black Hawk Down', D: 'We Were Soldiers', E: 'Jarhead' },
    options_tr: { A: 'Er Ryan\'ı Kurtarmak', B: 'Tek Hayatta Kalan', C: 'Kara Şahin Düşüyor', D: 'Asker Olmuştuk', E: 'Jarhead' },
    answer: 'C',
    explanation: 'Black Hawk Down (2001) depicts the 1993 Battle of Mogadishu, in which two US Black Hawk helicopters were shot down in Somalia.',
  },
  {
    id: 'cin_76',
    text: 'Which series is a spin-off prequel of "Breaking Bad," following the early career of lawyer Saul Goodman?',
    text_tr: '"Breaking Bad"in önceki dönemi anlatan, avukat Saul Goodman\'ın kariyer başlangıcını konu alan spin-off dizisi hangisidir?',
    options: { A: 'The Lawyers', B: 'Better Call Saul', C: 'Saul\'s World', D: 'The Counselor', E: 'Criminal Minds' },
    options_tr: { A: 'Avukatlar', B: 'Daha İyi Çağır Saul\'u', C: 'Saul\'un Dünyası', D: 'Danışman', E: 'Suç Zihinleri' },
    answer: 'B',
    explanation: 'Better Call Saul (AMC, 2015–2022) is the prequel/sequel to Breaking Bad, following Jimmy McGill\'s transformation into Saul Goodman.',
  },
  {
    id: 'cin_77',
    text: 'In which film does Tom Hanks play a man stranded on a desert island for four years?',
    text_tr: 'Tom Hanks\'in dört yıl boyunca ıssız bir adada mahsur kalan adamı canlandırdığı film hangisidir?',
    options: { A: 'The Terminal', B: 'Cast Away', C: 'Joe Versus the Volcano', D: 'The Green Mile', E: 'Big' },
    options_tr: { A: 'Terminal', B: 'Issız Ada', C: 'Joe Volkanla Savaşıyor', D: 'Yeşil Yol', E: 'Büyük' },
    answer: 'B',
    explanation: 'In Cast Away (2000, dir. Robert Zemeckis), Tom Hanks plays FedEx employee Chuck Noland stranded on an uninhabited island.',
  },
  {
    id: 'cin_78',
    text: 'Which series created by David Lynch is set in the fictional small town of Twin Peaks, Washington?',
    text_tr: 'David Lynch\'in yarattığı, kurgusal Twin Peaks, Washington kasabasında geçen dizi hangisidir?',
    options: { A: 'Northern Exposure', B: 'Twin Peaks', C: 'Wayward Pines', D: 'American Gothic', E: 'Picket Fences' },
    options_tr: { A: 'Kuzey Açılımı', B: 'Twin Peaks', C: 'Serseri Çamlar', D: 'Amerikan Gotik', E: 'Picket Fences' },
    answer: 'B',
    explanation: 'Twin Peaks (1990–1991, 2017) was created by David Lynch and Mark Frost; it became famous for surreal storytelling and "Who killed Laura Palmer?"',
  },
  {
    id: 'cin_79',
    text: 'What does "CGI" stand for in filmmaking?',
    text_tr: 'Filmcilikte "CGI" kısaltması neyi ifade eder?',
    options: { A: 'Computer Generated Imagery', B: 'Creative Graphic Illustration', C: 'Cinematic Graphics Interface', D: 'Composite Generated Images', E: 'Computer Graphics Integration' },
    options_tr: { A: 'Bilgisayar Üretimi Görüntü', B: 'Yaratıcı Grafik İllüstrasyon', C: 'Sinematik Grafik Arayüzü', D: 'Bileşik Üretilmiş Görüntüler', E: 'Bilgisayar Grafikleri Entegrasyonu' },
    answer: 'A',
    explanation: 'CGI (Computer Generated Imagery) refers to the use of computer graphics to create visual effects in film, TV, and other media.',
  },
  {
    id: 'cin_80',
    text: 'Which Disney+ series acts as a spin-off/sequel to "The Mandalorian," following the Jedi Ahsoka Tano?',
    text_tr: 'Jedi Ahsoka Tano\'yu konu alan hangi Disney+ dizisi "The Mandalorian"ın spin-off/devamı niteliği taşımaktadır?',
    options: { A: 'The Book of Boba Fett', B: 'Obi-Wan Kenobi', C: 'Andor', D: 'Ahsoka', E: 'Skeleton Crew' },
    options_tr: { A: 'Boba Fett\'in Kitabı', B: 'Obi-Wan Kenobi', C: 'Andor', D: 'Ahsoka', E: 'İskelet Ekibi' },
    answer: 'D',
    explanation: 'Ahsoka (2023) stars Rosario Dawson as Ahsoka Tano and serves as a live-action continuation following her appearances in The Mandalorian.',
  },
  {
    id: 'cin_81',
    text: 'Which classic 1986 action film features the quote "I\'ll be back" by a different actor?',
    text_tr: 'Hangi 1986 yapımı klasik aksiyon filminde başka bir aktörün "I\'ll be back" repliği vardır?',
    options: { A: 'Alien', B: 'Predator', C: 'Die Hard', D: 'Lethal Weapon', E: 'Top Gun' },
    options_tr: { A: 'Yaratık', B: 'Avcı', C: 'Zor Ölüm', D: 'Ölümcül Silah', E: 'Top Gun' },
    answer: 'B',
    explanation: 'Actually this is a trick — the "I\'ll be back" quote originates from The Terminator (1984). Predator (1987) starred Schwarzenegger but didn\'t use that line.',
  },
  {
    id: 'cin_82',
    text: 'Who voices the character Woody in "Toy Story"?',
    text_tr: '"Oyuncak Hikayesi" filminde Woody\'nin sesini kim verir?',
    options: { A: 'Billy Crystal', B: 'John Goodman', C: 'Tom Hanks', D: 'Tim Allen', E: 'Bill Murray' },
    options_tr: { A: 'Billy Crystal', B: 'John Goodman', C: 'Tom Hanks', D: 'Tim Allen', E: 'Bill Murray' },
    answer: 'C',
    explanation: 'Tom Hanks has voiced Woody in all four Toy Story films (1995, 1999, 2010, 2019).',
  },
  {
    id: 'cin_83',
    text: 'Which South Korean series became the most-watched non-English Netflix show in 2021?',
    text_tr: '2021\'de Netflix\'te en çok izlenen İngilizce olmayan dizi hangi Güney Kore yapımıdır?',
    options: { A: 'Sweet Home', B: 'All of Us Are Dead', C: 'Squid Game', D: 'Kingdom', E: 'Hellbound' },
    options_tr: { A: 'Tatlı Yurt', B: 'Hepimiz Ölüyüz', C: 'Squid Game', D: 'Krallık', E: 'Cehennem' },
    answer: 'C',
    explanation: 'Squid Game (2021) became Netflix\'s most-watched series ever at the time, viewed in 142 million households in its first four weeks.',
  },
  {
    id: 'cin_84',
    text: 'Which director made the "Lord of the Rings" film trilogy?',
    text_tr: '"Yüzüklerin Efendisi" film üçlemesinin yönetmeni kimdir?',
    options: { A: 'James Cameron', B: 'Steven Spielberg', C: 'Peter Jackson', D: 'Guillermo del Toro', E: 'Sam Raimi' },
    options_tr: { A: 'James Cameron', B: 'Steven Spielberg', C: 'Peter Jackson', D: 'Guillermo del Toro', E: 'Sam Raimi' },
    answer: 'C',
    explanation: 'Peter Jackson directed The Lord of the Rings trilogy (2001–2003), filmed entirely in New Zealand.',
  },
  {
    id: 'cin_85',
    text: 'In "Peaky Blinders," what city is the gang primarily based in?',
    text_tr: '"Peaky Blinders\'da" çete ağırlıklı olarak hangi şehirde faaliyet göstermektedir?',
    options: { A: 'Manchester', B: 'Leeds', C: 'Liverpool', D: 'Birmingham', E: 'London' },
    options_tr: { A: 'Manchester', B: 'Leeds', C: 'Liverpool', D: 'Birmingham', E: 'Londra' },
    answer: 'D',
    explanation: 'Peaky Blinders is set in Birmingham, England, following the Shelby crime family in the aftermath of World War I.',
  },
  {
    id: 'cin_86',
    text: 'Which 2010 Christopher Nolan film features a spinning top as a key plot element?',
    text_tr: 'Christopher Nolan\'ın 2010 yapımı hangi filminde dönen bir topaç önemli bir olay örgüsü unsuru olarak yer alır?',
    options: { A: 'The Prestige', B: 'Memento', C: 'Interstellar', D: 'Inception', E: 'The Dark Knight' },
    options_tr: { A: 'İhtişam', B: 'Hatırla', C: 'Yıldızlararası', D: 'Başlangıç', E: 'Kara Şövalye' },
    answer: 'D',
    explanation: 'In Inception, a spinning top serves as Cobb\'s "totem" to distinguish dreams from reality — its final spin is the film\'s famous ambiguous ending.',
  },
  {
    id: 'cin_87',
    text: 'Which streaming platform premiered "The Witcher" series starring Henry Cavill?',
    text_tr: 'Henry Cavill\'in oynadığı "The Witcher" dizisi hangi platformda yayınlanmaya başladı?',
    options: { A: 'HBO Max', B: 'Amazon Prime Video', C: 'Netflix', D: 'Paramount+', E: 'Peacock' },
    options_tr: { A: 'HBO Max', B: 'Amazon Prime Video', C: 'Netflix', D: 'Paramount+', E: 'Peacock' },
    answer: 'C',
    explanation: 'The Witcher premiered on Netflix on December 20, 2019, based on Polish author Andrzej Sapkowski\'s fantasy novel series.',
  },
  {
    id: 'cin_88',
    text: 'Who played Tony Montana in "Scarface" (1983)?',
    text_tr: '"Scarface" (1983) filminde Tony Montana rolünü kim canlandırdı?',
    options: { A: 'Robert De Niro', B: 'Al Pacino', C: 'James Caan', D: 'Sylvester Stallone', E: 'Jack Nicholson' },
    options_tr: { A: 'Robert De Niro', B: 'Al Pacino', C: 'James Caan', D: 'Sylvester Stallone', E: 'Jack Nicholson' },
    answer: 'B',
    explanation: 'Al Pacino played Tony Montana in Brian De Palma\'s Scarface (1983), delivering the famous line "Say hello to my little friend!"',
  },
  {
    id: 'cin_89',
    text: 'Which Disney animated film features the song "Let It Go"?',
    text_tr: 'Hangi Disney animasyon filminde "Let It Go" şarkısı yer almaktadır?',
    options: { A: 'Tangled', B: 'Moana', C: 'Frozen', D: 'Brave', E: 'The Little Mermaid' },
    options_tr: { A: 'Rapunzel', B: 'Moana', C: 'Frozen', D: 'Cesur', E: 'Küçük Deniz Kızı' },
    answer: 'C',
    explanation: '"Let It Go" is performed by Idina Menzel as Elsa in Frozen (2013); it won the Academy Award for Best Original Song.',
  },
  {
    id: 'cin_90',
    text: 'Which 1999 film features a character who realizes he is living in a simulated reality?',
    text_tr: 'Hangi 1999 yapımı filmde bir karakter simüle edilmiş bir gerçeklikte yaşadığını fark eder?',
    options: { A: 'Dark City', B: 'eXistenZ', C: 'The Thirteenth Floor', D: 'The Matrix', E: 'Vanilla Sky' },
    options_tr: { A: 'Karanlık Şehir', B: 'eXistenZ', C: 'On Üçüncü Kat', D: 'Matrix', E: 'Vanilya Gökyüzü' },
    answer: 'D',
    explanation: 'The Matrix (1999, dir. Wachowski Sisters) follows Neo\'s discovery that reality is a simulation controlled by machines.',
  },
  {
    id: 'cin_91',
    text: 'In "The Walking Dead," what is the name of the villain who wields a barbed-wire bat?',
    text_tr: '"The Walking Dead"de dikenli teli olan beysbol sopasını kullanan kötü adamın adı nedir?',
    options: { A: 'The Governor', B: 'Alpha', C: 'Beta', D: 'Negan', E: 'Simon' },
    options_tr: { A: 'Vali', B: 'Alpha', C: 'Beta', D: 'Negan', E: 'Simon' },
    answer: 'D',
    explanation: 'Negan (Jeffrey Dean Morgan) is the main antagonist of The Walking Dead Seasons 6–8, wielding a barbed-wire bat he calls "Lucille."',
  },
  {
    id: 'cin_92',
    text: 'Which country produced the film "Roma" (2018) directed by Alfonso Cuarón?',
    text_tr: 'Alfonso Cuarón\'un yönettiği "Roma" (2018) filmi hangi ülkede çekilmiştir?',
    options: { A: 'Spain', B: 'Argentina', C: 'Italy', D: 'Mexico', E: 'Brazil' },
    options_tr: { A: 'İspanya', B: 'Arjantin', C: 'İtalya', D: 'Meksika', E: 'Brezilya' },
    answer: 'D',
    explanation: 'Roma is a Mexican Spanish-language film set in 1970s Mexico City; it won 3 Oscars including Best Director and Best Foreign Language Film.',
  },
  {
    id: 'cin_93',
    text: 'Which series is set in a post-apocalyptic world overrun by fungal zombies?',
    text_tr: 'Hangi dizi mantar zombilerin istila ettiği kıyamet sonrası bir dünyada geçmektedir?',
    options: { A: 'The Walking Dead', B: 'Fear the Walking Dead', C: 'Z Nation', D: 'The Last of Us', E: '28 Days Later' },
    options_tr: { A: 'Yürüyen Ölüler', B: 'Yürüyen Ölülerden Kork', C: 'Z Ulusu', D: 'The Last of Us', E: '28 Gün Sonra' },
    answer: 'D',
    explanation: 'The Last of Us (HBO, 2023) is based on the video game, featuring a Cordyceps fungal pandemic that turns people into infected creatures.',
  },
  {
    id: 'cin_94',
    text: 'Which Turkish director made the film "Head-On" (Gegen die Wand) that won the Golden Bear at the 2004 Berlinale?',
    text_tr: '2004 Berlinale\'de Altın Ayı kazanan "Duvara Karşı" filmini hangi Türk yönetmen çekmiştir?',
    options: { A: 'Nuri Bilge Ceylan', B: 'Ferzan Özpetek', C: 'Fatih Akın', D: 'Derviş Zaim', E: 'Semih Kaplanoğlu' },
    options_tr: { A: 'Nuri Bilge Ceylan', B: 'Ferzan Özpetek', C: 'Fatih Akın', D: 'Derviş Zaim', E: 'Semih Kaplanoğlu' },
    answer: 'C',
    explanation: 'Fatih Akın\'s "Gegen die Wand" (Head-On / Duvara Karşı) won the Golden Bear at the 54th Berlin International Film Festival in 2004.',
  },
  {
    id: 'cin_95',
    text: 'What is the first Marvel Cinematic Universe film, released in 2008?',
    text_tr: '2008\'de yayımlanan ilk Marvel Sinematik Evreni filmi hangisidir?',
    options: { A: 'Thor', B: 'Captain America: The First Avenger', C: 'Iron Man', D: 'The Incredible Hulk', E: 'Avengers' },
    options_tr: { A: 'Thor', B: 'Kaptan Amerika: İlk Yenilmez', C: 'Demir Adam', D: 'İnanılmaz Hulk', E: 'Yenilmezler' },
    answer: 'C',
    explanation: 'Iron Man (2008) was the first film released in the MCU, directed by Jon Favreau and starring Robert Downey Jr.',
  },
  {
    id: 'cin_96',
    text: 'Which HBO series is based on George R.R. Martin\'s prequel story about House Targaryen?',
    text_tr: 'Hangi HBO dizisi George R.R. Martin\'in Targaryen Hanesi hakkındaki ön hikayesine dayanmaktadır?',
    options: { A: 'Rings of Power', B: 'House of the Dragon', C: 'Bloodmoon', D: 'The Long Night', E: 'Fire & Blood' },
    options_tr: { A: 'Güç Yüzükleri', B: 'Ejderha Evi', C: 'Kanlı Ay', D: 'Uzun Gece', E: 'Ateş ve Kan' },
    answer: 'B',
    explanation: 'House of the Dragon (HBO, 2022–present) is based on Martin\'s "Fire & Blood" and serves as a prequel to Game of Thrones.',
  },
  {
    id: 'cin_97',
    text: 'Which actor played James Bond in "Casino Royale" (2006)?',
    text_tr: '"Casino Royale" (2006) filminde James Bond rolünü hangi aktör canlandırdı?',
    options: { A: 'Pierce Brosnan', B: 'Roger Moore', C: 'Sean Connery', D: 'Daniel Craig', E: 'Timothy Dalton' },
    options_tr: { A: 'Pierce Brosnan', B: 'Roger Moore', C: 'Sean Connery', D: 'Daniel Craig', E: 'Timothy Dalton' },
    answer: 'D',
    explanation: 'Daniel Craig debuted as James Bond in Casino Royale (2006) and played the role through No Time to Die (2021).',
  },
  {
    id: 'cin_98',
    text: 'Which 2023 film based on a toy brand starred Margot Robbie and Ryan Gosling?',
    text_tr: 'Margot Robbie ve Ryan Gosling\'in oynadığı, bir oyuncak markasına dayanan 2023 yapımı film hangisidir?',
    options: { A: 'Ken', B: 'Toy Story 5', C: 'Barbie', D: 'GI Joe', E: 'Mattel' },
    options_tr: { A: 'Ken', B: 'Oyuncak Hikayesi 5', C: 'Barbie', D: 'GI Joe', E: 'Mattel' },
    answer: 'C',
    explanation: 'Barbie (2023, dir. Greta Gerwig) grossed over $1.4 billion worldwide, becoming the highest-grossing film directed by a woman.',
  },
  {
    id: 'cin_99',
    text: 'In "How I Met Your Mother," who narrates the story to his children?',
    text_tr: '"How I Met Your Mother"da çocuklarına hikayeyi anlatan karakter kimdir?',
    options: { A: 'Marshall Eriksen', B: 'Barney Stinson', C: 'Ted Mosby', D: 'Robin Scherbatsky', E: 'Lily Aldrin' },
    options_tr: { A: 'Marshall Eriksen', B: 'Barney Stinson', C: 'Ted Mosby', D: 'Robin Scherbatsky', E: 'Lily Aldrin' },
    answer: 'C',
    explanation: 'Ted Mosby (played by Josh Radnor, voiced in narration by Bob Saget) tells his children the story of how he met their mother.',
  },
  {
    id: 'cin_100',
    text: 'Which Ridley Scott film depicts the story of Maximus, a Roman general turned gladiator?',
    text_tr: 'Hangi Ridley Scott filmi gladyatöre dönüşen Romalı general Maximus\'un hikayesini anlatmaktadır?',
    options: { A: 'Kingdom of Heaven', B: '300', C: 'Troy', D: 'Gladiator', E: 'Ben-Hur' },
    options_tr: { A: 'Cennetin Krallığı', B: '300', C: 'Truva', D: 'Gladyatör', E: 'Ben-Hur' },
    answer: 'D',
    explanation: 'Gladiator (2000) won Best Picture and Best Actor (Russell Crowe) at the 73rd Academy Awards.',
  },
];

module.exports = { cinema };
