'use strict';

const games = [
  {
    id: 'game_01',
    text: 'Which video game is officially recognized as the best-selling video game of all time?',
    text_tr: 'Resmi olarak tüm zamanların en çok satan video oyunu hangisidir?',
    options: { A: 'Grand Theft Auto V', B: 'Tetris', C: 'Minecraft', D: 'Wii Sports', E: 'PUBG: Battlegrounds' },
    options_tr: { A: 'Grand Theft Auto V', B: 'Tetris', C: 'Minecraft', D: 'Wii Sports', E: 'PUBG: Battlegrounds' },
    answer: 'C',
    explanation: 'Minecraft is the best-selling video game of all time, with over 300 million copies sold across all platforms.',
  },
  {
    id: 'game_02',
    text: 'What is the name of the main protagonist in "The Legend of Zelda" series?',
    text_tr: '"The Legend of Zelda" serisindeki ana kahramanın adı nedir?',
    options: { A: 'Zelda', B: 'Link', C: 'Ganon', D: 'Mario', E: 'Luigi' },
    options_tr: { A: 'Zelda', B: 'Link', C: 'Ganon', D: 'Mario', E: 'Luigi' },
    answer: 'B',
    explanation: 'The main protagonist controlled by the player is Link; Princess Zelda is the character he often has to save.',
  },
  {
    id: 'game_03',
    text: 'Which company developed the classic arcade game "Pac-Man", released in 1980?',
    text_tr: '1980 yılında piyasaya sürülen klasik atari oyunu "Pac-Man"i hangi şirket geliştirmiştir?',
    options: { A: 'Nintendo', B: 'Sega', C: 'Namco', D: 'Capcom', E: 'Konami' },
    options_tr: { A: 'Nintendo', B: 'Sega', C: 'Namco', D: 'Capcom', E: 'Konami' },
    answer: 'C',
    explanation: 'Pac-Man was developed by Namco (now Bandai Namco Entertainment) and created by Toru Iwatani.',
  },
  {
    id: 'game_04',
    text: 'In the game "Portal", what delicious item is famously promised to the player but turns out to be a lie?',
    text_tr: '"Portal" oyununda oyuncuya söz verilen ancak sonradan yalan olduğu ortaya çıkan meşhur lezzet nedir?',
    options: { A: 'Pie', B: 'Ice Cream', C: 'Cake', D: 'Donut', E: 'Pizza' },
    options_tr: { A: 'Turta', B: 'Dondurma', C: 'Pasta', D: 'Donut', E: 'Pizza' },
    answer: 'C',
    explanation: 'The phrase "The cake is a lie" became a massive internet meme after the release of Valve\'s Portal.',
  },
  {
    id: 'game_05',
    text: 'Which gaming console is the best-selling home console of all time?',
    text_tr: 'Tüm zamanların en çok satan ev konsolu hangisidir?',
    options: { A: 'Nintendo Switch', B: 'PlayStation 2', C: 'PlayStation 4', D: 'Xbox 360', E: 'Nintendo Wii' },
    options_tr: { A: 'Nintendo Switch', B: 'PlayStation 2', C: 'PlayStation 4', D: 'Xbox 360', E: 'Nintendo Wii' },
    answer: 'B',
    explanation: 'Sony\'s PlayStation 2, released in 2000, has sold over 155 million units worldwide.',
  },
  {
    id: 'game_06',
    text: 'What is the name of the fictional city where "Grand Theft Auto: San Andreas" primarily begins?',
    text_tr: '"Grand Theft Auto: San Andreas" oyununun temel olarak başladığı kurgusal şehrin adı nedir?',
    options: { A: 'Liberty City', B: 'Vice City', C: 'Los Santos', D: 'San Fierro', E: 'Las Venturas' },
    options_tr: { A: 'Liberty City', B: 'Vice City', C: 'Los Santos', D: 'San Fierro', E: 'Las Venturas' },
    answer: 'C',
    explanation: 'The story of Carl "CJ" Johnson begins in Los Santos, which is based on Los Angeles.',
  },
  {
    id: 'game_07',
    text: 'Which popular battle royale game features locations like "Tilted Towers" and "Pleasant Park"?',
    text_tr: 'Hangi popüler battle royale oyunu "Tilted Towers" ve "Pleasant Park" gibi konumlara sahiptir?',
    options: { A: 'PUBG', B: 'Apex Legends', C: 'Call of Duty: Warzone', D: 'Fortnite', E: 'Free Fire' },
    options_tr: { A: 'PUBG', B: 'Apex Legends', C: 'Call of Duty: Warzone', D: 'Fortnite', E: 'Free Fire' },
    answer: 'D',
    explanation: 'These are classic point-of-interest names from Epic Games\' Fortnite Battle Royale map.',
  },
  {
    id: 'game_08',
    text: 'What is the name of Mario\'s loyal dinosaur companion in the Nintendo franchise?',
    text_tr: 'Nintendo evreninde Mario\'nun sadık dinozor arkadaşının adı nedir?',
    options: { A: 'Bowser', B: 'Toad', C: 'Yoshi', D: 'Donkey Kong', E: 'Wario' },
    options_tr: { A: 'Bowser', B: 'Toad', C: 'Yoshi', D: 'Donkey Kong', E: 'Wario' },
    answer: 'C',
    explanation: 'Yoshi first appeared in Super Mario World (1990) and serves as Mario\'s mount and companion.',
  },
  {
    id: 'game_09',
    text: 'Which online digital distribution platform for PC gaming was launched by Valve in 2003?',
    text_tr: 'Valve tarafından 2003 yılında PC oyunları için piyasaya sürülen çevrimiçi dijital dağıtım platformu hangisidir?',
    options: { A: 'Epic Games Store', B: 'Origin', C: 'Steam', D: 'Uplay', E: 'GOG Galaxy' },
    options_tr: { A: 'Epic Games Store', B: 'Origin', C: 'Steam', D: 'Uplay', E: 'GOG Galaxy' },
    answer: 'C',
    explanation: 'Steam was initially created by Valve to provide automatic updates for their games, eventually becoming the largest PC store.',
  },
  {
    id: 'game_10',
    text: 'Who is the main protagonist of the "God of War" series?',
    text_tr: '"God of War" serisinin ana karakteri kimdir?',
    options: { A: 'Zeus', B: 'Atreus', C: 'Kratos', D: 'Ares', E: 'Thor' },
    options_tr: { A: 'Zeus', B: 'Atreus', C: 'Kratos', D: 'Ares', E: 'Thor' },
    answer: 'C',
    explanation: 'Kratos is a Spartan warrior who battles Greek and later Norse gods throughout the franchise.',
  },
  {
    id: 'game_11',
    text: 'In competitive gaming, what does the acronym "FPS" usually stand for (as a game genre)?',
    text_tr: 'Rekabetçi oyunculukta "FPS" kısaltması oyun türü olarak genellikle ne anlama gelir?',
    options: { A: 'First Person Shooter', B: 'Frames Per Second', C: 'Fast Paced Strategy', D: 'Free Play System', E: 'Final Point Score' },
    options_tr: { A: 'Birinci Şahıs Nişancı', B: 'Saniyedeki Kare Sayısı', C: 'Fast Paced Strategy', D: 'Free Play System', E: 'Final Point Score' },
    answer: 'A',
    explanation: 'While FPS also means Frames Per Second in graphics, as a game genre it stands for First Person Shooter.',
  },
  {
    id: 'game_12',
    text: 'Which game studio is responsible for developing "The Witcher 3: Wild Hunt" and "Cyberpunk 2077"?',
    text_tr: '"The Witcher 3: Wild Hunt" ve "Cyberpunk 2077" oyunlarını geliştiren stüdyo hangisidir?',
    options: { A: 'Bethesda', B: 'BioWare', C: 'CD Projekt Red', D: 'Ubisoft', E: 'Rockstar Games' },
    options_tr: { A: 'Bethesda', B: 'BioWare', C: 'CD Projekt Red', D: 'Ubisoft', E: 'Rockstar Games' },
    answer: 'C',
    explanation: 'CD Projekt Red is a Polish video game development studio founded in 2002.',
  },
  {
    id: 'game_13',
    text: 'What traditional board game requires players to capture the opponent\'s king to win?',
    text_tr: 'Hangi geleneksel masa oyununda kazanmak için rakibin şahını ele geçirmek gerekir?',
    options: { A: 'Checkers', B: 'Chess', C: 'Backgammon', D: 'Go', E: 'Monopoly' },
    options_tr: { A: 'Dama', B: 'Satranç', C: 'Tavla', D: 'Go', E: 'Monopoly' },
    answer: 'B',
    explanation: 'In Chess, putting the opponent\'s king into an inescapable position is called "checkmate" and ends the game.',
  },
  {
    id: 'game_14',
    text: 'What is the name of the master assassin protagonist in the original "Assassin\'s Creed" game?',
    text_tr: 'Orijinal "Assassin\'s Creed" oyunundaki usta suikastçı başkarakterin adı nedir?',
    options: { A: 'Ezio Auditore', B: 'Altaïr Ibn-La\'Ahad', C: 'Connor Kenway', D: 'Edward Kenway', E: 'Bayek' },
    options_tr: { A: 'Ezio Auditore', B: 'Altaïr Ibn-La\'Ahad', C: 'Connor Kenway', D: 'Edward Kenway', E: 'Bayek' },
    answer: 'B',
    explanation: 'Altaïr Ibn-La\'Ahad was the protagonist of the first game, set during the Third Crusade.',
  },
  {
    id: 'game_15',
    text: 'Which blocky entity in Minecraft is famous for sneaking up on players and exploding?',
    text_tr: 'Minecraft\'ta oyunculara çaktırmadan yaklaşıp patlamasıyla ünlü olan blok yapılı yaratık hangisidir?',
    options: { A: 'Zombie', B: 'Skeleton', C: 'Creeper', D: 'Enderman', E: 'Spider' },
    options_tr: { A: 'Zombi', B: 'İskelet', C: 'Creeper', D: 'Enderman', E: 'Örümcek' },
    answer: 'C',
    explanation: 'The Creeper is an iconic, silent Minecraft monster that detonates when close to the player.',
  },
  {
    id: 'game_16',
    text: 'What is the highest tier rank achievable in competitive "League of Legends"?',
    text_tr: 'Rekabetçi "League of Legends" oyununda ulaşılabilecek en yüksek lig hangisidir?',
    options: { A: 'Diamond', B: 'Master', C: 'Grandmaster', D: 'Challenger', E: 'Immortal' },
    options_tr: { A: 'Elmas (Diamond)', B: 'Ustalık (Master)', C: 'Üstatlık (Grandmaster)', D: 'Şampiyonluk (Challenger)', E: 'Ölümsüz (Immortal)' },
    answer: 'D',
    explanation: 'Challenger is the elite tier representing the absolute top percentage of players in each region.',
  },
  {
    id: 'game_17',
    text: 'Which esports game genre do "Dota 2" and "League of Legends" belong to?',
    text_tr: '"Dota 2" ve "League of Legends" hangi e-spor oyun türüne aittir?',
    options: { A: 'RTS', B: 'MMORPG', C: 'MOBA', D: 'FPS', E: 'RPG' },
    options_tr: { A: 'RTS', B: 'MMORPG', C: 'MOBA', D: 'FPS', E: 'RPG' },
    answer: 'C',
    explanation: 'MOBA stands for Multiplayer Online Battle Arena.',
  },
  {
    id: 'game_18',
    text: 'What year was the original Sony PlayStation launched in Japan?',
    text_tr: 'Orijinal Sony PlayStation, Japonya\'da hangi yılda piyasaya sürülmüştür?',
    options: { A: '1990', B: '1992', C: '1994', D: '1996', E: '1998' },
    options_tr: { A: '1990', B: '1992', C: '1994', D: '1996', E: '1998' },
    answer: 'C',
    explanation: 'The original PlayStation was released in Japan on December 3, 1994.',
  },
  {
    id: 'game_19',
    text: 'Which fighting game franchise features characters like Sub-Zero, Scorpion, and Raiden?',
    text_tr: 'Sub-Zero, Scorpion ve Raiden gibi karakterleri barındıran dövüş oyunu serisi hangisidir?',
    options: { A: 'Street Fighter', B: 'Tekken', C: 'Mortal Kombat', D: 'Soulcalibur', E: 'Super Smash Bros.' },
    options_tr: { A: 'Street Fighter', B: 'Tekken', C: 'Mortal Kombat', D: 'Soulcalibur', E: 'Super Smash Bros.' },
    answer: 'C',
    explanation: 'Mortal Kombat is highly famous for these characters and its signature "Fatality" finishing moves.',
  },
  {
    id: 'game_20',
    text: 'What is the full name of the protagonist "Master Chief" in the Halo franchise?',
    text_tr: 'Halo serisindeki "Master Chief" karakterinin tam adı nedir?',
    options: { A: 'John-117', B: 'James-007', C: 'Marcus Fenix', D: 'Arthur Morgan', E: 'Solid Snake' },
    options_tr: { A: 'John-117', B: 'James-007', C: 'Marcus Fenix', D: 'Arthur Morgan', E: 'Solid Snake' },
    answer: 'A',
    explanation: 'Master Chief\'s military designation and name is John-117.',
  },
  {
    id: 'game_21',
    text: 'Which board game is centered around buying, trading, and developing properties to bankrupt opponents?',
    text_tr: 'Rakipleri iflas ettirmek için mülk satın alma, ticaret yapma ve geliştirme üzerine kurulu masa oyunu hangisidir?',
    options: { A: 'Catan', B: 'Risk', C: 'Monopoly', D: 'Scrabble', E: 'Clue' },
    options_tr: { A: 'Catan', B: 'Risk', C: 'Monopoly', D: 'Scrabble', E: 'Clue' },
    answer: 'C',
    explanation: 'Monopoly originated in the US and is named after the economic concept of a monopoly.',
  },
  {
    id: 'game_22',
    text: 'In "The Witcher" series, what is the name of Geralt\'s adoptive daughter who possesses Elder Blood?',
    text_tr: '"The Witcher" serisinde Geralt\'ın Kadim Kan\'a sahip evlatlık kızının adı nedir?',
    options: { A: 'Yennefer', B: 'Triss', C: 'Ciri', D: 'Vesemir', E: 'Shani' },
    options_tr: { A: 'Yennefer', B: 'Triss', C: 'Ciri', D: 'Vesemir', E: 'Shani' },
    answer: 'C',
    explanation: 'Cirilla Fiona Elen Riannon, known as Ciri, is a central figure in the Witcher plot.',
  },
  {
    id: 'game_23',
    text: 'Which legendary game creator designed "Metal Gear Solid" and founded Kojima Productions?',
    text_tr: '"Metal Gear Solid" oyununu tasarlayan ve Kojima Productions\'ı kuran efsanevi oyun yapımcısı kimdir?',
    options: { A: 'Shigeru Miyamoto', B: 'Hideo Kojima', C: 'Gabe Newell', D: 'Todd Howard', E: 'Sid Meier' },
    options_tr: { A: 'Shigeru Miyamoto', B: 'Hideo Kojima', C: 'Gabe Newell', D: 'Todd Howard', E: 'Sid Meier' },
    answer: 'B',
    explanation: 'Hideo Kojima is world-famous for creating the tactical espionage genre with the Metal Gear series.',
  },
  {
    id: 'game_24',
    text: 'What iconic weapon does Gordon Freeman use in the "Half-Life" series?',
    text_tr: '"Half-Life" serisinde Gordon Freeman hangi ikonik silahı/aleti kullanır?',
    options: { A: 'Lightsaber', B: 'Crowbar', C: 'Portal Gun', D: 'Chainsaw', E: 'Katana' },
    options_tr: { A: 'Işın Kılıcı', B: 'Levye (Crowbar)', C: 'Portal Silahı', D: 'Elektrikli Testere', E: 'Katana' },
    answer: 'B',
    explanation: 'The crowbar is Gordon Freeman\'s signature melee weapon throughout the Half-Life games.',
  },
  {
    id: 'game_25',
    text: 'Which company developed the Xbox console brand?',
    text_tr: 'Xbox konsol markasını hangi şirket geliştirmiştir?',
    options: { A: 'Sony', B: 'Nintendo', C: 'Sega', D: 'Microsoft', E: 'Google' },
    options_tr: { A: 'Sony', B: 'Nintendo', C: 'Sega', D: 'Microsoft', E: 'Google' },
    answer: 'D',
    explanation: 'Microsoft entered the home console market with the release of the original Xbox in 2001.',
  },
  {
    id: 'game_26',
    text: 'What is the highest-grossing media franchise in the world, which began as a pair of Game Boy video games?',
    text_tr: 'İlk olarak bir çift Game Boy video oyunu olarak başlayan ve dünyadaki en çok hasılat yapan medya serisi hangisidir?',
    options: { A: 'Star Wars', B: 'Marvel Cinematic Universe', C: 'Pokémon', D: 'Super Mario', E: 'Call of Duty' },
    options_tr: { A: 'Star Wars', B: 'Marvel Sinematik Evreni', C: 'Pokémon', D: 'Super Mario', E: 'Call of Duty' },
    answer: 'C',
    explanation: 'Pokémon began in Japan in 1996 as Pokémon Red and Green for the Nintendo Game Boy.',
  },
  {
    id: 'game_27',
    text: 'In "World of Warcraft", what are the two primary opposing factions?',
    text_tr: '"World of Warcraft" oyununda iki ana rakip taraf (fraksiyon) hangisidir?',
    options: { A: 'Jedi vs Sith', B: 'Alliance vs Horde', C: 'Autobots vs Decepticons', D: 'Terrorists vs Counter-Terrorists', E: 'Red vs Blue' },
    options_tr: { A: 'Jedi vs Sith', B: 'Alliance vs Horde', C: 'Autobots vs Decepticons', D: 'Terörist vs Anti-Terörist', E: 'Kırmızı vs Mavi' },
    answer: 'B',
    explanation: 'The lore of Warcraft heavily focuses on the perpetual conflict between the Alliance and the Horde.',
  },
  {
    id: 'game_28',
    text: 'Which horror video game franchise takes place in a town shrouded in fog and features a monster named Pyramid Head?',
    text_tr: 'Hangi korku oyunu serisi sislerle kaplı bir kasabada geçer ve Pyramid Head isimli bir canavara sahiptir?',
    options: { A: 'Resident Evil', B: 'Silent Hill', C: 'Dead Space', D: 'Outlast', E: 'Amnesia' },
    options_tr: { A: 'Resident Evil', B: 'Silent Hill', C: 'Dead Space', D: 'Outlast', E: 'Amnesia' },
    answer: 'B',
    explanation: 'Silent Hill is Konami\'s psychological horror franchise, with Pyramid Head debuting in Silent Hill 2.',
  },
  {
    id: 'game_29',
    text: 'What was the first commercially successful video game, released by Atari in 1972?',
    text_tr: 'Atari tarafından 1972\'de çıkarılan ve ticari olarak başarılı ilk video oyunu hangisidir?',
    options: { A: 'Space Invaders', B: 'Asteroids', C: 'Pong', D: 'Galaga', E: 'Frogger' },
    options_tr: { A: 'Space Invaders', B: 'Asteroids', C: 'Pong', D: 'Galaga', E: 'Frogger' },
    answer: 'C',
    explanation: 'Pong is a simple 2D tennis sports game that helped establish the video game industry.',
  },
  {
    id: 'game_30',
    text: 'Which game won the "Game of the Year" award at The Game Awards 2023?',
    text_tr: 'The Game Awards 2023 etkinliğinde "Yılın Oyunu" ödülünü hangi oyun kazanmıştır?',
    options: { A: 'Elden Ring', B: 'The Legend of Zelda: Tears of the Kingdom', C: 'Baldur\'s Gate 3', D: 'Marvel\'s Spider-Man 2', E: 'Alan Wake 2' },
    options_tr: { A: 'Elden Ring', B: 'The Legend of Zelda: Tears of the Kingdom', C: 'Baldur\'s Gate 3', D: 'Marvel\'s Spider-Man 2', E: 'Alan Wake 2' },
    answer: 'C',
    explanation: 'Baldur\'s Gate 3, developed by Larian Studios, dominated the awards in 2023, including GOTY.',
  },
  {
    id: 'game_31',
    text: 'What is the name of the main protagonist in the "Tomb Raider" series?',
    text_tr: '"Tomb Raider" serisinin ana kahramanı olan kadın karakterin adı nedir?',
    options: { A: 'Jill Valentine', B: 'Lara Croft', C: 'Samus Aran', D: 'Elena Fisher', E: 'Chloe Frazer' },
    options_tr: { A: 'Jill Valentine', B: 'Lara Croft', C: 'Samus Aran', D: 'Elena Fisher', E: 'Chloe Frazer' },
    answer: 'B',
    explanation: 'Lara Croft is an English archaeologist-adventurer created by Core Design.',
  },
  {
    id: 'game_32',
    text: 'Which country is the birthplace of the popular sandbox game "Minecraft"?',
    text_tr: 'Popüler hayatta kalma-sandbox oyunu "Minecraft" hangi ülkede doğmuştur?',
    options: { A: 'United States', B: 'Japan', C: 'Sweden', D: 'Germany', E: 'Canada' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Japonya', C: 'İsveç', D: 'Almanya', E: 'Kanada' },
    answer: 'C',
    explanation: 'Minecraft was created by Swedish developer Markus "Notch" Persson and developed by Mojang Studios.',
  },
  {
    id: 'game_33',
    text: 'What is the primary objective of the board game "Risk"?',
    text_tr: '"Risk" masa oyununun temel amacı nedir?',
    options: { A: 'Solve a murder mystery', B: 'Achieve global domination', C: 'Build the longest road', D: 'Gather 10 victory points', E: 'Collect the most money' },
    options_tr: { A: 'Bir cinayet gizemini çözmek', B: 'Dünyayı tamamen fethetmek', C: 'En uzun yolu inşa etmek', D: '10 zafer puanı toplamak', E: 'En çok parayı biriktirmek' },
    answer: 'B',
    explanation: 'Risk is a game of strategic conquest where players attempt to capture every territory on the map.',
  },
  {
    id: 'game_34',
    text: 'In the game "Among Us", what is the name given to the players whose job is to secretly sabotage and kill the crew?',
    text_tr: '"Among Us" oyununda görevi gizlice sabote etmek ve mürettebatı öldürmek olan oyunculara ne ad verilir?',
    options: { A: 'Traitor', B: 'Spy', C: 'Impostor', D: 'Assassin', E: 'Alien' },
    options_tr: { A: 'Hain', B: 'Casus', C: 'Impostor (Sahtekar)', D: 'Suikastçı', E: 'Uzaylı' },
    answer: 'C',
    explanation: 'The game divides players into "Crewmates" and "Impostors".',
  },
  {
    id: 'game_35',
    text: 'Which famous RPG franchise features a post-apocalyptic world and a mascot character named "Vault Boy"?',
    text_tr: 'Kıyamet sonrası bir dünyayı konu alan ve "Vault Boy" adında bir maskot karaktere sahip olan ünlü RPG serisi hangisidir?',
    options: { A: 'Metro', B: 'S.T.A.L.K.E.R.', C: 'Fallout', D: 'Borderlands', E: 'BioShock' },
    options_tr: { A: 'Metro', B: 'S.T.A.L.K.E.R.', C: 'Fallout', D: 'Borderlands', E: 'BioShock' },
    answer: 'C',
    explanation: 'Vault Boy is the corporate mascot of the Vault-Tec Corporation within the Fallout universe.',
  },
  {
    id: 'game_36',
    text: 'What was the title of the first "Grand Theft Auto" game to shift the franchise to 3D graphics?',
    text_tr: 'Grand Theft Auto serisini 3 boyutlu grafiğe taşıyan ilk oyunun adı nedir?',
    options: { A: 'Grand Theft Auto II', B: 'Grand Theft Auto III', C: 'Grand Theft Auto: Vice City', D: 'Grand Theft Auto IV', E: 'Grand Theft Auto V' },
    options_tr: { A: 'Grand Theft Auto II', B: 'Grand Theft Auto III', C: 'Grand Theft Auto: Vice City', D: 'Grand Theft Auto IV', E: 'Grand Theft Auto V' },
    answer: 'B',
    explanation: 'Released in 2001, GTA III revolutionized the series and open-world gaming by introducing a fully 3D Liberty City.',
  },
  {
    id: 'game_37',
    text: 'Which chess piece is the only one that can move in an "L" shape and jump over other pieces?',
    text_tr: 'Satrançta "L" şeklinde hareket edebilen ve diğer taşların üzerinden atlayabilen tek taş hangisidir?',
    options: { A: 'Rook', B: 'Bishop', C: 'Knight', D: 'Queen', E: 'Pawn' },
    options_tr: { A: 'Kale', B: 'Fil', C: 'At', D: 'Vezir', E: 'Piyon' },
    answer: 'C',
    explanation: 'The Knight moves two squares vertically and one horizontally (or vice versa), tracing an L-shape.',
  },
  {
    id: 'game_38',
    text: 'Which company created the popular tactical shooter game "Valorant"?',
    text_tr: 'Popüler taktiksel nişancı oyunu "Valorant"ı hangi şirket geliştirmiştir?',
    options: { A: 'Valve', B: 'Epic Games', C: 'Riot Games', D: 'Ubisoft', E: 'Blizzard' },
    options_tr: { A: 'Valve', B: 'Epic Games', C: 'Riot Games', D: 'Ubisoft', E: 'Blizzard' },
    answer: 'C',
    explanation: 'Riot Games released Valorant in June 2020, entering the competitive tactical FPS market.',
  },
  {
    id: 'game_39',
    text: 'What is the primary setting for "Red Dead Redemption 2"?',
    text_tr: '"Red Dead Redemption 2" hikayesinin geçtiği ana dönem/ortam hangisidir?',
    options: { A: 'The American Wild West', B: 'Medieval Europe', C: 'World War II', D: 'Futuristic Cyberpunk', E: 'Pirate Age Caribbean' },
    options_tr: { A: 'Amerikan Vahşi Batısı', B: 'Orta Çağ Avrupası', C: 'II. Dünya Savaşı', D: 'Fütüristik Siberpunk', E: 'Korsan Çağı Karayipler' },
    answer: 'A',
    explanation: 'RDR2 is an epic Western game following Arthur Morgan during the decline of the Wild West outlaw era in 1899.',
  },
  {
    id: 'game_40',
    text: 'In the game "Pac-Man", how many ghosts pursue the player around the maze?',
    text_tr: '"Pac-Man" oyununda labirent boyunca oyuncuyu kovalayan kaç adet hayalet vardır?',
    options: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    options_tr: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    answer: 'C',
    explanation: 'There are 4 ghosts named Blinky (red), Pinky (pink), Inky (cyan), and Clyde (orange).',
  },
  {
    id: 'game_41',
    text: 'Which fighting game tournament is widely considered the largest and longest-running in the world?',
    text_tr: 'Dünyadaki en büyük ve en köklü dövüş oyunları turnuvası hangisidir?',
    options: { A: 'The International', B: 'Worlds', C: 'EVO', D: 'Capcom Cup', E: 'DreamHack' },
    options_tr: { A: 'The International', B: 'Worlds', C: 'EVO (Evolution Championship Series)', D: 'Capcom Cup', E: 'DreamHack' },
    answer: 'C',
    explanation: 'EVO (Evolution Championship Series) is an annual esports event focused exclusively on fighting games.',
  },
  {
    id: 'game_42',
    text: 'What is the title of the FromSoftware game released in 2009 that pioneered the "Soulslike" genre?',
    text_tr: 'FromSoftware tarafından 2009\'da çıkarılan ve "Soulslike" tarzının öncüsü kabul edilen oyunun adı nedir?',
    options: { A: 'Bloodborne', B: 'Demon\'s Souls', C: 'Sekiro', D: 'Elden Ring', E: 'King\'s Field' },
    options_tr: { A: 'Bloodborne', B: 'Demon\'s Souls', C: 'Sekiro', D: 'Elden Ring', E: 'King\'s Field' },
    answer: 'B',
    explanation: 'Demon\'s Souls for the PS3 laid down the brutal gameplay foundations for the future Souls franchise.',
  },
  {
    id: 'game_43',
    text: 'In the "Sims" series, what is the fictional language spoken by the characters?',
    text_tr: '"The Sims" serisinde karakterlerin konuştuğu kurgusal dilin adı nedir?',
    options: { A: 'Simlish', B: 'Huttese', C: 'Dothraki', D: 'Elvish', E: 'Gibberish' },
    options_tr: { A: 'Simlish', B: 'Huttese', C: 'Dothraki', D: 'Elvice', E: 'Anlamsız Dil' },
    answer: 'A',
    explanation: 'Simlish is a gibberish language improvised by voice actors so players could interpret emotions without specific dialogue.',
  },
  {
    id: 'game_44',
    text: 'Which puzzle game features falling geometric blocks called "Tetrominoes"?',
    text_tr: '"Tetromino" adı verilen düşen geometrik blokları barındıran efsanevi bulmaca oyunu hangisidir?',
    options: { A: 'Bejeweled', B: 'Candy Crush', C: 'Tetris', D: 'Sudoku', E: 'Lemmings' },
    options_tr: { A: 'Bejeweled', B: 'Candy Crush', C: 'Tetris', D: 'Sudoku', E: 'Lemmings' },
    answer: 'C',
    explanation: 'Tetris was created by Alexey Pajitnov in 1984, named after the Greek numerical prefix "tetra" and tennis.',
  },
  {
    id: 'game_45',
    text: 'What is the name of the protagonist in the "Uncharted" series?',
    text_tr: '"Uncharted" serisinin ana kahramanı kimdir?',
    options: { A: 'Joel Miller', B: 'Nathan Drake', C: 'Sam Fisher', D: 'Solid Snake', E: 'Leon S. Kennedy' },
    options_tr: { A: 'Joel Miller', B: 'Nathan Drake', C: 'Sam Fisher', D: 'Solid Snake', E: 'Leon S. Kennedy' },
    answer: 'B',
    explanation: 'Nathan Drake is a charismatic treasure hunter who travels the world uncovering historical mysteries.',
  },
  {
    id: 'game_46',
    text: 'Which battle royale game was developed as a direct spin-off of the "Titanfall" universe?',
    text_tr: 'Hangi battle royale oyunu doğrudan "Titanfall" evreninin bir yan ürünü (spin-off) olarak geliştirilmiştir?',
    options: { A: 'Hyper Scape', B: 'Apex Legends', C: 'Warzone', D: 'Fortnite', E: 'Realm Royale' },
    options_tr: { A: 'Hyper Scape', B: 'Apex Legends', C: 'Warzone', D: 'Fortnite', E: 'Realm Royale' },
    answer: 'B',
    explanation: 'Apex Legends was developed by Respawn Entertainment and uses many mechanics and lore pieces from Titanfall.',
  },
  {
    id: 'game_47',
    text: 'In "The Last of Us", what type of infection turns humans into aggressive, zombie-like creatures?',
    text_tr: '"The Last of Us" oyununda insanları saldırgan, zombi benzeri yaratıklara dönüştüren enfeksiyon türü hangisidir?',
    options: { A: 'Viral Infection', B: 'Bacterial Infection', C: 'Cordyceps Fungal Infection', D: 'Radiation Sickness', E: 'Alien Parasite' },
    options_tr: { A: 'Virüs Enfeksiyonu', B: 'Bakteri Enfeksiyonu', C: 'Kordiseps Mantar Enfeksiyonu', D: 'Radyasyon Hastalığı', E: 'Uzaylı Paraziti' },
    answer: 'C',
    explanation: 'The game\'s outbreak is caused by a mutated Cordyceps fungus that takes over the human brain.',
  },
  {
    id: 'game_48',
    text: 'Which handheld gaming device, released by Nintendo in 1989, popularized portable gaming?',
    text_tr: 'Nintendo tarafından 1989\'da çıkarılan ve taşınabilir oyunculuğu popülerleştiren el konsolu hangisidir?',
    options: { A: 'Game Boy', B: 'Game Gear', C: 'Nintendo DS', D: 'PSP', E: 'Game & Watch' },
    options_tr: { A: 'Game Boy', B: 'Game Gear', C: 'Nintendo DS', D: 'PSP', E: 'Game & Watch' },
    answer: 'A',
    explanation: 'The original Game Boy featured an 8-bit system and a monochrome screen, becoming a massive global success.',
  },
  {
    id: 'game_49',
    text: 'Which classic Capcom survival horror game takes place in Raccoon City?',
    text_tr: 'Capcom\'un Raccoon City\'de geçen klasik hayatta kalma-korku oyunu serisi hangisidir?',
    options: { A: 'Silent Hill', B: 'Resident Evil', C: 'Dead Rising', D: 'Devil May Cry', E: 'Dino Crisis' },
    options_tr: { A: 'Silent Hill', B: 'Resident Evil', C: 'Dead Rising', D: 'Devil May Cry', E: 'Dino Crisis' },
    answer: 'B',
    explanation: 'Resident Evil revolves around corporate bioweapon outbreaks in and around Raccoon City.',
  },
  {
    id: 'game_50',
    text: 'What tactical multiplayer shooter features maps like "Dust II", "Mirage", and "Inferno"?',
    text_tr: 'Hangi taktiksel çok oyunculu nişancı oyununda "Dust II", "Mirage" ve "Inferno" gibi haritalar bulunur?',
    options: { A: 'Call of Duty', B: 'Counter-Strike', C: 'Rainbow Six Siege', D: 'Battlefield', E: 'Overwatch' },
    options_tr: { A: 'Call of Duty', B: 'Counter-Strike', C: 'Rainbow Six Siege', D: 'Battlefield', E: 'Overwatch' },
    answer: 'B',
    explanation: 'These maps are legendary staples of the Counter-Strike (CS:GO / CS2) franchise.',
  },
  {
    id: 'game_51',
    text: 'What was the first commercial home video game console, released in 1972?',
    text_tr: '1972 yılında piyasaya sürülen ilk ticari ev tipi video oyun konsolu hangisidir?',
    options: { A: 'Atari 2600', B: 'Magnavox Odyssey', C: 'ColecoVision', D: 'Intellivision', E: 'Nintendo Entertainment System' },
    options_tr: { A: 'Atari 2600', B: 'Magnavox Odyssey', C: 'ColecoVision', D: 'Intellivision', E: 'Nintendo Entertainment System' },
    answer: 'B',
    explanation: 'The Magnavox Odyssey predated the Atari VCS/2600 and was the world\'s first commercial home console.',
  },
  {
    id: 'game_52',
    text: 'What is the name of the elite Spartan super-soldier program that Master Chief belongs to?',
    text_tr: 'Halo evreninde Master Chief\'in dahil olduğu elit Spartan süper-asker programının adı nedir?',
    options: { A: 'Spartan-I', B: 'Spartan-II', C: 'Spartan-III', D: 'Spartan-IV', E: 'Spartan-V' },
    options_tr: { A: 'Spartan-I', B: 'Spartan-II', C: 'Spartan-III', D: 'Spartan-IV', E: 'Spartan-V' },
    answer: 'B',
    explanation: 'John-117 was recruited as a child to be part of the highly classified Spartan-II program.',
  },
  {
    id: 'game_53',
    text: 'Which sandbox game developed by Re-Logic is often described as a "2D Minecraft"?',
    text_tr: 'Re-Logic tarafından geliştirilen ve sıkça "2D Minecraft" olarak tanımlanan sandbox oyunu hangisidir?',
    options: { A: 'Starbound', B: 'Terraria', C: 'Stardew Valley', D: 'Don\'t Starve', E: 'Factorio' },
    options_tr: { A: 'Starbound', B: 'Terraria', C: 'Stardew Valley', D: 'Don\'t Starve', E: 'Factorio' },
    answer: 'B',
    explanation: 'Terraria is a 2D action-adventure sandbox game focused on exploration, building, and combat.',
  },
  {
    id: 'game_54',
    text: 'Which legendary creature is the final boss at the end of standard Minecraft progression?',
    text_tr: 'Minecraft\'ın standart ilerleyişinin sonundaki nihai patron (final boss) olan efsanevi yaratık hangisidir?',
    options: { A: 'The Wither', B: 'Herobrine', C: 'The Ender Dragon', D: 'The Warden', E: 'Giant Zombie' },
    options_tr: { A: 'The Wither', B: 'Herobrine', C: 'Ender Ejderhası', D: 'The Warden', E: 'Dev Zombi' },
    answer: 'C',
    explanation: 'Defeating the Ender Dragon in "The End" dimension triggers the game\'s credits roll.',
  },
  {
    id: 'game_55',
    text: 'What is the corporate name of the main antagonist faction in the "Resident Evil" series?',
    text_tr: '"Resident Evil" serisindeki ana düşman konumundaki şirketin adı nedir?',
    options: { A: 'Aperture Science', B: 'Abstergo Industries', C: 'Umbrella Corporation', D: 'Vault-Tec', E: 'Shinra Electric Power Company' },
    options_tr: { A: 'Aperture Science', B: 'Abstergo Industries', C: 'Umbrella Corporation', D: 'Vault-Tec', E: 'Shinra Electric Power Company' },
    answer: 'C',
    explanation: 'The Umbrella Corporation is responsible for creating the T-virus that causes the outbreaks.',
  },
  {
    id: 'game_56',
    text: 'Which character in "League of Legends" is known as the "Loose Cannon" and uses a rocket launcher named Fishbones?',
    text_tr: '"League of Legends" oyununda "Delifişek" olarak bilinen ve Fishbones adında bir roketatar kullanan karakter kimdir?',
    options: { A: 'Tristana', B: 'Miss Fortune', C: 'Jinx', D: 'Caitlyn', E: 'Ashe' },
    options_tr: { A: 'Tristana', B: 'Miss Fortune', C: 'Jinx', D: 'Caitlyn', E: 'Ashe' },
    answer: 'C',
    explanation: 'Jinx is a manic criminal from Zaun who wields an arsenal of custom weapons, also starring in the series "Arcane".',
  },
  {
    id: 'game_57',
    text: 'What is the name of the main fictional continent where the events of "The Witcher" take place?',
    text_tr: '"The Witcher" olaylarının geçtiği kurgusal ana kıtanın adı nedir?',
    options: { A: 'Tamriel', B: 'The Continent', C: 'Azeroth', D: 'Westeros', E: 'Hyrule' },
    options_tr: { A: 'Tamriel', B: 'Kıta (The Continent)', C: 'Azeroth', D: 'Westeros', E: 'Hyrule' },
    answer: 'B',
    explanation: 'The lore of Andrzej Sapkowski simply refers to the primary landmass as "The Continent".',
  },
  {
    id: 'game_58',
    text: 'Which Castlevania game is considered the pioneer of the modern "Metroidvania" subgenre?',
    text_tr: 'Hangi Castlevania oyunu modern "Metroidvania" alt türünün öncüsü kabul edilir?',
    options: { A: 'Castlevania: Symphony of the Night', B: 'Castlevania: Aria of Sorrow', C: 'Castlevania: Rondo of Blood', D: 'Super Castlevania IV', E: 'Castlevania: Simon\'s Quest' },
    options_tr: { A: 'Castlevania: Symphony of the Night', B: 'Castlevania: Aria of Sorrow', C: 'Castlevania: Rondo of Blood', D: 'Super Castlevania IV', E: 'Castlevania: Simon\'s Quest' },
    answer: 'A',
    explanation: 'Symphony of the Night (1997) added non-linear RPG exploration elements to the series, defining the genre name.',
  },
  {
    id: 'game_59',
    text: 'What role-playing game series features attributes collectively named "S.P.E.C.I.A.L."?',
    text_tr: 'Hangi rol yapma oyunu serisi "S.P.E.C.I.A.L." adı verilen nitelikler sistemine sahiptir?',
    options: { A: 'Skyrim', B: 'Cyberpunk 2077', C: 'Fallout', D: 'Mass Effect', E: 'Dragon Age' },
    options_tr: { A: 'Skyrim', B: 'Cyberpunk 2077', C: 'Fallout', D: 'Mass Effect', E: 'Dragon Age' },
    answer: 'C',
    explanation: 'S.P.E.C.I.A.L. stands for Strength, Perception, Endurance, Charisma, Intelligence, Agility, and Luck.',
  },
  {
    id: 'game_60',
    text: 'Which city does the player explore in the 2018 game "Marvel\'s Spider-Man" developed by Insomniac Games?',
    text_tr: 'Insomniac Games tarafından geliştirilen 2018 yapımı "Marvel\'s Spider-Man" oyununda oyuncu hangi şehri keşfeder?',
    options: { A: 'Gotham City', B: 'Los Angeles', C: 'New York City', D: 'Chicago', E: 'Metropolis' },
    options_tr: { A: 'Gotham Şehri', B: 'Los Angeles', C: 'New York Şehri', D: 'Chicago', E: 'Metropolis' },
    answer: 'C',
    explanation: 'The game features an open-world fictionalized version of Manhattan, New York City.',
  },
  {
    id: 'game_61',
    text: 'What was the original name of Nintendo\'s iconic mascot Mario when he first appeared in Donkey Kong (1981)?',
    text_tr: 'Nintendo\'nun ikonik maskotu Mario\'nun, Donkey Kong (1981) oyununda ilk göründüğündeki orijinal adı neydi?',
    options: { A: 'Jumpman', B: 'Plumber Joe', C: 'Luigi', D: 'Red Cap', E: 'Wario' },
    options_tr: { A: 'Jumpman', B: 'Plumber Joe', C: 'Luigi', D: 'Red Cap', E: 'Wario' },
    answer: 'A',
    explanation: 'Mario was initially called "Jumpman" because his primary action was jumping over barrels.',
  },
  {
    id: 'game_62',
    text: 'Which award-winning indie game requires the player to manage a farm inherited from their grandfather in Pelican Town?',
    text_tr: 'Hangi ödüllü bağımsız (indie) oyunda oyuncu, Pelican Town kasabasında büyükbabasından miras kalan bir çiftliği yönetir?',
    options: { A: 'Animal Crossing', B: 'Stardew Valley', C: 'Harvest Moon', D: 'Farming Simulator', E: 'Terraria' },
    options_tr: { A: 'Animal Crossing', B: 'Stardew Valley', C: 'Harvest Moon', D: 'Farming Simulator', E: 'Terraria' },
    answer: 'B',
    explanation: 'Stardew Valley was famously developed entirely by a single person, Eric "ConcernedApe" Barone.',
  },
  {
    id: 'game_63',
    text: 'Which popular MMORPG expansion pack released in 2007 was titled "The Burning Crusade"?',
    text_tr: '2007\'de çıkan hangi popüler MMORPG genişleme paketinin adı "The Burning Crusade"dir?',
    options: { A: 'Guild Wars', B: 'Runescape', C: 'World of Warcraft', D: 'Final Fantasy XI', E: 'Lineage II' },
    options_tr: { A: 'Guild Wars', B: 'Runescape', C: 'World of Warcraft', D: 'Final Fantasy XI', E: 'Lineage II' },
    answer: 'C',
    explanation: 'The Burning Crusade was the highly successful first expansion pack for World of Warcraft.',
  },
  {
    id: 'game_64',
    text: 'Which Ubisoft tactical shooter franchise is famous for destructible environments and Operator characters?',
    text_tr: 'Yıkılabilir çevre mekaniklerine ve Operatör karakterlerine sahip Ubisoft taktiksel nişancı serisi hangisidir?',
    options: { A: 'Tom Clancy\'s The Division', B: 'Tom Clancy\'s Ghost Recon', C: 'Tom Clancy\'s Rainbow Six Siege', D: 'Splinter Cell', E: 'Far Cry' },
    options_tr: { A: 'Tom Clancy\'s The Division', B: 'Tom Clancy\'s Ghost Recon', C: 'Tom Clancy\'s Rainbow Six Siege', D: 'Splinter Cell', E: 'Far Cry' },
    answer: 'C',
    explanation: 'Rainbow Six Siege heavily centers on tactical destruction and synergy between different "Operators".',
  },
  {
    id: 'game_65',
    text: 'Which game studio created "Elden Ring" in collaboration with George R.R. Martin?',
    text_tr: 'George R.R. Martin ile iş birliği içinde "Elden Ring"i hangi stüdyo yaratmıştır?',
    options: { A: 'Team Ninja', B: 'FromSoftware', C: 'Guerrilla Games', D: 'Santa Monica Studio', E: 'Capcom' },
    options_tr: { A: 'Team Ninja', B: 'FromSoftware', C: 'Guerrilla Games', D: 'Santa Monica Studio', E: 'Capcom' },
    answer: 'B',
    explanation: 'FromSoftware, led by Hidetaka Miyazaki, developed Elden Ring, winning Game of the Year in 2022.',
  },
  {
    id: 'game_66',
    text: 'What is the name of the internal AI character that assists Master Chief throughout most of the Halo series?',
    text_tr: 'Halo serisinin çoğunda Master Chief\'e yardımcı olan dahili yapay zeka karakterinin adı nedir?',
    options: { A: 'GLaDOS', B: 'Cortana', C: 'SHODAN', D: 'SIRI', E: 'ED-E' },
    options_tr: { A: 'GLaDOS', B: 'Cortana', C: 'SHODAN', D: 'SIRI', E: 'ED-E' },
    answer: 'B',
    explanation: 'Cortana is a highly advanced smart AI that develops a deep bond with Master Chief John-117.',
  },
  {
    id: 'game_67',
    text: 'Which turn-based tactical franchise developed by Firaxis Games requires players to defend Earth from alien invasion?',
    text_tr: 'Firaxis Games tarafından geliştirilen ve sıra tabanlı savaşta dünyayı uzaylı istilasından korumayı gerektiren seri hangisidir?',
    options: { A: 'Civilization', B: 'XCOM', C: 'Starcraft', D: 'Mass Effect', E: 'Gears of War' },
    options_tr: { A: 'Civilization', B: 'XCOM', C: 'Starcraft', D: 'Mass Effect', E: 'Gears of War' },
    answer: 'B',
    explanation: 'XCOM is a critically acclaimed turn-based tactical franchise focused on the Extraterrestrial Combat Unit.',
  },
  {
    id: 'game_68',
    text: 'What is the name of the virtual fictional currency used inside the game "Fortnite"?',
    text_tr: '"Fortnite" oyununda kullanılan kurgusal sanal para biriminin adı nedir?',
    options: { A: 'Robux', B: 'V-Bucks', C: 'Minecoins', D: 'Riot Points', E: 'COD Points' },
    options_tr: { A: 'Robux', B: 'V-Bucks', C: 'Minecoins', D: 'Riot Points', E: 'COD Points' },
    answer: 'B',
    explanation: 'V-Bucks (Vindertech Bucks) are used to purchase cosmetics and battle passes in Fortnite.',
  },
  {
    id: 'game_69',
    text: 'Which historical strategy game franchise was created by Sid Meier?',
    text_tr: 'Sid Meier tarafından yaratılan tarihi strateji oyunu serisi hangisidir?',
    options: { A: 'Age of Empires', B: 'Total War', C: 'Civilization', D: 'Europa Universalis', E: 'StarCraft' },
    options_tr: { A: 'Age of Empires', B: 'Total War', C: 'Civilization', D: 'Europa Universalis', E: 'StarCraft' },
    answer: 'C',
    explanation: 'Sid Meier\'s Civilization is a legendary turn-based "4X" strategy video game franchise first launched in 1991.',
  },
  {
    id: 'game_70',
    text: 'What is the sub-title of the 2011 "The Elder Scrolls V" entry, set in a dragon-infested northern province?',
    text_tr: 'Ejderhalarla kaplı kuzey bir eyalette geçen 2011 yapımı "The Elder Scrolls V" oyununun alt başlığı nedir?',
    options: { A: 'Morrowind', B: 'Oblivion', C: 'Skyrim', D: 'Daggerfall', E: 'Arena' },
    options_tr: { A: 'Morrowind', B: 'Oblivion', C: 'Skyrim', D: 'Daggerfall', E: 'Arena' },
    answer: 'C',
    explanation: 'Skyrim is one of the most celebrated and re-released open-world RPGs in history.',
  },
  {
    id: 'game_71',
    text: 'Which iconic blue hedgehog is the primary mascot of SEGA?',
    text_tr: 'SEGA\'nın ana maskotu olan ikonik mavi kirpinin adı nedir?',
    options: { A: 'Crash Bandicoot', B: 'Spyro', C: 'Sonic', D: 'Mega Man', E: 'Pac-Man' },
    options_tr: { A: 'Crash Bandicoot', B: 'Spyro', C: 'Sonic', D: 'Mega Man', E: 'Pac-Man' },
    answer: 'C',
    explanation: 'Sonic the Hedgehog was introduced in 1991 to compete directly with Nintendo\'s Mario.',
  },
  {
    id: 'game_72',
    text: 'In competitive "Counter-Strike", how many seconds does it take for the C4 bomb to detonate after being planted?',
    text_tr: 'Rekabetçi "Counter-Strike" turnuva kurallarında, C4 bombası kurulduktan kaç saniye sonra patlar?',
    options: { A: '35', B: '40', C: '45', D: '50', E: '60' },
    options_tr: { A: '35', B: '40', C: '45', D: '50', E: '60' },
    answer: 'B',
    explanation: 'The bomb timer in modern competitive Counter-Strike match settings is exactly 40 seconds.',
  },
  {
    id: 'game_73',
    text: 'What classic Nintendo franchise features space bounty hunter Samus Aran fighting Space Pirates?',
    text_tr: 'Hangi klasik Nintendo serisi, uzay ödül avcısı Samus Aran\'ın uzay korsanlarına karşı mücadelesini konu alır?',
    options: { A: 'Star Fox', B: 'F-Zero', C: 'Metroid', D: 'Kirby', E: 'Kid Icarus' },
    options_tr: { A: 'Star Fox', B: 'F-Zero', C: 'Metroid', D: 'Kirby', E: 'Kid Icarus' },
    answer: 'C',
    explanation: 'Metroid launched in 1986, famous for its atmospheric exploration and revealing Samus as a female protagonist.',
  },
  {
    id: 'game_74',
    text: 'Which multiplayer online game requires a team of survivors to repair generators while escaping a supernatural killer?',
    text_tr: 'Hangi çok oyunculu çevrimiçi oyunda bir hayatta kalan ekibi doğaüstü bir katilden kaçarken jeneratörleri tamir etmek zorundadır?',
    options: { A: 'Friday the 13th', B: 'Dead by Daylight', C: 'Left 4 Dead', D: 'Phasmophobia', E: 'Evolve' },
    options_tr: { A: 'Friday the 13th', B: 'Dead by Daylight', C: 'Left 4 Dead', D: 'Phasmophobia', E: 'Evolve' },
    answer: 'B',
    explanation: 'Dead by Daylight is an asymmetrical 4v1 horror game developed by Behaviour Interactive.',
  },
  {
    id: 'game_75',
    text: 'Which company developed the critically acclaimed space-opera RPG series "Mass Effect"?',
    text_tr: 'Büyük beğeni toplayan uzay operası RPG serisi "Mass Effect"i hangi şirket geliştirmiştir?',
    options: { A: 'Bethesda', B: 'BioWare', C: 'Obsidian', D: 'Bungie', E: 'CD Projekt Red' },
    options_tr: { A: 'Bethesda', B: 'BioWare', C: 'Obsidian', D: 'Bungie', E: 'CD Projekt Red' },
    answer: 'B',
    explanation: 'BioWare developed the Mass Effect trilogy, telling the story of Commander Shepard.',
  },
  {
    id: 'game_76',
    text: 'What is the standard total number of squares on a traditional chessboard?',
    text_tr: 'Geleneksel bir satranç tahtasında toplamda kaç kare bulunur?',
    options: { A: '32', B: '48', C: '64', D: '72', E: '81' },
    options_tr: { A: '32', B: '48', C: '64', D: '72', E: '81' },
    answer: 'C',
    explanation: 'A standard chessboard has an 8x8 grid layout, totaling 64 squares alternating in light and dark colors.',
  },
  {
    id: 'game_77',
    text: 'Which video game series features the fictional secret agency known as the "ICA" and an assassin named Agent 47?',
    text_tr: '"ICA" adlı kurgusal gizli ajansı ve Ajan 47 isimli suikastçıyı barındıran video oyunu serisi hangisidir?',
    options: { A: 'Splinter Cell', B: 'Hitman', C: 'Metal Gear', D: 'Deus Ex', E: 'Sniper Elite' },
    options_tr: { A: 'Splinter Cell', B: 'Hitman', C: 'Metal Gear', D: 'Deus Ex', E: 'Sniper Elite' },
    answer: 'B',
    explanation: 'Agent 47 is a cloned contract killer working for the International Contract Agency (ICA) in the Hitman series.',
  },
  {
    id: 'game_78',
    text: 'Which classic fighting game franchise introduced the special fireball move known as the "Hadouken"?',
    text_tr: '"Hadouken" adı verilen özel ateş topu saldırısını oyun dünyasına kazandıran klasik dövüş oyunu serisi hangisidir?',
    options: { A: 'Tekken', B: 'Mortal Kombat', C: 'Street Fighter', D: 'Virtua Fighter', E: 'King of Fighters' },
    options_tr: { A: 'Tekken', B: 'Mortal Kombat', C: 'Street Fighter', D: 'Virtua Fighter', E: 'King of Fighters' },
    answer: 'C',
    explanation: 'The Hadouken is the signature move of characters like Ryu and Ken in Capcom\'s Street Fighter.',
  },
  {
    id: 'game_79',
    text: 'What is the name of the underwater dystopian city where the original "BioShock" takes place?',
    text_tr: 'Orijinal "BioShock" oyununun geçtiği su altı distopik şehrinin adı nedir?',
    options: { A: 'Columbia', B: 'Rapture', C: 'Atlantis', D: 'Dunwall', E: 'Night City' },
    options_tr: { A: 'Columbia', B: 'Rapture', C: 'Atlantis', D: 'Dunwall', E: 'Night City' },
    answer: 'B',
    explanation: 'Rapture is an underwater city built by visionary Andrew Ryan to escape government interference.',
  },
  {
    id: 'game_80',
    text: 'In which city does "Cyberpunk 2077" take place?',
    text_tr: '"Cyberpunk 2077" hangi şehirde geçmektedir?',
    options: { A: 'Mega-City One', B: 'Night City', C: 'Los Santos', D: 'New Eden', E: 'Neo-Tokyo' },
    options_tr: { A: 'Mega-City One', B: 'Night City', C: 'Los Santos', D: 'New Eden', E: 'Neo-Tokyo' },
    answer: 'B',
    explanation: 'Night City is a fictional megalopolis set in the near-future California of 2077.',
  },
  {
    id: 'game_81',
    text: 'What card game requires players to yell the game\'s name when they have exactly one card left in their hand?',
    text_tr: 'Hangi kart oyununda oyuncuların elinde tam bir kart kaldığında oyunun adını bağırması gerekir?',
    options: { A: 'Poker', B: 'Go Fish', C: 'Uno', D: 'Snap', E: 'Blackjack' },
    options_tr: { A: 'Poker', B: 'Go Fish', C: 'Uno', D: 'Snap', E: 'Blackjack' },
    answer: 'C',
    explanation: 'In Uno, if you fail to say "Uno!" when you have one card left, you must draw two penalty cards.',
  },
  {
    id: 'game_82',
    text: 'Which Nintendo franchise lets players build and manage their own island, inviting anthropomorphic animal villagers?',
    text_tr: 'Hangi Nintendo serisi, oyuncuların kendi adalarını inşa etmelerine ve yönetmelerine olanak tanır; insan biçimli hayvan sakinler de davet edilebilir?',
    options: { A: 'Harvest Moon', B: 'Pikmin', C: 'Animal Crossing', D: 'Tomodachi Life', E: 'Fantasy Life' },
    options_tr: { A: 'Harvest Moon', B: 'Pikmin', C: 'Animal Crossing', D: 'Tomodachi Life', E: 'Fantasy Life' },
    answer: 'C',
    explanation: 'Animal Crossing: New Horizons sold over 40 million copies and became enormously popular during the COVID-19 pandemic.',
  },
  {
    id: 'game_83',
    text: 'In "Dark Souls", what resource is used as both a currency and experience points?',
    text_tr: '"Dark Souls" oyununda hem para birimi hem de deneyim puanı olarak kullanılan kaynak nedir?',
    options: { A: 'Runes', B: 'Estus', C: 'Souls', D: 'Embers', E: 'Humanity' },
    options_tr: { A: 'Runlar', B: 'Estus', C: 'Ruhlar (Souls)', D: 'Közler (Embers)', E: 'İnsanlık (Humanity)' },
    answer: 'C',
    explanation: 'Souls are collected from enemies and bosses, used for leveling up and purchasing items.',
  },
  {
    id: 'game_84',
    text: 'Which iconic Nintendo fighting game franchise features characters from across Nintendo\'s entire game library?',
    text_tr: 'Nintendo\'nun tüm oyun kütüphanesinden karakterleri bir araya getiren ikonik Nintendo dövüş oyunu serisi hangisidir?',
    options: { A: 'Street Fighter', B: 'Super Smash Bros.', C: 'Tekken', D: 'Mortal Kombat', E: 'Arms' },
    options_tr: { A: 'Street Fighter', B: 'Super Smash Bros.', C: 'Tekken', D: 'Mortal Kombat', E: 'Arms' },
    answer: 'B',
    explanation: 'Super Smash Bros. is a crossover fighting game series featuring Nintendo and third-party characters.',
  },
  {
    id: 'game_85',
    text: 'In "Minecraft", what is the name of the parallel dimension filled with lava, netherrack, and hostile mobs?',
    text_tr: '"Minecraft"ta lav, netherrack ve düşman yaratıklarla dolu paralel boyutun adı nedir?',
    options: { A: 'The End', B: 'The Aether', C: 'The Nether', D: 'The Overworld', E: 'The Deep Dark' },
    options_tr: { A: 'The End', B: 'The Aether', C: 'Nether', D: 'Aşırı Dünya (Overworld)', E: 'Derin Karanlık (Deep Dark)' },
    answer: 'C',
    explanation: 'The Nether is a hellish dimension accessed through an Obsidian portal, filled with unique resources and dangers.',
  },
];

module.exports = { games };
