'use strict';

const general = [
  {
    id: 'gen_01',
    text: 'Which organ in the human body produces bile?',
    text_tr: 'İnsan vücudunda safra üreten organ hangisidir?',
    options: { A: 'Pancreas', B: 'Gallbladder', C: 'Liver', D: 'Spleen', E: 'Duodenum' },
    options_tr: { A: 'Pankreas', B: 'Safra kesesi', C: 'Karaciğer', D: 'Dalak', E: 'Onikiparmak bağırsağı' },
    answer: 'C',
    explanation: 'Karaciğer safra üretir; safra kesesi yalnızca onu depolar ve yoğunlaştırır.',
  },
  {
    id: 'gen_02',
    text: 'What is the chemical symbol for Tungsten?',
    text_tr: 'Tungsten\'in kimyasal sembolü nedir?',
    options: { A: 'Tu', B: 'Wg', C: 'Tn', D: 'W', E: 'Wo' },
    options_tr: { A: 'Tu', B: 'Wg', C: 'Tn', D: 'W', E: 'Wo' },
    answer: 'D',
    explanation: 'Almancası "Wolfram"dan gelir. Tungsten ampul flamanlarında kullanılır.',
  },
  {
    id: 'gen_03',
    text: 'Which planet in our solar system has the most confirmed moons?',
    text_tr: 'Güneş sistemimizde en fazla onaylanmış uyduya sahip gezegen hangisidir?',
    options: { A: 'Jupiter', B: 'Neptune', C: 'Uranus', D: 'Saturn', E: 'Mars' },
    options_tr: { A: 'Jüpiter', B: 'Neptün', C: 'Uranüs', D: 'Satürn', E: 'Mars' },
    answer: 'D',
    explanation: 'Satürn 2023\'te 146 onaylı uyduyla Jüpiter\'i geçti.',
  },
  {
    id: 'gen_04',
    text: 'Who coined the term "Survival of the Fittest" in the context of evolution?',
    text_tr: 'Evrim bağlamında "En Uygun Olanın Hayatta Kalması" ifadesini kim ortaya attı?',
    options: { A: 'Charles Darwin', B: 'Alfred Russel Wallace', C: 'Thomas Huxley', D: 'Herbert Spencer', E: 'Ernst Haeckel' },
    options_tr: { A: 'Charles Darwin', B: 'Alfred Russel Wallace', C: 'Thomas Huxley', D: 'Herbert Spencer', E: 'Ernst Haeckel' },
    answer: 'D',
    explanation: 'Herbert Spencer bu ifadeyi 1864\'te yarattı; Darwin sonraki baskılarda Spencer\'dan ödünç aldı.',
  },
  {
    id: 'gen_05',
    text: 'Which country was the first to grant women the right to vote in national elections?',
    text_tr: 'Ulusal seçimlerde kadınlara oy hakkı tanıyan ilk ülke hangisidir?',
    options: { A: 'Finland', B: 'Australia', C: 'Norway', D: 'Denmark', E: 'New Zealand' },
    options_tr: { A: 'Finlandiya', B: 'Avustralya', C: 'Norveç', D: 'Danimarka', E: 'Yeni Zelanda' },
    answer: 'E',
    explanation: 'Yeni Zelanda, 1893\'te diğer tüm ülkelerden önce kadınlara oy hakkı tanıdı.',
  },
  {
    id: 'gen_06',
    text: 'What is the hardest natural substance on Earth?',
    text_tr: 'Dünya\'daki en sert doğal madde nedir?',
    options: { A: 'Corundum', B: 'Topaz', C: 'Quartz', D: 'Diamond', E: 'Graphite' },
    options_tr: { A: 'Korundum', B: 'Topaz', C: 'Kuvars', D: 'Elmas', E: 'Grafit' },
    answer: 'D',
    explanation: 'Elmas Mohs sertlik skalasında 10 ile en yüksek değere sahiptir.',
  },
  {
    id: 'gen_07',
    text: 'How many bones does an adult human body have?',
    text_tr: 'Yetişkin bir insan vücudunda kaç kemik bulunur?',
    options: { A: '186', B: '196', C: '206', D: '216', E: '226' },
    options_tr: { A: '186', B: '196', C: '206', D: '216', E: '226' },
    answer: 'C',
    explanation: 'Yetişkin insan iskeleti 206 kemikten oluşur; bebeklerin yaklaşık 270 kemiği vardır ve bunlar büyüme sırasında kaynaşır.',
  },
  {
    id: 'gen_08',
    text: 'Which gas makes up the largest percentage of Earth\'s atmosphere?',
    text_tr: 'Dünya atmosferinin en büyük bölümünü oluşturan gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Carbon dioxide', C: 'Argon', D: 'Nitrogen', E: 'Hydrogen' },
    options_tr: { A: 'Oksijen', B: 'Karbondioksit', C: 'Argon', D: 'Azot', E: 'Hidrojen' },
    answer: 'D',
    explanation: 'Azot (N₂) atmosferin yaklaşık %78\'ini oluşturur; oksijen ise yaklaşık %21\'ini.',
  },
  {
    id: 'gen_09',
    text: 'What is the speed of light in a vacuum (approximately)?',
    text_tr: 'Işığın vakumdaki hızı yaklaşık olarak nedir?',
    options: { A: '200,000 km/s', B: '250,000 km/s', C: '300,000 km/s', D: '350,000 km/s', E: '400,000 km/s' },
    options_tr: { A: '200.000 km/s', B: '250.000 km/s', C: '300.000 km/s', D: '350.000 km/s', E: '400.000 km/s' },
    answer: 'C',
    explanation: 'Işık vakumda yaklaşık 299.792 km/s hızla hareket eder; bu genellikle 300.000 km/s olarak yuvarlanır.',
  },
  {
    id: 'gen_10',
    text: 'Which element has the atomic number 1?',
    text_tr: 'Atom numarası 1 olan element hangisidir?',
    options: { A: 'Helium', B: 'Lithium', C: 'Carbon', D: 'Hydrogen', E: 'Oxygen' },
    options_tr: { A: 'Helyum', B: 'Lityum', C: 'Karbon', D: 'Hidrojen', E: 'Oksijen' },
    answer: 'D',
    explanation: 'Hidrojen, periyodik tablonun ilk elementidir ve evrende en bol bulunan elementtir.',
  },
  {
    id: 'gen_11',
    text: 'How many chambers does the human heart have?',
    text_tr: 'İnsan kalbinde kaç oda bulunur?',
    options: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    options_tr: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    answer: 'C',
    explanation: 'İnsan kalbi dört odadan oluşur: sağ ve sol kulakçık (atrium) ile sağ ve sol karıncık (ventrikül).',
  },
  {
    id: 'gen_12',
    text: 'What is the largest organ of the human body?',
    text_tr: 'İnsan vücudunun en büyük organı hangisidir?',
    options: { A: 'Liver', B: 'Brain', C: 'Lungs', D: 'Skin', E: 'Intestines' },
    options_tr: { A: 'Karaciğer', B: 'Beyin', C: 'Akciğerler', D: 'Deri', E: 'Bağırsaklar' },
    answer: 'D',
    explanation: 'Deri, yaklaşık 1,5–2 m² yüzey alanıyla insan vücudunun en büyük organıdır.',
  },
  {
    id: 'gen_13',
    text: 'Which blood type is known as the "universal donor"?',
    text_tr: '"Evrensel donör" olarak bilinen kan grubu hangisidir?',
    options: { A: 'A+', B: 'B-', C: 'AB+', D: 'O-', E: 'O+' },
    options_tr: { A: 'A+', B: 'B-', C: 'AB+', D: '0-', E: '0+' },
    answer: 'D',
    explanation: 'O Rh- kan grubu tüm alıcılara verilebilir; bu yüzden "evrensel donör" olarak adlandırılır.',
  },
  {
    id: 'gen_14',
    text: 'Which scientist proposed the general theory of relativity?',
    text_tr: 'Genel görelilik teorisini kim öne sürmüştür?',
    options: { A: 'Isaac Newton', B: 'Niels Bohr', C: 'Max Planck', D: 'Albert Einstein', E: 'Erwin Schrödinger' },
    options_tr: { A: 'Isaac Newton', B: 'Niels Bohr', C: 'Max Planck', D: 'Albert Einstein', E: 'Erwin Schrödinger' },
    answer: 'D',
    explanation: 'Albert Einstein genel görelilik teorisini 1915\'te yayımladı; kütleçekimini uzay-zamanın eğriliği olarak açıkladı.',
  },
  {
    id: 'gen_15',
    text: 'DNA stands for which of the following?',
    text_tr: 'DNA\'nın açılımı aşağıdakilerden hangisidir?',
    options: { A: 'Deoxyribonucleic Acid', B: 'Dioxynucleic Acid', C: 'Diribonucleic Acid', D: 'Deoxyribonitric Acid', E: 'Dinucleic Acid' },
    options_tr: { A: 'Deoksiribonükleik Asit', B: 'Dioksinükleik Asit', C: 'Diribonükleik Asit', D: 'Deoksiriboniterik Asit', E: 'Dinükleik Asit' },
    answer: 'A',
    explanation: 'DNA (Deoksiribonükleik Asit) canlı organizmaların genetik bilgisini taşıyan moleküldür.',
  },
  {
    id: 'gen_16',
    text: 'What is the boiling point of water at sea level in Celsius?',
    text_tr: 'Deniz seviyesinde suyun kaynama noktası Celsius olarak kaçtır?',
    options: { A: '90°C', B: '95°C', C: '98°C', D: '100°C', E: '105°C' },
    options_tr: { A: '90°C', B: '95°C', C: '98°C', D: '100°C', E: '105°C' },
    answer: 'D',
    explanation: 'Deniz seviyesinde (1 atm basınçta) su 100°C\'de kaynar.',
  },
  {
    id: 'gen_17',
    text: 'How many teeth does a healthy adult human have (including wisdom teeth)?',
    text_tr: 'Sağlıklı bir yetişkinin (yirmi yaş dişleri dahil) kaç dişi vardır?',
    options: { A: '28', B: '30', C: '32', D: '34', E: '36' },
    options_tr: { A: '28', B: '30', C: '32', D: '34', E: '36' },
    answer: 'C',
    explanation: 'Yetişkin insanın 32 daimi dişi vardır; bunların 4\'ü yirmi yaş dişidir.',
  },
  {
    id: 'gen_18',
    text: 'Which planet is known as the "Red Planet"?',
    text_tr: '"Kızıl Gezegen" olarak bilinen gezegen hangisidir?',
    options: { A: 'Venus', B: 'Jupiter', C: 'Mars', D: 'Mercury', E: 'Saturn' },
    options_tr: { A: 'Venüs', B: 'Jüpiter', C: 'Mars', D: 'Merkür', E: 'Satürn' },
    answer: 'C',
    explanation: 'Mars, yüzeyindeki demir oksit (pas) nedeniyle kırmızı görünür ve bu yüzden "Kızıl Gezegen" olarak anılır.',
  },
  {
    id: 'gen_19',
    text: 'What is the chemical formula for water?',
    text_tr: 'Suyun kimyasal formülü nedir?',
    options: { A: 'HO', B: 'H₂O', C: 'H₃O', D: 'HO₂', E: 'H₂O₂' },
    options_tr: { A: 'HO', B: 'H₂O', C: 'H₃O', D: 'HO₂', E: 'H₂O₂' },
    answer: 'B',
    explanation: 'Su molekülü iki hidrojen atomu ve bir oksijen atomundan oluşur: H₂O.',
  },
  {
    id: 'gen_20',
    text: 'Which animal has the longest gestation period?',
    text_tr: 'En uzun gebelik süresine sahip hayvan hangisidir?',
    options: { A: 'Blue Whale', B: 'Giraffe', C: 'African Elephant', D: 'Rhinoceros', E: 'Hippopotamus' },
    options_tr: { A: 'Mavi Balina', B: 'Zürafa', C: 'Afrika Fili', D: 'Gergedan', E: 'Su Aygırı' },
    answer: 'C',
    explanation: 'Afrika filinin gebelik süresi yaklaşık 22 aydır; bu tüm kara memelileri arasında en uzun olanıdır.',
  },
  {
    id: 'gen_21',
    text: 'How many pairs of chromosomes does a typical human cell contain?',
    text_tr: 'Tipik bir insan hücresi kaç çift kromozom içerir?',
    options: { A: '21', B: '22', C: '23', D: '24', E: '46' },
    options_tr: { A: '21', B: '22', C: '23', D: '24', E: '46' },
    answer: 'C',
    explanation: 'İnsan hücrelerinde 23 çift (toplam 46) kromozom bulunur.',
  },
  {
    id: 'gen_22',
    text: 'What is the most abundant metal in the Earth\'s crust?',
    text_tr: 'Dünya\'nın kabuğunda en bol bulunan metal hangisidir?',
    options: { A: 'Iron', B: 'Calcium', C: 'Sodium', D: 'Aluminium', E: 'Silicon' },
    options_tr: { A: 'Demir', B: 'Kalsiyum', C: 'Sodyum', D: 'Alüminyum', E: 'Silisyum' },
    answer: 'D',
    explanation: 'Alüminyum, Dünya kabuğunun yaklaşık %8\'ini oluşturarak en bol bulunan metaldir.',
  },
  {
    id: 'gen_23',
    text: 'Which vitamin is produced by the human body when exposed to sunlight?',
    text_tr: 'Güneş ışığına maruz kalındığında insan vücudu hangi vitamini üretir?',
    options: { A: 'Vitamin A', B: 'Vitamin B12', C: 'Vitamin C', D: 'Vitamin D', E: 'Vitamin K' },
    options_tr: { A: 'A vitamini', B: 'B12 vitamini', C: 'C vitamini', D: 'D vitamini', E: 'K vitamini' },
    answer: 'D',
    explanation: 'Cilt, güneş ışığındaki UVB radyasyonunu D vitaminine dönüştürür.',
  },
  {
    id: 'gen_24',
    text: 'What is the name of the force that keeps planets in orbit around the Sun?',
    text_tr: 'Gezegenleri Güneş\'in yörüngesinde tutan kuvvetin adı nedir?',
    options: { A: 'Electromagnetic force', B: 'Nuclear force', C: 'Centrifugal force', D: 'Gravity', E: 'Dark energy' },
    options_tr: { A: 'Elektromanyetik kuvvet', B: 'Nükleer kuvvet', C: 'Merkezkaç kuvveti', D: 'Yerçekimi', E: 'Karanlık enerji' },
    answer: 'D',
    explanation: 'Yerçekimi, güneşin gezegenleri yörüngede tutmasını sağlayan kuvvettir; Isaac Newton tarafından tanımlanmıştır.',
  },
  {
    id: 'gen_25',
    text: 'What is photosynthesis?',
    text_tr: 'Fotosentez nedir?',
    options: { A: 'Process by which animals digest food', B: 'Process by which plants convert light into energy', C: 'Process by which cells divide', D: 'Process by which bacteria reproduce', E: 'Process by which rocks form' },
    options_tr: { A: 'Hayvanların yiyecekleri sindirme süreci', B: 'Bitkilerin ışığı enerjiye dönüştürme süreci', C: 'Hücrelerin bölünme süreci', D: 'Bakterilerin çoğalma süreci', E: 'Kayaların oluşma süreci' },
    answer: 'B',
    explanation: 'Fotosentez, bitkilerin güneş ışığını, suyu ve karbondioksiti glikoz ve oksijene dönüştürdüğü süreçtir.',
  },
  {
    id: 'gen_26',
    text: 'Which planet is the largest in our solar system?',
    text_tr: 'Güneş sistemimizin en büyük gezegeni hangisidir?',
    options: { A: 'Saturn', B: 'Uranus', C: 'Neptune', D: 'Jupiter', E: 'Earth' },
    options_tr: { A: 'Satürn', B: 'Uranüs', C: 'Neptün', D: 'Jüpiter', E: 'Dünya' },
    answer: 'D',
    explanation: 'Jüpiter, Güneş sisteminin en büyük gezegenidir; kütlesi diğer tüm gezegenlerin toplamından iki kattan fazladır.',
  },
  {
    id: 'gen_27',
    text: 'How many sides does a hexagon have?',
    text_tr: 'Bir altıgenin kaç kenarı vardır?',
    options: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    options_tr: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    answer: 'C',
    explanation: '"Hexa" Yunanca\'da altı anlamına gelir; altıgen 6 kenarlı bir çokgendir.',
  },
  {
    id: 'gen_28',
    text: 'What type of animal is a shark?',
    text_tr: 'Köpek balığı ne tür bir hayvandır?',
    options: { A: 'Mammal', B: 'Reptile', C: 'Amphibian', D: 'Fish', E: 'Mollusk' },
    options_tr: { A: 'Memeli', B: 'Sürüngen', C: 'Amfibi', D: 'Balık', E: 'Yumuşakça' },
    answer: 'D',
    explanation: 'Köpek balıkları, kıkırdaklı iskeletleri olan ve solungaçlarıyla nefes alan kartilajlı balıklardır.',
  },
  {
    id: 'gen_29',
    text: 'What does a barometer measure?',
    text_tr: 'Barometre neyi ölçer?',
    options: { A: 'Temperature', B: 'Humidity', C: 'Wind speed', D: 'Atmospheric pressure', E: 'Rainfall' },
    options_tr: { A: 'Sıcaklık', B: 'Nem', C: 'Rüzgar hızı', D: 'Atmosfer basıncı', E: 'Yağış miktarı' },
    answer: 'D',
    explanation: 'Barometre atmosfer basıncını ölçer ve hava durumu tahmini için kullanılır.',
  },
  {
    id: 'gen_30',
    text: 'Which part of the brain controls balance and coordination?',
    text_tr: 'Beynin hangi bölümü denge ve koordinasyonu kontrol eder?',
    options: { A: 'Cerebrum', B: 'Cerebellum', C: 'Brain stem', D: 'Hippocampus', E: 'Amygdala' },
    options_tr: { A: 'Serebrum (büyük beyin)', B: 'Serebellum (küçük beyin)', C: 'Beyin sapı', D: 'Hipokampüs', E: 'Amigdala' },
    answer: 'B',
    explanation: 'Serebellum (küçük beyin), hareket koordinasyonunu, dengeyi ve kas tonusunu düzenler.',
  },
  {
    id: 'gen_31',
    text: 'What is the unit of electrical resistance?',
    text_tr: 'Elektriksel direncin birimi nedir?',
    options: { A: 'Volt', B: 'Ampere', C: 'Watt', D: 'Ohm', E: 'Farad' },
    options_tr: { A: 'Volt', B: 'Amper', C: 'Watt', D: 'Ohm', E: 'Farad' },
    answer: 'D',
    explanation: 'Ohm (Ω), Georg Simon Ohm\'un adından gelen elektriksel direnç birimidir.',
  },
  {
    id: 'gen_32',
    text: 'Which gas is responsible for the greenhouse effect?',
    text_tr: 'Sera etkisinden sorumlu olan gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Nitrogen', C: 'Argon', D: 'Carbon dioxide', E: 'Helium' },
    options_tr: { A: 'Oksijen', B: 'Azot', C: 'Argon', D: 'Karbondioksit', E: 'Helyum' },
    answer: 'D',
    explanation: 'Karbondioksit (CO₂), sera etkisine en çok katkıda bulunan gazlar arasında öne çıkan bir sera gazıdır.',
  },
  {
    id: 'gen_33',
    text: 'What is the most common type of star in the Milky Way galaxy?',
    text_tr: 'Samanyolu galaksisinde en yaygın yıldız türü hangisidir?',
    options: { A: 'Giant stars', B: 'Neutron stars', C: 'Red dwarf stars', D: 'White dwarf stars', E: 'Yellow dwarf stars' },
    options_tr: { A: 'Dev yıldızlar', B: 'Nötron yıldızları', C: 'Kırmızı cüce yıldızlar', D: 'Beyaz cüce yıldızlar', E: 'Sarı cüce yıldızlar' },
    answer: 'C',
    explanation: 'Kırmızı cüceler, Samanyolu\'ndaki yıldızların yaklaşık %70\'ini oluşturur.',
  },
  {
    id: 'gen_34',
    text: 'Which organ is primarily responsible for filtering blood in the human body?',
    text_tr: 'İnsan vücudunda kanı süzmekten öncelikli olarak sorumlu olan organ hangisidir?',
    options: { A: 'Liver', B: 'Spleen', C: 'Kidney', D: 'Lung', E: 'Pancreas' },
    options_tr: { A: 'Karaciğer', B: 'Dalak', C: 'Böbrek', D: 'Akciğer', E: 'Pankreas' },
    answer: 'C',
    explanation: 'Böbrekler, atık maddeleri ve fazla sıvıyı kandan süzerek idrar oluşturur.',
  },
  {
    id: 'gen_35',
    text: 'What is the term for animals that eat both plants and meat?',
    text_tr: 'Hem bitki hem de et yiyen hayvanlar için kullanılan terim nedir?',
    options: { A: 'Carnivore', B: 'Herbivore', C: 'Omnivore', D: 'Insectivore', E: 'Frugivore' },
    options_tr: { A: 'Etçil', B: 'Otçul', C: 'Hepçil', D: 'Böcekçil', E: 'Meyveçil' },
    answer: 'C',
    explanation: 'Hepçiller (omnivore) hem hayvan hem de bitki kökenli besinlerle beslenir; insanlar da hepçildir.',
  },
  {
    id: 'gen_36',
    text: 'What is the name of the process by which water turns into vapor?',
    text_tr: 'Suyun buhara dönüşme sürecinin adı nedir?',
    options: { A: 'Condensation', B: 'Sublimation', C: 'Evaporation', D: 'Precipitation', E: 'Transpiration' },
    options_tr: { A: 'Yoğuşma', B: 'Süblimleşme', C: 'Buharlaşma', D: 'Yağış', E: 'Terleme (bitkisel)' },
    answer: 'C',
    explanation: 'Buharlaşma, sıvı suyun su buharına dönüştüğü ısı kaynaklı bir süreçtir.',
  },
  {
    id: 'gen_37',
    text: 'How many legs does an insect have?',
    text_tr: 'Bir böceğin kaç bacağı vardır?',
    options: { A: '4', B: '6', C: '8', D: '10', E: '12' },
    options_tr: { A: '4', B: '6', C: '8', D: '10', E: '12' },
    answer: 'B',
    explanation: 'Tüm böcekler 6 bacağa sahiptir; bu özellik onları 8 bacaklı örümceklerden ayırır.',
  },
  {
    id: 'gen_38',
    text: 'Which layer of the Earth is liquid?',
    text_tr: 'Dünya\'nın hangi katmanı sıvıdır?',
    options: { A: 'Inner core', B: 'Outer core', C: 'Mantle', D: 'Crust', E: 'Lithosphere' },
    options_tr: { A: 'İç çekirdek', B: 'Dış çekirdek', C: 'Manto', D: 'Kabuk', E: 'Litosfer' },
    answer: 'B',
    explanation: 'Dünya\'nın dış çekirdeği erimiş demir ve nikelden oluşan sıvı bir katmandır.',
  },
  {
    id: 'gen_39',
    text: 'What is the powerhouse of the cell?',
    text_tr: 'Hücrenin enerji merkezi olarak bilinen organel nedir?',
    options: { A: 'Nucleus', B: 'Ribosome', C: 'Mitochondria', D: 'Golgi apparatus', E: 'Endoplasmic reticulum' },
    options_tr: { A: 'Çekirdek', B: 'Ribozom', C: 'Mitokondri', D: 'Golgi aygıtı', E: 'Endoplazmik retikulum' },
    answer: 'C',
    explanation: 'Mitokondri, hücresel solunum yoluyla ATP enerjisi üreten organel olduğu için "hücrenin enerji santrali" olarak anılır.',
  },
  {
    id: 'gen_40',
    text: 'Which ocean is the largest on Earth?',
    text_tr: 'Dünya\'daki en büyük okyanus hangisidir?',
    options: { A: 'Atlantic Ocean', B: 'Indian Ocean', C: 'Arctic Ocean', D: 'Southern Ocean', E: 'Pacific Ocean' },
    options_tr: { A: 'Atlas Okyanusu', B: 'Hint Okyanusu', C: 'Arktik Okyanus', D: 'Güney Okyanusu', E: 'Pasifik Okyanusu' },
    answer: 'E',
    explanation: 'Pasifik Okyanusu, yaklaşık 165 milyon km² ile Dünya\'nın en büyük ve en derin okyanusudur.',
  },
  {
    id: 'gen_41',
    text: 'What is the SI unit of temperature?',
    text_tr: 'Sıcaklığın SI birimi nedir?',
    options: { A: 'Celsius', B: 'Fahrenheit', C: 'Kelvin', D: 'Rankine', E: 'Réaumur' },
    options_tr: { A: 'Santigrat', B: 'Fahrenheit', C: 'Kelvin', D: 'Rankine', E: 'Réaumur' },
    answer: 'C',
    explanation: 'Kelvin (K), mutlak sıcaklık birimidir ve SI birim sisteminin temel birimidir.',
  },
  {
    id: 'gen_42',
    text: 'Which planet rotates on its side (axial tilt ~98°)?',
    text_tr: 'Yörünge eksenine dik yakın dönerek (~98° eksen eğimi) "yanına yatmış" şekilde dönen gezegen hangisidir?',
    options: { A: 'Neptune', B: 'Venus', C: 'Uranus', D: 'Saturn', E: 'Pluto' },
    options_tr: { A: 'Neptün', B: 'Venüs', C: 'Uranüs', D: 'Satürn', E: 'Plüton' },
    answer: 'C',
    explanation: 'Uranüs\'ün eksen eğimi yaklaşık 98°\'dir; bu durum onu güneş sistemi boyunca âdeta "yuvarlanarak" ilerler gibi gösterir.',
  },
  {
    id: 'gen_43',
    text: 'What is the name of the process by which rocks are broken down by weather?',
    text_tr: 'Kayaların hava koşullarıyla parçalanma sürecinin adı nedir?',
    options: { A: 'Erosion', B: 'Weathering', C: 'Sedimentation', D: 'Metamorphism', E: 'Crystallization' },
    options_tr: { A: 'Erozyon', B: 'Ayrışma', C: 'Çökelme', D: 'Metamorfizm', E: 'Kristalleşme' },
    answer: 'B',
    explanation: 'Ayrışma (weathering), kayaların fiziksel veya kimyasal süreçlerle daha küçük parçalara bölünmesidir.',
  },
  {
    id: 'gen_44',
    text: 'Which animal is capable of regenerating its entire body from a small fragment?',
    text_tr: 'Küçük bir parçasından tüm vücudunu yeniden oluşturabilen hayvan hangisidir?',
    options: { A: 'Starfish', B: 'Salamander', C: 'Planarian flatworm', D: 'Gecko', E: 'Crab' },
    options_tr: { A: 'Denizyıldızı', B: 'Semender', C: 'Planarya (yassı solucan)', D: 'Kertenkele', E: 'Yengeç' },
    answer: 'C',
    explanation: 'Planarya yassı solucanı en olağanüstü rejenerasyon yeteneğine sahiptir; tek bir hücreden tüm yeni bir organizma oluşturabilir.',
  },
  {
    id: 'gen_45',
    text: 'What is the term for the point in Earth\'s orbit closest to the Sun?',
    text_tr: 'Dünya\'nın yörüngesinde Güneş\'e en yakın noktanın adı nedir?',
    options: { A: 'Aphelion', B: 'Perihelion', C: 'Apogee', D: 'Perigee', E: 'Zenith' },
    options_tr: { A: 'Afelyum', B: 'Perihelyum', C: 'Apoje', D: 'Perije', E: 'Zenit' },
    answer: 'B',
    explanation: 'Perihelyum, bir gezegenin yörüngesinde Güneş\'e en yakın olduğu noktadır; Dünya her yıl yaklaşık 3 Ocak\'ta perihelyumda olur.',
  },
  {
    id: 'gen_46',
    text: 'What is the most spoken language in the world by total number of speakers?',
    text_tr: 'Toplam konuşucu sayısı bakımından dünyada en çok konuşulan dil hangisidir?',
    options: { A: 'Spanish', B: 'Hindi', C: 'English', D: 'Mandarin Chinese', E: 'Arabic' },
    options_tr: { A: 'İspanyolca', B: 'Hintçe', C: 'İngilizce', D: 'Mandarin Çincesi', E: 'Arapça' },
    answer: 'C',
    explanation: 'İngilizce, anadil ve ikinci dil konuşucuları dahil edildiğinde yaklaşık 1,5 milyar konuşucuyla dünyada en çok kullanılan dildir.',
  },
  {
    id: 'gen_47',
    text: 'What is the name of the point directly overhead in the sky?',
    text_tr: 'Gökyüzünde tam tepemizde bulunan noktanın adı nedir?',
    options: { A: 'Nadir', B: 'Zenith', C: 'Azimuth', D: 'Apogee', E: 'Meridian' },
    options_tr: { A: 'Nadir', B: 'Zenit', C: 'Azimut', D: 'Apoje', E: 'Meridyen' },
    answer: 'B',
    explanation: 'Zenit, gözlemcinin tam tepesindeki gökyüzü noktasıdır; karşıtı (ayakların altındaki nokta) ise nadirdir.',
  },
  {
    id: 'gen_48',
    text: 'Which element is a liquid at room temperature and is also a metal?',
    text_tr: 'Oda sıcaklığında sıvı hâlde bulunan ve aynı zamanda metal olan element hangisidir?',
    options: { A: 'Bromine', B: 'Gallium', C: 'Mercury', D: 'Cesium', E: 'Francium' },
    options_tr: { A: 'Brom', B: 'Galyum', C: 'Cıva', D: 'Sezyum', E: 'Fransiyum' },
    answer: 'C',
    explanation: 'Cıva (Hg), oda sıcaklığında sıvı olan tek metaldir; erime noktası −38,83°C\'dir.',
  },
  {
    id: 'gen_49',
    text: 'What percentage of the Earth\'s surface is covered by water?',
    text_tr: 'Dünya yüzeyinin yüzde kaçı suyla kaplıdır?',
    options: { A: '51%', B: '61%', C: '71%', D: '81%', E: '91%' },
    options_tr: { A: '%51', B: '%61', C: '%71', D: '%81', E: '%91' },
    answer: 'C',
    explanation: 'Dünya yüzeyinin yaklaşık %71\'i suyla kaplıdır; bu suyun %97\'si tuzlu okyanuslardan oluşur.',
  },
  {
    id: 'gen_50',
    text: 'What is the smallest unit of life?',
    text_tr: 'Yaşamın en küçük birimi nedir?',
    options: { A: 'Atom', B: 'Molecule', C: 'Organelle', D: 'Cell', E: 'Tissue' },
    options_tr: { A: 'Atom', B: 'Molekül', C: 'Organel', D: 'Hücre', E: 'Doku' },
    answer: 'D',
    explanation: 'Hücre, tüm canlı organizmaların temel yapı ve işlevsel birimidir.',
  },
  {
    id: 'gen_51',
    text: 'Which is the tallest mountain in the world?',
    text_tr: 'Dünyanın en yüksek dağı hangisidir?',
    options: { A: 'K2', B: 'Kangchenjunga', C: 'Lhotse', D: 'Makalu', E: 'Mount Everest' },
    options_tr: { A: 'K2', B: 'Kangchenjunga', C: 'Lhotse', D: 'Makalu', E: 'Everest Dağı' },
    answer: 'E',
    explanation: 'Everest Dağı, 8.848 m yüksekliğiyle deniz seviyesinden ölçülen dünyanın en yüksek zirvesidir.',
  },
  {
    id: 'gen_52',
    text: 'What type of energy does the Sun primarily produce?',
    text_tr: 'Güneş öncelikli olarak ne tür enerji üretir?',
    options: { A: 'Fission energy', B: 'Chemical energy', C: 'Fusion energy', D: 'Geothermal energy', E: 'Kinetic energy' },
    options_tr: { A: 'Fisyon enerjisi', B: 'Kimyasal enerji', C: 'Füzyon enerjisi', D: 'Jeotermal enerji', E: 'Kinetik enerji' },
    answer: 'C',
    explanation: 'Güneş, çekirdeğinde hidrojen atomlarını helyuma birleştiren nükleer füzyon yoluyla enerji üretir.',
  },
  {
    id: 'gen_53',
    text: 'What is the name of the scientist who discovered penicillin?',
    text_tr: 'Penisilin\'i keşfeden bilim insanının adı nedir?',
    options: { A: 'Louis Pasteur', B: 'Robert Koch', C: 'Joseph Lister', D: 'Alexander Fleming', E: 'Edward Jenner' },
    options_tr: { A: 'Louis Pasteur', B: 'Robert Koch', C: 'Joseph Lister', D: 'Alexander Fleming', E: 'Edward Jenner' },
    answer: 'D',
    explanation: 'Alexander Fleming, 1928\'de Penicillium notatum küfünün bakterileri öldürdüğünü tesadüfen keşfetti.',
  },
  {
    id: 'gen_54',
    text: 'How many colors are in a rainbow?',
    text_tr: 'Bir gökkuşağında kaç renk bulunur?',
    options: { A: '5', B: '6', C: '7', D: '8', E: '9' },
    options_tr: { A: '5', B: '6', C: '7', D: '8', E: '9' },
    answer: 'C',
    explanation: 'Gökkuşağı yedi renkten oluşur: kırmızı, turuncu, sarı, yeşil, mavi, çivit ve mor (mor menekşe).',
  },
  {
    id: 'gen_55',
    text: 'Which type of rock is formed by the cooling of magma?',
    text_tr: 'Magmanın soğumasıyla oluşan kaya türü hangisidir?',
    options: { A: 'Sedimentary', B: 'Metamorphic', C: 'Igneous', D: 'Carbonate', E: 'Clastic' },
    options_tr: { A: 'Tortul', B: 'Başkalaşım', C: 'Magmatik', D: 'Karbonat', E: 'Kırıntılı' },
    answer: 'C',
    explanation: 'Magmatik kayaçlar, magmanın veya lavanın soğuyup katılaşmasıyla oluşur.',
  },
  {
    id: 'gen_56',
    text: 'What is the term for the bending of light as it passes from one medium to another?',
    text_tr: 'Işığın bir ortamdan diğerine geçerken kırılmasını ifade eden terim nedir?',
    options: { A: 'Reflection', B: 'Diffraction', C: 'Refraction', D: 'Dispersion', E: 'Absorption' },
    options_tr: { A: 'Yansıma', B: 'Kırınım', C: 'Kırılma', D: 'Dağılma', E: 'Soğurma' },
    answer: 'C',
    explanation: 'Kırılma, ışığın farklı yoğunluktaki bir ortama geçerken yön değiştirmesidir; prizmalar ve lensler bu ilkeyle çalışır.',
  },
  {
    id: 'gen_57',
    text: 'Which planet has the Great Red Spot, a storm larger than Earth?',
    text_tr: 'Dünya\'dan büyük bir fırtına olan Büyük Kırmızı Leke hangi gezegende bulunur?',
    options: { A: 'Saturn', B: 'Neptune', C: 'Uranus', D: 'Jupiter', E: 'Mars' },
    options_tr: { A: 'Satürn', B: 'Neptün', C: 'Uranüs', D: 'Jüpiter', E: 'Mars' },
    answer: 'D',
    explanation: 'Jüpiter\'deki Büyük Kırmızı Leke, 350 yılı aşkın süredir devam eden ve Dünya\'nın çapından büyük olan devasa bir kasırgadır.',
  },
  {
    id: 'gen_58',
    text: 'What is the name of the force that opposes the motion of objects through air?',
    text_tr: 'Hava içinden geçen nesnelerin hareketine karşı koyan kuvvetin adı nedir?',
    options: { A: 'Gravity', B: 'Friction', C: 'Drag (Air resistance)', D: 'Inertia', E: 'Tension' },
    options_tr: { A: 'Yerçekimi', B: 'Sürtünme', C: 'Hava direnci (sürükleme)', D: 'Eylemsizlik', E: 'Gerilme' },
    answer: 'C',
    explanation: 'Hava direnci (aerodinamik sürükleme), akışkan bir ortamda hareket eden nesnelere karşı uygulanan kuvvettir.',
  },
  {
    id: 'gen_59',
    text: 'Which vitamin deficiency causes scurvy?',
    text_tr: 'Hangi vitaminin eksikliği iskorbüte (skorbüt) yol açar?',
    options: { A: 'Vitamin A', B: 'Vitamin B1', C: 'Vitamin C', D: 'Vitamin D', E: 'Vitamin E' },
    options_tr: { A: 'A vitamini', B: 'B1 vitamini', C: 'C vitamini', D: 'D vitamini', E: 'E vitamini' },
    answer: 'C',
    explanation: 'İskorbüt, C vitamini (askorbik asit) eksikliğinden kaynaklanır; diş eti kanaması ve yara iyileşmesinin bozulmasıyla kendini gösterir.',
  },
  {
    id: 'gen_60',
    text: 'What is the chemical symbol for gold?',
    text_tr: 'Altının kimyasal sembolü nedir?',
    options: { A: 'Ag', B: 'Go', C: 'Gl', D: 'Gd', E: 'Au' },
    options_tr: { A: 'Ag', B: 'Go', C: 'Gl', D: 'Gd', E: 'Au' },
    answer: 'E',
    explanation: 'Altın\'ın sembolü Au\'dur; Latincede altın anlamına gelen "Aurum"dan gelir.',
  },
  {
    id: 'gen_61',
    text: 'What is the largest living structure on Earth?',
    text_tr: 'Dünya\'daki en büyük canlı yapı nedir?',
    options: { A: 'Amazon Rainforest', B: 'Great Barrier Reef', C: 'Siberian Taiga', D: 'Sahara Desert grasslands', E: 'Congo Basin' },
    options_tr: { A: 'Amazon Yağmur Ormanları', B: 'Büyük Set Resifi', C: 'Sibirya Tayga ormanları', D: 'Sahra çayırlıkları', E: 'Kongo Havzası' },
    answer: 'B',
    explanation: 'Avustralya\'daki Büyük Set Resifi, yaklaşık 344.400 km² alanıyla uzaydan görülebilen tek canlı yapıdır.',
  },
  {
    id: 'gen_62',
    text: 'Which gas is commonly used in advertising signs that glow when electrified?',
    text_tr: 'Elektriklendiğinde ışıyan reklam tabelalarında yaygın olarak kullanılan gaz hangisidir?',
    options: { A: 'Argon', B: 'Helium', C: 'Krypton', D: 'Neon', E: 'Xenon' },
    options_tr: { A: 'Argon', B: 'Helyum', C: 'Kripton', D: 'Neon', E: 'Ksenon' },
    answer: 'D',
    explanation: 'Neon gazı elektrik akımıyla uyarıldığında parlak kırmızı-turuncu ışık yayar; bu yüzden tabela ışıklarında kullanılır.',
  },
  {
    id: 'gen_63',
    text: 'What is the name of the galaxy nearest to the Milky Way?',
    text_tr: 'Samanyolu\'na en yakın galaksinin adı nedir?',
    options: { A: 'Large Magellanic Cloud', B: 'Triangulum Galaxy', C: 'Messier 81', D: 'Andromeda Galaxy', E: 'Whirlpool Galaxy' },
    options_tr: { A: 'Büyük Macellan Bulutu', B: 'Üçgen Galaksisi', C: 'Messier 81', D: 'Andromeda Galaksisi', E: 'Girdap Galaksisi' },
    answer: 'D',
    explanation: 'Andromeda (M31), Samanyolu\'na yaklaşık 2,537 milyon ışık yılı uzaklıkta bulunan en yakın büyük galaksidir.',
  },
  {
    id: 'gen_64',
    text: 'What does pH measure?',
    text_tr: 'pH neyi ölçer?',
    options: { A: 'Temperature of a solution', B: 'Electrical conductivity', C: 'Acidity or alkalinity of a solution', D: 'Concentration of a solution', E: 'Viscosity of a liquid' },
    options_tr: { A: 'Çözeltinin sıcaklığını', B: 'Elektriksel iletkenliği', C: 'Asitlik veya bazlık derecesini', D: 'Çözelti konsantrasyonunu', E: 'Sıvının viskozitesini' },
    answer: 'C',
    explanation: 'pH, bir çözeltinin asitliğini veya bazlığını ölçen 0–14 skalasıdır; 7 nötr, 7\'nin altı asit, üstü bazdır.',
  },
  {
    id: 'gen_65',
    text: 'Which blood cells are responsible for fighting infections?',
    text_tr: 'Enfeksiyonlarla savaşmaktan sorumlu kan hücreleri hangileridir?',
    options: { A: 'Red blood cells', B: 'Platelets', C: 'White blood cells', D: 'Plasma cells', E: 'Stem cells' },
    options_tr: { A: 'Kırmızı kan hücreleri', B: 'Trombositler', C: 'Beyaz kan hücreleri', D: 'Plazma hücreleri', E: 'Kök hücreler' },
    answer: 'C',
    explanation: 'Beyaz kan hücreleri (lökositler), bağışıklık sisteminin temel savunma elemanlarıdır.',
  },
  {
    id: 'gen_66',
    text: 'What is the study of fungi called?',
    text_tr: 'Mantarları inceleyen bilim dalının adı nedir?',
    options: { A: 'Botany', B: 'Mycology', C: 'Phycology', D: 'Lichenology', E: 'Microbiology' },
    options_tr: { A: 'Botanik', B: 'Mikoloji', C: 'Fikotoji', D: 'Likenoloji', E: 'Mikrobiyoloji' },
    answer: 'B',
    explanation: 'Mikoloji, mantarları inceleyen biyoloji dalıdır.',
  },
  {
    id: 'gen_67',
    text: 'What causes a lunar eclipse?',
    text_tr: 'Ay tutulmasına ne sebep olur?',
    options: { A: 'Moon passing between Earth and Sun', B: 'Earth passing between Sun and Moon', C: 'Sun passing between Earth and Moon', D: 'Moon moving farther from Earth', E: 'Clouds blocking sunlight' },
    options_tr: { A: 'Ay\'ın Dünya ile Güneş arasına girmesi', B: 'Dünya\'nın Güneş ile Ay arasına girmesi', C: 'Güneş\'in Dünya ile Ay arasına girmesi', D: 'Ay\'ın Dünya\'dan uzaklaşması', E: 'Bulutların güneş ışığını engellemesi' },
    answer: 'B',
    explanation: 'Ay tutulması, Dünya\'nın Güneş ile Ay arasına girerek Ay\'a düşen güneş ışığını engellemesiyle oluşur.',
  },
  {
    id: 'gen_68',
    text: 'Which natural phenomenon is measured by the Richter scale?',
    text_tr: 'Richter skalasıyla ölçülen doğal olay nedir?',
    options: { A: 'Hurricanes', B: 'Tsunamis', C: 'Tornadoes', D: 'Earthquakes', E: 'Volcanic eruptions' },
    options_tr: { A: 'Kasırgalar', B: 'Tsunamiler', C: 'Hortumlar', D: 'Depremler', E: 'Volkan patlamaları' },
    answer: 'D',
    explanation: 'Richter skalası, depremlerin büyüklüğünü (salınan enerji miktarını) ölçer.',
  },
  {
    id: 'gen_69',
    text: 'What is the main component of natural gas?',
    text_tr: 'Doğal gazın ana bileşeni nedir?',
    options: { A: 'Propane', B: 'Butane', C: 'Ethane', D: 'Methane', E: 'Hydrogen' },
    options_tr: { A: 'Propan', B: 'Bütan', C: 'Etan', D: 'Metan', E: 'Hidrojen' },
    answer: 'D',
    explanation: 'Doğal gaz büyük ölçüde metandan (CH₄) oluşur; genellikle %70–90 oranında metan içerir.',
  },
  {
    id: 'gen_70',
    text: 'What is the name of the process by which plants lose water through their leaves?',
    text_tr: 'Bitkilerin yaprakları aracılığıyla su kaybetme sürecinin adı nedir?',
    options: { A: 'Osmosis', B: 'Transpiration', C: 'Evaporation', D: 'Photosynthesis', E: 'Respiration' },
    options_tr: { A: 'Ozmoz', B: 'Terleme (transpirasyom)', C: 'Buharlaşma', D: 'Fotosentez', E: 'Solunum' },
    answer: 'B',
    explanation: 'Transpirasyon, su buharının bitki yapraklarındaki gözenekler (stoma) aracılığıyla atmosfere salınmasıdır.',
  },
  {
    id: 'gen_71',
    text: 'Which is the most abundant gas in the Sun\'s composition?',
    text_tr: 'Güneş\'in bileşimindeki en bol gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Nitrogen', C: 'Helium', D: 'Hydrogen', E: 'Carbon' },
    options_tr: { A: 'Oksijen', B: 'Azot', C: 'Helyum', D: 'Hidrojen', E: 'Karbon' },
    answer: 'D',
    explanation: 'Güneş kütlesinin yaklaşık %74\'ü hidrojen, %24\'ü helyumdur.',
  },
  {
    id: 'gen_72',
    text: 'What is the name of the outer layer of the Earth?',
    text_tr: 'Dünya\'nın dış katmanının adı nedir?',
    options: { A: 'Mantle', B: 'Core', C: 'Crust', D: 'Lithosphere', E: 'Asthenosphere' },
    options_tr: { A: 'Manto', B: 'Çekirdek', C: 'Kabuk', D: 'Litosfer', E: 'Astenosfer' },
    answer: 'C',
    explanation: 'Dünya kabuğu, gezegenin en dış katmanıdır; kalınlığı kıtalarda 30–50 km, okyanus tabanlarında 5–10 km arasındadır.',
  },
  {
    id: 'gen_73',
    text: 'What is the chemical symbol for silver?',
    text_tr: 'Gümüşün kimyasal sembolü nedir?',
    options: { A: 'Si', B: 'Sv', C: 'Ag', D: 'Sl', E: 'Sr' },
    options_tr: { A: 'Si', B: 'Sv', C: 'Ag', D: 'Sl', E: 'Sr' },
    answer: 'C',
    explanation: 'Gümüş\'ün sembolü Ag\'dır; Latincede "gümüş parlak" anlamına gelen "Argentum"dan gelir.',
  },
  {
    id: 'gen_74',
    text: 'What is the study of the Earth\'s physical structure called?',
    text_tr: 'Dünya\'nın fiziksel yapısını inceleyen bilim dalının adı nedir?',
    options: { A: 'Oceanography', B: 'Meteorology', C: 'Seismology', D: 'Geology', E: 'Cosmology' },
    options_tr: { A: 'Oşinografi', B: 'Meteoroloji', C: 'Sismoloji', D: 'Jeoloji', E: 'Kozmoloji' },
    answer: 'D',
    explanation: 'Jeoloji, Dünya\'nın katı maddesi, kabuğu ve tarihi süreçleri inceleyen bilim dalıdır.',
  },
  {
    id: 'gen_75',
    text: 'Which type of radiation has the shortest wavelength?',
    text_tr: 'En kısa dalga boyuna sahip radyasyon türü hangisidir?',
    options: { A: 'Radio waves', B: 'Infrared', C: 'Ultraviolet', D: 'X-rays', E: 'Gamma rays' },
    options_tr: { A: 'Radyo dalgaları', B: 'Kızılötesi', C: 'Morötesi', D: 'X-ışınları', E: 'Gama ışınları' },
    answer: 'E',
    explanation: 'Gama ışınları elektromanyetik spektrumun en yüksek enerjili ve en kısa dalgaboylu radyasyonudur.',
  },
  {
    id: 'gen_76',
    text: 'How many muscles are in the human body (approximately)?',
    text_tr: 'İnsan vücudunda yaklaşık kaç kas bulunur?',
    options: { A: '300', B: '450', C: '600', D: '750', E: '900' },
    options_tr: { A: '300', B: '450', C: '600', D: '750', E: '900' },
    answer: 'C',
    explanation: 'İnsan vücudunda yaklaşık 600 iskelet kası bulunur; bunların yanı sıra düz kaslar ve kalp kası da vardır.',
  },
  {
    id: 'gen_77',
    text: 'What is the most common element in the universe?',
    text_tr: 'Evrende en yaygın bulunan element hangisidir?',
    options: { A: 'Helium', B: 'Carbon', C: 'Oxygen', D: 'Hydrogen', E: 'Iron' },
    options_tr: { A: 'Helyum', B: 'Karbon', C: 'Oksijen', D: 'Hidrojen', E: 'Demir' },
    answer: 'D',
    explanation: 'Hidrojen, evrendeki bilinen tüm atomların yaklaşık %75\'ini oluşturan en bol elementtir.',
  },
  {
    id: 'gen_78',
    text: 'What phenomenon causes the sky to appear blue?',
    text_tr: 'Gökyüzünün mavi görünmesine hangi olgu neden olur?',
    options: { A: 'Refraction of sunlight', B: 'Reflection from the ocean', C: 'Rayleigh scattering of sunlight', D: 'Absorption of red light', E: 'Ozone layer reflection' },
    options_tr: { A: 'Güneş ışığının kırılması', B: 'Okyanusun yansıması', C: 'Güneş ışığının Rayleigh saçılması', D: 'Kırmızı ışığın soğurulması', E: 'Ozon katmanının yansıması' },
    answer: 'C',
    explanation: 'Rayleigh saçılması, güneş ışığının atmosferdeki gaz molekülleriyle etkileşiminde mavi ışığın daha fazla dağılmasına yol açar ve bu nedenle gökyüzü mavi görünür.',
  },
  {
    id: 'gen_79',
    text: 'Which animal has the highest blood pressure?',
    text_tr: 'En yüksek kan basıncına sahip hayvan hangisidir?',
    options: { A: 'Elephant', B: 'Blue Whale', C: 'Giraffe', D: 'Cheetah', E: 'Gorilla' },
    options_tr: { A: 'Fil', B: 'Mavi Balina', C: 'Zürafa', D: 'Çita', E: 'Goril' },
    answer: 'C',
    explanation: 'Zürafanın, beynine 2 metrelik boynu boyunca kan pompalayabilmek için 300/180 mmHg\'yi aşan olağanüstü yüksek kan basıncı vardır.',
  },
  {
    id: 'gen_80',
    text: 'What type of bond holds water molecules together (hydrogen bonding)?',
    text_tr: 'Su moleküllerini bir arada tutan bağ türü nedir?',
    options: { A: 'Ionic bond', B: 'Covalent bond', C: 'Hydrogen bond', D: 'Metallic bond', E: 'Van der Waals force' },
    options_tr: { A: 'İyonik bağ', B: 'Kovalent bağ', C: 'Hidrojen bağı', D: 'Metalik bağ', E: 'Van der Waals kuvvetleri' },
    answer: 'C',
    explanation: 'Su molekülleri arasındaki hidrojen bağları, suyun yüksek kaynama noktası ve yüzey gerilimi gibi olağanüstü özelliklerine yol açar.',
  },
  {
    id: 'gen_81',
    text: 'Which planet has the shortest day (fastest rotation)?',
    text_tr: 'Hangi gezegenin günü en kısadır (en hızlı döner)?',
    options: { A: 'Saturn', B: 'Uranus', C: 'Neptune', D: 'Jupiter', E: 'Mars' },
    options_tr: { A: 'Satürn', B: 'Uranüs', C: 'Neptün', D: 'Jüpiter', E: 'Mars' },
    answer: 'D',
    explanation: 'Jüpiter yaklaşık 9 saat 56 dakikada bir kez döner; bu onu güneş sisteminin en hızlı dönen gezegeni yapar.',
  },
  {
    id: 'gen_82',
    text: 'What is the name of the scale used to measure wind speed?',
    text_tr: 'Rüzgar hızını ölçmek için kullanılan skalanın adı nedir?',
    options: { A: 'Richter Scale', B: 'Fujita Scale', C: 'Saffir-Simpson Scale', D: 'Beaufort Scale', E: 'Mercalli Scale' },
    options_tr: { A: 'Richter Skalası', B: 'Fujita Skalası', C: 'Saffir-Simpson Skalası', D: 'Beaufort Skalası', E: 'Mercalli Skalası' },
    answer: 'D',
    explanation: 'Beaufort Skalası, 0 (durgun) ile 12 (kasırga) arasında rüzgar hızını ve kuvvetini tanımlar.',
  },
  {
    id: 'gen_83',
    text: 'What is the process of a caterpillar transforming into a butterfly called?',
    text_tr: 'Tırtılın kelebeğe dönüşme sürecinin adı nedir?',
    options: { A: 'Metamorphosis', B: 'Molting', C: 'Transfiguration', D: 'Evolution', E: 'Adaptation' },
    options_tr: { A: 'Başkalaşım (metamorfoz)', B: 'Deri değişimi', C: 'Dönüşüm', D: 'Evrim', E: 'Adaptasyon' },
    answer: 'A',
    explanation: 'Tam başkalaşım (holometabolizm), yumurta → larva (tırtıl) → pupa (krizalit) → ergin (kelebek) aşamalarından oluşur.',
  },
  {
    id: 'gen_84',
    text: 'Which element is the main component of the Sun?',
    text_tr: 'Güneş\'in ana bileşenini oluşturan element hangisidir?',
    options: { A: 'Carbon', B: 'Oxygen', C: 'Helium', D: 'Neon', E: 'Hydrogen' },
    options_tr: { A: 'Karbon', B: 'Oksijen', C: 'Helyum', D: 'Neon', E: 'Hidrojen' },
    answer: 'E',
    explanation: 'Güneş kütlesinin yaklaşık %73\'ü hidrojenden oluşur; bu hidrojen, nükleer füzyon yoluyla helyuma dönüştürülür.',
  },
  {
    id: 'gen_85',
    text: 'What is the name of the hormone responsible for regulating blood sugar?',
    text_tr: 'Kan şekerini düzenleyen hormonun adı nedir?',
    options: { A: 'Adrenaline', B: 'Cortisol', C: 'Insulin', D: 'Glucagon', E: 'Thyroxine' },
    options_tr: { A: 'Adrenalin', B: 'Kortizol', C: 'İnsülin', D: 'Glukagon', E: 'Tiroksin' },
    answer: 'C',
    explanation: 'İnsülin, pankreastaki beta hücreleri tarafından üretilen ve kan şekerini düşüren hormondur.',
  },
  {
    id: 'gen_86',
    text: 'What is the approximate age of the universe?',
    text_tr: 'Evrenin yaklaşık yaşı nedir?',
    options: { A: '4.6 billion years', B: '8.2 billion years', C: '10.5 billion years', D: '13.8 billion years', E: '20 billion years' },
    options_tr: { A: '4,6 milyar yıl', B: '8,2 milyar yıl', C: '10,5 milyar yıl', D: '13,8 milyar yıl', E: '20 milyar yıl' },
    answer: 'D',
    explanation: 'Evrenin yaşı, kozmik mikrodalga arka plan radyasyonu ölçümlerine dayanılarak yaklaşık 13,8 milyar yıl olarak hesaplanmıştır.',
  },
  {
    id: 'gen_87',
    text: 'What is the name of the protein that carries oxygen in the blood?',
    text_tr: 'Kanda oksijen taşıyan proteinin adı nedir?',
    options: { A: 'Myosin', B: 'Albumin', C: 'Keratin', D: 'Haemoglobin', E: 'Collagen' },
    options_tr: { A: 'Miyozin', B: 'Albumin', C: 'Keratin', D: 'Hemoglobin', E: 'Kolajen' },
    answer: 'D',
    explanation: 'Hemoglobin, kırmızı kan hücrelerinde bulunan ve demiri sayesinde akciğerlerden dokulara oksijen taşıyan proteindir.',
  },
  {
    id: 'gen_88',
    text: 'What is the SI unit of force?',
    text_tr: 'Kuvvetin SI birimi nedir?',
    options: { A: 'Joule', B: 'Watt', C: 'Newton', D: 'Pascal', E: 'Dyne' },
    options_tr: { A: 'Joule', B: 'Watt', C: 'Newton', D: 'Pascal', E: 'Din' },
    answer: 'C',
    explanation: 'Newton (N), Isaac Newton\'ın adından gelen kuvvet birimidir; 1 N = 1 kg·m/s² olarak tanımlanır.',
  },
  {
    id: 'gen_89',
    text: 'Which part of the plant conducts water from the roots to the leaves?',
    text_tr: 'Bitkide köklerden yapraklara su ileten bölüm nedir?',
    options: { A: 'Phloem', B: 'Epidermis', C: 'Cortex', D: 'Xylem', E: 'Cambium' },
    options_tr: { A: 'Floem', B: 'Epidermis', C: 'Korteks', D: 'Ksilem', E: 'Kambiyum' },
    answer: 'D',
    explanation: 'Ksilem, köklerden gövde ve yapraklara su ve mineral tuzlarını taşıyan iletim dokusudur.',
  },
  {
    id: 'gen_90',
    text: 'What is the name of the process through which atomic nuclei combine to release energy?',
    text_tr: 'Atom çekirdeklerinin birleşerek enerji salması sürecinin adı nedir?',
    options: { A: 'Fission', B: 'Fusion', C: 'Combustion', D: 'Oxidation', E: 'Radioactive decay' },
    options_tr: { A: 'Fisyon', B: 'Füzyon', C: 'Yanma', D: 'Oksidasyon', E: 'Radyoaktif bozunma' },
    answer: 'B',
    explanation: 'Nükleer füzyon, hafif çekirdeklerin (örneğin hidrojen) birleşerek daha ağır çekirdekler oluşturması ve bu sırada büyük miktarda enerji salmasıdır.',
  },
  {
    id: 'gen_91',
    text: 'How long does it take for light from the Sun to reach Earth?',
    text_tr: 'Güneş\'ten Dünya\'ya ışığın ulaşması ne kadar sürer?',
    options: { A: 'About 2 minutes', B: 'About 4 minutes', C: 'About 8 minutes', D: 'About 15 minutes', E: 'About 30 minutes' },
    options_tr: { A: 'Yaklaşık 2 dakika', B: 'Yaklaşık 4 dakika', C: 'Yaklaşık 8 dakika', D: 'Yaklaşık 15 dakika', E: 'Yaklaşık 30 dakika' },
    answer: 'C',
    explanation: 'Güneş\'ten Dünya\'ya ışık yaklaşık 8 dakika 20 saniyede ulaşır.',
  },
  {
    id: 'gen_92',
    text: 'What does "laser" stand for?',
    text_tr: '"Laser" (lazer) kısaltması neyi ifade eder?',
    options: { A: 'Light Amplification by Simulated Electromagnetic Radiation', B: 'Light Amplification by Stimulated Emission of Radiation', C: 'Linear Amplification of Spectral Energy Radiation', D: 'Luminous Array of Synchronised Energy Rays', E: 'Light Amplification by Standard Emission Rays' },
    options_tr: { A: 'Simüle Edilmiş Elektromanyetik Radyasyonla Işık Amplifikasyonu', B: 'Uyarılmış Emisyonla Radyasyonun Işık Amplifikasyonu', C: 'Spektral Enerji Radyasyonunun Doğrusal Amplifikasyonu', D: 'Senkronize Enerji Işınlarının Aydınlatma Dizisi', E: 'Standart Emisyon Işınlarıyla Işık Amplifikasyonu' },
    answer: 'B',
    explanation: 'LASER, "Light Amplification by Stimulated Emission of Radiation" ifadesinin kısaltmasıdır.',
  },
  {
    id: 'gen_93',
    text: 'Which is the smallest planet in our solar system?',
    text_tr: 'Güneş sistemimizin en küçük gezegeni hangisidir?',
    options: { A: 'Mars', B: 'Venus', C: 'Earth', D: 'Mercury', E: 'Pluto' },
    options_tr: { A: 'Mars', B: 'Venüs', C: 'Dünya', D: 'Merkür', E: 'Plüton' },
    answer: 'D',
    explanation: 'Merkür, güneş sisteminin en küçük gezegenidir (Plüton cüce gezegen statüsündedir).',
  },
  {
    id: 'gen_94',
    text: 'What is the name of the hormone produced during stress?',
    text_tr: 'Stres sırasında üretilen hormonun adı nedir?',
    options: { A: 'Serotonin', B: 'Dopamine', C: 'Cortisol', D: 'Oxytocin', E: 'Melatonin' },
    options_tr: { A: 'Serotonin', B: 'Dopamin', C: 'Kortizol', D: 'Oksitosin', E: 'Melatonin' },
    answer: 'C',
    explanation: 'Kortizol, strese tepki olarak böbreküstü bezlerinden salgılanan temel stres hormonudur.',
  },
  {
    id: 'gen_95',
    text: 'What is the name of the boundary between two tectonic plates?',
    text_tr: 'İki tektonik levha arasındaki sınırın adı nedir?',
    options: { A: 'Fault line', B: 'Rift', C: 'Tectonic boundary', D: 'Plate boundary', E: 'Seismic zone' },
    options_tr: { A: 'Fay hattı', B: 'Rift', C: 'Tektonik sınır', D: 'Levha sınırı', E: 'Sismik bölge' },
    answer: 'D',
    explanation: 'Levha sınırları, tektonik levhaların birbirleriyle temas ettiği alanlardır; depremler ve volkanik etkinlikler bu sınırlarda yoğunlaşır.',
  },
  {
    id: 'gen_96',
    text: 'Which type of telescope uses mirrors to collect light?',
    text_tr: 'Işık toplamak için ayna kullanan teleskop türü nedir?',
    options: { A: 'Refracting telescope', B: 'Radio telescope', C: 'Reflecting telescope', D: 'X-ray telescope', E: 'Infrared telescope' },
    options_tr: { A: 'Kırıcı teleskop', B: 'Radyo teleskobu', C: 'Yansıtmalı teleskop', D: 'X-ışını teleskobu', E: 'Kızılötesi teleskop' },
    answer: 'C',
    explanation: 'Yansıtmalı (reflektör) teleskoplar, ışığı toplamak ve odaklamak için ayna kullanır; Isaac Newton ilk yansıtmalı teleskobu 1668\'de yaptı.',
  },
  {
    id: 'gen_97',
    text: 'What is the function of the ozone layer?',
    text_tr: 'Ozon tabakasının işlevi nedir?',
    options: { A: 'Regulates Earth\'s temperature', B: 'Absorbs harmful UV radiation from the Sun', C: 'Produces oxygen for breathing', D: 'Reflects radio waves for communication', E: 'Filters harmful gamma rays' },
    options_tr: { A: 'Dünya\'nın sıcaklığını düzenler', B: 'Güneş\'ten gelen zararlı UV radyasyonunu emer', C: 'Nefes alınan oksijeni üretir', D: 'Radyo dalgalarını iletişim için yansıtır', E: 'Zararlı gama ışınlarını süzer' },
    answer: 'B',
    explanation: 'Stratosferdeki ozon tabakası, canlılar için zararlı olan Güneş\'in UV-B ve UV-C radyasyonunun büyük bölümünü emer.',
  },
  {
    id: 'gen_98',
    text: 'What causes the Northern Lights (Aurora Borealis)?',
    text_tr: 'Kuzey Işıklarına (Kuzey Kutbu Işıması) ne sebep olur?',
    options: { A: 'Moonlight reflecting off ice crystals', B: 'Solar wind particles colliding with Earth\'s atmosphere', C: 'Volcanic gases in the upper atmosphere', D: 'Refraction of sunlight near the poles', E: 'Cosmic radiation hitting the stratosphere' },
    options_tr: { A: 'Ay ışığının buz kristallerinden yansıması', B: 'Güneş rüzgarı parçacıklarının Dünya atmosferiyle çarpışması', C: 'Üst atmosferdeki volkanik gazlar', D: 'Kutuplar yakınında güneş ışığının kırılması', E: 'Kozmik radyasyonun stratosfere çarpması' },
    answer: 'B',
    explanation: 'Kuzey Işıkları, manyetik alan boyunca atmosfere giren güneş rüzgarı parçacıklarının oksijen ve azot atomlarıyla çarpışması sonucu oluşur.',
  },
  {
    id: 'gen_99',
    text: 'What is the name of the coloured part of the human eye?',
    text_tr: 'İnsan gözünün renkli bölümünün adı nedir?',
    options: { A: 'Pupil', B: 'Retina', C: 'Cornea', D: 'Iris', E: 'Sclera' },
    options_tr: { A: 'Göz bebeği', B: 'Retina', C: 'Kornea', D: 'İris', E: 'Sklera' },
    answer: 'D',
    explanation: 'İris, göze rengini veren ve ışık miktarını düzenlemek için göz bebeğinin boyutunu kontrol eden halka biçimli kas yapıdır.',
  },
  {
    id: 'gen_100',
    text: 'Which Turkish scientist is known for his work on rocket propulsion and is called the father of modern rocketry?',
    text_tr: 'Roket itiş gücü alanındaki çalışmalarıyla tanınan ve modern roketchiliğin babası olarak anılan bilim insanı kimdir?',
    options: { A: 'Aziz Sancar', B: 'Cahit Arf', C: 'Oktay Sinanoğlu', D: 'Feza Gürsey', E: 'Ali Kuşçu' },
    options_tr: { A: 'Aziz Sancar', B: 'Cahit Arf', C: 'Oktay Sinanoğlu', D: 'Feza Gürsey', E: 'Ali Kuşçu' },
    answer: 'E',
    explanation: 'Ali Kuşçu (1403–1474), Osmanlı döneminin önde gelen astronomu ve matematikçisidir; Fatih Sultan Mehmet\'in daveti üzerine İstanbul\'a gelmiş ve astronomi alanındaki özgün çalışmalarıyla tanınmıştır.',
  },

  // --- Batch 2 (gen_101–gen_200) ---
  {
    id: 'gen_102',
    text: 'Which planet is known as the Red Planet?',
    text_tr: 'Kızıl Gezegen olarak bilinen gezegen hangisidir?',
    options: { A: 'Venus', B: 'Mars', C: 'Jupiter', D: 'Saturn', E: 'Mercury' },
    options_tr: { A: 'Venüs', B: 'Mars', C: 'Jüpiter', D: 'Satürn', E: 'Merkür' },
    answer: 'B',
    explanation: 'Mars is called the Red Planet due to the iron oxide (rust) on its surface.',
  },
  {
    id: 'gen_103',
    text: 'Who painted the famous "Mona Lisa"?',
    text_tr: '"Mona Lisa" adlı ünlü tabloyu kim yapmıştır?',
    options: { A: 'Vincent van Gogh', B: 'Pablo Picasso', C: 'Leonardo da Vinci', D: 'Michelangelo', E: 'Claude Monet' },
    options_tr: { A: 'Vincent van Gogh', B: 'Pablo Picasso', C: 'Leonardo da Vinci', D: 'Michelangelo', E: 'Claude Monet' },
    answer: 'C',
    explanation: 'The Mona Lisa was painted by the Italian Renaissance polymath Leonardo da Vinci in the early 16th century.',
  },
  {
    id: 'gen_105',
    text: 'Which country is the largest by land area?',
    text_tr: 'Yüzölçümü bakımından en büyük ülke hangisidir?',
    options: { A: 'Canada', B: 'China', C: 'United States', D: 'Russia', E: 'Brazil' },
    options_tr: { A: 'Kanada', B: 'Çin', C: 'Amerika Birleşik Devletleri', D: 'Rusya', E: 'Brezilya' },
    answer: 'D',
    explanation: 'Russia is the largest country in the world, covering more than one-eighth of Earth\'s inhabited land area.',
  },
  {
    id: 'gen_106',
    text: 'How many bones are there in an adult human body?',
    text_tr: 'Yetişkin bir insan vücudunda kaç kemik bulunur?',
    options: { A: '106', B: '206', C: '306', D: '406', E: '506' },
    options_tr: { A: '106', B: '206', C: '306', D: '406', E: '506' },
    answer: 'B',
    explanation: 'An adult human skeleton has 206 bones, though babies are born with around 270 bones that fuse over time.',
  },
  {
    id: 'gen_107',
    text: 'Which ocean is the largest and deepest on Earth?',
    text_tr: 'Dünyadaki en büyük ve en derin okyanus hangisidir?',
    options: { A: 'Atlantic Ocean', B: 'Indian Ocean', C: 'Arctic Ocean', D: 'Pacific Ocean', E: 'Southern Ocean' },
    options_tr: { A: 'Atlas Okyanusu', B: 'Hint Okyanusu', C: 'Arktik Okyanusu', D: 'Büyük Okyanus (Pasifik)', E: 'Güney Okyanusu' },
    answer: 'D',
    explanation: 'The Pacific Ocean is the largest and deepest of Earth\'s oceanic divisions, containing the Mariana Trench.',
  },
  {
    id: 'gen_108',
    text: 'Who wrote the play "Romeo and Juliet"?',
    text_tr: '"Romeo ve Juliet" oyununu kim yazmıştır?',
    options: { A: 'Charles Dickens', B: 'William Shakespeare', C: 'Mark Twain', D: 'Jane Austen', E: 'George Orwell' },
    options_tr: { A: 'Charles Dickens', B: 'William Shakespeare', C: 'Mark Twain', D: 'Jane Austen', E: 'George Orwell' },
    answer: 'B',
    explanation: 'Romeo and Juliet is a tragedy written by William Shakespeare early in his career.',
  },
  {
    id: 'gen_109',
    text: 'What is the capital city of Japan?',
    text_tr: 'Japonya\'nın başkenti hangi şehirdir?',
    options: { A: 'Kyoto', B: 'Osaka', C: 'Seoul', D: 'Beijing', E: 'Tokyo' },
    options_tr: { A: 'Kyoto', B: 'Osaka', C: 'Seul', D: 'Pekin', E: 'Tokyo' },
    answer: 'E',
    explanation: 'Tokyo is the capital and most populous city of Japan.',
  },
  {
    id: 'gen_110',
    text: 'What gas do plants absorb from the atmosphere during photosynthesis?',
    text_tr: 'Bitkiler fotosentez sırasında atmosferden hangi gazı emer?',
    options: { A: 'Oxygen', B: 'Nitrogen', C: 'Carbon Dioxide', D: 'Hydrogen', E: 'Helium' },
    options_tr: { A: 'Oksijen', B: 'Azot', C: 'Karbondioksit', D: 'Hidrojen', E: 'Helyum' },
    answer: 'C',
    explanation: 'Plants absorb carbon dioxide and water to produce glucose and oxygen using sunlight.',
  },
  {
    id: 'gen_111',
    text: 'In which year did the Titanic sink?',
    text_tr: 'Titanik gemisi hangi yılda batmıştır?',
    options: { A: '1905', B: '1912', C: '1918', D: '1923', E: '1939' },
    options_tr: { A: '1905', B: '1912', C: '1918', D: '1923', E: '1939' },
    answer: 'B',
    explanation: 'The Titanic sank on April 15, 1912, during its maiden voyage after colliding with an iceberg.',
  },
  {
    id: 'gen_112',
    text: 'Which country gifted the Statue of Liberty to the United States?',
    text_tr: 'Özgürlük Anıtı\'nı Amerika Birleşik Devletleri\'ne hangi ülke hediye etmiştir?',
    options: { A: 'United Kingdom', B: 'France', C: 'Germany', D: 'Italy', E: 'Spain' },
    options_tr: { A: 'Birleşik Krallık', B: 'Fransa', C: 'Almanya', D: 'İtalya', E: 'İspanya' },
    answer: 'B',
    explanation: 'The Statue of Liberty was a gift from France to the United States to celebrate their revolutionary alliance.',
  },
  {
    id: 'gen_113',
    text: 'What is the currency of the United Kingdom?',
    text_tr: 'Birleşik Krallık\'ın para birimi nedir?',
    options: { A: 'Euro', B: 'Dollar', C: 'Pound Sterling', D: 'Franc', E: 'Yen' },
    options_tr: { A: 'Euro', B: 'Dolar', C: 'Sterlin (Pound)', D: 'Frank', E: 'Yen' },
    answer: 'C',
    explanation: 'The official currency of the United Kingdom is the Pound Sterling (£).',
  },
  {
    id: 'gen_114',
    text: 'Which instrument is used to measure atmospheric pressure?',
    text_tr: 'Atmosfer basıncını ölçmek için hangi alet kullanılır?',
    options: { A: 'Thermometer', B: 'Barometer', C: 'Anemometer', D: 'Hygrometer', E: 'Altimeter' },
    options_tr: { A: 'Termometre', B: 'Barometre', C: 'Anemometre', D: 'Higrometre', E: 'Altimetre' },
    answer: 'B',
    explanation: 'A barometer is a scientific instrument used to measure atmospheric pressure.',
  },
  {
    id: 'gen_115',
    text: 'Who is known as the father of modern physics?',
    text_tr: 'Modern fiziğin babası olarak bilinen kimdir?',
    options: { A: 'Isaac Newton', B: 'Albert Einstein', C: 'Galileo Galilei', D: 'Nikola Tesla', E: 'Marie Curie' },
    options_tr: { A: 'Isaac Newton', B: 'Albert Einstein', C: 'Galileo Galilei', D: 'Nikola Tesla', E: 'Marie Curie' },
    answer: 'B',
    explanation: 'Albert Einstein developed the theory of relativity, one of the two pillars of modern physics.',
  },
  {
    id: 'gen_116',
    text: 'Which continent is the Sahara Desert located in?',
    text_tr: 'Sahra Çölü hangi kıtadadır?',
    options: { A: 'Asia', B: 'Australia', C: 'Africa', D: 'South America', E: 'North America' },
    options_tr: { A: 'Asya', B: 'Avustralya', C: 'Afrika', D: 'Güney Amerika', E: 'Kuzey Amerika' },
    answer: 'C',
    explanation: 'The Sahara is the largest hot desert in the world, covering much of North Africa.',
  },
  {
    id: 'gen_117',
    text: 'Which country is the origin of the Olympic Games?',
    text_tr: 'Olimpiyat Oyunları\'nın kökeni hangi ülkedir?',
    options: { A: 'Italy', B: 'Greece', C: 'Egypt', D: 'China', E: 'France' },
    options_tr: { A: 'İtalya', B: 'Yunanistan', C: 'Mısır', D: 'Çin', E: 'Fransa' },
    answer: 'B',
    explanation: 'The ancient Olympic Games began in Olympia, Greece, in 776 BC.',
  },
  {
    id: 'gen_118',
    text: 'Who discovered penicillin?',
    text_tr: 'Penisilini kim keşfetmiştir?',
    options: { A: 'Louis Pasteur', B: 'Alexander Fleming', C: 'Marie Curie', D: 'Robert Koch', E: 'Gregor Mendel' },
    options_tr: { A: 'Louis Pasteur', B: 'Alexander Fleming', C: 'Marie Curie', D: 'Robert Koch', E: 'Gregor Mendel' },
    answer: 'B',
    explanation: 'Alexander Fleming discovered penicillin, the world\'s first effective antibiotic, in 1928.',
  },
  {
    id: 'gen_119',
    text: 'Which is the smallest country in the world?',
    text_tr: 'Dünyanın en küçük ülkesi hangisidir?',
    options: { A: 'Monaco', B: 'San Marino', C: 'Liechtenstein', D: 'Vatican City', E: 'Malta' },
    options_tr: { A: 'Monako', B: 'San Marino', C: 'Lihtenştayn', D: 'Vatikan', E: 'Malta' },
    answer: 'D',
    explanation: 'Vatican City is the smallest independent state in the world by both area and population.',
  },
  {
    id: 'gen_120',
    text: 'Who was the first person to step on the Moon?',
    text_tr: 'Ay\'a ayak basan ilk insan kimdir?',
    options: { A: 'Yuri Gagarin', B: 'Buzz Aldrin', C: 'Neil Armstrong', D: 'Michael Collins', E: 'John Glenn' },
    options_tr: { A: 'Yuri Gagarin', B: 'Buzz Aldrin', C: 'Neil Armstrong', D: 'Michael Collins', E: 'John Glenn' },
    answer: 'C',
    explanation: 'Neil Armstrong stepped onto the lunar surface on July 20, 1969, during the Apollo 11 mission.',
  },
  {
    id: 'gen_121',
    text: 'Which country is known as the Land of the Rising Sun?',
    text_tr: 'Hangi ülke "Doğan Güneşin Ülkesi" olarak bilinir?',
    options: { A: 'China', B: 'Japan', C: 'South Korea', D: 'Thailand', E: 'Vietnam' },
    options_tr: { A: 'Çin', B: 'Japonya', C: 'Güney Kore', D: 'Tayland', E: 'Vietnam' },
    answer: 'B',
    explanation: 'The name "Japan" translates to "sun origin", which is why it is called the Land of the Rising Sun.',
  },
  {
    id: 'gen_122',
    text: 'What is the largest mammal in the world?',
    text_tr: 'Dünyadaki en büyük memeli hayvan hangisidir?',
    options: { A: 'African Elephant', B: 'Blue Whale', C: 'Giraffe', D: 'Colossal Squid', E: 'Hippopotamus' },
    options_tr: { A: 'Afrika Fili', B: 'Mavi Balina', C: 'Zürafa', D: 'Dev Mürekkepbalığı', E: 'Su Aygırı' },
    answer: 'B',
    explanation: 'The Blue Whale is the largest animal known to have ever existed, reaching lengths of up to 30 meters.',
  },
  {
    id: 'gen_123',
    text: 'In which city is the Eiffel Tower located?',
    text_tr: 'Eyfel Kulesi hangi şehirdedir?',
    options: { A: 'London', B: 'Rome', C: 'Paris', D: 'Berlin', E: 'Madrid' },
    options_tr: { A: 'Londra', B: 'Roma', C: 'Paris', D: 'Berlin', E: 'Madrid' },
    answer: 'C',
    explanation: 'The Eiffel Tower is a globally recognized landmark located in Paris, France.',
  },
  {
    id: 'gen_124',
    text: 'Which is the largest hot desert in the world?',
    text_tr: 'Dünyadaki en büyük sıcak çöl hangisidir?',
    options: { A: 'Gobi Desert', B: 'Kalahari Desert', C: 'Sahara Desert', D: 'Arabian Desert', E: 'Atacama Desert' },
    options_tr: { A: 'Gobi Çölü', B: 'Kalahari Çölü', C: 'Sahra Çölü', D: 'Arap Çölü', E: 'Atacama Çölü' },
    answer: 'C',
    explanation: 'The Sahara Desert is the largest hot desert (Antarctica and the Arctic are larger but are cold deserts).',
  },
  {
    id: 'gen_125',
    text: 'Who wrote the epic fantasy novel series "The Lord of the Rings"?',
    text_tr: '"Yüzüklerin Efendisi" fantastik roman serisini kim yazmıştır?',
    options: { A: 'George R.R. Martin', B: 'J.K. Rowling', C: 'C.S. Lewis', D: 'J.R.R. Tolkien', E: 'Stephen King' },
    options_tr: { A: 'George R.R. Martin', B: 'J.K. Rowling', C: 'C.S. Lewis', D: 'J.R.R. Tolkien', E: 'Stephen King' },
    answer: 'D',
    explanation: 'The Lord of the Rings was written by English author and scholar J.R.R. Tolkien.',
  },
  {
    id: 'gen_126',
    text: 'What is the capital city of Canada?',
    text_tr: 'Kanada\'nın başkenti hangi şehirdir?',
    options: { A: 'Toronto', B: 'Vancouver', C: 'Montreal', D: 'Ottawa', E: 'Calgary' },
    options_tr: { A: 'Toronto', B: 'Vancouver', C: 'Montreal', D: 'Ottawa', E: 'Calgary' },
    answer: 'D',
    explanation: 'Ottawa was chosen as the capital of Canada by Queen Victoria in 1857.',
  },
  {
    id: 'gen_127',
    text: 'Which country hosted the 2022 FIFA World Cup?',
    text_tr: '2022 FIFA Dünya Kupası\'na hangi ülke ev sahipliği yapmıştır?',
    options: { A: 'Brazil', B: 'Qatar', C: 'Russia', D: 'France', E: 'Germany' },
    options_tr: { A: 'Brezilya', B: 'Katar', C: 'Rusya', D: 'Fransa', E: 'Almanya' },
    answer: 'B',
    explanation: 'The 2022 FIFA World Cup took place in Qatar, marking the first World Cup held in the Arab world.',
  },
  {
    id: 'gen_128',
    text: 'What is the primary language spoken in Brazil?',
    text_tr: 'Brezilya\'da konuşulan ana dil hangisidir?',
    options: { A: 'Spanish', B: 'Portuguese', C: 'English', D: 'French', E: 'Italian' },
    options_tr: { A: 'İspanyolca', B: 'Portekizce', C: 'İngilizce', D: 'Fransızca', E: 'İtalyanca' },
    answer: 'B',
    explanation: 'Brazil was colonized by Portugal, making Portuguese its official and primary language.',
  },
  {
    id: 'gen_129',
    text: 'Which company developed the Android mobile operating system?',
    text_tr: 'Android mobil işletim sistemini hangi şirket geliştirmiştir?',
    options: { A: 'Apple', B: 'Microsoft', C: 'Google', D: 'Samsung', E: 'Nokia' },
    options_tr: { A: 'Apple', B: 'Microsoft', C: 'Google', D: 'Samsung', E: 'Nokia' },
    answer: 'C',
    explanation: 'Android was founded in 2003 and acquired by Google in 2005.',
  },
  {
    id: 'gen_130',
    text: 'Who is the author of the "Harry Potter" book series?',
    text_tr: '"Harry Potter" kitap serisinin yazarı kimdir?',
    options: { A: 'J.K. Rowling', B: 'Stephenie Meyer', C: 'Suzanne Collins', D: 'Rick Riordan', E: 'George R.R. Martin' },
    options_tr: { A: 'J.K. Rowling', B: 'Stephenie Meyer', C: 'Suzanne Collins', D: 'Rick Riordan', E: 'George R.R. Martin' },
    answer: 'A',
    explanation: 'The Harry Potter fantasy series was written by British author J.K. Rowling.',
  },
  {
    id: 'gen_131',
    text: 'Which is the largest country in South America by area?',
    text_tr: 'Yüzölçümü bakımından Güney Amerika\'nın en büyük ülkesi hangisidir?',
    options: { A: 'Argentina', B: 'Colombia', C: 'Peru', D: 'Brazil', E: 'Chile' },
    options_tr: { A: 'Arjantin', B: 'Kolombiya', C: 'Peru', D: 'Brezilya', E: 'Şili' },
    answer: 'D',
    explanation: 'Brazil is the largest country in both South America and Latin America.',
  },
  {
    id: 'gen_132',
    text: 'Which basic force keeps us on the ground?',
    text_tr: 'Bizi yerde tutan temel kuvvet hangisidir?',
    options: { A: 'Magnetism', B: 'Friction', C: 'Gravity', D: 'Centrifugal Force', E: 'Nuclear Force' },
    options_tr: { A: 'Manyetizma', B: 'Sürtünme', C: 'Yerçekimi', D: 'Santrifüj Kuvveti', E: 'Nükleer Kuvvet' },
    answer: 'C',
    explanation: 'Gravity is the force by which a planet or other body draws objects toward its center.',
  },
  {
    id: 'gen_133',
    text: 'What is the capital city of Italy?',
    text_tr: 'İtalya\'nın başkenti hangi şehirdir?',
    options: { A: 'Milan', B: 'Venice', C: 'Florence', D: 'Rome', E: 'Naples' },
    options_tr: { A: 'Milano', B: 'Venedik', C: 'Floransa', D: 'Roma', E: 'Napoli' },
    answer: 'D',
    explanation: 'Rome is the capital and largest city of Italy.',
  },
  {
    id: 'gen_134',
    text: 'Which gas is most vital for human respiration?',
    text_tr: 'İnsan solunumu için en hayati gaz hangisidir?',
    options: { A: 'Nitrogen', B: 'Oxygen', C: 'Carbon Dioxide', D: 'Hydrogen', E: 'Helium' },
    options_tr: { A: 'Azot', B: 'Oksijen', C: 'Karbondioksit', D: 'Hidrojen', E: 'Helyum' },
    answer: 'B',
    explanation: 'Humans require oxygen to convert glucose into usable energy (ATP) through cellular respiration.',
  },
  {
    id: 'gen_135',
    text: 'Who is known as the founder of the Republic of Turkey?',
    text_tr: 'Türkiye Cumhuriyeti\'nin kurucusu olarak bilinen lider kimdir?',
    options: { A: 'İsmet İnönü', B: 'Mustafa Kemal Atatürk', C: 'Adnan Menderes', D: 'Fevzi Çakmak', E: 'Kazım Karabekir' },
    options_tr: { A: 'İsmet İnönü', B: 'Mustafa Kemal Atatürk', C: 'Adnan Menderes', D: 'Fevzi Çakmak', E: 'Kazım Karabekir' },
    answer: 'B',
    explanation: 'Mustafa Kemal Atatürk founded the Republic of Turkey in 1923.',
  },
  {
    id: 'gen_136',
    text: 'What is the largest island in the world?',
    text_tr: 'Dünyanın en büyük adası hangisidir?',
    options: { A: 'Madagascar', B: 'Greenland', C: 'Borneo', D: 'New Guinea', E: 'Iceland' },
    options_tr: { A: 'Madagaskar', B: 'Grönland', C: 'Borneo', D: 'Yeni Gine', E: 'İzlanda' },
    answer: 'B',
    explanation: 'Greenland is the world\'s largest island (Australia is classified as a continent).',
  },
  {
    id: 'gen_137',
    text: 'Which historic structure in Istanbul was originally built as a Christian cathedral and is now a mosque?',
    text_tr: 'İstanbul\'da başlangıçta Hristiyan katedrali olarak inşa edilen ve günümüzde cami olan tarihi yapı hangisidir?',
    options: { A: 'Topkapi Palace', B: 'Blue Mosque', C: 'Hagia Sophia', D: 'Galata Tower', E: 'Süleymaniye Mosque' },
    options_tr: { A: 'Topkapı Sarayı', B: 'Sultanahmet Camii', C: 'Ayasofya', D: 'Galata Kulesi', E: 'Süleymaniye Camii' },
    answer: 'C',
    explanation: 'Hagia Sophia was built in 537 AD as a cathedral, converted to a mosque in 1453, became a museum in 1935, and reverted to a mosque in 2020.',
  },
  {
    id: 'gen_138',
    text: 'What is the capital city of France?',
    text_tr: 'Fransa\'nın başkenti hangi şehirdir?',
    options: { A: 'Lyon', B: 'Marseille', C: 'Nice', D: 'Paris', E: 'Bordeaux' },
    options_tr: { A: 'Lyon', B: 'Marsilya', C: 'Nice', D: 'Paris', E: 'Bordeaux' },
    answer: 'D',
    explanation: 'Paris is the capital and largest city of France.',
  },
  {
    id: 'gen_139',
    text: 'What is the approximate speed of light?',
    text_tr: 'Işık hızı yaklaşık olarak ne kadardır?',
    options: { A: '3,000 km/s', B: '30,000 km/s', C: '300,000 km/s', D: '3,000,000 km/s', E: '30,000,000 km/s' },
    options_tr: { A: '3.000 km/s', B: '30.000 km/s', C: '300.000 km/s', D: '3.000.000 km/s', E: '30.000.000 km/s' },
    answer: 'C',
    explanation: 'Light travels at approximately 300,000 km/s in a vacuum.',
  },
  {
    id: 'gen_140',
    text: 'Which is the tallest mountain in the world above sea level?',
    text_tr: 'Deniz seviyesinden yüksekte olan dünyadaki en yüksek dağ hangisidir?',
    options: { A: 'K2', B: 'Mount Kilimanjaro', C: 'Mount Everest', D: 'Mont Blanc', E: 'Mount Fuji' },
    options_tr: { A: 'K2', B: 'Kilimanjaro Dağı', C: 'Everest Dağı', D: 'Mont Blanc', E: 'Fuji Dağı' },
    answer: 'C',
    explanation: 'Mount Everest, located in the Himalayas, is Earth\'s highest mountain above sea level at 8,848 m.',
  },
  {
    id: 'gen_141',
    text: 'In which country are the ancient Pyramids of Giza located?',
    text_tr: 'Giza Piramitleri hangi ülkede yer almaktadır?',
    options: { A: 'Greece', B: 'Mexico', C: 'Egypt', D: 'Peru', E: 'Iran' },
    options_tr: { A: 'Yunanistan', B: 'Meksika', C: 'Mısır', D: 'Peru', E: 'İran' },
    answer: 'C',
    explanation: 'The Pyramids of Giza are located on the Giza Plateau near Cairo, Egypt.',
  },
  {
    id: 'gen_142',
    text: 'What is the chemical symbol for Sodium?',
    text_tr: 'Sodyum elementinin kimyasal sembolü nedir?',
    options: { A: 'S', B: 'So', C: 'Na', D: 'Sd', E: 'K' },
    options_tr: { A: 'S', B: 'So', C: 'Na', D: 'Sd', E: 'K' },
    answer: 'C',
    explanation: 'The symbol "Na" comes from the Latin word "natrium".',
  },
  {
    id: 'gen_143',
    text: 'How many elements are currently listed on the standard Periodic Table?',
    text_tr: 'Standart Periyodik Tablo\'da şu anda kaç element listelenmiştir?',
    options: { A: '92', B: '104', C: '112', D: '118', E: '124' },
    options_tr: { A: '92', B: '104', C: '112', D: '118', E: '124' },
    answer: 'D',
    explanation: 'The periodic table has 118 confirmed elements, from Hydrogen (1) to Oganesson (118).',
  },
  {
    id: 'gen_144',
    text: 'Which blood type is known as the universal donor?',
    text_tr: 'Hangi kan grubu "genel verici" olarak bilinir?',
    options: { A: 'A Positive', B: 'B Negative', C: 'O Negative', D: 'AB Positive', E: 'O Positive' },
    options_tr: { A: 'A Pozitif', B: 'B Negatif', C: 'O Negatif', D: 'AB Pozitif', E: 'O Pozitif' },
    answer: 'C',
    explanation: 'O negative blood can be given to patients of any blood type.',
  },
  {
    id: 'gen_145',
    text: 'What is the standard currency used by the majority of European Union members?',
    text_tr: 'Avrupa Birliği üyelerinin çoğunluğu tarafından kullanılan ortak para birimi nedir?',
    options: { A: 'Pound', B: 'Franc', C: 'Euro', D: 'Krona', E: 'Lira' },
    options_tr: { A: 'Sterlin', B: 'Frank', C: 'Euro', D: 'Kuron', E: 'Lira' },
    answer: 'C',
    explanation: 'The Euro (€) is the official currency of the eurozone.',
  },
  {
    id: 'gen_146',
    text: 'Which is the largest bone in the human body?',
    text_tr: 'İnsan vücudundaki en büyük kemik hangisidir?',
    options: { A: 'Femur', B: 'Tibia', C: 'Humerus', D: 'Skull', E: 'Pelvis' },
    options_tr: { A: 'Uyluk Kemiği (Femur)', B: 'Kaval Kemiği', C: 'Pazı Kemiği', D: 'Kafatası', E: 'Leğen Kemiği' },
    answer: 'A',
    explanation: 'The femur, or thigh bone, is both the longest and strongest bone in the human body.',
  },
  {
    id: 'gen_147',
    text: 'Which country is shaped like a boot?',
    text_tr: 'Çizme şeklinde olan ülke hangisidir?',
    options: { A: 'Greece', B: 'Spain', C: 'Italy', D: 'Portugal', E: 'France' },
    options_tr: { A: 'Yunanistan', B: 'İspanya', C: 'İtalya', D: 'Portekiz', E: 'Fransa' },
    answer: 'C',
    explanation: 'Italy\'s peninsular shape on maps heavily resembles a high-heeled boot.',
  },
  {
    id: 'gen_148',
    text: 'Who developed the three laws of motion?',
    text_tr: 'Hareketin üç yasasını kim geliştirmiştir?',
    options: { A: 'Albert Einstein', B: 'Isaac Newton', C: 'Galileo Galilei', D: 'Marie Curie', E: 'Stephen Hawking' },
    options_tr: { A: 'Albert Einstein', B: 'Isaac Newton', C: 'Galileo Galilei', D: 'Marie Curie', E: 'Stephen Hawking' },
    answer: 'B',
    explanation: 'Sir Isaac Newton published these laws in "Principia Mathematica" in 1687.',
  },
  {
    id: 'gen_149',
    text: 'What is the capital city of Germany?',
    text_tr: 'Almanya\'nın başkenti hangi şehirdir?',
    options: { A: 'Munich', B: 'Frankfurt', C: 'Berlin', D: 'Hamburg', E: 'Cologne' },
    options_tr: { A: 'Münih', B: 'Frankfurt', C: 'Berlin', D: 'Hamburg', E: 'Köln' },
    answer: 'C',
    explanation: 'Berlin became the official capital of reunified Germany in 1990.',
  },
  {
    id: 'gen_150',
    text: 'Which animal is the fastest land mammal?',
    text_tr: 'Karadaki en hızlı memeli hayvan hangisidir?',
    options: { A: 'Lion', B: 'Cheetah', C: 'Leopard', D: 'Antelope', E: 'Horse' },
    options_tr: { A: 'Aslan', B: 'Çita', C: 'Leopar', D: 'Antilop', E: 'At' },
    answer: 'B',
    explanation: 'The cheetah can reach speeds between 80 to 120 km/h in short bursts.',
  },
  {
    id: 'gen_151',
    text: 'What is the chemical symbol for Iron?',
    text_tr: 'Demirin kimyasal sembolü nedir?',
    options: { A: 'Ir', B: 'I', C: 'Fe', D: 'In', E: 'F' },
    options_tr: { A: 'Ir', B: 'I', C: 'Fe', D: 'In', E: 'F' },
    answer: 'C',
    explanation: 'The symbol "Fe" comes from the Latin word for iron, "ferrum".',
  },
  {
    id: 'gen_152',
    text: 'How many standard playing cards are there in a full deck (excluding Jokers)?',
    text_tr: 'Jokerler hariç tam bir oyun kâğıdı destesinde kaç kart vardır?',
    options: { A: '48', B: '50', C: '52', D: '54', E: '56' },
    options_tr: { A: '48', B: '50', C: '52', D: '54', E: '56' },
    answer: 'C',
    explanation: 'A standard deck has 52 cards divided into four suits.',
  },
  {
    id: 'gen_153',
    text: 'Which major sea is located between Europe and Africa?',
    text_tr: 'Avrupa ile Afrika arasında yer alan büyük deniz hangisidir?',
    options: { A: 'Red Sea', B: 'Caribbean Sea', C: 'Mediterranean Sea', D: 'Black Sea', E: 'Caspian Sea' },
    options_tr: { A: 'Kızıldeniz', B: 'Karayip Denizi', C: 'Akdeniz', D: 'Karadeniz', E: 'Hazar Denizi' },
    answer: 'C',
    explanation: 'The Mediterranean Sea connects to the Atlantic Ocean and is bordered by Europe, Africa, and Asia.',
  },
  {
    id: 'gen_154',
    text: 'What is the default currency of Japan?',
    text_tr: 'Japonya\'nın resmi para birimi nedir?',
    options: { A: 'Yuan', B: 'Won', C: 'Yen', D: 'Ringgit', E: 'Baht' },
    options_tr: { A: 'Yuan', B: 'Won', C: 'Yen', D: 'Ringgit', E: 'Baht' },
    answer: 'C',
    explanation: 'The Japanese Yen (¥) is the third most traded currency in the foreign exchange market.',
  },
  {
    id: 'gen_155',
    text: 'Which planet is closest to the Sun?',
    text_tr: 'Güneş\'e en yakın gezegen hangisidir?',
    options: { A: 'Venus', B: 'Earth', C: 'Mars', D: 'Mercury', E: 'Jupiter' },
    options_tr: { A: 'Venüs', B: 'Dünya', C: 'Mars', D: 'Merkür', E: 'Jüpiter' },
    answer: 'D',
    explanation: 'Mercury has the smallest orbit around the Sun, making it the closest planet.',
  },
  {
    id: 'gen_156',
    text: 'Who was the first President of the United States?',
    text_tr: 'Amerika Birleşik Devletleri\'nin ilk başkanı kimdir?',
    options: { A: 'Thomas Jefferson', B: 'Abraham Lincoln', C: 'George Washington', D: 'John Adams', E: 'Benjamin Franklin' },
    options_tr: { A: 'Thomas Jefferson', B: 'Abraham Lincoln', C: 'George Washington', D: 'John Adams', E: 'Benjamin Franklin' },
    answer: 'C',
    explanation: 'George Washington served as president from 1789 to 1797.',
  },
  {
    id: 'gen_157',
    text: 'What pigment gives leaves their green color?',
    text_tr: 'Yapraklara yeşil rengini veren pigment hangisidir?',
    options: { A: 'Carotene', B: 'Melanin', C: 'Chlorophyll', D: 'Hemoglobin', E: 'Xanthophyll' },
    options_tr: { A: 'Karoten', B: 'Melanin', C: 'Klorofil', D: 'Hemoglobin', E: 'Ksantofil' },
    answer: 'C',
    explanation: 'Chlorophyll absorbs sunlight to power photosynthesis and reflects green light.',
  },
  {
    id: 'gen_158',
    text: 'Which country is the home of the Great Barrier Reef?',
    text_tr: 'Büyük Set Resifi hangi ülkenin kıyılarında yer alır?',
    options: { A: 'New Zealand', B: 'South Africa', C: 'Australia', D: 'Indonesia', E: 'Brazil' },
    options_tr: { A: 'Yeni Zelanda', B: 'Güney Afrika', C: 'Avustralya', D: 'Endonezya', E: 'Brezilya' },
    answer: 'C',
    explanation: 'The Great Barrier Reef is the world\'s largest coral reef system, located off the coast of Queensland, Australia.',
  },
  {
    id: 'gen_159',
    text: 'What is the capital city of Russia?',
    text_tr: 'Rusya\'nın başkenti hangi şehirdir?',
    options: { A: 'Saint Petersburg', B: 'Moscow', C: 'Novosibirsk', D: 'Kazan', E: 'Sochi' },
    options_tr: { A: 'Saint Petersburg', B: 'Moskova', C: 'Novosibirsk', D: 'Kazan', E: 'Sochi' },
    answer: 'B',
    explanation: 'Moscow is the capital and largest city of Russia.',
  },
  {
    id: 'gen_160',
    text: 'Which shape is used for standard stop signs globally?',
    text_tr: 'Dünya genelinde standart "DUR" trafik işaretlerinde hangi şekil kullanılır?',
    options: { A: 'Hexagon', B: 'Octagon', C: 'Triangle', D: 'Square', E: 'Circle' },
    options_tr: { A: 'Altıgen', B: 'Sekizgen', C: 'Üçgen', D: 'Kare', E: 'Daire' },
    answer: 'B',
    explanation: 'Standard stop signs use an octagon shape so drivers can recognize them even from the back.',
  },
  {
    id: 'gen_161',
    text: 'Who is the creator of Mickey Mouse?',
    text_tr: 'Mickey Mouse\'un yaratıcısı kimdir?',
    options: { A: 'Warner Bros', B: 'Walt Disney', C: 'Stan Lee', D: 'Hayao Miyazaki', E: 'Charles Schulz' },
    options_tr: { A: 'Warner Bros', B: 'Walt Disney', C: 'Stan Lee', D: 'Hayao Miyazaki', E: 'Charles Schulz' },
    answer: 'B',
    explanation: 'Walt Disney and Ub Iwerks created Mickey Mouse in 1928.',
  },
  {
    id: 'gen_162',
    text: 'What is the main ingredient used in traditional guacamole?',
    text_tr: 'Geleneksel guakamole sosunun ana malzemesi nedir?',
    options: { A: 'Tomato', B: 'Onion', C: 'Avocado', D: 'Garlic', E: 'Potato' },
    options_tr: { A: 'Domates', B: 'Soğan', C: 'Avokado', D: 'Sarımsak', E: 'Patates' },
    answer: 'C',
    explanation: 'Guacamole is an avocado-based dip first developed by the Aztecs in Mexico.',
  },
  {
    id: 'gen_163',
    text: 'Which company developed iOS?',
    text_tr: 'iOS mobil işletim sistemini hangi şirket geliştirmiştir?',
    options: { A: 'Microsoft', B: 'Google', C: 'Apple', D: 'Samsung', E: 'Intel' },
    options_tr: { A: 'Microsoft', B: 'Google', C: 'Apple', D: 'Samsung', E: 'Intel' },
    answer: 'C',
    explanation: 'iOS is a proprietary mobile operating system created by Apple Inc.',
  },
  {
    id: 'gen_164',
    text: 'How many milliliters are there in one liter?',
    text_tr: 'Bir litrede kaç mililitre vardır?',
    options: { A: '10', B: '100', C: '500', D: '1000', E: '10000' },
    options_tr: { A: '10', B: '100', C: '500', D: '1000', E: '10000' },
    answer: 'D',
    explanation: 'The prefix "milli-" means one-thousandth, so there are 1,000 milliliters in 1 liter.',
  },
  {
    id: 'gen_165',
    text: 'Which European city is famous for its canals and gondolas?',
    text_tr: 'Kanalları ve gondolları ile ünlü Avrupa şehri hangisidir?',
    options: { A: 'Amsterdam', B: 'Venice', C: 'Bruges', D: 'Paris', E: 'Vienna' },
    options_tr: { A: 'Amsterdam', B: 'Venedik', C: 'Bruges', D: 'Paris', E: 'Viyana' },
    answer: 'B',
    explanation: 'Venice, Italy, is built on 118 small islands separated by canals.',
  },
  {
    id: 'gen_166',
    text: 'What is the chemically pure form of common table salt?',
    text_tr: 'Sofra tuzunun kimyasal adı nedir?',
    options: { A: 'Sodium Chloride', B: 'Potassium Nitrate', C: 'Calcium Carbonate', D: 'Sodium Bicarbonate', E: 'Magnesium Sulfate' },
    options_tr: { A: 'Sodyum Klorür', B: 'Potasyum Nitrat', C: 'Kalsiyum Karbonat', D: 'Sodyum Bikarbonat', E: 'Magnezyum Sülfat' },
    answer: 'A',
    explanation: 'Table salt is an ionic compound with the chemical formula NaCl (Sodium Chloride).',
  },
  {
    id: 'gen_167',
    text: 'Who painted the ceiling of the Sistine Chapel?',
    text_tr: 'Sistine Şapeli\'nin tavanını kim boyamıştır?',
    options: { A: 'Leonardo da Vinci', B: 'Raphael', C: 'Michelangelo', D: 'Donatello', E: 'Rembrandt' },
    options_tr: { A: 'Leonardo da Vinci', B: 'Rafael', C: 'Michelangelo', D: 'Donatello', E: 'Rembrandt' },
    answer: 'C',
    explanation: 'Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512.',
  },
  {
    id: 'gen_168',
    text: 'Which bird is globally recognized as a symbol of peace?',
    text_tr: 'Dünya genelinde barışın simgesi olarak kabul edilen kuş hangisidir?',
    options: { A: 'Eagle', B: 'Dove', C: 'Owl', D: 'Swan', E: 'Falcon' },
    options_tr: { A: 'Kartal', B: 'Güvercin', C: 'Baykuş', D: 'Kuğu', E: 'Doğan' },
    answer: 'B',
    explanation: 'A white dove, often carrying an olive branch, is a widely accepted symbol of peace.',
  },
  {
    id: 'gen_169',
    text: 'What is the capital city of Greece?',
    text_tr: 'Yunanistan\'ın başkenti hangi şehirdir?',
    options: { A: 'Thessaloniki', B: 'Athens', C: 'Patras', D: 'Heraklion', E: 'Rhodes' },
    options_tr: { A: 'Selanik', B: 'Atina', C: 'Patras', D: 'Kandiye', E: 'Rodos' },
    answer: 'B',
    explanation: 'Athens is the capital and largest city of Greece.',
  },
  {
    id: 'gen_170',
    text: 'Which is the smallest ocean in the world?',
    text_tr: 'Dünyadaki en küçük okyanus hangisidir?',
    options: { A: 'Indian Ocean', B: 'Pacific Ocean', C: 'Arctic Ocean', D: 'Atlantic Ocean', E: 'Southern Ocean' },
    options_tr: { A: 'Hint Okyanusu', B: 'Büyük Okyanus', C: 'Arktik Okyanusu', D: 'Atlas Okyanusu', E: 'Güney Okyanusu' },
    answer: 'C',
    explanation: 'The Arctic Ocean is the smallest and shallowest of the world\'s five major oceans.',
  },
  {
    id: 'gen_171',
    text: 'Who wrote the famous novel "1984"?',
    text_tr: '"1984" adlı ünlü romanı kim yazmıştır?',
    options: { A: 'George Orwell', B: 'Aldous Huxley', C: 'Ray Bradbury', D: 'Ernest Hemingway', E: 'F. Scott Fitzgerald' },
    options_tr: { A: 'George Orwell', B: 'Aldous Huxley', C: 'Ray Bradbury', D: 'Ernest Hemingway', E: 'F. Scott Fitzgerald' },
    answer: 'A',
    explanation: '1984 is a dystopian novel written by the English author George Orwell.',
  },
  {
    id: 'gen_172',
    text: 'What is the primary currency used in China?',
    text_tr: 'Çin\'de kullanılan resmi para birimi nedir?',
    options: { A: 'Yen', B: 'Won', C: 'Renminbi (Yuan)', D: 'Baht', E: 'Dong' },
    options_tr: { A: 'Yen', B: 'Won', C: 'Renminbi (Yuan)', D: 'Baht', E: 'Dong' },
    answer: 'C',
    explanation: 'The official currency of China is the Renminbi; its primary unit is the Yuan.',
  },
  {
    id: 'gen_173',
    text: 'Which planet in our solar system is famous for its massive rings?',
    text_tr: 'Güneş sistemimizde devasa halkalarıyla ünlü olan gezegen hangisidir?',
    options: { A: 'Mars', B: 'Neptune', C: 'Saturn', D: 'Uranus', E: 'Jupiter' },
    options_tr: { A: 'Mars', B: 'Neptün', C: 'Satürn', D: 'Uranüs', E: 'Jüpiter' },
    answer: 'C',
    explanation: 'Saturn has the most extensive and complex ring system of any planet in our solar system.',
  },
  {
    id: 'gen_174',
    text: 'In which continent is the Amazon Rainforest located?',
    text_tr: 'Amazon Yağmur Ormanları hangi kıtadadır?',
    options: { A: 'Africa', B: 'Asia', C: 'South America', D: 'North America', E: 'Australia' },
    options_tr: { A: 'Afrika', B: 'Asya', C: 'Güney Amerika', D: 'Kuzey Amerika', E: 'Avustralya' },
    answer: 'C',
    explanation: 'The Amazon Rainforest is located in South America, with the majority in Brazil.',
  },
  {
    id: 'gen_175',
    text: 'What is the main chemical element used to manufacture computer microchips?',
    text_tr: 'Bilgisayar mikroçiplerinin üretiminde kullanılan ana element hangisidir?',
    options: { A: 'Carbon', B: 'Silicon', C: 'Gold', D: 'Copper', E: 'Iron' },
    options_tr: { A: 'Karbon', B: 'Silisyum', C: 'Altın', D: 'Bakır', E: 'Demir' },
    answer: 'B',
    explanation: 'Silicon is a semiconductor, making it the perfect material for building transistors on integrated circuits.',
  },
  {
    id: 'gen_176',
    text: 'Which year is considered the start of the 21st century?',
    text_tr: 'Hangi yıl 21. yüzyılın başlangıcı kabul edilir?',
    options: { A: '1999', B: '2000', C: '2001', D: '2010', E: '2020' },
    options_tr: { A: '1999', B: '2000', C: '2001', D: '2010', E: '2020' },
    answer: 'C',
    explanation: 'Because there was no year 0, the 21st century officially began on January 1, 2001.',
  },
  {
    id: 'gen_177',
    text: 'Which social media platform features a bird in its original logo?',
    text_tr: 'Orijinal logosunda bir kuş bulunan sosyal medya platformu hangisidir?',
    options: { A: 'Facebook', B: 'Instagram', C: 'Twitter', D: 'LinkedIn', E: 'Pinterest' },
    options_tr: { A: 'Facebook', B: 'Instagram', C: 'Twitter', D: 'LinkedIn', E: 'Pinterest' },
    answer: 'C',
    explanation: 'Twitter\'s classic logo featured a blue bird named "Larry" before the platform rebranded to X.',
  },
  {
    id: 'gen_178',
    text: 'What gas is used to fill balloons to make them float?',
    text_tr: 'Balonların uçmasını sağlamak için kullanılan gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Nitrogen', C: 'Helium', D: 'Carbon Dioxide', E: 'Argon' },
    options_tr: { A: 'Oksijen', B: 'Azot', C: 'Helyum', D: 'Karbondioksit', E: 'Argon' },
    answer: 'C',
    explanation: 'Helium is lighter than air, which causes balloons filled with it to float.',
  },
  {
    id: 'gen_179',
    text: 'Which vitamin is highly abundant in citrus fruits?',
    text_tr: 'Narenciye meyvelerinde bol miktarda bulunan vitamin hangisidir?',
    options: { A: 'Vitamin A', B: 'Vitamin B', C: 'Vitamin C', D: 'Vitamin D', E: 'Vitamin K' },
    options_tr: { A: 'A Vitamini', B: 'B Vitamini', C: 'C Vitamini', D: 'D Vitamini', E: 'K Vitamini' },
    answer: 'C',
    explanation: 'Citrus fruits are famous for their high concentration of Vitamin C (ascorbic acid).',
  },
  {
    id: 'gen_180',
    text: 'What is the capital city of Spain?',
    text_tr: 'İspanya\'nın başkenti hangi şehirdir?',
    options: { A: 'Barcelona', B: 'Valencia', C: 'Seville', D: 'Madrid', E: 'Malaga' },
    options_tr: { A: 'Barselona', B: 'Valensiya', C: 'Sevilla', D: 'Madrid', E: 'Malaga' },
    answer: 'D',
    explanation: 'Madrid is the capital and largest city of Spain.',
  },
  {
    id: 'gen_181',
    text: 'Which popular fairy tale character leaves a glass slipper at a ball?',
    text_tr: 'Hangi masal kahramanı baloda camdan bir ayakkabı teki düşürür?',
    options: { A: 'Snow White', B: 'Cinderella', C: 'Sleeping Beauty', D: 'Rapunzel', E: 'Little Red Riding Hood' },
    options_tr: { A: 'Pamuk Prenses', B: 'Külkedisi', C: 'Uyuyan Güzel', D: 'Rapunzel', E: 'Kırmızı Başlıklı Kız' },
    answer: 'B',
    explanation: 'Cinderella accidentally leaves behind a glass slipper as she rushes from the prince\'s ball.',
  },
  {
    id: 'gen_182',
    text: 'Which device is used to measure earthquakes?',
    text_tr: 'Depremleri ölçmek için hangi alet kullanılır?',
    options: { A: 'Barometer', B: 'Seismograph', C: 'Speedometer', D: 'Thermometer', E: 'Hygrometer' },
    options_tr: { A: 'Barometre', B: 'Sismograf', C: 'Hız Göstergesi', D: 'Termometre', E: 'Higrometre' },
    answer: 'B',
    explanation: 'A seismograph detects and records the strength and duration of earthquakes.',
  },
  {
    id: 'gen_183',
    text: 'How many seconds are there in one hour?',
    text_tr: 'Bir saatte kaç saniye vardır?',
    options: { A: '60', B: '600', C: '1200', D: '2400', E: '3600' },
    options_tr: { A: '60', B: '600', C: '1200', D: '2400', E: '3600' },
    answer: 'E',
    explanation: '60 seconds × 60 minutes = 3,600 seconds per hour.',
  },
  {
    id: 'gen_184',
    text: 'What is the official language of Egypt?',
    text_tr: 'Mısır\'ın resmi dili nedir?',
    options: { A: 'Egyptian', B: 'Arabic', C: 'French', D: 'English', E: 'Coptic' },
    options_tr: { A: 'Mısırca', B: 'Arapça', C: 'Fransızca', D: 'İngilizce', E: 'Koptça' },
    answer: 'B',
    explanation: 'Modern Standard Arabic is the official language of Egypt.',
  },
  {
    id: 'gen_185',
    text: 'Which animal is known as the King of the Jungle?',
    text_tr: 'Hangi hayvan "Ormanın Kralı" olarak bilinir?',
    options: { A: 'Tiger', B: 'Elephant', C: 'Lion', D: 'Gorilla', E: 'Leopard' },
    options_tr: { A: 'Kaplan', B: 'Fil', C: 'Aslan', D: 'Goril', E: 'Leopar' },
    answer: 'C',
    explanation: 'Despite living mostly in grasslands, the lion is called the King of the Jungle.',
  },
  {
    id: 'gen_186',
    text: 'Which vitamin is produced when human skin is exposed to sunlight?',
    text_tr: 'İnsan derisi güneş ışığına maruz kaldığında hangi vitamin üretilir?',
    options: { A: 'Vitamin A', B: 'Vitamin B12', C: 'Vitamin C', D: 'Vitamin D', E: 'Vitamin E' },
    options_tr: { A: 'A Vitamini', B: 'B12 Vitamini', C: 'C Vitamini', D: 'D Vitamini', E: 'E Vitamini' },
    answer: 'D',
    explanation: 'The skin synthesizes Vitamin D when exposed to UVB radiation from sunlight.',
  },
  {
    id: 'gen_187',
    text: 'Which organ is responsible for pumping blood throughout the human body?',
    text_tr: 'İnsan vücudunda kanı pompalamakla görevli organ hangisidir?',
    options: { A: 'Lungs', B: 'Liver', C: 'Brain', D: 'Heart', E: 'Kidneys' },
    options_tr: { A: 'Akciğer', B: 'Karaciğer', C: 'Beyin', D: 'Kalp', E: 'Böbrekler' },
    answer: 'D',
    explanation: 'The heart pumps blood through the blood vessels of the circulatory system.',
  },
  {
    id: 'gen_188',
    text: 'What is the freezing point of water in Celsius?',
    text_tr: 'Suyun Celsius cinsinden donma noktası kaçtır?',
    options: { A: '-10°C', B: '0°C', C: '4°C', D: '10°C', E: '-1°C' },
    options_tr: { A: '-10°C', B: '0°C', C: '4°C', D: '10°C', E: '-1°C' },
    answer: 'B',
    explanation: 'Pure water freezes at exactly 0°C at standard atmospheric pressure.',
  },
  {
    id: 'gen_190',
    text: 'Who wrote "The Lord of the Rings"?',
    text_tr: '"Yüzüklerin Efendisi"ni kim yazmıştır?',
    options: { A: 'George R.R. Martin', B: 'J.K. Rowling', C: 'C.S. Lewis', D: 'J.R.R. Tolkien', E: 'Stephen King' },
    options_tr: { A: 'George R.R. Martin', B: 'J.K. Rowling', C: 'C.S. Lewis', D: 'J.R.R. Tolkien', E: 'Stephen King' },
    answer: 'D',
    explanation: 'The Lord of the Rings was written by J.R.R. Tolkien.',
  },
  {
    id: 'gen_191',
    text: 'How many lungs does a healthy human body normally have?',
    text_tr: 'Sağlıklı bir insan vücudunda normalde kaç akciğer bulunur?',
    options: { A: '1', B: '2', C: '3', D: '4', E: '0' },
    options_tr: { A: '1', B: '2', C: '3', D: '4', E: '0' },
    answer: 'B',
    explanation: 'Humans have a pair of lungs located in the thoracic cavity.',
  },
  {
    id: 'gen_195',
    text: 'What is the boiling point of water at standard atmospheric pressure?',
    text_tr: 'Standart atmosfer basıncında suyun kaynama noktası kaçtır?',
    options: { A: '50°C', B: '80°C', C: '100°C', D: '120°C', E: '150°C' },
    options_tr: { A: '50°C', B: '80°C', C: '100°C', D: '120°C', E: '150°C' },
    answer: 'C',
    explanation: 'Water boils at 100°C (212°F) at sea level atmospheric pressure.',
  },
  {
    id: 'gen_196',
    text: 'How many colors are there in a rainbow?',
    text_tr: 'Gökkuşağında kaç renk vardır?',
    options: { A: '5', B: '6', C: '7', D: '8', E: '9' },
    options_tr: { A: '5', B: '6', C: '7', D: '8', E: '9' },
    answer: 'C',
    explanation: 'A rainbow has 7 colors: Red, Orange, Yellow, Green, Blue, Indigo, and Violet.',
  },
  {
    id: 'gen_197',
    text: 'Which device is used to measure temperature?',
    text_tr: 'Sıcaklığı ölçmek için hangi alet kullanılır?',
    options: { A: 'Barometer', B: 'Seismograph', C: 'Thermometer', D: 'Hygrometer', E: 'Anemometer' },
    options_tr: { A: 'Barometre', B: 'Sismograf', C: 'Termometre', D: 'Higrometre', E: 'Anemometre' },
    answer: 'C',
    explanation: 'A thermometer measures temperature, typically using mercury or digital sensors.',
  },
  {
    id: 'gen_198',
    text: 'Which planet has the most moons in our solar system?',
    text_tr: 'Güneş sistemimizde en fazla uyduya sahip gezegen hangisidir?',
    options: { A: 'Jupiter', B: 'Mars', C: 'Neptune', D: 'Saturn', E: 'Uranus' },
    options_tr: { A: 'Jüpiter', B: 'Mars', C: 'Neptün', D: 'Satürn', E: 'Uranüs' },
    answer: 'D',
    explanation: 'Saturn has 146 confirmed moons, surpassing Jupiter as the planet with the most moons.',
  },
  {
    id: 'gen_199',
    text: 'Which country is known for producing the most coffee in the world?',
    text_tr: 'Dünyada en fazla kahve üreten ülke hangisidir?',
    options: { A: 'Colombia', B: 'Vietnam', C: 'Ethiopia', D: 'Brazil', E: 'Indonesia' },
    options_tr: { A: 'Kolombiya', B: 'Vietnam', C: 'Etiyopya', D: 'Brezilya', E: 'Endonezya' },
    answer: 'D',
    explanation: 'Brazil is the world\'s largest coffee producer, accounting for about one-third of global production.',
  },
  {
    id: 'gen_200',
    text: 'What is the name of the process by which the Moon causes ocean tides on Earth?',
    text_tr: 'Ay\'ın Dünya\'daki okyanus gelgitlerini oluşturma sürecinin adı nedir?',
    options: { A: 'Lunar pull', B: 'Gravitational attraction', C: 'Tidal force', D: 'Orbital resonance', E: 'Magnetic induction' },
    options_tr: { A: 'Ay çekimi', B: 'Yerçekimi çekim kuvveti', C: 'Gelgit kuvveti', D: 'Yörüngesel rezonans', E: 'Manyetik indüksiyon' },
    answer: 'C',
    explanation: 'Tidal forces arise from differences in the Moon\'s gravitational pull across different parts of Earth, creating the ocean\'s rise and fall.',
  },
];

module.exports = { general };
