'use strict';

const general = [
  {
    id: 'gen_01',
    text: 'Which organ in the human body produces bile?',
    text_tr: 'İnsan vücudunda safra üreten organ hangisidir?',
    options: { A: 'Pancreas', B: 'Gallbladder', C: 'Liver', D: 'Spleen', E: 'Duodenum' },
    options_tr: { A: 'Pankreas', B: 'Safra kesesi', C: 'Karaciğer', D: 'Dalak', E: 'Onikiparmak bağırsağı' },
    answer: 'C',
    explanation: 'Karaciğer safra üretir; safra kesesi yalnızca onu depolar ve yoğunlaştırır.',
  },
  {
    id: 'gen_02',
    text: 'What is the chemical symbol for Tungsten?',
    text_tr: 'Tungsten\'in kimyasal sembolü nedir?',
    options: { A: 'Tu', B: 'Wg', C: 'Tn', D: 'W', E: 'Wo' },
    options_tr: { A: 'Tu', B: 'Wg', C: 'Tn', D: 'W', E: 'Wo' },
    answer: 'D',
    explanation: 'Almancası "Wolfram"dan gelir. Tungsten ampul flamanlarında kullanılır.',
  },
  {
    id: 'gen_03',
    text: 'Which planet in our solar system has the most confirmed moons?',
    text_tr: 'Güneş sistemimizde en fazla onaylanmış uyduya sahip gezegen hangisidir?',
    options: { A: 'Jupiter', B: 'Neptune', C: 'Uranus', D: 'Saturn', E: 'Mars' },
    options_tr: { A: 'Jüpiter', B: 'Neptün', C: 'Uranüs', D: 'Satürn', E: 'Mars' },
    answer: 'D',
    explanation: 'Satürn 2023\'te 146 onaylı uyduyla Jüpiter\'i geçti.',
  },
  {
    id: 'gen_04',
    text: 'Who coined the term "Survival of the Fittest" in the context of evolution?',
    text_tr: 'Evrim bağlamında "En Uygun Olanın Hayatta Kalması" ifadesini kim ortaya attı?',
    options: { A: 'Charles Darwin', B: 'Alfred Russel Wallace', C: 'Thomas Huxley', D: 'Herbert Spencer', E: 'Ernst Haeckel' },
    options_tr: { A: 'Charles Darwin', B: 'Alfred Russel Wallace', C: 'Thomas Huxley', D: 'Herbert Spencer', E: 'Ernst Haeckel' },
    answer: 'D',
    explanation: 'Herbert Spencer bu ifadeyi 1864\'te yarattı; Darwin sonraki baskılarda Spencer\'dan ödünç aldı.',
  },
  {
    id: 'gen_05',
    text: 'Which country was the first to grant women the right to vote in national elections?',
    text_tr: 'Ulusal seçimlerde kadınlara oy hakkı tanıyan ilk ülke hangisidir?',
    options: { A: 'Finland', B: 'Australia', C: 'Norway', D: 'Denmark', E: 'New Zealand' },
    options_tr: { A: 'Finlandiya', B: 'Avustralya', C: 'Norveç', D: 'Danimarka', E: 'Yeni Zelanda' },
    answer: 'E',
    explanation: 'Yeni Zelanda, 1893\'te diğer tüm ülkelerden önce kadınlara oy hakkı tanıdı.',
  },
  {
    id: 'gen_06',
    text: 'What is the hardest natural substance on Earth?',
    text_tr: 'Dünya\'daki en sert doğal madde nedir?',
    options: { A: 'Corundum', B: 'Topaz', C: 'Quartz', D: 'Diamond', E: 'Graphite' },
    options_tr: { A: 'Korundum', B: 'Topaz', C: 'Kuvars', D: 'Elmas', E: 'Grafit' },
    answer: 'D',
    explanation: 'Elmas Mohs sertlik skalasında 10 ile en yüksek değere sahiptir.',
  },
  {
    id: 'gen_07',
    text: 'How many bones does an adult human body have?',
    text_tr: 'Yetişkin bir insan vücudunda kaç kemik bulunur?',
    options: { A: '186', B: '196', C: '206', D: '216', E: '226' },
    options_tr: { A: '186', B: '196', C: '206', D: '216', E: '226' },
    answer: 'C',
    explanation: 'Yetişkin insan iskeleti 206 kemikten oluşur; bebeklerin yaklaşık 270 kemiği vardır ve bunlar büyüme sırasında kaynaşır.',
  },
  {
    id: 'gen_08',
    text: 'Which gas makes up the largest percentage of Earth\'s atmosphere?',
    text_tr: 'Dünya atmosferinin en büyük bölümünü oluşturan gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Carbon dioxide', C: 'Argon', D: 'Nitrogen', E: 'Hydrogen' },
    options_tr: { A: 'Oksijen', B: 'Karbondioksit', C: 'Argon', D: 'Azot', E: 'Hidrojen' },
    answer: 'D',
    explanation: 'Azot (N₂) atmosferin yaklaşık %78\'ini oluşturur; oksijen ise yaklaşık %21\'ini.',
  },
  {
    id: 'gen_09',
    text: 'What is the speed of light in a vacuum (approximately)?',
    text_tr: 'Işığın vakumdaki hızı yaklaşık olarak nedir?',
    options: { A: '200,000 km/s', B: '250,000 km/s', C: '300,000 km/s', D: '350,000 km/s', E: '400,000 km/s' },
    options_tr: { A: '200.000 km/s', B: '250.000 km/s', C: '300.000 km/s', D: '350.000 km/s', E: '400.000 km/s' },
    answer: 'C',
    explanation: 'Işık vakumda yaklaşık 299.792 km/s hızla hareket eder; bu genellikle 300.000 km/s olarak yuvarlanır.',
  },
  {
    id: 'gen_10',
    text: 'Which element has the atomic number 1?',
    text_tr: 'Atom numarası 1 olan element hangisidir?',
    options: { A: 'Helium', B: 'Lithium', C: 'Carbon', D: 'Hydrogen', E: 'Oxygen' },
    options_tr: { A: 'Helyum', B: 'Lityum', C: 'Karbon', D: 'Hidrojen', E: 'Oksijen' },
    answer: 'D',
    explanation: 'Hidrojen, periyodik tablonun ilk elementidir ve evrende en bol bulunan elementtir.',
  },
  {
    id: 'gen_11',
    text: 'How many chambers does the human heart have?',
    text_tr: 'İnsan kalbinde kaç oda bulunur?',
    options: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    options_tr: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    answer: 'C',
    explanation: 'İnsan kalbi dört odadan oluşur: sağ ve sol kulakçık (atrium) ile sağ ve sol karıncık (ventrikül).',
  },
  {
    id: 'gen_12',
    text: 'What is the largest organ of the human body?',
    text_tr: 'İnsan vücudunun en büyük organı hangisidir?',
    options: { A: 'Liver', B: 'Brain', C: 'Lungs', D: 'Skin', E: 'Intestines' },
    options_tr: { A: 'Karaciğer', B: 'Beyin', C: 'Akciğerler', D: 'Deri', E: 'Bağırsaklar' },
    answer: 'D',
    explanation: 'Deri, yaklaşık 1,5–2 m² yüzey alanıyla insan vücudunun en büyük organıdır.',
  },
  {
    id: 'gen_13',
    text: 'Which blood type is known as the "universal donor"?',
    text_tr: '"Evrensel donör" olarak bilinen kan grubu hangisidir?',
    options: { A: 'A+', B: 'B-', C: 'AB+', D: 'O-', E: 'O+' },
    options_tr: { A: 'A+', B: 'B-', C: 'AB+', D: '0-', E: '0+' },
    answer: 'D',
    explanation: 'O Rh- kan grubu tüm alıcılara verilebilir; bu yüzden "evrensel donör" olarak adlandırılır.',
  },
  {
    id: 'gen_14',
    text: 'Which scientist proposed the general theory of relativity?',
    text_tr: 'Genel görelilik teorisini kim öne sürmüştür?',
    options: { A: 'Isaac Newton', B: 'Niels Bohr', C: 'Max Planck', D: 'Albert Einstein', E: 'Erwin Schrödinger' },
    options_tr: { A: 'Isaac Newton', B: 'Niels Bohr', C: 'Max Planck', D: 'Albert Einstein', E: 'Erwin Schrödinger' },
    answer: 'D',
    explanation: 'Albert Einstein genel görelilik teorisini 1915\'te yayımladı; kütleçekimini uzay-zamanın eğriliği olarak açıkladı.',
  },
  {
    id: 'gen_15',
    text: 'DNA stands for which of the following?',
    text_tr: 'DNA\'nın açılımı aşağıdakilerden hangisidir?',
    options: { A: 'Deoxyribonucleic Acid', B: 'Dioxynucleic Acid', C: 'Diribonucleic Acid', D: 'Deoxyribonitric Acid', E: 'Dinucleic Acid' },
    options_tr: { A: 'Deoksiribonükleik Asit', B: 'Dioksinükleik Asit', C: 'Diribonükleik Asit', D: 'Deoksiriboniterik Asit', E: 'Dinükleik Asit' },
    answer: 'A',
    explanation: 'DNA (Deoksiribonükleik Asit) canlı organizmaların genetik bilgisini taşıyan moleküldür.',
  },
  {
    id: 'gen_16',
    text: 'What is the boiling point of water at sea level in Celsius?',
    text_tr: 'Deniz seviyesinde suyun kaynama noktası Celsius olarak kaçtır?',
    options: { A: '90°C', B: '95°C', C: '98°C', D: '100°C', E: '105°C' },
    options_tr: { A: '90°C', B: '95°C', C: '98°C', D: '100°C', E: '105°C' },
    answer: 'D',
    explanation: 'Deniz seviyesinde (1 atm basınçta) su 100°C\'de kaynar.',
  },
  {
    id: 'gen_17',
    text: 'How many teeth does a healthy adult human have (including wisdom teeth)?',
    text_tr: 'Sağlıklı bir yetişkinin (yirmi yaş dişleri dahil) kaç dişi vardır?',
    options: { A: '28', B: '30', C: '32', D: '34', E: '36' },
    options_tr: { A: '28', B: '30', C: '32', D: '34', E: '36' },
    answer: 'C',
    explanation: 'Yetişkin insanın 32 daimi dişi vardır; bunların 4\'ü yirmi yaş dişidir.',
  },
  {
    id: 'gen_18',
    text: 'Which planet is known as the "Red Planet"?',
    text_tr: '"Kızıl Gezegen" olarak bilinen gezegen hangisidir?',
    options: { A: 'Venus', B: 'Jupiter', C: 'Mars', D: 'Mercury', E: 'Saturn' },
    options_tr: { A: 'Venüs', B: 'Jüpiter', C: 'Mars', D: 'Merkür', E: 'Satürn' },
    answer: 'C',
    explanation: 'Mars, yüzeyindeki demir oksit (pas) nedeniyle kırmızı görünür ve bu yüzden "Kızıl Gezegen" olarak anılır.',
  },
  {
    id: 'gen_19',
    text: 'What is the chemical formula for water?',
    text_tr: 'Suyun kimyasal formülü nedir?',
    options: { A: 'HO', B: 'H₂O', C: 'H₃O', D: 'HO₂', E: 'H₂O₂' },
    options_tr: { A: 'HO', B: 'H₂O', C: 'H₃O', D: 'HO₂', E: 'H₂O₂' },
    answer: 'B',
    explanation: 'Su molekülü iki hidrojen atomu ve bir oksijen atomundan oluşur: H₂O.',
  },
  {
    id: 'gen_20',
    text: 'Which animal has the longest gestation period?',
    text_tr: 'En uzun gebelik süresine sahip hayvan hangisidir?',
    options: { A: 'Blue Whale', B: 'Giraffe', C: 'African Elephant', D: 'Rhinoceros', E: 'Hippopotamus' },
    options_tr: { A: 'Mavi Balina', B: 'Zürafa', C: 'Afrika Fili', D: 'Gergedan', E: 'Su Aygırı' },
    answer: 'C',
    explanation: 'Afrika filinin gebelik süresi yaklaşık 22 aydır; bu tüm kara memelileri arasında en uzun olanıdır.',
  },
  {
    id: 'gen_21',
    text: 'How many pairs of chromosomes does a typical human cell contain?',
    text_tr: 'Tipik bir insan hücresi kaç çift kromozom içerir?',
    options: { A: '21', B: '22', C: '23', D: '24', E: '46' },
    options_tr: { A: '21', B: '22', C: '23', D: '24', E: '46' },
    answer: 'C',
    explanation: 'İnsan hücrelerinde 23 çift (toplam 46) kromozom bulunur.',
  },
  {
    id: 'gen_22',
    text: 'What is the most abundant metal in the Earth\'s crust?',
    text_tr: 'Dünya\'nın kabuğunda en bol bulunan metal hangisidir?',
    options: { A: 'Iron', B: 'Calcium', C: 'Sodium', D: 'Aluminium', E: 'Silicon' },
    options_tr: { A: 'Demir', B: 'Kalsiyum', C: 'Sodyum', D: 'Alüminyum', E: 'Silisyum' },
    answer: 'D',
    explanation: 'Alüminyum, Dünya kabuğunun yaklaşık %8\'ini oluşturarak en bol bulunan metaldir.',
  },
  {
    id: 'gen_23',
    text: 'Which vitamin is produced by the human body when exposed to sunlight?',
    text_tr: 'Güneş ışığına maruz kalındığında insan vücudu hangi vitamini üretir?',
    options: { A: 'Vitamin A', B: 'Vitamin B12', C: 'Vitamin C', D: 'Vitamin D', E: 'Vitamin K' },
    options_tr: { A: 'A vitamini', B: 'B12 vitamini', C: 'C vitamini', D: 'D vitamini', E: 'K vitamini' },
    answer: 'D',
    explanation: 'Cilt, güneş ışığındaki UVB radyasyonunu D vitaminine dönüştürür.',
  },
  {
    id: 'gen_24',
    text: 'What is the name of the force that keeps planets in orbit around the Sun?',
    text_tr: 'Gezegenleri Güneş\'in yörüngesinde tutan kuvvetin adı nedir?',
    options: { A: 'Electromagnetic force', B: 'Nuclear force', C: 'Centrifugal force', D: 'Gravity', E: 'Dark energy' },
    options_tr: { A: 'Elektromanyetik kuvvet', B: 'Nükleer kuvvet', C: 'Merkezkaç kuvveti', D: 'Yerçekimi', E: 'Karanlık enerji' },
    answer: 'D',
    explanation: 'Yerçekimi, güneşin gezegenleri yörüngede tutmasını sağlayan kuvvettir; Isaac Newton tarafından tanımlanmıştır.',
  },
  {
    id: 'gen_25',
    text: 'What is photosynthesis?',
    text_tr: 'Fotosentez nedir?',
    options: { A: 'Process by which animals digest food', B: 'Process by which plants convert light into energy', C: 'Process by which cells divide', D: 'Process by which bacteria reproduce', E: 'Process by which rocks form' },
    options_tr: { A: 'Hayvanların yiyecekleri sindirme süreci', B: 'Bitkilerin ışığı enerjiye dönüştürme süreci', C: 'Hücrelerin bölünme süreci', D: 'Bakterilerin çoğalma süreci', E: 'Kayaların oluşma süreci' },
    answer: 'B',
    explanation: 'Fotosentez, bitkilerin güneş ışığını, suyu ve karbondioksiti glikoz ve oksijene dönüştürdüğü süreçtir.',
  },
  {
    id: 'gen_26',
    text: 'Which planet is the largest in our solar system?',
    text_tr: 'Güneş sistemimizin en büyük gezegeni hangisidir?',
    options: { A: 'Saturn', B: 'Uranus', C: 'Neptune', D: 'Jupiter', E: 'Earth' },
    options_tr: { A: 'Satürn', B: 'Uranüs', C: 'Neptün', D: 'Jüpiter', E: 'Dünya' },
    answer: 'D',
    explanation: 'Jüpiter, Güneş sisteminin en büyük gezegenidir; kütlesi diğer tüm gezegenlerin toplamından iki kattan fazladır.',
  },
  {
    id: 'gen_27',
    text: 'How many sides does a hexagon have?',
    text_tr: 'Bir altıgenin kaç kenarı vardır?',
    options: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    options_tr: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    answer: 'C',
    explanation: '"Hexa" Yunanca\'da altı anlamına gelir; altıgen 6 kenarlı bir çokgendir.',
  },
  {
    id: 'gen_28',
    text: 'What type of animal is a shark?',
    text_tr: 'Köpek balığı ne tür bir hayvandır?',
    options: { A: 'Mammal', B: 'Reptile', C: 'Amphibian', D: 'Fish', E: 'Mollusk' },
    options_tr: { A: 'Memeli', B: 'Sürüngen', C: 'Amfibi', D: 'Balık', E: 'Yumuşakça' },
    answer: 'D',
    explanation: 'Köpek balıkları, kıkırdaklı iskeletleri olan ve solungaçlarıyla nefes alan kartilajlı balıklardır.',
  },
  {
    id: 'gen_29',
    text: 'What does a barometer measure?',
    text_tr: 'Barometre neyi ölçer?',
    options: { A: 'Temperature', B: 'Humidity', C: 'Wind speed', D: 'Atmospheric pressure', E: 'Rainfall' },
    options_tr: { A: 'Sıcaklık', B: 'Nem', C: 'Rüzgar hızı', D: 'Atmosfer basıncı', E: 'Yağış miktarı' },
    answer: 'D',
    explanation: 'Barometre atmosfer basıncını ölçer ve hava durumu tahmini için kullanılır.',
  },
  {
    id: 'gen_30',
    text: 'Which part of the brain controls balance and coordination?',
    text_tr: 'Beynin hangi bölümü denge ve koordinasyonu kontrol eder?',
    options: { A: 'Cerebrum', B: 'Cerebellum', C: 'Brain stem', D: 'Hippocampus', E: 'Amygdala' },
    options_tr: { A: 'Serebrum (büyük beyin)', B: 'Serebellum (küçük beyin)', C: 'Beyin sapı', D: 'Hipokampüs', E: 'Amigdala' },
    answer: 'B',
    explanation: 'Serebellum (küçük beyin), hareket koordinasyonunu, dengeyi ve kas tonusunu düzenler.',
  },
  {
    id: 'gen_31',
    text: 'What is the unit of electrical resistance?',
    text_tr: 'Elektriksel direncin birimi nedir?',
    options: { A: 'Volt', B: 'Ampere', C: 'Watt', D: 'Ohm', E: 'Farad' },
    options_tr: { A: 'Volt', B: 'Amper', C: 'Watt', D: 'Ohm', E: 'Farad' },
    answer: 'D',
    explanation: 'Ohm (Ω), Georg Simon Ohm\'un adından gelen elektriksel direnç birimidir.',
  },
  {
    id: 'gen_32',
    text: 'Which gas is responsible for the greenhouse effect?',
    text_tr: 'Sera etkisinden sorumlu olan gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Nitrogen', C: 'Argon', D: 'Carbon dioxide', E: 'Helium' },
    options_tr: { A: 'Oksijen', B: 'Azot', C: 'Argon', D: 'Karbondioksit', E: 'Helyum' },
    answer: 'D',
    explanation: 'Karbondioksit (CO₂), sera etkisine en çok katkıda bulunan gazlar arasında öne çıkan bir sera gazıdır.',
  },
  {
    id: 'gen_33',
    text: 'What is the most common type of star in the Milky Way galaxy?',
    text_tr: 'Samanyolu galaksisinde en yaygın yıldız türü hangisidir?',
    options: { A: 'Giant stars', B: 'Neutron stars', C: 'Red dwarf stars', D: 'White dwarf stars', E: 'Yellow dwarf stars' },
    options_tr: { A: 'Dev yıldızlar', B: 'Nötron yıldızları', C: 'Kırmızı cüce yıldızlar', D: 'Beyaz cüce yıldızlar', E: 'Sarı cüce yıldızlar' },
    answer: 'C',
    explanation: 'Kırmızı cüceler, Samanyolu\'ndaki yıldızların yaklaşık %70\'ini oluşturur.',
  },
  {
    id: 'gen_34',
    text: 'Which organ is primarily responsible for filtering blood in the human body?',
    text_tr: 'İnsan vücudunda kanı süzmekten öncelikli olarak sorumlu olan organ hangisidir?',
    options: { A: 'Liver', B: 'Spleen', C: 'Kidney', D: 'Lung', E: 'Pancreas' },
    options_tr: { A: 'Karaciğer', B: 'Dalak', C: 'Böbrek', D: 'Akciğer', E: 'Pankreas' },
    answer: 'C',
    explanation: 'Böbrekler, atık maddeleri ve fazla sıvıyı kandan süzerek idrar oluşturur.',
  },
  {
    id: 'gen_35',
    text: 'What is the term for animals that eat both plants and meat?',
    text_tr: 'Hem bitki hem de et yiyen hayvanlar için kullanılan terim nedir?',
    options: { A: 'Carnivore', B: 'Herbivore', C: 'Omnivore', D: 'Insectivore', E: 'Frugivore' },
    options_tr: { A: 'Etçil', B: 'Otçul', C: 'Hepçil', D: 'Böcekçil', E: 'Meyveçil' },
    answer: 'C',
    explanation: 'Hepçiller (omnivore) hem hayvan hem de bitki kökenli besinlerle beslenir; insanlar da hepçildir.',
  },
  {
    id: 'gen_36',
    text: 'What is the name of the process by which water turns into vapor?',
    text_tr: 'Suyun buhara dönüşme sürecinin adı nedir?',
    options: { A: 'Condensation', B: 'Sublimation', C: 'Evaporation', D: 'Precipitation', E: 'Transpiration' },
    options_tr: { A: 'Yoğuşma', B: 'Süblimleşme', C: 'Buharlaşma', D: 'Yağış', E: 'Terleme (bitkisel)' },
    answer: 'C',
    explanation: 'Buharlaşma, sıvı suyun su buharına dönüştüğü ısı kaynaklı bir süreçtir.',
  },
  {
    id: 'gen_37',
    text: 'How many legs does an insect have?',
    text_tr: 'Bir böceğin kaç bacağı vardır?',
    options: { A: '4', B: '6', C: '8', D: '10', E: '12' },
    options_tr: { A: '4', B: '6', C: '8', D: '10', E: '12' },
    answer: 'B',
    explanation: 'Tüm böcekler 6 bacağa sahiptir; bu özellik onları 8 bacaklı örümceklerden ayırır.',
  },
  {
    id: 'gen_38',
    text: 'Which layer of the Earth is liquid?',
    text_tr: 'Dünya\'nın hangi katmanı sıvıdır?',
    options: { A: 'Inner core', B: 'Outer core', C: 'Mantle', D: 'Crust', E: 'Lithosphere' },
    options_tr: { A: 'İç çekirdek', B: 'Dış çekirdek', C: 'Manto', D: 'Kabuk', E: 'Litosfer' },
    answer: 'B',
    explanation: 'Dünya\'nın dış çekirdeği erimiş demir ve nikelden oluşan sıvı bir katmandır.',
  },
  {
    id: 'gen_39',
    text: 'What is the powerhouse of the cell?',
    text_tr: 'Hücrenin enerji merkezi olarak bilinen organel nedir?',
    options: { A: 'Nucleus', B: 'Ribosome', C: 'Mitochondria', D: 'Golgi apparatus', E: 'Endoplasmic reticulum' },
    options_tr: { A: 'Çekirdek', B: 'Ribozom', C: 'Mitokondri', D: 'Golgi aygıtı', E: 'Endoplazmik retikulum' },
    answer: 'C',
    explanation: 'Mitokondri, hücresel solunum yoluyla ATP enerjisi üreten organel olduğu için "hücrenin enerji santrali" olarak anılır.',
  },
  {
    id: 'gen_40',
    text: 'Which ocean is the largest on Earth?',
    text_tr: 'Dünya\'daki en büyük okyanus hangisidir?',
    options: { A: 'Atlantic Ocean', B: 'Indian Ocean', C: 'Arctic Ocean', D: 'Southern Ocean', E: 'Pacific Ocean' },
    options_tr: { A: 'Atlas Okyanusu', B: 'Hint Okyanusu', C: 'Arktik Okyanus', D: 'Güney Okyanusu', E: 'Pasifik Okyanusu' },
    answer: 'E',
    explanation: 'Pasifik Okyanusu, yaklaşık 165 milyon km² ile Dünya\'nın en büyük ve en derin okyanusudur.',
  },
  {
    id: 'gen_41',
    text: 'What is the SI unit of temperature?',
    text_tr: 'Sıcaklığın SI birimi nedir?',
    options: { A: 'Celsius', B: 'Fahrenheit', C: 'Kelvin', D: 'Rankine', E: 'Réaumur' },
    options_tr: { A: 'Santigrat', B: 'Fahrenheit', C: 'Kelvin', D: 'Rankine', E: 'Réaumur' },
    answer: 'C',
    explanation: 'Kelvin (K), mutlak sıcaklık birimidir ve SI birim sisteminin temel birimidir.',
  },
  {
    id: 'gen_42',
    text: 'Which planet rotates on its side (axial tilt ~98°)?',
    text_tr: 'Yörünge eksenine dik yakın dönerek (~98° eksen eğimi) "yanına yatmış" şekilde dönen gezegen hangisidir?',
    options: { A: 'Neptune', B: 'Venus', C: 'Uranus', D: 'Saturn', E: 'Pluto' },
    options_tr: { A: 'Neptün', B: 'Venüs', C: 'Uranüs', D: 'Satürn', E: 'Plüton' },
    answer: 'C',
    explanation: 'Uranüs\'ün eksen eğimi yaklaşık 98°\'dir; bu durum onu güneş sistemi boyunca âdeta "yuvarlanarak" ilerler gibi gösterir.',
  },
  {
    id: 'gen_43',
    text: 'What is the name of the process by which rocks are broken down by weather?',
    text_tr: 'Kayaların hava koşullarıyla parçalanma sürecinin adı nedir?',
    options: { A: 'Erosion', B: 'Weathering', C: 'Sedimentation', D: 'Metamorphism', E: 'Crystallization' },
    options_tr: { A: 'Erozyon', B: 'Ayrışma', C: 'Çökelme', D: 'Metamorfizm', E: 'Kristalleşme' },
    answer: 'B',
    explanation: 'Ayrışma (weathering), kayaların fiziksel veya kimyasal süreçlerle daha küçük parçalara bölünmesidir.',
  },
  {
    id: 'gen_44',
    text: 'Which animal is capable of regenerating its entire body from a small fragment?',
    text_tr: 'Küçük bir parçasından tüm vücudunu yeniden oluşturabilen hayvan hangisidir?',
    options: { A: 'Starfish', B: 'Salamander', C: 'Planarian flatworm', D: 'Gecko', E: 'Crab' },
    options_tr: { A: 'Denizyıldızı', B: 'Semender', C: 'Planarya (yassı solucan)', D: 'Kertenkele', E: 'Yengeç' },
    answer: 'C',
    explanation: 'Planarya yassı solucanı en olağanüstü rejenerasyon yeteneğine sahiptir; tek bir hücreden tüm yeni bir organizma oluşturabilir.',
  },
  {
    id: 'gen_45',
    text: 'What is the term for the point in Earth\'s orbit closest to the Sun?',
    text_tr: 'Dünya\'nın yörüngesinde Güneş\'e en yakın noktanın adı nedir?',
    options: { A: 'Aphelion', B: 'Perihelion', C: 'Apogee', D: 'Perigee', E: 'Zenith' },
    options_tr: { A: 'Afelyum', B: 'Perihelyum', C: 'Apoje', D: 'Perije', E: 'Zenit' },
    answer: 'B',
    explanation: 'Perihelyum, bir gezegenin yörüngesinde Güneş\'e en yakın olduğu noktadır; Dünya her yıl yaklaşık 3 Ocak\'ta perihelyumda olur.',
  },
  {
    id: 'gen_46',
    text: 'What is the most spoken language in the world by total number of speakers?',
    text_tr: 'Toplam konuşucu sayısı bakımından dünyada en çok konuşulan dil hangisidir?',
    options: { A: 'Spanish', B: 'Hindi', C: 'English', D: 'Mandarin Chinese', E: 'Arabic' },
    options_tr: { A: 'İspanyolca', B: 'Hintçe', C: 'İngilizce', D: 'Mandarin Çincesi', E: 'Arapça' },
    answer: 'C',
    explanation: 'İngilizce, anadil ve ikinci dil konuşucuları dahil edildiğinde yaklaşık 1,5 milyar konuşucuyla dünyada en çok kullanılan dildir.',
  },
  {
    id: 'gen_47',
    text: 'What is the name of the point directly overhead in the sky?',
    text_tr: 'Gökyüzünde tam tepemizde bulunan noktanın adı nedir?',
    options: { A: 'Nadir', B: 'Zenith', C: 'Azimuth', D: 'Apogee', E: 'Meridian' },
    options_tr: { A: 'Nadir', B: 'Zenit', C: 'Azimut', D: 'Apoje', E: 'Meridyen' },
    answer: 'B',
    explanation: 'Zenit, gözlemcinin tam tepesindeki gökyüzü noktasıdır; karşıtı (ayakların altındaki nokta) ise nadirdir.',
  },
  {
    id: 'gen_48',
    text: 'Which element is a liquid at room temperature and is also a metal?',
    text_tr: 'Oda sıcaklığında sıvı hâlde bulunan ve aynı zamanda metal olan element hangisidir?',
    options: { A: 'Bromine', B: 'Gallium', C: 'Mercury', D: 'Cesium', E: 'Francium' },
    options_tr: { A: 'Brom', B: 'Galyum', C: 'Cıva', D: 'Sezyum', E: 'Fransiyum' },
    answer: 'C',
    explanation: 'Cıva (Hg), oda sıcaklığında sıvı olan tek metaldir; erime noktası −38,83°C\'dir.',
  },
  {
    id: 'gen_49',
    text: 'What percentage of the Earth\'s surface is covered by water?',
    text_tr: 'Dünya yüzeyinin yüzde kaçı suyla kaplıdır?',
    options: { A: '51%', B: '61%', C: '71%', D: '81%', E: '91%' },
    options_tr: { A: '%51', B: '%61', C: '%71', D: '%81', E: '%91' },
    answer: 'C',
    explanation: 'Dünya yüzeyinin yaklaşık %71\'i suyla kaplıdır; bu suyun %97\'si tuzlu okyanuslardan oluşur.',
  },
  {
    id: 'gen_50',
    text: 'What is the smallest unit of life?',
    text_tr: 'Yaşamın en küçük birimi nedir?',
    options: { A: 'Atom', B: 'Molecule', C: 'Organelle', D: 'Cell', E: 'Tissue' },
    options_tr: { A: 'Atom', B: 'Molekül', C: 'Organel', D: 'Hücre', E: 'Doku' },
    answer: 'D',
    explanation: 'Hücre, tüm canlı organizmaların temel yapı ve işlevsel birimidir.',
  },
  {
    id: 'gen_51',
    text: 'Which is the tallest mountain in the world?',
    text_tr: 'Dünyanın en yüksek dağı hangisidir?',
    options: { A: 'K2', B: 'Kangchenjunga', C: 'Lhotse', D: 'Makalu', E: 'Mount Everest' },
    options_tr: { A: 'K2', B: 'Kangchenjunga', C: 'Lhotse', D: 'Makalu', E: 'Everest Dağı' },
    answer: 'E',
    explanation: 'Everest Dağı, 8.848 m yüksekliğiyle deniz seviyesinden ölçülen dünyanın en yüksek zirvesidir.',
  },
  {
    id: 'gen_52',
    text: 'What type of energy does the Sun primarily produce?',
    text_tr: 'Güneş öncelikli olarak ne tür enerji üretir?',
    options: { A: 'Fission energy', B: 'Chemical energy', C: 'Fusion energy', D: 'Geothermal energy', E: 'Kinetic energy' },
    options_tr: { A: 'Fisyon enerjisi', B: 'Kimyasal enerji', C: 'Füzyon enerjisi', D: 'Jeotermal enerji', E: 'Kinetik enerji' },
    answer: 'C',
    explanation: 'Güneş, çekirdeğinde hidrojen atomlarını helyuma birleştiren nükleer füzyon yoluyla enerji üretir.',
  },
  {
    id: 'gen_53',
    text: 'What is the name of the scientist who discovered penicillin?',
    text_tr: 'Penisilin\'i keşfeden bilim insanının adı nedir?',
    options: { A: 'Louis Pasteur', B: 'Robert Koch', C: 'Joseph Lister', D: 'Alexander Fleming', E: 'Edward Jenner' },
    options_tr: { A: 'Louis Pasteur', B: 'Robert Koch', C: 'Joseph Lister', D: 'Alexander Fleming', E: 'Edward Jenner' },
    answer: 'D',
    explanation: 'Alexander Fleming, 1928\'de Penicillium notatum küfünün bakterileri öldürdüğünü tesadüfen keşfetti.',
  },
  {
    id: 'gen_54',
    text: 'How many colors are in a rainbow?',
    text_tr: 'Bir gökkuşağında kaç renk bulunur?',
    options: { A: '5', B: '6', C: '7', D: '8', E: '9' },
    options_tr: { A: '5', B: '6', C: '7', D: '8', E: '9' },
    answer: 'C',
    explanation: 'Gökkuşağı yedi renkten oluşur: kırmızı, turuncu, sarı, yeşil, mavi, çivit ve mor (mor menekşe).',
  },
  {
    id: 'gen_55',
    text: 'Which type of rock is formed by the cooling of magma?',
    text_tr: 'Magmanın soğumasıyla oluşan kaya türü hangisidir?',
    options: { A: 'Sedimentary', B: 'Metamorphic', C: 'Igneous', D: 'Carbonate', E: 'Clastic' },
    options_tr: { A: 'Tortul', B: 'Başkalaşım', C: 'Magmatik', D: 'Karbonat', E: 'Kırıntılı' },
    answer: 'C',
    explanation: 'Magmatik kayaçlar, magmanın veya lavanın soğuyup katılaşmasıyla oluşur.',
  },
  {
    id: 'gen_56',
    text: 'What is the term for the bending of light as it passes from one medium to another?',
    text_tr: 'Işığın bir ortamdan diğerine geçerken kırılmasını ifade eden terim nedir?',
    options: { A: 'Reflection', B: 'Diffraction', C: 'Refraction', D: 'Dispersion', E: 'Absorption' },
    options_tr: { A: 'Yansıma', B: 'Kırınım', C: 'Kırılma', D: 'Dağılma', E: 'Soğurma' },
    answer: 'C',
    explanation: 'Kırılma, ışığın farklı yoğunluktaki bir ortama geçerken yön değiştirmesidir; prizmalar ve lensler bu ilkeyle çalışır.',
  },
  {
    id: 'gen_57',
    text: 'Which planet has the Great Red Spot, a storm larger than Earth?',
    text_tr: 'Dünya\'dan büyük bir fırtına olan Büyük Kırmızı Leke hangi gezegende bulunur?',
    options: { A: 'Saturn', B: 'Neptune', C: 'Uranus', D: 'Jupiter', E: 'Mars' },
    options_tr: { A: 'Satürn', B: 'Neptün', C: 'Uranüs', D: 'Jüpiter', E: 'Mars' },
    answer: 'D',
    explanation: 'Jüpiter\'deki Büyük Kırmızı Leke, 350 yılı aşkın süredir devam eden ve Dünya\'nın çapından büyük olan devasa bir kasırgadır.',
  },
  {
    id: 'gen_58',
    text: 'What is the name of the force that opposes the motion of objects through air?',
    text_tr: 'Hava içinden geçen nesnelerin hareketine karşı koyan kuvvetin adı nedir?',
    options: { A: 'Gravity', B: 'Friction', C: 'Drag (Air resistance)', D: 'Inertia', E: 'Tension' },
    options_tr: { A: 'Yerçekimi', B: 'Sürtünme', C: 'Hava direnci (sürükleme)', D: 'Eylemsizlik', E: 'Gerilme' },
    answer: 'C',
    explanation: 'Hava direnci (aerodinamik sürükleme), akışkan bir ortamda hareket eden nesnelere karşı uygulanan kuvvettir.',
  },
  {
    id: 'gen_59',
    text: 'Which vitamin deficiency causes scurvy?',
    text_tr: 'Hangi vitaminin eksikliği iskorbüte (skorbüt) yol açar?',
    options: { A: 'Vitamin A', B: 'Vitamin B1', C: 'Vitamin C', D: 'Vitamin D', E: 'Vitamin E' },
    options_tr: { A: 'A vitamini', B: 'B1 vitamini', C: 'C vitamini', D: 'D vitamini', E: 'E vitamini' },
    answer: 'C',
    explanation: 'İskorbüt, C vitamini (askorbik asit) eksikliğinden kaynaklanır; diş eti kanaması ve yara iyileşmesinin bozulmasıyla kendini gösterir.',
  },
  {
    id: 'gen_60',
    text: 'What is the chemical symbol for gold?',
    text_tr: 'Altının kimyasal sembolü nedir?',
    options: { A: 'Ag', B: 'Go', C: 'Gl', D: 'Gd', E: 'Au' },
    options_tr: { A: 'Ag', B: 'Go', C: 'Gl', D: 'Gd', E: 'Au' },
    answer: 'E',
    explanation: 'Altın\'ın sembolü Au\'dur; Latincede altın anlamına gelen "Aurum"dan gelir.',
  },
  {
    id: 'gen_61',
    text: 'What is the largest living structure on Earth?',
    text_tr: 'Dünya\'daki en büyük canlı yapı nedir?',
    options: { A: 'Amazon Rainforest', B: 'Great Barrier Reef', C: 'Siberian Taiga', D: 'Sahara Desert grasslands', E: 'Congo Basin' },
    options_tr: { A: 'Amazon Yağmur Ormanları', B: 'Büyük Set Resifi', C: 'Sibirya Tayga ormanları', D: 'Sahra çayırlıkları', E: 'Kongo Havzası' },
    answer: 'B',
    explanation: 'Avustralya\'daki Büyük Set Resifi, yaklaşık 344.400 km² alanıyla uzaydan görülebilen tek canlı yapıdır.',
  },
  {
    id: 'gen_62',
    text: 'Which gas is commonly used in advertising signs that glow when electrified?',
    text_tr: 'Elektriklendiğinde ışıyan reklam tabelalarında yaygın olarak kullanılan gaz hangisidir?',
    options: { A: 'Argon', B: 'Helium', C: 'Krypton', D: 'Neon', E: 'Xenon' },
    options_tr: { A: 'Argon', B: 'Helyum', C: 'Kripton', D: 'Neon', E: 'Ksenon' },
    answer: 'D',
    explanation: 'Neon gazı elektrik akımıyla uyarıldığında parlak kırmızı-turuncu ışık yayar; bu yüzden tabela ışıklarında kullanılır.',
  },
  {
    id: 'gen_63',
    text: 'What is the name of the galaxy nearest to the Milky Way?',
    text_tr: 'Samanyolu\'na en yakın galaksinin adı nedir?',
    options: { A: 'Large Magellanic Cloud', B: 'Triangulum Galaxy', C: 'Messier 81', D: 'Andromeda Galaxy', E: 'Whirlpool Galaxy' },
    options_tr: { A: 'Büyük Macellan Bulutu', B: 'Üçgen Galaksisi', C: 'Messier 81', D: 'Andromeda Galaksisi', E: 'Girdap Galaksisi' },
    answer: 'D',
    explanation: 'Andromeda (M31), Samanyolu\'na yaklaşık 2,537 milyon ışık yılı uzaklıkta bulunan en yakın büyük galaksidir.',
  },
  {
    id: 'gen_64',
    text: 'What does pH measure?',
    text_tr: 'pH neyi ölçer?',
    options: { A: 'Temperature of a solution', B: 'Electrical conductivity', C: 'Acidity or alkalinity of a solution', D: 'Concentration of a solution', E: 'Viscosity of a liquid' },
    options_tr: { A: 'Çözeltinin sıcaklığını', B: 'Elektriksel iletkenliği', C: 'Asitlik veya bazlık derecesini', D: 'Çözelti konsantrasyonunu', E: 'Sıvının viskozitesini' },
    answer: 'C',
    explanation: 'pH, bir çözeltinin asitliğini veya bazlığını ölçen 0–14 skalasıdır; 7 nötr, 7\'nin altı asit, üstü bazdır.',
  },
  {
    id: 'gen_65',
    text: 'Which blood cells are responsible for fighting infections?',
    text_tr: 'Enfeksiyonlarla savaşmaktan sorumlu kan hücreleri hangileridir?',
    options: { A: 'Red blood cells', B: 'Platelets', C: 'White blood cells', D: 'Plasma cells', E: 'Stem cells' },
    options_tr: { A: 'Kırmızı kan hücreleri', B: 'Trombositler', C: 'Beyaz kan hücreleri', D: 'Plazma hücreleri', E: 'Kök hücreler' },
    answer: 'C',
    explanation: 'Beyaz kan hücreleri (lökositler), bağışıklık sisteminin temel savunma elemanlarıdır.',
  },
  {
    id: 'gen_66',
    text: 'What is the study of fungi called?',
    text_tr: 'Mantarları inceleyen bilim dalının adı nedir?',
    options: { A: 'Botany', B: 'Mycology', C: 'Phycology', D: 'Lichenology', E: 'Microbiology' },
    options_tr: { A: 'Botanik', B: 'Mikoloji', C: 'Fikotoji', D: 'Likenoloji', E: 'Mikrobiyoloji' },
    answer: 'B',
    explanation: 'Mikoloji, mantarları inceleyen biyoloji dalıdır.',
  },
  {
    id: 'gen_67',
    text: 'What causes a lunar eclipse?',
    text_tr: 'Ay tutulmasına ne sebep olur?',
    options: { A: 'Moon passing between Earth and Sun', B: 'Earth passing between Sun and Moon', C: 'Sun passing between Earth and Moon', D: 'Moon moving farther from Earth', E: 'Clouds blocking sunlight' },
    options_tr: { A: 'Ay\'ın Dünya ile Güneş arasına girmesi', B: 'Dünya\'nın Güneş ile Ay arasına girmesi', C: 'Güneş\'in Dünya ile Ay arasına girmesi', D: 'Ay\'ın Dünya\'dan uzaklaşması', E: 'Bulutların güneş ışığını engellemesi' },
    answer: 'B',
    explanation: 'Ay tutulması, Dünya\'nın Güneş ile Ay arasına girerek Ay\'a düşen güneş ışığını engellemesiyle oluşur.',
  },
  {
    id: 'gen_68',
    text: 'Which natural phenomenon is measured by the Richter scale?',
    text_tr: 'Richter skalasıyla ölçülen doğal olay nedir?',
    options: { A: 'Hurricanes', B: 'Tsunamis', C: 'Tornadoes', D: 'Earthquakes', E: 'Volcanic eruptions' },
    options_tr: { A: 'Kasırgalar', B: 'Tsunamiler', C: 'Hortumlar', D: 'Depremler', E: 'Volkan patlamaları' },
    answer: 'D',
    explanation: 'Richter skalası, depremlerin büyüklüğünü (salınan enerji miktarını) ölçer.',
  },
  {
    id: 'gen_69',
    text: 'What is the main component of natural gas?',
    text_tr: 'Doğal gazın ana bileşeni nedir?',
    options: { A: 'Propane', B: 'Butane', C: 'Ethane', D: 'Methane', E: 'Hydrogen' },
    options_tr: { A: 'Propan', B: 'Bütan', C: 'Etan', D: 'Metan', E: 'Hidrojen' },
    answer: 'D',
    explanation: 'Doğal gaz büyük ölçüde metandan (CH₄) oluşur; genellikle %70–90 oranında metan içerir.',
  },
  {
    id: 'gen_70',
    text: 'What is the name of the process by which plants lose water through their leaves?',
    text_tr: 'Bitkilerin yaprakları aracılığıyla su kaybetme sürecinin adı nedir?',
    options: { A: 'Osmosis', B: 'Transpiration', C: 'Evaporation', D: 'Photosynthesis', E: 'Respiration' },
    options_tr: { A: 'Ozmoz', B: 'Terleme (transpirasyom)', C: 'Buharlaşma', D: 'Fotosentez', E: 'Solunum' },
    answer: 'B',
    explanation: 'Transpirasyon, su buharının bitki yapraklarındaki gözenekler (stoma) aracılığıyla atmosfere salınmasıdır.',
  },
  {
    id: 'gen_71',
    text: 'Which is the most abundant gas in the Sun\'s composition?',
    text_tr: 'Güneş\'in bileşimindeki en bol gaz hangisidir?',
    options: { A: 'Oxygen', B: 'Nitrogen', C: 'Helium', D: 'Hydrogen', E: 'Carbon' },
    options_tr: { A: 'Oksijen', B: 'Azot', C: 'Helyum', D: 'Hidrojen', E: 'Karbon' },
    answer: 'D',
    explanation: 'Güneş kütlesinin yaklaşık %74\'ü hidrojen, %24\'ü helyumdur.',
  },
  {
    id: 'gen_72',
    text: 'What is the name of the outer layer of the Earth?',
    text_tr: 'Dünya\'nın dış katmanının adı nedir?',
    options: { A: 'Mantle', B: 'Core', C: 'Crust', D: 'Lithosphere', E: 'Asthenosphere' },
    options_tr: { A: 'Manto', B: 'Çekirdek', C: 'Kabuk', D: 'Litosfer', E: 'Astenosfer' },
    answer: 'C',
    explanation: 'Dünya kabuğu, gezegenin en dış katmanıdır; kalınlığı kıtalarda 30–50 km, okyanus tabanlarında 5–10 km arasındadır.',
  },
  {
    id: 'gen_73',
    text: 'What is the chemical symbol for silver?',
    text_tr: 'Gümüşün kimyasal sembolü nedir?',
    options: { A: 'Si', B: 'Sv', C: 'Ag', D: 'Sl', E: 'Sr' },
    options_tr: { A: 'Si', B: 'Sv', C: 'Ag', D: 'Sl', E: 'Sr' },
    answer: 'C',
    explanation: 'Gümüş\'ün sembolü Ag\'dır; Latincede "gümüş parlak" anlamına gelen "Argentum"dan gelir.',
  },
  {
    id: 'gen_74',
    text: 'What is the study of the Earth\'s physical structure called?',
    text_tr: 'Dünya\'nın fiziksel yapısını inceleyen bilim dalının adı nedir?',
    options: { A: 'Oceanography', B: 'Meteorology', C: 'Seismology', D: 'Geology', E: 'Cosmology' },
    options_tr: { A: 'Oşinografi', B: 'Meteoroloji', C: 'Sismoloji', D: 'Jeoloji', E: 'Kozmoloji' },
    answer: 'D',
    explanation: 'Jeoloji, Dünya\'nın katı maddesi, kabuğu ve tarihi süreçleri inceleyen bilim dalıdır.',
  },
  {
    id: 'gen_75',
    text: 'Which type of radiation has the shortest wavelength?',
    text_tr: 'En kısa dalga boyuna sahip radyasyon türü hangisidir?',
    options: { A: 'Radio waves', B: 'Infrared', C: 'Ultraviolet', D: 'X-rays', E: 'Gamma rays' },
    options_tr: { A: 'Radyo dalgaları', B: 'Kızılötesi', C: 'Morötesi', D: 'X-ışınları', E: 'Gama ışınları' },
    answer: 'E',
    explanation: 'Gama ışınları elektromanyetik spektrumun en yüksek enerjili ve en kısa dalgaboylu radyasyonudur.',
  },
  {
    id: 'gen_76',
    text: 'How many muscles are in the human body (approximately)?',
    text_tr: 'İnsan vücudunda yaklaşık kaç kas bulunur?',
    options: { A: '300', B: '450', C: '600', D: '750', E: '900' },
    options_tr: { A: '300', B: '450', C: '600', D: '750', E: '900' },
    answer: 'C',
    explanation: 'İnsan vücudunda yaklaşık 600 iskelet kası bulunur; bunların yanı sıra düz kaslar ve kalp kası da vardır.',
  },
  {
    id: 'gen_77',
    text: 'What is the most common element in the universe?',
    text_tr: 'Evrende en yaygın bulunan element hangisidir?',
    options: { A: 'Helium', B: 'Carbon', C: 'Oxygen', D: 'Hydrogen', E: 'Iron' },
    options_tr: { A: 'Helyum', B: 'Karbon', C: 'Oksijen', D: 'Hidrojen', E: 'Demir' },
    answer: 'D',
    explanation: 'Hidrojen, evrendeki bilinen tüm atomların yaklaşık %75\'ini oluşturan en bol elementtir.',
  },
  {
    id: 'gen_78',
    text: 'What phenomenon causes the sky to appear blue?',
    text_tr: 'Gökyüzünün mavi görünmesine hangi olgu neden olur?',
    options: { A: 'Refraction of sunlight', B: 'Reflection from the ocean', C: 'Rayleigh scattering of sunlight', D: 'Absorption of red light', E: 'Ozone layer reflection' },
    options_tr: { A: 'Güneş ışığının kırılması', B: 'Okyanusun yansıması', C: 'Güneş ışığının Rayleigh saçılması', D: 'Kırmızı ışığın soğurulması', E: 'Ozon katmanının yansıması' },
    answer: 'C',
    explanation: 'Rayleigh saçılması, güneş ışığının atmosferdeki gaz molekülleriyle etkileşiminde mavi ışığın daha fazla dağılmasına yol açar ve bu nedenle gökyüzü mavi görünür.',
  },
  {
    id: 'gen_79',
    text: 'Which animal has the highest blood pressure?',
    text_tr: 'En yüksek kan basıncına sahip hayvan hangisidir?',
    options: { A: 'Elephant', B: 'Blue Whale', C: 'Giraffe', D: 'Cheetah', E: 'Gorilla' },
    options_tr: { A: 'Fil', B: 'Mavi Balina', C: 'Zürafa', D: 'Çita', E: 'Goril' },
    answer: 'C',
    explanation: 'Zürafanın, beynine 2 metrelik boynu boyunca kan pompalayabilmek için 300/180 mmHg\'yi aşan olağanüstü yüksek kan basıncı vardır.',
  },
  {
    id: 'gen_80',
    text: 'What type of bond holds water molecules together (hydrogen bonding)?',
    text_tr: 'Su moleküllerini bir arada tutan bağ türü nedir?',
    options: { A: 'Ionic bond', B: 'Covalent bond', C: 'Hydrogen bond', D: 'Metallic bond', E: 'Van der Waals force' },
    options_tr: { A: 'İyonik bağ', B: 'Kovalent bağ', C: 'Hidrojen bağı', D: 'Metalik bağ', E: 'Van der Waals kuvvetleri' },
    answer: 'C',
    explanation: 'Su molekülleri arasındaki hidrojen bağları, suyun yüksek kaynama noktası ve yüzey gerilimi gibi olağanüstü özelliklerine yol açar.',
  },
  {
    id: 'gen_81',
    text: 'Which planet has the shortest day (fastest rotation)?',
    text_tr: 'Hangi gezegenin günü en kısadır (en hızlı döner)?',
    options: { A: 'Saturn', B: 'Uranus', C: 'Neptune', D: 'Jupiter', E: 'Mars' },
    options_tr: { A: 'Satürn', B: 'Uranüs', C: 'Neptün', D: 'Jüpiter', E: 'Mars' },
    answer: 'D',
    explanation: 'Jüpiter yaklaşık 9 saat 56 dakikada bir kez döner; bu onu güneş sisteminin en hızlı dönen gezegeni yapar.',
  },
  {
    id: 'gen_82',
    text: 'What is the name of the scale used to measure wind speed?',
    text_tr: 'Rüzgar hızını ölçmek için kullanılan skalanın adı nedir?',
    options: { A: 'Richter Scale', B: 'Fujita Scale', C: 'Saffir-Simpson Scale', D: 'Beaufort Scale', E: 'Mercalli Scale' },
    options_tr: { A: 'Richter Skalası', B: 'Fujita Skalası', C: 'Saffir-Simpson Skalası', D: 'Beaufort Skalası', E: 'Mercalli Skalası' },
    answer: 'D',
    explanation: 'Beaufort Skalası, 0 (durgun) ile 12 (kasırga) arasında rüzgar hızını ve kuvvetini tanımlar.',
  },
  {
    id: 'gen_83',
    text: 'What is the process of a caterpillar transforming into a butterfly called?',
    text_tr: 'Tırtılın kelebeğe dönüşme sürecinin adı nedir?',
    options: { A: 'Metamorphosis', B: 'Molting', C: 'Transfiguration', D: 'Evolution', E: 'Adaptation' },
    options_tr: { A: 'Başkalaşım (metamorfoz)', B: 'Deri değişimi', C: 'Dönüşüm', D: 'Evrim', E: 'Adaptasyon' },
    answer: 'A',
    explanation: 'Tam başkalaşım (holometabolizm), yumurta → larva (tırtıl) → pupa (krizalit) → ergin (kelebek) aşamalarından oluşur.',
  },
  {
    id: 'gen_84',
    text: 'Which element is the main component of the Sun?',
    text_tr: 'Güneş\'in ana bileşenini oluşturan element hangisidir?',
    options: { A: 'Carbon', B: 'Oxygen', C: 'Helium', D: 'Neon', E: 'Hydrogen' },
    options_tr: { A: 'Karbon', B: 'Oksijen', C: 'Helyum', D: 'Neon', E: 'Hidrojen' },
    answer: 'E',
    explanation: 'Güneş kütlesinin yaklaşık %73\'ü hidrojenden oluşur; bu hidrojen, nükleer füzyon yoluyla helyuma dönüştürülür.',
  },
  {
    id: 'gen_85',
    text: 'What is the name of the hormone responsible for regulating blood sugar?',
    text_tr: 'Kan şekerini düzenleyen hormonun adı nedir?',
    options: { A: 'Adrenaline', B: 'Cortisol', C: 'Insulin', D: 'Glucagon', E: 'Thyroxine' },
    options_tr: { A: 'Adrenalin', B: 'Kortizol', C: 'İnsülin', D: 'Glukagon', E: 'Tiroksin' },
    answer: 'C',
    explanation: 'İnsülin, pankreastaki beta hücreleri tarafından üretilen ve kan şekerini düşüren hormondur.',
  },
  {
    id: 'gen_86',
    text: 'What is the approximate age of the universe?',
    text_tr: 'Evrenin yaklaşık yaşı nedir?',
    options: { A: '4.6 billion years', B: '8.2 billion years', C: '10.5 billion years', D: '13.8 billion years', E: '20 billion years' },
    options_tr: { A: '4,6 milyar yıl', B: '8,2 milyar yıl', C: '10,5 milyar yıl', D: '13,8 milyar yıl', E: '20 milyar yıl' },
    answer: 'D',
    explanation: 'Evrenin yaşı, kozmik mikrodalga arka plan radyasyonu ölçümlerine dayanılarak yaklaşık 13,8 milyar yıl olarak hesaplanmıştır.',
  },
  {
    id: 'gen_87',
    text: 'What is the name of the protein that carries oxygen in the blood?',
    text_tr: 'Kanda oksijen taşıyan proteinin adı nedir?',
    options: { A: 'Myosin', B: 'Albumin', C: 'Keratin', D: 'Haemoglobin', E: 'Collagen' },
    options_tr: { A: 'Miyozin', B: 'Albumin', C: 'Keratin', D: 'Hemoglobin', E: 'Kolajen' },
    answer: 'D',
    explanation: 'Hemoglobin, kırmızı kan hücrelerinde bulunan ve demiri sayesinde akciğerlerden dokulara oksijen taşıyan proteindir.',
  },
  {
    id: 'gen_88',
    text: 'What is the SI unit of force?',
    text_tr: 'Kuvvetin SI birimi nedir?',
    options: { A: 'Joule', B: 'Watt', C: 'Newton', D: 'Pascal', E: 'Dyne' },
    options_tr: { A: 'Joule', B: 'Watt', C: 'Newton', D: 'Pascal', E: 'Din' },
    answer: 'C',
    explanation: 'Newton (N), Isaac Newton\'ın adından gelen kuvvet birimidir; 1 N = 1 kg·m/s² olarak tanımlanır.',
  },
  {
    id: 'gen_89',
    text: 'Which part of the plant conducts water from the roots to the leaves?',
    text_tr: 'Bitkide köklerden yapraklara su ileten bölüm nedir?',
    options: { A: 'Phloem', B: 'Epidermis', C: 'Cortex', D: 'Xylem', E: 'Cambium' },
    options_tr: { A: 'Floem', B: 'Epidermis', C: 'Korteks', D: 'Ksilem', E: 'Kambiyum' },
    answer: 'D',
    explanation: 'Ksilem, köklerden gövde ve yapraklara su ve mineral tuzlarını taşıyan iletim dokusudur.',
  },
  {
    id: 'gen_90',
    text: 'What is the name of the process through which atomic nuclei combine to release energy?',
    text_tr: 'Atom çekirdeklerinin birleşerek enerji salması sürecinin adı nedir?',
    options: { A: 'Fission', B: 'Fusion', C: 'Combustion', D: 'Oxidation', E: 'Radioactive decay' },
    options_tr: { A: 'Fisyon', B: 'Füzyon', C: 'Yanma', D: 'Oksidasyon', E: 'Radyoaktif bozunma' },
    answer: 'B',
    explanation: 'Nükleer füzyon, hafif çekirdeklerin (örneğin hidrojen) birleşerek daha ağır çekirdekler oluşturması ve bu sırada büyük miktarda enerji salmasıdır.',
  },
  {
    id: 'gen_91',
    text: 'How long does it take for light from the Sun to reach Earth?',
    text_tr: 'Güneş\'ten Dünya\'ya ışığın ulaşması ne kadar sürer?',
    options: { A: 'About 2 minutes', B: 'About 4 minutes', C: 'About 8 minutes', D: 'About 15 minutes', E: 'About 30 minutes' },
    options_tr: { A: 'Yaklaşık 2 dakika', B: 'Yaklaşık 4 dakika', C: 'Yaklaşık 8 dakika', D: 'Yaklaşık 15 dakika', E: 'Yaklaşık 30 dakika' },
    answer: 'C',
    explanation: 'Güneş\'ten Dünya\'ya ışık yaklaşık 8 dakika 20 saniyede ulaşır.',
  },
  {
    id: 'gen_92',
    text: 'What does "laser" stand for?',
    text_tr: '"Laser" (lazer) kısaltması neyi ifade eder?',
    options: { A: 'Light Amplification by Simulated Electromagnetic Radiation', B: 'Light Amplification by Stimulated Emission of Radiation', C: 'Linear Amplification of Spectral Energy Radiation', D: 'Luminous Array of Synchronised Energy Rays', E: 'Light Amplification by Standard Emission Rays' },
    options_tr: { A: 'Simüle Edilmiş Elektromanyetik Radyasyonla Işık Amplifikasyonu', B: 'Uyarılmış Emisyonla Radyasyonun Işık Amplifikasyonu', C: 'Spektral Enerji Radyasyonunun Doğrusal Amplifikasyonu', D: 'Senkronize Enerji Işınlarının Aydınlatma Dizisi', E: 'Standart Emisyon Işınlarıyla Işık Amplifikasyonu' },
    answer: 'B',
    explanation: 'LASER, "Light Amplification by Stimulated Emission of Radiation" ifadesinin kısaltmasıdır.',
  },
  {
    id: 'gen_93',
    text: 'Which is the smallest planet in our solar system?',
    text_tr: 'Güneş sistemimizin en küçük gezegeni hangisidir?',
    options: { A: 'Mars', B: 'Venus', C: 'Earth', D: 'Mercury', E: 'Pluto' },
    options_tr: { A: 'Mars', B: 'Venüs', C: 'Dünya', D: 'Merkür', E: 'Plüton' },
    answer: 'D',
    explanation: 'Merkür, güneş sisteminin en küçük gezegenidir (Plüton cüce gezegen statüsündedir).',
  },
  {
    id: 'gen_94',
    text: 'What is the name of the hormone produced during stress?',
    text_tr: 'Stres sırasında üretilen hormonun adı nedir?',
    options: { A: 'Serotonin', B: 'Dopamine', C: 'Cortisol', D: 'Oxytocin', E: 'Melatonin' },
    options_tr: { A: 'Serotonin', B: 'Dopamin', C: 'Kortizol', D: 'Oksitosin', E: 'Melatonin' },
    answer: 'C',
    explanation: 'Kortizol, strese tepki olarak böbreküstü bezlerinden salgılanan temel stres hormonudur.',
  },
  {
    id: 'gen_95',
    text: 'What is the name of the boundary between two tectonic plates?',
    text_tr: 'İki tektonik levha arasındaki sınırın adı nedir?',
    options: { A: 'Fault line', B: 'Rift', C: 'Tectonic boundary', D: 'Plate boundary', E: 'Seismic zone' },
    options_tr: { A: 'Fay hattı', B: 'Rift', C: 'Tektonik sınır', D: 'Levha sınırı', E: 'Sismik bölge' },
    answer: 'D',
    explanation: 'Levha sınırları, tektonik levhaların birbirleriyle temas ettiği alanlardır; depremler ve volkanik etkinlikler bu sınırlarda yoğunlaşır.',
  },
  {
    id: 'gen_96',
    text: 'Which type of telescope uses mirrors to collect light?',
    text_tr: 'Işık toplamak için ayna kullanan teleskop türü nedir?',
    options: { A: 'Refracting telescope', B: 'Radio telescope', C: 'Reflecting telescope', D: 'X-ray telescope', E: 'Infrared telescope' },
    options_tr: { A: 'Kırıcı teleskop', B: 'Radyo teleskobu', C: 'Yansıtmalı teleskop', D: 'X-ışını teleskobu', E: 'Kızılötesi teleskop' },
    answer: 'C',
    explanation: 'Yansıtmalı (reflektör) teleskoplar, ışığı toplamak ve odaklamak için ayna kullanır; Isaac Newton ilk yansıtmalı teleskobu 1668\'de yaptı.',
  },
  {
    id: 'gen_97',
    text: 'What is the function of the ozone layer?',
    text_tr: 'Ozon tabakasının işlevi nedir?',
    options: { A: 'Regulates Earth\'s temperature', B: 'Absorbs harmful UV radiation from the Sun', C: 'Produces oxygen for breathing', D: 'Reflects radio waves for communication', E: 'Filters harmful gamma rays' },
    options_tr: { A: 'Dünya\'nın sıcaklığını düzenler', B: 'Güneş\'ten gelen zararlı UV radyasyonunu emer', C: 'Nefes alınan oksijeni üretir', D: 'Radyo dalgalarını iletişim için yansıtır', E: 'Zararlı gama ışınlarını süzer' },
    answer: 'B',
    explanation: 'Stratosferdeki ozon tabakası, canlılar için zararlı olan Güneş\'in UV-B ve UV-C radyasyonunun büyük bölümünü emer.',
  },
  {
    id: 'gen_98',
    text: 'What causes the Northern Lights (Aurora Borealis)?',
    text_tr: 'Kuzey Işıklarına (Kuzey Kutbu Işıması) ne sebep olur?',
    options: { A: 'Moonlight reflecting off ice crystals', B: 'Solar wind particles colliding with Earth\'s atmosphere', C: 'Volcanic gases in the upper atmosphere', D: 'Refraction of sunlight near the poles', E: 'Cosmic radiation hitting the stratosphere' },
    options_tr: { A: 'Ay ışığının buz kristallerinden yansıması', B: 'Güneş rüzgarı parçacıklarının Dünya atmosferiyle çarpışması', C: 'Üst atmosferdeki volkanik gazlar', D: 'Kutuplar yakınında güneş ışığının kırılması', E: 'Kozmik radyasyonun stratosfere çarpması' },
    answer: 'B',
    explanation: 'Kuzey Işıkları, manyetik alan boyunca atmosfere giren güneş rüzgarı parçacıklarının oksijen ve azot atomlarıyla çarpışması sonucu oluşur.',
  },
  {
    id: 'gen_99',
    text: 'What is the name of the coloured part of the human eye?',
    text_tr: 'İnsan gözünün renkli bölümünün adı nedir?',
    options: { A: 'Pupil', B: 'Retina', C: 'Cornea', D: 'Iris', E: 'Sclera' },
    options_tr: { A: 'Göz bebeği', B: 'Retina', C: 'Kornea', D: 'İris', E: 'Sklera' },
    answer: 'D',
    explanation: 'İris, göze rengini veren ve ışık miktarını düzenlemek için göz bebeğinin boyutunu kontrol eden halka biçimli kas yapıdır.',
  },
  {
    id: 'gen_100',
    text: 'Which Turkish scientist is known for his work on rocket propulsion and is called the father of modern rocketry?',
    text_tr: 'Roket itiş gücü alanındaki çalışmalarıyla tanınan ve modern roketchiliğin babası olarak anılan bilim insanı kimdir?',
    options: { A: 'Aziz Sancar', B: 'Cahit Arf', C: 'Oktay Sinanoğlu', D: 'Feza Gürsey', E: 'Ali Kuşçu' },
    options_tr: { A: 'Aziz Sancar', B: 'Cahit Arf', C: 'Oktay Sinanoğlu', D: 'Feza Gürsey', E: 'Ali Kuşçu' },
    answer: 'E',
    explanation: 'Ali Kuşçu (1403–1474), Osmanlı döneminin önde gelen astronomu ve matematikçisidir; Fatih Sultan Mehmet\'in daveti üzerine İstanbul\'a gelmiş ve astronomi alanındaki özgün çalışmalarıyla tanınmıştır.',
  },
];

module.exports = { general };
