'use strict';

const geography = [
  {
    id: 'geo_01',
    text: 'Which is the largest country in the world by land area?',
    text_tr: 'Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?',
    options: { A: 'Canada', B: 'China', C: 'United States', D: 'Brazil', E: 'Russia' },
    options_tr: { A: 'Kanada', B: 'Çin', C: 'Amerika Birleşik Devletleri', D: 'Brezilya', E: 'Rusya' },
    answer: 'E',
    explanation: 'Russia is the largest country in the world, covering approximately 17.1 million km², which is over twice the size of Canada.',
  },
  {
    id: 'geo_02',
    text: 'What is the capital city of Australia?',
    text_tr: 'Avustralya\'nın başkenti neresidir?',
    options: { A: 'Sydney', B: 'Melbourne', C: 'Brisbane', D: 'Canberra', E: 'Perth' },
    options_tr: { A: 'Sidney', B: 'Melbourne', C: 'Brisbane', D: 'Canberra', E: 'Perth' },
    answer: 'D',
    explanation: 'Canberra is the capital of Australia, chosen as a compromise between Sydney and Melbourne when Australia federated in 1901.',
  },
  {
    id: 'geo_03',
    text: 'Which river is the longest in the world?',
    text_tr: 'Dünyanın en uzun nehri hangisidir?',
    options: { A: 'Amazon', B: 'Yangtze', C: 'Mississippi', D: 'Congo', E: 'Nile' },
    options_tr: { A: 'Amazon', B: 'Yangtze', C: 'Mississippi', D: 'Kongo', E: 'Nil' },
    answer: 'E',
    explanation: 'The Nile River in Africa is generally considered the world\'s longest river at approximately 6,650 km, though some studies suggest the Amazon may be longer.',
  },
  {
    id: 'geo_04',
    text: 'Which mountain range separates Europe from Asia in Russia?',
    text_tr: 'Rusya\'da Avrupa\'yı Asya\'dan ayıran dağ silsilesi hangisidir?',
    options: { A: 'Caucasus Mountains', B: 'Ural Mountains', C: 'Altai Mountains', D: 'Carpathian Mountains', E: 'Zagros Mountains' },
    options_tr: { A: 'Kafkas Dağları', B: 'Ural Dağları', C: 'Altay Dağları', D: 'Karpatlar', E: 'Zagros Dağları' },
    answer: 'B',
    explanation: 'The Ural Mountains form the traditional geographic boundary between Europe and Asia, stretching about 2,500 km through Russia.',
  },
  {
    id: 'geo_05',
    text: 'Which strait separates Europe (Spain) from Africa (Morocco)?',
    text_tr: 'Avrupa\'yı (İspanya) Afrika\'dan (Fas) ayıran boğaz hangisidir?',
    options: { A: 'Strait of Messina', B: 'Strait of Otranto', C: 'Strait of Gibraltar', D: 'Strait of Bosporus', E: 'Strait of Hormuz' },
    options_tr: { A: 'Messina Boğazı', B: 'Otranto Boğazı', C: 'Cebelitarık Boğazı', D: 'İstanbul Boğazı', E: 'Hürmüz Boğazı' },
    answer: 'C',
    explanation: 'The Strait of Gibraltar separates the Iberian Peninsula (Europe) from Morocco (Africa) and connects the Atlantic Ocean to the Mediterranean Sea.',
  },
  {
    id: 'geo_06',
    text: 'What is the capital of Turkey?',
    text_tr: 'Türkiye\'nin başkenti neresidir?',
    options: { A: 'Istanbul', B: 'Izmir', C: 'Ankara', D: 'Bursa', E: 'Antalya' },
    options_tr: { A: 'İstanbul', B: 'İzmir', C: 'Ankara', D: 'Bursa', E: 'Antalya' },
    answer: 'C',
    explanation: 'Ankara has been the capital of Turkey since 1923, following the founding of the Republic.',
  },
  {
    id: 'geo_07',
    text: 'Which is the smallest country in the world by land area?',
    text_tr: 'Yüzölçümü bakımından dünyanın en küçük ülkesi hangisidir?',
    options: { A: 'Monaco', B: 'San Marino', C: 'Vatican City', D: 'Liechtenstein', E: 'Nauru' },
    options_tr: { A: 'Monako', B: 'San Marino', C: 'Vatikan', D: 'Lihtenştayn', E: 'Nauru' },
    answer: 'C',
    explanation: 'Vatican City, at about 0.49 km², is the smallest sovereign state in the world, both by area and population.',
  },
  {
    id: 'geo_08',
    text: 'Which desert is the largest hot desert in the world?',
    text_tr: 'Dünyanın en büyük sıcak çölü hangisidir?',
    options: { A: 'Gobi Desert', B: 'Kalahari Desert', C: 'Sahara Desert', D: 'Arabian Desert', E: 'Thar Desert' },
    options_tr: { A: 'Gobi Çölü', B: 'Kalahari Çölü', C: 'Sahra Çölü', D: 'Arap Çölü', E: 'Thar Çölü' },
    answer: 'C',
    explanation: 'The Sahara, covering much of North Africa, is the largest hot desert in the world at about 9.2 million km².',
  },
  {
    id: 'geo_09',
    text: 'Which is the tallest mountain in the world, measured from sea level?',
    text_tr: 'Deniz seviyesinden ölçüldüğünde dünyanın en yüksek dağı hangisidir?',
    options: { A: 'K2', B: 'Kangchenjunga', C: 'Mount Everest', D: 'Denali', E: 'Aconcagua' },
    options_tr: { A: 'K2', B: 'Kangchenjunga', C: 'Everest Dağı', D: 'Denali', E: 'Aconcagua' },
    answer: 'C',
    explanation: 'Mount Everest, on the border of Nepal and Tibet, stands at 8,849 meters above sea level.',
  },
  {
    id: 'geo_10',
    text: 'Which African country was formerly known as Abyssinia and is one of the oldest independent nations in Africa?',
    text_tr: 'Eskiden Habeşistan olarak bilinen ve Afrika\'nın en eski bağımsız uluslarından biri olan Afrika ülkesi hangisidir?',
    options: { A: 'Sudan', B: 'Ethiopia', C: 'Kenya', D: 'Somalia', E: 'Eritrea' },
    options_tr: { A: 'Sudan', B: 'Etiyopya', C: 'Kenya', D: 'Somali', E: 'Eritre' },
    answer: 'B',
    explanation: 'Ethiopia, historically called Abyssinia, was never formally colonized (except for a brief Italian occupation, 1936–1941).',
  },
  {
    id: 'geo_11',
    text: 'Which sea is the saltiest large body of water in the world, so dense that swimmers float easily?',
    text_tr: 'Yüzücülerin kolayca yüzebildiği, dünyanın en tuzlu büyük su kütlesi hangi denizdir?',
    options: { A: 'Red Sea', B: 'Caspian Sea', C: 'Dead Sea', D: 'Black Sea', E: 'Aral Sea' },
    options_tr: { A: 'Kızıldeniz', B: 'Hazar Denizi', C: 'Lut Gölü (Ölü Deniz)', D: 'Karadeniz', E: 'Aral Gölü' },
    answer: 'C',
    explanation: 'The Dead Sea, bordering Israel, Jordan, and the West Bank, has a salinity of about 34%, making it extremely buoyant.',
  },
  {
    id: 'geo_12',
    text: 'Which South American country has both a Pacific and no Atlantic coastline, and includes part of the Atacama Desert?',
    text_tr: 'Yalnızca Pasifik kıyısı olan ve Atacama Çölü\'nün bir kısmını içeren Güney Amerika ülkesi hangisidir?',
    options: { A: 'Peru', B: 'Bolivia', C: 'Chile', D: 'Ecuador', E: 'Colombia' },
    options_tr: { A: 'Peru', B: 'Bolivya', C: 'Şili', D: 'Ekvador', E: 'Kolombiya' },
    answer: 'C',
    explanation: 'Chile is a long, narrow country along South America\'s Pacific coast and contains the Atacama Desert, the driest non-polar desert on Earth.',
  },
  {
    id: 'geo_13',
    text: 'What is the capital of Canada?',
    text_tr: 'Kanada\'nın başkenti neresidir?',
    options: { A: 'Toronto', B: 'Vancouver', C: 'Montreal', D: 'Ottawa', E: 'Quebec City' },
    options_tr: { A: 'Toronto', B: 'Vancouver', C: 'Montreal', D: 'Ottava', E: 'Quebec City' },
    answer: 'D',
    explanation: 'Ottawa, in the province of Ontario, has been Canada\'s capital since 1857.',
  },
  {
    id: 'geo_14',
    text: 'Which is the largest island in the world (not counting continental landmasses)?',
    text_tr: 'Kıtasal kara parçaları hariç, dünyanın en büyük adası hangisidir?',
    options: { A: 'Borneo', B: 'Madagascar', C: 'Greenland', D: 'New Guinea', E: 'Baffin Island' },
    options_tr: { A: 'Borneo', B: 'Madagaskar', C: 'Grönland', D: 'Yeni Gine', E: 'Baffin Adası' },
    answer: 'C',
    explanation: 'Greenland, an autonomous territory of Denmark, is the world\'s largest island at about 2.16 million km².',
  },
  {
    id: 'geo_15',
    text: 'Which strait connects the Black Sea to the Sea of Marmara, running through Istanbul?',
    text_tr: 'İstanbul\'dan geçerek Karadeniz\'i Marmara Denizi\'ne bağlayan boğaz hangisidir?',
    options: { A: 'Strait of Gibraltar', B: 'Bosporus Strait', C: 'Dardanelles Strait', D: 'Strait of Dover', E: 'Kerch Strait' },
    options_tr: { A: 'Cebelitarık Boğazı', B: 'İstanbul (Boğaziçi) Boğazı', C: 'Çanakkale Boğazı', D: 'Dover Boğazı', E: 'Kerç Boğazı' },
    answer: 'B',
    explanation: 'The Bosporus Strait runs through the heart of Istanbul, connecting the Black Sea to the Sea of Marmara.',
  },
  {
    id: 'geo_16',
    text: 'Which country has the most natural lakes in the world?',
    text_tr: 'Dünyada en çok doğal göle sahip ülke hangisidir?',
    options: { A: 'Russia', B: 'United States', C: 'Finland', D: 'Canada', E: 'Sweden' },
    options_tr: { A: 'Rusya', B: 'Amerika Birleşik Devletleri', C: 'Finlandiya', D: 'Kanada', E: 'İsveç' },
    answer: 'D',
    explanation: 'Canada has more lakes than the rest of the world\'s countries combined, largely due to glacial activity during the last Ice Age.',
  },
  {
    id: 'geo_17',
    text: 'Which mountain range contains the highest peaks on Earth, including Everest and K2?',
    text_tr: 'Everest ve K2 dahil dünyanın en yüksek zirvelerini içeren dağ silsilesi hangisidir?',
    options: { A: 'Andes', B: 'Rocky Mountains', C: 'Alps', D: 'Himalayas', E: 'Atlas Mountains' },
    options_tr: { A: 'And Dağları', B: 'Kayalık Dağlar', C: 'Alpler', D: 'Himalayalar', E: 'Atlas Dağları' },
    answer: 'D',
    explanation: 'The Himalayas, spanning several South and Central Asian countries, include 10 of the world\'s 14 peaks over 8,000 meters.',
  },
  {
    id: 'geo_18',
    text: 'What is the longest mountain range in the world, running along the western edge of South America?',
    text_tr: 'Güney Amerika\'nın batı kıyısı boyunca uzanan, dünyanın en uzun dağ silsilesi hangisidir?',
    options: { A: 'Rocky Mountains', B: 'Andes', C: 'Himalayas', D: 'Ural Mountains', E: 'Great Dividing Range' },
    options_tr: { A: 'Kayalık Dağlar', B: 'And Dağları', C: 'Himalayalar', D: 'Ural Dağları', E: 'Büyük Su Ayrım Sırası' },
    answer: 'B',
    explanation: 'The Andes stretch about 7,000 km along South America\'s western coast, making it the longest continental mountain range in the world.',
  },
  {
    id: 'geo_19',
    text: 'Which Turkish lake is the largest lake in Turkey, located in the east of the country?',
    text_tr: 'Türkiye\'nin doğusunda yer alan ve ülkenin en büyük gölü olan göl hangisidir?',
    options: { A: 'Lake Tuz', B: 'Lake Van', C: 'Lake Beyşehir', D: 'Lake Eğirdir', E: 'Lake İznik' },
    options_tr: { A: 'Tuz Gölü', B: 'Van Gölü', C: 'Beyşehir Gölü', D: 'Eğirdir Gölü', E: 'İznik Gölü' },
    answer: 'B',
    explanation: 'Lake Van, in eastern Turkey, is the country\'s largest lake and one of the world\'s largest soda lakes.',
  },
  {
    id: 'geo_20',
    text: 'Which country has the most time zones of any nation in the world?',
    text_tr: 'Dünyada en çok saat dilimine sahip ülke hangisidir?',
    options: { A: 'United States', B: 'Russia', C: 'China', D: 'France', E: 'Australia' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Rusya', C: 'Çin', D: 'Fransa', E: 'Avustralya' },
    answer: 'D',
    explanation: 'France has 12 time zones due to its overseas territories scattered around the globe, more than any other country.',
  },
  {
    id: 'geo_21',
    text: 'Which two continents does the country of Turkey span?',
    text_tr: 'Türkiye hangi iki kıta üzerinde yer almaktadır?',
    options: { A: 'Africa and Asia', B: 'Europe and Africa', C: 'Europe and Asia', D: 'Asia and North America', E: 'Europe and North America' },
    options_tr: { A: 'Afrika ve Asya', B: 'Avrupa ve Afrika', C: 'Avrupa ve Asya', D: 'Asya ve Kuzey Amerika', E: 'Avrupa ve Kuzey Amerika' },
    answer: 'C',
    explanation: 'Turkey spans both Europe (a small portion, including part of Istanbul) and Asia (the larger Anatolian peninsula).',
  },
  {
    id: 'geo_22',
    text: 'Which African country is home to Mount Kilimanjaro, the highest peak in Africa?',
    text_tr: 'Afrika\'nın en yüksek zirvesi olan Kilimanjaro Dağı\'na ev sahipliği yapan Afrika ülkesi hangisidir?',
    options: { A: 'Kenya', B: 'Uganda', C: 'Tanzania', D: 'Ethiopia', E: 'Rwanda' },
    options_tr: { A: 'Kenya', B: 'Uganda', C: 'Tanzanya', D: 'Etiyopya', E: 'Ruanda' },
    answer: 'C',
    explanation: 'Mount Kilimanjaro, at 5,895 meters, is located in Tanzania and is the highest freestanding mountain in the world.',
  },
  {
    id: 'geo_23',
    text: 'Which is the driest continent on Earth (excluding Antarctica\'s ice)?',
    text_tr: '(Antarktika\'nın buzu hariç) dünyanın en kurak kıtası hangisidir?',
    options: { A: 'Africa', B: 'Australia', C: 'Asia', D: 'South America', E: 'North America' },
    options_tr: { A: 'Afrika', B: 'Avustralya', C: 'Asya', D: 'Güney Amerika', E: 'Kuzey Amerika' },
    answer: 'B',
    explanation: 'Australia is the driest inhabited continent, with much of its interior covered by arid desert.',
  },
  {
    id: 'geo_24',
    text: 'Which body of water is the largest ocean on Earth?',
    text_tr: 'Dünyanın en büyük okyanusu hangisidir?',
    options: { A: 'Atlantic Ocean', B: 'Indian Ocean', C: 'Arctic Ocean', D: 'Pacific Ocean', E: 'Southern Ocean' },
    options_tr: { A: 'Atlas Okyanusu', B: 'Hint Okyanusu', C: 'Kuzey Buz Denizi', D: 'Pasifik Okyanusu', E: 'Güney Okyanusu' },
    answer: 'D',
    explanation: 'The Pacific Ocean is the largest and deepest ocean, covering more area than all of Earth\'s landmasses combined.',
  },
  {
    id: 'geo_25',
    text: 'Which South Asian country contains most of the Ganges Delta, shared with India?',
    text_tr: 'Hindistan ile paylaşılan Ganj Deltası\'nı içeren Güney Asya ülkesi hangisidir?',
    options: { A: 'Nepal', B: 'Bhutan', C: 'Bangladesh', D: 'Myanmar', E: 'Sri Lanka' },
    options_tr: { A: 'Nepal', B: 'Bhutan', C: 'Bangladeş', D: 'Myanmar', E: 'Sri Lanka' },
    answer: 'C',
    explanation: 'Bangladesh sits largely within the Ganges-Brahmaputra Delta, the largest river delta in the world.',
  },
  {
    id: 'geo_26',
    text: 'Which country is both the largest landlocked country in the world and located in Central Asia?',
    text_tr: 'Dünyanın hem en büyük denize kıyısı olmayan ülkesi hem de Orta Asya\'da yer alan ülke hangisidir?',
    options: { A: 'Mongolia', B: 'Kazakhstan', C: 'Uzbekistan', D: 'Afghanistan', E: 'Turkmenistan' },
    options_tr: { A: 'Moğolistan', B: 'Kazakistan', C: 'Özbekistan', D: 'Afganistan', E: 'Türkmenistan' },
    answer: 'B',
    explanation: 'Kazakhstan is the world\'s largest landlocked country by area, spanning parts of Central Asia and Eastern Europe.',
  },
  {
    id: 'geo_27',
    text: 'Which European country is famous for its many canals and is largely below sea level, protected by dikes?',
    text_tr: 'Çok sayıda kanalıyla ünlü ve set (dike) sistemleriyle korunarak büyük ölçüde deniz seviyesinin altında bulunan Avrupa ülkesi hangisidir?',
    options: { A: 'Belgium', B: 'Denmark', C: 'Netherlands', D: 'Germany', E: 'Luxembourg' },
    options_tr: { A: 'Belçika', B: 'Danimarka', C: 'Hollanda', D: 'Almanya', E: 'Lüksemburg' },
    answer: 'C',
    explanation: 'About one-third of the Netherlands lies below sea level, protected by an extensive system of dikes and pumps.',
  },
  {
    id: 'geo_28',
    text: 'Which waterfall, located on the border of Zambia and Zimbabwe, is one of the largest waterfalls in the world?',
    text_tr: 'Zambiya ve Zimbabve sınırında bulunan ve dünyanın en büyük şelalelerinden biri olan şelale hangisidir?',
    options: { A: 'Angel Falls', B: 'Niagara Falls', C: 'Iguazu Falls', D: 'Victoria Falls', E: 'Yosemite Falls' },
    options_tr: { A: 'Angel Şelalesi', B: 'Niagara Şelalesi', C: 'Iguazu Şelalesi', D: 'Victoria Şelalesi', E: 'Yosemite Şelalesi' },
    answer: 'D',
    explanation: 'Victoria Falls, on the Zambezi River, is considered one of the largest waterfalls in the world by combined width and height.',
  },
  {
    id: 'geo_29',
    text: 'Which Turkish region is known as "Cappadocia," famous for its fairy chimneys and hot air balloon rides?',
    text_tr: 'Peri bacaları ve sıcak hava balonu turlarıyla ünlü Türkiye bölgesi hangisidir?',
    options: { A: 'Pamukkale', B: 'Cappadocia', C: 'Ephesus', D: 'Mount Nemrut', E: 'Antalya' },
    options_tr: { A: 'Pamukkale', B: 'Kapadokya', C: 'Efes', D: 'Nemrut Dağı', E: 'Antalya' },
    answer: 'B',
    explanation: 'Cappadocia, in central Anatolia, is famous for its unique rock formations ("fairy chimneys") and popular hot air balloon tourism.',
  },
  {
    id: 'geo_30',
    text: 'Which country contains the geographic South Pole?',
    text_tr: 'Coğrafi Güney Kutbu\'nu içeren ülke hangisidir?',
    options: { A: 'Chile', B: 'Argentina', C: 'No country — it lies in Antarctica, under international governance', D: 'Australia', E: 'New Zealand' },
    options_tr: { A: 'Şili', B: 'Arjantin', C: 'Hiçbiri — Antarktika\'da, uluslararası yönetim altındadır', D: 'Avustralya', E: 'Yeni Zelanda' },
    answer: 'C',
    explanation: 'Antarctica, where the South Pole is located, is not owned by any single country; it is governed under the Antarctic Treaty System.',
  },
  {
    id: 'geo_31',
    text: 'Which sea is entirely enclosed by land and is technically the world\'s largest lake?',
    text_tr: 'Tamamen karayla çevrili olan ve teknik olarak dünyanın en büyük gölü sayılan deniz hangisidir?',
    options: { A: 'Black Sea', B: 'Caspian Sea', C: 'Red Sea', D: 'Baltic Sea', E: 'Aegean Sea' },
    options_tr: { A: 'Karadeniz', B: 'Hazar Denizi', C: 'Kızıldeniz', D: 'Baltık Denizi', E: 'Ege Denizi' },
    answer: 'B',
    explanation: 'The Caspian Sea, bordered by Russia, Kazakhstan, Turkmenistan, Iran, and Azerbaijan, is a landlocked body of water often classified as the world\'s largest lake.',
  },
  {
    id: 'geo_32',
    text: 'Which country is home to the Amazon Rainforest\'s largest share?',
    text_tr: 'Amazon Yağmur Ormanı\'nın en büyük payına sahip ülke hangisidir?',
    options: { A: 'Peru', B: 'Colombia', C: 'Brazil', D: 'Venezuela', E: 'Ecuador' },
    options_tr: { A: 'Peru', B: 'Kolombiya', C: 'Brezilya', D: 'Venezuela', E: 'Ekvador' },
    answer: 'C',
    explanation: 'Brazil contains about 60% of the Amazon Rainforest, the largest tropical rainforest on Earth.',
  },
  {
    id: 'geo_33',
    text: 'What is the capital of Egypt, located near the Nile Delta?',
    text_tr: 'Nil Deltası yakınında bulunan Mısır\'ın başkenti neresidir?',
    options: { A: 'Alexandria', B: 'Cairo', C: 'Giza', D: 'Luxor', E: 'Aswan' },
    options_tr: { A: 'İskenderiye', B: 'Kahire', C: 'Giza', D: 'Luksor', E: 'Asvan' },
    answer: 'B',
    explanation: 'Cairo, Egypt\'s capital, is one of the largest cities in Africa and sits just south of the Nile Delta.',
  },
  {
    id: 'geo_34',
    text: 'Which country spans 11 time zones (more than any other) but has only a single official time zone in practice?',
    text_tr: '11 saat dilimine yayılan (herhangi bir ülkeden fazla) ancak pratikte tek bir resmi saat dilimi kullanan ülke hangisidir?',
    options: { A: 'United States', B: 'Canada', C: 'Russia', D: 'China', E: 'Brazil' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Kanada', C: 'Rusya', D: 'Çin', E: 'Brezilya' },
    answer: 'D',
    explanation: 'China spans a geographic width that would cover 5 time zones, but the entire country officially uses a single time zone, Beijing Time.',
  },
  {
    id: 'geo_35',
    text: 'Which Turkish city is built on both the European and Asian sides of the Bosporus?',
    text_tr: 'Boğaziçi\'nin hem Avrupa hem de Asya yakasına kurulu Türk şehri hangisidir?',
    options: { A: 'Izmir', B: 'Istanbul', C: 'Bursa', D: 'Ankara', E: 'Antalya' },
    options_tr: { A: 'İzmir', B: 'İstanbul', C: 'Bursa', D: 'Ankara', E: 'Antalya' },
    answer: 'B',
    explanation: 'Istanbul is the only city in the world situated on two continents, straddling the Bosporus Strait.',
  },
  {
    id: 'geo_36',
    text: 'Which is the largest freshwater lake in the world by surface area?',
    text_tr: 'Yüzey alanı bakımından dünyanın en büyük tatlı su gölü hangisidir?',
    options: { A: 'Lake Victoria', B: 'Lake Baikal', C: 'Lake Superior', D: 'Lake Michigan', E: 'Lake Tanganyika' },
    options_tr: { A: 'Victoria Gölü', B: 'Baykal Gölü', C: 'Superior Gölü', D: 'Michigan Gölü', E: 'Tanganika Gölü' },
    answer: 'C',
    explanation: 'Lake Superior, one of North America\'s Great Lakes, is the largest freshwater lake in the world by surface area.',
  },
  {
    id: 'geo_37',
    text: 'Which lake, located in Russia, is the deepest lake in the world and holds about 20% of the world\'s unfrozen fresh water?',
    text_tr: 'Rusya\'da bulunan ve dünyanın en derin gölü olan, dünyanın donmamış tatlı suyunun yaklaşık %20\'sini barındıran göl hangisidir?',
    options: { A: 'Lake Baikal', B: 'Caspian Sea', C: 'Lake Ladoga', D: 'Lake Onega', E: 'Lake Balkhash' },
    options_tr: { A: 'Baykal Gölü', B: 'Hazar Denizi', C: 'Ladoga Gölü', D: 'Onega Gölü', E: 'Balkaş Gölü' },
    answer: 'A',
    explanation: 'Lake Baikal in Siberia is both the deepest (over 1,600 meters) and the largest freshwater lake by volume in the world.',
  },
  {
    id: 'geo_38',
    text: 'What is the capital of Japan?',
    text_tr: 'Japonya\'nın başkenti neresidir?',
    options: { A: 'Osaka', B: 'Kyoto', C: 'Tokyo', D: 'Yokohama', E: 'Nagoya' },
    options_tr: { A: 'Osaka', B: 'Kyoto', C: 'Tokyo', D: 'Yokohama', E: 'Nagoya' },
    answer: 'C',
    explanation: 'Tokyo has been Japan\'s capital since 1868, when it replaced Kyoto.',
  },
  {
    id: 'geo_39',
    text: 'Which peninsula, shared by Spain and Portugal, is separated from the rest of Europe by the Pyrenees mountains?',
    text_tr: 'İspanya ve Portekiz tarafından paylaşılan ve Pirene Dağları ile Avrupa\'nın geri kalanından ayrılan yarımada hangisidir?',
    options: { A: 'Balkan Peninsula', B: 'Italian Peninsula', C: 'Iberian Peninsula', D: 'Scandinavian Peninsula', E: 'Anatolian Peninsula' },
    options_tr: { A: 'Balkan Yarımadası', B: 'İtalyan Yarımadası', C: 'İber Yarımadası', D: 'İskandinav Yarımadası', E: 'Anadolu Yarımadası' },
    answer: 'C',
    explanation: 'The Iberian Peninsula, home to Spain and Portugal, is bordered to the north by the Pyrenees mountain range.',
  },
  {
    id: 'geo_40',
    text: 'Which African country is completely surrounded by South Africa\'s territory (an enclave)?',
    text_tr: 'Tamamen Güney Afrika toprakları içinde bulunan (bir anklav olan) Afrika ülkesi hangisidir?',
    options: { A: 'Eswatini', B: 'Lesotho', C: 'Botswana', D: 'Zimbabwe', E: 'Namibia' },
    options_tr: { A: 'Esvatini', B: 'Lesoto', C: 'Botsvana', D: 'Zimbabve', E: 'Namibya' },
    answer: 'B',
    explanation: 'Lesotho is entirely surrounded by South Africa, making it one of only three countries in the world that are enclaves within a single other nation.',
  },
  {
    id: 'geo_41',
    text: 'Which US state is the largest by land area?',
    text_tr: 'Yüzölçümü bakımından en büyük ABD eyaleti hangisidir?',
    options: { A: 'Texas', B: 'California', C: 'Alaska', D: 'Montana', E: 'New Mexico' },
    options_tr: { A: 'Teksas', B: 'Kaliforniya', C: 'Alaska', D: 'Montana', E: 'New Mexico' },
    answer: 'C',
    explanation: 'Alaska is by far the largest US state, more than twice the size of Texas, the second largest.',
  },
  {
    id: 'geo_42',
    text: 'Which strait, roughly 33 km wide at its narrowest point, separates the United Kingdom from mainland Europe?',
    text_tr: 'En dar yerinde yaklaşık 33 km genişliğinde olan ve Birleşik Krallık ile Avrupa anakarasını ayıran boğaz hangisidir?',
    options: { A: 'Strait of Gibraltar', B: 'Strait of Dover', C: 'Öresund Strait', D: 'Strait of Messina', E: 'English Channel Tunnel (not a strait)' },
    options_tr: { A: 'Cebelitarık Boğazı', B: 'Dover Boğazı', C: 'Öresund Boğazı', D: 'Messina Boğazı', E: 'Manş Tüneli (boğaz değil)' },
    answer: 'B',
    explanation: 'The Strait of Dover, the narrowest part of the English Channel, separates England from France by about 33 km.',
  },
  {
    id: 'geo_43',
    text: 'Which South American country is home to the Galápagos Islands, famous for inspiring Darwin\'s theory of evolution?',
    text_tr: 'Darwin\'in evrim teorisine ilham veren Galápagos Adaları\'na ev sahipliği yapan Güney Amerika ülkesi hangisidir?',
    options: { A: 'Peru', B: 'Colombia', C: 'Ecuador', D: 'Chile', E: 'Venezuela' },
    options_tr: { A: 'Peru', B: 'Kolombiya', C: 'Ekvador', D: 'Şili', E: 'Venezuela' },
    answer: 'C',
    explanation: 'The Galápagos Islands, an Ecuadorian province, sit about 1,000 km off the country\'s Pacific coast.',
  },
  {
    id: 'geo_44',
    text: 'Which is the only sea in the world with no coastline, named for the floating seaweed found within it?',
    text_tr: 'İçinde bulunan yüzen deniz yosunundan adını alan, kıyısı olmayan tek deniz hangisidir?',
    options: { A: 'Coral Sea', B: 'Sargasso Sea', C: 'Sea of Japan', D: 'Tasman Sea', E: 'Ross Sea' },
    options_tr: { A: 'Mercan Denizi', B: 'Sargasso Denizi', C: 'Japon Denizi', D: 'Tasman Denizi', E: 'Ross Denizi' },
    answer: 'B',
    explanation: 'The Sargasso Sea, located entirely within the Atlantic Ocean, is bounded by ocean currents rather than land.',
  },
  {
    id: 'geo_45',
    text: 'Which Turkish mountain is famously associated with the resting place of Noah\'s Ark in religious tradition?',
    text_tr: 'Dini gelenekte Nuh\'un Gemisi\'nin karaya oturduğu yer olarak ünlü olan Türk dağı hangisidir?',
    options: { A: 'Mount Erciyes', B: 'Mount Ararat', C: 'Mount Nemrut', D: 'Mount Süphan', E: 'Uludağ' },
    options_tr: { A: 'Erciyes Dağı', B: 'Ağrı Dağı', C: 'Nemrut Dağı', D: 'Süphan Dağı', E: 'Uludağ' },
    answer: 'B',
    explanation: 'Mount Ararat, in eastern Turkey near the Armenian border, is Turkey\'s highest peak and is traditionally associated with Noah\'s Ark.',
  },
  {
    id: 'geo_46',
    text: 'Which country has the longest coastline in the world?',
    text_tr: 'Dünyanın en uzun kıyı şeridine sahip ülkesi hangisidir?',
    options: { A: 'Indonesia', B: 'Australia', C: 'Russia', D: 'Canada', E: 'Norway' },
    options_tr: { A: 'Endonezya', B: 'Avustralya', C: 'Rusya', D: 'Kanada', E: 'Norveç' },
    answer: 'D',
    explanation: 'Canada has the world\'s longest coastline at over 200,000 km, thanks in part to its many islands and fjords.',
  },
  {
    id: 'geo_47',
    text: 'Which volcanic Indonesian island is known for the catastrophic 1883 eruption that was heard thousands of kilometers away?',
    text_tr: '1883\'te binlerce kilometre uzaktan duyulan yıkıcı patlamasıyla bilinen volkanik Endonezya adası hangisidir?',
    options: { A: 'Bali', B: 'Java', C: 'Krakatoa', D: 'Sumatra', E: 'Sulawesi' },
    options_tr: { A: 'Bali', B: 'Java', C: 'Krakatoa', D: 'Sumatra', E: 'Sulawesi' },
    answer: 'C',
    explanation: 'The 1883 eruption of Krakatoa was one of the most violent volcanic events in recorded history, producing sounds heard as far as Australia.',
  },
  {
    id: 'geo_48',
    text: 'Which European microstate is entirely landlocked between Switzerland and Austria?',
    text_tr: 'Tamamen İsviçre ve Avusturya arasında sıkışmış, denize kıyısı olmayan Avrupa mikro devleti hangisidir?',
    options: { A: 'Andorra', B: 'Monaco', C: 'San Marino', D: 'Liechtenstein', E: 'Luxembourg' },
    options_tr: { A: 'Andorra', B: 'Monako', C: 'San Marino', D: 'Lihtenştayn', E: 'Lüksemburg' },
    answer: 'D',
    explanation: 'Liechtenstein, one of only two doubly landlocked countries in the world, lies between Switzerland and Austria.',
  },
  {
    id: 'geo_49',
    text: 'Which river flows through more countries than any other river in the world?',
    text_tr: 'Dünyadaki diğer nehirlerden daha fazla ülkeden geçen nehir hangisidir?',
    options: { A: 'Nile', B: 'Amazon', C: 'Danube', D: 'Mississippi', E: 'Yangtze' },
    options_tr: { A: 'Nil', B: 'Amazon', C: 'Tuna', D: 'Mississippi', E: 'Yangtze' },
    answer: 'C',
    explanation: 'The Danube flows through 10 countries, more than any other river in the world.',
  },
  {
    id: 'geo_50',
    text: 'What is the capital of Brazil (not its largest city)?',
    text_tr: 'Brezilya\'nın (en büyük şehri olmayan) başkenti neresidir?',
    options: { A: 'Rio de Janeiro', B: 'São Paulo', C: 'Brasília', D: 'Salvador', E: 'Belo Horizonte' },
    options_tr: { A: 'Rio de Janeiro', B: 'São Paulo', C: 'Brasília', D: 'Salvador', E: 'Belo Horizonte' },
    answer: 'C',
    explanation: 'Brasília, a purpose-built planned city, has been Brazil\'s capital since 1960, replacing Rio de Janeiro.',
  },
  {
    id: 'geo_51',
    text: 'Which mountain range forms a natural border between France and Spain?',
    text_tr: 'Fransa ve İspanya arasında doğal bir sınır oluşturan dağ silsilesi hangisidir?',
    options: { A: 'Alps', B: 'Pyrenees', C: 'Apennines', D: 'Massif Central', E: 'Cantabrian Mountains' },
    options_tr: { A: 'Alpler', B: 'Pireneler', C: 'Apenin Dağları', D: 'Massif Central', E: 'Kantabriya Dağları' },
    answer: 'B',
    explanation: 'The Pyrenees mountain range runs along the border between France and Spain, also touching Andorra.',
  },
  {
    id: 'geo_52',
    text: 'Which Southeast Asian country is made up of over 7,000 islands and includes the capital Manila?',
    text_tr: '7.000\'den fazla adadan oluşan ve başkent Manila\'yı içeren Güneydoğu Asya ülkesi hangisidir?',
    options: { A: 'Indonesia', B: 'Malaysia', C: 'Philippines', D: 'Vietnam', E: 'Thailand' },
    options_tr: { A: 'Endonezya', B: 'Malezya', C: 'Filipinler', D: 'Vietnam', E: 'Tayland' },
    answer: 'C',
    explanation: 'The Philippines is an archipelago of over 7,000 islands in Southeast Asia, with Manila as its capital.',
  },
  {
    id: 'geo_53',
    text: 'Which Turkish region borders both Syria and Iraq?',
    text_tr: 'Hem Suriye hem de Irak ile sınır komşusu olan Türkiye bölgesi hangisidir?',
    options: { A: 'The Black Sea Region', B: 'The Aegean Region', C: 'Southeastern Anatolia Region', D: 'Central Anatolia Region', E: 'The Mediterranean Region' },
    options_tr: { A: 'Karadeniz Bölgesi', B: 'Ege Bölgesi', C: 'Güneydoğu Anadolu Bölgesi', D: 'İç Anadolu Bölgesi', E: 'Akdeniz Bölgesi' },
    answer: 'C',
    explanation: 'The Southeastern Anatolia Region of Turkey borders both Syria to the south and Iraq to the southeast.',
  },
  {
    id: 'geo_54',
    text: 'Which country is the only one to border both the Atlantic and Indian Oceans on the African continent\'s southern tip?',
    text_tr: 'Afrika kıtasının güney ucunda hem Atlas hem de Hint Okyanusu\'na kıyısı olan tek ülke hangisidir?',
    options: { A: 'Namibia', B: 'South Africa', C: 'Mozambique', D: 'Angola', E: 'Madagascar' },
    options_tr: { A: 'Namibya', B: 'Güney Afrika', C: 'Mozambik', D: 'Angola', E: 'Madagaskar' },
    answer: 'B',
    explanation: 'South Africa\'s coastline meets both the Atlantic Ocean (west) and Indian Ocean (east) near Cape Agulhas.',
  },
  {
    id: 'geo_55',
    text: 'Which Central American country is famous for the canal connecting the Atlantic and Pacific Oceans?',
    text_tr: 'Atlas Okyanusu ile Pasifik Okyanusu\'nu birbirine bağlayan kanalıyla ünlü Orta Amerika ülkesi hangisidir?',
    options: { A: 'Costa Rica', B: 'Nicaragua', C: 'Panama', D: 'Honduras', E: 'Belize' },
    options_tr: { A: 'Kosta Rika', B: 'Nikaragua', C: 'Panama', D: 'Honduras', E: 'Belize' },
    answer: 'C',
    explanation: 'The Panama Canal, completed in 1914, connects the Atlantic and Pacific Oceans across the Isthmus of Panama.',
  },
  {
    id: 'geo_56',
    text: 'Which is the highest, coldest, and windiest continent, holding about 70% of the world\'s fresh water as ice?',
    text_tr: 'Dünyanın tatlı suyunun yaklaşık %70\'ini buz olarak barındıran, en yüksek, en soğuk ve en rüzgarlı kıta hangisidir?',
    options: { A: 'Asia', B: 'Antarctica', C: 'North America', D: 'Europe', E: 'South America' },
    options_tr: { A: 'Asya', B: 'Antarktika', C: 'Kuzey Amerika', D: 'Avrupa', E: 'Güney Amerika' },
    answer: 'B',
    explanation: 'Antarctica holds roughly 70% of the world\'s fresh water, locked in its massive ice sheets.',
  },
  {
    id: 'geo_57',
    text: 'Which Middle Eastern country contains the Dead Sea and shares it with Israel and the West Bank?',
    text_tr: 'Lut Gölü\'nü (Ölü Deniz) İsrail ve Batı Şeria ile paylaşan Orta Doğu ülkesi hangisidir?',
    options: { A: 'Lebanon', B: 'Syria', C: 'Jordan', D: 'Saudi Arabia', E: 'Egypt' },
    options_tr: { A: 'Lübnan', B: 'Suriye', C: 'Ürdün', D: 'Suudi Arabistan', E: 'Mısır' },
    answer: 'C',
    explanation: 'Jordan borders the eastern shore of the Dead Sea, which it shares with Israel and the West Bank.',
  },
  {
    id: 'geo_58',
    text: 'What is the capital of South Korea?',
    text_tr: 'Güney Kore\'nin başkenti neresidir?',
    options: { A: 'Busan', B: 'Incheon', C: 'Seoul', D: 'Daegu', E: 'Gwangju' },
    options_tr: { A: 'Busan', B: 'Incheon', C: 'Seul', D: 'Daegu', E: 'Gwangju' },
    answer: 'C',
    explanation: 'Seoul has been the capital of Korea for centuries and remains South Korea\'s capital and largest city.',
  },
  {
    id: 'geo_59',
    text: 'Which Turkish coastal region is known for its "Turquoise Coast," including resorts like Antalya and Bodrum?',
    text_tr: 'Antalya ve Bodrum gibi tatil beldelerini içeren "Turkuaz Kıyı" ile bilinen Türk kıyı bölgesi hangisidir?',
    options: { A: 'Black Sea Coast', B: 'Mediterranean and Aegean Coast', C: 'Marmara Coast', D: 'Eastern Anatolia', E: 'Southeastern Anatolia' },
    options_tr: { A: 'Karadeniz Kıyısı', B: 'Akdeniz ve Ege Kıyısı', C: 'Marmara Kıyısı', D: 'Doğu Anadolu', E: 'Güneydoğu Anadolu' },
    answer: 'B',
    explanation: 'Turkey\'s Turquoise Coast refers to its Mediterranean and Aegean shoreline, famed for clear turquoise waters.',
  },
  {
    id: 'geo_60',
    text: 'Which country is the only one located entirely within a single city, being both a city and a nation?',
    text_tr: 'Hem şehir hem de ulus olarak tamamen tek bir şehir içinde yer alan tek ülke hangisidir?',
    options: { A: 'Monaco', B: 'Singapore (a city-state but larger)', C: 'Vatican City', D: 'San Marino', E: 'Malta' },
    options_tr: { A: 'Monako', B: 'Singapur (bir şehir devleti ama daha büyük)', C: 'Vatikan', D: 'San Marino', E: 'Malta' },
    answer: 'C',
    explanation: 'Vatican City is a city-state entirely enclosed within Rome, Italy, making it the world\'s smallest sovereign nation.',
  },
  {
    id: 'geo_61',
    text: 'Which African lake is the second-largest freshwater lake in the world by surface area and the source of the White Nile?',
    text_tr: 'Yüzey alanı bakımından dünyanın en büyük ikinci tatlı su gölü olan ve Beyaz Nil\'in kaynağı olan Afrika gölü hangisidir?',
    options: { A: 'Lake Tanganyika', B: 'Lake Malawi', C: 'Lake Victoria', D: 'Lake Chad', E: 'Lake Albert' },
    options_tr: { A: 'Tanganika Gölü', B: 'Malavi Gölü', C: 'Victoria Gölü', D: 'Çad Gölü', E: 'Albert Gölü' },
    answer: 'C',
    explanation: 'Lake Victoria, shared by Uganda, Kenya, and Tanzania, is the source of the White Nile and Africa\'s largest lake.',
  },
  {
    id: 'geo_62',
    text: 'Which country has the highest number of active volcanoes in the world?',
    text_tr: 'Dünyada en fazla aktif yanardağa sahip ülke hangisidir?',
    options: { A: 'Japan', B: 'Indonesia', C: 'Philippines', D: 'Chile', E: 'Iceland' },
    options_tr: { A: 'Japonya', B: 'Endonezya', C: 'Filipinler', D: 'Şili', E: 'İzlanda' },
    answer: 'B',
    explanation: 'Indonesia, sitting on the Pacific Ring of Fire, has around 130 active volcanoes, the most of any country.',
  },
  {
    id: 'geo_63',
    text: 'Which is the highest waterfall in the world, located in Venezuela?',
    text_tr: 'Venezuela\'da bulunan ve dünyanın en yüksek şelalesi olan şelale hangisidir?',
    options: { A: 'Angel Falls', B: 'Tugela Falls', C: 'Victoria Falls', D: 'Niagara Falls', E: 'Kaieteur Falls' },
    options_tr: { A: 'Angel Şelalesi', B: 'Tugela Şelalesi', C: 'Victoria Şelalesi', D: 'Niagara Şelalesi', E: 'Kaieteur Şelalesi' },
    answer: 'A',
    explanation: 'Angel Falls in Venezuela has an uninterrupted drop of 979 meters, making it the world\'s tallest waterfall.',
  },
  {
    id: 'geo_64',
    text: 'Which US state is separated from the rest of the country and borders Canada but not any other US state?',
    text_tr: 'Ülkenin geri kalanından ayrı olan ve başka hiçbir ABD eyaletine değil yalnızca Kanada\'ya sınırı olan eyalet hangisidir?',
    options: { A: 'Hawaii', B: 'Alaska', C: 'Maine', D: 'Michigan', E: 'Washington' },
    options_tr: { A: 'Hawaii', B: 'Alaska', C: 'Maine', D: 'Michigan', E: 'Washington' },
    answer: 'B',
    explanation: 'Alaska is geographically separated from the contiguous United States, bordered only by Canada.',
  },
  {
    id: 'geo_65',
    text: 'Which Turkish city was the capital of the Ottoman Empire before Istanbul (Constantinople) was conquered in 1453?',
    text_tr: '1453\'te İstanbul (Konstantinopolis) fethedilmeden önce Osmanlı İmparatorluğu\'nun başkenti olan Türk şehri hangisidir?',
    options: { A: 'Bursa', B: 'Edirne', C: 'Konya', D: 'Söğüt', E: 'Ankara' },
    options_tr: { A: 'Bursa', B: 'Edirne', C: 'Konya', D: 'Söğüt', E: 'Ankara' },
    answer: 'B',
    explanation: 'Edirne (formerly Adrianople) served as the Ottoman capital from 1369 until Constantinople was conquered in 1453 (Bursa was the capital before Edirne).',
  },
  {
    id: 'geo_66',
    text: 'Which sea lies between Turkey and Greece, dotted with numerous islands?',
    text_tr: 'Türkiye ve Yunanistan arasında bulunan ve çok sayıda ada ile bezeli deniz hangisidir?',
    options: { A: 'Ionian Sea', B: 'Adriatic Sea', C: 'Aegean Sea', D: 'Tyrrhenian Sea', E: 'Sea of Marmara (too small)' },
    options_tr: { A: 'İyon Denizi', B: 'Adriyatik Denizi', C: 'Ege Denizi', D: 'Tiren Denizi', E: 'Marmara Denizi (çok küçük)' },
    answer: 'C',
    explanation: 'The Aegean Sea, between Turkey and Greece, contains thousands of islands and islets.',
  },
  {
    id: 'geo_67',
    text: 'Which country is the world\'s largest archipelago nation (island nation), spread across over 17,000 islands?',
    text_tr: '17.000\'den fazla adaya yayılan, dünyanın en büyük takımada ülkesi (ada ülkesi) hangisidir?',
    options: { A: 'Philippines', B: 'Japan', C: 'Indonesia', D: 'Papua New Guinea', E: 'Maldives' },
    options_tr: { A: 'Filipinler', B: 'Japonya', C: 'Endonezya', D: 'Papua Yeni Gine', E: 'Maldivler' },
    answer: 'C',
    explanation: 'Indonesia is composed of over 17,000 islands, making it the world\'s largest island country.',
  },
  {
    id: 'geo_68',
    text: 'Which line of latitude, at 0°, divides the Earth into Northern and Southern Hemispheres?',
    text_tr: 'Dünyayı Kuzey ve Güney Yarımküre olarak ikiye bölen, 0° olan enlem çizgisi hangisidir?',
    options: { A: 'Tropic of Cancer', B: 'Prime Meridian', C: 'Equator', D: 'Tropic of Capricorn', E: 'Arctic Circle' },
    options_tr: { A: 'Yengeç Dönencesi', B: 'Greenwich (Başlangıç) Meridyeni', C: 'Ekvator', D: 'Oğlak Dönencesi', E: 'Kuzey Kutup Dairesi' },
    answer: 'C',
    explanation: 'The Equator, an imaginary line at 0° latitude, divides the Earth into the Northern and Southern Hemispheres.',
  },
  {
    id: 'geo_69',
    text: 'Which line of longitude, at 0°, passes through Greenwich, England, and serves as the reference for time zones?',
    text_tr: 'İngiltere\'nin Greenwich kasabasından geçen ve saat dilimleri için referans olarak kullanılan 0° boylam çizgisi hangisidir?',
    options: { A: 'International Date Line', B: 'Prime Meridian', C: 'Equator', D: 'Tropic of Cancer', E: 'Antimeridian' },
    options_tr: { A: 'Tarih Değiştirme Çizgisi', B: 'Greenwich (Başlangıç) Meridyeni', C: 'Ekvator', D: 'Yengeç Dönencesi', E: 'Anti-meridyen' },
    answer: 'B',
    explanation: 'The Prime Meridian, at 0° longitude, passes through the Royal Observatory in Greenwich and is the basis for Coordinated Universal Time (UTC).',
  },
  {
    id: 'geo_70',
    text: 'Which Scandinavian country is famous for its extensive network of fjords along its western coast?',
    text_tr: 'Batı kıyısı boyunca uzanan geniş fiyort ağıyla ünlü İskandinav ülkesi hangisidir?',
    options: { A: 'Sweden', B: 'Denmark', C: 'Norway', D: 'Finland', E: 'Iceland' },
    options_tr: { A: 'İsveç', B: 'Danimarka', C: 'Norveç', D: 'Finlandiya', E: 'İzlanda' },
    answer: 'C',
    explanation: 'Norway\'s deeply indented coastline is famous for its fjords, narrow inlets carved by glaciers.',
  },
  {
    id: 'geo_71',
    text: 'Which country contains the world\'s largest tropical wetland, the Pantanal?',
    text_tr: 'Dünyanın en büyük tropikal sulak alanı olan Pantanal\'ı içeren ülke hangisidir?',
    options: { A: 'Bolivia', B: 'Paraguay', C: 'Brazil', D: 'Argentina', E: 'Uruguay' },
    options_tr: { A: 'Bolivya', B: 'Paraguay', C: 'Brezilya', D: 'Arjantin', E: 'Uruguay' },
    answer: 'C',
    explanation: 'The Pantanal, mostly located in Brazil (extending into Bolivia and Paraguay), is the world\'s largest tropical wetland area.',
  },
  {
    id: 'geo_72',
    text: 'Which country is divided by the Ural River and Ural Mountains into European and Asian parts?',
    text_tr: 'Ural Nehri ve Ural Dağları tarafından Avrupa ve Asya kısımlarına bölünen ülke hangisidir?',
    options: { A: 'Kazakhstan', B: 'Russia', C: 'Turkey', D: 'Georgia', E: 'Azerbaijan' },
    options_tr: { A: 'Kazakistan', B: 'Rusya', C: 'Türkiye', D: 'Gürcistan', E: 'Azerbaycan' },
    answer: 'B',
    explanation: 'Russia is transcontinental, with the Ural Mountains and Ural River conventionally dividing its European and Asian territories.',
  },
  {
    id: 'geo_73',
    text: 'Which country is home to the Great Barrier Reef, the world\'s largest coral reef system?',
    text_tr: 'Dünyanın en büyük mercan resif sistemi olan Büyük Set Resifi\'ne ev sahipliği yapan ülke hangisidir?',
    options: { A: 'Indonesia', B: 'Philippines', C: 'Australia', D: 'Fiji', E: 'Papua New Guinea' },
    options_tr: { A: 'Endonezya', B: 'Filipinler', C: 'Avustralya', D: 'Fiji', E: 'Papua Yeni Gine' },
    answer: 'C',
    explanation: 'The Great Barrier Reef, off the coast of Queensland, Australia, is the world\'s largest coral reef system.',
  },
  {
    id: 'geo_74',
    text: 'Which is the saltiest and one of the flattest places on Earth, located in Bolivia and famous for its mirror-like reflections?',
    text_tr: 'Bolivya\'da bulunan, aynasal yansımalarıyla ünlü, dünyanın en tuzlu ve en düz yerlerinden biri hangisidir?',
    options: { A: 'Atacama Desert', B: 'Salar de Uyuni', C: 'Death Valley', D: 'Bonneville Salt Flats', E: 'Danakil Depression' },
    options_tr: { A: 'Atacama Çölü', B: 'Salar de Uyuni', C: 'Ölüm Vadisi', D: 'Bonneville Tuz Düzlükleri', E: 'Danakil Çöküntüsü' },
    answer: 'B',
    explanation: 'Salar de Uyuni in Bolivia is the world\'s largest salt flat, famous for creating a mirror effect when covered by a thin layer of water.',
  },
  {
    id: 'geo_75',
    text: 'Which mountain, located in Tanzania, is the tallest freestanding mountain in the world (not part of a range)?',
    text_tr: 'Tanzanya\'da bulunan ve bir sıradağın parçası olmayan, dünyanın en yüksek bağımsız dağı hangisidir?',
    options: { A: 'Mount Kenya', B: 'Mount Kilimanjaro', C: 'Mount Meru', D: 'Ruwenzori Mountains', E: 'Mount Elgon' },
    options_tr: { A: 'Kenya Dağı', B: 'Kilimanjaro Dağı', C: 'Meru Dağı', D: 'Ruwenzori Dağları', E: 'Elgon Dağı' },
    answer: 'B',
    explanation: 'Mount Kilimanjaro is described as a freestanding mountain because it is not part of a mountain range.',
  },
  {
    id: 'geo_76',
    text: 'In which transcontinental country is the largest city, Istanbul, not the capital?',
    text_tr: 'Kıtalar arası hangi ülkede en büyük şehir olan İstanbul, başkent değildir?',
    options: { A: 'Russia', B: 'Turkey', C: 'Kazakhstan', D: 'Georgia', E: 'Egypt' },
    options_tr: { A: 'Rusya', B: 'Türkiye', C: 'Kazakistan', D: 'Gürcistan', E: 'Mısır' },
    answer: 'B',
    explanation: 'Turkey\'s largest city, Istanbul, is not its capital — that role belongs to Ankara.',
  },
  {
    id: 'geo_77',
    text: 'Which country contains the Serengeti National Park, famous for the annual wildebeest migration?',
    text_tr: 'Yıllık gnu göçüyle ünlü Serengeti Ulusal Parkı\'nı içeren ülke hangisidir?',
    options: { A: 'Kenya', B: 'Tanzania', C: 'Uganda', D: 'Zambia', E: 'Botswana' },
    options_tr: { A: 'Kenya', B: 'Tanzanya', C: 'Uganda', D: 'Zambiya', E: 'Botsvana' },
    answer: 'B',
    explanation: 'The Serengeti National Park in Tanzania is renowned for the Great Migration of wildebeest and zebra.',
  },
  {
    id: 'geo_78',
    text: 'What is the capital of Argentina?',
    text_tr: 'Arjantin\'in başkenti neresidir?',
    options: { A: 'Córdoba', B: 'Rosario', C: 'Buenos Aires', D: 'Mendoza', E: 'La Plata' },
    options_tr: { A: 'Córdoba', B: 'Rosario', C: 'Buenos Aires', D: 'Mendoza', E: 'La Plata' },
    answer: 'C',
    explanation: 'Buenos Aires is the capital and largest city of Argentina, located on the Río de la Plata estuary.',
  },
  {
    id: 'geo_79',
    text: 'Which country is separated from Italy by the Adriatic Sea and is known for its Dalmatian Coast?',
    text_tr: 'İtalya\'dan Adriyatik Denizi ile ayrılan ve Dalmaçya Kıyısı ile bilinen ülke hangisidir?',
    options: { A: 'Slovenia', B: 'Croatia', C: 'Montenegro', D: 'Albania', E: 'Bosnia and Herzegovina' },
    options_tr: { A: 'Slovenya', B: 'Hırvatistan', C: 'Karadağ', D: 'Arnavutluk', E: 'Bosna Hersek' },
    answer: 'B',
    explanation: 'Croatia\'s Dalmatian Coast along the Adriatic Sea is renowned for its islands and historic coastal cities.',
  },
  {
    id: 'geo_80',
    text: 'Which mountain range separates Spain from the rest of continental Europe and is home to the microstate Andorra?',
    text_tr: 'İspanya\'yı Avrupa anakarasının geri kalanından ayıran ve mikro devlet Andorra\'ya ev sahipliği yapan dağ silsilesi hangisidir?',
    options: { A: 'Alps', B: 'Pyrenees', C: 'Cantabrian Mountains', D: 'Sierra Nevada', E: 'Atlas Mountains' },
    options_tr: { A: 'Alpler', B: 'Pireneler', C: 'Kantabriya Dağları', D: 'Sierra Nevada', E: 'Atlas Dağları' },
    answer: 'B',
    explanation: 'Andorra is a tiny country nestled in the Pyrenees mountains between France and Spain.',
  },
  {
    id: 'geo_81',
    text: 'Which strait separates the Arabian Peninsula from Iran and is a critical route for global oil shipments?',
    text_tr: 'Arap Yarımadası\'nı İran\'dan ayıran ve küresel petrol sevkiyatları için kritik bir güzergah olan boğaz hangisidir?',
    options: { A: 'Strait of Malacca', B: 'Strait of Hormuz', C: 'Bab-el-Mandeb', D: 'Suez Canal (not a strait)', E: 'Strait of Gibraltar' },
    options_tr: { A: 'Malakka Boğazı', B: 'Hürmüz Boğazı', C: 'Bab-el-Mendeb', D: 'Süveyş Kanalı (boğaz değil)', E: 'Cebelitarık Boğazı' },
    answer: 'B',
    explanation: 'The Strait of Hormuz, between Iran and the Arabian Peninsula, is one of the world\'s most important oil chokepoints.',
  },
  {
    id: 'geo_82',
    text: 'Which country is the only one with a coastline on both the Mediterranean Sea and the Red Sea?',
    text_tr: 'Hem Akdeniz hem de Kızıldeniz\'e kıyısı olan tek ülke hangisidir?',
    options: { A: 'Israel', B: 'Egypt', C: 'Jordan', D: 'Saudi Arabia', E: 'Sudan' },
    options_tr: { A: 'İsrail', B: 'Mısır', C: 'Ürdün', D: 'Suudi Arabistan', E: 'Sudan' },
    answer: 'B',
    explanation: 'Egypt uniquely borders both the Mediterranean Sea (north) and the Red Sea (east), connected by the Suez Canal.',
  },
  {
    id: 'geo_83',
    text: 'Which Turkish province is home to the ancient ruins of Ephesus, a major tourist destination?',
    text_tr: 'Önemli bir turistik yer olan antik Efes kalıntılarına ev sahipliği yapan Türk ili hangisidir?',
    options: { A: 'Antalya', B: 'Izmir', C: 'Mugla', D: 'Aydın', E: 'Denizli' },
    options_tr: { A: 'Antalya', B: 'İzmir', C: 'Muğla', D: 'Aydın', E: 'Denizli' },
    answer: 'B',
    explanation: 'Ephesus is located in the İzmir province of Turkey, near the town of Selçuk.',
  },
  {
    id: 'geo_84',
    text: 'Which country has the highest average elevation in the world, often called the "Roof of the World"?',
    text_tr: 'Genellikle "Dünyanın Çatısı" olarak adlandırılan, dünyada en yüksek ortalama rakıma sahip ülke hangisidir?',
    options: { A: 'Nepal', B: 'Bhutan', C: 'Bolivia', D: 'Lesotho', E: 'Tajikistan' },
    options_tr: { A: 'Nepal', B: 'Bhutan', C: 'Bolivya', D: 'Lesoto', E: 'Tacikistan' },
    answer: 'D',
    explanation: 'Lesotho, entirely above 1,000 meters in elevation, has the highest average elevation of any country in the world.',
  },
  {
    id: 'geo_85',
    text: 'Which sea separates Italy from the Balkan Peninsula?',
    text_tr: 'İtalya\'yı Balkan Yarımadası\'ndan ayıran deniz hangisidir?',
    options: { A: 'Tyrrhenian Sea', B: 'Ionian Sea', C: 'Adriatic Sea', D: 'Ligurian Sea', E: 'Aegean Sea' },
    options_tr: { A: 'Tiren Denizi', B: 'İyon Denizi', C: 'Adriyatik Denizi', D: 'Ligurya Denizi', E: 'Ege Denizi' },
    answer: 'C',
    explanation: 'The Adriatic Sea separates the Italian Peninsula from the Balkan Peninsula.',
  },
  {
    id: 'geo_86',
    text: 'Which country contains most of the Sahara Desert\'s largest share by area?',
    text_tr: 'Sahra Çölü\'nün alan bakımından en büyük payını içeren ülke hangisidir?',
    options: { A: 'Libya', B: 'Egypt', C: 'Algeria', D: 'Mali', E: 'Chad' },
    options_tr: { A: 'Libya', B: 'Mısır', C: 'Cezayir', D: 'Mali', E: 'Çad' },
    answer: 'C',
    explanation: 'Algeria contains the largest portion of the Sahara Desert of any single country by land area.',
  },
  {
    id: 'geo_87',
    text: 'Which body of water lies between the Korean Peninsula and Japan?',
    text_tr: 'Kore Yarımadası ile Japonya arasında yer alan su kütlesi hangisidir?',
    options: { A: 'Yellow Sea', B: 'Sea of Japan (East Sea)', C: 'East China Sea', D: 'Bohai Sea', E: 'Philippine Sea' },
    options_tr: { A: 'Sarı Deniz', B: 'Japon Denizi (Doğu Denizi)', C: 'Doğu Çin Denizi', D: 'Bohai Denizi', E: 'Filipin Denizi' },
    answer: 'B',
    explanation: 'The Sea of Japan (called the East Sea in Korea) lies between the Korean Peninsula and the Japanese archipelago.',
  },
  {
    id: 'geo_88',
    text: 'Which country is tied with China for having land borders with the most other countries (14 each)?',
    text_tr: 'Çin ile birlikte en fazla ülkeyle (her biri 14) kara sınırına sahip olan ülke hangisidir?',
    options: { A: 'India', B: 'Russia', C: 'Germany', D: 'Kazakhstan', E: 'Brazil' },
    options_tr: { A: 'Hindistan', B: 'Rusya', C: 'Almanya', D: 'Kazakistan', E: 'Brezilya' },
    answer: 'B',
    explanation: 'Russia and China both border 14 other countries, more than any other nation in the world.',
  },
  {
    id: 'geo_89',
    text: 'Which Turkish lake, in central Anatolia, is one of the largest hypersaline lakes in the world and a major source of salt?',
    text_tr: 'İç Anadolu\'da bulunan ve dünyanın en büyük hipersalin göllerinden biri olan, önemli bir tuz kaynağı olan Türk gölü hangisidir?',
    options: { A: 'Lake Van', B: 'Lake Tuz (Salt Lake)', C: 'Lake Beyşehir', D: 'Lake Eğirdir', E: 'Lake Burdur' },
    options_tr: { A: 'Van Gölü', B: 'Tuz Gölü', C: 'Beyşehir Gölü', D: 'Eğirdir Gölü', E: 'Burdur Gölü' },
    answer: 'B',
    explanation: 'Lake Tuz (Salt Lake), in central Turkey, is one of the largest hypersaline lakes in the world.',
  },
  {
    id: 'geo_90',
    text: 'Which country, an island nation off the southeast coast of Africa, is known for its unique biodiversity, including lemurs?',
    text_tr: 'Afrika\'nın güneydoğu kıyısı açıklarında bulunan, lemurlar dahil eşsiz biyoçeşitliliğiyle bilinen ada ülkesi hangisidir?',
    options: { A: 'Seychelles', B: 'Comoros', C: 'Madagascar', D: 'Mauritius', E: 'Réunion' },
    options_tr: { A: 'Seyşeller', B: 'Komorlar', C: 'Madagaskar', D: 'Mauritius', E: 'Réunion' },
    answer: 'C',
    explanation: 'Madagascar, isolated for millions of years, is home to lemurs and many species found nowhere else on Earth.',
  },
  {
    id: 'geo_91',
    text: 'Which river forms much of the border between the United States and Mexico?',
    text_tr: 'Amerika Birleşik Devletleri ile Meksika arasındaki sınırın büyük bölümünü oluşturan nehir hangisidir?',
    options: { A: 'Colorado River', B: 'Rio Grande', C: 'Pecos River', D: 'Gila River', E: 'Sacramento River' },
    options_tr: { A: 'Colorado Nehri', B: 'Rio Grande', C: 'Pecos Nehri', D: 'Gila Nehri', E: 'Sacramento Nehri' },
    answer: 'B',
    explanation: 'The Rio Grande (known as Río Bravo in Mexico) forms a large portion of the US-Mexico border.',
  },
  {
    id: 'geo_92',
    text: 'Which Turkish city, on the Aegean coast, is Turkey\'s third-largest city and a major port?',
    text_tr: 'Ege kıyısında yer alan, Türkiye\'nin üçüncü büyük şehri ve önemli bir liman kenti olan şehir hangisidir?',
    options: { A: 'Antalya', B: 'Bursa', C: 'Izmir', D: 'Adana', E: 'Gaziantep' },
    options_tr: { A: 'Antalya', B: 'Bursa', C: 'İzmir', D: 'Adana', E: 'Gaziantep' },
    answer: 'C',
    explanation: 'İzmir, on Turkey\'s Aegean coast, is the country\'s third-largest city and a major Mediterranean port.',
  },
  {
    id: 'geo_93',
    text: 'Which is the deepest point in the world\'s oceans, located in the Pacific Ocean?',
    text_tr: 'Pasifik Okyanusu\'nda bulunan, dünya okyanuslarının en derin noktası hangisidir?',
    options: { A: 'Puerto Rico Trench', B: 'Mariana Trench (Challenger Deep)', C: 'Java Trench', D: 'Tonga Trench', E: 'Kermadec Trench' },
    options_tr: { A: 'Porto Riko Çukuru', B: 'Mariana Çukuru (Challenger Deep)', C: 'Java Çukuru', D: 'Tonga Çukuru', E: 'Kermadec Çukuru' },
    answer: 'B',
    explanation: 'The Challenger Deep in the Mariana Trench, at nearly 11,000 meters, is the deepest known point in Earth\'s oceans.',
  },
  {
    id: 'geo_94',
    text: 'Which country is home to the ancient city of Petra, carved into rose-colored rock?',
    text_tr: 'Gül rengi kayaya oyulmuş antik Petra kentine ev sahipliği yapan ülke hangisidir?',
    options: { A: 'Syria', B: 'Jordan', C: 'Lebanon', D: 'Iraq', E: 'Israel' },
    options_tr: { A: 'Suriye', B: 'Ürdün', C: 'Lübnan', D: 'Irak', E: 'İsrail' },
    answer: 'B',
    explanation: 'Petra, a UNESCO World Heritage Site, is located in southern Jordan and was carved by the Nabataeans over 2,000 years ago.',
  },
  {
    id: 'geo_95',
    text: 'Which country is the only nation to span all four hemispheres (North, South, East, and West)?',
    text_tr: 'Dört yarımkürenin (Kuzey, Güney, Doğu ve Batı) tümüne yayılan tek ülke hangisidir?',
    options: { A: 'Brazil', B: 'Indonesia', C: 'Kiribati', D: 'Ecuador', E: 'Democratic Republic of the Congo' },
    options_tr: { A: 'Brezilya', B: 'Endonezya', C: 'Kiribati', D: 'Ekvador', E: 'Kongo Demokratik Cumhuriyeti' },
    answer: 'C',
    explanation: 'Kiribati, a Pacific island nation, is the only country whose territory extends into all four hemispheres.',
  },
  {
    id: 'geo_96',
    text: 'Which Turkish region, home to Mount Ağrı (Ararat), borders Iran, Armenia, Azerbaijan (Nakhchivan), and Georgia?',
    text_tr: 'Ağrı Dağı\'na ev sahipliği yapan ve İran, Ermenistan, Azerbaycan (Nahçıvan) ve Gürcistan ile sınırı olan Türkiye bölgesi hangisidir?',
    options: { A: 'Black Sea Region', B: 'Central Anatolia Region', C: 'Eastern Anatolia Region', D: 'Southeastern Anatolia Region', E: 'Marmara Region' },
    options_tr: { A: 'Karadeniz Bölgesi', B: 'İç Anadolu Bölgesi', C: 'Doğu Anadolu Bölgesi', D: 'Güneydoğu Anadolu Bölgesi', E: 'Marmara Bölgesi' },
    answer: 'C',
    explanation: 'Turkey\'s Eastern Anatolia Region borders Iran, Armenia, Azerbaijan\'s Nakhchivan exclave, and Georgia, and contains Mount Ararat.',
  },
  {
    id: 'geo_97',
    text: 'Which is the only continent through which all lines of longitude pass?',
    text_tr: 'Tüm boylam çizgilerinin içinden geçtiği tek kıta hangisidir?',
    options: { A: 'Africa', B: 'Asia', C: 'Antarctica', D: 'Australia', E: 'Europe' },
    options_tr: { A: 'Afrika', B: 'Asya', C: 'Antarktika', D: 'Avustralya', E: 'Avrupa' },
    answer: 'C',
    explanation: 'Because Antarctica surrounds the South Pole, every line of longitude passes through it.',
  },
  {
    id: 'geo_98',
    text: 'Which sea, bordered by Egypt, Sudan, Eritrea, Djibouti, Yemen, and Saudi Arabia, connects to the Indian Ocean via the Bab-el-Mandeb strait?',
    text_tr: 'Mısır, Sudan, Eritre, Cibuti, Yemen ve Suudi Arabistan ile sınırı olan ve Bab-el-Mendeb boğazı aracılığıyla Hint Okyanusu\'na bağlanan deniz hangisidir?',
    options: { A: 'Arabian Sea', B: 'Red Sea', C: 'Gulf of Aden', D: 'Persian Gulf', E: 'Mediterranean Sea' },
    options_tr: { A: 'Arap Denizi', B: 'Kızıldeniz', C: 'Aden Körfezi', D: 'Basra Körfezi', E: 'Akdeniz' },
    answer: 'B',
    explanation: 'The Red Sea separates Africa from the Arabian Peninsula and connects to the Indian Ocean through the Gulf of Aden via Bab-el-Mandeb.',
  },
  {
    id: 'geo_99',
    text: 'Which is the largest desert in the world overall (including cold deserts), covering Antarctica?',
    text_tr: 'Soğuk çölleri de içeren, Antarktika\'yı kapsayan, dünyanın genel olarak en büyük çölü hangisidir?',
    options: { A: 'Sahara Desert', B: 'Arctic Desert', C: 'Antarctic Desert', D: 'Gobi Desert', E: 'Arabian Desert' },
    options_tr: { A: 'Sahra Çölü', B: 'Arktik Çölü', C: 'Antarktika Çölü', D: 'Gobi Çölü', E: 'Arap Çölü' },
    answer: 'C',
    explanation: 'By the broad definition of "desert" as a region receiving very little precipitation, the Antarctic Desert (all of Antarctica) is the largest in the world at about 14 million km².',
  },
  {
    id: 'geo_100',
    text: 'Which Turkish city, home to Mount Uludağ, is famous for its historic role as an early Ottoman capital and for its thermal springs?',
    text_tr: 'Uludağ\'a ev sahipliği yapan ve erken dönem Osmanlı başkenti olma rolü ile kaplıcalarıyla ünlü Türk şehri hangisidir?',
    options: { A: 'Bursa', B: 'Eskişehir', C: 'Kütahya', D: 'Balıkesir', E: 'Sakarya' },
    options_tr: { A: 'Bursa', B: 'Eskişehir', C: 'Kütahya', D: 'Balıkesir', E: 'Sakarya' },
    answer: 'A',
    explanation: 'Bursa was the second capital of the Ottoman Empire (1335–1363) and is famous for Mount Uludağ and its thermal baths.',
  },
];

module.exports = { geography };
