'use strict';

const history = [
  {
    id: 'his_01',
    text: 'The Battle of Thermopylae (480 BC) was a stand by a Greek force led primarily by which city-state?',
    text_tr: 'Thermopylae Savaşı (MÖ 480) ağırlıklı olarak hangi şehir devletinin liderliğindeki Yunan kuvvetleri tarafından verildi?',
    options: { A: 'Athens', B: 'Corinth', C: 'Thebes', D: 'Sparta', E: 'Argos' },
    options_tr: { A: 'Atina', B: 'Korint', C: 'Teba', D: 'Sparta', E: 'Argos' },
    answer: 'D',
    explanation: 'King Leonidas of Sparta led 300 Spartans (plus allies) against the Persian army at Thermopylae.',
  },
  {
    id: 'his_02',
    text: 'Which treaty formally ended World War I between the Allies and Germany?',
    text_tr: 'Müttefikler ile Almanya arasında Birinci Dünya Savaşı\'nı resmen sona erdiren antlaşma hangisidir?',
    options: { A: 'Treaty of Brest-Litovsk', B: 'Treaty of Saint-Germain', C: 'Treaty of Versailles', D: 'Treaty of Trianon', E: 'Treaty of Lausanne' },
    options_tr: { A: 'Brest-Litovsk Antlaşması', B: 'Saint-Germain Antlaşması', C: 'Versay Antlaşması', D: 'Trianon Antlaşması', E: 'Lozan Antlaşması' },
    answer: 'C',
    explanation: 'The Treaty of Versailles (1919) ended the war with Germany; the other treaties dealt with the other Central Powers.',
  },
  {
    id: 'his_03',
    text: 'Which civilization built the mountaintop city of Machu Picchu?',
    text_tr: 'Dağ tepesindeki Machu Picchu şehrini hangi medeniyet inşa etmiştir?',
    options: { A: 'Aztec', B: 'Olmec', C: 'Toltec', D: 'Maya', E: 'Inca' },
    options_tr: { A: 'Aztekler', B: 'Olmekler', C: 'Toltekler', D: 'Mayalar', E: 'İnkalar' },
    answer: 'E',
    explanation: 'Machu Picchu was built by the Inca Empire in the 15th century in present-day Peru.',
  },
  {
    id: 'his_04',
    text: 'Which of the following structures was built BEFORE the Ottoman Conquest of Istanbul (1453)?',
    text_tr: 'Aşağıdaki yapılardan hangisi İstanbul\'un Osmanlı fethinden (1453) ÖNCE inşa edilmiştir?',
    options: { A: 'Rumeli Fortress', B: 'Anatolian Fortress', C: 'Tiled Kiosk (Çinili Köşk)', D: 'Fatih Mosque', E: 'Süleymaniye Mosque' },
    options_tr: { A: 'Rumeli Hisarı', B: 'Anadolu Hisarı', C: 'Çinili Köşk', D: 'Fatih Camii', E: 'Süleymaniye Camii' },
    answer: 'B',
    explanation: 'Anadolu Hisarı was built by Bayezid I around 1394; the other four were all built after 1453.',
  },
  {
    id: 'his_05',
    text: 'Who was the last active pharaoh of Ancient Egypt before Roman annexation?',
    text_tr: 'Roma\'nın ilhakından önce Antik Mısır\'ın son aktif firavunu kimdi?',
    options: { A: 'Nefertiti', B: 'Hatshepsut', C: 'Cleopatra VII', D: 'Ramesses III', E: 'Ptolemy XIII' },
    options_tr: { A: 'Nefertiti', B: 'Hatşepsut', C: 'Kleopatra VII', D: 'III. Ramses', E: 'XIII. Ptolemaios' },
    answer: 'C',
    explanation: 'Cleopatra VII (69–30 BC) was the last ruler of the Ptolemaic Kingdom before Egypt became a Roman province.',
  },
  {
    id: 'his_06',
    text: 'Which ancient code of law, inscribed on a stele, is famous for the principle "an eye for an eye"?',
    text_tr: 'Bir dikili taşa (stel) kazınmış olan ve "göze göz" ilkesiyle ünlü antik hukuk kanunu hangisidir?',
    options: { A: 'The Twelve Tables', B: 'Code of Hammurabi', C: 'Code of Ur-Nammu', D: 'Draconian Constitution', E: 'Code of Justinian' },
    options_tr: { A: 'On İki Levha Kanunu', B: 'Hammurabi Kanunları', C: 'Ur-Nammu Kanunları', D: 'Drakon Anayasası', E: 'Iustinianus Kanunnamesi' },
    answer: 'B',
    explanation: 'The Code of Hammurabi (c. 1754 BC) from Babylon is the most complete surviving ancient legal code and famously applies lex talionis. Ur-Nammu\'s code is older but favours fines.',
  },
  {
    id: 'his_07',
    text: 'The Rosetta Stone was crucial to deciphering Egyptian hieroglyphs because it carried the same text in three scripts. Which language did it also contain?',
    text_tr: 'Rosetta Taşı, Mısır hiyerogliflerinin çözülmesinde kilit rol oynadı çünkü aynı metni üç yazıyla taşıyordu. İçerdiği diğer dil hangisiydi?',
    options: { A: 'Latin', B: 'Aramaic', C: 'Ancient Greek', D: 'Phoenician', E: 'Coptic' },
    options_tr: { A: 'Latince', B: 'Aramice', C: 'Antik Yunanca', D: 'Fenikece', E: 'Kıptice' },
    answer: 'C',
    explanation: 'The stone bears hieroglyphic, Demotic and Ancient Greek. Scholars who could read Greek used it as the key.',
  },
  {
    id: 'his_08',
    text: 'Which Roman general crossed the Rubicon in 49 BC, an act that triggered civil war?',
    text_tr: 'MÖ 49\'da Rubicon Nehri\'ni geçerek iç savaşı başlatan Romalı komutan kimdir?',
    options: { A: 'Pompey', B: 'Sulla', C: 'Julius Caesar', D: 'Mark Antony', E: 'Crassus' },
    options_tr: { A: 'Pompeius', B: 'Sulla', C: 'Julius Caesar', D: 'Marcus Antonius', E: 'Crassus' },
    answer: 'C',
    explanation: 'Bringing his army across the Rubicon into Italy was an act of war against the Senate; "the die is cast" is attributed to Caesar at that moment.',
  },
  {
    id: 'his_09',
    text: 'In which year did the Western Roman Empire traditionally fall, when Romulus Augustulus was deposed?',
    text_tr: 'Romulus Augustulus\'un tahttan indirilmesiyle Batı Roma İmparatorluğu geleneksel olarak hangi yıl yıkılmıştır?',
    options: { A: '410 AD', B: '455 AD', C: '476 AD', D: '493 AD', E: '527 AD' },
    options_tr: { A: 'MS 410', B: 'MS 455', C: 'MS 476', D: 'MS 493', E: 'MS 527' },
    answer: 'C',
    explanation: 'Odoacer deposed Romulus Augustulus in 476 AD. 410 was the Visigothic sack of Rome, a different event.',
  },
  {
    id: 'his_10',
    text: 'Which empire did Emperor Justinian I rule while sponsoring the construction of the Hagia Sophia?',
    text_tr: 'İmparator I. Iustinianus, Ayasofya\'nın inşasına sponsor olurken hangi imparatorluğu yönetiyordu?',
    options: { A: 'The Holy Roman Empire', B: 'The Byzantine (Eastern Roman) Empire', C: 'The Sassanid Empire', D: 'The Frankish Kingdom', E: 'The Umayyad Caliphate' },
    options_tr: { A: 'Kutsal Roma İmparatorluğu', B: 'Bizans (Doğu Roma) İmparatorluğu', C: 'Sasani İmparatorluğu', D: 'Frank Krallığı', E: 'Emevi Halifeliği' },
    answer: 'B',
    explanation: 'Justinian ruled the Byzantine Empire from Constantinople (527–565) and rebuilt the Hagia Sophia after the Nika riots.',
  },
  {
    id: 'his_11',
    text: 'The Islamic prophet Muhammad\'s migration from Mecca to Medina, which marks year one of the Islamic calendar, is known as what?',
    text_tr: 'İslam peygamberi Muhammed\'in Mekke\'den Medine\'ye göçü — ki İslami takvimin birinci yılını işaret eder — hangi adla bilinir?',
    options: { A: 'The Isra', B: 'The Hijra', C: 'The Fatḥ', D: 'The Hajj', E: 'The Bay\'ah' },
    options_tr: { A: 'İsra', B: 'Hicret', C: 'Feth', D: 'Hac', E: 'Biat' },
    answer: 'B',
    explanation: 'The Hijra took place in 622 AD and its year became the start of the Islamic (Hijri) calendar.',
  },
  {
    id: 'his_12',
    text: 'At the Battle of Manzikert in 1071, the Seljuk Turks defeated the army of which empire, opening Anatolia to Turkish settlement?',
    text_tr: '1071 Malazgirt Savaşı\'nda Selçuklu Türkleri hangi imparatorluğun ordusunu yenerek Anadolu\'yu Türk yerleşimine açtı?',
    options: { A: 'The Abbasid Caliphate', B: 'The Byzantine Empire', C: 'The Kingdom of Georgia', D: 'The Fatimid Caliphate', E: 'The Empire of Trebizond' },
    options_tr: { A: 'Abbasi Halifeliği', B: 'Bizans İmparatorluğu', C: 'Gürcistan Krallığı', D: 'Fatımi Halifeliği', E: 'Trabzon İmparatorluğu' },
    answer: 'B',
    explanation: 'Alp Arslan captured the Byzantine emperor Romanos IV Diogenes at Manzikert, and Turkish beyliks spread across Anatolia in the following decades.',
  },
  {
    id: 'his_13',
    text: 'Which document, sealed by King John of England in 1215, is celebrated as an early limit on royal power?',
    text_tr: 'İngiltere Kralı John tarafından 1215\'te mühürlenen ve kraliyet gücüne erken bir sınır olarak kutlanan belge hangisidir?',
    options: { A: 'The Bill of Rights', B: 'The Petition of Right', C: 'Magna Carta', D: 'The Act of Settlement', E: 'The Provisions of Oxford' },
    options_tr: { A: 'Haklar Bildirisi (Bill of Rights)', B: 'Petition of Right', C: 'Magna Carta', D: 'Veraset Yasası', E: 'Oxford Hükümleri' },
    answer: 'C',
    explanation: 'Magna Carta ("Great Charter") was forced on King John by rebel barons at Runnymede in 1215.',
  },
  {
    id: 'his_14',
    text: 'The Black Death of the 14th century is now generally attributed to which pathogen?',
    text_tr: '14. yüzyıldaki Kara Ölüm, günümüzde genellikle hangi patojene atfedilir?',
    options: { A: 'Variola virus (smallpox)', B: 'Vibrio cholerae', C: 'Yersinia pestis', D: 'Rickettsia prowazekii (typhus)', E: 'Influenza virus' },
    options_tr: { A: 'Variola virüsü (çiçek)', B: 'Vibrio cholerae (kolera)', C: 'Yersinia pestis', D: 'Rickettsia prowazekii (tifüs)', E: 'İnfluenza virüsü' },
    answer: 'C',
    explanation: 'The bacterium Yersinia pestis, spread largely by fleas on rodents, caused the plague that killed perhaps a third of Europe.',
  },
  {
    id: 'his_15',
    text: 'Which Mongol leader united the tribes of the steppe and founded an empire that became the largest contiguous land empire in history?',
    text_tr: 'Bozkır kabilelerini birleştirip tarihin en büyük bitişik kara imparatorluğunu kuran Moğol lideri kimdir?',
    options: { A: 'Kublai Khan', B: 'Ögedei Khan', C: 'Möngke Khan', D: 'Genghis Khan', E: 'Batu Khan' },
    options_tr: { A: 'Kubilay Han', B: 'Ögeday Han', C: 'Möngke Han', D: 'Cengiz Han', E: 'Batu Han' },
    answer: 'D',
    explanation: 'Genghis (Chinggis) Khan united the Mongol tribes in 1206; his descendants expanded the empire to its greatest extent.',
  },
  {
    id: 'his_16',
    text: 'The Hundred Years\' War was fought primarily between which two kingdoms?',
    text_tr: 'Yüzyıl Savaşları esas olarak hangi iki krallık arasında yapılmıştır?',
    options: { A: 'England and Scotland', B: 'France and the Holy Roman Empire', C: 'England and France', D: 'France and Castile', E: 'England and Burgundy' },
    options_tr: { A: 'İngiltere ve İskoçya', B: 'Fransa ve Kutsal Roma İmparatorluğu', C: 'İngiltere ve Fransa', D: 'Fransa ve Kastilya', E: 'İngiltere ve Burgonya' },
    answer: 'C',
    explanation: 'England and France fought intermittently from 1337 to 1453 over claims to the French throne.',
  },
  {
    id: 'his_17',
    text: 'Which invention by Johannes Gutenberg around 1440 transformed the spread of information in Europe?',
    text_tr: 'Johannes Gutenberg\'in 1440 civarındaki hangi icadı, Avrupa\'da bilginin yayılmasını dönüştürdü?',
    options: { A: 'Movable-type printing press', B: 'The mechanical clock', C: 'The spinning jenny', D: 'Paper', E: 'The telescope' },
    options_tr: { A: 'Hareketli harfli matbaa', B: 'Mekanik saat', C: 'İplik eğirme makinesi (spinning jenny)', D: 'Kâğıt', E: 'Teleskop' },
    answer: 'A',
    explanation: 'Gutenberg\'s press with reusable metal type made books far cheaper; paper and block printing already existed elsewhere.',
  },
  {
    id: 'his_18',
    text: 'In 1453, Constantinople fell to the Ottomans under which sultan?',
    text_tr: '1453\'te İstanbul, hangi sultan yönetimindeki Osmanlılara düştü?',
    options: { A: 'Bayezid I', B: 'Murad II', C: 'Mehmed II', D: 'Selim I', E: 'Süleyman I' },
    options_tr: { A: 'I. Bayezid', B: 'II. Murad', C: 'II. Mehmed', D: 'I. Selim', E: 'I. Süleyman' },
    answer: 'C',
    explanation: 'Mehmed II, thereafter called "Fatih" (the Conqueror), took the city on 29 May 1453, ending the Byzantine Empire.',
  },
  {
    id: 'his_19',
    text: 'Which explorer, sailing for Spain, reached the Caribbean in 1492 while seeking a westward route to Asia?',
    text_tr: 'İspanya adına yelken açan hangi kâşif, Asya\'ya batıdan bir yol ararken 1492\'de Karayipler\'e ulaştı?',
    options: { A: 'Vasco da Gama', B: 'Ferdinand Magellan', C: 'Christopher Columbus', D: 'Amerigo Vespucci', E: 'John Cabot' },
    options_tr: { A: 'Vasco da Gama', B: 'Ferdinand Macellan', C: 'Kristof Kolomb', D: 'Amerigo Vespucci', E: 'John Cabot' },
    answer: 'C',
    explanation: 'Columbus made landfall in the Bahamas in October 1492 under the Catholic Monarchs of Spain.',
  },
  {
    id: 'his_20',
    text: 'The 95 Theses, which helped ignite the Protestant Reformation in 1517, were written by whom?',
    text_tr: '1517\'de Protestan Reformu\'nu ateşlemeye yardımcı olan 95 Tez kim tarafından yazılmıştır?',
    options: { A: 'John Calvin', B: 'Martin Luther', C: 'Huldrych Zwingli', D: 'John Wycliffe', E: 'Jan Hus' },
    options_tr: { A: 'Jean Calvin', B: 'Martin Luther', C: 'Huldrych Zwingli', D: 'John Wycliffe', E: 'Jan Hus' },
    answer: 'B',
    explanation: 'Luther, an Augustinian monk, challenged the sale of indulgences; the theses spread rapidly thanks to the printing press.',
  },
  {
    id: 'his_21',
    text: 'Which empire did Hernán Cortés bring down in 1521 with the help of indigenous allies and disease?',
    text_tr: 'Hernán Cortés, 1521\'de yerli müttefiklerin ve hastalığın yardımıyla hangi imparatorluğu yıkmıştır?',
    options: { A: 'The Inca Empire', B: 'The Maya city-states', C: 'The Aztec Empire', D: 'The Zapotec state', E: 'The Purépecha Empire' },
    options_tr: { A: 'İnka İmparatorluğu', B: 'Maya şehir devletleri', C: 'Aztek İmparatorluğu', D: 'Zapotek devleti', E: 'Purépecha İmparatorluğu' },
    answer: 'C',
    explanation: 'Cortés captured the Aztec capital Tenochtitlan in 1521. Pizarro toppled the Inca a decade later.',
  },
  {
    id: 'his_22',
    text: 'The reign of Ottoman Sultan Süleyman is called "the Magnificent" in the West but by which title in Ottoman/Turkish tradition?',
    text_tr: 'Osmanlı Sultanı Süleyman\'ın saltanatı Batı\'da "Muhteşem" olarak anılır; Osmanlı/Türk geleneğinde hangi unvanla anılır?',
    options: { A: 'Yavuz (the Stern)', B: 'Fatih (the Conqueror)', C: 'Kanuni (the Lawgiver)', D: 'Gazi (the Warrior)', E: 'Avcı (the Hunter)' },
    options_tr: { A: 'Yavuz', B: 'Fatih', C: 'Kanuni', D: 'Gazi', E: 'Avcı' },
    answer: 'C',
    explanation: '"Kanuni" refers to his codification and reform of Ottoman law during his reign (1520–1566).',
  },
  {
    id: 'his_23',
    text: 'Ferdinand Magellan\'s expedition (1519–1522) is credited with the first circumnavigation of the globe, though he died en route in which islands?',
    text_tr: 'Ferdinand Macellan\'ın seferi (1519–1522) dünyayı ilk dolaşma seferi sayılır; kendisi yolda hangi adalarda öldü?',
    options: { A: 'The Canary Islands', B: 'The Cape Verde Islands', C: 'The Philippines', D: 'The Moluccas', E: 'The Azores' },
    options_tr: { A: 'Kanarya Adaları', B: 'Yeşil Burun Adaları', C: 'Filipinler', D: 'Moluku Adaları', E: 'Azor Adaları' },
    answer: 'C',
    explanation: 'Magellan was killed at Mactan in the Philippines in 1521; Juan Sebastián Elcano completed the voyage.',
  },
  {
    id: 'his_24',
    text: 'The Thirty Years\' War (1618–1648) was ended by which set of treaties?',
    text_tr: 'Otuz Yıl Savaşları (1618–1648) hangi antlaşmalar dizisiyle sona erdi?',
    options: { A: 'The Peace of Augsburg', B: 'The Peace of Westphalia', C: 'The Treaty of Utrecht', D: 'The Peace of the Pyrenees', E: 'The Congress of Vienna' },
    options_tr: { A: 'Augsburg Barışı', B: 'Vestfalya Barışı', C: 'Utrecht Antlaşması', D: 'Pireneler Barışı', E: 'Viyana Kongresi' },
    answer: 'B',
    explanation: 'The 1648 Peace of Westphalia is often taken as the origin of the modern sovereign-state system.',
  },
  {
    id: 'his_25',
    text: 'Which English king was executed in 1649 after losing the English Civil War?',
    text_tr: 'İngiliz İç Savaşı\'nı kaybettikten sonra 1649\'da idam edilen İngiliz kralı kimdir?',
    options: { A: 'James I', B: 'Charles I', C: 'Charles II', D: 'James II', E: 'William III' },
    options_tr: { A: 'I. James', B: 'I. Charles', C: 'II. Charles', D: 'II. James', E: 'III. William' },
    answer: 'B',
    explanation: 'Charles I was beheaded in Whitehall; England was then a republic (Commonwealth) under Oliver Cromwell until 1660.',
  },
  {
    id: 'his_26',
    text: 'The 1683 Battle of Vienna, a turning point in Ottoman–Habsburg wars, featured a famous cavalry charge led by which king?',
    text_tr: 'Osmanlı–Habsburg savaşlarında bir dönüm noktası olan 1683 Viyana Kuşatması, hangi kralın önderliğindeki ünlü süvari hücumuna sahne oldu?',
    options: { A: 'Leopold I of Austria', B: 'John III Sobieski of Poland', C: 'Louis XIV of France', D: 'Charles V of Lorraine', E: 'Frederick William of Brandenburg' },
    options_tr: { A: 'Avusturyalı I. Leopold', B: 'Polonyalı III. Jan Sobieski', C: 'Fransa Kralı XIV. Louis', D: 'Lorraine\'li Charles V', E: 'Brandenburg\'lu Friedrich Wilhelm' },
    answer: 'B',
    explanation: 'The Polish king John III Sobieski led the winged hussars in the relief of Vienna against the army of Kara Mustafa Pasha.',
  },
  {
    id: 'his_27',
    text: 'Which Russian ruler founded Saint Petersburg in 1703 and pushed sweeping Westernizing reforms?',
    text_tr: '1703\'te Saint Petersburg\'u kuran ve kapsamlı Batılılaşma reformlarını dayatan Rus hükümdarı kimdir?',
    options: { A: 'Ivan the Terrible', B: 'Catherine the Great', C: 'Peter the Great', D: 'Alexander I', E: 'Nicholas I' },
    options_tr: { A: 'Korkunç İvan', B: 'Büyük Katerina', C: 'Büyük Petro', D: 'I. Aleksandr', E: 'I. Nikolay' },
    answer: 'C',
    explanation: 'Peter I built the new capital on the Baltic as a "window to the West" and reorganized the army, navy and administration.',
  },
  {
    id: 'his_28',
    text: 'The Declaration of Independence of the United States was adopted in which year?',
    text_tr: 'Amerika Birleşik Devletleri Bağımsızlık Bildirgesi hangi yıl kabul edilmiştir?',
    options: { A: '1774', B: '1775', C: '1776', D: '1781', E: '1783' },
    options_tr: { A: '1774', B: '1775', C: '1776', D: '1781', E: '1783' },
    answer: 'C',
    explanation: 'The Continental Congress adopted the Declaration on 4 July 1776. 1783 was the Treaty of Paris that recognized independence.',
  },
  {
    id: 'his_29',
    text: 'The storming of the Bastille on 14 July 1789 is a symbolic start of which revolution?',
    text_tr: '14 Temmuz 1789\'da Bastille\'in basılması, hangi devrimin sembolik başlangıcıdır?',
    options: { A: 'The American Revolution', B: 'The French Revolution', C: 'The Haitian Revolution', D: 'The July Revolution', E: 'The Revolutions of 1848' },
    options_tr: { A: 'Amerikan Devrimi', B: 'Fransız Devrimi', C: 'Haiti Devrimi', D: 'Temmuz Devrimi', E: '1848 Devrimleri' },
    answer: 'B',
    explanation: 'The fall of the Bastille prison in Paris is commemorated as France\'s national day.',
  },
  {
    id: 'his_30',
    text: 'Which 1804 event made Haiti the first independent state founded by formerly enslaved people?',
    text_tr: '1804\'te hangi olay, Haiti\'yi eski kölelerin kurduğu ilk bağımsız devlet yaptı?',
    options: { A: 'The Louisiana Purchase', B: 'The Haitian Declaration of Independence', C: 'The abolition of the French monarchy', D: 'The Congress of Vienna', E: 'The Monroe Doctrine' },
    options_tr: { A: 'Louisiana Satın Alımı', B: 'Haiti Bağımsızlık Bildirisi', C: 'Fransız monarşisinin kaldırılması', D: 'Viyana Kongresi', E: 'Monroe Doktrini' },
    answer: 'B',
    explanation: 'After a slave revolt defeated Napoleon\'s forces, Haiti declared independence from France on 1 January 1804.',
  },
  {
    id: 'his_31',
    text: 'The Congress of Vienna (1814–1815) met to reorganize Europe after the defeat of which figure?',
    text_tr: 'Viyana Kongresi (1814–1815), kimin yenilgisinden sonra Avrupa\'yı yeniden düzenlemek için toplandı?',
    options: { A: 'Louis XVI', B: 'Napoleon Bonaparte', C: 'Metternich', D: 'Talleyrand', E: 'Tsar Alexander I' },
    options_tr: { A: 'XVI. Louis', B: 'Napolyon Bonapart', C: 'Metternich', D: 'Talleyrand', E: 'Çar I. Aleksandr' },
    answer: 'B',
    explanation: 'The Congress sought a balance-of-power settlement after Napoleon\'s first abdication; it was interrupted by his brief return in 1815.',
  },
  {
    id: 'his_32',
    text: 'The Greek War of Independence, which began in 1821, was fought against which empire?',
    text_tr: '1821\'de başlayan Yunan Bağımsızlık Savaşı, hangi imparatorluğa karşı verildi?',
    options: { A: 'The Austrian Empire', B: 'The Russian Empire', C: 'The Ottoman Empire', D: 'The Venetian Republic', E: 'The British Empire' },
    options_tr: { A: 'Avusturya İmparatorluğu', B: 'Rus İmparatorluğu', C: 'Osmanlı İmparatorluğu', D: 'Venedik Cumhuriyeti', E: 'Britanya İmparatorluğu' },
    answer: 'C',
    explanation: 'Greece won recognition of independence from the Ottoman Empire in 1830 after intervention by Britain, France and Russia.',
  },
  {
    id: 'his_33',
    text: 'Which two statesmen are most associated with the unification of Italy and Germany, respectively, in the 19th century?',
    text_tr: '19. yüzyılda İtalya ve Almanya\'nın birleşmesiyle sırasıyla en çok özdeşleşen iki devlet adamı kimlerdir?',
    options: { A: 'Garibaldi and Metternich', B: 'Cavour and Bismarck', C: 'Mazzini and Wilhelm I', D: 'Victor Emmanuel II and Moltke', E: 'Cavour and Kaiser Wilhelm II' },
    options_tr: { A: 'Garibaldi ve Metternich', B: 'Cavour ve Bismarck', C: 'Mazzini ve I. Wilhelm', D: 'II. Vittorio Emanuele ve Moltke', E: 'Cavour ve Kayzer II. Wilhelm' },
    answer: 'B',
    explanation: 'Count Cavour engineered Italian unification (completed 1871) and Otto von Bismarck engineered German unification (1871).',
  },
  {
    id: 'his_34',
    text: 'The American Civil War (1861–1865) was fought largely over which issue?',
    text_tr: 'Amerikan İç Savaşı (1861–1865) büyük ölçüde hangi mesele üzerine verildi?',
    options: { A: 'Tariffs on manufactured goods', B: 'The expansion and future of slavery', C: 'Control of railroads', D: 'Immigration policy', E: 'Currency and banking' },
    options_tr: { A: 'Sanayi mallarına gümrük vergileri', B: 'Köleliğin yayılması ve geleceği', C: 'Demiryollarının kontrolü', D: 'Göç politikası', E: 'Para ve bankacılık' },
    answer: 'B',
    explanation: 'Southern states seceded to protect slavery; the war ended slavery in the US with the 13th Amendment.',
  },
  {
    id: 'his_35',
    text: 'Which 1867 arrangement transformed the Austrian Empire into a dual monarchy?',
    text_tr: '1867\'de hangi düzenleme, Avusturya İmparatorluğu\'nu ikili bir monarşiye dönüştürdü?',
    options: { A: 'The Ausgleich (Austro-Hungarian Compromise)', B: 'The Treaty of Prague', C: 'The Pragmatic Sanction', D: 'The Dual Alliance', E: 'The Congress of Berlin' },
    options_tr: { A: 'Ausgleich (Avusturya-Macaristan Uzlaşması)', B: 'Prag Antlaşması', C: 'Pragmatik Yaptırım', D: 'İkili İttifak', E: 'Berlin Kongresi' },
    answer: 'A',
    explanation: 'The 1867 Compromise created Austria-Hungary, with Hungary gaining its own parliament and government under a shared monarch.',
  },
  {
    id: 'his_36',
    text: 'The Meiji Restoration of 1868 marked the rapid modernization of which country?',
    text_tr: '1868 Meiji Restorasyonu, hangi ülkenin hızlı modernleşmesini işaret etti?',
    options: { A: 'China', B: 'Korea', C: 'Japan', D: 'Thailand', E: 'Vietnam' },
    options_tr: { A: 'Çin', B: 'Kore', C: 'Japonya', D: 'Tayland', E: 'Vietnam' },
    answer: 'C',
    explanation: 'Power was restored to the Japanese emperor and the country industrialized and militarized within a generation.',
  },
  {
    id: 'his_37',
    text: 'The "Scramble for Africa" was formalized at which 1884–85 conference?',
    text_tr: '"Afrika Kapışması", 1884–85\'te hangi konferansta resmileştirildi?',
    options: { A: 'The Congress of Berlin', B: 'The Berlin Conference', C: 'The Hague Convention', D: 'The Brussels Conference', E: 'The Congress of Vienna' },
    options_tr: { A: 'Berlin Kongresi', B: 'Berlin Konferansı', C: 'Lahey Sözleşmesi', D: 'Brüksel Konferansı', E: 'Viyana Kongresi' },
    answer: 'B',
    explanation: 'The Berlin Conference of 1884–85 set rules for European powers partitioning Africa. The 1878 Congress of Berlin was about the Balkans.',
  },
  {
    id: 'his_38',
    text: 'Which assassination in Sarajevo in June 1914 triggered the chain of events leading to World War I?',
    text_tr: 'Haziran 1914\'te Saraybosna\'da hangi suikast, Birinci Dünya Savaşı\'na giden olaylar zincirini tetikledi?',
    options: { A: 'Tsar Nicholas II', B: 'Archduke Franz Ferdinand', C: 'King Alexander I of Serbia', D: 'Kaiser Wilhelm II', E: 'Jean Jaurès' },
    options_tr: { A: 'Çar II. Nikolay', B: 'Arşidük Franz Ferdinand', C: 'Sırbistan Kralı I. Aleksandar', D: 'Kayzer II. Wilhelm', E: 'Jean Jaurès' },
    answer: 'B',
    explanation: 'Gavrilo Princip, a Bosnian Serb nationalist, shot the Austro-Hungarian heir and his wife, prompting the July Crisis.',
  },
  {
    id: 'his_39',
    text: 'The Gallipoli Campaign of 1915 was an Allied attempt to force which strait and knock the Ottomans out of the war?',
    text_tr: '1915 Çanakkale (Gelibolu) Harekâtı, Müttefiklerin hangi boğazı zorlayıp Osmanlıları savaş dışı bırakma girişimiydi?',
    options: { A: 'The Bosphorus', B: 'The Dardanelles', C: 'The Strait of Otranto', D: 'The Suez Canal', E: 'The Strait of Gibraltar' },
    options_tr: { A: 'İstanbul Boğazı', B: 'Çanakkale Boğazı (Dardanel)', C: 'Otranto Boğazı', D: 'Süveyş Kanalı', E: 'Cebelitarık Boğazı' },
    answer: 'B',
    explanation: 'The failed landings on the Gallipoli peninsula guarding the Dardanelles cost heavy casualties on both sides; Mustafa Kemal rose to prominence there.',
  },
  {
    id: 'his_40',
    text: 'The 1917 October Revolution in Russia brought which party to power?',
    text_tr: 'Rusya\'da 1917 Ekim Devrimi hangi partiyi iktidara getirdi?',
    options: { A: 'The Mensheviks', B: 'The Socialist Revolutionaries', C: 'The Bolsheviks', D: 'The Constitutional Democrats (Kadets)', E: 'The Octobrists' },
    options_tr: { A: 'Menşevikler', B: 'Sosyalist Devrimciler', C: 'Bolşevikler', D: 'Anayasal Demokratlar (Kadetler)', E: 'Oktobristler' },
    answer: 'C',
    explanation: 'Lenin\'s Bolsheviks seized power from the Provisional Government, leading to the founding of the Soviet state.',
  },
  {
    id: 'his_41',
    text: 'The Turkish War of Independence (1919–1923) was led by which figure, who became the first president of the Republic of Turkey?',
    text_tr: 'Türk Kurtuluş Savaşı (1919–1923), Türkiye Cumhuriyeti\'nin ilk cumhurbaşkanı olan hangi kişi tarafından yönetildi?',
    options: { A: 'İsmet İnönü', B: 'Enver Pasha', C: 'Mustafa Kemal Atatürk', D: 'Kâzım Karabekir', E: 'Fevzi Çakmak' },
    options_tr: { A: 'İsmet İnönü', B: 'Enver Paşa', C: 'Mustafa Kemal Atatürk', D: 'Kâzım Karabekir', E: 'Fevzi Çakmak' },
    answer: 'C',
    explanation: 'Mustafa Kemal led the national resistance from Ankara; the Republic was proclaimed on 29 October 1923 with him as president.',
  },
  {
    id: 'his_42',
    text: 'Which 1923 treaty replaced the unratified Treaty of Sèvres and set the borders of modern Turkey?',
    text_tr: 'Onaylanmayan Sevr Antlaşması\'nın yerini alan ve modern Türkiye\'nin sınırlarını belirleyen 1923 antlaşması hangisidir?',
    options: { A: 'The Treaty of Kars', B: 'The Treaty of Lausanne', C: 'The Treaty of Moscow', D: 'The Armistice of Mudanya', E: 'The Treaty of Ankara' },
    options_tr: { A: 'Kars Antlaşması', B: 'Lozan Antlaşması', C: 'Moskova Antlaşması', D: 'Mudanya Mütarekesi', E: 'Ankara Antlaşması' },
    answer: 'B',
    explanation: 'The Treaty of Lausanne (July 1923) was negotiated by İsmet İnönü and secured international recognition of the new Turkish state.',
  },
  {
    id: 'his_43',
    text: 'The Wall Street Crash that helped trigger the Great Depression occurred in which year?',
    text_tr: 'Büyük Buhran\'ı tetiklemeye yardımcı olan Wall Street Çöküşü hangi yıl gerçekleşti?',
    options: { A: '1919', B: '1923', C: '1929', D: '1931', E: '1933' },
    options_tr: { A: '1919', B: '1923', C: '1929', D: '1931', E: '1933' },
    answer: 'C',
    explanation: 'The US stock market collapsed in October 1929, deepening a worldwide economic depression through the 1930s.',
  },
  {
    id: 'his_44',
    text: 'Adolf Hitler was appointed Chancellor of Germany in which year?',
    text_tr: 'Adolf Hitler, hangi yıl Almanya Başbakanı olarak atandı?',
    options: { A: '1929', B: '1931', C: '1933', D: '1934', E: '1936' },
    options_tr: { A: '1929', B: '1931', C: '1933', D: '1934', E: '1936' },
    answer: 'C',
    explanation: 'President Hindenburg appointed Hitler chancellor on 30 January 1933; the Nazi dictatorship consolidated over the following 18 months.',
  },
  {
    id: 'his_45',
    text: 'World War II in Europe began with the German invasion of which country in September 1939?',
    text_tr: 'Avrupa\'da İkinci Dünya Savaşı, Eylül 1939\'da Almanya\'nın hangi ülkeyi işgaliyle başladı?',
    options: { A: 'France', B: 'Czechoslovakia', C: 'Poland', D: 'Belgium', E: 'Austria' },
    options_tr: { A: 'Fransa', B: 'Çekoslovakya', C: 'Polonya', D: 'Belçika', E: 'Avusturya' },
    answer: 'C',
    explanation: 'Germany invaded Poland on 1 September 1939; Britain and France declared war two days later.',
  },
  {
    id: 'his_46',
    text: 'The D-Day landings of 6 June 1944 took place on the beaches of which region?',
    text_tr: '6 Haziran 1944\'teki Normandiya Çıkarması (D-Day), hangi bölgenin sahillerinde gerçekleşti?',
    options: { A: 'Brittany', B: 'Normandy', C: 'Provence', D: 'Flanders', E: 'Calais' },
    options_tr: { A: 'Britanya (Bretagne)', B: 'Normandiya', C: 'Provence', D: 'Flandre', E: 'Calais' },
    answer: 'B',
    explanation: 'Allied forces landed on five Normandy beaches (Utah, Omaha, Gold, Juno, Sword), opening the Western Front in France.',
  },
  {
    id: 'his_47',
    text: 'The first atomic bomb used in war was dropped on which city on 6 August 1945?',
    text_tr: 'Savaşta kullanılan ilk atom bombası, 6 Ağustos 1945\'te hangi şehre atıldı?',
    options: { A: 'Tokyo', B: 'Nagasaki', C: 'Hiroshima', D: 'Osaka', E: 'Kyoto' },
    options_tr: { A: 'Tokyo', B: 'Nagazaki', C: 'Hiroşima', D: 'Osaka', E: 'Kyoto' },
    answer: 'C',
    explanation: 'Hiroshima was bombed on 6 August; Nagasaki on 9 August. Japan announced surrender on 15 August 1945.',
  },
  {
    id: 'his_48',
    text: 'The United Nations was founded in which year, replacing the League of Nations?',
    text_tr: 'Birleşmiş Milletler, Milletler Cemiyeti\'nin yerini alarak hangi yıl kuruldu?',
    options: { A: '1919', B: '1939', C: '1945', D: '1948', E: '1950' },
    options_tr: { A: '1919', B: '1939', C: '1945', D: '1948', E: '1950' },
    answer: 'C',
    explanation: 'The UN Charter took effect on 24 October 1945. 1948 saw the Universal Declaration of Human Rights.',
  },
  {
    id: 'his_49',
    text: 'The partition of British India in 1947 created which two independent states?',
    text_tr: '1947\'de Britanya Hindistanı\'nın bölünmesi hangi iki bağımsız devleti yarattı?',
    options: { A: 'India and Bangladesh', B: 'India and Pakistan', C: 'India and Ceylon', D: 'Pakistan and Bangladesh', E: 'India and Burma' },
    options_tr: { A: 'Hindistan ve Bangladeş', B: 'Hindistan ve Pakistan', C: 'Hindistan ve Seylan', D: 'Pakistan ve Bangladeş', E: 'Hindistan ve Burma' },
    answer: 'B',
    explanation: 'India and Pakistan became independent in August 1947. Bangladesh (formerly East Pakistan) seceded from Pakistan in 1971.',
  },
  {
    id: 'his_50',
    text: 'The People\'s Republic of China was proclaimed in 1949 by which leader?',
    text_tr: 'Çin Halk Cumhuriyeti, 1949\'da hangi lider tarafından ilan edildi?',
    options: { A: 'Zhou Enlai', B: 'Chiang Kai-shek', C: 'Deng Xiaoping', D: 'Mao Zedong', E: 'Sun Yat-sen' },
    options_tr: { A: 'Zhou Enlai', B: 'Çan Kay-şek', C: 'Deng Xiaoping', D: 'Mao Zedong', E: 'Sun Yat-sen' },
    answer: 'D',
    explanation: 'Mao proclaimed the PRC on 1 October 1949 after the Communists won the civil war; the Nationalists retreated to Taiwan.',
  },
  {
    id: 'his_51',
    text: 'The Berlin Airlift of 1948–49 was a response to a blockade imposed by which power?',
    text_tr: '1948–49 Berlin Hava Köprüsü, hangi gücün uyguladığı bir ablukaya yanıttı?',
    options: { A: 'France', B: 'The United Kingdom', C: 'The Soviet Union', D: 'The United States', E: 'East Germany' },
    options_tr: { A: 'Fransa', B: 'Birleşik Krallık', C: 'Sovyetler Birliği', D: 'Amerika Birleşik Devletleri', E: 'Doğu Almanya' },
    answer: 'C',
    explanation: 'The USSR blockaded land routes to West Berlin; Western powers supplied the city by air for nearly a year.',
  },
  {
    id: 'his_52',
    text: 'Which 1962 confrontation brought the US and USSR to the brink of nuclear war over missiles on a Caribbean island?',
    text_tr: '1962\'de bir Karayip adasındaki füzeler yüzünden ABD ve SSCB\'yi nükleer savaşın eşiğine getiren kriz hangisidir?',
    options: { A: 'The Berlin Crisis', B: 'The Cuban Missile Crisis', C: 'The Suez Crisis', D: 'The U-2 incident', E: 'The Bay of Pigs invasion' },
    options_tr: { A: 'Berlin Krizi', B: 'Küba Füze Krizi', C: 'Süveyş Krizi', D: 'U-2 olayı', E: 'Domuzlar Körfezi çıkarması' },
    answer: 'B',
    explanation: 'In October 1962, the US discovered Soviet nuclear missiles in Cuba; a naval "quarantine" and secret negotiations defused the crisis.',
  },
  {
    id: 'his_53',
    text: 'Which country did the US formally enter a war to defend in the 1960s, withdrawing in 1973?',
    text_tr: 'ABD, 1960\'larda savunmak için resmen bir savaşa girip 1973\'te çekildiği ülke hangisidir?',
    options: { A: 'Cambodia', B: 'South Korea', C: 'Laos', D: 'South Vietnam', E: 'Thailand' },
    options_tr: { A: 'Kamboçya', B: 'Güney Kore', C: 'Laos', D: 'Güney Vietnam', E: 'Tayland' },
    answer: 'D',
    explanation: 'US combat troops fought for South Vietnam; the Paris Peace Accords of 1973 preceded the fall of Saigon in 1975.',
  },
  {
    id: 'his_54',
    text: 'The first human to journey into outer space, in 1961, was a citizen of which country?',
    text_tr: '1961\'de uzaya çıkan ilk insan, hangi ülkenin vatandaşıydı?',
    options: { A: 'The United States', B: 'The Soviet Union', C: 'The United Kingdom', D: 'France', E: 'Germany' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Sovyetler Birliği', C: 'Birleşik Krallık', D: 'Fransa', E: 'Almanya' },
    answer: 'B',
    explanation: 'Yuri Gagarin orbited Earth aboard Vostok 1 on 12 April 1961.',
  },
  {
    id: 'his_55',
    text: 'Apollo 11 landed the first humans on the Moon in which year?',
    text_tr: 'Apollo 11, ilk insanları Ay\'a hangi yıl indirdi?',
    options: { A: '1967', B: '1968', C: '1969', D: '1970', E: '1972' },
    options_tr: { A: '1967', B: '1968', C: '1969', D: '1970', E: '1972' },
    answer: 'C',
    explanation: 'Neil Armstrong and Buzz Aldrin walked on the Moon on 20 July 1969.',
  },
  {
    id: 'his_56',
    text: 'The Prague Spring of 1968, a period of liberal reform, was crushed by an invasion by which alliance?',
    text_tr: '1968\'de bir liberal reform dönemi olan Prag Baharı, hangi ittifakın işgaliyle bastırıldı?',
    options: { A: 'NATO', B: 'The Warsaw Pact', C: 'The Comintern', D: 'CENTO', E: 'The Non-Aligned Movement' },
    options_tr: { A: 'NATO', B: 'Varşova Paktı', C: 'Komintern', D: 'CENTO', E: 'Bağlantısızlar Hareketi' },
    answer: 'B',
    explanation: 'Warsaw Pact forces led by the USSR invaded Czechoslovakia in August 1968 to reverse Alexander Dubček\'s reforms.',
  },
  {
    id: 'his_57',
    text: 'The Iranian Revolution of 1979 overthrew the Shah and established a republic led by which figure?',
    text_tr: '1979 İran Devrimi, Şah\'ı devirip hangi kişinin önderliğinde bir cumhuriyet kurdu?',
    options: { A: 'Mohammad Mosaddegh', B: 'Ali Khamenei', C: 'Ruhollah Khomeini', D: 'Abolhassan Banisadr', E: 'Mehdi Bazargan' },
    options_tr: { A: 'Muhammed Musaddık', B: 'Ali Hamaney', C: 'Ruhullah Humeyni', D: 'Abolhasan Benisadr', E: 'Mehdi Bazergan' },
    answer: 'C',
    explanation: 'Ayatollah Khomeini returned from exile and became Supreme Leader of the new Islamic Republic of Iran.',
  },
  {
    id: 'his_58',
    text: 'The Berlin Wall fell in which year, symbolizing the end of the Cold War division of Europe?',
    text_tr: 'Berlin Duvarı, Avrupa\'nın Soğuk Savaş bölünmesinin sonunu simgeleyerek hangi yıl yıkıldı?',
    options: { A: '1985', B: '1987', C: '1989', D: '1990', E: '1991' },
    options_tr: { A: '1985', B: '1987', C: '1989', D: '1990', E: '1991' },
    answer: 'C',
    explanation: 'The wall was opened on 9 November 1989; Germany was reunified in October 1990 and the USSR dissolved in December 1991.',
  },
  {
    id: 'his_59',
    text: 'The Soviet Union was formally dissolved in which year?',
    text_tr: 'Sovyetler Birliği resmen hangi yıl dağıldı?',
    options: { A: '1989', B: '1990', C: '1991', D: '1992', E: '1993' },
    options_tr: { A: '1989', B: '1990', C: '1991', D: '1992', E: '1993' },
    answer: 'C',
    explanation: 'Mikhail Gorbachev resigned on 25 December 1991 and the USSR ceased to exist the next day, splitting into 15 states.',
  },
  {
    id: 'his_60',
    text: 'Apartheid in South Africa formally ended with the first fully multiracial elections in which year?',
    text_tr: 'Güney Afrika\'da apartheid, ilk tam çok ırklı seçimlerle resmen hangi yıl sona erdi?',
    options: { A: '1990', B: '1991', C: '1993', D: '1994', E: '1996' },
    options_tr: { A: '1990', B: '1991', C: '1993', D: '1994', E: '1996' },
    answer: 'D',
    explanation: 'Nelson Mandela was elected president in the April 1994 elections, ending decades of white-minority rule.',
  },
  {
    id: 'his_61',
    text: 'Which ancient wonder, a lighthouse, stood on the island of Pharos near Alexandria?',
    text_tr: 'Bir deniz feneri olan hangi antik dünya harikası, İskenderiye yakınlarındaki Pharos adasında bulunuyordu?',
    options: { A: 'The Colossus of Rhodes', B: 'The Lighthouse of Alexandria', C: 'The Temple of Artemis', D: 'The Mausoleum at Halicarnassus', E: 'The Hanging Gardens' },
    options_tr: { A: 'Rodos Heykeli', B: 'İskenderiye Feneri', C: 'Artemis Tapınağı', D: 'Halikarnas Mozolesi', E: 'Asma Bahçeler' },
    answer: 'B',
    explanation: 'The Lighthouse (Pharos) of Alexandria, built under the Ptolemies around 280 BC, was one of the Seven Wonders of the Ancient World.',
  },
  {
    id: 'his_62',
    text: 'The Silk Road primarily connected China with which other region?',
    text_tr: 'İpek Yolu esas olarak Çin\'i hangi diğer bölgeyle bağlıyordu?',
    options: { A: 'Sub-Saharan Africa', B: 'The Mediterranean and Europe', C: 'The Americas', D: 'Australia', E: 'Scandinavia' },
    options_tr: { A: 'Sahra Altı Afrika', B: 'Akdeniz ve Avrupa', C: 'Amerika kıtası', D: 'Avustralya', E: 'İskandinavya' },
    answer: 'B',
    explanation: 'The network of routes carried silk, spices and ideas between East Asia and the Mediterranean world for over a thousand years.',
  },
  {
    id: 'his_63',
    text: 'The Magna Carta, the Renaissance and the Reformation all took place before which of these events?',
    text_tr: 'Magna Carta, Rönesans ve Reform — hepsi aşağıdaki olaylardan hangisinden önce gerçekleşti?',
    options: { A: 'The fall of the Western Roman Empire', B: 'The Norman Conquest of England', C: 'The French Revolution', D: 'The Crusades', E: 'The reign of Charlemagne' },
    options_tr: { A: 'Batı Roma İmparatorluğu\'nun yıkılışı', B: 'İngiltere\'nin Norman Fethi', C: 'Fransız Devrimi', D: 'Haçlı Seferleri', E: 'Şarlman\'ın saltanatı' },
    answer: 'C',
    explanation: 'Magna Carta (1215), the Renaissance (14th–16th c.) and the Reformation (16th c.) all predate the French Revolution (1789).',
  },
  {
    id: 'his_64',
    text: 'Which empire was ruled from the city of Tenochtitlan?',
    text_tr: 'Hangi imparatorluk Tenochtitlan şehrinden yönetiliyordu?',
    options: { A: 'The Inca Empire', B: 'The Aztec Empire', C: 'The Maya League', D: 'The Kingdom of Kush', E: 'The Songhai Empire' },
    options_tr: { A: 'İnka İmparatorluğu', B: 'Aztek İmparatorluğu', C: 'Maya Ligi', D: 'Kush Krallığı', E: 'Songhay İmparatorluğu' },
    answer: 'B',
    explanation: 'Tenochtitlan, on an island in Lake Texcoco, was the Aztec capital; Mexico City is built over its ruins.',
  },
  {
    id: 'his_65',
    text: 'The Ottoman devşirme system recruited boys, primarily from Balkan Christian families, for what purpose?',
    text_tr: 'Osmanlı devşirme sistemi, ağırlıklı olarak Balkan Hristiyan ailelerinden erkek çocukları hangi amaçla topluyordu?',
    options: { A: 'Agricultural labour on state farms', B: 'Service in the Janissary corps and palace administration', C: 'Galley rowing in the navy', D: 'Construction of imperial mosques', E: 'Tax collection in the provinces' },
    options_tr: { A: 'Devlet çiftliklerinde tarım işçiliği', B: 'Yeniçeri ocağı ve saray yönetiminde hizmet', C: 'Donanmada kadırga kürekçiliği', D: 'İmparatorluk camilerinin inşası', E: 'Taşrada vergi toplama' },
    answer: 'B',
    explanation: 'Levied boys were converted to Islam and trained; the ablest rose to high office, some becoming grand viziers.',
  },
  {
    id: 'his_66',
    text: 'The Renaissance is generally considered to have begun in which country?',
    text_tr: 'Rönesans\'ın genellikle hangi ülkede başladığı kabul edilir?',
    options: { A: 'France', B: 'The Netherlands', C: 'Italy', D: 'England', E: 'Germany' },
    options_tr: { A: 'Fransa', B: 'Hollanda', C: 'İtalya', D: 'İngiltere', E: 'Almanya' },
    answer: 'C',
    explanation: 'The cultural rebirth began in the Italian city-states, especially Florence, in the 14th century.',
  },
  {
    id: 'his_67',
    text: 'Which trade route across the Atlantic forcibly transported millions of enslaved Africans to the Americas?',
    text_tr: 'Atlantik boyunca uzanan hangi ticaret yolu, milyonlarca köleleştirilmiş Afrikalıyı zorla Amerika kıtasına taşıdı?',
    options: { A: 'The Columbian Exchange', B: 'The Middle Passage', C: 'The Trans-Saharan trade', D: 'The Manila Galleon route', E: 'The Hanseatic League routes' },
    options_tr: { A: 'Kolomb Değişimi', B: 'Orta Geçit (Middle Passage)', C: 'Trans-Sahra ticareti', D: 'Manila Kalyonu rotası', E: 'Hansa Birliği rotaları' },
    answer: 'B',
    explanation: 'The "Middle Passage" was the transatlantic leg of the triangular trade, notorious for its lethal conditions.',
  },
  {
    id: 'his_68',
    text: 'The Industrial Revolution began in the late 18th century in which country?',
    text_tr: 'Sanayi Devrimi, 18. yüzyılın sonlarında hangi ülkede başladı?',
    options: { A: 'The United States', B: 'France', C: 'Belgium', D: 'Great Britain', E: 'Prussia' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Fransa', C: 'Belçika', D: 'Büyük Britanya', E: 'Prusya' },
    answer: 'D',
    explanation: 'Textile mechanization, steam power and coal in Britain from around the 1760s launched industrialization.',
  },
  {
    id: 'his_69',
    text: 'Which war between 1853 and 1856 saw Britain, France and the Ottomans fight Russia, and is remembered for Florence Nightingale\'s nursing work?',
    text_tr: '1853–1856 arasında Britanya, Fransa ve Osmanlıların Rusya ile savaştığı, Florence Nightingale\'in hemşirelik çalışmasıyla hatırlanan savaş hangisidir?',
    options: { A: 'The Russo-Turkish War', B: 'The Crimean War', C: 'The Franco-Prussian War', D: 'The Second Italian War of Independence', E: 'The Great Eastern Crisis' },
    options_tr: { A: 'Rus-Türk Savaşı', B: 'Kırım Savaşı', C: 'Fransa-Prusya Savaşı', D: 'İkinci İtalya Bağımsızlık Savaşı', E: 'Büyük Doğu Krizi' },
    answer: 'B',
    explanation: 'The Crimean War (1853–56) centred on the Black Sea and the fortress of Sevastopol.',
  },
  {
    id: 'his_70',
    text: 'The Tanzimat reforms of the 19th century were an attempt to modernize which state?',
    text_tr: '19. yüzyıldaki Tanzimat reformları, hangi devleti modernleştirme girişimiydi?',
    options: { A: 'The Russian Empire', B: 'The Qajar dynasty of Persia', C: 'The Ottoman Empire', D: 'The Kingdom of Egypt', E: 'The Austrian Empire' },
    options_tr: { A: 'Rus İmparatorluğu', B: 'İran Kaçar Hanedanı', C: 'Osmanlı İmparatorluğu', D: 'Mısır Krallığı', E: 'Avusturya İmparatorluğu' },
    answer: 'C',
    explanation: 'The Tanzimat ("reorganization") edicts of 1839 and 1856 reformed Ottoman law, administration, taxation and the status of non-Muslims.',
  },
  {
    id: 'his_71',
    text: 'Which 1885 political organization is regarded as the vehicle that eventually led India to independence?',
    text_tr: 'Hangi 1885 siyasi örgütü, Hindistan\'ı sonunda bağımsızlığa götüren araç olarak görülür?',
    options: { A: 'The Muslim League', B: 'The Indian National Congress', C: 'The Swaraj Party', D: 'The Home Rule League', E: 'The Ghadar Party' },
    options_tr: { A: 'Müslüman Birliği', B: 'Hindistan Ulusal Kongresi', C: 'Swaraj Partisi', D: 'Home Rule Ligi', E: 'Ghadar Partisi' },
    answer: 'B',
    explanation: 'The Indian National Congress, founded in 1885, became the main nationalist movement under leaders such as Gandhi and Nehru.',
  },
  {
    id: 'his_72',
    text: 'The Boxer Rebellion of 1899–1901 was an uprising against foreign influence in which country?',
    text_tr: '1899–1901 Boksör İsyanı, hangi ülkedeki yabancı nüfuza karşı bir ayaklanmaydı?',
    options: { A: 'Japan', B: 'Korea', C: 'China', D: 'Vietnam', E: 'Siam' },
    options_tr: { A: 'Japonya', B: 'Kore', C: 'Çin', D: 'Vietnam', E: 'Siyam' },
    answer: 'C',
    explanation: 'The anti-foreign, anti-Christian uprising in Qing China was suppressed by an eight-nation alliance.',
  },
  {
    id: 'his_73',
    text: 'Which 1905 war was the first modern conflict in which an Asian power defeated a European great power?',
    text_tr: 'Hangi 1905 savaşı, bir Asya gücünün bir Avrupa büyük gücünü yendiği ilk modern çatışmaydı?',
    options: { A: 'The First Sino-Japanese War', B: 'The Russo-Japanese War', C: 'The Boxer War', D: 'The Anglo-Afghan War', E: 'The Italo-Turkish War' },
    options_tr: { A: 'Birinci Çin-Japon Savaşı', B: 'Rus-Japon Savaşı', C: 'Boksör Savaşı', D: 'İngiliz-Afgan Savaşı', E: 'İtalyan-Türk Savaşı' },
    answer: 'B',
    explanation: 'Japan\'s victory over Russia in 1904–05, sealed at Tsushima and Mukden, shocked the European powers.',
  },
  {
    id: 'his_74',
    text: 'The Balfour Declaration of 1917 expressed British support for a national home for which people in Palestine?',
    text_tr: '1917 Balfour Deklarasyonu, Filistin\'de hangi halk için bir ulusal yurda Britanya desteğini ifade etti?',
    options: { A: 'The Armenians', B: 'The Kurds', C: 'The Jewish people', D: 'The Assyrians', E: 'The Druze' },
    options_tr: { A: 'Ermeniler', B: 'Kürtler', C: 'Yahudi halkı', D: 'Süryaniler', E: 'Dürziler' },
    answer: 'C',
    explanation: 'The letter from Foreign Secretary Arthur Balfour became a cornerstone of the British Mandate policy in Palestine.',
  },
  {
    id: 'his_75',
    text: 'The Spanish Civil War (1936–1939) ended with the victory of forces led by whom?',
    text_tr: 'İspanya İç Savaşı (1936–1939), kimin önderliğindeki güçlerin zaferiyle sona erdi?',
    options: { A: 'Manuel Azaña', B: 'Francisco Franco', C: 'Dolores Ibárruri', D: 'José Antonio Primo de Rivera', E: 'Juan Negrín' },
    options_tr: { A: 'Manuel Azaña', B: 'Francisco Franco', C: 'Dolores Ibárruri', D: 'José Antonio Primo de Rivera', E: 'Juan Negrín' },
    answer: 'B',
    explanation: 'General Franco\'s Nationalists defeated the Republic and he ruled Spain as dictator until his death in 1975.',
  },
  {
    id: 'his_76',
    text: 'The Marshall Plan of 1948 was a US program to do what?',
    text_tr: '1948 Marshall Planı, ABD\'nin ne yapmak için başlattığı bir programdı?',
    options: { A: 'Rebuild the economies of Western Europe', B: 'Contain communism in East Asia', C: 'Fund the United Nations', D: 'Establish NATO military bases', E: 'Provide famine relief to India' },
    options_tr: { A: 'Batı Avrupa ekonomilerini yeniden inşa etmek', B: 'Doğu Asya\'da komünizmi çevrelemek', C: 'Birleşmiş Milletler\'i finanse etmek', D: 'NATO askeri üsleri kurmak', E: 'Hindistan\'a kıtlık yardımı sağlamak' },
    answer: 'A',
    explanation: 'The European Recovery Program sent roughly $13 billion in aid to help rebuild war-torn Western Europe and blunt Soviet appeal.',
  },
  {
    id: 'his_77',
    text: 'The Korean War (1950–1953) ended with an armistice that left the peninsula divided near which parallel?',
    text_tr: 'Kore Savaşı (1950–1953), yarımadayı yaklaşık hangi paralel yakınında bölünmüş bırakan bir ateşkesle sona erdi?',
    options: { A: 'The 17th parallel', B: 'The 38th parallel', C: 'The 45th parallel', D: 'The 49th parallel', E: 'The 40th parallel' },
    options_tr: { A: '17. paralel', B: '38. paralel', C: '45. paralel', D: '49. paralel', E: '40. paralel' },
    answer: 'B',
    explanation: 'The 1953 armistice fixed the demilitarized zone near the 38th parallel; no peace treaty has been signed. The 17th parallel divided Vietnam.',
  },
  {
    id: 'his_78',
    text: 'The 1956 Suez Crisis was triggered when Egypt\'s Nasser nationalized what?',
    text_tr: '1956 Süveyş Krizi, Mısır lideri Nasır\'ın neyi millileştirmesiyle tetiklendi?',
    options: { A: 'The Aswan Dam', B: 'The Suez Canal', C: 'Egypt\'s oil fields', D: 'The Cairo railways', E: 'The cotton export board' },
    options_tr: { A: 'Assuan Barajı', B: 'Süveyş Kanalı', C: 'Mısır petrol sahaları', D: 'Kahire demiryolları', E: 'Pamuk ihracat kurulu' },
    answer: 'B',
    explanation: 'Nasser nationalized the Anglo-French canal company in July 1956; an Israeli, British and French intervention followed but was reversed under US and Soviet pressure.',
  },
  {
    id: 'his_79',
    text: '"Perestroika" and "glasnost" were reform policies associated with which Soviet leader?',
    text_tr: '"Perestroyka" ve "glasnost", hangi Sovyet lideriyle özdeşleşen reform politikalarıydı?',
    options: { A: 'Nikita Khrushchev', B: 'Leonid Brezhnev', C: 'Yuri Andropov', D: 'Mikhail Gorbachev', E: 'Boris Yeltsin' },
    options_tr: { A: 'Nikita Kruşçev', B: 'Leonid Brejnev', C: 'Yuri Andropov', D: 'Mihail Gorbaçov', E: 'Boris Yeltsin' },
    answer: 'D',
    explanation: 'Gorbachev introduced "restructuring" and "openness" from 1985; both accelerated the collapse of the Soviet system.',
  },
  {
    id: 'his_80',
    text: 'The European Union was established by which 1992 treaty?',
    text_tr: 'Avrupa Birliği, hangi 1992 antlaşmasıyla kuruldu?',
    options: { A: 'The Treaty of Rome', B: 'The Single European Act', C: 'The Maastricht Treaty', D: 'The Treaty of Lisbon', E: 'The Schengen Agreement' },
    options_tr: { A: 'Roma Antlaşması', B: 'Avrupa Tek Senedi', C: 'Maastricht Antlaşması', D: 'Lizbon Antlaşması', E: 'Schengen Anlaşması' },
    answer: 'C',
    explanation: 'The Maastricht Treaty (signed 1992, in force 1993) created the EU and set the path to the euro.',
  },
  {
    id: 'his_81',
    text: 'Which civilization developed cuneiform, one of the earliest known writing systems, in Mesopotamia?',
    text_tr: 'Mezopotamya\'da bilinen en eski yazı sistemlerinden biri olan çivi yazısını hangi medeniyet geliştirdi?',
    options: { A: 'The Egyptians', B: 'The Sumerians', C: 'The Hittites', D: 'The Phoenicians', E: 'The Minoans' },
    options_tr: { A: 'Mısırlılar', B: 'Sümerler', C: 'Hititler', D: 'Fenikeliler', E: 'Minoslular' },
    answer: 'B',
    explanation: 'The Sumerians of southern Mesopotamia developed cuneiform on clay tablets from around 3200 BC.',
  },
  {
    id: 'his_82',
    text: 'The Hittite Empire, which clashed with Egypt at the Battle of Kadesh, was centred in which modern country?',
    text_tr: 'Kadeş Savaşı\'nda Mısır ile çatışan Hitit İmparatorluğu, hangi modern ülkede merkezliydi?',
    options: { A: 'Iraq', B: 'Iran', C: 'Turkey', D: 'Syria', E: 'Greece' },
    options_tr: { A: 'Irak', B: 'İran', C: 'Türkiye', D: 'Suriye', E: 'Yunanistan' },
    answer: 'C',
    explanation: 'The Hittite capital Hattusa was in central Anatolia, near modern Boğazkale. Kadesh (c. 1274 BC) produced one of history\'s first known peace treaties.',
  },
  {
    id: 'his_83',
    text: 'Which Greek city-state is credited with developing an early form of democracy in the 5th century BC?',
    text_tr: 'MÖ 5. yüzyılda erken bir demokrasi biçimi geliştirdiği kabul edilen Yunan şehir devleti hangisidir?',
    options: { A: 'Sparta', B: 'Corinth', C: 'Thebes', D: 'Athens', E: 'Syracuse' },
    options_tr: { A: 'Sparta', B: 'Korint', C: 'Teba', D: 'Atina', E: 'Siraküza' },
    answer: 'D',
    explanation: 'Athenian democracy, associated with reforms by Cleisthenes (508 BC) and the age of Pericles, let male citizens vote directly in the assembly.',
  },
  {
    id: 'his_84',
    text: 'The Roman Republic became the Roman Empire when which man became the first emperor, Augustus?',
    text_tr: 'Roma Cumhuriyeti, hangi kişi ilk imparator Augustus olduğunda Roma İmparatorluğu\'na dönüştü?',
    options: { A: 'Julius Caesar', B: 'Octavian', C: 'Mark Antony', D: 'Tiberius', E: 'Pompey' },
    options_tr: { A: 'Julius Caesar', B: 'Octavianus', C: 'Marcus Antonius', D: 'Tiberius', E: 'Pompeius' },
    answer: 'B',
    explanation: 'Octavian, Caesar\'s adopted heir, took the title Augustus in 27 BC after defeating Antony and Cleopatra.',
  },
  {
    id: 'his_85',
    text: 'The Crusades, beginning in 1096, were launched primarily to seize control of which city?',
    text_tr: '1096\'da başlayan Haçlı Seferleri, esas olarak hangi şehrin kontrolünü ele geçirmek için başlatıldı?',
    options: { A: 'Constantinople', B: 'Damascus', C: 'Jerusalem', D: 'Antioch', E: 'Cairo' },
    options_tr: { A: 'Konstantinopolis', B: 'Şam', C: 'Kudüs', D: 'Antakya', E: 'Kahire' },
    answer: 'C',
    explanation: 'Pope Urban II called the First Crusade in 1095; the crusaders captured Jerusalem in 1099.',
  },
  {
    id: 'his_86',
    text: 'Marco Polo\'s famous 13th-century travels took him to the court of which ruler?',
    text_tr: 'Marco Polo\'nun ünlü 13. yüzyıl seyahatleri, onu hangi hükümdarın sarayına götürdü?',
    options: { A: 'Genghis Khan', B: 'Kublai Khan', C: 'Timur (Tamerlane)', D: 'Saladin', E: 'Suleiman the Magnificent' },
    options_tr: { A: 'Cengiz Han', B: 'Kubilay Han', C: 'Timur', D: 'Selahaddin Eyyubi', E: 'Kanuni Sultan Süleyman' },
    answer: 'B',
    explanation: 'The Venetian merchant claimed to have served Kublai Khan, founder of the Yuan dynasty in China, for many years.',
  },
  {
    id: 'his_87',
    text: 'The Reconquista concluded in 1492 with the fall of which last Muslim stronghold in Iberia?',
    text_tr: 'Reconquista, 1492\'de İberya\'daki son Müslüman kalesi olan hangi şehrin düşüşüyle sona erdi?',
    options: { A: 'Córdoba', B: 'Seville', C: 'Toledo', D: 'Granada', E: 'Valencia' },
    options_tr: { A: 'Kurtuba', B: 'Sevilla', C: 'Toledo', D: 'Gırnata', E: 'Valensiya' },
    answer: 'D',
    explanation: 'The Emirate of Granada surrendered to Ferdinand and Isabella in January 1492, completing the Christian reconquest of Spain.',
  },
  {
    id: 'his_88',
    text: 'The Glorious Revolution of 1688 replaced James II of England with which joint monarchs?',
    text_tr: '1688 Şanlı Devrimi, İngiltere Kralı II. James\'in yerine hangi ortak hükümdarları getirdi?',
    options: { A: 'William III and Mary II', B: 'Anne and George of Denmark', C: 'George I and Sophia', D: 'Charles II and Catherine', E: 'William IV and Adelaide' },
    options_tr: { A: 'III. William ve II. Mary', B: 'Anne ve Danimarkalı George', C: 'I. George ve Sophia', D: 'II. Charles ve Catherine', E: 'IV. William ve Adelaide' },
    answer: 'A',
    explanation: 'Parliament invited the Dutch stadtholder William of Orange and his wife Mary, James\'s daughter, to take the throne jointly.',
  },
  {
    id: 'his_89',
    text: 'The "Boston Tea Party" of 1773 was a protest by American colonists against a tax on what?',
    text_tr: '1773 "Boston Çay Partisi", Amerikalı kolonicilerin neye konan vergiye karşı bir protestosuydu?',
    options: { A: 'Sugar', B: 'Stamps and legal documents', C: 'Tea', D: 'Glass and paper', E: 'Molasses' },
    options_tr: { A: 'Şeker', B: 'Damga ve resmi belgeler', C: 'Çay', D: 'Cam ve kâğıt', E: 'Melas' },
    answer: 'C',
    explanation: 'Colonists dumped East India Company tea into Boston Harbor to protest the Tea Act and "taxation without representation".',
  },
  {
    id: 'his_90',
    text: 'Napoleon Bonaparte was finally defeated in 1815 at which battle?',
    text_tr: 'Napolyon Bonapart, 1815\'te hangi savaşta nihai olarak yenildi?',
    options: { A: 'Austerlitz', B: 'Borodino', C: 'Leipzig', D: 'Waterloo', E: 'Trafalgar' },
    options_tr: { A: 'Austerlitz', B: 'Borodino', C: 'Leipzig', D: 'Waterloo', E: 'Trafalgar' },
    answer: 'D',
    explanation: 'A coalition under Wellington and Blücher defeated Napoleon at Waterloo in present-day Belgium; he was exiled to Saint Helena.',
  },
  {
    id: 'his_91',
    text: 'Simón Bolívar is celebrated as a liberator of which region from Spanish rule?',
    text_tr: 'Simón Bolívar, hangi bölgeyi İspanyol yönetiminden kurtaran kişi olarak kutlanır?',
    options: { A: 'Mexico and Central America', B: 'northern South America', C: 'the Caribbean islands', D: 'the Philippines', E: 'Brazil' },
    options_tr: { A: 'Meksika ve Orta Amerika', B: 'kuzey Güney Amerika', C: 'Karayip adaları', D: 'Filipinler', E: 'Brezilya' },
    answer: 'B',
    explanation: 'Bolívar led independence campaigns that freed Venezuela, Colombia, Ecuador, Peru and Bolivia (named after him) in the 1810s–20s.',
  },
  {
    id: 'his_92',
    text: 'The Opium Wars of the 19th century were fought between China and which country?',
    text_tr: '19. yüzyıldaki Afyon Savaşları, Çin ile hangi ülke arasında yapıldı?',
    options: { A: 'France', B: 'Russia', C: 'Britain', D: 'Japan', E: 'Portugal' },
    options_tr: { A: 'Fransa', B: 'Rusya', C: 'Britanya', D: 'Japonya', E: 'Portekiz' },
    answer: 'C',
    explanation: 'Britain fought the First (1839–42) and, with France, the Second (1856–60) Opium War, forcing open Chinese trade and ceding Hong Kong.',
  },
  {
    id: 'his_93',
    text: 'The League of Nations was created after which conflict?',
    text_tr: 'Milletler Cemiyeti, hangi çatışmadan sonra kuruldu?',
    options: { A: 'The Franco-Prussian War', B: 'World War I', C: 'World War II', D: 'The Crimean War', E: 'The Napoleonic Wars' },
    options_tr: { A: 'Fransa-Prusya Savaşı', B: 'Birinci Dünya Savaşı', C: 'İkinci Dünya Savaşı', D: 'Kırım Savaşı', E: 'Napolyon Savaşları' },
    answer: 'B',
    explanation: 'The League was founded in 1920 under the Treaty of Versailles; its failure to prevent WWII led to its replacement by the UN.',
  },
  {
    id: 'his_94',
    text: 'Mahatma Gandhi\'s 1930 Salt March was a protest against a British monopoly and tax on what?',
    text_tr: 'Mahatma Gandhi\'nin 1930 Tuz Yürüyüşü, bir Britanya tekeline ve neye konan vergiye karşı bir protestoydu?',
    options: { A: 'Cotton cloth', B: 'Salt', C: 'Tea', D: 'Opium', E: 'Iron' },
    options_tr: { A: 'Pamuklu kumaş', B: 'Tuz', C: 'Çay', D: 'Afyon', E: 'Demir' },
    answer: 'B',
    explanation: 'Gandhi walked to the sea at Dandi to make salt in defiance of the colonial salt laws, energizing the civil-disobedience movement.',
  },
  {
    id: 'his_95',
    text: 'Which country was the first to grant women the right to vote in national elections, in 1893?',
    text_tr: '1893\'te ulusal seçimlerde kadınlara oy hakkı tanıyan ilk ülke hangisidir?',
    options: { A: 'The United States', B: 'The United Kingdom', C: 'New Zealand', D: 'Finland', E: 'Australia' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Birleşik Krallık', C: 'Yeni Zelanda', D: 'Finlandiya', E: 'Avustralya' },
    answer: 'C',
    explanation: 'New Zealand granted women\'s suffrage in 1893. Finland (1906) was the first to also allow women to stand for parliament.',
  },
  {
    id: 'his_96',
    text: 'The Cuban Revolution of 1959 brought which leader to power?',
    text_tr: '1959 Küba Devrimi, hangi lideri iktidara getirdi?',
    options: { A: 'Che Guevara', B: 'Fulgencio Batista', C: 'Fidel Castro', D: 'Camilo Cienfuegos', E: 'Raúl Castro' },
    options_tr: { A: 'Che Guevara', B: 'Fulgencio Batista', C: 'Fidel Castro', D: 'Camilo Cienfuegos', E: 'Raúl Castro' },
    answer: 'C',
    explanation: 'Fidel Castro\'s 26th of July Movement overthrew Batista on 1 January 1959 and Castro ruled Cuba for nearly five decades.',
  },
  {
    id: 'his_97',
    text: 'The Rwandan genocide, in which an estimated 800,000 people were killed in about 100 days, occurred in which year?',
    text_tr: 'Yaklaşık 100 günde tahminen 800.000 kişinin öldürüldüğü Ruanda soykırımı hangi yıl gerçekleşti?',
    options: { A: '1990', B: '1992', C: '1994', D: '1996', E: '1998' },
    options_tr: { A: '1990', B: '1992', C: '1994', D: '1996', E: '1998' },
    answer: 'C',
    explanation: 'The genocide against the Tutsi by Hutu extremists ran from April to July 1994, ending when the RPF took power.',
  },
  {
    id: 'his_98',
    text: 'The Ottoman Empire officially ended and the Sultanate was abolished in which year?',
    text_tr: 'Osmanlı İmparatorluğu resmen sona erdi ve saltanat hangi yıl kaldırıldı?',
    options: { A: '1918', B: '1920', C: '1922', D: '1923', E: '1924' },
    options_tr: { A: '1918', B: '1920', C: '1922', D: '1923', E: '1924' },
    answer: 'C',
    explanation: 'The Grand National Assembly abolished the sultanate on 1 November 1922; the last sultan, Mehmed VI, left the country. The caliphate followed in 1924.',
  },
  {
    id: 'his_99',
    text: 'The Battle of Sakarya (1921) and the Great Offensive (1922) were decisive victories in which war?',
    text_tr: 'Sakarya Meydan Muharebesi (1921) ve Büyük Taarruz (1922), hangi savaşta belirleyici zaferlerdi?',
    options: { A: 'The First Balkan War', B: 'World War I', C: 'The Turkish War of Independence', D: 'The Italo-Turkish War', E: 'The Crimean War' },
    options_tr: { A: 'Birinci Balkan Savaşı', B: 'Birinci Dünya Savaşı', C: 'Türk Kurtuluş Savaşı', D: 'İtalyan-Türk Savaşı', E: 'Kırım Savaşı' },
    answer: 'C',
    explanation: 'These battles against the invading Greek army secured western Anatolia; İzmir was retaken in September 1922.',
  },
  {
    id: 'his_100',
    text: 'The Nuremberg Trials of 1945–46 prosecuted leading officials of which regime?',
    text_tr: '1945–46 Nürnberg Duruşmaları, hangi rejimin önde gelen yetkililerini yargıladı?',
    options: { A: 'Fascist Italy', B: 'Imperial Japan', C: 'Nazi Germany', D: 'Vichy France', E: 'the Soviet Union' },
    options_tr: { A: 'Faşist İtalya', B: 'İmparatorluk Japonyası', C: 'Nazi Almanyası', D: 'Vichy Fransası', E: 'Sovyetler Birliği' },
    answer: 'C',
    explanation: 'An international military tribunal tried 24 senior Nazi leaders for war crimes, crimes against peace and crimes against humanity.',
  },
];

module.exports = { history };
