'use strict';

const literature = [
  {
    id: 'lit_01',
    text: 'Who wrote "Don Quixote," often cited as the first modern novel?',
    text_tr: 'Genellikle ilk modern roman olarak gösterilen "Don Kişot"u kim yazmıştır?',
    options: { A: 'Lope de Vega', B: 'Miguel de Cervantes', C: 'Francisco de Quevedo', D: 'Tirso de Molina', E: 'Calderón de la Barca' },
    options_tr: { A: 'Lope de Vega', B: 'Miguel de Cervantes', C: 'Francisco de Quevedo', D: 'Tirso de Molina', E: 'Calderón de la Barca' },
    answer: 'B',
    explanation: 'Miguel de Cervantes wrote Don Quixote (Part I: 1605, Part II: 1615), widely considered the first modern novel.',
  },
  {
    id: 'lit_02',
    text: 'Which Turkish author won the Nobel Prize in Literature in 2006?',
    text_tr: '2006 yılında Nobel Edebiyat Ödülü\'nü kazanan Türk yazar kimdir?',
    options: { A: 'Yaşar Kemal', B: 'Aziz Nesin', C: 'Orhan Pamuk', D: 'Sabahattin Ali', E: 'Ahmet Hamdi Tanpınar' },
    options_tr: { A: 'Yaşar Kemal', B: 'Aziz Nesin', C: 'Orhan Pamuk', D: 'Sabahattin Ali', E: 'Ahmet Hamdi Tanpınar' },
    answer: 'C',
    explanation: 'Orhan Pamuk won the 2006 Nobel Prize in Literature, becoming the first Turkish citizen to win a Nobel Prize.',
  },
  {
    id: 'lit_03',
    text: 'Which Shakespeare play features the characters Hamlet, Ophelia and Horatio?',
    text_tr: 'Hamlet, Ophelia ve Horatio karakterlerinin yer aldığı Shakespeare oyunu hangisidir?',
    options: { A: 'Macbeth', B: 'Othello', C: 'King Lear', D: 'Hamlet', E: 'The Tempest' },
    options_tr: { A: 'Macbeth', B: 'Othello', C: 'Kral Lear', D: 'Hamlet', E: 'Fırtına' },
    answer: 'D',
    explanation: 'Hamlet (c. 1600–1601) is one of Shakespeare\'s greatest tragedies, featuring the Danish prince Hamlet seeking revenge for his father\'s murder.',
  },
  {
    id: 'lit_04',
    text: 'Who wrote "1984," the dystopian novel set in Oceania?',
    text_tr: 'Oceania\'da geçen distopik roman "1984"ü kim yazmıştır?',
    options: { A: 'Aldous Huxley', B: 'Ray Bradbury', C: 'Philip K. Dick', D: 'George Orwell', E: 'H.G. Wells' },
    options_tr: { A: 'Aldous Huxley', B: 'Ray Bradbury', C: 'Philip K. Dick', D: 'George Orwell', E: 'H.G. Wells' },
    answer: 'D',
    explanation: 'George Orwell (Eric Arthur Blair) wrote Nineteen Eighty-Four in 1949, introducing concepts like "Big Brother" and "doublethink."',
  },
  {
    id: 'lit_05',
    text: 'The character "Raskolnikov" appears in which classic Russian novel?',
    text_tr: '"Raskolnikov" karakteri hangi klasik Rus romanında yer alır?',
    options: { A: 'War and Peace', B: 'Anna Karenina', C: 'Crime and Punishment', D: 'The Brothers Karamazov', E: 'The Idiot' },
    options_tr: { A: 'Savaş ve Barış', B: 'Anna Karenina', C: 'Suç ve Ceza', D: 'Karamazov Kardeşler', E: 'Budala' },
    answer: 'C',
    explanation: 'Rodion Raskolnikov is the protagonist of Fyodor Dostoevsky\'s Crime and Punishment (1866).',
  },
  {
    id: 'lit_06',
    text: 'Who wrote the epic poem "The Odyssey"?',
    text_tr: '"Odysseia" destanını kim yazmıştır?',
    options: { A: 'Homer', B: 'Virgil', C: 'Sophocles', D: 'Hesiod', E: 'Euripides' },
    options_tr: { A: 'Homeros', B: 'Vergilius', C: 'Sophokles', D: 'Hesiodos', E: 'Euripides' },
    answer: 'A',
    explanation: 'The Odyssey, attributed to Homer, follows Odysseus\'s ten-year journey home after the Trojan War.',
  },
  {
    id: 'lit_07',
    text: 'Which novel by Jane Austen begins with the line "It is a truth universally acknowledged..."?',
    text_tr: '"Herkesçe kabul edilen bir gerçektir ki..." cümlesiyle başlayan Jane Austen romanı hangisidir?',
    options: { A: 'Sense and Sensibility', B: 'Emma', C: 'Pride and Prejudice', D: 'Persuasion', E: 'Mansfield Park' },
    options_tr: { A: 'Sağduyu ve Duyarlılık', B: 'Emma', C: 'Gurur ve Önyargı', D: 'İkna', E: 'Mansfield Parkı' },
    answer: 'C',
    explanation: 'Pride and Prejudice (1813) opens with this famous line about a single man in possession of a good fortune.',
  },
  {
    id: 'lit_08',
    text: 'Who wrote "One Hundred Years of Solitude," a landmark of magical realism?',
    text_tr: 'Büyülü gerçekçiliğin dönüm noktası olan "Yüzyıllık Yalnızlık"ı kim yazmıştır?',
    options: { A: 'Jorge Luis Borges', B: 'Mario Vargas Llosa', C: 'Gabriel García Márquez', D: 'Pablo Neruda', E: 'Isabel Allende' },
    options_tr: { A: 'Jorge Luis Borges', B: 'Mario Vargas Llosa', C: 'Gabriel García Márquez', D: 'Pablo Neruda', E: 'Isabel Allende' },
    answer: 'C',
    explanation: 'Gabriel García Márquez published One Hundred Years of Solitude in 1967, a cornerstone of magical realism.',
  },
  {
    id: 'lit_09',
    text: 'Which epic Turkish/Central Asian literary work centers on the hero Manas?',
    text_tr: 'Kahraman Manas\'ı merkeze alan destansı Türk/Orta Asya edebi eseri hangisidir?',
    options: { A: 'The Book of Dede Korkut', B: 'Manas Epic', C: 'Oğuzname', D: 'Şehname', E: 'Kutadgu Bilig' },
    options_tr: { A: 'Dede Korkut Kitabı', B: 'Manas Destanı', C: 'Oğuzname', D: 'Şehname', E: 'Kutadgu Bilig' },
    answer: 'B',
    explanation: 'The Manas Epic is a traditional Kyrgyz epic poem, one of the longest epic poems in world literature.',
  },
  {
    id: 'lit_10',
    text: 'Who wrote "Moby-Dick," the novel about the whale hunt led by Captain Ahab?',
    text_tr: 'Kaptan Ahab liderliğindeki balina avını konu alan "Moby-Dick" romanını kim yazmıştır?',
    options: { A: 'Nathaniel Hawthorne', B: 'Herman Melville', C: 'Mark Twain', D: 'Edgar Allan Poe', E: 'Washington Irving' },
    options_tr: { A: 'Nathaniel Hawthorne', B: 'Herman Melville', C: 'Mark Twain', D: 'Edgar Allan Poe', E: 'Washington Irving' },
    answer: 'B',
    explanation: 'Herman Melville published Moby-Dick in 1851; it is now considered a masterpiece of American literature.',
  },
  {
    id: 'lit_11',
    text: 'Which Turkish novelist wrote "İnce Memed" (Memed, My Hawk)?',
    text_tr: '"İnce Memed" romanını hangi Türk yazar kaleme almıştır?',
    options: { A: 'Orhan Kemal', B: 'Yaşar Kemal', C: 'Kemal Tahir', D: 'Aziz Nesin', E: 'Reşat Nuri Güntekin' },
    options_tr: { A: 'Orhan Kemal', B: 'Yaşar Kemal', C: 'Kemal Tahir', D: 'Aziz Nesin', E: 'Reşat Nuri Güntekin' },
    answer: 'B',
    explanation: 'Yaşar Kemal published İnce Memed in 1955, a novel about a young bandit in rural Anatolia.',
  },
  {
    id: 'lit_12',
    text: 'Who wrote "War and Peace"?',
    text_tr: '"Savaş ve Barış" romanını kim yazmıştır?',
    options: { A: 'Fyodor Dostoevsky', B: 'Anton Chekhov', C: 'Leo Tolstoy', D: 'Ivan Turgenev', E: 'Nikolai Gogol' },
    options_tr: { A: 'Fyodor Dostoyevski', B: 'Anton Çehov', C: 'Lev Tolstoy', D: 'İvan Turgenyev', E: 'Nikolay Gogol' },
    answer: 'C',
    explanation: 'Leo Tolstoy\'s War and Peace (1869) is set during the Napoleonic Wars and is one of the longest major novels ever written.',
  },
  {
    id: 'lit_13',
    text: 'Which Gothic novel, published in 1818, tells the story of a scientist who creates a living creature?',
    text_tr: '1818\'de yayımlanan ve canlı bir yaratık yaratan bir bilim insanının hikayesini anlatan Gotik roman hangisidir?',
    options: { A: 'Dracula', B: 'Frankenstein', C: 'The Picture of Dorian Gray', D: 'The Castle of Otranto', E: 'Wuthering Heights' },
    options_tr: { A: 'Drakula', B: 'Frankenstein', C: 'Dorian Gray\'in Portresi', D: 'Otranto Şatosu', E: 'Uğultulu Tepeler' },
    answer: 'B',
    explanation: 'Mary Shelley wrote Frankenstein; or, The Modern Prometheus in 1818, often cited as an early work of science fiction.',
  },
  {
    id: 'lit_14',
    text: 'Which Turkish poet wrote the national anthem "İstiklal Marşı"?',
    text_tr: '"İstiklal Marşı"nı hangi Türk şair yazmıştır?',
    options: { A: 'Necip Fazıl Kısakürek', B: 'Mehmet Akif Ersoy', C: 'Yahya Kemal Beyatlı', D: 'Nazım Hikmet', E: 'Orhan Veli Kanık' },
    options_tr: { A: 'Necip Fazıl Kısakürek', B: 'Mehmet Akif Ersoy', C: 'Yahya Kemal Beyatlı', D: 'Nazım Hikmet', E: 'Orhan Veli Kanık' },
    answer: 'B',
    explanation: 'Mehmet Akif Ersoy wrote the İstiklal Marşı (Independence March), adopted as Turkey\'s national anthem in 1921.',
  },
  {
    id: 'lit_15',
    text: 'Who wrote "The Divine Comedy," describing a journey through Hell, Purgatory, and Paradise?',
    text_tr: 'Cehennem, Araf ve Cennet\'ten geçen bir yolculuğu anlatan "İlahi Komedya"yı kim yazmıştır?',
    options: { A: 'Petrarch', B: 'Giovanni Boccaccio', C: 'Dante Alighieri', D: 'Torquato Tasso', E: 'Ludovico Ariosto' },
    options_tr: { A: 'Petrarca', B: 'Giovanni Boccaccio', C: 'Dante Alighieri', D: 'Torquato Tasso', E: 'Ludovico Ariosto' },
    answer: 'C',
    explanation: 'Dante Alighieri wrote The Divine Comedy in the early 14th century, a foundational work of Italian literature.',
  },
  {
    id: 'lit_16',
    text: 'Which novel by Victor Hugo follows the ex-convict Jean Valjean?',
    text_tr: 'Eski hükümlü Jean Valjean\'ı konu alan Victor Hugo romanı hangisidir?',
    options: { A: 'The Hunchback of Notre-Dame', B: 'Les Misérables', C: 'Toilers of the Sea', D: 'Ninety-Three', E: 'The Man Who Laughs' },
    options_tr: { A: 'Notre Dame\'ın Kamburu', B: 'Sefiller', C: 'Deniz İşçileri', D: 'Doksanüç', E: 'Gülen Adam' },
    answer: 'B',
    explanation: 'Les Misérables (1862) follows Jean Valjean\'s redemption across decades of 19th-century France.',
  },
  {
    id: 'lit_17',
    text: 'Which Turkish author wrote the novel "Kürk Mantolu Madonna" (Madonna in a Fur Coat)?',
    text_tr: '"Kürk Mantolu Madonna" romanını hangi Türk yazar yazmıştır?',
    options: { A: 'Ahmet Hamdi Tanpınar', B: 'Sabahattin Ali', C: 'Halide Edip Adıvar', D: 'Peyami Safa', E: 'Reşat Nuri Güntekin' },
    options_tr: { A: 'Ahmet Hamdi Tanpınar', B: 'Sabahattin Ali', C: 'Halide Edip Adıvar', D: 'Peyami Safa', E: 'Reşat Nuri Güntekin' },
    answer: 'B',
    explanation: 'Sabahattin Ali published Kürk Mantolu Madonna in 1943; it became a bestseller decades after his death.',
  },
  {
    id: 'lit_18',
    text: 'Who wrote "Pride and Prejudice," "Emma," and "Sense and Sensibility"?',
    text_tr: '"Gurur ve Önyargı", "Emma" ve "Sağduyu ve Duyarlılık" adlı eserleri kim yazmıştır?',
    options: { A: 'Charlotte Brontë', B: 'Jane Austen', C: 'George Eliot', D: 'Elizabeth Gaskell', E: 'Virginia Woolf' },
    options_tr: { A: 'Charlotte Brontë', B: 'Jane Austen', C: 'George Eliot', D: 'Elizabeth Gaskell', E: 'Virginia Woolf' },
    answer: 'B',
    explanation: 'Jane Austen (1775–1817) wrote these novels of manners set in Regency-era England.',
  },
  {
    id: 'lit_19',
    text: 'Which Franz Kafka novella begins with a man waking up transformed into an insect?',
    text_tr: 'Bir adamın böceğe dönüşmüş halde uyanmasıyla başlayan Franz Kafka novellası hangisidir?',
    options: { A: 'The Trial', B: 'The Castle', C: 'The Metamorphosis', D: 'Amerika', E: 'A Hunger Artist' },
    options_tr: { A: 'Dava', B: 'Şato', C: 'Dönüşüm', D: 'Amerika', E: 'Bir Açlık Sanatçısı' },
    answer: 'C',
    explanation: 'The Metamorphosis (1915) opens with Gregor Samsa waking up transformed into a giant insect.',
  },
  {
    id: 'lit_20',
    text: 'Which Turkish author wrote "Çalıkuşu" (The Wren), a beloved novel about a young teacher?',
    text_tr: 'Genç bir öğretmeni konu alan sevilen roman "Çalıkuşu"nu hangi Türk yazar yazmıştır?',
    options: { A: 'Reşat Nuri Güntekin', B: 'Halide Edip Adıvar', C: 'Yakup Kadri Karaosmanoğlu', D: 'Ömer Seyfettin', E: 'Refik Halid Karay' },
    options_tr: { A: 'Reşat Nuri Güntekin', B: 'Halide Edip Adıvar', C: 'Yakup Kadri Karaosmanoğlu', D: 'Ömer Seyfettin', E: 'Refik Halid Karay' },
    answer: 'A',
    explanation: 'Reşat Nuri Güntekin published Çalıkuşu in 1922, one of the most beloved novels in Turkish literature.',
  },
  {
    id: 'lit_21',
    text: 'Who wrote "The Great Gatsby," set during the Jazz Age?',
    text_tr: 'Caz Çağı\'nda geçen "Muhteşem Gatsby"yi kim yazmıştır?',
    options: { A: 'Ernest Hemingway', B: 'F. Scott Fitzgerald', C: 'William Faulkner', D: 'John Steinbeck', E: 'Sinclair Lewis' },
    options_tr: { A: 'Ernest Hemingway', B: 'F. Scott Fitzgerald', C: 'William Faulkner', D: 'John Steinbeck', E: 'Sinclair Lewis' },
    answer: 'B',
    explanation: 'F. Scott Fitzgerald published The Great Gatsby in 1925, a defining novel of the American Jazz Age.',
  },
  {
    id: 'lit_22',
    text: 'Which ancient Greek poet is credited with writing both "The Iliad" and "The Odyssey"?',
    text_tr: 'Hem "İlyada" hem de "Odysseia"yı yazdığına inanılan antik Yunan şair kimdir?',
    options: { A: 'Hesiod', B: 'Pindar', C: 'Homer', D: 'Sappho', E: 'Aeschylus' },
    options_tr: { A: 'Hesiodos', B: 'Pindaros', C: 'Homeros', D: 'Sappho', E: 'Aiskhylos' },
    answer: 'C',
    explanation: 'Homer is traditionally credited as the author of these two foundational epics of ancient Greek literature.',
  },
  {
    id: 'lit_23',
    text: 'Which Turkish poet is famous for the collection "Simavne Kadısı Oğlu Şeyh Bedreddin" (based on the historical Şeyh Bedreddin)?',
    text_tr: '"Simavne Kadısı Oğlu Şeyh Bedreddin Destanı" adlı eseriyle tanınan Türk şair kimdir?',
    options: { A: 'Nazım Hikmet', B: 'Fazıl Hüsnü Dağlarca', C: 'Cahit Sıtkı Tarancı', D: 'Ahmed Arif', E: 'Attila İlhan' },
    options_tr: { A: 'Nazım Hikmet', B: 'Fazıl Hüsnü Dağlarca', C: 'Cahit Sıtkı Tarancı', D: 'Ahmed Arif', E: 'Attila İlhan' },
    answer: 'A',
    explanation: 'Nazım Hikmet wrote this epic poem in 1936 about the 15th-century rebel sheikh Bedreddin.',
  },
  {
    id: 'lit_24',
    text: 'Who wrote "To Kill a Mockingbird," narrated by young Scout Finch?',
    text_tr: 'Genç Scout Finch tarafından anlatılan "Bülbülü Öldürmek"i kim yazmıştır?',
    options: { A: 'Harper Lee', B: 'Toni Morrison', C: 'Flannery O\'Connor', D: 'Carson McCullers', E: 'Eudora Welty' },
    options_tr: { A: 'Harper Lee', B: 'Toni Morrison', C: 'Flannery O\'Connor', D: 'Carson McCullers', E: 'Eudora Welty' },
    answer: 'A',
    explanation: 'Harper Lee published To Kill a Mockingbird in 1960; it won the Pulitzer Prize for Fiction in 1961.',
  },
  {
    id: 'lit_25',
    text: 'Which epic Persian poem by Ferdowsi chronicles the mythical and historical past of the Persian Empire?',
    text_tr: 'Firdevsi\'nin İran İmparatorluğu\'nun mitolojik ve tarihi geçmişini anlatan destansı Fars şiiri hangisidir?',
    options: { A: 'Rubaiyat', B: 'Shahnameh (Şehname)', C: 'Gulistan', D: 'Masnavi', E: 'Bustan' },
    options_tr: { A: 'Rubailer', B: 'Şehname', C: 'Gülistan', D: 'Mesnevi', E: 'Bustan' },
    answer: 'B',
    explanation: 'The Shahnameh ("Book of Kings"), completed around 1010 AD, is one of the longest epic poems in world literature.',
  },
  {
    id: 'lit_26',
    text: 'Which Turkish author wrote "Huzur" (A Mind at Peace), a novel exploring Istanbul society in the 1930s?',
    text_tr: '1930\'lu yıllarda İstanbul toplumunu inceleyen "Huzur" romanını hangi Türk yazar yazmıştır?',
    options: { A: 'Ahmet Hamdi Tanpınar', B: 'Peyami Safa', C: 'Oğuz Atay', D: 'Yusuf Atılgan', E: 'Adalet Ağaoğlu' },
    options_tr: { A: 'Ahmet Hamdi Tanpınar', B: 'Peyami Safa', C: 'Oğuz Atay', D: 'Yusuf Atılgan', E: 'Adalet Ağaoğlu' },
    answer: 'A',
    explanation: 'Ahmet Hamdi Tanpınar published Huzur in 1949, a landmark of Turkish modernist literature.',
  },
  {
    id: 'lit_27',
    text: 'Who wrote "The Old Man and the Sea," about a fisherman battling a giant marlin?',
    text_tr: 'Dev bir kılıçbalığıyla mücadele eden bir balıkçıyı konu alan "İhtiyar Balıkçı"yı kim yazmıştır?',
    options: { A: 'John Steinbeck', B: 'Ernest Hemingway', C: 'William Faulkner', D: 'Jack London', E: 'Herman Melville' },
    options_tr: { A: 'John Steinbeck', B: 'Ernest Hemingway', C: 'William Faulkner', D: 'Jack London', E: 'Herman Melville' },
    answer: 'B',
    explanation: 'Ernest Hemingway published The Old Man and the Sea in 1952; it contributed to his 1954 Nobel Prize in Literature.',
  },
  {
    id: 'lit_28',
    text: 'Which novel by Fyodor Dostoevsky centers on the three Karamazov brothers and the murder of their father?',
    text_tr: 'Üç Karamazov kardeş ve babalarının öldürülmesini konu alan Fyodor Dostoyevski romanı hangisidir?',
    options: { A: 'The Idiot', B: 'Demons', C: 'The Brothers Karamazov', D: 'Notes from Underground', E: 'The Gambler' },
    options_tr: { A: 'Budala', B: 'Cinler', C: 'Karamazov Kardeşler', D: 'Yeraltından Notlar', E: 'Kumarbaz' },
    answer: 'C',
    explanation: 'The Brothers Karamazov (1880) was Dostoevsky\'s final novel, exploring faith, doubt, and morality.',
  },
  {
    id: 'lit_29',
    text: 'Which Turkish poet is known for the line "Yaşamak bir ağaç gibi tek ve hür..." from the poem "Davet"?',
    text_tr: '"Davet" şiirindeki "Yaşamak bir ağaç gibi tek ve hür..." dizesiyle tanınan Türk şair kimdir?',
    options: { A: 'Orhan Veli Kanık', B: 'Nazım Hikmet', C: 'Cemal Süreya', D: 'Turgut Uyar', E: 'İlhan Berk' },
    options_tr: { A: 'Orhan Veli Kanık', B: 'Nazım Hikmet', C: 'Cemal Süreya', D: 'Turgut Uyar', E: 'İlhan Berk' },
    answer: 'B',
    explanation: 'The line is from Nazım Hikmet\'s poem "Davet," part of his famous "İnsan Manzaraları" era of work.',
  },
  {
    id: 'lit_30',
    text: 'Who wrote "Don Juan," a satirical epic poem, and "Childe Harold\'s Pilgrimage"?',
    text_tr: 'Hicivli destansı şiir "Don Juan" ve "Childe Harold\'un Hac Yolculuğu"nu kim yazmıştır?',
    options: { A: 'Percy Bysshe Shelley', B: 'John Keats', C: 'Lord Byron', D: 'William Wordsworth', E: 'Samuel Taylor Coleridge' },
    options_tr: { A: 'Percy Bysshe Shelley', B: 'John Keats', C: 'Lord Byron', D: 'William Wordsworth', E: 'Samuel Taylor Coleridge' },
    answer: 'C',
    explanation: 'Lord Byron, a leading figure of the Romantic movement, wrote both of these celebrated works.',
  },
  {
    id: 'lit_31',
    text: 'Which novel by Emily Brontë tells the tormented love story of Heathcliff and Catherine?',
    text_tr: 'Heathcliff ile Catherine\'in ıstıraplı aşk hikayesini anlatan Emily Brontë romanı hangisidir?',
    options: { A: 'Jane Eyre', B: 'Wuthering Heights', C: 'Agnes Grey', D: 'The Tenant of Wildfell Hall', E: 'Villette' },
    options_tr: { A: 'Jane Eyre', B: 'Uğultulu Tepeler', C: 'Agnes Grey', D: 'Wildfell Malikanesi\'nin Kiracısı', E: 'Villette' },
    answer: 'B',
    explanation: 'Wuthering Heights (1847) is Emily Brontë\'s only novel, set on the Yorkshire moors.',
  },
  {
    id: 'lit_32',
    text: 'Which Turkish writer authored "Tutunamayanlar" (The Disconnected), considered a landmark postmodern novel?',
    text_tr: 'Postmodern edebiyatın önemli bir eseri sayılan "Tutunamayanlar"ı hangi Türk yazar kaleme almıştır?',
    options: { A: 'Oğuz Atay', B: 'Orhan Pamuk', C: 'Bilge Karasu', D: 'Yusuf Atılgan', E: 'Latife Tekin' },
    options_tr: { A: 'Oğuz Atay', B: 'Orhan Pamuk', C: 'Bilge Karasu', D: 'Yusuf Atılgan', E: 'Latife Tekin' },
    answer: 'A',
    explanation: 'Oğuz Atay published Tutunamayanlar in 1972; it is now regarded as a landmark of Turkish literature.',
  },
  {
    id: 'lit_33',
    text: 'Who wrote "The Canterbury Tales," a collection of stories told by pilgrims?',
    text_tr: 'Hacılar tarafından anlatılan hikayelerden oluşan "Canterbury Hikayeleri"ni kim yazmıştır?',
    options: { A: 'William Langland', B: 'Geoffrey Chaucer', C: 'John Gower', D: 'Thomas Malory', E: 'Sir Thomas More' },
    options_tr: { A: 'William Langland', B: 'Geoffrey Chaucer', C: 'John Gower', D: 'Thomas Malory', E: 'Sir Thomas More' },
    answer: 'B',
    explanation: 'Geoffrey Chaucer wrote The Canterbury Tales in the late 14th century, largely in Middle English.',
  },
  {
    id: 'lit_34',
    text: 'Which novel by Leo Tolstoy follows Anna\'s tragic affair with Count Vronsky?',
    text_tr: 'Anna\'nın Kont Vronski ile olan trajik ilişkisini konu alan Lev Tolstoy romanı hangisidir?',
    options: { A: 'War and Peace', B: 'Anna Karenina', C: 'Resurrection', D: 'The Death of Ivan Ilyich', E: 'The Kreutzer Sonata' },
    options_tr: { A: 'Savaş ve Barış', B: 'Anna Karenina', C: 'Diriliş', D: 'İvan İlyiç\'in Ölümü', E: 'Kreutzer Sonat' },
    answer: 'B',
    explanation: 'Anna Karenina (1877) opens with the famous line about happy and unhappy families.',
  },
  {
    id: 'lit_35',
    text: 'Which Turkish poet wrote "Otuz Beş Yaş" (Age Thirty-Five), reflecting on the middle of life?',
    text_tr: 'Yaşamın ortasını düşünen "Otuz Beş Yaş" şiirini hangi Türk şair yazmıştır?',
    options: { A: 'Cahit Sıtkı Tarancı', B: 'Necip Fazıl Kısakürek', C: 'Ahmet Muhip Dıranas', D: 'Behçet Necatigil', E: 'Fazıl Hüsnü Dağlarca' },
    options_tr: { A: 'Cahit Sıtkı Tarancı', B: 'Necip Fazıl Kısakürek', C: 'Ahmet Muhip Dıranas', D: 'Behçet Necatigil', E: 'Fazıl Hüsnü Dağlarca' },
    answer: 'A',
    explanation: 'Cahit Sıtkı Tarancı\'s "Otuz Beş Yaş" (1946) is one of the most quoted poems in Turkish literature, opening with "Yaş otuz beş! Yolun yarısı eder."',
  },
  {
    id: 'lit_36',
    text: 'Who wrote "Crime and Punishment," featuring the impoverished student Raskolnikov?',
    text_tr: 'Yoksul öğrenci Raskolnikov\'u konu alan "Suç ve Ceza"yı kim yazmıştır?',
    options: { A: 'Leo Tolstoy', B: 'Fyodor Dostoevsky', C: 'Ivan Turgenev', D: 'Nikolai Gogol', E: 'Anton Chekhov' },
    options_tr: { A: 'Lev Tolstoy', B: 'Fyodor Dostoyevski', C: 'İvan Turgenyev', D: 'Nikolay Gogol', E: 'Anton Çehov' },
    answer: 'B',
    explanation: 'Fyodor Dostoevsky published Crime and Punishment in 1866, exploring guilt and redemption.',
  },
  {
    id: 'lit_37',
    text: 'Which epic poem by Virgil tells the story of Aeneas fleeing Troy to found Rome?',
    text_tr: 'Truva\'dan kaçıp Roma\'yı kuran Aeneas\'ı anlatan Vergilius destanı hangisidir?',
    options: { A: 'The Aeneid', B: 'Metamorphoses', C: 'The Georgics', D: 'The Eclogues', E: 'Pharsalia' },
    options_tr: { A: 'Aeneis', B: 'Dönüşümler', C: 'Georgica', D: 'Bucolica', E: 'Pharsalia' },
    answer: 'A',
    explanation: 'Virgil\'s Aeneid, written in the 1st century BC, is a Latin epic that became Rome\'s national epic.',
  },
  {
    id: 'lit_38',
    text: 'Which Turkish author wrote satirical short stories and is known for characters like "Hafize Ana"?',
    text_tr: 'Hicivli hikayeler yazan ve "Hafize Ana" gibi karakterleriyle tanınan Türk yazar kimdir?',
    options: { A: 'Aziz Nesin', B: 'Rıfat Ilgaz', C: 'Muzaffer İzgü', D: 'Haldun Taner', E: 'Sait Faik Abasıyanık' },
    options_tr: { A: 'Aziz Nesin', B: 'Rıfat Ilgaz', C: 'Muzaffer İzgü', D: 'Haldun Taner', E: 'Sait Faik Abasıyanık' },
    answer: 'A',
    explanation: 'Aziz Nesin was a prolific satirist widely known for humorous social commentary in Turkish literature.',
  },
  {
    id: 'lit_39',
    text: 'Who wrote the play "Life Is a Dream," a landmark of Spanish Golden Age drama?',
    text_tr: '"Hayat Bir Rüyadır" oyununu kim yazmıştır?',
    options: { A: 'Lope de Vega', B: 'Pedro Calderón de la Barca', C: 'Tirso de Molina', D: 'Miguel de Cervantes', E: 'Francisco de Quevedo' },
    options_tr: { A: 'Lope de Vega', B: 'Pedro Calderón de la Barca', C: 'Tirso de Molina', D: 'Miguel de Cervantes', E: 'Francisco de Quevedo' },
    answer: 'B',
    explanation: 'Pedro Calderón de la Barca wrote "La vida es sueño" (Life Is a Dream) in 1635, a landmark of Spanish Golden Age drama.',
  },
  {
    id: 'lit_40',
    text: 'Which Turkish novel by Reşat Nuri Güntekin follows a village teacher named Şahin?',
    text_tr: 'Reşat Nuri Güntekin\'in Şahin adlı bir köy öğretmenini konu alan romanı hangisidir?',
    options: { A: 'Yeşil Gece', B: 'Acımak', C: 'Dudaktan Kalbe', D: 'Kızılcık Dalları', E: 'Miskinler Tekkesi' },
    options_tr: { A: 'Yeşil Gece', B: 'Acımak', C: 'Dudaktan Kalbe', D: 'Kızılcık Dalları', E: 'Miskinler Tekkesi' },
    answer: 'A',
    explanation: 'Yeşil Gece (1928) is one of Güntekin\'s notable novels dealing with rural education and social change.',
  },
  {
    id: 'lit_41',
    text: 'Who wrote "The Adventures of Huckleberry Finn"?',
    text_tr: '"Huckleberry Finn\'in Maceraları"nı kim yazmıştır?',
    options: { A: 'Mark Twain', B: 'Nathaniel Hawthorne', C: 'Herman Melville', D: 'Washington Irving', E: 'Bret Harte' },
    options_tr: { A: 'Mark Twain', B: 'Nathaniel Hawthorne', C: 'Herman Melville', D: 'Washington Irving', E: 'Bret Harte' },
    answer: 'A',
    explanation: 'Mark Twain (Samuel Clemens) published this novel in 1884, often called the "Great American Novel."',
  },
  {
    id: 'lit_42',
    text: 'Which classical Persian poet is famous for the collection of quatrains known as "Rubaiyat"?',
    text_tr: '"Rubailer" olarak bilinen dörtlük koleksiyonuyla ünlü klasik Fars şair kimdir?',
    options: { A: 'Rumi', B: 'Hafez', C: 'Omar Khayyam', D: 'Saadi', E: 'Ferdowsi' },
    options_tr: { A: 'Mevlana', B: 'Hafız', C: 'Ömer Hayyam', D: 'Sadi', E: 'Firdevsi' },
    answer: 'C',
    explanation: 'Omar Khayyam\'s Rubaiyat, a collection of quatrains, was popularized in the West by Edward FitzGerald\'s translation.',
  },
  {
    id: 'lit_43',
    text: 'Which mystical Sufi poet, born in Balkh, wrote the "Masnavi" and is buried in Konya?',
    text_tr: 'Belh\'te doğan, "Mesnevi"yi yazan ve Konya\'da gömülü olan tasavvufi şair kimdir?',
    options: { A: 'Yunus Emre', B: 'Rumi (Mevlana Celaleddin)', C: 'Hacı Bektaş Veli', D: 'Ahmed Yesevi', E: 'Şeyh Galib' },
    options_tr: { A: 'Yunus Emre', B: 'Mevlana Celaleddin Rumi', C: 'Hacı Bektaş Veli', D: 'Ahmed Yesevi', E: 'Şeyh Galib' },
    answer: 'B',
    explanation: 'Rumi (1207–1273) wrote the Masnavi, a major work of Sufi mystical poetry, and is buried in Konya, Turkey.',
  },
  {
    id: 'lit_44',
    text: 'Who wrote "Little Women," following the March sisters?',
    text_tr: 'March kardeşleri konu alan "Küçük Kadınlar"ı kim yazmıştır?',
    options: { A: 'Louisa May Alcott', B: 'Edith Wharton', C: 'Kate Chopin', D: 'Willa Cather', E: 'Harriet Beecher Stowe' },
    options_tr: { A: 'Louisa May Alcott', B: 'Edith Wharton', C: 'Kate Chopin', D: 'Willa Cather', E: 'Harriet Beecher Stowe' },
    answer: 'A',
    explanation: 'Louisa May Alcott published Little Women in 1868–69, following the lives of the four March sisters.',
  },
  {
    id: 'lit_45',
    text: 'Which Turkish poet, a leading figure of the "Yedi Meşaleciler" (Seven Torchbearers) movement, is known for lyrical poems like "Fahriye Abla"?',
    text_tr: '"Yedi Meşaleciler" akımının önde gelen isimlerinden ve "Fahriye Abla" gibi lirik şiirleriyle tanınan Türk şair kimdir?',
    options: { A: 'Ahmet Muhip Dıranas', B: 'Ziya Osman Saba', C: 'Yaşar Nabi Nayır', D: 'Cevdet Kudret', E: 'Sabri Esat Siyavuşgil' },
    options_tr: { A: 'Ahmet Muhip Dıranas', B: 'Ziya Osman Saba', C: 'Yaşar Nabi Nayır', D: 'Cevdet Kudret', E: 'Sabri Esat Siyavuşgil' },
    answer: 'A',
    explanation: 'Ahmet Muhip Dıranas is celebrated for "Fahriye Abla," one of the most beloved lyric poems in Turkish literature.',
  },
  {
    id: 'lit_46',
    text: 'Who wrote "The Picture of Dorian Gray," a novel about a man who never ages while his portrait bears the marks of sin?',
    text_tr: 'Kendisi hiç yaşlanmazken portresinin günahların izlerini taşıdığı bir adamı anlatan "Dorian Gray\'in Portresi"ni kim yazmıştır?',
    options: { A: 'Arthur Conan Doyle', B: 'Oscar Wilde', C: 'Bram Stoker', D: 'Robert Louis Stevenson', E: 'H.G. Wells' },
    options_tr: { A: 'Arthur Conan Doyle', B: 'Oscar Wilde', C: 'Bram Stoker', D: 'Robert Louis Stevenson', E: 'H.G. Wells' },
    answer: 'B',
    explanation: 'Oscar Wilde published The Picture of Dorian Gray in 1890, his only novel.',
  },
  {
    id: 'lit_47',
    text: 'Which Turkish author wrote "Aylak Adam" (The Idle Man), a key existentialist novel of Turkish literature?',
    text_tr: 'Türk edebiyatının varoluşçu önemli eserlerinden "Aylak Adam"ı hangi yazar kaleme almıştır?',
    options: { A: 'Yusuf Atılgan', B: 'Bilge Karasu', C: 'Vüs\'at O. Bener', D: 'Demir Özlü', E: 'Ferit Edgü' },
    options_tr: { A: 'Yusuf Atılgan', B: 'Bilge Karasu', C: 'Vüs\'at O. Bener', D: 'Demir Özlü', E: 'Ferit Edgü' },
    answer: 'A',
    explanation: 'Yusuf Atılgan published Aylak Adam in 1959, exploring alienation in Turkish urban life.',
  },
  {
    id: 'lit_48',
    text: 'Who wrote the play "A Doll\'s House," about Nora Helmer\'s awakening within a stifling marriage?',
    text_tr: 'Nora Helmer\'in boğucu bir evlilikte uyanışını anlatan "Bir Bebek Evi" oyununu kim yazmıştır?',
    options: { A: 'August Strindberg', B: 'Henrik Ibsen', C: 'Anton Chekhov', D: 'George Bernard Shaw', E: 'Oscar Wilde' },
    options_tr: { A: 'August Strindberg', B: 'Henrik Ibsen', C: 'Anton Çehov', D: 'George Bernard Shaw', E: 'Oscar Wilde' },
    answer: 'B',
    explanation: 'Henrik Ibsen wrote A Doll\'s House in 1879, a landmark of realist drama and early feminist literature.',
  },
  {
    id: 'lit_49',
    text: 'Which novel by John Steinbeck follows the Joad family fleeing the Dust Bowl to California?',
    text_tr: 'Toz Kasesi\'nden Kaliforniya\'ya kaçan Joad ailesini konu alan John Steinbeck romanı hangisidir?',
    options: { A: 'Of Mice and Men', B: 'East of Eden', C: 'The Grapes of Wrath', D: 'Cannery Row', E: 'Tortilla Flat' },
    options_tr: { A: 'Fareler ve İnsanlar', B: 'Cennetin Doğusu', C: 'Gazap Üzümleri', D: 'Konserve Sokağı', E: 'Tortilla Flat' },
    answer: 'C',
    explanation: 'The Grapes of Wrath (1939) won the Pulitzer Prize and depicted Great Depression-era hardship.',
  },
  {
    id: 'lit_50',
    text: 'Which Turkish poet wrote "Yunus Emre Divanı," blending mystical love with plain, accessible language in the 13th–14th centuries?',
    text_tr: '13.-14. yüzyıllarda tasavvufi aşkı sade ve anlaşılır bir dille harmanlayan "Yunus Emre Divanı"nı kim yazmıştır?',
    options: { A: 'Hacı Bayram-ı Veli', B: 'Yunus Emre', C: 'Aşık Paşa', D: 'Kaygusuz Abdal', E: 'Pir Sultan Abdal' },
    options_tr: { A: 'Hacı Bayram-ı Veli', B: 'Yunus Emre', C: 'Aşık Paşa', D: 'Kaygusuz Abdal', E: 'Pir Sultan Abdal' },
    answer: 'B',
    explanation: 'Yunus Emre is one of the most beloved figures in Turkish literature, writing accessible Sufi poetry in vernacular Turkish.',
  },
  {
    id: 'lit_51',
    text: 'Who wrote "Ulysses," a modernist novel set over a single day in Dublin?',
    text_tr: 'Dublin\'de tek bir gün içinde geçen modernist roman "Ulysses"i kim yazmıştır?',
    options: { A: 'Samuel Beckett', B: 'James Joyce', C: 'W.B. Yeats', D: 'Flann O\'Brien', E: 'Sean O\'Casey' },
    options_tr: { A: 'Samuel Beckett', B: 'James Joyce', C: 'W.B. Yeats', D: 'Flann O\'Brien', E: 'Sean O\'Casey' },
    answer: 'B',
    explanation: 'James Joyce published Ulysses in 1922, structured to parallel Homer\'s Odyssey across one day in Dublin (June 16, 1904).',
  },
  {
    id: 'lit_52',
    text: 'Which Turkish author wrote "Yer Demir Gök Bakır" (Iron Earth, Copper Sky), depicting a harsh Anatolian winter?',
    text_tr: 'Zorlu bir Anadolu kışını anlatan "Yer Demir Gök Bakır"ı hangi Türk yazar yazmıştır?',
    options: { A: 'Yaşar Kemal', B: 'Fakir Baykurt', C: 'Kemal Bilbaşar', D: 'Talip Apaydın', E: 'Mahmut Makal' },
    options_tr: { A: 'Yaşar Kemal', B: 'Fakir Baykurt', C: 'Kemal Bilbaşar', D: 'Talip Apaydın', E: 'Mahmut Makal' },
    answer: 'A',
    explanation: 'Yaşar Kemal published Yer Demir Gök Bakır in 1963, part of his village-life novel cycle.',
  },
  {
    id: 'lit_53',
    text: 'Who wrote "Don Carlos" and "Wilhelm Tell," major works of German drama?',
    text_tr: 'Alman dramasının önemli eserlerinden "Don Carlos" ve "Wilhelm Tell"i kim yazmıştır?',
    options: { A: 'Johann Wolfgang von Goethe', B: 'Friedrich Schiller', C: 'Heinrich Heine', D: 'Gotthold Ephraim Lessing', E: 'Bertolt Brecht' },
    options_tr: { A: 'Johann Wolfgang von Goethe', B: 'Friedrich Schiller', C: 'Heinrich Heine', D: 'Gotthold Ephraim Lessing', E: 'Bertolt Brecht' },
    answer: 'B',
    explanation: 'Friedrich Schiller, along with Goethe, is one of the most important figures of German classical literature.',
  },
  {
    id: 'lit_54',
    text: 'Which novel by Albert Camus explores the absurd through the emotionally detached Meursault?',
    text_tr: 'Duygusal olarak kopuk Meursault üzerinden absürdü inceleyen Albert Camus romanı hangisidir?',
    options: { A: 'The Plague', B: 'The Fall', C: 'The Stranger', D: 'The Myth of Sisyphus', E: 'A Happy Death' },
    options_tr: { A: 'Veba', B: 'Düşüş', C: 'Yabancı', D: 'Sisifos Söyleni', E: 'Mutlu Ölüm' },
    answer: 'C',
    explanation: 'The Stranger (1942) is Camus\'s best-known novel, exploring existentialist and absurdist philosophy.',
  },
  {
    id: 'lit_55',
    text: 'Which Turkish poet and writer authored "Çile" (Suffering), a major collection reflecting his mystical and political worldview?',
    text_tr: 'Mistik ve siyasi dünya görüşünü yansıtan önemli bir şiir koleksiyonu olan "Çile"yi hangi Türk şair yazmıştır?',
    options: { A: 'Necip Fazıl Kısakürek', B: 'Sezai Karakoç', C: 'İsmet Özel', D: 'Nuri Pakdil', E: 'Cahit Zarifoğlu' },
    options_tr: { A: 'Necip Fazıl Kısakürek', B: 'Sezai Karakoç', C: 'İsmet Özel', D: 'Nuri Pakdil', E: 'Cahit Zarifoğlu' },
    answer: 'A',
    explanation: 'Necip Fazıl Kısakürek\'s "Çile" is one of his most significant poetry collections, reflecting his spiritual journey.',
  },
  {
    id: 'lit_56',
    text: 'Who wrote "Beloved," a novel dealing with the trauma of slavery through a ghostly haunting?',
    text_tr: 'Köleliğin travmasını hayaletimsi bir musallat oluş üzerinden ele alan "Sevilen"i kim yazmıştır?',
    options: { A: 'Alice Walker', B: 'Toni Morrison', C: 'Zora Neale Hurston', D: 'Maya Angelou', E: 'Octavia Butler' },
    options_tr: { A: 'Alice Walker', B: 'Toni Morrison', C: 'Zora Neale Hurston', D: 'Maya Angelou', E: 'Octavia Butler' },
    answer: 'B',
    explanation: 'Toni Morrison published Beloved in 1987 and won the Nobel Prize in Literature in 1993.',
  },
  {
    id: 'lit_57',
    text: 'Which Turkish poet is the author of "Garip" (Strange), a manifesto-style collection that revolutionized modern Turkish poetry with plain language?',
    text_tr: 'Sade dille modern Türk şiirinde devrim yaratan manifesto niteliğindeki "Garip" koleksiyonunun yazarı kimdir?',
    options: { A: 'Orhan Veli Kanık', B: 'Oktay Rifat', C: 'Melih Cevdet Anday', D: 'Necati Cumalı', E: 'Ceyhun Atuf Kansu' },
    options_tr: { A: 'Orhan Veli Kanık', B: 'Oktay Rifat', C: 'Melih Cevdet Anday', D: 'Necati Cumalı', E: 'Ceyhun Atuf Kansu' },
    answer: 'A',
    explanation: 'Orhan Veli Kanık, alongside Oktay Rifat and Melih Cevdet Anday, co-founded the "Garip" movement in 1941, though the book itself is most associated with Orhan Veli.',
  },
  {
    id: 'lit_58',
    text: 'Which Gabriel García Márquez novel tells of Florentino Ariza\'s decades-long love for Fermina Daza?',
    text_tr: 'Florentino Ariza\'nın Fermina Daza\'ya olan onlarca yıllık aşkını anlatan Gabriel García Márquez romanı hangisidir?',
    options: { A: 'Love in the Time of Cholera', B: 'The Autumn of the Patriarch', C: 'Chronicle of a Death Foretold', D: 'No One Writes to the Colonel', E: 'The General in His Labyrinth' },
    options_tr: { A: 'Kolera Günlerinde Aşk', B: 'Yaprak Fırtınası', C: 'Kırmızı Pazartesi', D: 'Albaya Mektup Yazan Kimse Yok', E: 'Labirentindeki General' },
    answer: 'A',
    explanation: 'Love in the Time of Cholera (1985) is one of Márquez\'s most celebrated novels.',
  },
  {
    id: 'lit_59',
    text: 'Which Turkish author wrote "Kuyucaklı Yusuf," a novel about social injustice in a small Anatolian town?',
    text_tr: 'Küçük bir Anadolu kasabasındaki sosyal adaletsizliği konu alan "Kuyucaklı Yusuf"u hangi Türk yazar yazmıştır?',
    options: { A: 'Sabahattin Ali', B: 'Orhan Kemal', C: 'Kemal Tahir', D: 'Necati Cumalı', E: 'Samim Kocagöz' },
    options_tr: { A: 'Sabahattin Ali', B: 'Orhan Kemal', C: 'Kemal Tahir', D: 'Necati Cumalı', E: 'Samim Kocagöz' },
    answer: 'A',
    explanation: 'Sabahattin Ali published Kuyucaklı Yusuf in 1937, a socially critical novel of rural Turkey.',
  },
  {
    id: 'lit_60',
    text: 'Who wrote "Brave New World," a dystopia built on genetic engineering and enforced happiness?',
    text_tr: 'Genetik mühendisliği ve zorunlu mutluluk üzerine kurulu bir distopya olan "Cesur Yeni Dünya"yı kim yazmıştır?',
    options: { A: 'George Orwell', B: 'Aldous Huxley', C: 'Ray Bradbury', D: 'Kurt Vonnegut', E: 'Yevgeny Zamyatin' },
    options_tr: { A: 'George Orwell', B: 'Aldous Huxley', C: 'Ray Bradbury', D: 'Kurt Vonnegut', E: 'Yevgeny Zamyatin' },
    answer: 'B',
    explanation: 'Aldous Huxley published Brave New World in 1932, envisioning a technologically pacified dystopian future.',
  },
  {
    id: 'lit_61',
    text: 'Which epic Turkish/Oghuz oral tradition tells stories of heroes like Dirse Han and Bamsı Beyrek?',
    text_tr: 'Dirse Han ve Bamsı Beyrek gibi kahramanların hikayelerini anlatan destansı Türk/Oğuz sözlü geleneği hangisidir?',
    options: { A: 'Köroğlu', B: 'The Book of Dede Korkut', C: 'Manas', D: 'Battalname', E: 'Danişmendname' },
    options_tr: { A: 'Köroğlu', B: 'Dede Korkut Kitabı', C: 'Manas', D: 'Battalname', E: 'Danişmendname' },
    answer: 'B',
    explanation: 'The Book of Dede Korkut is a collection of epic stories reflecting the oral tradition of the Oghuz Turks.',
  },
  {
    id: 'lit_62',
    text: 'Who wrote "The Sound and the Fury," told partly through the perspective of a cognitively disabled character?',
    text_tr: 'Kısmen bilişsel engelli bir karakterin bakış açısından anlatılan "Ses ve Öfke"yi kim yazmıştır?',
    options: { A: 'William Faulkner', B: 'Ernest Hemingway', C: 'John Dos Passos', D: 'Thomas Wolfe', E: 'Sherwood Anderson' },
    options_tr: { A: 'William Faulkner', B: 'Ernest Hemingway', C: 'John Dos Passos', D: 'Thomas Wolfe', E: 'Sherwood Anderson' },
    answer: 'A',
    explanation: 'William Faulkner published The Sound and the Fury in 1929, known for its stream-of-consciousness narration.',
  },
  {
    id: 'lit_63',
    text: 'Which Turkish author wrote the historical novel series "Devlet Ana," depicting the founding era of the Ottoman Empire?',
    text_tr: 'Osmanlı Devleti\'nin kuruluş dönemini anlatan tarihi roman "Devlet Ana"yı hangi Türk yazar yazmıştır?',
    options: { A: 'Kemal Tahir', B: 'Tarık Buğra', C: 'Turgut Özakman', D: 'Ahmet Turan Alkan', E: 'Feridun Fazıl Tülbentçi' },
    options_tr: { A: 'Kemal Tahir', B: 'Tarık Buğra', C: 'Turgut Özakman', D: 'Ahmet Turan Alkan', E: 'Feridun Fazıl Tülbentçi' },
    answer: 'B',
    explanation: 'Tarık Buğra published Devlet Ana in 1967, dramatizing the founding of the Ottoman state under Osman Gazi.',
  },
  {
    id: 'lit_64',
    text: 'Who wrote "Faust," a play in which a scholar makes a pact with the devil?',
    text_tr: 'Bir bilim insanının şeytanla anlaşma yaptığı "Faust" oyununu kim yazmıştır?',
    options: { A: 'Friedrich Schiller', B: 'Heinrich von Kleist', C: 'Johann Wolfgang von Goethe', D: 'Georg Büchner', E: 'Christoph Martin Wieland' },
    options_tr: { A: 'Friedrich Schiller', B: 'Heinrich von Kleist', C: 'Johann Wolfgang von Goethe', D: 'Georg Büchner', E: 'Christoph Martin Wieland' },
    answer: 'C',
    explanation: 'Goethe worked on Faust for most of his life, publishing Part One in 1808 and Part Two just before his death in 1832.',
  },
  {
    id: 'lit_65',
    text: 'Which Turkish poet wrote "Bin Hüzünlü Sokak" and blends folk tradition with modern free verse in works like "Karşı" and "Mor Ötesi"?',
    text_tr: '"Bin Hüzünlü Sokak" gibi eserlerde halk geleneğini modern serbest nazımla harmanlayan Türk şair kimdir?',
    options: { A: 'Ahmed Arif', B: 'Attila İlhan', C: 'Turgut Uyar', D: 'Edip Cansever', E: 'Cemal Süreya' },
    options_tr: { A: 'Ahmed Arif', B: 'Attila İlhan', C: 'Turgut Uyar', D: 'Edip Cansever', E: 'Cemal Süreya' },
    answer: 'B',
    explanation: 'Attila İlhan is known for blending romantic, political, and modern themes and wrote "Bin Hüzünlü Sokak" (1971).',
  },
  {
    id: 'lit_66',
    text: 'Who wrote "Lolita," narrated by the unreliable Humbert Humbert?',
    text_tr: 'Güvenilmez anlatıcı Humbert Humbert tarafından anlatılan "Lolita"yı kim yazmıştır?',
    options: { A: 'Vladimir Nabokov', B: 'Saul Bellow', C: 'Philip Roth', D: 'John Updike', E: 'Norman Mailer' },
    options_tr: { A: 'Vladimir Nabokov', B: 'Saul Bellow', C: 'Philip Roth', D: 'John Updike', E: 'Norman Mailer' },
    answer: 'A',
    explanation: 'Vladimir Nabokov published Lolita in 1955, controversial for its subject matter and celebrated for its prose style.',
  },
  {
    id: 'lit_67',
    text: 'Which Turkish novelist wrote "Bit Palas" (The Flea Palace), a modern novel centered on an apartment building in Istanbul?',
    text_tr: 'İstanbul\'da bir apartmanı merkeze alan modern roman "Bit Palas"ı hangi Türk yazar yazmıştır?',
    options: { A: 'Elif Şafak', B: 'Ayşe Kulin', C: 'Perihan Mağden', D: 'Buket Uzuner', E: 'Zülfü Livaneli' },
    options_tr: { A: 'Elif Şafak', B: 'Ayşe Kulin', C: 'Perihan Mağden', D: 'Buket Uzuner', E: 'Zülfü Livaneli' },
    answer: 'A',
    explanation: 'Elif Şafak published Bit Palas (The Flea Palace) in 2002, following the intertwined lives of an apartment building\'s residents.',
  },
  {
    id: 'lit_68',
    text: 'Who wrote "The Count of Monte Cristo," a tale of imprisonment and revenge?',
    text_tr: 'Hapis ve intikamı konu alan "Monte Kristo Kontu"nu kim yazmıştır?',
    options: { A: 'Victor Hugo', B: 'Alexandre Dumas', C: 'Gustave Flaubert', D: 'Stendhal', E: 'Honoré de Balzac' },
    options_tr: { A: 'Victor Hugo', B: 'Alexandre Dumas', C: 'Gustave Flaubert', D: 'Stendhal', E: 'Honoré de Balzac' },
    answer: 'B',
    explanation: 'Alexandre Dumas published The Count of Monte Cristo in serialized form between 1844 and 1846.',
  },
  {
    id: 'lit_69',
    text: 'Which Turkish poet wrote "Üsküdar\'a Giderken" style folk-influenced verse and is a key figure of the "Hisarcılar" (Hisar poets) group?',
    text_tr: '"Hisarcılar" şiir grubunun önemli isimlerinden ve halk şiiri etkili dizeler yazan şair kimdir?',
    options: { A: 'İlhan Geçer', B: 'Yavuz Bülent Bakiler', C: 'Gültekin Samanoğlu', D: 'Bahaeddin Karakoç', E: 'Mehmet Çınarlı' },
    options_tr: { A: 'İlhan Geçer', B: 'Yavuz Bülent Bakiler', C: 'Gültekin Samanoğlu', D: 'Bahaeddin Karakoç', E: 'Mehmet Çınarlı' },
    answer: 'E',
    explanation: 'Mehmet Çınarlı was a founding figure of the Hisar literary journal and its associated poetry group.',
  },
  {
    id: 'lit_70',
    text: 'Which novel by Herman Hesse follows a young man\'s spiritual journey in ancient India?',
    text_tr: 'Antik Hindistan\'da genç bir adamın manevi yolculuğunu konu alan Hermann Hesse romanı hangisidir?',
    options: { A: 'Steppenwolf', B: 'Siddhartha', C: 'Demian', D: 'The Glass Bead Game', E: 'Narcissus and Goldmund' },
    options_tr: { A: 'Bozkırkurdu', B: 'Siddhartha', C: 'Demian', D: 'Boncuk Oyunu', E: 'Narziss ve Goldmund' },
    answer: 'B',
    explanation: 'Hermann Hesse published Siddhartha in 1922, following a spiritual seeker in the time of the Buddha.',
  },
  {
    id: 'lit_71',
    text: 'Which Turkish author wrote "Saatleri Ayarlama Enstitüsü" (The Time Regulation Institute), a satire of bureaucracy and modernization?',
    text_tr: 'Bürokrasi ve modernleşmenin hicvi olan "Saatleri Ayarlama Enstitüsü"nü hangi Türk yazar yazmıştır?',
    options: { A: 'Ahmet Hamdi Tanpınar', B: 'Peyami Safa', C: 'Refik Halid Karay', D: 'Oğuz Atay', E: 'Haldun Taner' },
    options_tr: { A: 'Ahmet Hamdi Tanpınar', B: 'Peyami Safa', C: 'Refik Halid Karay', D: 'Oğuz Atay', E: 'Haldun Taner' },
    answer: 'A',
    explanation: 'Ahmet Hamdi Tanpınar published The Time Regulation Institute in 1961/1962, a satirical masterpiece on Turkish modernization.',
  },
  {
    id: 'lit_72',
    text: 'Who wrote "Madame Bovary," about a woman whose romantic dreams clash with provincial life?',
    text_tr: 'Romantik hayallerinin taşra yaşamıyla çatıştığı bir kadını konu alan "Madam Bovary"yi kim yazmıştır?',
    options: { A: 'Émile Zola', B: 'Gustave Flaubert', C: 'Guy de Maupassant', D: 'Stendhal', E: 'Honoré de Balzac' },
    options_tr: { A: 'Émile Zola', B: 'Gustave Flaubert', C: 'Guy de Maupassant', D: 'Stendhal', E: 'Honoré de Balzac' },
    answer: 'B',
    explanation: 'Gustave Flaubert published Madame Bovary in 1856, and was even tried (and acquitted) for obscenity because of it.',
  },
  {
    id: 'lit_73',
    text: 'Which Turkish poet and playwright is known for "Keşanlı Ali Destanı" (The Ballad of Ali of Keşan)?',
    text_tr: '"Keşanlı Ali Destanı" ile tanınan Türk şair ve oyun yazarı kimdir?',
    options: { A: 'Haldun Taner', B: 'Cevat Fehmi Başkut', C: 'Turan Oflazoğlu', D: 'Recep Bilginer', E: 'Necati Cumalı' },
    options_tr: { A: 'Haldun Taner', B: 'Cevat Fehmi Başkut', C: 'Turan Oflazoğlu', D: 'Recep Bilginer', E: 'Necati Cumalı' },
    answer: 'A',
    explanation: 'Haldun Taner wrote Keşanlı Ali Destanı (1964), a landmark of modern Turkish theater blending traditional and epic-theater styles.',
  },
  {
    id: 'lit_74',
    text: 'Who wrote "The Trial," in which a man is prosecuted by a remote, inaccessible authority for an unspecified crime?',
    text_tr: 'Bir adamın belirtilmemiş bir suç için uzak, ulaşılmaz bir otorite tarafından yargılandığı "Dava"yı kim yazmıştır?',
    options: { A: 'Franz Kafka', B: 'Thomas Mann', C: 'Hermann Hesse', D: 'Robert Musil', E: 'Stefan Zweig' },
    options_tr: { A: 'Franz Kafka', B: 'Thomas Mann', C: 'Hermann Hesse', D: 'Robert Musil', E: 'Stefan Zweig' },
    answer: 'A',
    explanation: 'Franz Kafka wrote The Trial around 1914–1915; it was published posthumously in 1925.',
  },
  {
    id: 'lit_75',
    text: 'Which Turkish author wrote children\'s and youth classics such as "Sinekli Bakkal," which also won a national award?',
    text_tr: 'Aynı zamanda ulusal bir ödül de kazanan "Sinekli Bakkal" gibi klasikleri hangi Türk yazar yazmıştır?',
    options: { A: 'Halide Edip Adıvar', B: 'Fakir Baykurt', C: 'Muzaffer İzgü', D: 'Gülten Dayıoğlu', E: 'Aziz Nesin' },
    options_tr: { A: 'Halide Edip Adıvar', B: 'Fakir Baykurt', C: 'Muzaffer İzgü', D: 'Gülten Dayıoğlu', E: 'Aziz Nesin' },
    answer: 'A',
    explanation: 'Halide Edip Adıvar published Sinekli Bakkal in 1936, which won the CHP (Republican People\'s Party) Novel Prize.',
  },
  {
    id: 'lit_76',
    text: 'Who wrote "Don Juan Tenorio," a Spanish Romantic play about the legendary seducer?',
    text_tr: 'Efsanevi baştan çıkarıcıyı konu alan İspanyol Romantik oyunu "Don Juan Tenorio"yu kim yazmıştır?',
    options: { A: 'José Zorrilla', B: 'Gustavo Adolfo Bécquer', C: 'Mariano José de Larra', D: 'Ángel de Saavedra', E: 'José de Espronceda' },
    options_tr: { A: 'José Zorrilla', B: 'Gustavo Adolfo Bécquer', C: 'Mariano José de Larra', D: 'Ángel de Saavedra', E: 'José de Espronceda' },
    answer: 'A',
    explanation: 'José Zorrilla wrote Don Juan Tenorio in 1844, a Spanish Romantic reworking of the Don Juan legend.',
  },
  {
    id: 'lit_77',
    text: 'Which Turkish author wrote the "Anayurt Oteli" (Motherland Hotel), depicting the loneliness of a small-town hotel clerk?',
    text_tr: 'Küçük bir kasaba otelinin görevlisinin yalnızlığını anlatan "Anayurt Oteli"ni hangi Türk yazar yazmıştır?',
    options: { A: 'Yusuf Atılgan', B: 'Vüs\'at O. Bener', C: 'Adalet Ağaoğlu', D: 'Selim İleri', E: 'Nedim Gürsel' },
    options_tr: { A: 'Yusuf Atılgan', B: 'Vüs\'at O. Bener', C: 'Adalet Ağaoğlu', D: 'Selim İleri', E: 'Nedim Gürsel' },
    answer: 'A',
    explanation: 'Yusuf Atılgan published Anayurt Oteli in 1973; it was later adapted into a well-known film by Ömer Kavur.',
  },
  {
    id: 'lit_78',
    text: 'Who wrote "The Scarlet Letter," about Hester Prynne\'s public shaming in Puritan New England?',
    text_tr: 'Hester Prynne\'in Püriten Yeni İngiltere\'de teşhir edilmesini konu alan "Kızıl Damga"yı kim yazmıştır?',
    options: { A: 'Nathaniel Hawthorne', B: 'Herman Melville', C: 'Henry James', D: 'Edith Wharton', E: 'Washington Irving' },
    options_tr: { A: 'Nathaniel Hawthorne', B: 'Herman Melville', C: 'Henry James', D: 'Edith Wharton', E: 'Washington Irving' },
    answer: 'A',
    explanation: 'Nathaniel Hawthorne published The Scarlet Letter in 1850, exploring themes of sin, guilt, and redemption.',
  },
  {
    id: 'lit_79',
    text: 'Which Turkish poet and academic wrote "Rubailer," reviving the quatrain form in modern Turkish, and is also known for scholarly work on Ottoman literature?',
    text_tr: 'Modern Türkçede dörtlük formunu yeniden canlandıran "Rubailer"i yazan ve Osmanlı edebiyatı üzerine bilimsel çalışmalarıyla da tanınan şair-akademisyen kimdir?',
    options: { A: 'Yahya Kemal Beyatlı', B: 'Ahmet Hamdi Tanpınar', C: 'Fuad Köprülü', D: 'Nihad Sami Banarlı', E: 'Ali Nihat Tarlan' },
    options_tr: { A: 'Yahya Kemal Beyatlı', B: 'Ahmet Hamdi Tanpınar', C: 'Fuad Köprülü', D: 'Nihad Sami Banarlı', E: 'Ali Nihat Tarlan' },
    answer: 'A',
    explanation: 'Yahya Kemal Beyatlı wrote Rubailer, and is regarded as one of the greatest modern masters of classical Turkish verse forms.',
  },
  {
    id: 'lit_80',
    text: 'Who wrote "The Metamorphosis," "The Trial," and "The Castle" — a Prague-born author writing mostly in German?',
    text_tr: '"Dönüşüm", "Dava" ve "Şato"nun yazarı, Prag doğumlu ve çoğunlukla Almanca yazan yazar kimdir?',
    options: { A: 'Rainer Maria Rilke', B: 'Franz Kafka', C: 'Max Brod', D: 'Egon Erwin Kisch', E: 'Gustav Meyrink' },
    options_tr: { A: 'Rainer Maria Rilke', B: 'Franz Kafka', C: 'Max Brod', D: 'Egon Erwin Kisch', E: 'Gustav Meyrink' },
    answer: 'B',
    explanation: 'Franz Kafka was born in Prague in 1883 and wrote his major works in German.',
  },
  {
    id: 'lit_81',
    text: 'Which Turkish author\'s "İçimizdeki Şeytan" (The Devil Within Us) explores the moral struggles of a young intellectual in 1930s Istanbul?',
    text_tr: '1930\'lu yıllarda İstanbul\'da genç bir aydının ahlaki mücadelelerini inceleyen "İçimizdeki Şeytan"ın yazarı kimdir?',
    options: { A: 'Sabahattin Ali', B: 'Peyami Safa', C: 'Reşat Nuri Güntekin', D: 'Ahmet Hamdi Tanpınar', E: 'Yakup Kadri Karaosmanoğlu' },
    options_tr: { A: 'Sabahattin Ali', B: 'Peyami Safa', C: 'Reşat Nuri Güntekin', D: 'Ahmet Hamdi Tanpınar', E: 'Yakup Kadri Karaosmanoğlu' },
    answer: 'B',
    explanation: 'Peyami Safa published İçimizdeki Şeytan in 1940, examining Westernization and ideology in Turkish society.',
  },
  {
    id: 'lit_82',
    text: 'Who wrote "Don Segundo Sombra," a landmark Argentine novel of gaucho life on the pampas?',
    text_tr: 'Pampalarda gaucho yaşamını konu alan önemli bir Arjantin romanı olan "Don Segundo Sombra"yı kim yazmıştır?',
    options: { A: 'Jorge Luis Borges', B: 'Ricardo Güiraldes', C: 'Julio Cortázar', D: 'Domingo Faustino Sarmiento', E: 'Ernesto Sabato' },
    options_tr: { A: 'Jorge Luis Borges', B: 'Ricardo Güiraldes', C: 'Julio Cortázar', D: 'Domingo Faustino Sarmiento', E: 'Ernesto Sabato' },
    answer: 'B',
    explanation: 'Ricardo Güiraldes published Don Segundo Sombra in 1926, a defining work of Argentine gauchesco literature.',
  },
  {
    id: 'lit_83',
    text: 'Which Turkish writer authored "Yaban" (The Stranger/The Alien), depicting a disillusioned intellectual\'s encounter with rural Anatolia after WWI?',
    text_tr: 'Birinci Dünya Savaşı sonrası hayal kırıklığına uğramış bir aydının Anadolu köyüyle karşılaşmasını anlatan "Yaban"ın yazarı kimdir?',
    options: { A: 'Yakup Kadri Karaosmanoğlu', B: 'Halide Edip Adıvar', C: 'Reşat Nuri Güntekin', D: 'Refik Halid Karay', E: 'Falih Rıfkı Atay' },
    options_tr: { A: 'Yakup Kadri Karaosmanoğlu', B: 'Halide Edip Adıvar', C: 'Reşat Nuri Güntekin', D: 'Refik Halid Karay', E: 'Falih Rıfkı Atay' },
    answer: 'A',
    explanation: 'Yakup Kadri Karaosmanoğlu published Yaban in 1932, a critical look at the gap between intellectuals and rural Anatolia.',
  },
  {
    id: 'lit_84',
    text: 'Who wrote "Gulliver\'s Travels," a satirical account of a man\'s voyages to fantastical lands?',
    text_tr: 'Bir adamın fantastik ülkelere yolculuklarını hicivli bir şekilde anlatan "Gulliver\'in Gezileri"ni kim yazmıştır?',
    options: { A: 'Daniel Defoe', B: 'Jonathan Swift', C: 'Alexander Pope', D: 'Samuel Richardson', E: 'Henry Fielding' },
    options_tr: { A: 'Daniel Defoe', B: 'Jonathan Swift', C: 'Alexander Pope', D: 'Samuel Richardson', E: 'Henry Fielding' },
    answer: 'B',
    explanation: 'Jonathan Swift published Gulliver\'s Travels in 1726, a satire of human nature and travel-narrative conventions.',
  },
  {
    id: 'lit_85',
    text: 'Which Turkish author wrote "Kırık Hayatlar" (Broken Lives), a Servet-i Fünun era novel about love and betrayal in Ottoman high society?',
    text_tr: 'Osmanlı yüksek sosyetesinde aşk ve ihaneti anlatan, Servet-i Fünun dönemine ait "Kırık Hayatlar" romanının yazarı kimdir?',
    options: { A: 'Halit Ziya Uşaklıgil', B: 'Mehmet Rauf', C: 'Hüseyin Cahit Yalçın', D: 'Ahmed Midhat Efendi', E: 'Recaizade Mahmud Ekrem' },
    options_tr: { A: 'Halit Ziya Uşaklıgil', B: 'Mehmet Rauf', C: 'Hüseyin Cahit Yalçın', D: 'Ahmed Midhat Efendi', E: 'Recaizade Mahmud Ekrem' },
    answer: 'A',
    explanation: 'Halit Ziya Uşaklıgil, a leading figure of the Servet-i Fünun movement, published Kırık Hayatlar serially starting in 1901.',
  },
  {
    id: 'lit_86',
    text: 'Who wrote "The Idiot," featuring the almost impossibly good Prince Myshkin?',
    text_tr: 'Neredeyse imkansız derecede iyi olan Prens Mişkin\'i konu alan "Budala"yı kim yazmıştır?',
    options: { A: 'Leo Tolstoy', B: 'Fyodor Dostoevsky', C: 'Ivan Goncharov', D: 'Nikolai Leskov', E: 'Mikhail Saltykov-Shchedrin' },
    options_tr: { A: 'Lev Tolstoy', B: 'Fyodor Dostoyevski', C: 'İvan Gonçarov', D: 'Nikolay Leskov', E: 'Mihail Saltıkov-Şçedrin' },
    answer: 'B',
    explanation: 'Fyodor Dostoevsky published The Idiot in 1869, exploring the difficulty of goodness in a corrupt society.',
  },
  {
    id: 'lit_87',
    text: 'Which Turkish author wrote "Bereketli Topraklar Üzerinde" (On Fertile Lands), depicting seasonal agricultural workers?',
    text_tr: 'Mevsimlik tarım işçilerini konu alan "Bereketli Topraklar Üzerinde"nin yazarı kimdir?',
    options: { A: 'Orhan Kemal', B: 'Kemal Tahir', C: 'Yaşar Kemal', D: 'Fakir Baykurt', E: 'Talip Apaydın' },
    options_tr: { A: 'Orhan Kemal', B: 'Kemal Tahir', C: 'Yaşar Kemal', D: 'Fakir Baykurt', E: 'Talip Apaydın' },
    answer: 'A',
    explanation: 'Orhan Kemal published Bereketli Topraklar Üzerinde in 1954, portraying the harsh life of migrant farm workers.',
  },
  {
    id: 'lit_88',
    text: 'Who wrote "Middlemarch," a sweeping novel of provincial English life focused on Dorothea Brooke?',
    text_tr: 'Dorothea Brooke merkezli, geniş kapsamlı bir İngiliz taşra yaşamı romanı olan "Middlemarch"ı kim yazmıştır?',
    options: { A: 'Charlotte Brontë', B: 'George Eliot', C: 'Elizabeth Gaskell', D: 'Thomas Hardy', E: 'Anthony Trollope' },
    options_tr: { A: 'Charlotte Brontë', B: 'George Eliot', C: 'Elizabeth Gaskell', D: 'Thomas Hardy', E: 'Anthony Trollope' },
    answer: 'B',
    explanation: 'George Eliot (pen name of Mary Ann Evans) published Middlemarch serially between 1871 and 1872.',
  },
  {
    id: 'lit_89',
    text: 'Which Turkish poet wrote "Üç Şehitler Destanı" and other patriotic/epic verse celebrating the War of Independence?',
    text_tr: 'Kurtuluş Savaşı\'nı kutlayan "Üç Şehitler Destanı" ve diğer vatansever/destansı dizeleri hangi Türk şair yazmıştır?',
    options: { A: 'Mehmet Akif Ersoy', B: 'Yahya Kemal Beyatlı', C: 'Faruk Nafiz Çamlıbel', D: 'Kemalettin Kamu', E: 'Orhan Şaik Gökyay' },
    options_tr: { A: 'Mehmet Akif Ersoy', B: 'Yahya Kemal Beyatlı', C: 'Faruk Nafiz Çamlıbel', D: 'Kemalettin Kamu', E: 'Orhan Şaik Gökyay' },
    answer: 'A',
    explanation: 'Mehmet Akif Ersoy wrote "Üç Şehitler Destanı," commemorating fallen soldiers, alongside his broader patriotic body of work.',
  },
  {
    id: 'lit_90',
    text: 'Who wrote "Anna Karenina" and "The Death of Ivan Ilyich," both landmarks of Russian realism?',
    text_tr: 'Rus gerçekçiliğinin iki önemli eseri olan "Anna Karenina" ve "İvan İlyiç\'in Ölümü"nü kim yazmıştır?',
    options: { A: 'Ivan Turgenev', B: 'Leo Tolstoy', C: 'Fyodor Dostoevsky', D: 'Nikolai Gogol', E: 'Anton Chekhov' },
    options_tr: { A: 'İvan Turgenyev', B: 'Lev Tolstoy', C: 'Fyodor Dostoyevski', D: 'Nikolay Gogol', E: 'Anton Çehov' },
    answer: 'B',
    explanation: 'Leo Tolstoy wrote both works; The Death of Ivan Ilyich (1886) is a novella on mortality and meaning.',
  },
  {
    id: 'lit_91',
    text: 'Which Turkish author wrote "Küçük Ağa," a novel about the Turkish War of Independence in the Aegean region?',
    text_tr: 'Ege bölgesinde Türk Kurtuluş Savaşı\'nı konu alan "Küçük Ağa" romanının yazarı kimdir?',
    options: { A: 'Tarık Buğra', B: 'Kemal Tahir', C: 'Turgut Özakman', D: 'Necati Cumalı', E: 'Cengiz Aytmatov' },
    options_tr: { A: 'Tarık Buğra', B: 'Kemal Tahir', C: 'Turgut Özakman', D: 'Necati Cumalı', E: 'Cengiz Aytmatov' },
    answer: 'A',
    explanation: 'Tarık Buğra published Küçük Ağa in 1964, set during the Turkish War of Independence around Akşehir.',
  },
  {
    id: 'lit_92',
    text: 'Who wrote "The Alchemist," a fable-like novel following a shepherd boy named Santiago on a journey to find treasure?',
    text_tr: 'Çoban çocuk Santiago\'nun define aramak için çıktığı yolculuğu anlatan masalsı roman "Simyacı"yı kim yazmıştır?',
    options: { A: 'Jorge Amado', B: 'Paulo Coelho', C: 'Clarice Lispector', D: 'Machado de Assis', E: 'José Saramago' },
    options_tr: { A: 'Jorge Amado', B: 'Paulo Coelho', C: 'Clarice Lispector', D: 'Machado de Assis', E: 'José Saramago' },
    answer: 'B',
    explanation: 'Paulo Coelho published The Alchemist in 1988; it became one of the best-selling books in history.',
  },
  {
    id: 'lit_93',
    text: 'Which Turkish author wrote "Gora" and "Puslu Kıtalar Atlası," known for dense, allegorical prose?',
    text_tr: 'Yoğun, alegorik nesriyle tanınan "Gora" ve "Puslu Kıtalar Atlası"nın yazarı kimdir?',
    options: { A: 'İhsan Oktay Anar', B: 'Hasan Ali Toptaş', C: 'Ahmet Ümit', D: 'Murathan Mungan', E: 'Nedim Gürsel' },
    options_tr: { A: 'İhsan Oktay Anar', B: 'Hasan Ali Toptaş', C: 'Ahmet Ümit', D: 'Murathan Mungan', E: 'Nedim Gürsel' },
    answer: 'A',
    explanation: 'İhsan Oktay Anar is known for atmospheric, Ottoman-flavored novels like Puslu Kıtalar Atlası (1995) and Gora (2013).',
  },
  {
    id: 'lit_94',
    text: 'Who wrote "Dead Souls," a satirical novel about a con man buying deceased serfs\' names?',
    text_tr: 'Bir dolandırıcının ölmüş serflerin isimlerini satın almasını konu alan hicivli "Ölü Canlar"ı kim yazmıştır?',
    options: { A: 'Nikolai Gogol', B: 'Ivan Turgenev', C: 'Alexander Pushkin', D: 'Mikhail Lermontov', E: 'Ivan Goncharov' },
    options_tr: { A: 'Nikolay Gogol', B: 'İvan Turgenyev', C: 'Aleksandr Puşkin', D: 'Mihail Lermontov', E: 'İvan Gonçarov' },
    answer: 'A',
    explanation: 'Nikolai Gogol published Dead Souls in 1842, a satire of Russian bureaucracy and serfdom.',
  },
  {
    id: 'lit_95',
    text: 'Which Turkish author is known for crime/historical fiction such as "Beyoğlu Rapsodisi" and "İstanbul Hatırası"?',
    text_tr: '"Beyoğlu Rapsodisi" ve "İstanbul Hatırası" gibi polisiye/tarihi kurgularıyla tanınan Türk yazar kimdir?',
    options: { A: 'Ahmet Ümit', B: 'Osman Balcıgil', C: 'Celil Oker', D: 'Mehmet Murat Somer', E: 'Yekta Kopan' },
    options_tr: { A: 'Ahmet Ümit', B: 'Osman Balcıgil', C: 'Celil Oker', D: 'Mehmet Murat Somer', E: 'Yekta Kopan' },
    answer: 'A',
    explanation: 'Ahmet Ümit is one of Turkey\'s most popular crime novelists, often blending Istanbul history with detective fiction.',
  },
  {
    id: 'lit_96',
    text: 'Who wrote "A Tale of Two Cities," set during the French Revolution and opening with "It was the best of times, it was the worst of times"?',
    text_tr: 'Fransız Devrimi sırasında geçen ve "Zamanların en iyisiydi, zamanların en kötüsüydü" diye başlayan "İki Şehrin Hikayesi"ni kim yazmıştır?',
    options: { A: 'Charles Dickens', B: 'William Makepeace Thackeray', C: 'Wilkie Collins', D: 'Anthony Trollope', E: 'Thomas Hardy' },
    options_tr: { A: 'Charles Dickens', B: 'William Makepeace Thackeray', C: 'Wilkie Collins', D: 'Anthony Trollope', E: 'Thomas Hardy' },
    answer: 'A',
    explanation: 'Charles Dickens published A Tale of Two Cities in 1859, set in London and Paris before and during the French Revolution.',
  },
  {
    id: 'lit_97',
    text: 'Which Turkish author wrote "Cevdet Bey ve Oğulları" (Cevdet Bey and His Sons), his first novel, before later winning the Nobel Prize?',
    text_tr: 'Daha sonra Nobel Ödülü kazanan yazarın ilk romanı olan "Cevdet Bey ve Oğulları"nın yazarı kimdir?',
    options: { A: 'Orhan Pamuk', B: 'Yaşar Kemal', C: 'Elif Şafak', D: 'Ahmet Altan', E: 'Nedim Gürsel' },
    options_tr: { A: 'Orhan Pamuk', B: 'Yaşar Kemal', C: 'Elif Şafak', D: 'Ahmet Altan', E: 'Nedim Gürsel' },
    answer: 'A',
    explanation: 'Orhan Pamuk published Cevdet Bey ve Oğulları in 1982, his debut novel, years before winning the 2006 Nobel Prize.',
  },
  {
    id: 'lit_98',
    text: 'Who wrote "One Flew Over the Cuckoo\'s Nest," set in a mental institution and narrated by "Chief" Bromden?',
    text_tr: 'Bir akıl hastanesinde geçen ve "Şef" Bromden tarafından anlatılan "Guguk Kuşu"nu kim yazmıştır?',
    options: { A: 'Ken Kesey', B: 'Kurt Vonnegut', C: 'Joseph Heller', D: 'Tom Wolfe', E: 'Hunter S. Thompson' },
    options_tr: { A: 'Ken Kesey', B: 'Kurt Vonnegut', C: 'Joseph Heller', D: 'Tom Wolfe', E: 'Hunter S. Thompson' },
    answer: 'A',
    explanation: 'Ken Kesey published One Flew Over the Cuckoo\'s Nest in 1962, later adapted into the Academy Award-winning film.',
  },
  {
    id: 'lit_99',
    text: 'Which Turkish poet, associated with the "İkinci Yeni" (Second New) movement, wrote experimental, image-dense poetry collections like "Üvercinka"?',
    text_tr: '"İkinci Yeni" akımıyla ilişkilendirilen ve "Üvercinka" gibi deneysel, imge yoğun şiir kitapları yazan şair kimdir?',
    options: { A: 'Cemal Süreya', B: 'İlhan Berk', C: 'Edip Cansever', D: 'Sezai Karakoç', E: 'Ece Ayhan' },
    options_tr: { A: 'Cemal Süreya', B: 'İlhan Berk', C: 'Edip Cansever', D: 'Sezai Karakoç', E: 'Ece Ayhan' },
    answer: 'A',
    explanation: 'Cemal Süreya published Üvercinka in 1958, a foundational collection of the İkinci Yeni (Second New) poetry movement.',
  },
  {
    id: 'lit_100',
    text: 'Which author wrote both "Notes from Underground" and "The Brothers Karamazov"?',
    text_tr: 'Hem "Yeraltından Notlar" hem de "Karamazov Kardeşler"i yazan yazar kimdir?',
    options: { A: 'Leo Tolstoy', B: 'Ivan Turgenev', C: 'Fyodor Dostoevsky', D: 'Anton Chekhov', E: 'Nikolai Gogol' },
    options_tr: { A: 'Lev Tolstoy', B: 'İvan Turgenyev', C: 'Fyodor Dostoyevski', D: 'Anton Çehov', E: 'Nikolay Gogol' },
    answer: 'C',
    explanation: 'Fyodor Dostoevsky wrote both Notes from Underground (1864) and his final novel, The Brothers Karamazov (1880).',
  },
];

module.exports = { literature };
