'use strict';

const math = [
  {
    id: 'mat_01',
    text: 'What is the value of π (pi) to five decimal places?',
    text_tr: 'π (pi) sayısının beş ondalık basamağa kadar değeri nedir?',
    options: { A: '3.14149', B: '3.14159', C: '3.14169', D: '3.14179', E: '3.14189' },
    options_tr: { A: '3,14149', B: '3,14159', C: '3,14169', D: '3,14179', E: '3,14189' },
    answer: 'B',
    explanation: 'π ≈ 3.14159 (3.14159265358979…). It is an irrational number representing the ratio of a circle\'s circumference to its diameter.',
  },
  {
    id: 'mat_02',
    text: 'What is the sum of the interior angles of a triangle?',
    text_tr: 'Bir üçgenin iç açılarının toplamı nedir?',
    options: { A: '90°', B: '120°', C: '180°', D: '270°', E: '360°' },
    options_tr: { A: '90°', B: '120°', C: '180°', D: '270°', E: '360°' },
    answer: 'C',
    explanation: 'The sum of interior angles in any Euclidean triangle is always 180°.',
  },
  {
    id: 'mat_03',
    text: 'Which mathematician is credited with formulating the Pythagorean theorem?',
    text_tr: 'Pisagor teoremini geliştiren matematikçi kimdir?',
    options: { A: 'Euclid', B: 'Archimedes', C: 'Thales', D: 'Pythagoras', E: 'Plato' },
    options_tr: { A: 'Euklid', B: 'Arşimet', C: 'Tales', D: 'Pisagor', E: 'Platon' },
    answer: 'D',
    explanation: 'Pythagoras of Samos (c. 570–495 BC) is credited with the theorem a² + b² = c² for right triangles, though it was known earlier in other cultures.',
  },
  {
    id: 'mat_04',
    text: 'What is the result of 0! (zero factorial)?',
    text_tr: '0! (sıfır faktöriyel) işleminin sonucu nedir?',
    options: { A: '0', B: 'Undefined', C: '1', D: '-1', E: 'Infinity' },
    options_tr: { A: '0', B: 'Tanımsız', C: '1', D: '-1', E: 'Sonsuz' },
    answer: 'C',
    explanation: 'By convention and mathematical definition, 0! = 1. This is consistent with the recursive definition n! = n × (n−1)! and combinatorics.',
  },
  {
    id: 'mat_05',
    text: 'Which number system uses only 0 and 1?',
    text_tr: 'Yalnızca 0 ve 1 rakamlarını kullanan sayı sistemi hangisidir?',
    options: { A: 'Decimal', B: 'Hexadecimal', C: 'Octal', D: 'Binary', E: 'Duodecimal' },
    options_tr: { A: 'Onluk', B: 'On altılık', C: 'Sekizlik', D: 'İkilik', E: 'On ikilik' },
    answer: 'D',
    explanation: 'The binary (base-2) number system uses only digits 0 and 1, and is the foundation of all modern digital computing.',
  },
  {
    id: 'mat_06',
    text: 'What is 7 × 8?',
    text_tr: '7 × 8 kaçtır?',
    options: { A: '54', B: '56', C: '58', D: '64', E: '48' },
    options_tr: { A: '54', B: '56', C: '58', D: '64', E: '48' },
    answer: 'B',
    explanation: '7 × 8 = 56.',
  },
  {
    id: 'mat_07',
    text: 'What is the square root of 144?',
    text_tr: '144\'ün karekökü kaçtır?',
    options: { A: '10', B: '11', C: '12', D: '13', E: '14' },
    options_tr: { A: '10', B: '11', C: '12', D: '13', E: '14' },
    answer: 'C',
    explanation: '12 × 12 = 144, so √144 = 12.',
  },
  {
    id: 'mat_08',
    text: 'A number that can only be divided evenly by 1 and itself (and is greater than 1) is called what?',
    text_tr: 'Yalnızca 1\'e ve kendisine tam bölünebilen (ve 1\'den büyük olan) sayıya ne denir?',
    options: { A: 'Composite number', B: 'Prime number', C: 'Rational number', D: 'Perfect number', E: 'Irrational number' },
    options_tr: { A: 'Bileşik sayı', B: 'Asal sayı', C: 'Rasyonel sayı', D: 'Mükemmel sayı', E: 'İrrasyonel sayı' },
    answer: 'B',
    explanation: 'A prime number has exactly two positive divisors: 1 and itself. Examples include 2, 3, 5, 7, 11.',
  },
  {
    id: 'mat_09',
    text: 'What is the value of 2 to the power of 10 (2¹⁰)?',
    text_tr: '2 üssü 10 (2¹⁰) değerinin sonucu nedir?',
    options: { A: '512', B: '1000', C: '1024', D: '2048', E: '256' },
    options_tr: { A: '512', B: '1000', C: '1024', D: '2048', E: '256' },
    answer: 'C',
    explanation: '2¹⁰ = 1024, a value especially significant in computing (1 kibibyte = 1024 bytes).',
  },
  {
    id: 'mat_10',
    text: 'What is the area of a circle with radius r, in terms of π?',
    text_tr: 'Yarıçapı r olan bir dairenin alanı π cinsinden nasıl ifade edilir?',
    options: { A: '2πr', B: 'πr', C: 'πr²', D: '2πr²', E: 'πd' },
    options_tr: { A: '2πr', B: 'πr', C: 'πr²', D: '2πr²', E: 'πd' },
    answer: 'C',
    explanation: 'The area of a circle is given by A = πr², where r is the radius.',
  },
  {
    id: 'mat_11',
    text: 'What is the value of x in the equation 2x + 3 = 11?',
    text_tr: '2x + 3 = 11 denkleminde x\'in değeri nedir?',
    options: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    options_tr: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    answer: 'B',
    explanation: '2x + 3 = 11 → 2x = 8 → x = 4.',
  },
  {
    id: 'mat_12',
    text: 'Which ancient Greek mathematician wrote "Elements," a foundational text of geometry?',
    text_tr: 'Geometrinin temel eseri olan "Elementler"i yazan antik Yunan matematikçi kimdir?',
    options: { A: 'Archimedes', B: 'Euclid', C: 'Pythagoras', D: 'Eratosthenes', E: 'Apollonius' },
    options_tr: { A: 'Arşimet', B: 'Euklid', C: 'Pisagor', D: 'Eratosthenes', E: 'Apollonius' },
    answer: 'B',
    explanation: 'Euclid\'s "Elements" (c. 300 BC) systematized geometry and remained a standard textbook for over 2,000 years.',
  },
  {
    id: 'mat_13',
    text: 'What is the mathematical constant "e" (Euler\'s number) approximately equal to?',
    text_tr: '"e" (Euler sayısı) matematiksel sabiti yaklaşık olarak kaça eşittir?',
    options: { A: '2.71828', B: '3.14159', C: '1.61803', D: '1.41421', E: '0.57722' },
    options_tr: { A: '2,71828', B: '3,14159', C: '1,61803', D: '1,41421', E: '0,57722' },
    answer: 'A',
    explanation: 'Euler\'s number e ≈ 2.71828 is the base of natural logarithms and appears throughout calculus and compound growth.',
  },
  {
    id: 'mat_14',
    text: 'In a right triangle, what is the name of the side opposite the right angle?',
    text_tr: 'Bir dik üçgende dik açının karşısındaki kenara ne ad verilir?',
    options: { A: 'Adjacent', B: 'Opposite', C: 'Hypotenuse', D: 'Base', E: 'Altitude' },
    options_tr: { A: 'Komşu kenar', B: 'Karşı kenar', C: 'Hipotenüs', D: 'Taban', E: 'Yükseklik' },
    answer: 'C',
    explanation: 'The hypotenuse is always the longest side of a right triangle, opposite the 90° angle.',
  },
  {
    id: 'mat_15',
    text: 'What is 15% of 200?',
    text_tr: '200\'ün yüzde 15\'i kaçtır?',
    options: { A: '15', B: '20', C: '25', D: '30', E: '35' },
    options_tr: { A: '15', B: '20', C: '25', D: '30', E: '35' },
    answer: 'D',
    explanation: '15% of 200 = 0.15 × 200 = 30.',
  },
  {
    id: 'mat_16',
    text: 'Which branch of mathematics deals with rates of change and slopes of curves, developed independently by Newton and Leibniz?',
    text_tr: 'Değişim oranları ve eğrilerin eğimleriyle ilgilenen, Newton ve Leibniz tarafından bağımsız olarak geliştirilen matematik dalı hangisidir?',
    options: { A: 'Algebra', B: 'Calculus', C: 'Topology', D: 'Combinatorics', E: 'Statistics' },
    options_tr: { A: 'Cebir', B: 'Kalkülüs (Analiz)', C: 'Topoloji', D: 'Kombinatorik', E: 'İstatistik' },
    answer: 'B',
    explanation: 'Calculus, developed independently by Isaac Newton and Gottfried Wilhelm Leibniz in the late 17th century, studies continuous change.',
  },
  {
    id: 'mat_17',
    text: 'What do you call a triangle with all three sides of equal length?',
    text_tr: 'Üç kenarı da eşit uzunlukta olan üçgene ne denir?',
    options: { A: 'Scalene triangle', B: 'Isosceles triangle', C: 'Equilateral triangle', D: 'Right triangle', E: 'Obtuse triangle' },
    options_tr: { A: 'Çeşitkenar üçgen', B: 'İkizkenar üçgen', C: 'Eşkenar üçgen', D: 'Dik üçgen', E: 'Geniş açılı üçgen' },
    answer: 'C',
    explanation: 'An equilateral triangle has three equal sides and three equal 60° angles.',
  },
  {
    id: 'mat_18',
    text: 'What is the least common multiple (LCM) of 4 and 6?',
    text_tr: '4 ve 6\'nın en küçük ortak katı (EKOK) kaçtır?',
    options: { A: '10', B: '12', C: '18', D: '24', E: '8' },
    options_tr: { A: '10', B: '12', C: '18', D: '24', E: '8' },
    answer: 'B',
    explanation: 'The multiples of 4 are 4, 8, 12...; the multiples of 6 are 6, 12...; the smallest common one is 12.',
  },
  {
    id: 'mat_19',
    text: 'Which famous unsolved (until 1995) problem, proposed by Pierre de Fermat, states that no three positive integers a, b, c satisfy aⁿ + bⁿ = cⁿ for n > 2?',
    text_tr: '1995\'e kadar çözülemeyen, Pierre de Fermat tarafından öne sürülen ve n > 2 için aⁿ + bⁿ = cⁿ\'i sağlayan üç pozitif tam sayı olmadığını belirten ünlü teorem hangisidir?',
    options: { A: 'Goldbach\'s Conjecture', B: 'The Riemann Hypothesis', C: 'Fermat\'s Last Theorem', D: 'The Poincaré Conjecture', E: 'The Four Color Theorem' },
    options_tr: { A: 'Goldbach Sanısı', B: 'Riemann Hipotezi', C: 'Fermat\'nın Son Teoremi', D: 'Poincaré Sanısı', E: 'Dört Renk Teoremi' },
    answer: 'C',
    explanation: 'Fermat\'s Last Theorem, conjectured in 1637, was finally proven by Andrew Wiles in 1994/1995.',
  },
  {
    id: 'mat_20',
    text: 'What is the result of 9² (9 squared)?',
    text_tr: '9² (9\'un karesi) kaçtır?',
    options: { A: '18', B: '72', C: '81', D: '90', E: '99' },
    options_tr: { A: '18', B: '72', C: '81', D: '90', E: '99' },
    answer: 'C',
    explanation: '9² = 9 × 9 = 81.',
  },
  {
    id: 'mat_21',
    text: 'What is the term for a quadrilateral with exactly one pair of parallel sides?',
    text_tr: 'Yalnızca bir çift kenarı paralel olan dörtgene ne denir?',
    options: { A: 'Parallelogram', B: 'Rhombus', C: 'Trapezoid', D: 'Rectangle', E: 'Kite' },
    options_tr: { A: 'Paralelkenar', B: 'Eşkenar dörtgen', C: 'Yamuk', D: 'Dikdörtgen', E: 'Deltoid' },
    answer: 'C',
    explanation: 'A trapezoid (trapezium in British English) has exactly one pair of parallel sides.',
  },
  {
    id: 'mat_22',
    text: 'Which mathematician is known for the "Fibonacci sequence," where each number is the sum of the two preceding ones?',
    text_tr: 'Her sayının kendinden önceki iki sayının toplamı olduğu "Fibonacci dizisi" ile tanınan matematikçi kimdir?',
    options: { A: 'Leonardo da Vinci', B: 'Leonardo Fibonacci', C: 'Blaise Pascal', D: 'René Descartes', E: 'Carl Friedrich Gauss' },
    options_tr: { A: 'Leonardo da Vinci', B: 'Leonardo Fibonacci', C: 'Blaise Pascal', D: 'René Descartes', E: 'Carl Friedrich Gauss' },
    answer: 'B',
    explanation: 'Leonardo Fibonacci introduced the sequence 1, 1, 2, 3, 5, 8, 13... to Western mathematics in his 1202 book "Liber Abaci."',
  },
  {
    id: 'mat_23',
    text: 'What is 100 divided by 4?',
    text_tr: '100\'ün 4\'e bölümü kaçtır?',
    options: { A: '20', B: '24', C: '25', D: '30', E: '40' },
    options_tr: { A: '20', B: '24', C: '25', D: '30', E: '40' },
    answer: 'C',
    explanation: '100 ÷ 4 = 25.',
  },
  {
    id: 'mat_24',
    text: 'What is the mathematical term for a number that cannot be expressed as a simple fraction, such as π or √2?',
    text_tr: 'π veya √2 gibi basit bir kesir olarak ifade edilemeyen sayılara verilen matematiksel terim nedir?',
    options: { A: 'Rational number', B: 'Irrational number', C: 'Imaginary number', D: 'Natural number', E: 'Integer' },
    options_tr: { A: 'Rasyonel sayı', B: 'İrrasyonel sayı', C: 'Sanal sayı', D: 'Doğal sayı', E: 'Tam sayı' },
    answer: 'B',
    explanation: 'Irrational numbers have non-repeating, non-terminating decimal expansions and cannot be written as a ratio of integers.',
  },
  {
    id: 'mat_25',
    text: 'Which 9th-century Persian scholar, whose name is the root of the word "algorithm," wrote foundational works on algebra?',
    text_tr: '"Algoritma" kelimesinin kökeni olan ve cebir üzerine temel eserler yazan 9. yüzyıl Fars bilgini kimdir?',
    options: { A: 'Al-Kindi', B: 'Al-Khwarizmi', C: 'Omar Khayyam', D: 'Ibn al-Haytham', E: 'Al-Biruni' },
    options_tr: { A: 'El-Kindi', B: 'El-Harezmi', C: 'Ömer Hayyam', D: 'İbn el-Heysem', E: 'El-Biruni' },
    answer: 'B',
    explanation: 'Muhammad ibn Musa al-Khwarizmi\'s name gave rise to the word "algorithm," and his book gave us the word "algebra" (from "al-jabr").',
  },
  {
    id: 'mat_26',
    text: 'What is the value of the square root of -1, denoted as "i" in mathematics?',
    text_tr: 'Matematikte "i" olarak gösterilen -1\'in karekökünün değeri nedir?',
    options: { A: 'A real number', B: 'Undefined in all number systems', C: 'The imaginary unit', D: 'Equal to 1', E: 'Equal to 0' },
    options_tr: { A: 'Bir reel sayı', B: 'Tüm sayı sistemlerinde tanımsız', C: 'Sanal birim', D: '1\'e eşit', E: '0\'a eşit' },
    answer: 'C',
    explanation: 'The imaginary unit i is defined as √(-1) and forms the basis of complex numbers (a + bi).',
  },
  {
    id: 'mat_27',
    text: 'What is 6 factorial (6!)?',
    text_tr: '6 faktöriyel (6!) kaçtır?',
    options: { A: '360', B: '620', C: '720', D: '120', E: '840' },
    options_tr: { A: '360', B: '620', C: '720', D: '120', E: '840' },
    answer: 'C',
    explanation: '6! = 6×5×4×3×2×1 = 720.',
  },
  {
    id: 'mat_28',
    text: 'What is the sum of the interior angles of a quadrilateral (four-sided polygon)?',
    text_tr: 'Bir dörtgenin (dört kenarlı çokgen) iç açılarının toplamı nedir?',
    options: { A: '180°', B: '270°', C: '360°', D: '450°', E: '540°' },
    options_tr: { A: '180°', B: '270°', C: '360°', D: '450°', E: '540°' },
    answer: 'C',
    explanation: 'The sum of interior angles of any quadrilateral is 360° (it can be split into two triangles of 180° each).',
  },
  {
    id: 'mat_29',
    text: 'Which theorem, central to number theory, states that every integer greater than 1 is either prime or can be represented as a unique product of primes?',
    text_tr: 'Sayı teorisinde merkezi bir teorem olan ve 1\'den büyük her tam sayının asal olduğunu veya asal sayıların benzersiz bir çarpımı olarak ifade edilebileceğini belirten teorem hangisidir?',
    options: { A: 'The Binomial Theorem', B: 'The Fundamental Theorem of Arithmetic', C: 'The Pythagorean Theorem', D: 'Bayes\' Theorem', E: 'The Intermediate Value Theorem' },
    options_tr: { A: 'Binom Teoremi', B: 'Aritmetiğin Temel Teoremi', C: 'Pisagor Teoremi', D: 'Bayes Teoremi', E: 'Ara Değer Teoremi' },
    answer: 'B',
    explanation: 'The Fundamental Theorem of Arithmetic guarantees unique prime factorization for every integer greater than 1.',
  },
  {
    id: 'mat_30',
    text: 'What is the perimeter of a square with side length 5 cm?',
    text_tr: 'Kenar uzunluğu 5 cm olan bir karenin çevresi kaçtır?',
    options: { A: '10 cm', B: '15 cm', C: '20 cm', D: '25 cm', E: '30 cm' },
    options_tr: { A: '10 cm', B: '15 cm', C: '20 cm', D: '25 cm', E: '30 cm' },
    answer: 'C',
    explanation: 'The perimeter of a square is 4 × side = 4 × 5 = 20 cm.',
  },
  {
    id: 'mat_31',
    text: 'What is the term for the middle value in a sorted list of numbers?',
    text_tr: 'Sıralanmış bir sayı listesindeki orta değere ne denir?',
    options: { A: 'Mean', B: 'Mode', C: 'Median', D: 'Range', E: 'Variance' },
    options_tr: { A: 'Ortalama', B: 'Mod (Tepe değer)', C: 'Medyan (Ortanca)', D: 'Açıklık', E: 'Varyans' },
    answer: 'C',
    explanation: 'The median is the middle value of a data set when arranged in order; for an even count, it\'s the average of the two middle values.',
  },
  {
    id: 'mat_32',
    text: 'Which German mathematician, called the "Prince of Mathematicians," made major contributions to number theory, algebra, and statistics?',
    text_tr: '"Matematikçilerin Prensi" olarak anılan ve sayı teorisi, cebir ve istatistiğe önemli katkılarda bulunan Alman matematikçi kimdir?',
    options: { A: 'Georg Cantor', B: 'David Hilbert', C: 'Carl Friedrich Gauss', D: 'Bernhard Riemann', E: 'Leonhard Euler' },
    options_tr: { A: 'Georg Cantor', B: 'David Hilbert', C: 'Carl Friedrich Gauss', D: 'Bernhard Riemann', E: 'Leonhard Euler' },
    answer: 'C',
    explanation: 'Carl Friedrich Gauss (1777–1855) is often called "Princeps mathematicorum" (Prince of Mathematicians).',
  },
  {
    id: 'mat_33',
    text: 'What is 3/4 expressed as a decimal?',
    text_tr: '3/4 kesrinin ondalık gösterimi nedir?',
    options: { A: '0.25', B: '0.5', C: '0.75', D: '1.25', E: '0.34' },
    options_tr: { A: '0,25', B: '0,5', C: '0,75', D: '1,25', E: '0,34' },
    answer: 'C',
    explanation: '3 ÷ 4 = 0.75.',
  },
  {
    id: 'mat_34',
    text: 'What do you call a polygon with eight sides?',
    text_tr: 'Sekiz kenarlı bir çokgene ne denir?',
    options: { A: 'Hexagon', B: 'Heptagon', C: 'Octagon', D: 'Nonagon', E: 'Decagon' },
    options_tr: { A: 'Altıgen', B: 'Yedigen', C: 'Sekizgen', D: 'Dokuzgen', E: 'Ongen' },
    answer: 'C',
    explanation: 'An octagon has eight sides and eight angles; a stop sign is a common real-world example.',
  },
  {
    id: 'mat_35',
    text: 'Which unsolved problem in mathematics, one of the seven Millennium Prize Problems, concerns the distribution of prime numbers and the zeros of a complex function?',
    text_tr: 'Yedi Milenyum Ödül Problemi\'nden biri olan ve asal sayıların dağılımı ile karmaşık bir fonksiyonun sıfırlarıyla ilgilenen çözülmemiş matematik problemi hangisidir?',
    options: { A: 'The P versus NP Problem', B: 'The Riemann Hypothesis', C: 'The Poincaré Conjecture (solved in 2003)', D: 'The Hodge Conjecture', E: 'The Birch and Swinnerton-Dyer Conjecture' },
    options_tr: { A: 'P vs NP Problemi', B: 'Riemann Hipotezi', C: 'Poincaré Sanısı (2003\'te çözüldü)', D: 'Hodge Sanısı', E: 'Birch ve Swinnerton-Dyer Sanısı' },
    answer: 'B',
    explanation: 'The Riemann Hypothesis, proposed in 1859, remains unproven and concerns the zeros of the Riemann zeta function.',
  },
  {
    id: 'mat_36',
    text: 'What is the greatest common divisor (GCD) of 18 and 24?',
    text_tr: '18 ve 24\'ün en büyük ortak böleni (EBOB) kaçtır?',
    options: { A: '2', B: '3', C: '6', D: '9', E: '12' },
    options_tr: { A: '2', B: '3', C: '6', D: '9', E: '12' },
    answer: 'C',
    explanation: 'The divisors of 18 are 1,2,3,6,9,18; of 24 are 1,2,3,4,6,8,12,24; the greatest common one is 6.',
  },
  {
    id: 'mat_37',
    text: 'In statistics, what do you call the value that appears most frequently in a data set?',
    text_tr: 'İstatistikte bir veri kümesinde en sık görülen değere ne denir?',
    options: { A: 'Mean', B: 'Median', C: 'Mode', D: 'Standard deviation', E: 'Percentile' },
    options_tr: { A: 'Ortalama', B: 'Medyan', C: 'Mod', D: 'Standart sapma', E: 'Yüzdelik dilim' },
    answer: 'C',
    explanation: 'The mode is the most frequently occurring value in a data set; a set can have one, multiple, or no mode.',
  },
  {
    id: 'mat_38',
    text: 'What is the value of 5³ (5 cubed)?',
    text_tr: '5³ (5\'in küpü) değeri kaçtır?',
    options: { A: '15', B: '25', C: '75', D: '125', E: '625' },
    options_tr: { A: '15', B: '25', C: '75', D: '125', E: '625' },
    answer: 'D',
    explanation: '5³ = 5 × 5 × 5 = 125.',
  },
  {
    id: 'mat_39',
    text: 'What is the term for the ratio of a circle\'s circumference to its diameter, denoted by the Greek letter π?',
    text_tr: 'Bir dairenin çevresinin çapına oranına verilen ve Yunanca π harfiyle gösterilen terim nedir?',
    options: { A: 'Euler\'s number', B: 'Golden ratio', C: 'Pi', D: 'Tau', E: 'Planck constant' },
    options_tr: { A: 'Euler sayısı', B: 'Altın oran', C: 'Pi', D: 'Tau', E: 'Planck sabiti' },
    answer: 'C',
    explanation: 'Pi (π) is a mathematical constant approximately equal to 3.14159, fundamental to circle geometry.',
  },
  {
    id: 'mat_40',
    text: 'Which 17th-century French mathematician and philosopher is known for "Cogito, ergo sum" and for developing Cartesian coordinates?',
    text_tr: '"Düşünüyorum, öyleyse varım" sözü ve Kartezyen koordinat sistemini geliştirmesiyle tanınan 17. yüzyıl Fransız matematikçi ve filozof kimdir?',
    options: { A: 'Blaise Pascal', B: 'René Descartes', C: 'Pierre de Fermat', D: 'Voltaire', E: 'Denis Diderot' },
    options_tr: { A: 'Blaise Pascal', B: 'René Descartes', C: 'Pierre de Fermat', D: 'Voltaire', E: 'Denis Diderot' },
    answer: 'B',
    explanation: 'René Descartes (1596–1650) developed the Cartesian coordinate system, linking algebra and geometry.',
  },
  {
    id: 'mat_41',
    text: 'What is 12 × 12?',
    text_tr: '12 × 12 kaçtır?',
    options: { A: '124', B: '134', C: '144', D: '154', E: '164' },
    options_tr: { A: '124', B: '134', C: '144', D: '154', E: '164' },
    answer: 'C',
    explanation: '12 × 12 = 144.',
  },
  {
    id: 'mat_42',
    text: 'What is the term for a number multiplied by itself, such as 4 × 4 = 16?',
    text_tr: '4 × 4 = 16 örneğinde olduğu gibi bir sayının kendisiyle çarpılmasına ne denir?',
    options: { A: 'Cube', B: 'Root', C: 'Square', D: 'Reciprocal', E: 'Logarithm' },
    options_tr: { A: 'Küp', B: 'Kök', C: 'Kare', D: 'Çarpma tersi', E: 'Logaritma' },
    answer: 'C',
    explanation: 'Squaring a number means multiplying it by itself; 4² = 16.',
  },
  {
    id: 'mat_43',
    text: 'What do you call two angles that add up to 90°?',
    text_tr: 'Toplamı 90° olan iki açıya ne denir?',
    options: { A: 'Supplementary angles', B: 'Complementary angles', C: 'Vertical angles', D: 'Adjacent angles', E: 'Reflex angles' },
    options_tr: { A: 'Bütünler açılar', B: 'Tümler açılar', C: 'Ters açılar', D: 'Komşu açılar', E: 'Tam açılar' },
    answer: 'B',
    explanation: 'Complementary angles sum to 90°; supplementary angles sum to 180°.',
  },
  {
    id: 'mat_44',
    text: 'Which ancient Greek mathematician is famous for shouting "Eureka!" after discovering a principle of buoyancy while in his bath?',
    text_tr: 'Küvette yıkanırken kaldırma kuvveti ilkesini keşfedip "Eureka!" diye bağırdığı için ünlü antik Yunan matematikçi kimdir?',
    options: { A: 'Euclid', B: 'Archimedes', C: 'Thales of Miletus', D: 'Eratosthenes', E: 'Pythagoras' },
    options_tr: { A: 'Euklid', B: 'Arşimet', C: 'Miletli Tales', D: 'Eratosthenes', E: 'Pisagor' },
    answer: 'B',
    explanation: 'Archimedes discovered the principle of buoyancy (Archimedes\' principle) and is said to have run through the streets shouting "Eureka!"',
  },
  {
    id: 'mat_45',
    text: 'What is 1/2 + 1/3 as a single fraction?',
    text_tr: '1/2 + 1/3 işleminin sonucu tek bir kesir olarak nedir?',
    options: { A: '2/5', B: '5/6', C: '3/5', D: '2/6', E: '1/6' },
    options_tr: { A: '2/5', B: '5/6', C: '3/5', D: '2/6', E: '1/6' },
    answer: 'B',
    explanation: '1/2 = 3/6 and 1/3 = 2/6, so 3/6 + 2/6 = 5/6.',
  },
  {
    id: 'mat_46',
    text: 'What is the value of the golden ratio (φ), approximately?',
    text_tr: 'Altın oranın (φ) yaklaşık değeri nedir?',
    options: { A: '1.41421', B: '1.61803', C: '2.71828', D: '3.14159', E: '0.61803 (only)' },
    options_tr: { A: '1,41421', B: '1,61803', C: '2,71828', D: '3,14159', E: 'Yalnızca 0,61803' },
    answer: 'B',
    explanation: 'The golden ratio φ ≈ 1.61803, defined as (1 + √5) / 2, appears in art, architecture, and nature.',
  },
  {
    id: 'mat_47',
    text: 'What is the volume of a cube with side length 3 cm?',
    text_tr: 'Kenar uzunluğu 3 cm olan bir küpün hacmi kaçtır?',
    options: { A: '9 cm³', B: '18 cm³', C: '27 cm³', D: '36 cm³', E: '81 cm³' },
    options_tr: { A: '9 cm³', B: '18 cm³', C: '27 cm³', D: '36 cm³', E: '81 cm³' },
    answer: 'C',
    explanation: 'Volume of a cube = side³ = 3³ = 27 cm³.',
  },
  {
    id: 'mat_48',
    text: 'Which unproven conjecture in number theory states that every even integer greater than 2 can be expressed as the sum of two prime numbers?',
    text_tr: '2\'den büyük her çift tam sayının iki asal sayının toplamı olarak ifade edilebileceğini belirten kanıtlanmamış sayı teorisi sanısı hangisidir?',
    options: { A: 'Twin Prime Conjecture', B: 'Goldbach\'s Conjecture', C: 'Collatz Conjecture', D: 'Fermat\'s Last Theorem (proven)', E: 'Catalan\'s Conjecture (proven)' },
    options_tr: { A: 'İkiz Asal Sanısı', B: 'Goldbach Sanısı', C: 'Collatz Sanısı', D: 'Fermat\'nın Son Teoremi (kanıtlandı)', E: 'Catalan Sanısı (kanıtlandı)' },
    answer: 'B',
    explanation: 'Goldbach\'s Conjecture, proposed in 1742, remains unproven despite being verified for extremely large numbers.',
  },
  {
    id: 'mat_49',
    text: 'What is 20% of 150?',
    text_tr: '150\'nin yüzde 20\'si kaçtır?',
    options: { A: '20', B: '25', C: '30', D: '35', E: '40' },
    options_tr: { A: '20', B: '25', C: '30', D: '35', E: '40' },
    answer: 'C',
    explanation: '20% of 150 = 0.20 × 150 = 30.',
  },
  {
    id: 'mat_50',
    text: 'What is the term for a straight line that touches a curve at exactly one point without crossing it?',
    text_tr: 'Bir eğriye tam olarak bir noktada değen ve onu kesmeyen düz çizgiye ne denir?',
    options: { A: 'Secant', B: 'Chord', C: 'Tangent', D: 'Radius', E: 'Diameter' },
    options_tr: { A: 'Kesen', B: 'Kiriş', C: 'Teğet', D: 'Yarıçap', E: 'Çap' },
    answer: 'C',
    explanation: 'A tangent line touches a curve at a single point and, at that point, has the same slope as the curve.',
  },
  {
    id: 'mat_51',
    text: 'What is 144 ÷ 12?',
    text_tr: '144\'ün 12\'ye bölümü kaçtır?',
    options: { A: '10', B: '11', C: '12', D: '13', E: '14' },
    options_tr: { A: '10', B: '11', C: '12', D: '13', E: '14' },
    answer: 'C',
    explanation: '144 ÷ 12 = 12.',
  },
  {
    id: 'mat_52',
    text: 'Which Hungarian-American mathematician published more papers than any other mathematician in history and was famous for extensive collaborations (giving rise to the "Erdős number")?',
    text_tr: 'Tarihte en çok makale yayımlayan matematikçi olan ve kapsamlı iş birlikleriyle tanınan ("Erdős sayısı" kavramına yol açan) Macar-Amerikalı matematikçi kimdir?',
    options: { A: 'John von Neumann', B: 'Paul Erdős', C: 'George Pólya', D: 'John Nash', E: 'Kurt Gödel' },
    options_tr: { A: 'John von Neumann', B: 'Paul Erdős', C: 'George Pólya', D: 'John Nash', E: 'Kurt Gödel' },
    answer: 'B',
    explanation: 'Paul Erdős (1913–1996) published around 1,500 papers with hundreds of collaborators.',
  },
  {
    id: 'mat_53',
    text: 'What is the sum of the first five positive integers (1+2+3+4+5)?',
    text_tr: 'İlk beş pozitif tam sayının toplamı (1+2+3+4+5) kaçtır?',
    options: { A: '10', B: '12', C: '15', D: '20', E: '25' },
    options_tr: { A: '10', B: '12', C: '15', D: '20', E: '25' },
    answer: 'C',
    explanation: '1+2+3+4+5 = 15.',
  },
  {
    id: 'mat_54',
    text: 'What do you call a polygon with all sides and angles equal?',
    text_tr: 'Tüm kenarları ve açıları eşit olan bir çokgene ne denir?',
    options: { A: 'Convex polygon', B: 'Regular polygon', C: 'Concave polygon', D: 'Irregular polygon', E: 'Simple polygon' },
    options_tr: { A: 'Dışbükey çokgen', B: 'Düzgün çokgen', C: 'İçbükey çokgen', D: 'Düzensiz çokgen', E: 'Basit çokgen' },
    answer: 'B',
    explanation: 'A regular polygon has all sides and interior angles equal, such as an equilateral triangle or a square.',
  },
  {
    id: 'mat_55',
    text: 'Which branch of mathematics studies the properties of shapes that are preserved under continuous deformations, such as stretching or bending (but not tearing)?',
    text_tr: 'Yırtılmadan yapılan gerdirme veya bükme gibi sürekli deformasyonlar altında korunan şekil özelliklerini inceleyen matematik dalı hangisidir?',
    options: { A: 'Algebra', B: 'Number theory', C: 'Topology', D: 'Trigonometry', E: 'Combinatorics' },
    options_tr: { A: 'Cebir', B: 'Sayı teorisi', C: 'Topoloji', D: 'Trigonometri', E: 'Kombinatorik' },
    answer: 'C',
    explanation: 'Topology studies properties preserved under continuous deformation; famously, a coffee cup and a donut are topologically equivalent.',
  },
  {
    id: 'mat_56',
    text: 'What is -8 + 5?',
    text_tr: '-8 + 5 kaçtır?',
    options: { A: '-13', B: '-3', C: '3', D: '13', E: '-5' },
    options_tr: { A: '-13', B: '-3', C: '3', D: '13', E: '-5' },
    answer: 'B',
    explanation: '-8 + 5 = -3.',
  },
  {
    id: 'mat_57',
    text: 'What is the value of sin(90°)?',
    text_tr: 'sin(90°) değeri nedir?',
    options: { A: '0', B: '0.5', C: '1', D: '-1', E: 'Undefined' },
    options_tr: { A: '0', B: '0,5', C: '1', D: '-1', E: 'Tanımsız' },
    answer: 'C',
    explanation: 'sin(90°) = 1, the maximum value of the sine function.',
  },
  {
    id: 'mat_58',
    text: 'Which German mathematician\'s work laid the foundation for set theory, introducing the concept of different sizes of infinity?',
    text_tr: 'Farklı sonsuzluk büyüklükleri kavramını tanıtarak küme teorisinin temelini atan Alman matematikçi kimdir?',
    options: { A: 'David Hilbert', B: 'Richard Dedekind', C: 'Georg Cantor', D: 'Gottlob Frege', E: 'Ernst Zermelo' },
    options_tr: { A: 'David Hilbert', B: 'Richard Dedekind', C: 'Georg Cantor', D: 'Gottlob Frege', E: 'Ernst Zermelo' },
    answer: 'C',
    explanation: 'Georg Cantor developed set theory in the late 19th century and proved that some infinities are larger than others.',
  },
  {
    id: 'mat_59',
    text: 'What is 2/5 expressed as a percentage?',
    text_tr: '2/5 kesrinin yüzde olarak ifadesi nedir?',
    options: { A: '20%', B: '25%', C: '40%', D: '50%', E: '45%' },
    options_tr: { A: '%20', B: '%25', C: '%40', D: '%50', E: '%45' },
    answer: 'C',
    explanation: '2/5 = 0.4 = 40%.',
  },
  {
    id: 'mat_60',
    text: 'What is the term for an equation of the form ax² + bx + c = 0?',
    text_tr: 'ax² + bx + c = 0 biçimindeki denkleme ne ad verilir?',
    options: { A: 'Linear equation', B: 'Quadratic equation', C: 'Cubic equation', D: 'Exponential equation', E: 'Logarithmic equation' },
    options_tr: { A: 'Doğrusal denklem', B: 'İkinci dereceden denklem', C: 'Üçüncü dereceden denklem', D: 'Üstel denklem', E: 'Logaritmik denklem' },
    answer: 'B',
    explanation: 'A quadratic equation has the general form ax² + bx + c = 0, where a ≠ 0.',
  },
  {
    id: 'mat_61',
    text: 'What is the value of |-7| (the absolute value of -7)?',
    text_tr: '|-7| (yani -7\'nin mutlak değeri) kaçtır?',
    options: { A: '-7', B: '0', C: '7', D: '14', E: '-14' },
    options_tr: { A: '-7', B: '0', C: '7', D: '14', E: '-14' },
    answer: 'C',
    explanation: 'The absolute value of a number is its distance from zero, always non-negative: |-7| = 7.',
  },
  {
    id: 'mat_62',
    text: 'Which branch of mathematics is concerned with counting, arrangement, and combination of objects, foundational to probability?',
    text_tr: 'Nesnelerin sayılması, düzenlenmesi ve birleştirilmesiyle ilgilenen ve olasılığın temelini oluşturan matematik dalı hangisidir?',
    options: { A: 'Calculus', B: 'Combinatorics', C: 'Geometry', D: 'Algebra', E: 'Analysis' },
    options_tr: { A: 'Kalkülüs', B: 'Kombinatorik', C: 'Geometri', D: 'Cebir', E: 'Analiz' },
    answer: 'B',
    explanation: 'Combinatorics studies counting, arrangement, and combination principles, essential to probability theory.',
  },
  {
    id: 'mat_63',
    text: 'What is the result of 6 - (-4)?',
    text_tr: '6 - (-4) işleminin sonucu nedir?',
    options: { A: '2', B: '-2', C: '10', D: '-10', E: '24' },
    options_tr: { A: '2', B: '-2', C: '10', D: '-10', E: '24' },
    answer: 'C',
    explanation: 'Subtracting a negative number is equivalent to adding its positive: 6 - (-4) = 6 + 4 = 10.',
  },
  {
    id: 'mat_64',
    text: 'What do you call numbers that can be expressed as the ratio of two integers, such as 1/2 or 3?',
    text_tr: '1/2 veya 3 gibi iki tam sayının oranı olarak ifade edilebilen sayılara ne denir?',
    options: { A: 'Irrational numbers', B: 'Rational numbers', C: 'Imaginary numbers', D: 'Transcendental numbers', E: 'Prime numbers' },
    options_tr: { A: 'İrrasyonel sayılar', B: 'Rasyonel sayılar', C: 'Sanal sayılar', D: 'Aşkın sayılar', E: 'Asal sayılar' },
    answer: 'B',
    explanation: 'A rational number can be written as a fraction p/q where p and q are integers and q ≠ 0.',
  },
  {
    id: 'mat_65',
    text: 'Which English mathematician and physicist developed calculus and the laws of motion, later engaging in a bitter priority dispute with Leibniz?',
    text_tr: 'Kalkülüsü ve hareket yasalarını geliştiren, daha sonra Leibniz ile öncelik konusunda şiddetli bir tartışmaya giren İngiliz matematikçi ve fizikçi kimdir?',
    options: { A: 'Robert Hooke', B: 'Isaac Newton', C: 'James Clerk Maxwell', D: 'Michael Faraday', E: 'Edmund Halley' },
    options_tr: { A: 'Robert Hooke', B: 'Isaac Newton', C: 'James Clerk Maxwell', D: 'Michael Faraday', E: 'Edmund Halley' },
    answer: 'B',
    explanation: 'Isaac Newton (1643–1727) developed calculus independently of Leibniz, leading to a famous priority dispute.',
  },
  {
    id: 'mat_66',
    text: 'What is the circumference of a circle with a diameter of 10 cm, in terms of π?',
    text_tr: 'Çapı 10 cm olan bir dairenin çevresi π cinsinden nedir?',
    options: { A: '5π cm', B: '10π cm', C: '20π cm', D: '100π cm', E: '2.5π cm' },
    options_tr: { A: '5π cm', B: '10π cm', C: '20π cm', D: '100π cm', E: '2,5π cm' },
    answer: 'B',
    explanation: 'Circumference = π × diameter = π × 10 = 10π cm.',
  },
  {
    id: 'mat_67',
    text: 'What is 1000 in binary (base 2)? (Hint: think of it as the decimal number eight expressed in binary)',
    text_tr: 'Sekiz sayısı ikilik (taban 2) sistemde nasıl yazılır?',
    options: { A: '100', B: '1000', C: '1010', D: '1100', E: '10000' },
    options_tr: { A: '100', B: '1000', C: '1010', D: '1100', E: '10000' },
    answer: 'B',
    explanation: 'Decimal 8 = 2³, so in binary it is written as 1000.',
  },
  {
    id: 'mat_68',
    text: 'Which mathematical operation is the inverse of exponentiation, used to solve for the exponent, such as log₂(8) = 3?',
    text_tr: 'Üslü sayıların tersini alan ve üssü bulmak için kullanılan, log₂(8) = 3 gibi bir matematik işlemi hangisidir?',
    options: { A: 'Differentiation', B: 'Integration', C: 'Logarithm', D: 'Factorial', E: 'Modulo operation' },
    options_tr: { A: 'Türev', B: 'İntegral', C: 'Logaritma', D: 'Faktöriyel', E: 'Mod (kalan) işlemi' },
    answer: 'C',
    explanation: 'The logarithm is the inverse of exponentiation: log₂(8) = 3 because 2³ = 8.',
  },
  {
    id: 'mat_69',
    text: 'What is the average (mean) of the numbers 4, 8, and 12?',
    text_tr: '4, 8 ve 12 sayılarının aritmetik ortalaması kaçtır?',
    options: { A: '6', B: '7', C: '8', D: '9', E: '10' },
    options_tr: { A: '6', B: '7', C: '8', D: '9', E: '10' },
    answer: 'C',
    explanation: '(4 + 8 + 12) / 3 = 24 / 3 = 8.',
  },
  {
    id: 'mat_70',
    text: 'Which Swiss mathematician, one of the most prolific in history, introduced much of modern mathematical notation including the function notation f(x) and the constant e?',
    text_tr: 'Tarihin en üretken matematikçilerinden biri olan ve f(x) fonksiyon notasyonu ile e sabiti dahil modern matematik notasyonunun büyük bölümünü tanıtan İsviçreli matematikçi kimdir?',
    options: { A: 'Jacob Bernoulli', B: 'Leonhard Euler', C: 'Johann Bernoulli', D: 'Gabriel Cramer', E: 'Jean le Rond d\'Alembert' },
    options_tr: { A: 'Jacob Bernoulli', B: 'Leonhard Euler', C: 'Johann Bernoulli', D: 'Gabriel Cramer', E: 'Jean le Rond d\'Alembert' },
    answer: 'B',
    explanation: 'Leonhard Euler (1707–1783) was extraordinarily prolific and introduced notation still used today, including f(x), e, and i.',
  },
  {
    id: 'mat_71',
    text: 'What is 3⁴ (3 to the power of 4)?',
    text_tr: '3⁴ (3\'ün 4. kuvveti) kaçtır?',
    options: { A: '12', B: '27', C: '64', D: '81', E: '243' },
    options_tr: { A: '12', B: '27', C: '64', D: '81', E: '243' },
    answer: 'D',
    explanation: '3⁴ = 3×3×3×3 = 81.',
  },
  {
    id: 'mat_72',
    text: 'What do you call a solid shape with six identical square faces?',
    text_tr: 'Altı özdeş kare yüzü olan katı şekle ne denir?',
    options: { A: 'Tetrahedron', B: 'Cube', C: 'Octahedron', D: 'Prism', E: 'Sphere' },
    options_tr: { A: 'Dörtyüzlü (Tetrahedron)', B: 'Küp', C: 'Sekizyüzlü (Oktahedron)', D: 'Prizma', E: 'Küre' },
    answer: 'B',
    explanation: 'A cube (a type of regular hexahedron) has six equal square faces.',
  },
  {
    id: 'mat_73',
    text: 'Which mathematical constant, associated with exponential growth, satisfies the equation e^(iπ) + 1 = 0 (Euler\'s Identity)?',
    text_tr: 'e^(iπ) + 1 = 0 (Euler Özdeşliği) denklemini sağlayan, üstel büyümeyle ilişkili matematiksel sabit hangisidir?',
    options: { A: 'π only', B: 'e (Euler\'s number)', C: 'i only', D: 'The golden ratio', E: 'Avogadro\'s number' },
    options_tr: { A: 'Yalnızca π', B: 'e (Euler sayısı)', C: 'Yalnızca i', D: 'Altın oran', E: 'Avogadro sayısı' },
    answer: 'B',
    explanation: 'Euler\'s Identity, e^(iπ) + 1 = 0, elegantly links e, i, π, 1, and 0, often called the most beautiful equation in mathematics.',
  },
  {
    id: 'mat_74',
    text: 'What is 250 - 175?',
    text_tr: '250 - 175 işleminin sonucu nedir?',
    options: { A: '65', B: '70', C: '75', D: '80', E: '85' },
    options_tr: { A: '65', B: '70', C: '75', D: '80', E: '85' },
    answer: 'C',
    explanation: '250 - 175 = 75.',
  },
  {
    id: 'mat_75',
    text: 'What is the term for a number sequence in which each term after the first is found by adding a constant difference to the previous term?',
    text_tr: 'İlk terimden sonraki her terimin, bir önceki terime sabit bir fark eklenerek bulunduğu sayı dizisine ne denir?',
    options: { A: 'Geometric sequence', B: 'Arithmetic sequence', C: 'Fibonacci sequence', D: 'Harmonic sequence', E: 'Quadratic sequence' },
    options_tr: { A: 'Geometrik dizi', B: 'Aritmetik dizi', C: 'Fibonacci dizisi', D: 'Harmonik dizi', E: 'İkinci dereceden dizi' },
    answer: 'B',
    explanation: 'An arithmetic sequence has a constant difference between consecutive terms, e.g., 2, 5, 8, 11...',
  },
  {
    id: 'mat_76',
    text: 'Which American mathematician, portrayed in the film "A Beautiful Mind," won the Nobel Memorial Prize in Economics for his work on game theory?',
    text_tr: '"Akıl Oyunları" filminde canlandırılan ve oyun teorisi çalışmalarıyla Nobel Ekonomi Ödülü kazanan Amerikalı matematikçi kimdir?',
    options: { A: 'John von Neumann', B: 'John Nash', C: 'Claude Shannon', D: 'Norbert Wiener', E: 'Alan Turing' },
    options_tr: { A: 'John von Neumann', B: 'John Nash', C: 'Claude Shannon', D: 'Norbert Wiener', E: 'Alan Turing' },
    answer: 'B',
    explanation: 'John Nash won the 1994 Nobel Memorial Prize in Economic Sciences for his contributions to game theory (Nash equilibrium).',
  },
  {
    id: 'mat_77',
    text: 'What is 1/4 + 1/4 + 1/4 + 1/4?',
    text_tr: '1/4 + 1/4 + 1/4 + 1/4 işleminin sonucu nedir?',
    options: { A: '1/4', B: '1/2', C: '3/4', D: '1', E: '4/4' },
    options_tr: { A: '1/4', B: '1/2', C: '3/4', D: '1', E: '4/4' },
    answer: 'D',
    explanation: '1/4 × 4 = 4/4 = 1.',
  },
  {
    id: 'mat_78',
    text: 'What do you call a triangle with one angle greater than 90°?',
    text_tr: 'Bir açısı 90°\'den büyük olan üçgene ne denir?',
    options: { A: 'Acute triangle', B: 'Right triangle', C: 'Obtuse triangle', D: 'Equilateral triangle', E: 'Isosceles triangle (necessarily)' },
    options_tr: { A: 'Dar açılı üçgen', B: 'Dik üçgen', C: 'Geniş açılı üçgen', D: 'Eşkenar üçgen', E: 'İkizkenar üçgen (zorunlu olarak)' },
    answer: 'C',
    explanation: 'An obtuse triangle has exactly one interior angle greater than 90°.',
  },
  {
    id: 'mat_79',
    text: 'Which British mathematician and logician is considered a founder of theoretical computer science and proposed the "Turing Test" for machine intelligence?',
    text_tr: 'Teorik bilgisayar biliminin kurucularından sayılan ve makine zekası için "Turing Testi"ni öneren İngiliz matematikçi ve mantıkçı kimdir?',
    options: { A: 'Alonzo Church', B: 'Alan Turing', C: 'John von Neumann', D: 'Claude Shannon', E: 'Kurt Gödel' },
    options_tr: { A: 'Alonzo Church', B: 'Alan Turing', C: 'John von Neumann', D: 'Claude Shannon', E: 'Kurt Gödel' },
    answer: 'B',
    explanation: 'Alan Turing (1912–1954) formalized the concepts of algorithm and computation with the Turing machine.',
  },
  {
    id: 'mat_80',
    text: 'What is 500 × 0.1?',
    text_tr: '500 × 0,1 işleminin sonucu nedir?',
    options: { A: '5', B: '50', C: '0.5', D: '5000', E: '500.1' },
    options_tr: { A: '5', B: '50', C: '0,5', D: '5000', E: '500,1' },
    answer: 'B',
    explanation: '500 × 0.1 = 50.',
  },
  {
    id: 'mat_81',
    text: 'What is the term for two lines that never meet and remain the same distance apart?',
    text_tr: 'Hiç kesişmeyen ve aralarındaki mesafe hep aynı kalan iki çizgiye ne denir?',
    options: { A: 'Perpendicular lines', B: 'Parallel lines', C: 'Intersecting lines', D: 'Skew lines', E: 'Transversal lines' },
    options_tr: { A: 'Dik çizgiler', B: 'Paralel çizgiler', C: 'Kesişen çizgiler', D: 'Ayrık çizgiler', E: 'Kesen çizgiler' },
    answer: 'B',
    explanation: 'Parallel lines lie in the same plane and never intersect, maintaining a constant distance.',
  },
  {
    id: 'mat_82',
    text: 'Which number, often associated with bad luck in Western superstition, is also a prime number?',
    text_tr: 'Batı batıl inançlarında genellikle uğursuzlukla ilişkilendirilen, aynı zamanda bir asal sayı olan sayı hangisidir?',
    options: { A: '12', B: '13', C: '14', D: '15', E: '16' },
    options_tr: { A: '12', B: '13', C: '14', D: '15', E: '16' },
    answer: 'B',
    explanation: 'Thirteen is both considered unlucky in many Western traditions and is a prime number.',
  },
  {
    id: 'mat_83',
    text: 'What is 7² - 4² (7 squared minus 4 squared)?',
    text_tr: '7² - 4² işleminin sonucu nedir?',
    options: { A: '9', B: '23', C: '33', D: '13', E: '45' },
    options_tr: { A: '9', B: '23', C: '33', D: '13', E: '45' },
    answer: 'C',
    explanation: '7² = 49, 4² = 16, and 49 - 16 = 33.',
  },
  {
    id: 'mat_84',
    text: 'Which branch of mathematics is fundamentally concerned with the collection, analysis, interpretation, and presentation of data?',
    text_tr: 'Temel olarak verilerin toplanması, analizi, yorumlanması ve sunulmasıyla ilgilenen matematik dalı hangisidir?',
    options: { A: 'Algebra', B: 'Statistics', C: 'Geometry', D: 'Calculus', E: 'Number theory' },
    options_tr: { A: 'Cebir', B: 'İstatistik', C: 'Geometri', D: 'Kalkülüs', E: 'Sayı teorisi' },
    answer: 'B',
    explanation: 'Statistics is the branch of mathematics dealing with data collection, analysis, and interpretation.',
  },
  {
    id: 'mat_85',
    text: 'What is the sum of the exterior angles of any convex polygon?',
    text_tr: 'Herhangi bir dışbükey çokgenin dış açılarının toplamı nedir?',
    options: { A: '180°', B: '270°', C: '360°', D: '540°', E: 'Depends on number of sides' },
    options_tr: { A: '180°', B: '270°', C: '360°', D: '540°', E: 'Kenar sayısına bağlıdır' },
    answer: 'C',
    explanation: 'The exterior angles of any convex polygon always sum to 360°, regardless of the number of sides.',
  },
  {
    id: 'mat_86',
    text: 'What is the probability of rolling a 4 on a standard six-sided die?',
    text_tr: 'Standart altı yüzlü bir zarda 4 gelme olasılığı nedir?',
    options: { A: '1/2', B: '1/3', C: '1/4', D: '1/6', E: '1/8' },
    options_tr: { A: '1/2', B: '1/3', C: '1/4', D: '1/6', E: '1/8' },
    answer: 'D',
    explanation: 'A fair six-sided die has 6 equally likely outcomes, so the probability of any specific number is 1/6.',
  },
  {
    id: 'mat_87',
    text: 'What is 999 + 1?',
    text_tr: '999 + 1 işleminin sonucu nedir?',
    options: { A: '990', B: '1000', C: '1001', D: '1010', E: '900' },
    options_tr: { A: '990', B: '1000', C: '1001', D: '1010', E: '900' },
    answer: 'B',
    explanation: '999 + 1 = 1000.',
  },
  {
    id: 'mat_88',
    text: 'Which mathematician\'s incompleteness theorems, published in 1931, showed that any consistent formal system powerful enough to describe arithmetic contains true statements it cannot prove?',
    text_tr: '1931\'de yayımlanan ve aritmetiği tanımlayacak kadar güçlü herhangi bir tutarlı biçimsel sistemin kanıtlayamayacağı doğru ifadeler içerdiğini gösteren "eksiklik teoremleri"nin sahibi kimdir?',
    options: { A: 'Bertrand Russell', B: 'Kurt Gödel', C: 'Alfred Tarski', D: 'David Hilbert', E: 'Alonzo Church' },
    options_tr: { A: 'Bertrand Russell', B: 'Kurt Gödel', C: 'Alfred Tarski', D: 'David Hilbert', E: 'Alonzo Church' },
    answer: 'B',
    explanation: 'Kurt Gödel\'s incompleteness theorems (1931) reshaped the foundations of mathematics and logic.',
  },
  {
    id: 'mat_89',
    text: 'What is the reciprocal of 5?',
    text_tr: '5\'in çarpma tersi (resiproğu) nedir?',
    options: { A: '-5', B: '0.5', C: '1/5', D: '5', E: '0' },
    options_tr: { A: '-5', B: '0,5', C: '1/5', D: '5', E: '0' },
    answer: 'C',
    explanation: 'The reciprocal of a number n is 1/n; the reciprocal of 5 is 1/5.',
  },
  {
    id: 'mat_90',
    text: 'What is the term for a number greater than the sum of its proper divisors, such as 12 (whose divisors 1+2+3+4+6=16 exceed 12)?',
    text_tr: 'Uygun bölenlerinin toplamından büyük olan bir sayıya (örneğin 12: bölenleri 1+2+3+4+6=16, 12\'den büyük) ne denir?',
    options: { A: 'Deficient number', B: 'Perfect number', C: 'Abundant number', D: 'Amicable number', E: 'Triangular number' },
    options_tr: { A: 'Eksik sayı', B: 'Mükemmel sayı', C: 'Bolluk sayısı (abundant)', D: 'Dost sayı', E: 'Üçgensel sayı' },
    answer: 'C',
    explanation: 'An abundant number\'s proper divisors sum to more than the number itself; 12 is the smallest example.',
  },
  {
    id: 'mat_91',
    text: 'What is 45 ÷ 9?',
    text_tr: '45\'in 9\'a bölümü kaçtır?',
    options: { A: '4', B: '5', C: '6', D: '9', E: '15' },
    options_tr: { A: '4', B: '5', C: '6', D: '9', E: '15' },
    answer: 'B',
    explanation: '45 ÷ 9 = 5.',
  },
  {
    id: 'mat_92',
    text: 'Which type of number, such as 6 (whose proper divisors 1+2+3=6), equals the sum of its own proper divisors?',
    text_tr: 'Uygun bölenlerinin toplamına eşit olan sayı türü hangisidir (örneğin 6: 1+2+3=6)?',
    options: { A: 'Abundant number', B: 'Deficient number', C: 'Perfect number', D: 'Composite number', E: 'Prime number' },
    options_tr: { A: 'Bolluk sayısı', B: 'Eksik sayı', C: 'Mükemmel sayı', D: 'Bileşik sayı', E: 'Asal sayı' },
    answer: 'C',
    explanation: 'A perfect number equals the sum of its proper divisors; 6, 28, and 496 are the smallest examples.',
  },
  {
    id: 'mat_93',
    text: 'What is the value of cos(0°)?',
    text_tr: 'cos(0°) değeri nedir?',
    options: { A: '0', B: '0.5', C: '1', D: '-1', E: 'Undefined' },
    options_tr: { A: '0', B: '0,5', C: '1', D: '-1', E: 'Tanımsız' },
    answer: 'C',
    explanation: 'cos(0°) = 1, since the cosine function reaches its maximum value at 0°.',
  },
  {
    id: 'mat_94',
    text: 'What is the term for a statement that is assumed to be true without proof, used as a starting point for reasoning?',
    text_tr: 'Kanıt olmadan doğru kabul edilen ve akıl yürütme için başlangıç noktası olarak kullanılan ifadeye ne ad verilir?',
    options: { A: 'Theorem', B: 'Axiom', C: 'Corollary', D: 'Lemma', E: 'Conjecture' },
    options_tr: { A: 'Teorem', B: 'Aksiyom (Belit)', C: 'Sonuç (Corollary)', D: 'Yardımcı teorem (Lemma)', E: 'Sanı (Conjecture)' },
    answer: 'B',
    explanation: 'An axiom (or postulate) is a foundational statement accepted as true without proof, such as Euclid\'s postulates.',
  },
  {
    id: 'mat_95',
    text: 'What is 6/8 simplified to its lowest terms?',
    text_tr: '6/8 kesrinin en sade hali nedir?',
    options: { A: '1/2', B: '2/3', C: '3/4', D: '4/5', E: '5/6' },
    options_tr: { A: '1/2', B: '2/3', C: '3/4', D: '4/5', E: '5/6' },
    answer: 'C',
    explanation: 'Dividing both numerator and denominator by their GCD (2) gives 6/8 = 3/4.',
  },
  {
    id: 'mat_96',
    text: 'Which award, often called the "Nobel Prize of Mathematics," is given every four years to mathematicians under 40?',
    text_tr: 'Genellikle "Matematik Nobeli" olarak adlandırılan ve dört yılda bir 40 yaşın altındaki matematikçilere verilen ödül hangisidir?',
    options: { A: 'Abel Prize', B: 'Fields Medal', C: 'Wolf Prize', D: 'Turing Award', E: 'Gauss Prize' },
    options_tr: { A: 'Abel Ödülü', B: 'Fields Madalyası', C: 'Wolf Ödülü', D: 'Turing Ödülü', E: 'Gauss Ödülü' },
    answer: 'B',
    explanation: 'The Fields Medal, first awarded in 1936, is given at the International Congress of Mathematicians to outstanding mathematicians under 40.',
  },
  {
    id: 'mat_97',
    text: 'What is 3.5 × 2?',
    text_tr: '3,5 × 2 işleminin sonucu nedir?',
    options: { A: '5', B: '6', C: '6.5', D: '7', E: '7.5' },
    options_tr: { A: '5', B: '6', C: '6,5', D: '7', E: '7,5' },
    answer: 'D',
    explanation: '3.5 × 2 = 7.',
  },
  {
    id: 'mat_98',
    text: 'What do you call a number that is the product of exactly two prime numbers or itself and other factors, but is not prime (has more than two divisors)?',
    text_tr: 'İkiden fazla böleni olan (yani asal olmayan) sayıya ne denir?',
    options: { A: 'Prime number', B: 'Composite number', C: 'Perfect square only', D: 'Natural number', E: 'Rational number' },
    options_tr: { A: 'Asal sayı', B: 'Bileşik sayı', C: 'Yalnızca tam kare', D: 'Doğal sayı', E: 'Rasyonel sayı' },
    answer: 'B',
    explanation: 'A composite number has more than two positive divisors, e.g., 4, 6, 8, 9, 10.',
  },
  {
    id: 'mat_99',
    text: 'What is the sum of angles around a single point (a full turn)?',
    text_tr: 'Bir noktanın etrafındaki açıların (tam bir tur) toplamı kaçtır?',
    options: { A: '90°', B: '180°', C: '270°', D: '360°', E: '450°' },
    options_tr: { A: '90°', B: '180°', C: '270°', D: '360°', E: '450°' },
    answer: 'D',
    explanation: 'Angles around a single point always sum to 360°, a full rotation.',
  },
  {
    id: 'mat_100',
    text: 'Which unsolved conjecture asks whether repeatedly applying the rule "if even, halve it; if odd, triple it and add one" to any positive integer will always eventually reach 1?',
    text_tr: 'Herhangi bir pozitif tam sayıya "çiftse yarıya böl, tekse üçle çarpıp bir ekle" kuralını tekrar tekrar uygulamanın her zaman sonunda 1\'e ulaşıp ulaşmayacağını soran çözülmemiş sanı hangisidir?',
    options: { A: 'Goldbach\'s Conjecture', B: 'Twin Prime Conjecture', C: 'Collatz Conjecture', D: 'Riemann Hypothesis', E: 'Erdős–Straus Conjecture' },
    options_tr: { A: 'Goldbach Sanısı', B: 'İkiz Asal Sanısı', C: 'Collatz Sanısı', D: 'Riemann Hipotezi', E: 'Erdős–Straus Sanısı' },
    answer: 'C',
    explanation: 'The Collatz Conjecture (also called the 3n+1 problem) remains unproven despite being verified for enormous numbers.',
  },
];

module.exports = { math };
