'use strict';

const music = [
  {
    id: 'mus_01',
    text: 'Which composer wrote the opera "The Magic Flute" (Die Zauberflöte)?',
    text_tr: '"Sihirli Flüt" (Die Zauberflöte) operasını besteleyen kimdir?',
    options: { A: 'Ludwig van Beethoven', B: 'Johann Sebastian Bach', C: 'George Frideric Handel', D: 'Franz Joseph Haydn', E: 'Wolfgang Amadeus Mozart' },
    options_tr: { A: 'Ludwig van Beethoven', B: 'Johann Sebastian Bach', C: 'George Frideric Handel', D: 'Franz Joseph Haydn', E: 'Wolfgang Amadeus Mozart' },
    answer: 'E',
    explanation: 'Mozart composed The Magic Flute in 1791, the year of his death.',
  },
  {
    id: 'mus_02',
    text: 'The iconic opening bassline of "Under Pressure" (1981) by Queen & David Bowie was later sampled without clearance by which artist?',
    text_tr: 'Queen & David Bowie\'nin "Under Pressure" (1981) şarkısının ikonik bas ritmi, hangi sanatçı tarafından izinsiz sample alındı?',
    options: { A: 'Tupac Shakur', B: 'The Notorious B.I.G.', C: 'Jay-Z', D: 'Vanilla Ice', E: 'Ice Cube' },
    options_tr: { A: 'Tupac Shakur', B: 'The Notorious B.I.G.', C: 'Jay-Z', D: 'Vanilla Ice', E: 'Ice Cube' },
    answer: 'D',
    explanation: 'Vanilla Ice used the riff in "Ice Ice Baby" (1990) and initially denied it before a settlement.',
  },
  {
    id: 'mus_03',
    text: 'Which band released the album "The Dark Side of the Moon" in 1973?',
    text_tr: '"The Dark Side of the Moon" albümünü 1973\'te hangi grup yayımladı?',
    options: { A: 'Led Zeppelin', B: 'The Rolling Stones', C: 'Pink Floyd', D: 'The Beatles', E: 'Deep Purple' },
    options_tr: { A: 'Led Zeppelin', B: 'Rolling Stones', C: 'Pink Floyd', D: 'Beatles', E: 'Deep Purple' },
    answer: 'C',
    explanation: 'Pink Floyd\'s The Dark Side of the Moon spent a record number of weeks on the Billboard 200.',
  },
  {
    id: 'mus_04',
    text: 'Which singer is most commonly called the "Queen of Pop"?',
    text_tr: 'En yaygın olarak "Pop\'un Kraliçesi" diye anılan sanatçı kimdir?',
    options: { A: 'Beyoncé', B: 'Mariah Carey', C: 'Whitney Houston', D: 'Madonna', E: 'Celine Dion' },
    options_tr: { A: 'Beyoncé', B: 'Mariah Carey', C: 'Whitney Houston', D: 'Madonna', E: 'Celine Dion' },
    answer: 'D',
    explanation: 'Madonna has held the "Queen of Pop" title since the 1980s for her influence and commercial success.',
  },
  {
    id: 'mus_05',
    text: 'Which Turkish pop artist is nicknamed "Süper Star" and is one of the best-selling artists in Turkish music history?',
    text_tr: '"Süper Star" lakaplı ve Türk müzik tarihinin en çok satan sanatçılarından biri olan Türk pop sanatçısı kimdir?',
    options: { A: 'Sezen Aksu', B: 'Tarkan', C: 'Zara', D: 'Ajda Pekkan', E: 'Sibel Can' },
    options_tr: { A: 'Sezen Aksu', B: 'Tarkan', C: 'Zara', D: 'Ajda Pekkan', E: 'Sibel Can' },
    answer: 'D',
    explanation: 'Ajda Pekkan, known as "Süper Star", has been a leading figure in Turkish pop since the 1960s.',
  },
  {
    id: 'mus_06',
    text: 'How many lines make up a standard modern musical staff?',
    text_tr: 'Standart modern bir müzik dizeği (porte) kaç çizgiden oluşur?',
    options: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    options_tr: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    answer: 'C',
    explanation: 'The staff has five lines and four spaces. The grand staff joins two five-line staves.',
  },
  {
    id: 'mus_07',
    text: 'How many semitones are there in one octave?',
    text_tr: 'Bir oktavda kaç yarım ses (semiton) vardır?',
    options: { A: '5', B: '7', C: '8', D: '12', E: '24' },
    options_tr: { A: '5', B: '7', C: '8', D: '12', E: '24' },
    answer: 'D',
    explanation: 'Western equal temperament divides the octave into 12 equal semitones. The seven is the number of notes in a diatonic scale.',
  },
  {
    id: 'mus_08',
    text: 'In music, what does the Italian term "forte" instruct the performer to do?',
    text_tr: 'Müzikte İtalyanca "forte" terimi icracıya ne yapmasını söyler?',
    options: { A: 'Play softly', B: 'Play loudly', C: 'Play faster', D: 'Play slower', E: 'Play smoothly and connected' },
    options_tr: { A: 'Yumuşak (hafif) çalmak', B: 'Yüksek sesle (kuvvetli) çalmak', C: 'Daha hızlı çalmak', D: 'Daha yavaş çalmak', E: 'Bağlı ve akıcı çalmak' },
    answer: 'B',
    explanation: '"Forte" means loud; "piano" means soft. "Legato" is smooth and connected.',
  },
  {
    id: 'mus_09',
    text: 'A standard classical symphony orchestra is divided into how many main instrument families?',
    text_tr: 'Standart bir klasik senfoni orkestrası kaç ana çalgı ailesine ayrılır?',
    options: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    options_tr: { A: '2', B: '3', C: '4', D: '5', E: '6' },
    answer: 'C',
    explanation: 'Strings, woodwinds, brass and percussion. Keyboards and harp are usually grouped with the others as needed.',
  },
  {
    id: 'mus_10',
    text: 'Which clef is normally used for the lower notes played by the left hand on a piano?',
    text_tr: 'Piyanoda sol elin çaldığı pes notalar için normalde hangi anahtar kullanılır?',
    options: { A: 'Treble clef', B: 'Alto clef', C: 'Tenor clef', D: 'Bass clef', E: 'Soprano clef' },
    options_tr: { A: 'Sol anahtarı', B: 'Alto anahtarı', C: 'Tenor anahtarı', D: 'Fa anahtarı (bas)', E: 'Soprano anahtarı' },
    answer: 'D',
    explanation: 'The bass (F) clef covers the lower register; the treble (G) clef covers the higher one.',
  },
  {
    id: 'mus_11',
    text: 'How many strings does a standard violin have?',
    text_tr: 'Standart bir kemanın kaç teli vardır?',
    options: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    options_tr: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    answer: 'B',
    explanation: 'A violin has four strings tuned G–D–A–E.',
  },
  {
    id: 'mus_12',
    text: 'Which of these instruments is NOT a member of the woodwind family?',
    text_tr: 'Bu çalgılardan hangisi tahta üflemeli (woodwind) ailesinin üyesi DEĞİLDİR?',
    options: { A: 'Oboe', B: 'Clarinet', C: 'Bassoon', D: 'Flute', E: 'Trumpet' },
    options_tr: { A: 'Obua', B: 'Klarnet', C: 'Fagot', D: 'Flüt', E: 'Trompet' },
    answer: 'E',
    explanation: 'The trumpet is a brass instrument. The flute is a woodwind even though modern flutes are metal.',
  },
  {
    id: 'mus_13',
    text: 'A time signature of 3/4 is most associated with which dance?',
    text_tr: '3/4\'lük bir ölçü, en çok hangi dansla ilişkilendirilir?',
    options: { A: 'March', B: 'Waltz', C: 'Tango', D: 'Polka', E: 'Foxtrot' },
    options_tr: { A: 'Marş', B: 'Vals', C: 'Tango', D: 'Polka', E: 'Fokstrot' },
    answer: 'B',
    explanation: 'The waltz is the classic triple-metre dance. Marches and polkas are typically in duple metre.',
  },
  {
    id: 'mus_14',
    text: 'In which historical period did Johann Sebastian Bach and George Frideric Handel compose?',
    text_tr: 'Johann Sebastian Bach ve George Frideric Handel hangi tarihsel dönemde beste yaptılar?',
    options: { A: 'Renaissance', B: 'Baroque', C: 'Classical', D: 'Romantic', E: 'Modern' },
    options_tr: { A: 'Rönesans', B: 'Barok', C: 'Klasik', D: 'Romantik', E: 'Modern' },
    answer: 'B',
    explanation: 'The Baroque era is roughly 1600–1750; Bach\'s death in 1750 is often taken as its end.',
  },
  {
    id: 'mus_15',
    text: 'Which composer, who became deaf later in life, wrote nine symphonies including the "Choral" Symphony?',
    text_tr: 'Hayatının ilerleyen döneminde sağır olan ve "Koral" Senfoni dahil dokuz senfoni yazan besteci kimdir?',
    options: { A: 'Franz Schubert', B: 'Johannes Brahms', C: 'Ludwig van Beethoven', D: 'Gustav Mahler', E: 'Antonín Dvořák' },
    options_tr: { A: 'Franz Schubert', B: 'Johannes Brahms', C: 'Ludwig van Beethoven', D: 'Gustav Mahler', E: 'Antonín Dvořák' },
    answer: 'C',
    explanation: 'Beethoven\'s Ninth Symphony (1824) sets Schiller\'s "Ode to Joy" for chorus and soloists.',
  },
  {
    id: 'mus_16',
    text: 'The "Ode to Joy" melody, used in the EU anthem, comes from a symphony by which composer?',
    text_tr: 'AB marşında kullanılan "Ode to Joy" (Neşeye Övgü) melodisi, hangi bestecinin bir senfonisinden gelir?',
    options: { A: 'Mozart', B: 'Beethoven', C: 'Wagner', D: 'Tchaikovsky', E: 'Haydn' },
    options_tr: { A: 'Mozart', B: 'Beethoven', C: 'Wagner', D: 'Çaykovski', E: 'Haydn' },
    answer: 'B',
    explanation: 'It is the main theme of the finale of Beethoven\'s Symphony No. 9.',
  },
  {
    id: 'mus_17',
    text: 'Which Italian composer wrote the operas "La Bohème", "Tosca" and "Madama Butterfly"?',
    text_tr: '"La Bohème", "Tosca" ve "Madama Butterfly" operalarını yazan İtalyan besteci kimdir?',
    options: { A: 'Giuseppe Verdi', B: 'Gioachino Rossini', C: 'Giacomo Puccini', D: 'Gaetano Donizetti', E: 'Vincenzo Bellini' },
    options_tr: { A: 'Giuseppe Verdi', B: 'Gioachino Rossini', C: 'Giacomo Puccini', D: 'Gaetano Donizetti', E: 'Vincenzo Bellini' },
    answer: 'C',
    explanation: 'Puccini (1858–1924) is one of the most performed opera composers in the world.',
  },
  {
    id: 'mus_18',
    text: 'The ballet "Swan Lake" was composed by whom?',
    text_tr: '"Kuğu Gölü" balesini kim besteledi?',
    options: { A: 'Igor Stravinsky', B: 'Sergei Prokofiev', C: 'Pyotr Ilyich Tchaikovsky', D: 'Aram Khachaturian', E: 'Claude Debussy' },
    options_tr: { A: 'Igor Stravinski', B: 'Sergey Prokofyev', C: 'Pyotr İlyiç Çaykovski', D: 'Aram Haçaturyan', E: 'Claude Debussy' },
    answer: 'C',
    explanation: 'Tchaikovsky also wrote the ballets "The Nutcracker" and "The Sleeping Beauty".',
  },
  {
    id: 'mus_19',
    text: 'Which family of instruments produces sound primarily by the vibration of the player\'s lips against a mouthpiece?',
    text_tr: 'Hangi çalgı ailesi, sesi esas olarak icracının dudaklarının bir ağızlığa titreşmesiyle üretir?',
    options: { A: 'Woodwinds', B: 'Brass', C: 'Strings', D: 'Percussion', E: 'Keyboards' },
    options_tr: { A: 'Tahta üflemeliler', B: 'Bakır üflemeliler (nefesli)', C: 'Yaylılar', D: 'Vurmalılar', E: 'Klavyeli çalgılar' },
    answer: 'B',
    explanation: 'Brass players "buzz" their lips; reeds and air columns define the woodwinds.',
  },
  {
    id: 'mus_20',
    text: 'Which term describes the speed or pace of a piece of music?',
    text_tr: 'Bir müzik parçasının hızını veya temposunu tanımlayan terim hangisidir?',
    options: { A: 'Timbre', B: 'Dynamics', C: 'Tempo', D: 'Harmony', E: 'Texture' },
    options_tr: { A: 'Tını (timbre)', B: 'Nüans (dinamik)', C: 'Tempo', D: 'Armoni', E: 'Doku' },
    answer: 'C',
    explanation: 'Tempo markings such as "Allegro" and "Adagio" indicate how fast to play; dynamics indicate how loud.',
  },
  {
    id: 'mus_21',
    text: 'A "concerto" is a composition typically written for what?',
    text_tr: 'Bir "konçerto", tipik olarak ne için yazılmış bir eserdir?',
    options: { A: 'Voice alone', B: 'A solo instrument and orchestra', C: 'A string quartet', D: 'Solo piano only', E: 'A full choir' },
    options_tr: { A: 'Yalnız ses', B: 'Solo bir çalgı ve orkestra', C: 'Bir yaylı kuartet', D: 'Yalnızca solo piyano', E: 'Tam bir koro' },
    answer: 'B',
    explanation: 'A concerto contrasts a soloist (or small group, in a concerto grosso) with the orchestra.',
  },
  {
    id: 'mus_22',
    text: 'Which of these is a percussion instrument of definite pitch?',
    text_tr: 'Bunlardan hangisi belirli perdeli (ses yüksekliği olan) bir vurmalı çalgıdır?',
    options: { A: 'Snare drum', B: 'Cymbals', C: 'Timpani', D: 'Triangle', E: 'Bass drum' },
    options_tr: { A: 'Trampet (snare davul)', B: 'Zil', C: 'Timpani', D: 'Üçgen (triangle)', E: 'Bas davul' },
    answer: 'C',
    explanation: 'Timpani (kettledrums) are tuned to specific pitches; the others produce indefinite pitch.',
  },
  {
    id: 'mus_23',
    text: 'What is the interval between two notes with the same letter name, one being twice the frequency of the other?',
    text_tr: 'Aynı harf adını taşıyan ve biri diğerinin frekansının iki katı olan iki nota arasındaki aralık nedir?',
    options: { A: 'A fifth', B: 'A third', C: 'An octave', D: 'A seventh', E: 'A fourth' },
    options_tr: { A: 'Beşli', B: 'Üçlü', C: 'Oktav', D: 'Yedili', E: 'Dörtlü' },
    answer: 'C',
    explanation: 'Doubling the frequency raises a note by exactly one octave.',
  },
  {
    id: 'mus_24',
    text: 'Which Baroque composer wrote the set of violin concertos known as "The Four Seasons"?',
    text_tr: '"Dört Mevsim" olarak bilinen keman konçertoları setini yazan Barok besteci kimdir?',
    options: { A: 'Arcangelo Corelli', B: 'Antonio Vivaldi', C: 'Georg Philipp Telemann', D: 'Henry Purcell', E: 'Jean-Baptiste Lully' },
    options_tr: { A: 'Arcangelo Corelli', B: 'Antonio Vivaldi', C: 'Georg Philipp Telemann', D: 'Henry Purcell', E: 'Jean-Baptiste Lully' },
    answer: 'B',
    explanation: 'Vivaldi, "the Red Priest", published "Le quattro stagioni" around 1725.',
  },
  {
    id: 'mus_25',
    text: 'The technique of writing music with two or more independent melodic lines sounding together is called what?',
    text_tr: 'Birlikte tınlayan iki veya daha fazla bağımsız ezgi çizgisiyle müzik yazma tekniğine ne denir?',
    options: { A: 'Homophony', B: 'Monophony', C: 'Polyphony', D: 'Heterophony', E: 'Antiphony' },
    options_tr: { A: 'Homofoni', B: 'Monofoni', C: 'Polifoni', D: 'Heterofoni', E: 'Antifoni' },
    answer: 'C',
    explanation: 'Polyphony ("many voices") includes counterpoint and the fugue; monophony is a single line.',
  },
  {
    id: 'mus_26',
    text: 'How many keys does a standard full-size modern piano have?',
    text_tr: 'Standart tam boy modern bir piyanonun kaç tuşu vardır?',
    options: { A: '61', B: '76', C: '85', D: '88', E: '96' },
    options_tr: { A: '61', B: '76', C: '85', D: '88', E: '96' },
    answer: 'D',
    explanation: 'A standard piano has 88 keys: 52 white and 36 black, spanning A0 to C8.',
  },
  {
    id: 'mus_27',
    text: 'Which genre of American music, born in New Orleans, is characterized by improvisation, swing and blue notes?',
    text_tr: 'New Orleans\'ta doğan; doğaçlama, swing ve blue note\'larla karakterize edilen Amerikan müzik türü hangisidir?',
    options: { A: 'Blues', B: 'Country', C: 'Jazz', D: 'Gospel', E: 'Bluegrass' },
    options_tr: { A: 'Blues', B: 'Country', C: 'Caz', D: 'Gospel', E: 'Bluegrass' },
    answer: 'C',
    explanation: 'Jazz emerged in the early 20th century in New Orleans from ragtime, blues and brass-band traditions.',
  },
  {
    id: 'mus_28',
    text: 'Which trumpeter and bandleader is nicknamed "Satchmo" and recorded "What a Wonderful World"?',
    text_tr: '"Satchmo" lakaplı ve "What a Wonderful World"\'ü kaydeden trompetçi ve orkestra şefi kimdir?',
    options: { A: 'Miles Davis', B: 'Dizzy Gillespie', C: 'Louis Armstrong', D: 'Chet Baker', E: 'Duke Ellington' },
    options_tr: { A: 'Miles Davis', B: 'Dizzy Gillespie', C: 'Louis Armstrong', D: 'Chet Baker', E: 'Duke Ellington' },
    answer: 'C',
    explanation: 'Louis Armstrong was a foundational figure in jazz as both a trumpet virtuoso and a singer.',
  },
  {
    id: 'mus_29',
    text: 'The 12-bar blues is defined mainly by a repeating pattern of which musical element?',
    text_tr: '12 ölçülük blues, esas olarak hangi müzik unsurunun tekrar eden bir kalıbıyla tanımlanır?',
    options: { A: 'Melody', B: 'Chord progression', C: 'Lyrics', D: 'Instrumentation', E: 'Tempo' },
    options_tr: { A: 'Ezgi', B: 'Akor ilerleyişi', C: 'Sözler', D: 'Çalgılama', E: 'Tempo' },
    answer: 'B',
    explanation: 'The classic form uses the I, IV and V chords over twelve bars in a set order.',
  },
  {
    id: 'mus_30',
    text: 'Which four musicians made up the classic line-up of The Beatles?',
    text_tr: 'The Beatles\'ın klasik kadrosunu hangi dört müzisyen oluşturuyordu?',
    options: {
      A: 'John Lennon, Paul McCartney, George Harrison, Ringo Starr',
      B: 'John Lennon, Paul McCartney, George Harrison, Pete Best',
      C: 'John Lennon, Paul McCartney, Stuart Sutcliffe, Ringo Starr',
      D: 'Mick Jagger, Keith Richards, George Harrison, Ringo Starr',
      E: 'John Lennon, Paul McCartney, Eric Clapton, Ringo Starr',
    },
    options_tr: {
      A: 'John Lennon, Paul McCartney, George Harrison, Ringo Starr',
      B: 'John Lennon, Paul McCartney, George Harrison, Pete Best',
      C: 'John Lennon, Paul McCartney, Stuart Sutcliffe, Ringo Starr',
      D: 'Mick Jagger, Keith Richards, George Harrison, Ringo Starr',
      E: 'John Lennon, Paul McCartney, Eric Clapton, Ringo Starr',
    },
    answer: 'A',
    explanation: 'Ringo Starr replaced Pete Best in 1962; Stuart Sutcliffe had left earlier.',
  },
  {
    id: 'mus_31',
    text: 'Which guitarist, a member of Led Zeppelin, is famous for the riff and solo in "Stairway to Heaven"?',
    text_tr: 'Led Zeppelin üyesi olan ve "Stairway to Heaven"deki riff ve soloyla ünlü gitarist kimdir?',
    options: { A: 'Eric Clapton', B: 'Jimmy Page', C: 'Jimi Hendrix', D: 'David Gilmour', E: 'Ritchie Blackmore' },
    options_tr: { A: 'Eric Clapton', B: 'Jimmy Page', C: 'Jimi Hendrix', D: 'David Gilmour', E: 'Ritchie Blackmore' },
    answer: 'B',
    explanation: 'Jimmy Page founded Led Zeppelin and wrote most of its music with singer Robert Plant.',
  },
  {
    id: 'mus_32',
    text: 'Which singer, born Reginald Dwight, recorded "Rocket Man" and "Your Song"?',
    text_tr: 'Asıl adı Reginald Dwight olan ve "Rocket Man" ile "Your Song"u kaydeden şarkıcı kimdir?',
    options: { A: 'Rod Stewart', B: 'David Bowie', C: 'Elton John', D: 'Freddie Mercury', E: 'George Michael' },
    options_tr: { A: 'Rod Stewart', B: 'David Bowie', C: 'Elton John', D: 'Freddie Mercury', E: 'George Michael' },
    answer: 'C',
    explanation: 'Elton John has written most of his songs with lyricist Bernie Taupin since the late 1960s.',
  },
  {
    id: 'mus_33',
    text: 'The album "Thriller" (1982), the best-selling album of all time, was released by which artist?',
    text_tr: 'Tüm zamanların en çok satan albümü olan "Thriller" (1982), hangi sanatçı tarafından yayımlandı?',
    options: { A: 'Prince', B: 'Michael Jackson', C: 'Lionel Richie', D: 'Stevie Wonder', E: 'Whitney Houston' },
    options_tr: { A: 'Prince', B: 'Michael Jackson', C: 'Lionel Richie', D: 'Stevie Wonder', E: 'Whitney Houston' },
    answer: 'B',
    explanation: 'Michael Jackson\'s "Thriller", produced with Quincy Jones, has sold an estimated 70 million copies.',
  },
  {
    id: 'mus_34',
    text: 'Which band\'s lead singer was Freddie Mercury?',
    text_tr: 'Solisti Freddie Mercury olan grup hangisidir?',
    options: { A: 'The Who', B: 'Queen', C: 'The Police', D: 'Genesis', E: 'Dire Straits' },
    options_tr: { A: 'The Who', B: 'Queen', C: 'The Police', D: 'Genesis', E: 'Dire Straits' },
    answer: 'B',
    explanation: 'Queen also included Brian May, Roger Taylor and John Deacon; "Bohemian Rhapsody" (1975) is their signature song.',
  },
  {
    id: 'mus_35',
    text: 'Which US city is regarded as the birthplace of hip-hop in the 1970s?',
    text_tr: '1970\'lerde hip-hop\'un doğum yeri sayılan ABD şehri hangisidir?',
    options: { A: 'Los Angeles', B: 'Atlanta', C: 'Detroit', D: 'New York City (the Bronx)', E: 'Chicago' },
    options_tr: { A: 'Los Angeles', B: 'Atlanta', C: 'Detroit', D: 'New York (Bronx)', E: 'Chicago' },
    answer: 'D',
    explanation: 'Block parties in the Bronx, with DJs such as Kool Herc, gave rise to hip-hop culture.',
  },
  {
    id: 'mus_36',
    text: 'In a DJ setup, "scratching" is performed using what?',
    text_tr: 'Bir DJ düzeneğinde "scratch" (kazıma) neyle yapılır?',
    options: { A: 'A drum machine', B: 'A turntable and vinyl record', C: 'A synthesizer keyboard', D: 'A microphone', E: 'A sampler pad' },
    options_tr: { A: 'Bir ritim makinesi', B: 'Bir pikap ve plak', C: 'Bir synthesizer klavyesi', D: 'Bir mikrofon', E: 'Bir sampler pad' },
    answer: 'B',
    explanation: 'The DJ moves a vinyl record back and forth under the needle while manipulating the crossfader.',
  },
  {
    id: 'mus_37',
    text: 'Which electronic music pioneer group from Germany released the album "Autobahn" (1974)?',
    text_tr: 'Almanya\'dan çıkan hangi elektronik müzik öncüsü grup, "Autobahn" (1974) albümünü yayımladı?',
    options: { A: 'Tangerine Dream', B: 'Can', C: 'Kraftwerk', D: 'Neu!', E: 'Faust' },
    options_tr: { A: 'Tangerine Dream', B: 'Can', C: 'Kraftwerk', D: 'Neu!', E: 'Faust' },
    answer: 'C',
    explanation: 'Kraftwerk\'s synthesizer-driven sound deeply influenced synth-pop, techno and hip-hop.',
  },
  {
    id: 'mus_38',
    text: 'Which decade saw the rise of grunge, led by bands such as Nirvana and Pearl Jam from Seattle?',
    text_tr: 'Seattle\'dan Nirvana ve Pearl Jam gibi grupların öncülüğünde grunge\'ın yükselişi hangi on yılda oldu?',
    options: { A: 'The 1970s', B: 'The 1980s', C: 'The 1990s', D: 'The 2000s', E: 'The 2010s' },
    options_tr: { A: '1970\'ler', B: '1980\'ler', C: '1990\'lar', D: '2000\'ler', E: '2010\'lar' },
    answer: 'C',
    explanation: 'Nirvana\'s "Nevermind" (1991) brought grunge to the mainstream.',
  },
  {
    id: 'mus_39',
    text: 'Which instrument did Ravi Shankar bring to Western audiences and teach to George Harrison?',
    text_tr: 'Ravi Shankar\'ın Batılı dinleyicilerle tanıştırdığı ve George Harrison\'a öğrettiği çalgı hangisidir?',
    options: { A: 'The tabla', B: 'The sitar', C: 'The tanpura', D: 'The sarod', E: 'The bansuri' },
    options_tr: { A: 'Tabla', B: 'Sitar', C: 'Tanpura', D: 'Sarod', E: 'Bansuri' },
    answer: 'B',
    explanation: 'The sitar, a plucked string instrument, features on Beatles tracks such as "Norwegian Wood".',
  },
  {
    id: 'mus_40',
    text: 'Which award is the most prestigious given by the Recording Academy in the United States?',
    text_tr: 'Amerika\'da Kayıt Akademisi tarafından verilen en prestijli ödül hangisidir?',
    options: { A: 'The BRIT Award', B: 'The Grammy Award', C: 'The Juno Award', D: 'The American Music Award', E: 'The Billboard Music Award' },
    options_tr: { A: 'BRIT Ödülü', B: 'Grammy Ödülü', C: 'Juno Ödülü', D: 'American Music Award', E: 'Billboard Music Award' },
    answer: 'B',
    explanation: 'The Grammy Awards have been presented by the Recording Academy since 1959.',
  },
  {
    id: 'mus_41',
    text: 'The "A cappella" style of singing is defined by the absence of what?',
    text_tr: '"A cappella" söyleyiş tarzı, neyin yokluğuyla tanımlanır?',
    options: { A: 'Harmony', B: 'Lyrics', C: 'Instrumental accompaniment', D: 'A conductor', E: 'A melody' },
    options_tr: { A: 'Armoni', B: 'Sözler', C: 'Çalgı eşliği', D: 'Bir şef', E: 'Bir ezgi' },
    answer: 'C',
    explanation: '"A cappella" (literally "in the manner of the chapel") means voices only, with no instruments.',
  },
  {
    id: 'mus_42',
    text: 'Which voice type is the highest standard female singing voice?',
    text_tr: 'En yüksek standart kadın şan sesi türü hangisidir?',
    options: { A: 'Contralto', B: 'Mezzo-soprano', C: 'Soprano', D: 'Alto', E: 'Tenor' },
    options_tr: { A: 'Kontralto', B: 'Mezzosoprano', C: 'Soprano', D: 'Alto', E: 'Tenor' },
    answer: 'C',
    explanation: 'From lowest to highest, the standard female voices are contralto, mezzo-soprano and soprano.',
  },
  {
    id: 'mus_43',
    text: 'Which key signature has no sharps or flats?',
    text_tr: 'Hangi donanım (anahtar işareti) hiç diyez veya bemol içermez?',
    options: { A: 'G major', B: 'F major', C: 'C major', D: 'D major', E: 'B-flat major' },
    options_tr: { A: 'Sol majör', B: 'Fa majör', C: 'Do majör', D: 'Re majör', E: 'Si bemol majör' },
    answer: 'C',
    explanation: 'C major (and its relative, A minor) uses only the natural notes, so it has an empty key signature.',
  },
  {
    id: 'mus_44',
    text: 'What Italian term marks a gradual increase in loudness?',
    text_tr: 'Sesin kademeli olarak yükselmesini belirten İtalyanca terim nedir?',
    options: { A: 'Diminuendo', B: 'Crescendo', C: 'Sforzando', D: 'Ritardando', E: 'Fermata' },
    options_tr: { A: 'Diminuendo', B: 'Crescendo', C: 'Sforzando', D: 'Ritardando', E: 'Fermata' },
    answer: 'B',
    explanation: '"Crescendo" grows louder; "diminuendo" (or "decrescendo") grows softer.',
  },
  {
    id: 'mus_45',
    text: 'Which composer wrote "The Rite of Spring", whose 1913 Paris premiere reportedly caused a riot?',
    text_tr: '1913 Paris prömiyeri bir ayaklanmaya yol açtığı söylenen "Bahar Ayini"ni hangi besteci yazdı?',
    options: { A: 'Claude Debussy', B: 'Maurice Ravel', C: 'Igor Stravinsky', D: 'Arnold Schoenberg', E: 'Béla Bartók' },
    options_tr: { A: 'Claude Debussy', B: 'Maurice Ravel', C: 'Igor Stravinski', D: 'Arnold Schönberg', E: 'Béla Bartók' },
    answer: 'C',
    explanation: 'Stravinsky\'s ballet score for the Ballets Russes broke with traditional rhythm and harmony.',
  },
  {
    id: 'mus_46',
    text: 'The 12-tone (serial) method of composition was developed by which composer?',
    text_tr: '12 ton (seri) besteleme yöntemini hangi besteci geliştirdi?',
    options: { A: 'Igor Stravinsky', B: 'Arnold Schoenberg', C: 'Aaron Copland', D: 'Dmitri Shostakovich', E: 'Paul Hindemith' },
    options_tr: { A: 'Igor Stravinski', B: 'Arnold Schönberg', C: 'Aaron Copland', D: 'Dmitri Şostakoviç', E: 'Paul Hindemith' },
    answer: 'B',
    explanation: 'Schoenberg introduced the method in the early 1920s; his pupils Berg and Webern developed it further.',
  },
  {
    id: 'mus_47',
    text: 'Which of these is a standard member of a string quartet?',
    text_tr: 'Bunlardan hangisi bir yaylı kuartetin standart üyesidir?',
    options: { A: 'Double bass', B: 'Two violins, one viola, one cello', C: 'Two cellos and two violas', D: 'Violin, viola, cello, harp', E: 'Four violins' },
    options_tr: { A: 'Kontrbas', B: 'İki keman, bir viyola, bir çello', C: 'İki çello ve iki viyola', D: 'Keman, viyola, çello, arp', E: 'Dört keman' },
    answer: 'B',
    explanation: 'The classic string quartet is two violins, a viola and a cello.',
  },
  {
    id: 'mus_48',
    text: 'What is a "cadenza" in a concerto?',
    text_tr: 'Bir konçertodaki "kadans" (cadenza) nedir?',
    options: {
      A: 'The slow middle movement',
      B: 'A virtuosic solo passage, often unaccompanied, near the end of a movement',
      C: 'The orchestral introduction',
      D: 'A repeated bass line',
      E: 'The final chord of the piece',
    },
    options_tr: {
      A: 'Yavaş orta bölüm',
      B: 'Bir bölümün sonuna yakın, genellikle eşliksiz, virtüözik bir solo pasaj',
      C: 'Orkestral giriş',
      D: 'Tekrar eden bir bas çizgisi',
      E: 'Parçanın son akoru',
    },
    answer: 'B',
    explanation: 'The cadenza lets the soloist display technique; historically it was often improvised.',
  },
  {
    id: 'mus_49',
    text: 'Which stringed instrument is the largest and lowest-pitched of the standard orchestral string family?',
    text_tr: 'Standart orkestra yaylı çalgı ailesinin en büyük ve en pes sesli çalgısı hangisidir?',
    options: { A: 'Cello', B: 'Viola', C: 'Double bass', D: 'Harp', E: 'Violin' },
    options_tr: { A: 'Çello', B: 'Viyola', C: 'Kontrbas', D: 'Arp', E: 'Keman' },
    answer: 'C',
    explanation: 'The double bass (contrabass) is played standing or on a high stool and often reads an octave above its sounding pitch.',
  },
  {
    id: 'mus_50',
    text: 'A "fugue", perfected by J. S. Bach, is built on the imitative treatment of a short melodic idea called what?',
    text_tr: 'J. S. Bach tarafından mükemmelleştirilen bir "füg", "subject" (özne) denen kısa bir ezgi fikrinin taklitçi işlenişi üzerine kuruludur; bu kısa fikrin diğer adı nedir?',
    options: { A: 'Coda', B: 'Subject', C: 'Ostinato', D: 'Refrain', E: 'Bridge' },
    options_tr: { A: 'Coda', B: 'Subject (özne / tema)', C: 'Ostinato', D: 'Nakarat', E: 'Köprü' },
    answer: 'B',
    explanation: 'The fugue subject is announced alone, then answered and developed contrapuntally in each voice.',
  },
  {
    id: 'mus_51',
    text: 'Which singer-songwriter, born Robert Zimmerman, won the Nobel Prize in Literature in 2016?',
    text_tr: 'Asıl adı Robert Zimmerman olan ve 2016\'da Nobel Edebiyat Ödülü\'nü kazanan şarkıcı-söz yazarı kimdir?',
    options: { A: 'Leonard Cohen', B: 'Bruce Springsteen', C: 'Bob Dylan', D: 'Neil Young', E: 'Paul Simon' },
    options_tr: { A: 'Leonard Cohen', B: 'Bruce Springsteen', C: 'Bob Dylan', D: 'Neil Young', E: 'Paul Simon' },
    answer: 'C',
    explanation: 'Bob Dylan was recognized "for having created new poetic expressions within the great American song tradition".',
  },
  {
    id: 'mus_52',
    text: 'Which Jamaican musician popularized reggae worldwide with albums like "Exodus" and songs like "No Woman, No Cry"?',
    text_tr: '"Exodus" gibi albümler ve "No Woman, No Cry" gibi şarkılarla reggae\'yi dünyaya yayan Jamaikalı müzisyen kimdir?',
    options: { A: 'Jimmy Cliff', B: 'Peter Tosh', C: 'Bob Marley', D: 'Toots Hibbert', E: 'Burning Spear' },
    options_tr: { A: 'Jimmy Cliff', B: 'Peter Tosh', C: 'Bob Marley', D: 'Toots Hibbert', E: 'Burning Spear' },
    answer: 'C',
    explanation: 'Bob Marley and the Wailers made reggae a global genre in the 1970s.',
  },
  {
    id: 'mus_53',
    text: 'Which term refers to the tone colour or character of a sound that distinguishes, say, a flute from a violin playing the same note?',
    text_tr: 'Aynı notayı çalan bir flütü bir kemandan ayıran ses rengine veya karakterine ne denir?',
    options: { A: 'Pitch', B: 'Timbre', C: 'Amplitude', D: 'Dynamics', E: 'Resonance' },
    options_tr: { A: 'Perde (pitch)', B: 'Tını (timbre)', C: 'Genlik (amplitude)', D: 'Nüans (dinamik)', E: 'Rezonans' },
    answer: 'B',
    explanation: 'Timbre arises largely from the pattern of overtones an instrument produces.',
  },
  {
    id: 'mus_54',
    text: 'Which family does the saxophone belong to, despite being made of brass?',
    text_tr: 'Saksofon, pirinçten yapılmış olmasına rağmen hangi çalgı ailesine aittir?',
    options: { A: 'Brass', B: 'Woodwind', C: 'Percussion', D: 'String', E: 'Keyboard' },
    options_tr: { A: 'Bakır üflemeliler', B: 'Tahta üflemeliler (woodwind)', C: 'Vurmalılar', D: 'Yaylılar', E: 'Klavyeli çalgılar' },
    answer: 'B',
    explanation: 'The saxophone uses a single reed like the clarinet, which places it among the woodwinds.',
  },
  {
    id: 'mus_55',
    text: 'The Eurovision Song Contest has been held annually since which year?',
    text_tr: 'Eurovision Şarkı Yarışması hangi yıldan beri her yıl düzenlenmektedir?',
    options: { A: '1946', B: '1956', C: '1964', D: '1972', E: '1981' },
    options_tr: { A: '1946', B: '1956', C: '1964', D: '1972', E: '1981' },
    answer: 'B',
    explanation: 'The first contest took place in Lugano, Switzerland, in 1956 with seven countries.',
  },
  {
    id: 'mus_56',
    text: 'Which Turkish singer won the Eurovision Song Contest in 2003 with the song "Everyway That I Can"?',
    text_tr: '"Everyway That I Can" şarkısıyla 2003\'te Eurovision Şarkı Yarışması\'nı kazanan Türk şarkıcı kimdir?',
    options: { A: 'Sertab Erener', B: 'Hadise', C: 'Athena', D: 'Kenan Doğulu', E: 'mor ve ötesi' },
    options_tr: { A: 'Sertab Erener', B: 'Hadise', C: 'Athena', D: 'Kenan Doğulu', E: 'mor ve ötesi' },
    answer: 'A',
    explanation: 'Sertab Erener gave Turkey its only Eurovision victory, in Riga in 2003.',
  },
  {
    id: 'mus_57',
    text: 'The bağlama, central to Turkish folk music, is what kind of instrument?',
    text_tr: 'Türk halk müziğinin merkezinde yer alan bağlama ne tür bir çalgıdır?',
    options: { A: 'A bowed string instrument', B: 'A long-necked plucked lute', C: 'A double-reed wind instrument', D: 'A frame drum', E: 'A hammered dulcimer' },
    options_tr: { A: 'Yaylı bir telli çalgı', B: 'Uzun saplı, mızraplı bir lut (saz)', C: 'Çift kamışlı bir üflemeli çalgı', D: 'Bir çerçeve davul', E: 'Tokmakla çalınan bir santur' },
    answer: 'B',
    explanation: 'The bağlama (saz) is a long-necked, fretted lute plucked with a plectrum or with the fingers ("şelpe").',
  },
  {
    id: 'mus_58',
    text: 'Which genre of Turkish music, associated with artists like Orhan Gencebay and Müslüm Gürses, blends Turkish classical, folk and Arabic influences with orchestral arrangements?',
    text_tr: 'Orhan Gencebay ve Müslüm Gürses gibi sanatçılarla özdeşleşen; Türk sanat, halk ve Arap etkilerini orkestral düzenlemelerle harmanlayan Türk müzik türü hangisidir?',
    options: { A: 'Türkü', B: 'Fasıl', C: 'Arabesk', D: 'Taverna', E: 'Özgün müzik' },
    options_tr: { A: 'Türkü', B: 'Fasıl', C: 'Arabesk', D: 'Taverna', E: 'Özgün müzik' },
    answer: 'C',
    explanation: 'Arabesk rose to popularity from the 1970s and was long kept off state television and radio.',
  },
  {
    id: 'mus_59',
    text: 'Which Turkish pop star had a global hit with "Şımarık" (known abroad as "Kiss Kiss") in 1997?',
    text_tr: '1997\'de "Şımarık" (yurt dışında "Kiss Kiss") ile dünya çapında hit yapan Türk pop yıldızı kimdir?',
    options: { A: 'Kenan Doğulu', B: 'Mustafa Sandal', C: 'Tarkan', D: 'Serdar Ortaç', E: 'Levent Yüksel' },
    options_tr: { A: 'Kenan Doğulu', B: 'Mustafa Sandal', C: 'Tarkan', D: 'Serdar Ortaç', E: 'Levent Yüksel' },
    answer: 'C',
    explanation: '"Şımarık" from the album "Ölürüm Sana" was a hit across Europe, Latin America and beyond.',
  },
  {
    id: 'mus_60',
    text: 'The Turkish makam system is a framework of what?',
    text_tr: 'Türk makam sistemi neyin çerçevesidir?',
    options: { A: 'Rhythmic cycles', B: 'Melodic modes and their characteristic phrases', C: 'Instrument tunings only', D: 'Song lyrics forms', E: 'Dance steps' },
    options_tr: { A: 'Ritmik döngüler', B: 'Ezgisel modlar ve bunlara özgü seyirler', C: 'Yalnızca çalgı akortları', D: 'Şarkı sözü biçimleri', E: 'Dans adımları' },
    answer: 'B',
    explanation: 'A makam defines a scale, a tonic, a dominant and typical melodic movement; rhythmic cycles are called "usul".',
  },
  {
    id: 'mus_61',
    text: 'Which composer wrote the "Turkish March" (Rondo alla Turca) as a piano sonata movement?',
    text_tr: 'Bir piyano sonatı bölümü olarak "Türk Marşı"nı (Rondo alla Turca) hangi besteci yazdı?',
    options: { A: 'Beethoven', B: 'Mozart', C: 'Haydn', D: 'Schubert', E: 'Chopin' },
    options_tr: { A: 'Beethoven', B: 'Mozart', C: 'Haydn', D: 'Schubert', E: 'Chopin' },
    answer: 'B',
    explanation: 'It is the finale of Mozart\'s Piano Sonata No. 11 in A major, K. 331, imitating Janissary band music.',
  },
  {
    id: 'mus_62',
    text: 'Which polish composer is famous almost entirely for solo piano works such as nocturnes, mazurkas and polonaises?',
    text_tr: 'Neredeyse tamamen noktürn, mazurka ve polonez gibi solo piyano eserleriyle ünlü Polonyalı besteci kimdir?',
    options: { A: 'Franz Liszt', B: 'Frédéric Chopin', C: 'Robert Schumann', D: 'Johannes Brahms', E: 'Edvard Grieg' },
    options_tr: { A: 'Franz Liszt', B: 'Frédéric Chopin', C: 'Robert Schumann', D: 'Johannes Brahms', E: 'Edvard Grieg' },
    answer: 'B',
    explanation: 'Chopin (1810–1849) wrote almost exclusively for the piano.',
  },
  {
    id: 'mus_63',
    text: 'The opera and music dramas "The Ring of the Nibelung" were composed by whom?',
    text_tr: '"Nibelungen\'in Yüzüğü" opera ve müzik dramları kim tarafından bestelendi?',
    options: { A: 'Giuseppe Verdi', B: 'Richard Strauss', C: 'Richard Wagner', D: 'Georges Bizet', E: 'Modest Mussorgsky' },
    options_tr: { A: 'Giuseppe Verdi', B: 'Richard Strauss', C: 'Richard Wagner', D: 'Georges Bizet', E: 'Modest Musorgski' },
    answer: 'C',
    explanation: 'Wagner\'s four-opera cycle, about 15 hours long, premiered as a whole at Bayreuth in 1876.',
  },
  {
    id: 'mus_64',
    text: 'What do the letters "BPM" measure in music production?',
    text_tr: 'Müzik prodüksiyonunda "BPM" harfleri neyi ölçer?',
    options: { A: 'Bass power modulation', B: 'Beats per minute (tempo)', C: 'Bit depth per module', D: 'Bars per measure', E: 'Balance and panning metric' },
    options_tr: { A: 'Bas güç modülasyonu', B: 'Dakikadaki vuruş sayısı (tempo)', C: 'Modül başına bit derinliği', D: 'Ölçü başına bar', E: 'Denge ve panning metriği' },
    answer: 'B',
    explanation: 'BPM is a numerical tempo: 120 BPM means two beats every second.',
  },
  {
    id: 'mus_65',
    text: 'Which four-on-the-floor genre emerged from Detroit in the 1980s and is characterized by a steady kick drum on every beat?',
    text_tr: '1980\'lerde Detroit\'ten çıkan ve her vuruşta sabit bir kick davul ("four-on-the-floor") ile tanımlanan tür hangisidir?',
    options: { A: 'House', B: 'Techno', C: 'Dubstep', D: 'Drum and bass', E: 'Trance' },
    options_tr: { A: 'House', B: 'Techno', C: 'Dubstep', D: 'Drum and bass', E: 'Trance' },
    answer: 'B',
    explanation: 'Detroit techno (Juan Atkins, Derrick May, Kevin Saunderson) grew alongside Chicago house in the mid-1980s.',
  },
  {
    id: 'mus_66',
    text: 'Which term describes a group of notes played in rapid succession as an ornament, sliding between two main notes?',
    text_tr: 'İki ana nota arasında kayarak, süsleme olarak hızlıca art arda çalınan nota grubuna ne denir?',
    options: { A: 'Trill', B: 'Glissando', C: 'Tremolo', D: 'Vibrato', E: 'Staccato' },
    options_tr: { A: 'Tril', B: 'Glissando', C: 'Tremolo', D: 'Vibrato', E: 'Stakato' },
    answer: 'B',
    explanation: 'A glissando slides continuously (or through many quick steps) from one pitch to another; a trill rapidly alternates two adjacent notes.',
  },
  {
    id: 'mus_67',
    text: 'How many movements does a typical Classical-era symphony have?',
    text_tr: 'Tipik bir Klasik dönem senfonisinin kaç bölümü vardır?',
    options: { A: '1', B: '2', C: '3', D: '4', E: '5' },
    options_tr: { A: '1', B: '2', C: '3', D: '4', E: '5' },
    answer: 'D',
    explanation: 'The standard plan is fast – slow – minuet (or scherzo) – fast.',
  },
  {
    id: 'mus_68',
    text: 'Which of these is a minor scale degree pattern feature that distinguishes the natural minor from the major?',
    text_tr: 'Doğal minör gamı majörden ayıran özellik aşağıdakilerden hangisidir?',
    options: {
      A: 'A raised 7th degree',
      B: 'Lowered 3rd, 6th and 7th degrees',
      C: 'Only five notes',
      D: 'No leading tone resolution at all',
      E: 'A doubled tonic',
    },
    options_tr: {
      A: 'Yükseltilmiş 7. derece',
      B: 'İndirilmiş 3., 6. ve 7. dereceler',
      C: 'Yalnızca beş nota',
      D: 'Hiçbir yeden ses çözümü olmaması',
      E: 'İkiye katlanmış tonik',
    },
    answer: 'B',
    explanation: 'Compared with the parallel major, the natural minor flattens the 3rd, 6th and 7th scale degrees.',
  },
  {
    id: 'mus_69',
    text: 'Which American composer wrote "Rhapsody in Blue" (1924), blending jazz idioms with the concert hall?',
    text_tr: 'Caz deyişlerini konser salonuyla harmanlayan "Rhapsody in Blue"yu (1924) hangi Amerikalı besteci yazdı?',
    options: { A: 'Aaron Copland', B: 'George Gershwin', C: 'Leonard Bernstein', D: 'Charles Ives', E: 'Duke Ellington' },
    options_tr: { A: 'Aaron Copland', B: 'George Gershwin', C: 'Leonard Bernstein', D: 'Charles Ives', E: 'Duke Ellington' },
    answer: 'B',
    explanation: 'Gershwin also wrote the opera "Porgy and Bess" and countless songs with his brother Ira.',
  },
  {
    id: 'mus_70',
    text: 'Which pair of scale patterns is used in the standard blues scale?',
    text_tr: 'Standart blues gamında kullanılan yaklaşım hangisidir?',
    options: {
      A: 'The major pentatonic with an added major 7th',
      B: 'The minor pentatonic with an added flattened 5th ("blue note")',
      C: 'The whole-tone scale',
      D: 'The chromatic scale',
      E: 'The harmonic minor scale',
    },
    options_tr: {
      A: 'Majör pentatonik + eklenmiş majör 7\'li',
      B: 'Minör pentatonik + eklenmiş eksik 5\'li ("blue note")',
      C: 'Tam ton (whole-tone) gamı',
      D: 'Kromatik gam',
      E: 'Armonik minör gam',
    },
    answer: 'B',
    explanation: 'The six-note blues scale is the minor pentatonic plus the "blue note" a flat fifth above the tonic.',
  },
  {
    id: 'mus_71',
    text: 'Which soprano-range brass instrument is pitched an octave above the trombone and is a staple of orchestras and jazz?',
    text_tr: 'Trombondan bir oktav tiz akortlanan; orkestraların ve cazın vazgeçilmezi olan soprano bakır üflemeli çalgı hangisidir?',
    options: { A: 'French horn', B: 'Tuba', C: 'Trumpet', D: 'Euphonium', E: 'Cornet' },
    options_tr: { A: 'Korno', B: 'Tuba', C: 'Trompet', D: 'Eufonyum', E: 'Kornet' },
    answer: 'C',
    explanation: 'The B-flat trumpet is the highest common orchestral brass instrument.',
  },
  {
    id: 'mus_72',
    text: 'Which two chords, along with the tonic, form the basic "three-chord" progression of much popular music (in C major)?',
    text_tr: 'Tonik ile birlikte pek çok popüler müziğin temel "üç akorlu" ilerleyişini (Do majörde) oluşturan diğer iki akor hangisidir?',
    options: { A: 'D minor and E minor', B: 'F major and G major', C: 'A minor and B diminished', D: 'E major and A major', E: 'B-flat and E-flat' },
    options_tr: { A: 'Re minör ve Mi minör', B: 'Fa majör ve Sol majör', C: 'La minör ve Si eksik', D: 'Mi majör ve La majör', E: 'Si bemol ve Mi bemol' },
    answer: 'B',
    explanation: 'The I–IV–V progression in C major is C, F and G.',
  },
  {
    id: 'mus_73',
    text: 'Which of these describes "syncopation"?',
    text_tr: '"Senkop" (syncopation) aşağıdakilerden hangisini tanımlar?',
    options: {
      A: 'Playing all notes exactly on the beat',
      B: 'Placing emphasis on normally weak beats or off-beats',
      C: 'Gradually slowing the tempo',
      D: 'Playing very quietly',
      E: 'Repeating a phrase an octave higher',
    },
    options_tr: {
      A: 'Tüm notaları tam vuruş üzerinde çalmak',
      B: 'Vurguyu normalde zayıf olan vuruşlara veya vuruş aralarına koymak',
      C: 'Tempoyu kademeli olarak yavaşlatmak',
      D: 'Çok yumuşak çalmak',
      E: 'Bir cümleyi bir oktav tiz tekrarlamak',
    },
    answer: 'B',
    explanation: 'Syncopation shifts accents off the expected strong beats, driving jazz, funk and much pop.',
  },
  {
    id: 'mus_74',
    text: 'Which streaming-era metric, introduced in 2013, feeds directly into the US Billboard Hot 100?',
    text_tr: '2013\'te getirilen ve doğrudan ABD Billboard Hot 100\'e giren, streaming çağına ait ölçüt hangisidir?',
    options: { A: 'Radio requests only', B: 'On-demand audio and video streams', C: 'Concert ticket sales', D: 'Sheet-music sales', E: 'Karaoke plays' },
    options_tr: { A: 'Yalnızca radyo istekleri', B: 'İstek üzerine ses ve video streamleri', C: 'Konser bileti satışları', D: 'Nota satışları', E: 'Karaoke çalınmaları' },
    answer: 'B',
    explanation: 'Billboard began counting YouTube and on-demand streaming toward Hot 100 chart position in 2013.',
  },
  {
    id: 'mus_75',
    text: 'Which South Korean group became the first K-pop act to top the US Billboard 200 albums chart, in 2018?',
    text_tr: '2018\'de ABD Billboard 200 albüm listesinin zirvesine çıkan ilk K-pop grubu hangisidir?',
    options: { A: 'EXO', B: 'BTS', C: 'BLACKPINK', D: 'Big Bang', E: 'Twice' },
    options_tr: { A: 'EXO', B: 'BTS', C: 'BLACKPINK', D: 'Big Bang', E: 'Twice' },
    answer: 'B',
    explanation: 'BTS reached No. 1 with "Love Yourself: Tear" in 2018 and repeated the feat several times after.',
  },
  {
    id: 'mus_76',
    text: 'Which orchestral role is responsible for setting tempo, cueing entries and shaping the overall interpretation?',
    text_tr: 'Tempoyu belirlemek, girişleri işaret etmek ve genel yorumu şekillendirmekten sorumlu orkestra rolü hangisidir?',
    options: { A: 'The concertmaster', B: 'The conductor', C: 'The principal cellist', D: 'The librarian', E: 'The soloist' },
    options_tr: { A: 'Başkemancı (konzertmeister)', B: 'Orkestra şefi', C: 'Baş çellist', D: 'Nota kütüphanecisi', E: 'Solist' },
    answer: 'B',
    explanation: 'The conductor directs from the podium; the concertmaster (first-chair violin) is the orchestra\'s leader among the players.',
  },
  {
    id: 'mus_77',
    text: 'What is the standard tuning reference pitch that "A above middle C" is set to in most modern orchestras?',
    text_tr: 'Çoğu modern orkestrada "orta Do üstündeki La" notasının akortlandığı standart referans frekansı nedir?',
    options: { A: '415 Hz', B: '432 Hz', C: '440 Hz', D: '466 Hz', E: '480 Hz' },
    options_tr: { A: '415 Hz', B: '432 Hz', C: '440 Hz', D: '466 Hz', E: '480 Hz' },
    answer: 'C',
    explanation: 'A4 = 440 Hz is the widely used standard; some ensembles tune slightly higher (442–443 Hz) and Baroque groups often use 415 Hz.',
  },
  {
    id: 'mus_78',
    text: 'Which of these is a woodwind instrument that uses a double reed?',
    text_tr: 'Bunlardan hangisi çift kamış kullanan bir tahta üflemeli çalgıdır?',
    options: { A: 'Clarinet', B: 'Flute', C: 'Oboe', D: 'Recorder', E: 'Saxophone' },
    options_tr: { A: 'Klarnet', B: 'Flüt', C: 'Obua', D: 'Blok flüt', E: 'Saksofon' },
    answer: 'C',
    explanation: 'The oboe and bassoon use double reeds; the clarinet and saxophone use single reeds; the flute and recorder use none.',
  },
  {
    id: 'mus_79',
    text: 'Which chord quality is built from a root, a minor third and a diminished fifth?',
    text_tr: 'Bir kök, bir minör üçlü ve bir eksik beşliden oluşan akor cinsi hangisidir?',
    options: { A: 'Major triad', B: 'Minor triad', C: 'Augmented triad', D: 'Diminished triad', E: 'Suspended chord' },
    options_tr: { A: 'Majör üçlü', B: 'Minör üçlü', C: 'Artık üçlü', D: 'Eksik üçlü', E: 'Askılı akor (sus)' },
    answer: 'D',
    explanation: 'Stacking two minor thirds gives a diminished triad; two major thirds gives an augmented triad.',
  },
  {
    id: 'mus_80',
    text: 'Which Austrian composer left his Symphony No. 8 unfinished, so it is known as the "Unfinished Symphony"?',
    text_tr: '8. Senfonisi\'ni yarım bırakan ve bu yüzden "Bitmemiş Senfoni" olarak bilinen Avusturyalı besteci kimdir?',
    options: { A: 'Anton Bruckner', B: 'Gustav Mahler', C: 'Franz Schubert', D: 'Joseph Haydn', E: 'Franz Liszt' },
    options_tr: { A: 'Anton Bruckner', B: 'Gustav Mahler', C: 'Franz Schubert', D: 'Joseph Haydn', E: 'Franz Liszt' },
    answer: 'C',
    explanation: 'Schubert completed only two movements of his Symphony in B minor (1822); it was premiered decades after his death.',
  },
  {
    id: 'mus_81',
    text: 'Which term describes music with a single melodic line and no harmony or accompaniment, such as Gregorian chant?',
    text_tr: 'Gregoryen ilahisi gibi, tek bir ezgi çizgisine sahip; armoni veya eşliği olmayan müziği tanımlayan terim hangisidir?',
    options: { A: 'Homophony', B: 'Monophony', C: 'Polyphony', D: 'Biphony', E: 'Organum' },
    options_tr: { A: 'Homofoni', B: 'Monofoni', C: 'Polifoni', D: 'Bifoni', E: 'Organum' },
    answer: 'B',
    explanation: 'Monophonic texture is a single unaccompanied line, even if sung by many voices in unison.',
  },
  {
    id: 'mus_82',
    text: 'The "Motown Sound" of the 1960s came from a record label based in which US city?',
    text_tr: '1960\'ların "Motown Sound"u, hangi ABD şehrinde kurulu bir plak şirketinden geldi?',
    options: { A: 'Memphis', B: 'Nashville', C: 'Detroit', D: 'Philadelphia', E: 'Chicago' },
    options_tr: { A: 'Memphis', B: 'Nashville', C: 'Detroit', D: 'Philadelphia', E: 'Chicago' },
    answer: 'C',
    explanation: 'Berry Gordy founded Motown in Detroit ("Motor Town"); its artists included The Supremes, Marvin Gaye and Stevie Wonder.',
  },
  {
    id: 'mus_83',
    text: 'Which composer is associated with the musical style called "Impressionism", including works like "Clair de Lune" and "La Mer"?',
    text_tr: '"Clair de Lune" ve "La Mer" gibi eserler dahil "İzlenimcilik" adı verilen müzik tarzıyla özdeşleşen besteci kimdir?',
    options: { A: 'Maurice Ravel', B: 'Claude Debussy', C: 'Erik Satie', D: 'Gabriel Fauré', E: 'César Franck' },
    options_tr: { A: 'Maurice Ravel', B: 'Claude Debussy', C: 'Erik Satie', D: 'Gabriel Fauré', E: 'César Franck' },
    answer: 'B',
    explanation: 'Debussy disliked the "Impressionist" label but is its central figure, using whole-tone scales and unresolved harmony for atmosphere.',
  },
  {
    id: 'mus_84',
    text: 'In a recording studio, what does a "DAW" refer to?',
    text_tr: 'Bir kayıt stüdyosunda "DAW" neyi ifade eder?',
    options: { A: 'Dynamic audio wave', B: 'Digital audio workstation', C: 'Direct amplifier wiring', D: 'Dual analog wave', E: 'Delay and wah unit' },
    options_tr: { A: 'Dinamik ses dalgası', B: 'Dijital ses iş istasyonu (yazılımı)', C: 'Doğrudan amfi kablolaması', D: 'Çift analog dalga', E: 'Delay ve wah ünitesi' },
    answer: 'B',
    explanation: 'A DAW (e.g. Pro Tools, Ableton Live, Logic) is software for recording, editing and mixing audio.',
  },
  {
    id: 'mus_85',
    text: 'Which vocal technique involves rapid, slight fluctuation of pitch to enrich a sustained note?',
    text_tr: 'Sürdürülen bir notayı zenginleştirmek için perdenin hızlı, hafif dalgalanmasını içeren şan tekniği hangisidir?',
    options: { A: 'Falsetto', B: 'Vibrato', C: 'Portamento', D: 'Melisma', E: 'Belting' },
    options_tr: { A: 'Falsetto', B: 'Vibrato', C: 'Portamento', D: 'Melizma', E: 'Belting' },
    answer: 'B',
    explanation: 'Vibrato is a controlled oscillation in pitch (and sometimes intensity) around the central note.',
  },
  {
    id: 'mus_86',
    text: 'Which of the following is a plucked keyboard instrument common in Baroque music, replaced by the piano in the Classical era?',
    text_tr: 'Barok müzikte yaygın olan; Klasik dönemde yerini piyanoya bırakan, telleri çırpılarak (mızraplanarak) çalınan klavyeli çalgı hangisidir?',
    options: { A: 'Celesta', B: 'Harpsichord', C: 'Clavichord', D: 'Organ', E: 'Accordion' },
    options_tr: { A: 'Çelesta', B: 'Klavsen (harpsichord)', C: 'Klavikord', D: 'Org', E: 'Akordeon' },
    answer: 'B',
    explanation: 'The harpsichord plucks its strings with quills, so it cannot vary loudness by touch as the piano can.',
  },
  {
    id: 'mus_87',
    text: 'Which term names the concluding passage that rounds off a movement or piece, often after the main material?',
    text_tr: 'Ana malzemeden sonra bir bölümü veya parçayı tamamlayan bitiş pasajını adlandıran terim hangisidir?',
    options: { A: 'Coda', B: 'Exposition', C: 'Development', D: 'Recapitulation', E: 'Interlude' },
    options_tr: { A: 'Coda', B: 'Sergi (exposition)', C: 'Gelişme (development)', D: 'Yeniden sergi (recapitulation)', E: 'Ara bölüm (interlude)' },
    answer: 'A',
    explanation: '"Coda" (Italian for "tail") is a closing section; a very short one is a "codetta".',
  },
  {
    id: 'mus_88',
    text: 'Which Turkish rock band, formed in the 1990s, is known for songs like "Cambaz" and represented Turkey at Eurovision 2008?',
    text_tr: '1990\'larda kurulan; "Cambaz" gibi şarkılarıyla tanınan ve 2008 Eurovision\'da Türkiye\'yi temsil eden Türk rock grubu hangisidir?',
    options: { A: 'Duman', B: 'mor ve ötesi', C: 'Şebnem Ferah', D: 'Pentagram', E: 'Mavi Sakal' },
    options_tr: { A: 'Duman', B: 'mor ve ötesi', C: 'Şebnem Ferah', D: 'Pentagram', E: 'Mavi Sakal' },
    answer: 'B',
    explanation: 'mor ve ötesi performed "Deli" and finished seventh at Eurovision 2008 in Belgrade.',
  },
  {
    id: 'mus_89',
    text: 'The instrument called the "ney", important in Turkish and Sufi music, is what type of instrument?',
    text_tr: 'Türk ve tasavvuf müziğinde önemli olan "ney", ne tür bir çalgıdır?',
    options: { A: 'A plucked lute', B: 'An end-blown reed flute', C: 'A bowed fiddle', D: 'A hammered dulcimer', E: 'A frame drum' },
    options_tr: { A: 'Mızraplı bir lut', B: 'Uçtan üflemeli bir kamış flüt', C: 'Yaylı bir kemençe', D: 'Tokmakla çalınan bir santur', E: 'Bir çerçeve davul' },
    answer: 'B',
    explanation: 'The ney is an ancient end-blown flute made of reed, central to Mevlevi (whirling dervish) ceremonies.',
  },
  {
    id: 'mus_90',
    text: 'Which of these best describes an "ostinato"?',
    text_tr: 'Aşağıdakilerden hangisi bir "ostinato"yu en iyi tanımlar?',
    options: {
      A: 'A sudden loud accent',
      B: 'A short musical pattern repeated persistently',
      C: 'A key change',
      D: 'A held pause',
      E: 'A solo improvisation',
    },
    options_tr: {
      A: 'Ani, güçlü bir vurgu',
      B: 'Israrla tekrarlanan kısa bir müzikal kalıp',
      C: 'Bir ton (tonalite) değişimi',
      D: 'Tutulan bir duraklama',
      E: 'Bir solo doğaçlama',
    },
    answer: 'B',
    explanation: 'An ostinato ("obstinate") is a motif or phrase that repeats through a passage, often in the bass ("basso ostinato").',
  },
  {
    id: 'mus_91',
    text: 'Which American singer is known as "the King of Rock and Roll"?',
    text_tr: '"Rock and Roll\'un Kralı" olarak bilinen Amerikalı şarkıcı kimdir?',
    options: { A: 'Chuck Berry', B: 'Little Richard', C: 'Elvis Presley', D: 'Buddy Holly', E: 'Jerry Lee Lewis' },
    options_tr: { A: 'Chuck Berry', B: 'Little Richard', C: 'Elvis Presley', D: 'Buddy Holly', E: 'Jerry Lee Lewis' },
    answer: 'C',
    explanation: 'Elvis Presley became a global star from the mid-1950s and remains one of the best-selling solo artists ever.',
  },
  {
    id: 'mus_92',
    text: 'What is the term for the lowest note of a chord, on which the harmony is built?',
    text_tr: 'Bir akorun, armoninin üzerine kurulduğu en pes notasına ne denir?',
    options: { A: 'The leading tone', B: 'The root', C: 'The seventh', D: 'The mediant', E: 'The subdominant' },
    options_tr: { A: 'Yeden ses (leading tone)', B: 'Kök (root)', C: 'Yedili (7\'li)', D: 'Ortancıl (mediant)', E: 'Alt çeken (subdominant)' },
    answer: 'B',
    explanation: 'The root gives the chord its name; when another chord tone is in the bass, the chord is "inverted".',
  },
  {
    id: 'mus_93',
    text: 'Which festival, held on a dairy farm in New York in 1969, became a symbol of the 1960s counterculture?',
    text_tr: '1969\'da New York\'ta bir süt çiftliğinde düzenlenen ve 1960\'lar karşı kültürünün simgesi hâline gelen festival hangisidir?',
    options: { A: 'Monterey Pop', B: 'Woodstock', C: 'Isle of Wight', D: 'Altamont', E: 'Newport Folk' },
    options_tr: { A: 'Monterey Pop', B: 'Woodstock', C: 'Isle of Wight', D: 'Altamont', E: 'Newport Folk' },
    answer: 'B',
    explanation: 'Woodstock drew an estimated 400,000 people over four days in August 1969.',
  },
  {
    id: 'mus_94',
    text: 'Which term describes shortening a note so it sounds detached, marked with a dot above or below the notehead?',
    text_tr: 'Bir notayı kısaltarak kopuk (ayrık) tınlamasını sağlayan, nota başının altına veya üstüne bir nokta ile gösterilen terim hangisidir?',
    options: { A: 'Legato', B: 'Tenuto', C: 'Staccato', D: 'Marcato', E: 'Portato' },
    options_tr: { A: 'Legato', B: 'Tenuto', C: 'Stakato', D: 'Markato', E: 'Portato' },
    answer: 'C',
    explanation: 'Staccato notes are played short and separated; legato notes are smoothly connected.',
  },
  {
    id: 'mus_95',
    text: 'Which composer wrote "The Nutcracker" and "1812 Overture"?',
    text_tr: '"Fındıkkıran" ve "1812 Uvertürü"nü hangi besteci yazdı?',
    options: { A: 'Nikolai Rimsky-Korsakov', B: 'Pyotr Ilyich Tchaikovsky', C: 'Alexander Borodin', D: 'Sergei Rachmaninoff', E: 'Modest Mussorgsky' },
    options_tr: { A: 'Nikolay Rimski-Korsakov', B: 'Pyotr İlyiç Çaykovski', C: 'Aleksandr Borodin', D: 'Sergey Rahmaninov', E: 'Modest Musorgski' },
    answer: 'B',
    explanation: 'The 1812 Overture famously scores real cannon fire; "The Nutcracker" is a Christmas ballet staple.',
  },
  {
    id: 'mus_96',
    text: 'How many strings does a standard classical/acoustic guitar have?',
    text_tr: 'Standart bir klasik/akustik gitarın kaç teli vardır?',
    options: { A: '4', B: '5', C: '6', D: '7', E: '12' },
    options_tr: { A: '4', B: '5', C: '6', D: '7', E: '12' },
    answer: 'C',
    explanation: 'A standard guitar has six strings tuned E–A–D–G–B–E. Twelve-string guitars double each course.',
  },
  {
    id: 'mus_97',
    text: 'Which term describes the simultaneous sounding of notes to form chords, and the study of how they progress?',
    text_tr: 'Akorları oluşturmak üzere notaların aynı anda tınlamasını ve bunların nasıl ilerlediğinin incelenmesini tanımlayan terim hangisidir?',
    options: { A: 'Melody', B: 'Rhythm', C: 'Harmony', D: 'Form', E: 'Dynamics' },
    options_tr: { A: 'Ezgi', B: 'Ritim', C: 'Armoni', D: 'Biçim', E: 'Nüans' },
    answer: 'C',
    explanation: 'Harmony concerns vertical combinations of pitches and the "harmonic progression" from chord to chord.',
  },
  {
    id: 'mus_98',
    text: 'Which of these singers is a famous countertenor / male soprano voice type example historically associated with Baroque opera roles?',
    text_tr: 'Tarihsel olarak Barok opera rolleriyle ilişkilendirilen, ünlü bir kontratenor / erkek soprano ses türü örneği aşağıdakilerden hangisidir?',
    options: { A: 'The castrato', B: 'The baritone', C: 'The basso profondo', D: 'The lyric tenor', E: 'The heldentenor' },
    options_tr: { A: 'Kastrato', B: 'Bariton', C: 'Basso profondo', D: 'Lirik tenor', E: 'Heldentenor' },
    answer: 'A',
    explanation: 'Castrati sang soprano and alto roles in Baroque opera; modern productions use countertenors or women instead.',
  },
  {
    id: 'mus_99',
    text: 'Which pop artist released the record-breaking album "1989" and re-recorded her early catalogue as "(Taylor\'s Version)"?',
    text_tr: 'Rekor kıran "1989" albümünü yayımlayan ve erken dönem kayıtlarını "(Taylor\'s Version)" olarak yeniden kaydeden pop sanatçısı kimdir?',
    options: { A: 'Katy Perry', B: 'Taylor Swift', C: 'Ariana Grande', D: 'Lady Gaga', E: 'Adele' },
    options_tr: { A: 'Katy Perry', B: 'Taylor Swift', C: 'Ariana Grande', D: 'Lady Gaga', E: 'Adele' },
    answer: 'B',
    explanation: 'Taylor Swift began re-recording her first six albums in 2021 to own her master recordings.',
  },
  {
    id: 'mus_100',
    text: 'Which rhythmic value lasts twice as long as a quarter note (crotchet)?',
    text_tr: 'Dörtlük nota (siyah) kadar sürenin iki katı kadar süren ritmik değer hangisidir?',
    options: { A: 'An eighth note (quaver)', B: 'A half note (minim)', C: 'A whole note (semibreve)', D: 'A sixteenth note (semiquaver)', E: 'A dotted quarter note' },
    options_tr: { A: 'Sekizlik nota (kuyruklu)', B: 'İkilik nota (beyaz)', C: 'Birlik nota (yuvarlak)', D: 'On altılık nota', E: 'Noktalı dörtlük nota' },
    answer: 'B',
    explanation: 'A half note = two quarter notes; a whole note = four quarter notes.',
  },
];

module.exports = { music };
