'use strict';

const philosophy = [
  {
    id: 'phi_01',
    text: 'Which ancient Greek philosopher is famous for the phrase "I know that I know nothing"?',
    text_tr: '"Bildiğim tek şey hiçbir şey bilmediğimdir" sözüyle ünlü antik Yunan filozof kimdir?',
    options: { A: 'Plato', B: 'Aristotle', C: 'Socrates', D: 'Pythagoras', E: 'Heraclitus' },
    options_tr: { A: 'Platon', B: 'Aristoteles', C: 'Sokrates', D: 'Pisagor', E: 'Herakleitos' },
    answer: 'C',
    explanation: 'Socrates is associated with this statement of humble ignorance, part of what is now called "Socratic wisdom."',
  },
  {
    id: 'phi_02',
    text: 'Which philosopher wrote "The Republic," describing his vision of an ideal state ruled by philosopher-kings?',
    text_tr: 'Filozof-kralların yönettiği ideal bir devlet vizyonunu anlatan "Devlet"i kim yazmıştır?',
    options: { A: 'Aristotle', B: 'Plato', C: 'Socrates', D: 'Epicurus', E: 'Zeno of Citium' },
    options_tr: { A: 'Aristoteles', B: 'Platon', C: 'Sokrates', D: 'Epikuros', E: 'Kitionlu Zenon' },
    answer: 'B',
    explanation: 'Plato\'s "The Republic" (c. 375 BC) is one of the most influential works in the history of philosophy and political theory.',
  },
  {
    id: 'phi_03',
    text: 'Which French philosopher wrote "Cogito, ergo sum" ("I think, therefore I am")?',
    text_tr: '"Düşünüyorum, öyleyse varım" (Cogito, ergo sum) sözünü yazan Fransız filozof kimdir?',
    options: { A: 'Voltaire', B: 'René Descartes', C: 'Jean-Jacques Rousseau', D: 'Blaise Pascal', E: 'Michel de Montaigne' },
    options_tr: { A: 'Voltaire', B: 'René Descartes', C: 'Jean-Jacques Rousseau', D: 'Blaise Pascal', E: 'Michel de Montaigne' },
    answer: 'B',
    explanation: 'René Descartes used this statement as a foundational certainty in his 1637 work "Discourse on the Method."',
  },
  {
    id: 'phi_04',
    text: 'Which branch of philosophy deals with questions of right and wrong, and moral conduct?',
    text_tr: 'Doğru ve yanlış, ahlaki davranış sorularıyla ilgilenen felsefe dalı hangisidir?',
    options: { A: 'Epistemology', B: 'Metaphysics', C: 'Ethics', D: 'Aesthetics', E: 'Logic' },
    options_tr: { A: 'Epistemoloji', B: 'Metafizik', C: 'Etik', D: 'Estetik', E: 'Mantık' },
    answer: 'C',
    explanation: 'Ethics (moral philosophy) studies concepts of right and wrong behavior, justice, and virtue.',
  },
  {
    id: 'phi_05',
    text: 'Which German philosopher wrote "Thus Spoke Zarathustra" and proposed the concept of the "Übermensch" (Overman)?',
    text_tr: '"Böyle Buyurdu Zerdüşt"ü yazan ve "Übermensch" (Üstinsan) kavramını öne süren Alman filozof kimdir?',
    options: { A: 'Arthur Schopenhauer', B: 'Friedrich Nietzsche', C: 'Georg Wilhelm Friedrich Hegel', D: 'Immanuel Kant', E: 'Martin Heidegger' },
    options_tr: { A: 'Arthur Schopenhauer', B: 'Friedrich Nietzsche', C: 'Georg Wilhelm Friedrich Hegel', D: 'Immanuel Kant', E: 'Martin Heidegger' },
    answer: 'B',
    explanation: 'Friedrich Nietzsche introduced the Übermensch concept in "Thus Spoke Zarathustra" (1883–1885).',
  },
  {
    id: 'phi_06',
    text: 'Which student of Socrates went on to found the Academy in Athens and later taught Aristotle?',
    text_tr: 'Sokrates\'in öğrencisi olup Atina\'da Akademi\'yi kuran ve daha sonra Aristoteles\'e ders veren kimdir?',
    options: { A: 'Xenophon', B: 'Plato', C: 'Antisthenes', D: 'Aristippus', E: 'Euclid of Megara' },
    options_tr: { A: 'Ksenophon', B: 'Platon', C: 'Antisthenes', D: 'Aristippos', E: 'Megaralı Euklid' },
    answer: 'B',
    explanation: 'Plato founded the Academy around 387 BC, where Aristotle studied for about 20 years.',
  },
  {
    id: 'phi_07',
    text: 'Which philosophical school, founded by Zeno of Citium, taught that virtue and self-control lead to a life free of destructive emotions?',
    text_tr: 'Kitionlu Zenon tarafından kurulan ve erdem ile öz kontrolün yıkıcı duygulardan arınmış bir yaşama yol açtığını öğreten felsefi okul hangisidir?',
    options: { A: 'Epicureanism', B: 'Stoicism', C: 'Cynicism', D: 'Skepticism', E: 'Hedonism' },
    options_tr: { A: 'Epikürcülük', B: 'Stoacılık', C: 'Kinizm', D: 'Kuşkuculuk (Şüphecilik)', E: 'Hedonizm' },
    answer: 'B',
    explanation: 'Stoicism, founded around 300 BC, emphasizes virtue, reason, and living in accordance with nature.',
  },
  {
    id: 'phi_08',
    text: 'Which German philosopher wrote "Critique of Pure Reason" and developed the concept of the "categorical imperative"?',
    text_tr: '"Saf Aklın Eleştirisi"ni yazan ve "kategorik buyruk" (categorical imperative) kavramını geliştiren Alman filozof kimdir?',
    options: { A: 'Georg Wilhelm Friedrich Hegel', B: 'Immanuel Kant', C: 'Arthur Schopenhauer', D: 'Johann Gottlieb Fichte', E: 'Friedrich Schelling' },
    options_tr: { A: 'Georg Wilhelm Friedrich Hegel', B: 'Immanuel Kant', C: 'Arthur Schopenhauer', D: 'Johann Gottlieb Fichte', E: 'Friedrich Schelling' },
    answer: 'B',
    explanation: 'Immanuel Kant published "Critique of Pure Reason" in 1781 and developed the categorical imperative as a basis for moral duty.',
  },
  {
    id: 'phi_09',
    text: 'Which branch of philosophy is concerned with the nature of knowledge, belief, and justification?',
    text_tr: 'Bilginin, inancın ve gerekçelendirmenin doğasıyla ilgilenen felsefe dalı hangisidir?',
    options: { A: 'Epistemology', B: 'Ethics', C: 'Aesthetics', D: 'Metaphysics', E: 'Political philosophy' },
    options_tr: { A: 'Epistemoloji', B: 'Etik', C: 'Estetik', D: 'Metafizik', E: 'Siyaset felsefesi' },
    answer: 'A',
    explanation: 'Epistemology studies what knowledge is, how it is acquired, and how we can be certain of what we believe.',
  },
  {
    id: 'phi_10',
    text: 'Which pre-Socratic philosopher is famous for the idea that "you cannot step into the same river twice," emphasizing constant change?',
    text_tr: 'Sürekli değişimi vurgulayarak "aynı nehre iki kez giremezsin" fikriyle tanınan Sokrates öncesi filozof kimdir?',
    options: { A: 'Thales', B: 'Anaximander', C: 'Heraclitus', D: 'Parmenides', E: 'Democritus' },
    options_tr: { A: 'Tales', B: 'Anaksimandros', C: 'Herakleitos', D: 'Parmenides', E: 'Demokritos' },
    answer: 'C',
    explanation: 'Heraclitus of Ephesus emphasized constant flux ("panta rhei," everything flows) as the fundamental nature of reality.',
  },
  {
    id: 'phi_11',
    text: 'Which English philosopher wrote "Leviathan," arguing that human life in a state of nature is "solitary, poor, nasty, brutish, and short"?',
    text_tr: 'Doğa halindeki insan yaşamının "yalnız, yoksul, iğrenç, canavarca ve kısa" olduğunu savunan "Leviathan"ı yazan İngiliz filozof kimdir?',
    options: { A: 'John Locke', B: 'Thomas Hobbes', C: 'David Hume', D: 'Francis Bacon', E: 'Jeremy Bentham' },
    options_tr: { A: 'John Locke', B: 'Thomas Hobbes', C: 'David Hume', D: 'Francis Bacon', E: 'Jeremy Bentham' },
    answer: 'B',
    explanation: 'Thomas Hobbes published Leviathan in 1651, arguing for a strong central authority to prevent the chaos of the state of nature.',
  },
  {
    id: 'phi_12',
    text: 'Which Ottoman-era Turkish/Islamic scholar, known in the West as "Averroes," wrote influential commentaries on Aristotle?',
    text_tr: 'Batı\'da "Averroes" olarak bilinen ve Aristoteles üzerine etkili yorumlar yazan İslam alimi kimdir?',
    options: { A: 'Al-Ghazali', B: 'Ibn Sina (Avicenna)', C: 'Ibn Rushd', D: 'Al-Farabi', E: 'Ibn Khaldun' },
    options_tr: { A: 'Gazali', B: 'İbn Sina', C: 'İbn Rüşd', D: 'Farabi', E: 'İbn Haldun' },
    answer: 'C',
    explanation: 'Ibn Rushd (Averroes, 1126–1198), from Córdoba, wrote extensive commentaries on Aristotle that greatly influenced medieval European philosophy.',
  },
  {
    id: 'phi_13',
    text: 'Which English philosopher argued in "An Essay Concerning Human Understanding" that the mind begins as a "tabula rasa" (blank slate)?',
    text_tr: '"İnsan Anlığı Üzerine Bir Deneme"de zihnin "tabula rasa" (boş levha) olarak başladığını savunan İngiliz filozof kimdir?',
    options: { A: 'David Hume', B: 'John Locke', C: 'George Berkeley', D: 'Thomas Hobbes', E: 'John Stuart Mill' },
    options_tr: { A: 'David Hume', B: 'John Locke', C: 'George Berkeley', D: 'Thomas Hobbes', E: 'John Stuart Mill' },
    answer: 'B',
    explanation: 'John Locke argued that all knowledge comes from experience, published in his 1689 "Essay Concerning Human Understanding."',
  },
  {
    id: 'phi_14',
    text: 'Which branch of philosophy studies the nature of reality, existence, and the fundamental structure of the world?',
    text_tr: 'Gerçekliğin, varlığın ve dünyanın temel yapısının doğasını inceleyen felsefe dalı hangisidir?',
    options: { A: 'Metaphysics', B: 'Epistemology', C: 'Ethics', D: 'Logic', E: 'Aesthetics' },
    options_tr: { A: 'Metafizik', B: 'Epistemoloji', C: 'Etik', D: 'Mantık', E: 'Estetik' },
    answer: 'A',
    explanation: 'Metaphysics deals with questions about being, existence, causality, time, and the nature of reality.',
  },
  {
    id: 'phi_15',
    text: 'Which philosopher, a student of Plato, wrote extensively on logic, ethics, and natural science, and famously tutored Alexander the Great?',
    text_tr: 'Platon\'un öğrencisi olan ve mantık, etik ve doğa bilimleri üzerine kapsamlı eserler yazan, Büyük İskender\'in öğretmenliğini yapmasıyla ünlü filozof kimdir?',
    options: { A: 'Diogenes', B: 'Aristotle', C: 'Epicurus', D: 'Pyrrho', E: 'Speusippus' },
    options_tr: { A: 'Diyojen', B: 'Aristoteles', C: 'Epikuros', D: 'Pyrrhon', E: 'Speusippos' },
    answer: 'B',
    explanation: 'Aristotle studied under Plato and later tutored Alexander the Great before founding his own school, the Lyceum.',
  },
  {
    id: 'phi_16',
    text: 'Which Turkish/Islamic philosopher, known in Latin as "Avicenna," wrote "The Canon of Medicine" and made major contributions to metaphysics?',
    text_tr: 'Latincede "Avicenna" olarak bilinen ve "Tıp Kanunu"nu yazan, metafiziğe önemli katkılarda bulunan filozof kimdir?',
    options: { A: 'Al-Kindi', B: 'Ibn Sina', C: 'Al-Razi', D: 'Al-Biruni', E: 'Ibn Tufail' },
    options_tr: { A: 'El-Kindi', B: 'İbn Sina', C: 'Er-Razi', D: 'El-Biruni', E: 'İbn Tufeyl' },
    answer: 'B',
    explanation: 'Ibn Sina (Avicenna, 980–1037), born near Bukhara, was one of the most significant physicians and philosophers of the Islamic Golden Age.',
  },
  {
    id: 'phi_17',
    text: 'Which philosophical position holds that pleasure and the absence of pain are the highest good?',
    text_tr: 'Hazzın ve acının yokluğunun en yüksek iyi olduğunu savunan felsefi görüş hangisidir?',
    options: { A: 'Stoicism', B: 'Hedonism', C: 'Nihilism', D: 'Existentialism', E: 'Rationalism' },
    options_tr: { A: 'Stoacılık', B: 'Hedonizm', C: 'Nihilizm', D: 'Varoluşçuluk', E: 'Rasyonalizm' },
    answer: 'B',
    explanation: 'Hedonism, associated with philosophers like Epicurus, holds that pleasure (often understood as tranquility) is the highest good.',
  },
  {
    id: 'phi_18',
    text: 'Which 20th-century French philosopher and writer, associated with existentialism, wrote "Being and Nothingness" and declined the Nobel Prize in Literature?',
    text_tr: 'Varoluşçulukla ilişkilendirilen ve "Varlık ve Hiçlik"i yazan, Nobel Edebiyat Ödülü\'nü reddeden 20. yüzyıl Fransız filozof ve yazar kimdir?',
    options: { A: 'Albert Camus', B: 'Jean-Paul Sartre', C: 'Maurice Merleau-Ponty', D: 'Michel Foucault', E: 'Gabriel Marcel' },
    options_tr: { A: 'Albert Camus', B: 'Jean-Paul Sartre', C: 'Maurice Merleau-Ponty', D: 'Michel Foucault', E: 'Gabriel Marcel' },
    answer: 'B',
    explanation: 'Jean-Paul Sartre declined the 1964 Nobel Prize in Literature, stating he always declined official honors.',
  },
  {
    id: 'phi_19',
    text: 'Which Danish philosopher is often considered the father of existentialism, writing under pseudonyms like "Johannes Climacus"?',
    text_tr: '"Johannes Climacus" gibi takma adlarla yazan ve genellikle varoluşçuluğun babası sayılan Danimarkalı filozof kimdir?',
    options: { A: 'Søren Kierkegaard', B: 'Friedrich Nietzsche', C: 'Martin Heidegger', D: 'Karl Jaspers', E: 'Edmund Husserl' },
    options_tr: { A: 'Søren Kierkegaard', B: 'Friedrich Nietzsche', C: 'Martin Heidegger', D: 'Karl Jaspers', E: 'Edmund Husserl' },
    answer: 'A',
    explanation: 'Søren Kierkegaard (1813–1855) explored individual existence, choice, and faith, and is widely regarded as the first existentialist philosopher.',
  },
  {
    id: 'phi_20',
    text: 'Which Chinese philosopher\'s teachings, emphasizing filial piety, ritual, and moral virtue, formed the basis of Confucianism?',
    text_tr: 'Ebeveyne saygı, tören ve ahlaki erdemi vurgulayan öğretileri Konfüçyüsçülüğün temelini oluşturan Çinli filozof kimdir?',
    options: { A: 'Laozi', B: 'Confucius', C: 'Mencius', D: 'Mozi', E: 'Zhuangzi' },
    options_tr: { A: 'Laozi', B: 'Konfüçyüs', C: 'Mengzi (Mencius)', D: 'Mozi', E: 'Zhuangzi' },
    answer: 'B',
    explanation: 'Confucius (551–479 BC) founded a philosophical and ethical system focused on personal and governmental morality.',
  },
  {
    id: 'phi_21',
    text: 'Which Chinese philosopher is credited as the founder of Taoism and the author (traditionally) of the "Tao Te Ching"?',
    text_tr: 'Taoizmin kurucusu olarak kabul edilen ve geleneksel olarak "Tao Te Ching"in yazarı sayılan Çinli filozof kimdir?',
    options: { A: 'Confucius', B: 'Laozi', C: 'Sun Tzu', D: 'Han Feizi', E: 'Xunzi' },
    options_tr: { A: 'Konfüçyüs', B: 'Laozi', C: 'Sun Tzu', D: 'Han Feizi', E: 'Xunzi' },
    answer: 'B',
    explanation: 'Laozi is the semi-legendary author credited with the "Tao Te Ching," the foundational text of Taoism.',
  },
  {
    id: 'phi_22',
    text: 'Which branch of philosophy studies the nature of beauty, art, and taste?',
    text_tr: 'Güzelliğin, sanatın ve zevkin doğasını inceleyen felsefe dalı hangisidir?',
    options: { A: 'Ethics', B: 'Aesthetics', C: 'Logic', D: 'Metaphysics', E: 'Epistemology' },
    options_tr: { A: 'Etik', B: 'Estetik', C: 'Mantık', D: 'Metafizik', E: 'Epistemoloji' },
    answer: 'B',
    explanation: 'Aesthetics examines questions about beauty, artistic value, and the nature of aesthetic experience.',
  },
  {
    id: 'phi_23',
    text: 'Which German philosopher developed the dialectical method of thesis-antithesis-synthesis and wrote "Phenomenology of Spirit"?',
    text_tr: 'Tez-antitez-sentez diyalektik yöntemini geliştiren ve "Tinin Fenomenolojisi"ni yazan Alman filozof kimdir?',
    options: { A: 'Immanuel Kant', B: 'Georg Wilhelm Friedrich Hegel', C: 'Karl Marx', D: 'Arthur Schopenhauer', E: 'Friedrich Schelling' },
    options_tr: { A: 'Immanuel Kant', B: 'Georg Wilhelm Friedrich Hegel', C: 'Karl Marx', D: 'Arthur Schopenhauer', E: 'Friedrich Schelling' },
    answer: 'B',
    explanation: 'Hegel\'s dialectical method profoundly influenced later philosophy, including Karl Marx\'s dialectical materialism.',
  },
  {
    id: 'phi_24',
    text: 'Which German philosopher and economist, co-author of "The Communist Manifesto," argued that history is driven by class struggle?',
    text_tr: '"Komünist Manifesto"nun ortak yazarı olan ve tarihin sınıf mücadelesi tarafından yönlendirildiğini savunan Alman filozof ve ekonomist kimdir?',
    options: { A: 'Friedrich Engels', B: 'Karl Marx', C: 'Vladimir Lenin', D: 'Max Weber', E: 'Antonio Gramsci' },
    options_tr: { A: 'Friedrich Engels', B: 'Karl Marx', C: 'Vladimir Lenin', D: 'Max Weber', E: 'Antonio Gramsci' },
    answer: 'B',
    explanation: 'Karl Marx, with Friedrich Engels, co-wrote "The Communist Manifesto" (1848) and developed historical materialism.',
  },
  {
    id: 'phi_25',
    text: 'Which philosophical school of ancient Greece, associated with Diogenes, rejected social conventions and advocated living in accordance with nature in the simplest way?',
    text_tr: 'Diyojen ile ilişkilendirilen ve toplumsal gelenekleri reddedip doğaya en basit şekilde uygun yaşamayı savunan antik Yunan felsefi okulu hangisidir?',
    options: { A: 'Stoicism', B: 'Epicureanism', C: 'Cynicism', D: 'Skepticism', E: 'Platonism' },
    options_tr: { A: 'Stoacılık', B: 'Epikürcülük', C: 'Kinizm', D: 'Kuşkuculuk', E: 'Platonculuk' },
    answer: 'C',
    explanation: 'Diogenes of Sinope, the most famous Cynic, was known for extreme asceticism and rejecting conventional social norms.',
  },
  {
    id: 'phi_26',
    text: 'Which Turkish/Central Asian philosopher, known as "the Second Teacher" (after Aristotle), wrote extensively on logic and political philosophy?',
    text_tr: '(Aristoteles\'ten sonra) "İkinci Öğretmen" olarak bilinen ve mantık ile siyaset felsefesi üzerine kapsamlı eserler yazan Türk/Orta Asyalı filozof kimdir?',
    options: { A: 'Al-Kindi', B: 'Al-Farabi', C: 'Al-Ghazali', D: 'Ibn Khaldun', E: 'Al-Razi' },
    options_tr: { A: 'El-Kindi', B: 'Farabi', C: 'Gazali', D: 'İbn Haldun', E: 'Er-Razi' },
    answer: 'B',
    explanation: 'Al-Farabi (c. 872–950), born in Central Asia, was called "the Second Teacher" for his influential commentaries on Aristotelian logic.',
  },
  {
    id: 'phi_27',
    text: 'Which philosophical position argues that knowledge comes primarily from sensory experience, contrasted with rationalism?',
    text_tr: 'Bilginin öncelikle duyusal deneyimden geldiğini savunan ve rasyonalizmle karşıtlaştırılan felsefi görüş hangisidir?',
    options: { A: 'Rationalism', B: 'Empiricism', C: 'Idealism', D: 'Dualism', E: 'Materialism' },
    options_tr: { A: 'Rasyonalizm', B: 'Ampirizm', C: 'İdealizm', D: 'Düalizm (İkicilik)', E: 'Materyalizm' },
    answer: 'B',
    explanation: 'Empiricism, championed by philosophers like Locke, Berkeley, and Hume, holds that knowledge is derived mainly from sensory experience.',
  },
  {
    id: 'phi_28',
    text: 'Which Scottish philosopher, a leading empiricist, argued that causation is not directly observed but inferred from habitual conjunction of events?',
    text_tr: 'Nedenselliğin doğrudan gözlemlenmediğini, olayların alışılmış birlikteliğinden çıkarsandığını savunan önde gelen ampirist İskoç filozof kimdir?',
    options: { A: 'Adam Smith', B: 'David Hume', C: 'Thomas Reid', D: 'Francis Hutcheson', E: 'Dugald Stewart' },
    options_tr: { A: 'Adam Smith', B: 'David Hume', C: 'Thomas Reid', D: 'Francis Hutcheson', E: 'Dugald Stewart' },
    answer: 'B',
    explanation: 'David Hume\'s skepticism about causation, presented in his 1739 "A Treatise of Human Nature," deeply influenced later philosophy.',
  },
  {
    id: 'phi_29',
    text: 'Which Islamic philosopher and theologian, author of "The Incoherence of the Philosophers," criticized the use of Greek philosophy in Islamic thought?',
    text_tr: '"Filozofların Tutarsızlığı"nın yazarı olan ve İslam düşüncesinde Yunan felsefesinin kullanılmasını eleştiren İslam filozof ve din bilgini kimdir?',
    options: { A: 'Ibn Rushd', B: 'Al-Ghazali', C: 'Al-Farabi', D: 'Ibn Sina', E: 'Al-Kindi' },
    options_tr: { A: 'İbn Rüşd', B: 'Gazali', C: 'Farabi', D: 'İbn Sina', E: 'El-Kindi' },
    answer: 'B',
    explanation: 'Al-Ghazali\'s "The Incoherence of the Philosophers" (11th century) criticized the reliance on Aristotelian philosophy by earlier Islamic thinkers.',
  },
  {
    id: 'phi_30',
    text: 'Which Turkish word, borrowed from Arabic, is the standard term for "philosophy" in modern Turkish?',
    text_tr: 'Arapçadan alınan ve modern Türkçede "felsefe" için standart terim olan kelime hangisidir?',
    options: { A: 'Hikmet', B: 'Felsefe', C: 'Mantık', D: 'İrfan', E: 'Tefekkür' },
    options_tr: { A: 'Hikmet', B: 'Felsefe', C: 'Mantık', D: 'İrfan', E: 'Tefekkür' },
    answer: 'B',
    explanation: '"Felsefe" is the standard Turkish word for philosophy, ultimately derived from the Greek "philosophia" via Arabic.',
  },
  {
    id: 'phi_31',
    text: 'Which philosophical thought experiment, proposed by philosopher John Searle, argues that a computer running a program cannot truly "understand" language?',
    text_tr: 'Bir program çalıştıran bilgisayarın gerçekten dil "anlayamayacağını" savunan, filozof John Searle tarafından önerilen düşünce deneyi hangisidir?',
    options: { A: 'The Trolley Problem', B: 'The Chinese Room', C: 'The Brain in a Vat', D: 'Schrödinger\'s Cat (physics, not philosophy)', E: 'The Ship of Theseus' },
    options_tr: { A: 'Tramvay Problemi', B: 'Çin Odası', C: 'Fıçıdaki Beyin', D: 'Schrödinger\'in Kedisi (fizik, felsefe değil)', E: 'Theseus\'un Gemisi' },
    answer: 'B',
    explanation: 'John Searle proposed the Chinese Room argument in 1980 to challenge claims of "strong AI" — that symbol manipulation alone constitutes understanding.',
  },
  {
    id: 'phi_32',
    text: 'Which ethical thought experiment asks whether it is morally acceptable to divert a runaway trolley to kill one person instead of five?',
    text_tr: 'Kaçak bir tramvayı beş kişi yerine bir kişiyi öldürecek şekilde yönlendirmenin ahlaki açıdan kabul edilebilir olup olmadığını soran etik düşünce deneyi hangisidir?',
    options: { A: 'The Chinese Room', B: 'The Trolley Problem', C: 'The Veil of Ignorance', D: 'The Prisoner\'s Dilemma', E: 'The Ship of Theseus' },
    options_tr: { A: 'Çin Odası', B: 'Tramvay Problemi', C: 'Cehalet Perdesi', D: 'Mahkumların İkilemi', E: 'Theseus\'un Gemisi' },
    answer: 'B',
    explanation: 'The Trolley Problem, introduced by philosopher Philippa Foot in 1967, is a classic thought experiment in ethics concerning action versus inaction.',
  },
  {
    id: 'phi_33',
    text: 'Which ancient philosophical puzzle asks whether an object that has had all its components replaced remains fundamentally the same object?',
    text_tr: 'Tüm bileşenleri değiştirilen bir nesnenin temelde aynı nesne olup olmadığını soran antik felsefi bilmece hangisidir?',
    options: { A: 'Zeno\'s Paradox', B: 'The Ship of Theseus', C: 'The Liar Paradox', D: 'The Sorites Paradox', E: 'Buridan\'s Ass' },
    options_tr: { A: 'Zenon Paradoksu', B: 'Theseus\'un Gemisi', C: 'Yalancı Paradoksu', D: 'Sorites Paradoksu', E: 'Buridan\'ın Eşeği' },
    answer: 'B',
    explanation: 'The Ship of Theseus paradox questions identity and persistence over time, discussed since Plutarch\'s writings in antiquity.',
  },
  {
    id: 'phi_34',
    text: 'Which German philosopher argued in "Being and Time" that human existence ("Dasein") is fundamentally characterized by its relationship to time and mortality?',
    text_tr: '"Varlık ve Zaman"da insan varoluşunun ("Dasein") temelde zaman ve ölümlülükle ilişkisiyle karakterize edildiğini savunan Alman filozof kimdir?',
    options: { A: 'Edmund Husserl', B: 'Martin Heidegger', C: 'Karl Jaspers', D: 'Hans-Georg Gadamer', E: 'Max Scheler' },
    options_tr: { A: 'Edmund Husserl', B: 'Martin Heidegger', C: 'Karl Jaspers', D: 'Hans-Georg Gadamer', E: 'Max Scheler' },
    answer: 'B',
    explanation: 'Martin Heidegger\'s "Being and Time" (1927) is a foundational text of 20th-century existential and phenomenological philosophy.',
  },
  {
    id: 'phi_35',
    text: 'Which utilitarian philosopher argued that actions are right if they promote "the greatest happiness of the greatest number"?',
    text_tr: 'Eylemlerin "en fazla sayıda insanın en büyük mutluluğunu" desteklediğinde doğru olduğunu savunan faydacı filozof kimdir?',
    options: { A: 'John Stuart Mill', B: 'Jeremy Bentham', C: 'Immanuel Kant', D: 'John Locke', E: 'Thomas Hobbes' },
    options_tr: { A: 'John Stuart Mill', B: 'Jeremy Bentham', C: 'Immanuel Kant', D: 'John Locke', E: 'Thomas Hobbes' },
    answer: 'B',
    explanation: 'Jeremy Bentham founded classical utilitarianism, later refined by his student John Stuart Mill.',
  },
  {
    id: 'phi_36',
    text: 'Which philosopher, a student of Bentham, wrote "Utilitarianism" and "On Liberty," defending individual freedom and refined the utilitarian ethical theory?',
    text_tr: 'Bentham\'ın öğrencisi olan ve "Faydacılık" ile "Özgürlük Üzerine"yi yazarak bireysel özgürlüğü savunan ve faydacı etik teorisini geliştiren filozof kimdir?',
    options: { A: 'Herbert Spencer', B: 'John Stuart Mill', C: 'Henry Sidgwick', D: 'G.E. Moore', E: 'Bertrand Russell' },
    options_tr: { A: 'Herbert Spencer', B: 'John Stuart Mill', C: 'Henry Sidgwick', D: 'G.E. Moore', E: 'Bertrand Russell' },
    answer: 'B',
    explanation: 'John Stuart Mill published "On Liberty" in 1859 and "Utilitarianism" in 1861, both foundational texts of liberal and utilitarian thought.',
  },
  {
    id: 'phi_37',
    text: 'Which branch of philosophy studies the principles of valid reasoning and argumentation?',
    text_tr: 'Geçerli akıl yürütme ve tartışma ilkelerini inceleyen felsefe dalı hangisidir?',
    options: { A: 'Logic', B: 'Ethics', C: 'Aesthetics', D: 'Metaphysics', E: 'Epistemology' },
    options_tr: { A: 'Mantık', B: 'Etik', C: 'Estetik', D: 'Metafizik', E: 'Epistemoloji' },
    answer: 'A',
    explanation: 'Logic studies the structure of valid arguments and inference, foundational to philosophy since Aristotle\'s "Organon."',
  },
  {
    id: 'phi_38',
    text: 'Which 20th-century philosopher and Nazi party member is nonetheless considered one of the most influential phenomenologists, known for "Being and Time"?',
    text_tr: 'Nazi partisi üyesi olmasına rağmen "Varlık ve Zaman" ile tanınan ve en etkili fenomenologlardan biri sayılan 20. yüzyıl filozofu kimdir?',
    options: { A: 'Edmund Husserl', B: 'Martin Heidegger', C: 'Karl Jaspers', D: 'Max Horkheimer', E: 'Theodor Adorno' },
    options_tr: { A: 'Edmund Husserl', B: 'Martin Heidegger', C: 'Karl Jaspers', D: 'Max Horkheimer', E: 'Theodor Adorno' },
    answer: 'B',
    explanation: 'Martin Heidegger joined the Nazi party in 1933; his philosophical legacy remains hugely influential but controversial due to this history.',
  },
  {
    id: 'phi_39',
    text: 'Which Turkish/Ottoman scholar wrote "Muqaddimah" (Introduction), a foundational work in the philosophy of history and sociology?',
    text_tr: 'Tarih felsefesi ve sosyolojide temel bir eser olan "Mukaddime"yi yazan (Kuzey Afrikalı) alim kimdir?',
    options: { A: 'Ibn Khaldun', B: 'Al-Biruni', C: 'Ibn Battuta', D: 'Al-Tabari', E: 'Ibn al-Nafis' },
    options_tr: { A: 'İbn Haldun', B: 'El-Biruni', C: 'İbn Battuta', D: 'Et-Taberi', E: 'İbn en-Nefis' },
    answer: 'A',
    explanation: 'Ibn Khaldun (1332–1406), a North African polymath, wrote the "Muqaddimah," considered a foundational text of historiography, sociology, and economics.',
  },
  {
    id: 'phi_40',
    text: 'Which philosophical position holds that mind and body are two fundamentally different kinds of substance, most associated with Descartes?',
    text_tr: 'Zihin ve bedenin temelde iki farklı töz türü olduğunu savunan, en çok Descartes ile ilişkilendirilen felsefi görüş hangisidir?',
    options: { A: 'Monism', B: 'Dualism', C: 'Materialism', D: 'Idealism', E: 'Functionalism' },
    options_tr: { A: 'Monizm (Birciliğik)', B: 'Düalizm (İkicilik)', C: 'Materyalizm', D: 'İdealizm', E: 'İşlevselcilik (Fonksiyonalizm)' },
    answer: 'B',
    explanation: 'Cartesian dualism proposes that the mind (a non-physical substance) and the body (a physical substance) are fundamentally distinct.',
  },
  {
    id: 'phi_41',
    text: 'Which Greek philosopher argued that the material world is an imperfect reflection of unchanging, eternal "Forms" or "Ideas"?',
    text_tr: 'Maddi dünyanın, değişmeyen, ebedi "Formlar" veya "İdealar"ın kusurlu bir yansıması olduğunu savunan Yunan filozof kimdir?',
    options: { A: 'Aristotle', B: 'Plato', C: 'Democritus', D: 'Epicurus', E: 'Zeno' },
    options_tr: { A: 'Aristoteles', B: 'Platon', C: 'Demokritos', D: 'Epikuros', E: 'Zenon' },
    answer: 'B',
    explanation: 'Plato\'s Theory of Forms holds that non-physical, eternal Forms represent the truest reality, with physical objects being mere shadows or copies.',
  },
  {
    id: 'phi_42',
    text: 'Which German philosopher wrote "The World as Will and Representation," influenced by Buddhist and Hindu thought, and is known for a pessimistic worldview?',
    text_tr: 'Budist ve Hindu düşüncesinden etkilenen "İstenç ve Tasavvur Olarak Dünya"yı yazan ve karamsar bir dünya görüşüyle bilinen Alman filozof kimdir?',
    options: { A: 'Friedrich Nietzsche', B: 'Arthur Schopenhauer', C: 'Georg Wilhelm Friedrich Hegel', D: 'Ludwig Feuerbach', E: 'Eduard von Hartmann' },
    options_tr: { A: 'Friedrich Nietzsche', B: 'Arthur Schopenhauer', C: 'Georg Wilhelm Friedrich Hegel', D: 'Ludwig Feuerbach', E: 'Eduard von Hartmann' },
    answer: 'B',
    explanation: 'Arthur Schopenhauer\'s philosophy, centered on the concept of a blind, striving "will," profoundly influenced Nietzsche and later thinkers.',
  },
  {
    id: 'phi_43',
    text: 'Which branch of philosophy is concerned with the organization of society, government, justice, and political authority?',
    text_tr: 'Toplumun örgütlenmesi, yönetim, adalet ve siyasi otorite ile ilgilenen felsefe dalı hangisidir?',
    options: { A: 'Political philosophy', B: 'Aesthetics', C: 'Philosophy of mind', D: 'Philosophy of science', E: 'Logic' },
    options_tr: { A: 'Siyaset felsefesi', B: 'Estetik', C: 'Zihin felsefesi', D: 'Bilim felsefesi', E: 'Mantık' },
    answer: 'A',
    explanation: 'Political philosophy examines questions of governance, justice, rights, and the legitimacy of political authority.',
  },
  {
    id: 'phi_44',
    text: 'Which French philosopher wrote "The Social Contract," arguing that legitimate political authority comes from a social contract agreed to by all citizens?',
    text_tr: 'Meşru siyasi otoritenin tüm vatandaşların kabul ettiği bir toplumsal sözleşmeden geldiğini savunan "Toplum Sözleşmesi"ni yazan Fransız filozof kimdir?',
    options: { A: 'Voltaire', B: 'Montesquieu', C: 'Jean-Jacques Rousseau', D: 'Denis Diderot', E: 'Baron d\'Holbach' },
    options_tr: { A: 'Voltaire', B: 'Montesquieu', C: 'Jean-Jacques Rousseau', D: 'Denis Diderot', E: 'Baron d\'Holbach' },
    answer: 'C',
    explanation: 'Jean-Jacques Rousseau\'s "The Social Contract" (1762) opens with the famous line, "Man is born free, and everywhere he is in chains."',
  },
  {
    id: 'phi_45',
    text: 'Which philosopher used the metaphor of the "Veil of Ignorance" to argue for principles of justice that people would choose without knowing their place in society?',
    text_tr: 'İnsanların toplumdaki konumlarını bilmeden seçecekleri adalet ilkelerini savunmak için "Cehalet Perdesi" metaforunu kullanan filozof kimdir?',
    options: { A: 'Robert Nozick', B: 'John Rawls', C: 'Michael Sandel', D: 'Amartya Sen', E: 'Ronald Dworkin' },
    options_tr: { A: 'Robert Nozick', B: 'John Rawls', C: 'Michael Sandel', D: 'Amartya Sen', E: 'Ronald Dworkin' },
    answer: 'B',
    explanation: 'John Rawls introduced the "veil of ignorance" thought experiment in his 1971 book "A Theory of Justice."',
  },
  {
    id: 'phi_46',
    text: 'Which pre-Socratic philosopher is traditionally regarded as the first Western philosopher, proposing that water is the fundamental substance of all things?',
    text_tr: 'Geleneksel olarak ilk Batılı filozof sayılan ve suyun tüm şeylerin temel maddesi olduğunu öne süren Sokrates öncesi filozof kimdir?',
    options: { A: 'Anaximander', B: 'Thales of Miletus', C: 'Anaximenes', D: 'Pythagoras', E: 'Xenophanes' },
    options_tr: { A: 'Anaksimandros', B: 'Miletli Tales', C: 'Anaksimenes', D: 'Pisagor', E: 'Ksenophanes' },
    answer: 'B',
    explanation: 'Thales of Miletus (c. 624–546 BC) is traditionally considered the first philosopher in the Western tradition.',
  },
  {
    id: 'phi_47',
    text: 'Which branch of philosophy examines the nature of the mind, mental states, consciousness, and their relationship to the physical body?',
    text_tr: 'Zihnin, zihinsel durumların, bilincin doğasını ve bunların fiziksel bedenle ilişkisini inceleyen felsefe dalı hangisidir?',
    options: { A: 'Philosophy of language', B: 'Philosophy of mind', C: 'Philosophy of religion', D: 'Philosophy of science', E: 'Social philosophy' },
    options_tr: { A: 'Dil felsefesi', B: 'Zihin felsefesi', C: 'Din felsefesi', D: 'Bilim felsefesi', E: 'Toplum felsefesi' },
    answer: 'B',
    explanation: 'Philosophy of mind explores consciousness, mental states, and the mind-body problem, closely tied to cognitive science.',
  },
  {
    id: 'phi_48',
    text: 'Which philosophical argument, associated with Anselm of Canterbury, attempts to prove God\'s existence through pure logical reasoning alone?',
    text_tr: 'Canterburylu Anselm ile ilişkilendirilen ve Tanrı\'nın varlığını yalnızca saf mantıksal akıl yürütmeyle kanıtlamaya çalışan felsefi argüman hangisidir?',
    options: { A: 'The Cosmological Argument', B: 'The Teleological Argument', C: 'The Ontological Argument', D: 'The Moral Argument', E: 'Pascal\'s Wager' },
    options_tr: { A: 'Kozmolojik Argüman', B: 'Teleolojik Argüman', C: 'Ontolojik Argüman', D: 'Ahlaki Argüman', E: 'Pascal\'ın Bahsi' },
    answer: 'C',
    explanation: 'Anselm\'s Ontological Argument (11th century) reasons that God, defined as the greatest conceivable being, must exist because existence is a necessary attribute of such a being.',
  },
  {
    id: 'phi_49',
    text: 'Which French philosopher\'s wager argued that believing in God is the rational choice given the potential infinite reward versus finite cost?',
    text_tr: 'Tanrı\'ya inanmanın, sonsuz ödül potansiyeline karşı sonlu maliyeti göz önüne alındığında rasyonel seçim olduğunu savunan Fransız filozofun bahsi hangisidir?',
    options: { A: 'Descartes\' Wager', B: 'Pascal\'s Wager', C: 'Voltaire\'s Wager', D: 'Rousseau\'s Wager', E: 'Montaigne\'s Wager' },
    options_tr: { A: 'Descartes\'ın Bahsi', B: 'Pascal\'ın Bahsi', C: 'Voltaire\'in Bahsi', D: 'Rousseau\'nun Bahsi', E: 'Montaigne\'in Bahsi' },
    answer: 'B',
    explanation: 'Blaise Pascal\'s Wager, from his "Pensées" (published posthumously in 1670), is a pragmatic argument for believing in God under uncertainty.',
  },
  {
    id: 'phi_50',
    text: 'Which 20th-century Austrian-British philosopher, known for "Tractatus Logico-Philosophicus," argued that "the limits of my language mean the limits of my world"?',
    text_tr: '"Tractatus Logico-Philosophicus" ile tanınan ve "dilimin sınırları dünyamın sınırları demektir" diyen 20. yüzyıl Avusturyalı-İngiliz filozof kimdir?',
    options: { A: 'Bertrand Russell', B: 'Ludwig Wittgenstein', C: 'Karl Popper', D: 'Rudolf Carnap', E: 'Gottlob Frege' },
    options_tr: { A: 'Bertrand Russell', B: 'Ludwig Wittgenstein', C: 'Karl Popper', D: 'Rudolf Carnap', E: 'Gottlob Frege' },
    answer: 'B',
    explanation: 'Ludwig Wittgenstein published the "Tractatus Logico-Philosophicus" in 1921, profoundly shaping analytic philosophy and philosophy of language.',
  },
  {
    id: 'phi_51',
    text: 'Which British philosopher and mathematician, co-author of "Principia Mathematica," was also a prominent social critic and Nobel laureate in Literature?',
    text_tr: '"Principia Mathematica"nın ortak yazarı olan ve aynı zamanda önde gelen bir toplumsal eleştirmen ve Nobel Edebiyat ödüllü olan İngiliz filozof ve matematikçi kimdir?',
    options: { A: 'Alfred North Whitehead', B: 'Bertrand Russell', C: 'G.E. Moore', D: 'A.J. Ayer', E: 'Gilbert Ryle' },
    options_tr: { A: 'Alfred North Whitehead', B: 'Bertrand Russell', C: 'G.E. Moore', D: 'A.J. Ayer', E: 'Gilbert Ryle' },
    answer: 'B',
    explanation: 'Bertrand Russell won the Nobel Prize in Literature in 1950 and co-authored "Principia Mathematica" with Alfred North Whitehead.',
  },
  {
    id: 'phi_52',
    text: 'Which ancient Greek philosopher taught that the goal of life is "ataraxia" (freedom from distress) achieved through simple pleasures and the removal of fear, especially fear of death?',
    text_tr: 'Yaşamın amacının, basit hazlar ve özellikle ölüm korkusunun ortadan kaldırılmasıyla elde edilen "ataraxia" (sıkıntısızlık) olduğunu öğreten antik Yunan filozof kimdir?',
    options: { A: 'Zeno of Citium', B: 'Epicurus', C: 'Pyrrho', D: 'Antisthenes', E: 'Aristippus' },
    options_tr: { A: 'Kitionlu Zenon', B: 'Epikuros', C: 'Pyrrhon', D: 'Antisthenes', E: 'Aristippos' },
    answer: 'B',
    explanation: 'Epicurus founded Epicureanism, teaching that the highest good is a tranquil state free from fear and pain, not mere indulgence in pleasure.',
  },
  {
    id: 'phi_53',
    text: 'Which philosophical movement, associated with Sartre and Camus, emphasizes individual freedom, choice, and the inherent meaninglessness of existence?',
    text_tr: 'Sartre ve Camus ile ilişkilendirilen ve bireysel özgürlüğü, seçimi ve varoluşun doğasında var olan anlamsızlığı vurgulayan felsefi akım hangisidir?',
    options: { A: 'Structuralism', B: 'Existentialism', C: 'Positivism', D: 'Idealism', E: 'Pragmatism' },
    options_tr: { A: 'Yapısalcılık', B: 'Varoluşçuluk', C: 'Pozitivizm', D: 'İdealizm', E: 'Pragmatizm' },
    answer: 'B',
    explanation: 'Existentialism holds that individuals create their own meaning in an inherently indifferent or absurd universe.',
  },
  {
    id: 'phi_54',
    text: 'Which philosophy, most associated with American thinkers like William James and John Dewey, evaluates the truth or meaning of ideas based on their practical consequences?',
    text_tr: 'En çok William James ve John Dewey gibi Amerikalı düşünürlerle ilişkilendirilen ve fikirlerin doğruluğunu veya anlamını pratik sonuçlarına göre değerlendiren felsefe hangisidir?',
    options: { A: 'Empiricism', B: 'Pragmatism', C: 'Rationalism', D: 'Idealism', E: 'Existentialism' },
    options_tr: { A: 'Ampirizm', B: 'Pragmatizm', C: 'Rasyonalizm', D: 'İdealizm', E: 'Varoluşçuluk' },
    answer: 'B',
    explanation: 'Pragmatism, developed by Charles Sanders Peirce, William James, and John Dewey, judges the value of ideas by their practical effects.',
  },
  {
    id: 'phi_55',
    text: 'Which French philosopher, associated with structuralism and post-structuralism, wrote "Discipline and Punish," examining how power operates through institutions?',
    text_tr: 'Yapısalcılık ve post-yapısalcılıkla ilişkilendirilen ve iktidarın kurumlar aracılığıyla nasıl işlediğini inceleyen "Hapishanenin Doğuşu"nu yazan Fransız filozof kimdir?',
    options: { A: 'Jacques Derrida', B: 'Michel Foucault', C: 'Claude Lévi-Strauss', D: 'Louis Althusser', E: 'Roland Barthes' },
    options_tr: { A: 'Jacques Derrida', B: 'Michel Foucault', C: 'Claude Lévi-Strauss', D: 'Louis Althusser', E: 'Roland Barthes' },
    answer: 'B',
    explanation: 'Michel Foucault\'s "Discipline and Punish" (1975) examines the evolution of punishment and the mechanisms of institutional power.',
  },
  {
    id: 'phi_56',
    text: 'Which German-American philosopher, associated with the Frankfurt School, co-wrote "Dialectic of Enlightenment," critiquing modern rationality and mass culture?',
    text_tr: 'Frankfurt Okulu ile ilişkilendirilen ve modern akılcılığı ve kitle kültürünü eleştiren "Aydınlanmanın Diyalektiği"ni ortak yazan Alman-Amerikalı filozof kimdir?',
    options: { A: 'Herbert Marcuse', B: 'Theodor Adorno', C: 'Jürgen Habermas', D: 'Walter Benjamin', E: 'Erich Fromm' },
    options_tr: { A: 'Herbert Marcuse', B: 'Theodor Adorno', C: 'Jürgen Habermas', D: 'Walter Benjamin', E: 'Erich Fromm' },
    answer: 'B',
    explanation: 'Theodor Adorno co-wrote "Dialectic of Enlightenment" (1944) with Max Horkheimer, a key text of Frankfurt School critical theory.',
  },
  {
    id: 'phi_57',
    text: 'Which Ottoman Turkish thinker and reformist, known for works on modernization and Islamic thought, was influential in the late Ottoman intellectual movement?',
    text_tr: 'Modernleşme ve İslami düşünce üzerine eserleriyle tanınan ve geç Osmanlı entelektüel hareketinde etkili olan Osmanlı Türk düşünürü ve reformisti kimdir?',
    options: { A: 'Namık Kemal', B: 'Ziya Gökalp', C: 'Ahmed Cevdet Pasha', D: 'Şemseddin Sami', E: 'Mehmed Akif Ersoy' },
    options_tr: { A: 'Namık Kemal', B: 'Ziya Gökalp', C: 'Ahmed Cevdet Paşa', D: 'Şemseddin Sami', E: 'Mehmed Akif Ersoy' },
    answer: 'B',
    explanation: 'Ziya Gökalp (1876–1924) was a highly influential sociologist and thinker whose ideas on nationalism shaped early Turkish republican ideology.',
  },
  {
    id: 'phi_58',
    text: 'Which logical paradox states "This sentence is false," creating a contradiction if taken as either true or false?',
    text_tr: '"Bu cümle yanlıştır" diyen ve doğru ya da yanlış kabul edildiğinde bir çelişki yaratan mantıksal paradoks hangisidir?',
    options: { A: 'The Sorites Paradox', B: 'The Liar Paradox', C: 'Zeno\'s Paradox', D: 'The Barber Paradox', E: 'Russell\'s Paradox' },
    options_tr: { A: 'Sorites Paradoksu', B: 'Yalancı Paradoksu', C: 'Zenon Paradoksu', D: 'Berber Paradoksu', E: 'Russell Paradoksu' },
    answer: 'B',
    explanation: 'The Liar Paradox, known since antiquity, highlights deep problems in self-referential statements and formal logic.',
  },
  {
    id: 'phi_59',
    text: 'Which ancient Greek philosopher proposed several paradoxes of motion, including one where a fast runner (Achilles) can never overtake a slower one (a tortoise) with a head start?',
    text_tr: 'Hızlı bir koşucunun (Aşil), önde başlayan yavaş bir rakibi (kaplumbağa) asla geçemeyeceğini savunan hareket paradoksları öneren antik Yunan filozof kimdir?',
    options: { A: 'Parmenides', B: 'Zeno of Elea', C: 'Heraclitus', D: 'Empedocles', E: 'Anaxagoras' },
    options_tr: { A: 'Parmenides', B: 'Elealı Zenon', C: 'Herakleitos', D: 'Empedokles', E: 'Anaksagoras' },
    answer: 'B',
    explanation: 'Zeno of Elea devised paradoxes, including "Achilles and the Tortoise," to support his teacher Parmenides\' view that motion is illusory.',
  },
  {
    id: 'phi_60',
    text: 'Which Turkish/Islamic philosopher and mystic, born in Konya (present-day Turkey) region, is known for founding the Mevlevi Sufi order, associated with the "whirling dervishes"?',
    text_tr: 'Konya\'da (bugünkü Türkiye) yaşamış ve "dönen dervişler" ile ilişkilendirilen Mevlevi tarikatını kuran Türk/İslam filozofu ve mutasavvıfı kimdir?',
    options: { A: 'Yunus Emre', B: 'Rumi (Jalal ad-Din Muhammad Rumi)', C: 'Hacı Bektaş Veli', D: 'Ibn Arabi', E: 'Şeyh Bedreddin' },
    options_tr: { A: 'Yunus Emre', B: 'Mevlana Celaleddin Rumi', C: 'Hacı Bektaş Veli', D: 'İbn Arabi', E: 'Şeyh Bedreddin' },
    answer: 'B',
    explanation: 'Rumi\'s teachings and poetry gave rise to the Mevlevi Order, founded after his death by his followers in Konya.',
  },
  {
    id: 'phi_61',
    text: 'Which philosophical position holds that only physical matter exists, and mental states can ultimately be explained in physical terms?',
    text_tr: 'Yalnızca fiziksel maddenin var olduğunu ve zihinsel durumların nihayetinde fiziksel terimlerle açıklanabileceğini savunan felsefi görüş hangisidir?',
    options: { A: 'Idealism', B: 'Materialism', C: 'Dualism', D: 'Solipsism', E: 'Panpsychism' },
    options_tr: { A: 'İdealizm', B: 'Materyalizm', C: 'Düalizm', D: 'Sadece-benincilik (Solipsizm)', E: 'Panpsişizm' },
    answer: 'B',
    explanation: 'Materialism (physicalism) holds that everything, including mental phenomena, ultimately consists of or arises from physical matter.',
  },
  {
    id: 'phi_62',
    text: 'Which Irish philosopher and bishop argued that physical objects only exist as they are perceived, summarized by "esse est percipi" (to be is to be perceived)?',
    text_tr: '"Esse est percipi" (var olmak, algılanmaktır) ile özetlenen, fiziksel nesnelerin yalnızca algılandıkları sürece var olduğunu savunan İrlandalı filozof ve piskopos kimdir?',
    options: { A: 'John Locke', B: 'David Hume', C: 'George Berkeley', D: 'Francis Hutcheson', E: 'Edmund Burke' },
    options_tr: { A: 'John Locke', B: 'David Hume', C: 'George Berkeley', D: 'Francis Hutcheson', E: 'Edmund Burke' },
    answer: 'C',
    explanation: 'George Berkeley\'s idealism (immaterialism) holds that objects only exist as ideas perceived by minds.',
  },
  {
    id: 'phi_63',
    text: 'Which branch of philosophy examines the nature, scope, and validity of scientific knowledge and methodology?',
    text_tr: 'Bilimsel bilginin ve metodolojinin doğasını, kapsamını ve geçerliliğini inceleyen felsefe dalı hangisidir?',
    options: { A: 'Philosophy of science', B: 'Philosophy of religion', C: 'Philosophy of language', D: 'Social philosophy', E: 'Philosophy of law' },
    options_tr: { A: 'Bilim felsefesi', B: 'Din felsefesi', C: 'Dil felsefesi', D: 'Toplum felsefesi', E: 'Hukuk felsefesi' },
    answer: 'A',
    explanation: 'Philosophy of science examines the foundations, methods, and implications of science, including questions about what makes a theory scientific.',
  },
  {
    id: 'phi_64',
    text: 'Which Austrian-British philosopher of science proposed "falsifiability" as the key criterion distinguishing genuine science from pseudoscience?',
    text_tr: 'Gerçek bilimi sözde bilimden ayıran temel kriter olarak "yanlışlanabilirlik"i öneren Avusturyalı-İngiliz bilim filozofu kimdir?',
    options: { A: 'Thomas Kuhn', B: 'Karl Popper', C: 'Imre Lakatos', D: 'Paul Feyerabend', E: 'Rudolf Carnap' },
    options_tr: { A: 'Thomas Kuhn', B: 'Karl Popper', C: 'Imre Lakatos', D: 'Paul Feyerabend', E: 'Rudolf Carnap' },
    answer: 'B',
    explanation: 'Karl Popper proposed falsifiability in his 1934 work "The Logic of Scientific Discovery" as the demarcation criterion for science.',
  },
  {
    id: 'phi_65',
    text: 'Which American philosopher of science introduced the concept of the "paradigm shift" in his book "The Structure of Scientific Revolutions"?',
    text_tr: '"Bilimsel Devrimlerin Yapısı" kitabında "paradigma kayması" kavramını tanıtan Amerikalı bilim filozofu kimdir?',
    options: { A: 'Karl Popper', B: 'Thomas Kuhn', C: 'W.V.O. Quine', D: 'Hilary Putnam', E: 'Nelson Goodman' },
    options_tr: { A: 'Karl Popper', B: 'Thomas Kuhn', C: 'W.V.O. Quine', D: 'Hilary Putnam', E: 'Nelson Goodman' },
    answer: 'B',
    explanation: 'Thomas Kuhn\'s 1962 book introduced "paradigm shift" to describe how scientific revolutions overturn established frameworks.',
  },
  {
    id: 'phi_66',
    text: 'Which ancient philosopher, a student of Parmenides, argued that all reality consists of four eternal elements (earth, water, air, fire) combined by love and strife?',
    text_tr: 'Parmenides\'in öğrencisi olan ve tüm gerçekliğin sevgi ve çekişme tarafından birleştirilen dört ebedi unsurdan (toprak, su, hava, ateş) oluştuğunu savunan antik filozof kimdir?',
    options: { A: 'Anaxagoras', B: 'Empedocles', C: 'Democritus', D: 'Leucippus', E: 'Xenophanes' },
    options_tr: { A: 'Anaksagoras', B: 'Empedokles', C: 'Demokritos', D: 'Leukippos', E: 'Ksenophanes' },
    answer: 'B',
    explanation: 'Empedocles proposed the four classical elements theory, which influenced Western thought for centuries afterward.',
  },
  {
    id: 'phi_67',
    text: 'Which ancient philosopher is credited (along with his teacher Leucippus) with developing the idea that all matter is composed of indivisible "atoms"?',
    text_tr: 'Öğretmeni Leukippos ile birlikte, tüm maddenin bölünemez "atomlar"dan oluştuğu fikrini geliştirmesiyle tanınan antik filozof kimdir?',
    options: { A: 'Democritus', B: 'Empedocles', C: 'Anaximander', D: 'Thales', E: 'Pythagoras' },
    options_tr: { A: 'Demokritos', B: 'Empedokles', C: 'Anaksimandros', D: 'Tales', E: 'Pisagor' },
    answer: 'A',
    explanation: 'Democritus, alongside Leucippus, developed early atomic theory in the 5th century BC, long before modern atomic physics.',
  },
  {
    id: 'phi_68',
    text: 'Which philosophical school of India, founded around the same time as Buddhism, is known for the concept of non-violence ("ahimsa") and asceticism, associated with Mahavira?',
    text_tr: 'Budizm ile hemen hemen aynı dönemde kurulan ve Mahavira ile ilişkilendirilen şiddetsizlik ("ahimsa") ile çilecilik kavramlarıyla bilinen Hindistan felsefi okulu hangisidir?',
    options: { A: 'Hinduism (Vedanta)', B: 'Jainism', C: 'Sikhism', D: 'Buddhism (same tradition)', E: 'Zoroastrianism' },
    options_tr: { A: 'Hinduizm (Vedanta)', B: 'Caynizm (Jainizm)', C: 'Sihizm', D: 'Budizm (aynı gelenek)', E: 'Zerdüştlük' },
    answer: 'B',
    explanation: 'Jainism, associated with Mahavira (6th century BC), emphasizes strict non-violence toward all living beings.',
  },
  {
    id: 'phi_69',
    text: 'Which prince, born in present-day Nepal, renounced his royal life and became the "Buddha" ("the Awakened One"), founding Buddhism?',
    text_tr: 'Bugünkü Nepal\'de doğan ve kraliyet hayatından vazgeçip "Buda" ("Uyanmış Olan") olan, Budizmi kuran prens kimdir?',
    options: { A: 'Ashoka', B: 'Siddhartha Gautama', C: 'Mahavira', D: 'Nagarjuna', E: 'Bodhidharma' },
    options_tr: { A: 'Ashoka', B: 'Siddhartha Gautama', C: 'Mahavira', D: 'Nagarjuna', E: 'Bodhidharma' },
    answer: 'B',
    explanation: 'Siddhartha Gautama (c. 5th–4th century BC) achieved enlightenment and became known as the Buddha, founding Buddhism.',
  },
  {
    id: 'phi_70',
    text: 'Which of the Buddha\'s core teachings identifies the cause of suffering as craving and attachment, part of the "Four Noble Truths"?',
    text_tr: 'Acının nedenini arzu ve bağlılık olarak tanımlayan, "Dört Yüce Gerçek"in bir parçası olan Buda\'nın temel öğretisi hangisidir?',
    options: { A: 'The Eightfold Path', B: 'The Four Noble Truths', C: 'Karma', D: 'Nirvana', E: 'Dharma' },
    options_tr: { A: 'Sekiz Dilimli Yol', B: 'Dört Yüce Gerçek', C: 'Karma', D: 'Nirvana', E: 'Dharma' },
    answer: 'B',
    explanation: 'The Four Noble Truths are the foundation of Buddhist teaching, identifying suffering, its cause, its end, and the path to end it.',
  },
  {
    id: 'phi_71',
    text: 'Which Turkish/Islamic mystic poet, whose simple, humanistic verse is central to Turkish Sufi literature, is often quoted as saying "Gel, tanış olalım" (Come, let us know one another)?',
    text_tr: 'Sade, hümanist dizeleri Türk tasavvuf edebiyatının merkezinde yer alan ve genellikle "Gel, tanış olalım" sözüyle anılan Türk/İslam mutasavvıf şair kimdir?',
    options: { A: 'Yunus Emre', B: 'Mevlana Celaleddin Rumi', C: 'Hacı Bektaş Veli', D: 'Ahmed Yesevi', E: 'Niyazi Mısri' },
    options_tr: { A: 'Yunus Emre', B: 'Mevlana Celaleddin Rumi', C: 'Hacı Bektaş Veli', D: 'Ahmed Yesevi', E: 'Niyazi Mısri' },
    answer: 'A',
    explanation: 'Yunus Emre (13th–14th century) is beloved for his humanistic, accessible Sufi poetry central to Turkish and Anatolian mysticism.',
  },
  {
    id: 'phi_72',
    text: 'Which philosophical concept, central to Hindu and Buddhist thought, refers to the cycle of action and consequence, where intent and actions shape future experiences?',
    text_tr: 'Hindu ve Budist düşüncesinin merkezinde olan ve niyet ile eylemlerin gelecekteki deneyimleri şekillendirdiği eylem ve sonuç döngüsüne atıfta bulunan felsefi kavram hangisidir?',
    options: { A: 'Dharma', B: 'Karma', C: 'Moksha', D: 'Samsara', E: 'Maya' },
    options_tr: { A: 'Dharma', B: 'Karma', C: 'Moksha', D: 'Samsara', E: 'Maya' },
    answer: 'B',
    explanation: 'Karma is the principle that actions have consequences affecting future lives and circumstances in the cycle of rebirth (samsara).',
  },
  {
    id: 'phi_73',
    text: 'Which German philosopher\'s concept of "false consciousness" describes how ideology can obscure the true nature of social and economic relations from those who experience them?',
    text_tr: 'İdeolojinin, toplumsal ve ekonomik ilişkilerin gerçek doğasını bunları deneyimleyenlerden nasıl gizleyebileceğini tanımlayan "yanlış bilinç" kavramı hangi Alman filozofa aittir?',
    options: { A: 'Georg Wilhelm Friedrich Hegel', B: 'Karl Marx', C: 'Immanuel Kant', D: 'Friedrich Nietzsche', E: 'Arthur Schopenhauer' },
    options_tr: { A: 'Georg Wilhelm Friedrich Hegel', B: 'Karl Marx', C: 'Immanuel Kant', D: 'Friedrich Nietzsche', E: 'Arthur Schopenhauer' },
    answer: 'B',
    explanation: '"False consciousness," a concept elaborated within Marxist theory, describes how ideology masks the reality of class relations.',
  },
  {
    id: 'phi_74',
    text: 'Which branch of philosophy investigates the nature of language, meaning, and how words relate to reality?',
    text_tr: 'Dilin, anlamın doğasını ve kelimelerin gerçeklikle nasıl ilişkilendiğini araştıran felsefe dalı hangisidir?',
    options: { A: 'Philosophy of language', B: 'Philosophy of mind', C: 'Metaphysics', D: 'Epistemology', E: 'Ethics' },
    options_tr: { A: 'Dil felsefesi', B: 'Zihin felsefesi', C: 'Metafizik', D: 'Epistemoloji', E: 'Etik' },
    answer: 'A',
    explanation: 'Philosophy of language studies meaning, reference, truth, and communication, closely tied to logic and linguistics.',
  },
  {
    id: 'phi_75',
    text: 'Which philosophical view holds that moral truths are absolute and apply universally, regardless of culture or individual opinion?',
    text_tr: 'Ahlaki gerçeklerin mutlak olduğunu ve kültürden veya bireysel görüşten bağımsız olarak evrensel olarak uygulandığını savunan felsefi görüş hangisidir?',
    options: { A: 'Moral relativism', B: 'Moral absolutism', C: 'Moral nihilism', D: 'Emotivism', E: 'Moral skepticism' },
    options_tr: { A: 'Ahlaki görecelik', B: 'Ahlaki mutlakçılık', C: 'Ahlaki hiççilik', D: 'Duygusalcılık', E: 'Ahlaki kuşkuculuk' },
    answer: 'B',
    explanation: 'Moral absolutism holds that certain actions are always right or wrong, regardless of context or cultural variation, contrasted with moral relativism.',
  },
  {
    id: 'phi_76',
    text: 'Which philosophical view holds that moral judgments are relative to the cultural or individual context in which they are made?',
    text_tr: 'Ahlaki yargıların yapıldıkları kültürel veya bireysel bağlama göreceli olduğunu savunan felsefi görüş hangisidir?',
    options: { A: 'Moral absolutism', B: 'Moral relativism', C: 'Deontology', D: 'Virtue ethics', E: 'Consequentialism' },
    options_tr: { A: 'Ahlaki mutlakçılık', B: 'Ahlaki görecelik', C: 'Ödev etiği (Deontoloji)', D: 'Erdem etiği', E: 'Sonuççuluk' },
    answer: 'B',
    explanation: 'Moral relativism holds that ethical standards and judgments vary according to cultural or personal perspectives, rather than being universally fixed.',
  },
  {
    id: 'phi_77',
    text: 'Which ethical theory, associated with Aristotle, focuses on the cultivation of good character traits rather than rules or consequences?',
    text_tr: 'Aristoteles ile ilişkilendirilen ve kurallar veya sonuçlar yerine iyi karakter özelliklerinin geliştirilmesine odaklanan etik teori hangisidir?',
    options: { A: 'Deontology', B: 'Consequentialism', C: 'Virtue ethics', D: 'Divine command theory', E: 'Contractualism' },
    options_tr: { A: 'Ödev etiği', B: 'Sonuççuluk', C: 'Erdem etiği', D: 'İlahi buyruk teorisi', E: 'Sözleşmecilik' },
    answer: 'C',
    explanation: 'Virtue ethics, rooted in Aristotle\'s "Nicomachean Ethics," emphasizes character and the pursuit of "eudaimonia" (flourishing) over rigid rules.',
  },
  {
    id: 'phi_78',
    text: 'Which ethical theory judges the morality of an action based solely on whether it follows a set of rules or duties, regardless of consequences (associated with Kant)?',
    text_tr: 'Bir eylemin ahlakiliğini, sonuçlarından bağımsız olarak yalnızca bir dizi kural veya ödeve uyup uymadığına göre değerlendiren (Kant ile ilişkilendirilen) etik teori hangisidir?',
    options: { A: 'Consequentialism', B: 'Deontology', C: 'Virtue ethics', D: 'Hedonism', E: 'Egoism' },
    options_tr: { A: 'Sonuççuluk', B: 'Ödev etiği (Deontoloji)', C: 'Erdem etiği', D: 'Hedonizm', E: 'Bencillik (Egoizm)' },
    answer: 'B',
    explanation: 'Deontological ethics, most associated with Kant, judges actions as right or wrong based on adherence to moral rules or duties, not outcomes.',
  },
  {
    id: 'phi_79',
    text: 'Which ethical theory judges the morality of an action based purely on its outcomes or consequences, as in utilitarianism?',
    text_tr: 'Bir eylemin ahlakiliğini yalnızca sonuçlarına göre değerlendiren, faydacılıkta olduğu gibi bir etik teori hangisidir?',
    options: { A: 'Deontology', B: 'Virtue ethics', C: 'Consequentialism', D: 'Divine command theory', E: 'Natural law theory' },
    options_tr: { A: 'Ödev etiği', B: 'Erdem etiği', C: 'Sonuççuluk', D: 'İlahi buyruk teorisi', E: 'Doğal hukuk teorisi' },
    answer: 'C',
    explanation: 'Consequentialism, including utilitarianism, evaluates the morality of actions based on their results rather than intrinsic rules or character.',
  },
  {
    id: 'phi_80',
    text: 'Which 20th-century French philosopher, associated with deconstruction, argued that texts contain inherent contradictions that undermine any single, fixed meaning?',
    text_tr: 'Yapısöküm ile ilişkilendirilen ve metinlerin, tek ve sabit bir anlamı baltalayan içsel çelişkiler barındırdığını savunan 20. yüzyıl Fransız filozof kimdir?',
    options: { A: 'Michel Foucault', B: 'Jacques Derrida', C: 'Jean Baudrillard', D: 'Gilles Deleuze', E: 'Jean-François Lyotard' },
    options_tr: { A: 'Michel Foucault', B: 'Jacques Derrida', C: 'Jean Baudrillard', D: 'Gilles Deleuze', E: 'Jean-François Lyotard' },
    answer: 'B',
    explanation: 'Jacques Derrida developed deconstruction, a method of critical analysis showing how texts undermine their own apparent meanings.',
  },
  {
    id: 'phi_81',
    text: 'Which Ottoman/Turkish intellectual is considered a founding figure of Turkish nationalism and wrote "The Principles of Turkism"?',
    text_tr: 'Türk milliyetçiliğinin kurucu figürlerinden sayılan ve "Türkçülüğün Esasları"nı yazan Osmanlı/Türk düşünürü kimdir?',
    options: { A: 'Yusuf Akçura', B: 'Ziya Gökalp', C: 'Ahmet Ağaoğlu', D: 'Mehmed Emin Yurdakul', E: 'Halide Edip Adıvar' },
    options_tr: { A: 'Yusuf Akçura', B: 'Ziya Gökalp', C: 'Ahmet Ağaoğlu', D: 'Mehmed Emin Yurdakul', E: 'Halide Edip Adıvar' },
    answer: 'B',
    explanation: 'Ziya Gökalp\'s "The Principles of Turkism" (Türkçülüğün Esasları, 1923) was highly influential in shaping early Turkish nationalist ideology.',
  },
  {
    id: 'phi_82',
    text: 'Which ancient philosophical school held that certainty is impossible and that one should suspend judgment on all matters to achieve peace of mind?',
    text_tr: 'Kesinliğin imkansız olduğunu ve ruh huzuruna ulaşmak için her konuda yargıyı askıya almak gerektiğini savunan antik felsefi okul hangisidir?',
    options: { A: 'Stoicism', B: 'Epicureanism', C: 'Skepticism (Pyrrhonism)', D: 'Cynicism', E: 'Platonism' },
    options_tr: { A: 'Stoacılık', B: 'Epikürcülük', C: 'Kuşkuculuk (Pyrrhonculuk)', D: 'Kinizm', E: 'Platonculuk' },
    answer: 'C',
    explanation: 'Pyrrhonist Skepticism, founded by Pyrrho of Elis, advocated "epoché" (suspension of judgment) as the path to tranquility.',
  },
  {
    id: 'phi_83',
    text: 'Which contemporary philosopher, known for works like "Justice: What\'s the Right Thing to Do?", is a prominent proponent of communitarian critiques of pure individual liberalism?',
    text_tr: '"Adalet: Doğru Olan Nedir?" gibi eserleriyle tanınan ve saf bireysel liberalizme yönelik komüniteryan eleştirilerin önde gelen savunucusu olan çağdaş filozof kimdir?',
    options: { A: 'John Rawls', B: 'Michael Sandel', C: 'Robert Nozick', D: 'Alasdair MacIntyre', E: 'Martha Nussbaum' },
    options_tr: { A: 'John Rawls', B: 'Michael Sandel', C: 'Robert Nozick', D: 'Alasdair MacIntyre', E: 'Martha Nussbaum' },
    answer: 'B',
    explanation: 'Michael Sandel, a Harvard political philosopher, is well known for his critiques of Rawlsian liberalism and his popular course/book "Justice."',
  },
  {
    id: 'phi_84',
    text: 'Which German philosopher, in "Zur Genealogie der Moral" (On the Genealogy of Morals), distinguished between "master morality" and "slave morality"?',
    text_tr: '"Ahlakın Soykütüğü Üzerine" adlı eserinde "efendi ahlakı" ile "köle ahlakı" ayrımını yapan Alman filozof kimdir?',
    options: { A: 'Arthur Schopenhauer', B: 'Friedrich Nietzsche', C: 'Max Weber', D: 'Georg Simmel', E: 'Wilhelm Dilthey' },
    options_tr: { A: 'Arthur Schopenhauer', B: 'Friedrich Nietzsche', C: 'Max Weber', D: 'Georg Simmel', E: 'Wilhelm Dilthey' },
    answer: 'B',
    explanation: 'Friedrich Nietzsche developed this distinction in his 1887 work, critiquing conventional morality\'s origins in resentment ("ressentiment").',
  },
  {
    id: 'phi_85',
    text: 'Which philosopher, an important figure in Islamic Spain, wrote "Hayy ibn Yaqzan," a philosophical novel about a boy raised alone on an island who reasons his way to knowledge of God?',
    text_tr: 'İslam İspanyası\'nın önemli bir figürü olan ve bir adada tek başına büyüyen ve akıl yoluyla Tanrı bilgisine ulaşan bir çocuğu anlatan felsefi roman "Hay bin Yakzan"ı yazan filozof kimdir?',
    options: { A: 'Ibn Rushd', B: 'Ibn Tufail', C: 'Ibn Bajjah', D: 'Ibn Arabi', E: 'Al-Ghazali' },
    options_tr: { A: 'İbn Rüşd', B: 'İbn Tufeyl', C: 'İbn Bacce', D: 'İbn Arabi', E: 'Gazali' },
    answer: 'B',
    explanation: 'Ibn Tufail\'s 12th-century philosophical novel "Hayy ibn Yaqzan" explored themes of reason, nature, and religious knowledge, influencing later European thought.',
  },
  {
    id: 'phi_86',
    text: 'Which branch of philosophy examines the nature of God, religious belief, and the relationship between faith and reason?',
    text_tr: 'Tanrı\'nın doğasını, dini inancı ve iman ile akıl arasındaki ilişkiyi inceleyen felsefe dalı hangisidir?',
    options: { A: 'Philosophy of religion', B: 'Philosophy of law', C: 'Philosophy of history', D: 'Social philosophy', E: 'Philosophy of mind' },
    options_tr: { A: 'Din felsefesi', B: 'Hukuk felsefesi', C: 'Tarih felsefesi', D: 'Toplum felsefesi', E: 'Zihin felsefesi' },
    answer: 'A',
    explanation: 'Philosophy of religion investigates religious concepts, arguments for and against God\'s existence, and the nature of faith.',
  },
  {
    id: 'phi_87',
    text: 'Which philosophical argument reasons from the apparent order, complexity, and purpose in nature to the existence of an intelligent designer?',
    text_tr: 'Doğadaki görünür düzen, karmaşıklık ve amaçtan yola çıkarak akıllı bir tasarımcının varlığına ulaşan felsefi argüman hangisidir?',
    options: { A: 'The Ontological Argument', B: 'The Cosmological Argument', C: 'The Teleological Argument (Argument from Design)', D: 'The Problem of Evil', E: 'The Moral Argument' },
    options_tr: { A: 'Ontolojik Argüman', B: 'Kozmolojik Argüman', C: 'Teleolojik Argüman (Tasarım Argümanı)', D: 'Kötülük Problemi', E: 'Ahlaki Argüman' },
    answer: 'C',
    explanation: 'The Teleological Argument, notably advanced by William Paley\'s "watchmaker analogy" (1802), infers design from apparent purpose in nature.',
  },
  {
    id: 'phi_88',
    text: 'Which philosophical problem asks how the existence of evil and suffering can be reconciled with the existence of an all-powerful, all-knowing, and all-good God?',
    text_tr: 'Kötülük ve acının varlığının, her şeye gücü yeten, her şeyi bilen ve tamamen iyi bir Tanrı\'nın varlığıyla nasıl bağdaştırılabileceğini soran felsefi problem hangisidir?',
    options: { A: 'The Problem of Evil', B: 'The Problem of Free Will', C: 'The Problem of Universals', D: 'The Mind-Body Problem', E: 'The Problem of Induction' },
    options_tr: { A: 'Kötülük Problemi', B: 'Özgür İrade Problemi', C: 'Evrenseller Problemi', D: 'Zihin-Beden Problemi', E: 'Tümevarım Problemi' },
    answer: 'A',
    explanation: 'The Problem of Evil is one of the oldest and most debated challenges in philosophy of religion, dating back to Epicurus.',
  },
  {
    id: 'phi_89',
    text: 'Which philosopher, writing "Meditations" while serving as Roman Emperor, is considered one of the most important Stoic philosophers?',
    text_tr: 'Roma İmparatoru olarak görev yaparken "Düşünceler"i (Meditasyonlar) yazan ve en önemli Stoacı filozoflardan biri sayılan kimdir?',
    options: { A: 'Seneca', B: 'Epictetus', C: 'Marcus Aurelius', D: 'Cicero', E: 'Cato the Younger' },
    options_tr: { A: 'Seneca', B: 'Epiktetos', C: 'Marcus Aurelius', D: 'Cicero', E: 'Genç Cato' },
    answer: 'C',
    explanation: 'Marcus Aurelius (121–180 AD), Roman Emperor, wrote "Meditations" as a private philosophical diary reflecting Stoic principles.',
  },
  {
    id: 'phi_90',
    text: 'Which formerly enslaved Stoic philosopher taught that while we cannot control external events, we can always control our own judgments and reactions?',
    text_tr: 'Dış olayları kontrol edemesek de, kendi yargılarımızı ve tepkilerimizi her zaman kontrol edebileceğimizi öğreten, eski köle olan Stoacı filozof kimdir?',
    options: { A: 'Seneca', B: 'Epictetus', C: 'Marcus Aurelius', D: 'Musonius Rufus', E: 'Zeno of Citium' },
    options_tr: { A: 'Seneca', B: 'Epiktetos', C: 'Marcus Aurelius', D: 'Musonius Rufus', E: 'Kitionlu Zenon' },
    answer: 'B',
    explanation: 'Epictetus, born into slavery, became a highly influential Stoic teacher whose "Enchiridion" and "Discourses" emphasize the "dichotomy of control."',
  },
  {
    id: 'phi_91',
    text: 'Which contemporary field, bridging philosophy of mind and cognitive science, examines whether machines can possess genuine understanding or consciousness?',
    text_tr: 'Zihin felsefesi ile bilişsel bilimi birleştiren ve makinelerin gerçek anlama veya bilince sahip olup olamayacağını inceleyen çağdaş alan hangisidir?',
    options: { A: 'Philosophy of biology', B: 'Philosophy of artificial intelligence', C: 'Philosophy of mathematics', D: 'Philosophy of physics', E: 'Philosophy of economics' },
    options_tr: { A: 'Biyoloji felsefesi', B: 'Yapay zeka felsefesi', C: 'Matematik felsefesi', D: 'Fizik felsefesi', E: 'Ekonomi felsefesi' },
    answer: 'B',
    explanation: 'Philosophy of artificial intelligence explores questions of machine consciousness, understanding, and the ethical implications of AI, drawing on thought experiments like the Chinese Room.',
  },
  {
    id: 'phi_92',
    text: 'Which German-Jewish political philosopher, who fled Nazi Germany, wrote "The Origins of Totalitarianism" and coined the phrase "the banality of evil"?',
    text_tr: 'Nazi Almanyası\'ndan kaçan ve "Totalitarizmin Kökenleri"ni yazan, "kötülüğün sıradanlığı" ifadesini ortaya atan Alman-Yahudi siyaset filozofu kimdir?',
    options: { A: 'Simone Weil', B: 'Hannah Arendt', C: 'Rosa Luxemburg', D: 'Susan Sontag', E: 'Judith Butler' },
    options_tr: { A: 'Simone Weil', B: 'Hannah Arendt', C: 'Rosa Luxemburg', D: 'Susan Sontag', E: 'Judith Butler' },
    answer: 'B',
    explanation: 'Hannah Arendt coined "the banality of evil" in her 1963 book "Eichmann in Jerusalem," reporting on the trial of Nazi official Adolf Eichmann.',
  },
  {
    id: 'phi_93',
    text: 'Which Indian philosopher and later political leader emphasized "satyagraha" (truth-force / nonviolent resistance) as a moral and political philosophy?',
    text_tr: '"Satyagraha"yı (doğruluk gücü / şiddetsiz direniş) ahlaki ve siyasi bir felsefe olarak vurgulayan Hintli filozof ve daha sonra siyasi lider olan kimdir?',
    options: { A: 'Jawaharlal Nehru', B: 'Mahatma Gandhi', C: 'Rabindranath Tagore', D: 'B.R. Ambedkar', E: 'Sarvepalli Radhakrishnan' },
    options_tr: { A: 'Jawaharlal Nehru', B: 'Mahatma Gandhi', C: 'Rabindranath Tagore', D: 'B.R. Ambedkar', E: 'Sarvepalli Radhakrishnan' },
    answer: 'B',
    explanation: 'Mahatma Gandhi developed and applied "satyagraha" as a philosophy of nonviolent civil resistance during India\'s independence movement.',
  },
  {
    id: 'phi_94',
    text: 'Which philosophical concept, central to existentialism, refers to the anxiety or dread that comes from confronting the radical freedom and responsibility of human existence?',
    text_tr: 'Varoluşçuluğun merkezinde olan ve insan varoluşunun radikal özgürlük ve sorumluluğuyla yüzleşmekten kaynaklanan kaygı veya dehşete atıfta bulunan felsefi kavram hangisidir?',
    options: { A: 'Ataraxia', B: 'Angst (existential anxiety/dread)', C: 'Eudaimonia', D: 'Catharsis', E: 'Apatheia' },
    options_tr: { A: 'Ataraxia', B: 'Angst (varoluşsal kaygı/dehşet)', C: 'Eudaimonia', D: 'Katarsis', E: 'Apatheia' },
    answer: 'B',
    explanation: 'Angst (or "dread"), explored by Kierkegaard, Heidegger, and Sartre, describes the unsettling experience of confronting one\'s own radical freedom.',
  },
  {
    id: 'phi_95',
    text: 'Which term, from Aristotle\'s ethics, refers to human flourishing or well-being, often translated as "happiness" but meaning something closer to "living well"?',
    text_tr: 'Aristoteles\'in etiğinden gelen ve genellikle "mutluluk" olarak çevrilen, ancak "iyi yaşamak"a daha yakın bir anlam taşıyan, insan gelişimi veya iyi oluşuna atıfta bulunan terim hangisidir?',
    options: { A: 'Ataraxia', B: 'Eudaimonia', C: 'Phronesis', D: 'Arete', E: 'Sophia' },
    options_tr: { A: 'Ataraxia', B: 'Eudaimonia', C: 'Phronesis', D: 'Arete', E: 'Sophia' },
    answer: 'B',
    explanation: 'Eudaimonia, central to Aristotle\'s "Nicomachean Ethics," describes a state of flourishing achieved through virtuous activity in accordance with reason.',
  },
  {
    id: 'phi_96',
    text: 'Which contemporary Turkish philosopher and academic is known for works on the history of Ottoman/Islamic philosophy and comparative philosophy?',
    text_tr: 'Osmanlı/İslam felsefesi tarihi ve karşılaştırmalı felsefe üzerine eserleriyle tanınan çağdaş Türk filozof ve akademisyen kimdir?',
    options: { A: 'İoanna Kuçuradi', B: 'Nermi Uygur', C: 'Takiyettin Mengüşoğlu', D: 'Hilmi Ziya Ülken', E: 'All of the above are notable Turkish philosophers' },
    options_tr: { A: 'İoanna Kuçuradi', B: 'Nermi Uygur', C: 'Takiyettin Mengüşoğlu', D: 'Hilmi Ziya Ülken', E: 'Yukarıdakilerin hepsi tanınmış Türk filozoflardır' },
    answer: 'E',
    explanation: 'İoanna Kuçuradi, Nermi Uygur, Takiyettin Mengüşoğlu, and Hilmi Ziya Ülken are all significant 20th-century Turkish philosophers and academics.',
  },
  {
    id: 'phi_97',
    text: 'Which philosophical problem concerns whether human choices are truly free or are ultimately determined by prior causes, such as physics or divine foreknowledge?',
    text_tr: 'İnsan seçimlerinin gerçekten özgür mü yoksa nihayetinde fizik veya ilahi önbilgi gibi önceki nedenler tarafından mı belirlendiğiyle ilgili felsefi problem hangisidir?',
    options: { A: 'The Problem of Universals', B: 'The Free Will Problem (Free Will vs. Determinism)', C: 'The Problem of Induction', D: 'The Mind-Body Problem', E: 'The Problem of Personal Identity' },
    options_tr: { A: 'Evrenseller Problemi', B: 'Özgür İrade Problemi (Özgür İrade vs. Determinizm)', C: 'Tümevarım Problemi', D: 'Zihin-Beden Problemi', E: 'Kişisel Kimlik Problemi' },
    answer: 'B',
    explanation: 'The free will vs. determinism debate is one of the oldest problems in metaphysics, addressing moral responsibility and causation.',
  },
  {
    id: 'phi_98',
    text: 'Which branch of philosophy studies the moral principles governing the conduct of war, including just cause and proportionality?',
    text_tr: 'Savaşın yürütülmesini yöneten ahlaki ilkeleri, haklı neden ve orantılılık dahil olmak üzere inceleyen felsefe dalı hangisidir?',
    options: { A: 'Just War Theory', B: 'Social contract theory', C: 'Virtue ethics', D: 'Applied epistemology', E: 'Philosophy of law' },
    options_tr: { A: 'Adil Savaş Teorisi', B: 'Toplum sözleşmesi teorisi', C: 'Erdem etiği', D: 'Uygulamalı epistemoloji', E: 'Hukuk felsefesi' },
    answer: 'A',
    explanation: 'Just War Theory, developed by thinkers including Augustine and Aquinas, sets out moral criteria for when war is justified and how it should be conducted.',
  },
  {
    id: 'phi_99',
    text: 'Which medieval Christian philosopher and theologian synthesized Aristotelian philosophy with Christian doctrine in works like "Summa Theologica"?',
    text_tr: '"Summa Theologica" gibi eserlerde Aristotelesçi felsefeyi Hristiyan doktriniyle sentezleyen Ortaçağ Hristiyan filozofu ve din bilgini kimdir?',
    options: { A: 'Augustine of Hippo', B: 'Thomas Aquinas', C: 'Anselm of Canterbury', D: 'Duns Scotus', E: 'William of Ockham' },
    options_tr: { A: 'Hippolu Augustinus', B: 'Aquinolu Thomas (Aziz Thomas)', C: 'Canterburylu Anselm', D: 'Duns Scotus', E: 'Ockhamlı William' },
    answer: 'B',
    explanation: 'Thomas Aquinas (1225–1274) synthesized Aristotelian philosophy with Catholic theology in his monumental "Summa Theologica."',
  },
  {
    id: 'phi_100',
    text: 'Which principle, attributed to the medieval philosopher William of Ockham, states that among competing explanations, the simplest one requiring the fewest assumptions should be preferred?',
    text_tr: 'Ortaçağ filozofu Ockhamlı William\'a atfedilen ve rakip açıklamalar arasında en az varsayım gerektiren en basit olanın tercih edilmesi gerektiğini belirten ilke hangisidir?',
    options: { A: 'The Principle of Sufficient Reason', B: 'Ockham\'s Razor', C: 'The Law of Non-Contradiction', D: 'The Principle of Charity', E: 'The Correspondence Theory of Truth' },
    options_tr: { A: 'Yeter Sebep İlkesi', B: 'Ockham\'ın Usturası (Ockham\'s Razor)', C: 'Çelişmezlik İlkesi', D: 'Hayırseverlik İlkesi', E: 'Doğruluğun Uygunluk Teorisi' },
    answer: 'B',
    explanation: 'Ockham\'s Razor is a heuristic principle favoring simplicity in explanations, widely used in philosophy and science.',
  },
];

module.exports = { philosophy };
