'use strict';

const sports = [
  {
    id: 'sport_01',
    text: 'How many players are on the field for one team in a standard soccer match?',
    text_tr: 'Standart bir futbol maçında bir takım için sahada kaç oyuncu bulunur?',
    options: { A: '9', B: '10', C: '11', D: '12', E: '15' },
    options_tr: { A: '9', B: '10', C: '11', D: '12', E: '15' },
    answer: 'C',
    explanation: 'A standard soccer match is played between two teams, each consisting of 11 players including a goalkeeper.',
  },
  {
    id: 'sport_02',
    text: 'Which country has won the most FIFA World Cup titles in history?',
    text_tr: 'Tarihte FIFA Dünya Kupası\'nı en çok kazanan ülke hangisidir?',
    options: { A: 'Germany', B: 'Italy', C: 'Argentina', D: 'Brazil', E: 'France' },
    options_tr: { A: 'Almanya', B: 'İtalya', C: 'Arjantin', D: 'Brezilya', E: 'Fransa' },
    answer: 'D',
    explanation: 'Brazil has won the FIFA World Cup a record five times (1958, 1962, 1970, 1994, and 2002).',
  },
  {
    id: 'sport_03',
    text: 'In basketball, how many seconds does a team have to attempt a shot before a shot-clock violation occurs in the NBA?',
    text_tr: 'Basketbolda (NBA), bir takımın hücum ihlali olmadan şut çekmek için kaç saniyelik süresi vardır?',
    options: { A: '14', B: '20', C: '24', D: '30', E: '35' },
    options_tr: { A: '14', B: '20', C: '24', D: '30', E: '35' },
    answer: 'C',
    explanation: 'The NBA and FIBA use a 24-second shot clock to ensure a fast pace of play.',
  },
  {
    id: 'sport_04',
    text: 'Who is widely regarded as the fastest man in history, holding the world record for the 100m sprint?',
    text_tr: '100 metre koşuda dünya rekorunu elinde tutan ve tarihin en hızlı insanı olarak kabul edilen atlet kimdir?',
    options: { A: 'Carl Lewis', B: 'Justin Gatlin', C: 'Tyson Gay', D: 'Usain Bolt', E: 'Yohan Blake' },
    options_tr: { A: 'Carl Lewis', B: 'Justin Gatlin', C: 'Tyson Gay', D: 'Usain Bolt', E: 'Yohan Blake' },
    answer: 'D',
    explanation: 'Jamaican sprinter Usain Bolt set the 100m world record of 9.58 seconds in Berlin in 2009.',
  },
  {
    id: 'sport_05',
    text: 'Which grand slam tennis tournament is famously played on grass courts?',
    text_tr: 'Hangi grand slam tenis turnuvası çim kortta oynanmasıyla ünlüdür?',
    options: { A: 'Australian Open', B: 'French Open', C: 'Wimbledon', D: 'US Open', E: 'ATP Finals' },
    options_tr: { A: 'Avustralya Açık', B: 'Fransa Açık (Roland Garros)', C: 'Wimbledon', D: 'Amerika Açık', E: 'ATP Finalleri' },
    answer: 'C',
    explanation: 'Wimbledon, held in London, is the oldest tennis tournament in the world and the only Grand Slam still played on grass.',
  },
  {
    id: 'sport_06',
    text: 'How many rings make up the official Olympic symbol?',
    text_tr: 'Resmi Olimpiyat sembolünü kaç adet halka oluşturur?',
    options: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    options_tr: { A: '3', B: '4', C: '5', D: '6', E: '7' },
    answer: 'C',
    explanation: 'The Olympic symbol consists of five interlaced rings, representing the five inhabited continents of the world.',
  },
  {
    id: 'sport_07',
    text: 'Which legendary basketball player spent his entire 20-year NBA career with the Los Angeles Lakers and wore numbers 8 and 24?',
    text_tr: '20 yıllık NBA kariyerinin tamamını Los Angeles Lakers\'ta geçiren, 8 ve 24 numaralı formaları giyen efsanevi basketbolcu kimdir?',
    options: { A: 'Michael Jordan', B: 'Kobe Bryant', C: 'LeBron James', D: 'Shaquille O\'Neal', E: 'Magic Johnson' },
    options_tr: { A: 'Michael Jordan', B: 'Kobe Bryant', C: 'LeBron James', D: 'Shaquille O\'Neal', E: 'Magic Johnson' },
    answer: 'B',
    explanation: 'Kobe Bryant, known as the "Black Mamba", won five NBA championships with the Lakers.',
  },
  {
    id: 'sport_08',
    text: 'What is the standard length of a full marathon in kilometers?',
    text_tr: 'Tam bir maraton koşusunun standart uzunluğu kaç kilometredir?',
    options: { A: '21.1 km', B: '30.0 km', C: '42.195 km', D: '50.0 km', E: '10.0 km' },
    options_tr: { A: '21.1 km', B: '30.0 km', C: '42.195 km', D: '50.0 km', E: '10.0 km' },
    answer: 'C',
    explanation: 'An official marathon covers a distance of 42.195 kilometers (or 26 miles 385 yards).',
  },
  {
    id: 'sport_09',
    text: 'Which motor racing series features the iconic Monaco Grand Prix?',
    text_tr: 'İkonik Monako Grand Prix\'sine ev sahipliği yapan motor sporları serisi hangisidir?',
    options: { A: 'MotoGP', B: 'Formula 1', C: 'NASCAR', D: 'IndyCar', E: 'WRC' },
    options_tr: { A: 'MotoGP', B: 'Formula 1', C: 'NASCAR', D: 'IndyCar', E: 'WRC (Dünya Ralli Şampiyonası)' },
    answer: 'B',
    explanation: 'The Monaco Grand Prix is one of the most prestigious automobile races in the Formula 1 World Championship.',
  },
  {
    id: 'sport_10',
    text: 'Who is the all-time top scorer in UEFA Champions League history?',
    text_tr: 'UEFA Şampiyonlar Ligi tarihinin tüm zamanların en golcü oyuncusu kimdir?',
    options: { A: 'Lionel Messi', B: 'Cristiano Ronaldo', C: 'Robert Lewandowski', D: 'Raúl', E: 'Karim Benzema' },
    options_tr: { A: 'Lionel Messi', B: 'Cristiano Ronaldo', C: 'Robert Lewandowski', D: 'Raúl', E: 'Karim Benzema' },
    answer: 'B',
    explanation: 'Cristiano Ronaldo holds the record for the most goals scored in Champions League history.',
  },
  {
    id: 'sport_11',
    text: 'How many players are on the court for one team in a standard volleyball match?',
    text_tr: 'Standart bir voleybol maçında bir takım adına sahada kaç oyuncu bulunur?',
    options: { A: '5', B: '6', C: '7', D: '8', E: '11' },
    options_tr: { A: '5', B: '6', C: '7', D: '8', E: '11' },
    answer: 'B',
    explanation: 'In indoor volleyball, each team has 6 players on the court at any given time.',
  },
  {
    id: 'sport_12',
    text: 'Which country is traditionally credited with inventing modern golf?',
    text_tr: 'Modern golf sporunun kökeni geleneksel olarak hangi ülkeye dayandırılır?',
    options: { A: 'England', B: 'United States', C: 'Scotland', D: 'Ireland', E: 'France' },
    options_tr: { A: 'İngiltere', B: 'Amerika Birleşik Devletleri', C: 'İskoçya', D: 'İrlanda', E: 'Fransa' },
    answer: 'C',
    explanation: 'The modern game of golf originated in 15th-century Scotland, specifically on the links of St Andrews.',
  },
  {
    id: 'sport_13',
    text: 'What is the color of the jersey worn by the leader of the general classification in the Tour de France?',
    text_tr: 'Fransa Bisiklet Turu\'nda (Tour de France) genel klasman liderinin giydiği formanın rengi nedir?',
    options: { A: 'Green', B: 'Red', C: 'Yellow', D: 'White', E: 'Pink' },
    options_tr: { A: 'Yeşil', B: 'Kırmızı', C: 'Sarı', D: 'Beyaz', E: 'Pembe' },
    answer: 'C',
    explanation: 'The yellow jersey ("maillot jaune") is worn by the overall leader of the Tour de France.',
  },
  {
    id: 'sport_14',
    text: 'In professional boxing, how many rounds are there in a standard men\'s world championship fight?',
    text_tr: 'Profesyonel boks maçlarında, standart bir erkekler dünya şampiyonluğu müsabakası kaç raunttur?',
    options: { A: '10', B: '12', C: '15', D: '8', E: '14' },
    options_tr: { A: '10', B: '12', C: '15', D: '8', E: '14' },
    answer: 'B',
    explanation: 'Professional championship boxing matches were reduced from 15 rounds to 12 rounds in the 1980s for safety reasons.',
  },
  {
    id: 'sport_15',
    text: 'Which tennis player has won the most French Open (Roland Garros) men\'s singles titles in history?',
    text_tr: 'Tarihte Fransa Açık (Roland Garros) erkekler tekler şampiyonluğunu en çok kazanan tenisçi kimdir?',
    options: { A: 'Roger Federer', B: 'Novak Djokovic', C: 'Rafael Nadal', D: 'Björn Borg', E: 'Pete Sampras' },
    options_tr: { A: 'Roger Federer', B: 'Novak Djokovic', C: 'Rafael Nadal', D: 'Björn Borg', E: 'Pete Sampras' },
    answer: 'C',
    explanation: 'Rafael Nadal, the "King of Clay", has won a historic 14 French Open titles.',
  },
  {
    id: 'sport_16',
    text: 'What unique object is used instead of a ball in the sport of ice hockey?',
    text_tr: 'Buz hokeyi sporunda top yerine kullanılan özel nesneye ne ad verilir?',
    options: { A: 'Disc', B: 'Puck', C: 'Ring', D: 'Shuttlecock', E: 'Stone' },
    options_tr: { A: 'Disk', B: 'Pak (Puck)', C: 'Halka', D: 'Tüytop', E: 'Taş' },
    answer: 'B',
    explanation: 'Ice hockey is played with a puck, which is a flat, solid vulcanized rubber disc.',
  },
  {
    id: 'sport_17',
    text: 'Which driver holds the record for the most Formula 1 World Championship titles, tied with Michael Schumacher?',
    text_tr: 'Michael Schumacher ile eşit sayıda, en çok Formula 1 Dünya Şampiyonluğu kazanma rekorunu paylaşan pilot kimdir?',
    options: { A: 'Sebastian Vettel', B: 'Lewis Hamilton', C: 'Max Verstappen', D: 'Fernando Alonso', E: 'Ayrton Senna' },
    options_tr: { A: 'Sebastian Vettel', B: 'Lewis Hamilton', C: 'Max Verstappen', D: 'Fernando Alonso', E: 'Ayrton Senna' },
    answer: 'B',
    explanation: 'Lewis Hamilton has won 7 World Championships, tying the record held by Michael Schumacher.',
  },
  {
    id: 'sport_18',
    text: 'How often are the Olympic Games held?',
    text_tr: 'Olimpiyat Oyunları kaç yılda bir düzenlenir?',
    options: { A: 'Every year', B: 'Every 2 years', C: 'Every 3 years', D: 'Every 4 years', E: 'Every 5 years' },
    options_tr: { A: 'Her yıl', B: '2 yılda bir', C: '3 yılda bir', D: '4 yılda bir', E: '5 yılda bir' },
    answer: 'D',
    explanation: 'Both the Summer and Winter Olympic Games are held every 4 years.',
  },
  {
    id: 'sport_19',
    text: 'What team won the first-ever Super Bowl in NFL history in 1967?',
    text_tr: '1967 yılında Amerikan Futbolu (NFL) tarihinin ilk Super Bowl kupasını hangi takım kazanmıştır?',
    options: { A: 'Dallas Cowboys', B: 'Green Bay Packers', C: 'New England Patriots', D: 'Kansas City Chiefs', E: 'Pittsburgh Steelers' },
    options_tr: { A: 'Dallas Cowboys', B: 'Green Bay Packers', C: 'New England Patriots', D: 'Kansas City Chiefs', E: 'Pittsburgh Steelers' },
    answer: 'B',
    explanation: 'The Green Bay Packers won Super Bowl I by defeating the Kansas City Chiefs 35-10.',
  },
  {
    id: 'sport_20',
    text: 'In professional swimming, which stroke is generally considered the slowest?',
    text_tr: 'Profesyonel yüzmede, genel olarak en yavaş yüzme stili hangisi kabul edilir?',
    options: { A: 'Freestyle', B: 'Backstroke', C: 'Butterfly', D: 'Breaststroke', E: 'Dog paddle' },
    options_tr: { A: 'Serbest stil', B: 'Sırtüstü', C: 'Kelebek', D: 'Kurbağalama', E: 'Köpek fersahi' },
    answer: 'D',
    explanation: 'Breaststroke is mechanically the slowest of the four competitive swimming strokes.',
  },
  {
    id: 'sport_21',
    text: 'Which gymnast won four gold medals at the 2016 Rio Olympics and is widely called the "GOAT" of gymnastics?',
    text_tr: '2016 Rio Olimpiyatları\'nda dört altın madalya kazanan ve jimnastiğin "en büyüğü" kabul edilen sporcu kimdir?',
    options: { A: 'Nadia Comăneci', B: 'Simone Biles', C: 'Aliya Mustafina', D: 'Gabby Douglas', E: 'Sunisa Lee' },
    options_tr: { A: 'Nadia Comăneci', B: 'Simone Biles', C: 'Aliya Mustafina', D: 'Gabby Douglas', E: 'Sunisa Lee' },
    answer: 'B',
    explanation: 'Simone Biles is the most decorated gymnast in history, renowned for her incredible difficulty and execution.',
  },
  {
    id: 'sport_22',
    text: 'What is the score name given to a zero score in a tennis game?',
    text_tr: 'Tenis maçlarında sıfır puana verilen özel ad nedir?',
    options: { A: 'Nil', B: 'Love', C: 'Blank', D: 'Zero', E: 'Deuce' },
    options_tr: { A: 'Nil', B: 'Love', C: 'Blank', D: 'Zero', E: 'Deuce (Beraberlik)' },
    answer: 'B',
    explanation: 'In tennis scoring, "Love" represents zero points, likely derived from the French word for egg ("l\'oeuf"), meaning a zero shape.',
  },
  {
    id: 'sport_23',
    text: 'Which English football club has won the most top-flight league titles in English football history?',
    text_tr: 'İngiliz futbol tarihinde en çok en üst düzey lig şampiyonluğu yaşayan futbol kulübü hangisidir?',
    options: { A: 'Arsenal', B: 'Chelsea', C: 'Liverpool', D: 'Manchester United', E: 'Manchester City' },
    options_tr: { A: 'Arsenal', B: 'Chelsea', C: 'Liverpool', D: 'Manchester United', E: 'Manchester City' },
    answer: 'D',
    explanation: 'Manchester United has won 20 English top-flight titles, closely followed by Liverpool with 19.',
  },
  {
    id: 'sport_24',
    text: 'What country dominates the sport of table tennis, winning the vast majority of Olympic gold medals?',
    text_tr: 'Masa tenisi sporunu domine eden ve Olimpiyat altın madalyalarının büyük çoğunluğunu kazanan ülke hangisidir?',
    options: { A: 'Japan', B: 'South Korea', C: 'China', D: 'Germany', E: 'Sweden' },
    options_tr: { A: 'Japonya', B: 'Güney Kore', C: 'Çin', D: 'Almanya', E: 'İsveç' },
    answer: 'C',
    explanation: 'China has won more than 30 of the available gold medals since table tennis was introduced to the Olympics in 1988.',
  },
  {
    id: 'sport_25',
    text: 'How many players are on the field at a time for a single team in American football?',
    text_tr: 'Amerikan futbolunda bir takım için sahada aynı anda kaç oyuncu bulunur?',
    options: { A: '9', B: '10', C: '11', D: '13', E: '15' },
    options_tr: { A: '9', B: '10', C: '11', D: '13', E: '15' },
    answer: 'C',
    explanation: 'Just like association football (soccer), American football is played with 11 players per team on the field.',
  },
  {
    id: 'sport_26',
    text: 'Which legendary boxer famously proclaimed "Float like a butterfly, sting like a bee"?',
    text_tr: '"Kelebek gibi uçarım, arı gibi sokarım" sözüyle ünlü efsanevi boksör kimdir?',
    options: { A: 'Mike Tyson', B: 'Joe Frazier', C: 'Muhammad Ali', D: 'Sugar Ray Robinson', E: 'George Foreman' },
    options_tr: { A: 'Mike Tyson', B: 'Joe Frazier', C: 'Muhammed Ali', D: 'Sugar Ray Robinson', E: 'George Foreman' },
    answer: 'C',
    explanation: 'Muhammad Ali used this iconic catchphrase to describe his quick-footed and hard-hitting fighting style.',
  },
  {
    id: 'sport_27',
    text: 'What color is the center bullseye circle on a standard archery target?',
    text_tr: 'Standart bir okçuluk hedef tahtasındaki en içte yer alan merkez dairenin rengi nedir?',
    options: { A: 'Red', B: 'White', C: 'Black', D: 'Yellow', E: 'Blue' },
    options_tr: { A: 'Kırmızı', B: 'Beyaz', C: 'Siyah', D: 'Sarı', E: 'Mavi' },
    answer: 'D',
    explanation: 'The center rings of an archery target, indicating the maximum 10 and 9 points, are colored gold/yellow.',
  },
  {
    id: 'sport_28',
    text: 'Who is the all-time leading scorer in NBA history?',
    text_tr: 'NBA tarihinin tüm zamanların en çok sayı atan oyuncusu kimdir?',
    options: { A: 'Michael Jordan', B: 'Kareem Abdul-Jabbar', C: 'Kobe Bryant', D: 'Karl Malone', E: 'LeBron James' },
    options_tr: { A: 'Michael Jordan', B: 'Kareem Abdul-Jabbar', C: 'Kobe Bryant', D: 'Karl Malone', E: 'LeBron James' },
    answer: 'E',
    explanation: 'LeBron James surpassed Kareem Abdul-Jabbar\'s long-standing record to become the NBA\'s all-time leading scorer.',
  },
  {
    id: 'sport_29',
    text: 'Which team won the 2022 FIFA World Cup held in Qatar?',
    text_tr: 'Katar\'da düzenlenen 2022 FIFA Dünya Kupası\'nı hangi takım kazanmıştır?',
    options: { A: 'France', B: 'Croatia', C: 'Brazil', D: 'Argentina', E: 'Morocco' },
    options_tr: { A: 'Fransa', B: 'Hırvatistan', C: 'Brezilya', D: 'Arjantin', E: 'Fas' },
    answer: 'D',
    explanation: 'Argentina won their third World Cup title in 2022 by defeating France in a dramatic penalty shootout.',
  },
  {
    id: 'sport_30',
    text: 'In golf, what term is used when a player finishes a hole two strokes under par?',
    text_tr: 'Golfte, bir delikle ilgili belirlenen vuruş sayısından (par) iki vuruş daha azıyla bitirmeye ne ad verilir?',
    options: { A: 'Bogey', B: 'Birdie', C: 'Eagle', D: 'Albatross', E: 'Mulligan' },
    options_tr: { A: 'Bogey', B: 'Birdie', C: 'Eagle (Kartal)', D: 'Albatross', E: 'Mulligan' },
    answer: 'C',
    explanation: 'One under par is a "Birdie", two under par is an "Eagle", and three under par is an "Albatross".',
  },
  {
    id: 'sport_31',
    text: 'Which ice hockey nation has won the most Winter Olympic gold medals in men\'s tournament history?',
    text_tr: 'Erkekler buz hokeyi tarihinde Kış Olimpiyatları\'nda en çok altın madalya kazanan ülke hangisidir?',
    options: { A: 'United States', B: 'Canada', C: 'Russia / Soviet Union', D: 'Sweden', E: 'Finland' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Kanada', C: 'Rusya / Sovyetler Birliği', D: 'İsveç', E: 'Finlandiya' },
    answer: 'B',
    explanation: 'Canada is the most successful nation in Olympic ice hockey, historically capturing the most gold medals.',
  },
  {
    id: 'sport_32',
    text: 'How long is a standard professional swimming pool used in the Olympic Games?',
    text_tr: 'Olimpiyat Oyunları\'nda kullanılan standart bir profesyonel yüzme havuzunun boyu kaç metredir?',
    options: { A: '25 meters', B: '50 meters', C: '100 meters', D: '75 meters', E: '40 meters' },
    options_tr: { A: '25 metre', B: '50 metre', C: '100 metre', D: '75 metre', E: '40 metre' },
    answer: 'B',
    explanation: 'Olympic-size swimming pools are exactly 50 meters long, commonly referred to as "long course".',
  },
  {
    id: 'sport_33',
    text: 'In which country did Bruce Lee officially found his martial art style Jeet Kune Do?',
    text_tr: 'Bruce Lee\'nin kendi imza dövüş stili Jeet Kune Do\'yu resmi olarak kurduğu ülke hangisidir?',
    options: { A: 'China', B: 'Japan', C: 'Hong Kong', D: 'United States', E: 'Thailand' },
    options_tr: { A: 'Çin', B: 'Japonya', C: 'Hong Kong', D: 'Amerika Birleşik Devletleri', E: 'Tayland' },
    answer: 'D',
    explanation: 'Bruce Lee officially founded Jeet Kune Do in the United States in 1967.',
  },
  {
    id: 'sport_34',
    text: 'In baseball, how many total defensive players are on the field at any one time?',
    text_tr: 'Beyzbolda, sahada aynı anda savunma yapan toplam kaç oyuncu bulunur?',
    options: { A: '7', B: '8', C: '9', D: '10', E: '11' },
    options_tr: { A: '7', B: '8', C: '9', D: '10', E: '11' },
    answer: 'C',
    explanation: 'The defending team has 9 players on the baseball field trying to get the batters out.',
  },
  {
    id: 'sport_35',
    text: 'Which legendary athlete won 9 Olympic gold medals in sprinting and long jump during the 1980s and 1990s?',
    text_tr: '1980\'li ve 90\'lı yıllarda kısa mesafe koşu ve uzun atlamada toplam 9 Olimpiyat altın madalyası kazanan efsanevi atlet kimdir?',
    options: { A: 'Usain Bolt', B: 'Carl Lewis', C: 'Michael Johnson', D: 'Jesse Owens', E: 'Linford Christie' },
    options_tr: { A: 'Usain Bolt', B: 'Carl Lewis', C: 'Michael Johnson', D: 'Jesse Owens', E: 'Linford Christie' },
    answer: 'B',
    explanation: 'American track and field athlete Carl Lewis won 9 Olympic gold medals across four consecutive Games.',
  },
  {
    id: 'sport_36',
    text: 'Which country hosts the annual tennis tournament known as the "Australian Open"?',
    text_tr: '"Avustralya Açık" yıllık tenis turnuvasına ev sahipliği yapan ülke hangisidir?',
    options: { A: 'New Zealand', B: 'Australia', C: 'United Kingdom', D: 'United States', E: 'Austria' },
    options_tr: { A: 'Yeni Zelanda', B: 'Avustralya', C: 'Birleşik Krallık', D: 'Amerika Birleşik Devletleri', E: 'Avusturya' },
    answer: 'B',
    explanation: 'The Australian Open is held annually in Melbourne, Australia, as the first Grand Slam of the calendar year.',
  },
  {
    id: 'sport_37',
    text: 'What sport uses a net, rackets, and a lightweight projectile called a "shuttlecock"?',
    text_tr: 'Ağ, raketler ve "tüytop" (shuttlecock) adı verilen hafif bir nesne kullanılan spor hangisidir?',
    options: { A: 'Tennis', B: 'Table Tennis', C: 'Badminton', D: 'Squash', E: 'Pickleball' },
    options_tr: { A: 'Tenis', B: 'Masa Tenisi', C: 'Badminton', D: 'Skuaş (Squash)', E: 'Pickleball' },
    answer: 'C',
    explanation: 'Badminton is a racket sport played with a shuttlecock across an elevated net.',
  },
  {
    id: 'sport_38',
    text: 'Which country\'s national rugby union team is famously known as the "All Blacks"?',
    text_tr: 'Ulusal ragbi takımı dünya çapında "All Blacks" olarak bilinen ülke hangisidir?',
    options: { A: 'Australia', B: 'South Africa', C: 'England', D: 'New Zealand', E: 'Ireland' },
    options_tr: { A: 'Avustralya', B: 'Güney Afrika', C: 'İngiltere', D: 'Yeni Zelanda', E: 'İrlanda' },
    answer: 'D',
    explanation: 'New Zealand\'s national rugby team is named the All Blacks due to their entirely black team kit.',
  },
  {
    id: 'sport_39',
    text: 'How many total pockets are there on a standard pool/billiards table?',
    text_tr: 'Standart bir bilardo masasında toplam kaç adet cep (delik) bulunur?',
    options: { A: '4', B: '6', C: '8', D: '10', E: '12' },
    options_tr: { A: '4', B: '6', C: '8', D: '10', E: '12' },
    answer: 'B',
    explanation: 'A standard pool table has 6 pockets: one at each of the four corners and one in the middle of each long side.',
  },
  {
    id: 'sport_40',
    text: 'What soccer stadium in Rio de Janeiro hosted the final match of both the 1950 and 2014 FIFA World Cups?',
    text_tr: 'Rio de Janeiro\'da bulunan ve hem 1950 hem de 2014 FIFA Dünya Kupası final maçlarına ev sahipliği yapan stadyum hangisidir?',
    options: { A: 'Camp Nou', B: 'Wembley Stadium', C: 'Maracanã Stadium', D: 'San Siro', E: 'La Bombonera' },
    options_tr: { A: 'Camp Nou', B: 'Wembley Stadyumu', C: 'Maracanã Stadyumu', D: 'San Siro', E: 'La Bombonera' },
    answer: 'C',
    explanation: 'The Maracanã Stadium is one of the most historic and famous football stadiums in the world.',
  },
  {
    id: 'sport_41',
    text: 'In cycling, which famous grand tour features the mountain climb known as the "Alpe d\'Huez"?',
    text_tr: 'Bisiklette, "Alpe d\'Huez" zirve tırmanışıyla ünlü olan büyük tur hangisidir?',
    options: { A: 'Giro d\'Italia', B: 'Vuelta a España', C: 'Tour de France', D: 'Tour de Suisse', E: 'Paris-Roubaix' },
    options_tr: { A: 'Giro d\'Italia (İtalya Turu)', B: 'Vuelta a España (İspanya Turu)', C: 'Tour de France (Fransa Turu)', D: 'Tour de Suisse', E: 'Paris-Roubaix' },
    answer: 'C',
    explanation: 'Alpe d\'Huez is one of the most legendary and challenging mountain stages in the Tour de France.',
  },
  {
    id: 'sport_42',
    text: 'What basic equipment is worn on the hands by competitors in the sport of curling?',
    text_tr: 'Köling (curling) sporunda yarışmacıların ellerine giydiği temel ekipman hangisidir?',
    options: { A: 'Gloves', B: 'Tape', C: 'Chalk', D: 'Pads', E: 'Nothing' },
    options_tr: { A: 'Eldiven', B: 'Sargı (Bant)', C: 'Tebeşir tozu', D: 'Koruyucu ped', E: 'Hiçbir şey' },
    answer: 'A',
    explanation: 'Curlers wear specialized gloves to keep their hands warm and maintain a solid grip on the stone handle.',
  },
  {
    id: 'sport_43',
    text: 'Which NFL franchise has won the most Super Bowl titles, tied with the New England Patriots?',
    text_tr: 'New England Patriots ile birlikte en çok Super Bowl şampiyonluğu kazanma rekorunu paylaşan NFL takımı hangisidir?',
    options: { A: 'Dallas Cowboys', B: 'San Francisco 49ers', C: 'Pittsburgh Steelers', D: 'Green Bay Packers', E: 'Kansas City Chiefs' },
    options_tr: { A: 'Dallas Cowboys', B: 'San Francisco 49ers', C: 'Pittsburgh Steelers', D: 'Green Bay Packers', E: 'Kansas City Chiefs' },
    answer: 'C',
    explanation: 'Both the Pittsburgh Steelers and the New England Patriots have won a record 6 Super Bowl titles.',
  },
  {
    id: 'sport_44',
    text: 'In cricket, what are the vertical wooden posts called that the bowler attempts to hit?',
    text_tr: 'Krikette, atıcının vurmaya çalıştığı dikey ahşap direklere ne ad verilir?',
    options: { A: 'Bails', B: 'Wickets / Stumps', C: 'Bats', D: 'Creases', E: 'Bases' },
    options_tr: { A: 'Bail', B: 'Wicket / Stump (Kale direkleri)', C: 'Sopa (Bat)', D: 'Crease', E: 'Base' },
    answer: 'B',
    explanation: 'Stumps are the three vertical posts that make up the wicket, which the defensive bowler aims to hit.',
  },
  {
    id: 'sport_45',
    text: 'Who was the first female tennis player to achieve 23 Grand Slam singles titles in the Open Era?',
    text_tr: 'Açık Dönem\'de 23 Grand Slam tekler şampiyonluğuna ulaşan ilk kadın tenisçi kimdir?',
    options: { A: 'Steffi Graf', B: 'Martina Navratilova', C: 'Serena Williams', D: 'Venus Williams', E: 'Margaret Court' },
    options_tr: { A: 'Steffi Graf', B: 'Martina Navratilova', C: 'Serena Williams', D: 'Venus Williams', E: 'Margaret Court' },
    answer: 'C',
    explanation: 'Serena Williams holds the Open Era record for the most Grand Slam singles titles by any player, male or female.',
  },
  {
    id: 'sport_46',
    text: 'What term is used in bowling when a player throws three consecutive strikes?',
    text_tr: 'Labut devirme (bowling) oyununda peş peşe üç kez tam isabet (strike) yapmaya ne ad verilir?',
    options: { A: 'Hat-trick', B: 'Turkey', C: 'Triple', D: 'Perfect Circle', E: 'Clean Sweep' },
    options_tr: { A: 'Hat-trick', B: 'Hindi (Turkey)', C: 'Üçleme', D: 'Kusursuz Döngü', E: 'Silip Süpürme' },
    answer: 'B',
    explanation: 'In bowling lingo, rolling three strikes in a row is traditionally called a "Turkey".',
  },
  {
    id: 'sport_47',
    text: 'Which national team won the UEFA Euro 2020 football tournament (played in 2021)?',
    text_tr: '2021 yılında düzenlenen UEFA Euro 2020 Avrupa Futbol Şampiyonası\'nı hangi ülke kazanmıştır?',
    options: { A: 'England', B: 'France', C: 'Italy', D: 'Spain', E: 'Portugal' },
    options_tr: { A: 'İngiltere', B: 'Fransa', C: 'İtalya', D: 'İspanya', E: 'Portekiz' },
    answer: 'C',
    explanation: 'Italy won Euro 2020 by defeating England in a penalty shootout at Wembley Stadium.',
  },
  {
    id: 'sport_48',
    text: 'In Formula 1 racing, what color flag indicates to drivers that they must slow down due to a hazard on the track?',
    text_tr: 'Formula 1 yarışlarında pistteki bir tehlike nedeniyle pilotların yavaşlaması gerektiğini bildiren bayrak rengi nedir?',
    options: { A: 'Red flag', B: 'Green flag', C: 'Yellow flag', D: 'Blue flag', E: 'Black flag' },
    options_tr: { A: 'Kırmızı bayrak', B: 'Yeşil bayrak', C: 'Sarı bayrak', D: 'Mavi bayrak', E: 'Siyah bayrak' },
    answer: 'C',
    explanation: 'A yellow flag signals danger and prohibits overtaking, warning drivers to slow down.',
  },
  {
    id: 'sport_49',
    text: 'Which legendary NHL player is universally known as "The Great One"?',
    text_tr: 'Hangi efsanevi NHL (buz hokeyi) oyuncusu dünya çapında "The Great One" (En Büyük) lakabıyla tanınır?',
    options: { A: 'Mario Lemieux', B: 'Wayne Gretzky', C: 'Sidney Crosby', D: 'Alex Ovechkin', E: 'Gordie Howe' },
    options_tr: { A: 'Mario Lemieux', B: 'Wayne Gretzky', C: 'Sidney Crosby', D: 'Alex Ovechkin', E: 'Gordie Howe' },
    answer: 'B',
    explanation: 'Wayne Gretzky is widely considered the greatest hockey player of all time, holding almost every scoring record.',
  },
  {
    id: 'sport_50',
    text: 'What is the maximum possible score a player can achieve in a single standard game of 10-pin bowling?',
    text_tr: 'Standart bir 10 labutlu bowling oyununda bir oyuncunun alabileceği maksimum kusursuz puan kaçtır?',
    options: { A: '150', B: '200', C: '250', D: '300', E: '400' },
    options_tr: { A: '150', B: '200', C: '250', D: '300', E: '400' },
    answer: 'D',
    explanation: 'A perfect game in bowling consists of 12 consecutive strikes, resulting in a maximum score of 300 points.',
  },
  {
    id: 'sport_51',
    text: 'Which country is famous for originating the modern martial art of Judo?',
    text_tr: 'Modern bir dövüş sanatı olan Judo hangi ülkede doğmuştur?',
    options: { A: 'China', B: 'South Korea', C: 'Japan', D: 'Thailand', E: 'Brazil' },
    options_tr: { A: 'Çin', B: 'Güney Kore', C: 'Japonya', D: 'Tayland', E: 'Brezilya' },
    answer: 'C',
    explanation: 'Judo was created in Japan in 1882 by Jigoro Kano as a physical, mental, and moral pedagogy.',
  },
  {
    id: 'sport_52',
    text: 'How many players are on the field for one team in a standard baseball game?',
    text_tr: 'Standart bir beyzbol maçında bir takım adına sahada kaç oyuncu bulunur?',
    options: { A: '9', B: '11', C: '7', D: '10', E: '12' },
    options_tr: { A: '9', B: '11', C: '7', D: '10', E: '12' },
    answer: 'A',
    explanation: 'A standard baseball team has 9 players on the field during defense.',
  },
  {
    id: 'sport_53',
    text: 'Which famous association football cup is the oldest national football competition in the world?',
    text_tr: 'Dünyanın en eski ulusal futbol müsabakası kabul edilen futbol kupası hangisidir?',
    options: { A: 'FIFA World Cup', B: 'Copa América', C: 'The FA Cup', D: 'UEFA Champions League', E: 'Copa del Rey' },
    options_tr: { A: 'FIFA Dünya Kupası', B: 'Copa América', C: 'FA Cup (İngiltere Federasyon Kupası)', D: 'UEFA Şampiyonlar Ligi', E: 'Copa del Rey' },
    answer: 'C',
    explanation: 'The FA Cup (Football Association Challenge Cup) was first played during the 1871-72 season in England.',
  },
  {
    id: 'sport_54',
    text: 'In tennis, what score follows 30 in a game point progression?',
    text_tr: 'Teniste oyun puanı ilerlemesinde 30\'dan sonra hangi puan gelir?',
    options: { A: '35', B: '40', C: '45', D: '50', E: 'Game' },
    options_tr: { A: '35', B: '40', C: '45', D: '50', E: 'Oyun' },
    answer: 'B',
    explanation: 'The scoring steps in a tennis game are 15, 30, 40, and then game point.',
  },
  {
    id: 'sport_55',
    text: 'What team won the NBA Championship in 2023, capturing their first franchise title?',
    text_tr: '2023 yılında tarihinin ilk NBA şampiyonluğunu kazanan takım hangisidir?',
    options: { A: 'Miami Heat', B: 'Boston Celtics', C: 'Denver Nuggets', D: 'Phoenix Suns', E: 'Golden State Warriors' },
    options_tr: { A: 'Miami Heat', B: 'Boston Celtics', C: 'Denver Nuggets', D: 'Phoenix Suns', E: 'Golden State Warriors' },
    answer: 'C',
    explanation: 'The Denver Nuggets, led by Nikola Jokić, won the 2023 NBA Finals by defeating the Miami Heat.',
  },
  {
    id: 'sport_56',
    text: 'Which international multi-sport event is organized specifically for athletes with physical disabilities?',
    text_tr: 'Fiziksel engelli sporcular için özel olarak düzenlenen uluslararası çok sporlu organizasyon hangisidir?',
    options: { A: 'Special Olympics', B: 'Paralympic Games', C: 'Invictus Games', D: 'Deaflympics', E: 'World Games' },
    options_tr: { A: 'Özel Olimpiyatlar', B: 'Paralimpik Oyunları', C: 'Invictus Oyunları', D: 'İşitme Engelliler Olimpiyatları', E: 'Dünya Oyunları' },
    answer: 'B',
    explanation: 'The Paralympic Games are held immediately following the respective Summer and Winter Olympic Games.',
  },
  {
    id: 'sport_57',
    text: 'What is the color of the card shown by a soccer referee to completely eject a player from the game?',
    text_tr: 'Futbolda hakemin bir oyuncuyu oyundan tamamen ihraç etmek için gösterdiği kartın rengi nedir?',
    options: { A: 'Yellow', B: 'Green', C: 'Red', D: 'White', E: 'Blue' },
    options_tr: { A: 'Sarı', B: 'Yeşil', C: 'Kırmızı', D: 'Beyaz', E: 'Mavi' },
    answer: 'C',
    explanation: 'A red card indicates that a player has committed a serious offense and must immediately leave the field.',
  },
  {
    id: 'sport_58',
    text: 'In track and field, how many events make up a standard men\'s decathlon?',
    text_tr: 'Atletizmde, standart bir erkekler dekatlon müsabakası toplam kaç yarıştan oluşur?',
    options: { A: '5', B: '7', C: '10', D: '12', E: '15' },
    options_tr: { A: '5', B: '7', C: '10', D: '12', E: '15' },
    answer: 'C',
    explanation: 'A decathlon is a combined event consisting of 10 track and field disciplines held over two days.',
  },
  {
    id: 'sport_59',
    text: 'Which legendary Portuguese football player has won five Ballon d\'Or awards and is famous for his number 7 jersey?',
    text_tr: 'Kariyerinde 5 kez Ballon d\'Or kazanan ve 7 numaralı formasıyla özdeşleşen efsanevi Portekizli futbolcu kimdir?',
    options: { A: 'Luís Figo', B: 'Eusébio', C: 'Cristiano Ronaldo', D: 'Bruno Fernandes', E: 'João Félix' },
    options_tr: { A: 'Luís Figo', B: 'Eusébio', C: 'Cristiano Ronaldo', D: 'Bruno Fernandes', E: 'João Félix' },
    answer: 'C',
    explanation: 'Cristiano Ronaldo, often called CR7, is one of the most successful and decorated players in football history.',
  },
  {
    id: 'sport_60',
    text: 'What is the name of the tournament trophy awarded annually to the NHL champion?',
    text_tr: 'Her yıl National Hockey League (NHL) şampiyonuna verilen tarihi kupanın adı nedir?',
    options: { A: 'The Larry O\'Brien Trophy', B: 'The Stanley Cup', C: 'The Vince Lombardi Trophy', D: 'The Commissioner\'s Trophy', E: 'The Calder Cup' },
    options_tr: { A: 'Larry O\'Brien Kupası', B: 'Stanley Kupası (Stanley Cup)', C: 'Vince Lombardi Kupası', D: 'Kombine Edilmiş Kupa', E: 'Calder Kupası' },
    answer: 'B',
    explanation: 'The Stanley Cup is the oldest professional sports trophy in North America, awarded since 1893.',
  },
  {
    id: 'sport_61',
    text: 'In table tennis, how many points must a player score to win a standard modern game (assuming a 2-point lead)?',
    text_tr: 'Masa tenisinde, standart modern bir seti kazanmak için bir oyuncunun en az kaç sayıya ulaşması gerekir (2 fark kuralı dahilinde)?',
    options: { A: '11', B: '15', C: '21', D: '25', E: '30' },
    options_tr: { A: '11', B: '15', C: '21', D: '25', E: '30' },
    answer: 'A',
    explanation: 'In 2001, the ITTF officially changed the game score requirement from 21 points down to 11 points.',
  },
  {
    id: 'sport_62',
    text: 'Which American city hosts the annual "Indianapolis 500" motorsport race?',
    text_tr: '"Indianapolis 500" tarihi dayanıklılık yarışına ev sahipliği yapan Amerika şehri hangisidir?',
    options: { A: 'Daytona', B: 'Indianapolis', C: 'Detroit', D: 'Austin', E: 'Miami' },
    options_tr: { A: 'Daytona', B: 'Indianapolis', C: 'Detroit', D: 'Austin', E: 'Miami' },
    answer: 'B',
    explanation: 'The Indy 500 is held annually at the Indianapolis Motor Speedway in Speedway, Indiana.',
  },
  {
    id: 'sport_63',
    text: 'What country dominates the historical medal standings in Olympic weightlifting\'s heavier divisions?',
    text_tr: 'Modern Olimpiyat halter tarihindeki ağır sıklet kategorilerinde madalya sıralamasını domine eden ülke hangisidir?',
    options: { A: 'United States', B: 'China', C: 'Soviet Union / Russia', D: 'Turkey', E: 'Greece' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Çin', C: 'Sovyetler Birliği / Rusya', D: 'Türkiye', E: 'Yunanistan' },
    answer: 'C',
    explanation: 'The Soviet Union and subsequently Russian athletes historically dominated the heavy lifting divisions in weightlifting.',
  },
  {
    id: 'sport_64',
    text: 'In horse racing, what term is used when a single horse wins the Kentucky Derby, Preakness Stakes, and Belmont Stakes in the same year?',
    text_tr: 'At yarışçılığında, bir atın aynı yıl içinde Kentucky Derby, Preakness ve Belmont Stakes yarışlarının tümünü kazanmasına ne ad verilir?',
    options: { A: 'Grand Slam', B: 'Triple Crown', C: 'Hat-Trick', D: 'Perfect Run', E: 'Superfecta' },
    options_tr: { A: 'Grand Slam', B: 'Üçlü Taç (Triple Crown)', C: 'Hat-Trick', D: 'Kusursuz Koşu', E: 'Superfecta' },
    answer: 'B',
    explanation: 'Winning these three prestigious races for three-year-old Thoroughbreds is called winning the Triple Crown.',
  },
  {
    id: 'sport_65',
    text: 'Which American Olympic swimmer holds the all-time record for the most Olympic gold medals (23)?',
    text_tr: 'Tarihte en çok Olimpiyat altın madalyası (23) kazanma rekorunu elinde tutan efsanevi Amerikalı yüzücü kimdir?',
    options: { A: 'Ian Thorpe', B: 'Caeleb Dressel', C: 'Michael Phelps', D: 'Ryan Lochte', E: 'Mark Spitz' },
    options_tr: { A: 'Ian Thorpe', B: 'Caeleb Dressel', C: 'Michael Phelps', D: 'Ryan Lochte', E: 'Mark Spitz' },
    answer: 'C',
    explanation: 'Michael Phelps has won a total of 28 Olympic medals, 23 of which are gold, making him the most decorated Olympian ever.',
  },
  {
    id: 'sport_66',
    text: 'Which nation won the first-ever FIFA World Cup held in 1930?',
    text_tr: '1930 yılında düzenlenen ilk FIFA Dünya Kupası\'nı hangi ülke kazanmıştır?',
    options: { A: 'Brazil', B: 'Argentina', C: 'Uruguay', D: 'Italy', E: 'France' },
    options_tr: { A: 'Brezilya', B: 'Arjantin', C: 'Uruguay', D: 'İtalya', E: 'Fransa' },
    answer: 'C',
    explanation: 'Uruguay hosted and won the inaugural FIFA World Cup, defeating Argentina 4-2 in the final.',
  },
  {
    id: 'sport_67',
    text: 'In professional darts, what is the highest possible score a player can achieve with a single dart?',
    text_tr: 'Profesyonel dart oyununda bir oyuncunun tek bir ok atışıyla alabileceği en yüksek puan kaçtır?',
    options: { A: '20', B: '50', C: '60', D: '100', E: '180' },
    options_tr: { A: '20', B: '50', C: '60', D: '100', E: '180' },
    answer: 'C',
    explanation: 'Hitting the triple 20 segment yields 60 points, which is higher than an inner bullseye (50 points).',
  },
  {
    id: 'sport_68',
    text: 'Which NBA team did Michael Jordan lead to six championships during the 1990s?',
    text_tr: 'Michael Jordan\'ın 1990\'lı yıllarda altı kez şampiyonluğa taşıdığı NBA takımı hangisidir?',
    options: { A: 'Los Angeles Lakers', B: 'Chicago Bulls', C: 'Boston Celtics', D: 'New York Knicks', E: 'Miami Heat' },
    options_tr: { A: 'Los Angeles Lakers', B: 'Chicago Bulls', C: 'Boston Celtics', D: 'New York Knicks', E: 'Miami Heat' },
    answer: 'B',
    explanation: 'Michael Jordan won all six of his NBA titles and Finals MVP awards with the Chicago Bulls.',
  },
  {
    id: 'sport_69',
    text: 'What is the literal translation of the Japanese word "Karate"?',
    text_tr: 'Japonca bir kelime olan "Karate"nin tam kelime anlamı nedir?',
    options: { A: 'Empty Hand', B: 'Strong Fist', C: 'Way of Life', D: 'Swift Strike', E: 'Silent Shadow' },
    options_tr: { A: 'Boş El', B: 'Güçlü Yumruk', C: 'Yaşam Yolu', D: 'Hızlı Vuruş', E: 'Sessiz Gölge' },
    answer: 'A',
    explanation: '"Kara" translates to empty, and "te" means hand, symbolizing fighting without weapons.',
  },
  {
    id: 'sport_70',
    text: 'Which Spanish tennis player won the men\'s singles title at Wimbledon in 2023 by defeating Novak Djokovic?',
    text_tr: '2023 Wimbledon erkekler tekler finalinde Novak Djokovic\'i yenerek şampiyon olan genç İspanyol tenisçi kimdir?',
    options: { A: 'Rafael Nadal', B: 'Carlos Alcaraz', C: 'Daniil Medvedev', D: 'Stefanos Tsitsipas', E: 'Casper Ruud' },
    options_tr: { A: 'Rafael Nadal', B: 'Carlos Alcaraz', C: 'Daniil Medvedev', D: 'Stefanos Tsitsipas', E: 'Casper Ruud' },
    answer: 'B',
    explanation: 'Carlos Alcaraz won an epic five-set final to secure his first Wimbledon title in 2023.',
  },
  {
    id: 'sport_71',
    text: 'What country\'s team is the most successful in the history of the America\'s Cup sailing race?',
    text_tr: 'Efsanevi "Amerika Kupası" yelken yarışı tarihinin en başarılı ülkesi hangisidir?',
    options: { A: 'United Kingdom', B: 'New Zealand', C: 'United States', D: 'Australia', E: 'France' },
    options_tr: { A: 'Birleşik Krallık', B: 'Yeni Zelanda', C: 'Amerika Birleşik Devletleri', D: 'Avustralya', E: 'Fransa' },
    answer: 'C',
    explanation: 'The United States dominated the America\'s Cup, winning the trophy for the first 132 years of the competition.',
  },
  {
    id: 'sport_72',
    text: 'In association football, how long is the standard halftime break in minutes?',
    text_tr: 'Futbolda standart devre arası dinlenme süresi kaç dakikadır?',
    options: { A: '10', B: '15', C: '20', D: '12', E: '5' },
    options_tr: { A: '10', B: '15', C: '20', D: '12', E: '5' },
    answer: 'B',
    explanation: 'According to IFAB laws of the game, players are entitled to a halftime interval not exceeding 15 minutes.',
  },
  {
    id: 'sport_73',
    text: 'Which major league baseball (MLB) team features a famous logo with interlocking letters "N" and "Y"?',
    text_tr: 'Birbiriyle kenetlenmiş "N" ve "Y" harflerinden oluşan logosuyla ünlü beyzbol (MLB) takımı hangisidir?',
    options: { A: 'New York Mets', B: 'New York Yankees', C: 'Boston Red Sox', D: 'Los Angeles Dodgers', E: 'Chicago Cubs' },
    options_tr: { A: 'New York Mets', B: 'New York Yankees', C: 'Boston Red Sox', D: 'Los Angeles Dodgers', E: 'Chicago Cubs' },
    answer: 'B',
    explanation: 'The New York Yankees feature one of the most widely recognized sports logos in global fashion and culture.',
  },
  {
    id: 'sport_74',
    text: 'How many legal players from one team are on the ice during a standard professional ice hockey game (excluding penalties)?',
    text_tr: 'Cezalar hariç, standart bir profesyonel buz hokeyi maçında bir takım adına buzda aynı anda kaç oyuncu yer alır?',
    options: { A: '5', B: '6', C: '7', D: '11', E: '4' },
    options_tr: { A: '5', B: '6', C: '7', D: '11', E: '4' },
    answer: 'B',
    explanation: 'Teams typically skate with 6 players at a time: 3 forwards, 2 defensemen, and 1 goaltender.',
  },
  {
    id: 'sport_75',
    text: 'Which country hosted the historic 2008 Summer Olympic Games?',
    text_tr: 'Tarihe geçen 2008 Yaz Olimpiyat Oyunları\'na hangi ülke ev sahipliği yapmıştır?',
    options: { A: 'United States', B: 'United Kingdom', C: 'China', D: 'Greece', E: 'Japan' },
    options_tr: { A: 'Amerika Birleşik Devletleri', B: 'Birleşik Krallık', C: 'Çin', D: 'Yunanistan', E: 'Japonya' },
    answer: 'C',
    explanation: 'The 2008 Summer Olympics were held in Beijing, China, under the motto "One World, One Dream".',
  },
  {
    id: 'sport_76',
    text: 'What term is used in tennis when the score in a game is tied at 40-40?',
    text_tr: 'Tenis maçlarında bir oyun içindeki puan durumu 40-40 eşitliğe ulaştığında bu duruma ne ad verilir?',
    options: { A: 'Love', B: 'Deuce', C: 'Tie-break', D: 'Advantage', E: 'All' },
    options_tr: { A: 'Love', B: 'Deuce (Beraberlik)', C: 'Tie-break', D: 'Avantaj (Advantage)', E: 'All' },
    answer: 'B',
    explanation: 'When a game score reaches 40-40, it is called "Deuce", and a player must win two consecutive points from there to win the game.',
  },
  {
    id: 'sport_77',
    text: 'In professional golf, what color jacket is traditionally awarded to the winner of the Masters Tournament?',
    text_tr: 'Profesyonel golfte, Masters Turnuvası\'nı kazanan sporcuya geleneksel olarak hangi renk ceket giydirilir?',
    options: { A: 'Red', B: 'Blue', C: 'Green', D: 'White', E: 'Gold' },
    options_tr: { A: 'Kırmızı', B: 'Mavi', C: 'Yeşil', D: 'Beyaz', E: 'Altın' },
    answer: 'C',
    explanation: 'The iconic "Green Jacket" is the signature award presented to the winner of the Masters at Augusta National.',
  },
  {
    id: 'sport_78',
    text: 'Which country is historically credited with the invention of the modern sport of basketball in 1891?',
    text_tr: '1891 yılında modern basketbol sporunun icat edildiği ülke hangisidir?',
    options: { A: 'Canada', B: 'United States', C: 'England', D: 'France', E: 'Germany' },
    options_tr: { A: 'Kanada', B: 'Amerika Birleşik Devletleri', C: 'İngiltere', D: 'Fransa', E: 'Almanya' },
    answer: 'B',
    explanation: 'Dr. James Naismith, a Canadian physical education instructor, invented basketball in Springfield, Massachusetts, USA.',
  },
  {
    id: 'sport_79',
    text: 'What is the standard weight of a men\'s shot put ball in international athletic competitions?',
    text_tr: 'Uluslararası atletizm müsabakalarında standart erkekler gülle atma topunun ağırlığı yaklaşık kaç kilogramdır?',
    options: { A: '5 kg', B: '6 kg', C: '7.26 kg', D: '8 kg', E: '10 kg' },
    options_tr: { A: '5 kg', B: '6 kg', C: '7.26 kg', D: '8 kg', E: '10 kg' },
    answer: 'C',
    explanation: 'The standard men\'s shot put weight is exactly 7.26 kilograms (16 pounds).',
  },
  {
    id: 'sport_80',
    text: 'Which European football league is famously known as "Serie A"?',
    text_tr: '"Serie A" olarak bilinen en üst düzey futbol ligi hangi ülkeye aittir?',
    options: { A: 'Spain', B: 'France', C: 'Germany', D: 'Italy', E: 'Portugal' },
    options_tr: { A: 'İspanya', B: 'Fransa', C: 'Almanya', D: 'İtalya', E: 'Portekiz' },
    answer: 'D',
    explanation: 'Serie A is the top tier professional league competition for football clubs in Italy.',
  },
  {
    id: 'sport_81',
    text: 'In the sport of American football, how many points is a standard touchdown worth before any extra points?',
    text_tr: 'Amerikan futbolunda, ekstra sayı vuruşları yapılmadan önce standart bir touchdown (sayı) kaç puandır?',
    options: { A: '3', B: '6', C: '7', D: '4', E: '5' },
    options_tr: { A: '3', B: '6', C: '7', D: '4', E: '5' },
    answer: 'B',
    explanation: 'A touchdown is worth 6 points, after which the team can attempt a conversion for 1 or 2 extra points.',
  },
  {
    id: 'sport_82',
    text: 'Which track and field event requires athletes to jump over barriers and a water jump over a 3000-meter distance?',
    text_tr: 'Atletizmde, sporcuların 3000 metrelik bir mesafede engeller ve su dolu bir havuz üzerinden atlamasını gerektiren dal hangisidir?',
    options: { A: 'Hurdles', B: 'Steeplechase', C: 'Triple Jump', D: 'High Jump', E: 'Marathon' },
    options_tr: { A: 'Engelli Koşu', B: 'Hendekli Engelli Koşu (Steeplechase)', C: 'Üç Adım Atlama', D: 'Yüksek Atlama', E: 'Marathon' },
    answer: 'B',
    explanation: 'The 3000m steeplechase features 28 ordinary barriers and 7 water jumps.',
  },
  {
    id: 'sport_83',
    text: 'Who scored the infamous "Hand of God" goal in the 1986 World Cup?',
    text_tr: '1986 Dünya Kupası\'nda "Tanrı\'nın Eli" olarak bilinen meşhur golü atan futbolcu kimdir?',
    options: { A: 'Lionel Messi', B: 'Diego Maradona', C: 'Pelé', D: 'Gabriel Batistuta', E: 'Juan Román Riquelme' },
    options_tr: { A: 'Lionel Messi', B: 'Diego Maradona', C: 'Pelé', D: 'Gabriel Batistuta', E: 'Juan Román Riquelme' },
    answer: 'B',
    explanation: 'Diego Maradona scored both the controversial "Hand of God" and the spectacular "Goal of the Century" against England in 1986.',
  },
  {
    id: 'sport_84',
    text: 'In the sport of polo, what type of animal do the players ride during matches?',
    text_tr: 'Polo sporunda oyuncular maç sırasında hangi hayvana binerler?',
    options: { A: 'Camel', B: 'Donkey', C: 'Horse', D: 'Elephant', E: 'Mule' },
    options_tr: { A: 'Deve', B: 'Eşek', C: 'At', D: 'Fil', E: 'Katır' },
    answer: 'C',
    explanation: 'Polo is a team sport played on horseback where the objective is to score goals using a long mallet.',
  },
  {
    id: 'sport_85',
    text: 'What country is the origin of the traditional martial art of Taekwondo?',
    text_tr: 'Geleneksel bir dövüş sanatı olan Taekwondo hangi ülkenin kökenine dayanır?',
    options: { A: 'Japan', B: 'China', C: 'Korea', D: 'Vietnam', E: 'Thailand' },
    options_tr: { A: 'Japonya', B: 'Çin', C: 'Kore', D: 'Vietnam', E: 'Tayland' },
    answer: 'C',
    explanation: 'Taekwondo was developed during the 1940s and 1950s by Korean martial artists blending various ancestral styles.',
  },
  {
    id: 'sport_86',
    text: 'Which legendary driver is a 7-time Formula 1 World Champion, famously dominating the early 2000s with Scuderia Ferrari?',
    text_tr: '2000\'li yılların başında Scuderia Ferrari ile fırtınalar estiren, 7 kez Formula 1 Dünya Şampiyonu olmuş efsanevi Alman pilot kimdir?',
    options: { A: 'Ayrton Senna', B: 'Michael Schumacher', C: 'Sebastian Vettel', D: 'Niki Lauda', E: 'Alain Prost' },
    options_tr: { A: 'Ayrton Senna', B: 'Michael Schumacher', C: 'Sebastian Vettel', D: 'Niki Lauda', E: 'Alain Prost' },
    answer: 'B',
    explanation: 'Michael Schumacher won five consecutive titles with Ferrari from 2000 to 2004, totaling 7 in his career.',
  },
  {
    id: 'sport_87',
    text: 'How many total players from both teams combined are on the court during a standard basketball game?',
    text_tr: 'Standart bir basketbol maçında her iki takımdan toplam kaç oyuncu sahada aynı anda bulunur?',
    options: { A: '5', B: '8', C: '10', D: '12', E: '14' },
    options_tr: { A: '5', B: '8', C: '10', D: '12', E: '14' },
    answer: 'C',
    explanation: 'Each team fields 5 players, making a total of 10 active players on the court.',
  },
  {
    id: 'sport_88',
    text: 'Which grand slam tennis tournament is historically played on red clay courts?',
    text_tr: 'Kırmızı toprak (kil) kortta oynanmasıyla ünlü grand slam tenis turnuvası hangisidir?',
    options: { A: 'Wimbledon', B: 'US Open', C: 'French Open', D: 'Australian Open', E: 'Miami Open' },
    options_tr: { A: 'Wimbledon', B: 'Amerika Açık', C: 'Fransa Açık (Roland Garros)', D: 'Avustralya Açık', E: 'Miami Açık' },
    answer: 'C',
    explanation: 'The French Open (Roland Garros) is the premier clay court tennis championship in the world.',
  },
];

module.exports = { sports };
