'use strict';

const technology = [
  {
    id: 'tec_01',
    text: 'Who co-founded Apple Computer Company in 1976?',
    text_tr: '1976\'da Apple Computer Company\'yi kuranlar kimlerdir?',
    options: { A: 'Bill Gates & Paul Allen', B: 'Steve Jobs, Steve Wozniak & Ronald Wayne', C: 'Steve Jobs & Bill Gates', D: 'Steve Wozniak & Larry Page', E: 'Tim Cook & Steve Jobs' },
    options_tr: { A: 'Bill Gates ve Paul Allen', B: 'Steve Jobs, Steve Wozniak ve Ronald Wayne', C: 'Steve Jobs ve Bill Gates', D: 'Steve Wozniak ve Larry Page', E: 'Tim Cook ve Steve Jobs' },
    answer: 'B',
    explanation: 'Apple was co-founded by Steve Jobs, Steve Wozniak, and Ronald Wayne on April 1, 1976.',
  },
  {
    id: 'tec_02',
    text: 'What does "HTML" stand for?',
    text_tr: '"HTML" kısaltması neyi ifade eder?',
    options: { A: 'Hyper Transfer Markup Language', B: 'HyperText Markup Language', C: 'High-level Text Markup Language', D: 'Hyperlink Text Meta Language', E: 'HyperText Machine Language' },
    options_tr: { A: 'Hiper Transfer İşaretleme Dili', B: 'Hiper Metin İşaretleme Dili', C: 'Yüksek Seviyeli Metin İşaretleme Dili', D: 'Köprü Metni Meta Dili', E: 'Hiper Metin Makine Dili' },
    answer: 'B',
    explanation: 'HTML (HyperText Markup Language) is the standard markup language used to create web pages.',
  },
  {
    id: 'tec_03',
    text: 'In which year was the World Wide Web invented by Tim Berners-Lee?',
    text_tr: 'Tim Berners-Lee tarafından World Wide Web hangi yılda icat edildi?',
    options: { A: '1985', B: '1987', C: '1989', D: '1991', E: '1993' },
    options_tr: { A: '1985', B: '1987', C: '1989', D: '1991', E: '1993' },
    answer: 'C',
    explanation: 'Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN in Switzerland.',
  },
  {
    id: 'tec_04',
    text: 'What is the name of the open-source operating system kernel created by Linus Torvalds in 1991?',
    text_tr: '1991\'de Linus Torvalds tarafından oluşturulan açık kaynaklı işletim sistemi çekirdeğinin adı nedir?',
    options: { A: 'Unix', B: 'FreeBSD', C: 'GNU', D: 'Linux', E: 'Minix' },
    options_tr: { A: 'Unix', B: 'FreeBSD', C: 'GNU', D: 'Linux', E: 'Minix' },
    answer: 'D',
    explanation: 'Linus Torvalds created the Linux kernel in 1991, which now powers the majority of the world\'s servers, smartphones (Android), and supercomputers.',
  },
  {
    id: 'tec_05',
    text: 'Which company developed the Python programming language?',
    text_tr: 'Python programlama dilini kim/hangi kurum geliştirmiştir?',
    options: { A: 'Google', B: 'Microsoft', C: 'Guido van Rossum (personal project)', D: 'MIT', E: 'Sun Microsystems' },
    options_tr: { A: 'Google', B: 'Microsoft', C: 'Guido van Rossum (kişisel proje)', D: 'MIT', E: 'Sun Microsystems' },
    answer: 'C',
    explanation: 'Python was created by Guido van Rossum and first released in 1991. It was not created by a company but by an individual developer.',
  },
  {
    id: 'tec_06',
    text: 'What does "CPU" stand for?',
    text_tr: '"CPU" kısaltması neyi ifade eder?',
    options: { A: 'Central Processing Unit', B: 'Computer Processing Unit', C: 'Central Program Utility', D: 'Core Processing Unit', E: 'Central Peripheral Unit' },
    options_tr: { A: 'Merkezi İşlem Birimi', B: 'Bilgisayar İşlem Birimi', C: 'Merkezi Program Yardımcı Programı', D: 'Çekirdek İşlem Birimi', E: 'Merkezi Çevre Birimi' },
    answer: 'A',
    explanation: 'CPU stands for Central Processing Unit, the primary component that executes instructions in a computer.',
  },
  {
    id: 'tec_07',
    text: 'Which company created the Android operating system before Google acquired it in 2005?',
    text_tr: 'Google\'ın 2005\'te satın almasından önce Android işletim sistemini hangi şirket kurmuştu?',
    options: { A: 'Android Inc.', B: 'Symbian Ltd.', C: 'Palm Inc.', D: 'BlackBerry Ltd.', E: 'Nokia' },
    options_tr: { A: 'Android Inc.', B: 'Symbian Ltd.', C: 'Palm Inc.', D: 'BlackBerry Ltd.', E: 'Nokia' },
    answer: 'A',
    explanation: 'Android Inc. was founded by Andy Rubin and others in 2003, and Google acquired it in 2005.',
  },
  {
    id: 'tec_08',
    text: 'What does "URL" stand for?',
    text_tr: '"URL" kısaltması neyi ifade eder?',
    options: { A: 'Universal Resource Locator', B: 'Uniform Resource Locator', C: 'Uniform Reference Link', D: 'Universal Reference Locator', E: 'United Resource Link' },
    options_tr: { A: 'Universal Resource Locator', B: 'Uniform Resource Locator', C: 'Uniform Reference Link', D: 'Universal Reference Locator', E: 'United Resource Link' },
    answer: 'B',
    explanation: 'URL stands for Uniform Resource Locator, the address used to access resources on the internet.',
  },
  {
    id: 'tec_09',
    text: 'Which programming language, created by James Gosling at Sun Microsystems, was released in 1995 with the slogan "write once, run anywhere"?',
    text_tr: 'Sun Microsystems\'ta James Gosling tarafından yaratılan ve 1995\'te "bir kere yaz, her yerde çalıştır" sloganıyla piyasaya sürülen programlama dili hangisidir?',
    options: { A: 'C++', B: 'Java', C: 'Python', D: 'JavaScript', E: 'Ruby' },
    options_tr: { A: 'C++', B: 'Java', C: 'Python', D: 'JavaScript', E: 'Ruby' },
    answer: 'B',
    explanation: 'Java was designed for platform independence, running on any device with a Java Virtual Machine.',
  },
  {
    id: 'tec_10',
    text: 'What is the name of the first practical mechanical calculator, invented by Blaise Pascal in 1642?',
    text_tr: 'Blaise Pascal tarafından 1642\'de icat edilen ilk pratik mekanik hesap makinesinin adı nedir?',
    options: { A: 'The Analytical Engine', B: 'The Pascaline', C: 'The Difference Engine', D: 'The Abacus Machine', E: 'The Leibniz Wheel' },
    options_tr: { A: 'The Analytical Engine', B: 'Pascaline', C: 'The Difference Engine', D: 'The Abacus Machine', E: 'Leibniz Çarkı' },
    answer: 'B',
    explanation: 'The Pascaline was one of the earliest mechanical calculators, designed to help Pascal\'s father with tax calculations.',
  },
  {
    id: 'tec_11',
    text: 'Which company developed the first commercially successful graphical web browser, "Mosaic," in 1993?',
    text_tr: '1993\'te ilk ticari açıdan başarılı grafiksel web tarayıcısı olan "Mosaic"i hangi kurum geliştirdi?',
    options: { A: 'Microsoft', B: 'NCSA (National Center for Supercomputing Applications)', C: 'Netscape', D: 'Bell Labs', E: 'IBM' },
    options_tr: { A: 'Microsoft', B: 'NCSA (Ulusal Süper Bilgisayar Uygulamaları Merkezi)', C: 'Netscape', D: 'Bell Labs', E: 'IBM' },
    answer: 'B',
    explanation: 'Mosaic was developed at NCSA at the University of Illinois; its team later founded Netscape.',
  },
  {
    id: 'tec_12',
    text: 'What is the name of Elon Musk\'s company focused on brain-computer interfaces?',
    text_tr: 'Elon Musk\'ın beyin-bilgisayar arayüzlerine odaklanan şirketinin adı nedir?',
    options: { A: 'OpenAI', B: 'Neuralink', C: 'SpaceX', D: 'The Boring Company', E: 'Synchron' },
    options_tr: { A: 'OpenAI', B: 'Neuralink', C: 'SpaceX', D: 'The Boring Company', E: 'Synchron' },
    answer: 'B',
    explanation: 'Neuralink, founded in 2016, develops implantable brain-computer interface devices.',
  },
  {
    id: 'tec_13',
    text: 'What does "RAM" stand for?',
    text_tr: '"RAM" kısaltması neyi ifade eder?',
    options: { A: 'Random Access Memory', B: 'Read Access Memory', C: 'Rapid Access Module', D: 'Random Allocation Memory', E: 'Read and Modify' },
    options_tr: { A: 'Rastgele Erişimli Bellek', B: 'Okuma Erişimli Bellek', C: 'Hızlı Erişim Modülü', D: 'Rastgele Tahsis Belleği', E: 'Oku ve Değiştir' },
    answer: 'A',
    explanation: 'RAM (Random Access Memory) is volatile memory used by computers to store data being actively used.',
  },
  {
    id: 'tec_14',
    text: 'Which social media platform was originally called "TheFacebook" when it launched in 2004?',
    text_tr: '2004\'te piyasaya çıktığında adı "TheFacebook" olan sosyal medya platformu hangisidir?',
    options: { A: 'Instagram', B: 'MySpace', C: 'Facebook', D: 'Twitter', E: 'Friendster' },
    options_tr: { A: 'Instagram', B: 'MySpace', C: 'Facebook', D: 'Twitter', E: 'Friendster' },
    answer: 'C',
    explanation: 'Mark Zuckerberg launched "TheFacebook" at Harvard in 2004; it dropped the "The" in 2005.',
  },
  {
    id: 'tec_15',
    text: 'What is the name of the protocol used to securely transfer data over the web, indicated by a padlock icon in browsers?',
    text_tr: 'Tarayıcılarda kilit simgesiyle gösterilen, web üzerinden veriyi güvenli şekilde aktaran protokolün adı nedir?',
    options: { A: 'FTP', B: 'HTTP', C: 'HTTPS', D: 'SMTP', E: 'SSH' },
    options_tr: { A: 'FTP', B: 'HTTP', C: 'HTTPS', D: 'SMTP', E: 'SSH' },
    answer: 'C',
    explanation: 'HTTPS (HTTP Secure) encrypts data between the browser and server using TLS/SSL.',
  },
  {
    id: 'tec_16',
    text: 'Which company created the first widely used search engine algorithm called PageRank?',
    text_tr: 'PageRank adı verilen ilk yaygın kullanılan arama motoru algoritmasını hangi şirket yarattı?',
    options: { A: 'Yahoo', B: 'Google', C: 'AltaVista', D: 'Bing', E: 'Ask Jeeves' },
    options_tr: { A: 'Yahoo', B: 'Google', C: 'AltaVista', D: 'Bing', E: 'Ask Jeeves' },
    answer: 'B',
    explanation: 'PageRank was developed by Larry Page and Sergey Brin at Stanford and became the basis of Google Search.',
  },
  {
    id: 'tec_17',
    text: 'What does "GPU" stand for?',
    text_tr: '"GPU" kısaltması neyi ifade eder?',
    options: { A: 'General Processing Unit', B: 'Graphics Processing Unit', C: 'Global Processing Unit', D: 'Graphic Print Unit', E: 'Gaming Processing Unit' },
    options_tr: { A: 'Genel İşlem Birimi', B: 'Grafik İşlem Birimi', C: 'Küresel İşlem Birimi', D: 'Grafik Yazdırma Birimi', E: 'Oyun İşlem Birimi' },
    answer: 'B',
    explanation: 'GPU (Graphics Processing Unit) is specialized hardware for rendering images and, more recently, parallel computation like AI training.',
  },
  {
    id: 'tec_18',
    text: 'Which company manufactures the "Ryzen" line of CPUs?',
    text_tr: '"Ryzen" işlemci serisini hangi şirket üretir?',
    options: { A: 'Intel', B: 'NVIDIA', C: 'AMD', D: 'Qualcomm', E: 'ARM' },
    options_tr: { A: 'Intel', B: 'NVIDIA', C: 'AMD', D: 'Qualcomm', E: 'ARM' },
    answer: 'C',
    explanation: 'AMD introduced the Ryzen processor line in 2017 to compete with Intel\'s Core lineup.',
  },
  {
    id: 'tec_19',
    text: 'What was the name of the first commercially available smartphone, released by IBM in 1994?',
    text_tr: 'IBM tarafından 1994\'te piyasaya sürülen ilk ticari akıllı telefonun adı nedir?',
    options: { A: 'IBM Simon', B: 'Nokia Communicator', C: 'BlackBerry 850', D: 'Palm Pilot', E: 'Motorola StarTAC' },
    options_tr: { A: 'IBM Simon', B: 'Nokia Communicator', C: 'BlackBerry 850', D: 'Palm Pilot', E: 'Motorola StarTAC' },
    answer: 'A',
    explanation: 'The IBM Simon Personal Communicator, released in 1994, combined phone, fax, and PDA features with a touchscreen.',
  },
  {
    id: 'tec_20',
    text: 'What is the name of Amazon\'s cloud computing platform?',
    text_tr: 'Amazon\'ın bulut bilişim platformunun adı nedir?',
    options: { A: 'Amazon Cloud', B: 'AWS (Amazon Web Services)', C: 'Amazon Compute', D: 'EC2 Cloud', E: 'Amazon Nimbus' },
    options_tr: { A: 'Amazon Cloud', B: 'AWS (Amazon Web Services)', C: 'Amazon Compute', D: 'EC2 Cloud', E: 'Amazon Nimbus' },
    answer: 'B',
    explanation: 'AWS, launched in 2006, is the largest cloud computing platform in the world.',
  },
  {
    id: 'tec_21',
    text: 'Which encryption algorithm, named after its three inventors, is widely used for secure data transmission?',
    text_tr: 'Üç mucidinin isimlerinden oluşan, güvenli veri iletiminde yaygın olarak kullanılan şifreleme algoritması hangisidir?',
    options: { A: 'AES', B: 'DES', C: 'RSA', D: 'SHA', E: 'MD5' },
    options_tr: { A: 'AES', B: 'DES', C: 'RSA', D: 'SHA', E: 'MD5' },
    answer: 'C',
    explanation: 'RSA is named after Rivest, Shamir, and Adleman, who described the algorithm in 1977.',
  },
  {
    id: 'tec_22',
    text: 'What does "IoT" stand for?',
    text_tr: '"IoT" kısaltması neyi ifade eder?',
    options: { A: 'Internet of Technology', B: 'Internet of Things', C: 'Integration of Things', D: 'Interface of Technology', E: 'Internal Object Transfer' },
    options_tr: { A: 'Teknoloji İnterneti', B: 'Nesnelerin İnterneti', C: 'Nesnelerin Entegrasyonu', D: 'Teknoloji Arayüzü', E: 'Dahili Nesne Transferi' },
    answer: 'B',
    explanation: 'IoT (Internet of Things) refers to the network of physical devices connected to and exchanging data over the internet.',
  },
  {
    id: 'tec_23',
    text: 'Which company developed the ChatGPT chatbot?',
    text_tr: 'ChatGPT sohbet robotunu hangi şirket geliştirdi?',
    options: { A: 'Google DeepMind', B: 'Meta AI', C: 'OpenAI', D: 'Anthropic', E: 'Microsoft Research' },
    options_tr: { A: 'Google DeepMind', B: 'Meta AI', C: 'OpenAI', D: 'Anthropic', E: 'Microsoft Research' },
    answer: 'C',
    explanation: 'ChatGPT was developed by OpenAI and released to the public in November 2022.',
  },
  {
    id: 'tec_24',
    text: 'What is the name of the first electronic general-purpose digital computer, completed in 1945?',
    text_tr: '1945\'te tamamlanan ilk elektronik genel amaçlı dijital bilgisayarın adı nedir?',
    options: { A: 'ENIAC', B: 'UNIVAC', C: 'Colossus', D: 'Z3', E: 'EDVAC' },
    options_tr: { A: 'ENIAC', B: 'UNIVAC', C: 'Colossus', D: 'Z3', E: 'EDVAC' },
    answer: 'A',
    explanation: 'ENIAC (Electronic Numerical Integrator and Computer) was built at the University of Pennsylvania.',
  },
  {
    id: 'tec_25',
    text: 'What does "SSD" stand for in computer storage?',
    text_tr: 'Bilgisayar depolamasında "SSD" kısaltması neyi ifade eder?',
    options: { A: 'Solid State Drive', B: 'Secure Storage Device', C: 'Static State Disk', D: 'Serial Storage Drive', E: 'Solid Storage Disk' },
    options_tr: { A: 'Katı Hal Sürücü', B: 'Güvenli Depolama Aygıtı', C: 'Statik Durum Diski', D: 'Seri Depolama Sürücüsü', E: 'Katı Depolama Diski' },
    answer: 'A',
    explanation: 'SSDs use flash memory instead of spinning disks, offering faster read/write speeds than traditional hard drives (HDDs).',
  },
  {
    id: 'tec_26',
    text: 'Which company created the Kubernetes container orchestration system, later donating it to open source?',
    text_tr: 'Konteyner orkestrasyonu sistemi Kubernetes\'i hangi şirket yaratıp daha sonra açık kaynağa bağışladı?',
    options: { A: 'Amazon', B: 'Google', C: 'Microsoft', D: 'Red Hat', E: 'Docker Inc.' },
    options_tr: { A: 'Amazon', B: 'Google', C: 'Microsoft', D: 'Red Hat', E: 'Docker Inc.' },
    answer: 'B',
    explanation: 'Kubernetes was originally designed by Google, based on their internal Borg system, and open-sourced in 2014.',
  },
  {
    id: 'tec_27',
    text: 'What is the name of the first widely adopted version control system created by Linus Torvalds in 2005?',
    text_tr: 'Linus Torvalds tarafından 2005\'te yaratılan ve yaygın olarak benimsenen ilk sürüm kontrol sisteminin adı nedir?',
    options: { A: 'Subversion', B: 'Mercurial', C: 'Git', D: 'CVS', E: 'Perforce' },
    options_tr: { A: 'Subversion', B: 'Mercurial', C: 'Git', D: 'CVS', E: 'Perforce' },
    answer: 'C',
    explanation: 'Git was created by Linus Torvalds to manage development of the Linux kernel after a licensing dispute with the prior tool, BitKeeper.',
  },
  {
    id: 'tec_28',
    text: 'What does "VPN" stand for?',
    text_tr: '"VPN" kısaltması neyi ifade eder?',
    options: { A: 'Virtual Private Network', B: 'Verified Public Network', C: 'Virtual Public Node', D: 'Variable Protocol Network', E: 'Virtual Protected Node' },
    options_tr: { A: 'Sanal Özel Ağ', B: 'Doğrulanmış Genel Ağ', C: 'Sanal Genel Düğüm', D: 'Değişken Protokol Ağı', E: 'Sanal Korumalı Düğüm' },
    answer: 'A',
    explanation: 'A VPN (Virtual Private Network) creates an encrypted connection over a less secure network, such as the public internet.',
  },
  {
    id: 'tec_29',
    text: 'Which company designed the first computer mouse prototype, demonstrated by Douglas Engelbart in 1968?',
    text_tr: 'Douglas Engelbart tarafından 1968\'de tanıtılan ilk bilgisayar faresi prototipini hangi kurum tasarladı?',
    options: { A: 'IBM', B: 'Xerox PARC', C: 'Stanford Research Institute (SRI)', D: 'Bell Labs', E: 'MIT' },
    options_tr: { A: 'IBM', B: 'Xerox PARC', C: 'Stanford Araştırma Enstitüsü (SRI)', D: 'Bell Labs', E: 'MIT' },
    answer: 'C',
    explanation: 'Engelbart developed the first mouse prototype at the Stanford Research Institute, famously demonstrated in "The Mother of All Demos."',
  },
  {
    id: 'tec_30',
    text: 'What is the name of the programming paradigm that treats computation as the evaluation of mathematical functions, avoiding changing state and mutable data?',
    text_tr: 'Hesaplamayı matematiksel fonksiyonların değerlendirilmesi olarak ele alan, durum değişikliğinden ve değişebilir veriden kaçınan programlama paradigmasının adı nedir?',
    options: { A: 'Object-oriented programming', B: 'Procedural programming', C: 'Functional programming', D: 'Logic programming', E: 'Imperative programming' },
    options_tr: { A: 'Nesne yönelimli programlama', B: 'Yordamsal programlama', C: 'Fonksiyonel programlama', D: 'Mantıksal programlama', E: 'Buyurgan programlama' },
    answer: 'C',
    explanation: 'Functional programming languages include Haskell, Lisp, and Erlang; JavaScript and Python support functional styles too.',
  },
  {
    id: 'tec_31',
    text: 'Which chip architecture, dominant in smartphones, is licensed rather than manufactured directly by the company that designs it?',
    text_tr: 'Akıllı telefonlarda baskın olan, tasarımını yapan şirket tarafından doğrudan üretilmek yerine lisanslanan çip mimarisi hangisidir?',
    options: { A: 'x86', B: 'ARM', C: 'MIPS', D: 'RISC-V', E: 'PowerPC' },
    options_tr: { A: 'x86', B: 'ARM', C: 'MIPS', D: 'RISC-V', E: 'PowerPC' },
    answer: 'B',
    explanation: 'ARM Holdings designs chip architectures and licenses them to manufacturers like Apple, Qualcomm, and Samsung.',
  },
  {
    id: 'tec_32',
    text: 'What is the term for a piece of malicious software that disguises itself as legitimate software to trick users into installing it?',
    text_tr: 'Kullanıcıları kandırıp yüklemesi için kendisini meşru yazılım gibi gösteren kötü amaçlı yazılım türüne ne denir?',
    options: { A: 'Worm', B: 'Ransomware', C: 'Trojan horse', D: 'Rootkit', E: 'Adware' },
    options_tr: { A: 'Solucan (Worm)', B: 'Fidye yazılımı', C: 'Truva atı', D: 'Rootkit', E: 'Reklam yazılımı' },
    answer: 'C',
    explanation: 'Named after the Greek myth, a Trojan horse appears harmless but carries out malicious actions once installed.',
  },
  {
    id: 'tec_33',
    text: 'Which company introduced the first iPhone in 2007?',
    text_tr: 'İlk iPhone\'u 2007\'de hangi şirket tanıttı?',
    options: { A: 'Samsung', B: 'Apple', C: 'Nokia', D: 'HTC', E: 'Google' },
    options_tr: { A: 'Samsung', B: 'Apple', C: 'Nokia', D: 'HTC', E: 'Google' },
    answer: 'B',
    explanation: 'Steve Jobs unveiled the original iPhone on January 9, 2007, combining a phone, iPod, and internet device.',
  },
  {
    id: 'tec_34',
    text: 'What does "API" stand for?',
    text_tr: '"API" kısaltması neyi ifade eder?',
    options: { A: 'Application Programming Interface', B: 'Automated Program Integration', C: 'Application Process Interaction', D: 'Advanced Programming Instruction', E: 'Application Protocol Interface' },
    options_tr: { A: 'Uygulama Programlama Arayüzü', B: 'Otomatik Program Entegrasyonu', C: 'Uygulama Süreç Etkileşimi', D: 'Gelişmiş Programlama Talimatı', E: 'Uygulama Protokol Arayüzü' },
    answer: 'A',
    explanation: 'An API (Application Programming Interface) defines how software components communicate with each other.',
  },
  {
    id: 'tec_35',
    text: 'Which quantum computing company built "Sycamore," the processor used in a 2019 claim of "quantum supremacy"?',
    text_tr: '2019\'da "kuantum üstünlüğü" iddiası için kullanılan "Sycamore" işlemcisini hangi kuantum bilgi işlem şirketi üretti?',
    options: { A: 'IBM', B: 'D-Wave', C: 'Google', D: 'Intel', E: 'Rigetti' },
    options_tr: { A: 'IBM', B: 'D-Wave', C: 'Google', D: 'Intel', E: 'Rigetti' },
    answer: 'C',
    explanation: 'Google\'s Sycamore processor reportedly performed a calculation in 200 seconds that would take a supercomputer thousands of years.',
  },
  {
    id: 'tec_36',
    text: 'What is the name for the practice of tricking people into revealing sensitive information via deceptive emails or messages?',
    text_tr: 'İnsanları aldatıcı e-posta veya mesajlar yoluyla hassas bilgileri ifşa etmeleri için kandırma pratiğine ne ad verilir?',
    options: { A: 'Spoofing', B: 'Phishing', C: 'Pharming', D: 'Spamming', E: 'Sniffing' },
    options_tr: { A: 'Spoofing', B: 'Oltalama (Phishing)', C: 'Pharming', D: 'Spam', E: 'Sniffing' },
    answer: 'B',
    explanation: 'Phishing attacks impersonate trusted entities to steal credentials, financial information, or install malware.',
  },
  {
    id: 'tec_37',
    text: 'Which company developed the first widely used relational database management system, Oracle Database?',
    text_tr: 'İlk yaygın kullanılan ilişkisel veritabanı yönetim sistemi olan Oracle Database\'i hangi şirket geliştirdi?',
    options: { A: 'IBM', B: 'Oracle Corporation', C: 'Microsoft', D: 'Sybase', E: 'Informix' },
    options_tr: { A: 'IBM', B: 'Oracle Corporation', C: 'Microsoft', D: 'Sybase', E: 'Informix' },
    answer: 'B',
    explanation: 'Oracle Corporation, founded by Larry Ellison, released the first commercial relational database in 1979.',
  },
  {
    id: 'tec_38',
    text: 'What does "DNS" stand for, the system that translates domain names into IP addresses?',
    text_tr: 'Alan adlarını IP adreslerine çeviren sistemin adı olan "DNS" kısaltması neyi ifade eder?',
    options: { A: 'Domain Name System', B: 'Digital Network Service', C: 'Domain Network Server', D: 'Data Naming System', E: 'Domain Node Service' },
    options_tr: { A: 'Alan Adı Sistemi', B: 'Dijital Ağ Servisi', C: 'Alan Adı Ağ Sunucusu', D: 'Veri Adlandırma Sistemi', E: 'Alan Adı Düğüm Servisi' },
    answer: 'A',
    explanation: 'DNS (Domain Name System) acts like the internet\'s phone book, mapping human-readable names to IP addresses.',
  },
  {
    id: 'tec_39',
    text: 'Which company created the JavaScript programming language in 1995, originally named "Mocha"?',
    text_tr: '1995\'te başlangıçta "Mocha" adıyla JavaScript programlama dilini hangi şirket yarattı?',
    options: { A: 'Sun Microsystems', B: 'Microsoft', C: 'Netscape', D: 'IBM', E: 'Adobe' },
    options_tr: { A: 'Sun Microsystems', B: 'Microsoft', C: 'Netscape', D: 'IBM', E: 'Adobe' },
    answer: 'C',
    explanation: 'Brendan Eich created JavaScript at Netscape in just 10 days in 1995.',
  },
  {
    id: 'tec_40',
    text: 'What is the name for a network of infected computers controlled remotely, often used for DDoS attacks?',
    text_tr: 'Genellikle DDoS saldırılarında kullanılan, uzaktan kontrol edilen enfekte bilgisayarlar ağına ne ad verilir?',
    options: { A: 'Honeypot', B: 'Botnet', C: 'Firewall cluster', D: 'Sandbox', E: 'Mesh network' },
    options_tr: { A: 'Bal küpü (Honeypot)', B: 'Botnet', C: 'Güvenlik duvarı kümesi', D: 'Sandbox', E: 'Örgü ağ' },
    answer: 'B',
    explanation: 'A botnet is a collection of internet-connected devices infected with malware and controlled as a group, often without owners\' knowledge.',
  },
  {
    id: 'tec_41',
    text: 'Which company manufactures the "Snapdragon" line of mobile processors?',
    text_tr: '"Snapdragon" mobil işlemci serisini hangi şirket üretir?',
    options: { A: 'Samsung', B: 'MediaTek', C: 'Qualcomm', D: 'Apple', E: 'Huawei' },
    options_tr: { A: 'Samsung', B: 'MediaTek', C: 'Qualcomm', D: 'Apple', E: 'Huawei' },
    answer: 'C',
    explanation: 'Qualcomm\'s Snapdragon chips power a large share of Android smartphones worldwide.',
  },
  {
    id: 'tec_42',
    text: 'What does "USB" stand for?',
    text_tr: '"USB" kısaltması neyi ifade eder?',
    options: { A: 'Universal Serial Bus', B: 'Unified System Board', C: 'Universal System Bridge', D: 'Unified Serial Board', E: 'Universal Storage Bus' },
    options_tr: { A: 'Evrensel Seri Veri Yolu', B: 'Birleşik Sistem Kartı', C: 'Evrensel Sistem Köprüsü', D: 'Birleşik Seri Kart', E: 'Evrensel Depolama Yolu' },
    answer: 'A',
    explanation: 'USB (Universal Serial Bus) standardized connections between computers and peripheral devices starting in 1996.',
  },
  {
    id: 'tec_43',
    text: 'Which programming language, developed at Bell Labs in the early 1970s, heavily influenced C++, Java, and C#?',
    text_tr: '1970\'lerin başında Bell Labs\'te geliştirilen ve C++, Java ile C#\'ı büyük ölçüde etkileyen programlama dili hangisidir?',
    options: { A: 'Fortran', B: 'COBOL', C: 'C', D: 'Pascal', E: 'BASIC' },
    options_tr: { A: 'Fortran', B: 'COBOL', C: 'C', D: 'Pascal', E: 'BASIC' },
    answer: 'C',
    explanation: 'Dennis Ritchie developed C at Bell Labs, and it became one of the most influential programming languages ever created.',
  },
  {
    id: 'tec_44',
    text: 'What is the name of Microsoft\'s AI-powered assistant integrated across its products, launched in 2023?',
    text_tr: '2023\'te piyasaya sürülen ve Microsoft ürünlerine entegre edilen yapay zeka destekli asistanının adı nedir?',
    options: { A: 'Cortana', B: 'Copilot', C: 'Bing Chat Assistant', D: 'Azure Assistant', E: 'Clippy AI' },
    options_tr: { A: 'Cortana', B: 'Copilot', C: 'Bing Chat Assistant', D: 'Azure Assistant', E: 'Clippy AI' },
    answer: 'B',
    explanation: 'Microsoft Copilot, built on OpenAI\'s models, was integrated into Windows, Office, and other products.',
  },
  {
    id: 'tec_45',
    text: 'Which company created the first commercially available 3D printer in 1987?',
    text_tr: '1987\'de ilk ticari olarak satılan 3D yazıcıyı hangi şirket yarattı?',
    options: { A: 'Stratasys', B: '3D Systems', C: 'MakerBot', D: 'HP', E: 'Formlabs' },
    options_tr: { A: 'Stratasys', B: '3D Systems', C: 'MakerBot', D: 'HP', E: 'Formlabs' },
    answer: 'B',
    explanation: '3D Systems, founded by Chuck Hull (inventor of stereolithography), released the SLA-1 in 1987.',
  },
  {
    id: 'tec_46',
    text: 'What does "LAN" stand for?',
    text_tr: '"LAN" kısaltması neyi ifade eder?',
    options: { A: 'Large Area Network', B: 'Local Area Network', C: 'Linked Access Node', D: 'Long Access Network', E: 'Layered Application Network' },
    options_tr: { A: 'Geniş Alan Ağı', B: 'Yerel Alan Ağı', C: 'Bağlantılı Erişim Düğümü', D: 'Uzun Erişim Ağı', E: 'Katmanlı Uygulama Ağı' },
    answer: 'B',
    explanation: 'A LAN (Local Area Network) connects computers within a limited area, such as a home, school, or office building.',
  },
  {
    id: 'tec_47',
    text: 'Which company acquired GitHub in 2018?',
    text_tr: 'GitHub\'ı 2018\'de hangi şirket satın aldı?',
    options: { A: 'Google', B: 'Microsoft', C: 'Amazon', D: 'Atlassian', E: 'IBM' },
    options_tr: { A: 'Google', B: 'Microsoft', C: 'Amazon', D: 'Atlassian', E: 'IBM' },
    answer: 'B',
    explanation: 'Microsoft acquired GitHub for approximately $7.5 billion in stock in 2018.',
  },
  {
    id: 'tec_48',
    text: 'What is the term for storing frequently accessed data in a fast, temporary storage layer to speed up future requests?',
    text_tr: 'Sık erişilen verileri gelecekteki istekleri hızlandırmak için hızlı, geçici bir depolama katmanında saklamaya ne ad verilir?',
    options: { A: 'Indexing', B: 'Caching', C: 'Sharding', D: 'Replication', E: 'Partitioning' },
    options_tr: { A: 'İndeksleme', B: 'Önbellekleme (Caching)', C: 'Parçalama (Sharding)', D: 'Çoğaltma (Replication)', E: 'Bölümleme (Partitioning)' },
    answer: 'B',
    explanation: 'Caching stores copies of data (e.g., in RAM or a CDN) to reduce latency and load on the original data source.',
  },
  {
    id: 'tec_49',
    text: 'Which tech company\'s founders, Larry Page and Sergey Brin, met as PhD students at Stanford University?',
    text_tr: 'Kurucuları Larry Page ve Sergey Brin\'in Stanford Üniversitesi\'nde doktora öğrencisiyken tanıştığı teknoloji şirketi hangisidir?',
    options: { A: 'Yahoo', B: 'Google', C: 'PayPal', D: 'eBay', E: 'Netscape' },
    options_tr: { A: 'Yahoo', B: 'Google', C: 'PayPal', D: 'eBay', E: 'Netscape' },
    answer: 'B',
    explanation: 'Page and Brin met at Stanford in 1995 and founded Google in a garage in 1998.',
  },
  {
    id: 'tec_50',
    text: 'What is the name of the wireless networking technology standard commonly known as "Wi-Fi," standardized under which IEEE family?',
    text_tr: '"Wi-Fi" olarak bilinen kablosuz ağ teknolojisi standardı hangi IEEE aile numarası altında standartlaştırılmıştır?',
    options: { A: 'IEEE 802.3', B: 'IEEE 802.11', C: 'IEEE 802.15', D: 'IEEE 802.16', E: 'IEEE 1394' },
    options_tr: { A: 'IEEE 802.3', B: 'IEEE 802.11', C: 'IEEE 802.15', D: 'IEEE 802.16', E: 'IEEE 1394' },
    answer: 'B',
    explanation: 'The IEEE 802.11 family of standards defines wireless local area networking, commercially branded as Wi-Fi.',
  },
  {
    id: 'tec_51',
    text: 'Which company developed the Tesla Autopilot driver-assistance system?',
    text_tr: 'Tesla Autopilot sürücü destek sistemini hangi şirket geliştirdi?',
    options: { A: 'Waymo', B: 'Tesla', C: 'NVIDIA', D: 'Mobileye', E: 'Cruise' },
    options_tr: { A: 'Waymo', B: 'Tesla', C: 'NVIDIA', D: 'Mobileye', E: 'Cruise' },
    answer: 'B',
    explanation: 'Tesla developed Autopilot in-house, though it initially relied on Mobileye hardware before switching to its own chips.',
  },
  {
    id: 'tec_52',
    text: 'What does "IP" stand for in "IP address"?',
    text_tr: '"IP adresi" ifadesindeki "IP" kısaltması neyi ifade eder?',
    options: { A: 'Internal Protocol', B: 'Internet Protocol', C: 'Interface Path', D: 'Information Packet', E: 'Integrated Path' },
    options_tr: { A: 'Dahili Protokol', B: 'İnternet Protokolü', C: 'Arayüz Yolu', D: 'Bilgi Paketi', E: 'Entegre Yol' },
    answer: 'B',
    explanation: 'An IP (Internet Protocol) address uniquely identifies a device on a network.',
  },
  {
    id: 'tec_53',
    text: 'Which company created the first widely used spreadsheet software, VisiCalc, in 1979?',
    text_tr: '1979\'da ilk yaygın kullanılan hesap tablosu yazılımı olan VisiCalc\'ı hangi şirket yarattı?',
    options: { A: 'Microsoft', B: 'Lotus Development', C: 'Software Arts', D: 'IBM', E: 'Apple' },
    options_tr: { A: 'Microsoft', B: 'Lotus Development', C: 'Software Arts', D: 'IBM', E: 'Apple' },
    answer: 'C',
    explanation: 'VisiCalc was created by Dan Bricklin and Bob Frankston at Software Arts, and is considered the first "killer app" for personal computers.',
  },
  {
    id: 'tec_54',
    text: 'What is the name for a computing model where data processing happens close to the data source rather than a centralized data center?',
    text_tr: 'Veri işlemenin merkezi bir veri merkezi yerine veri kaynağına yakın bir yerde gerçekleştiği bilgi işlem modeline ne ad verilir?',
    options: { A: 'Cloud computing', B: 'Grid computing', C: 'Edge computing', D: 'Quantum computing', E: 'Distributed computing' },
    options_tr: { A: 'Bulut bilişim', B: 'Grid bilişim', C: 'Uç (Edge) bilişim', D: 'Kuantum bilişim', E: 'Dağıtık bilişim' },
    answer: 'C',
    explanation: 'Edge computing reduces latency by processing data near where it is generated, such as on IoT devices.',
  },
  {
    id: 'tec_55',
    text: 'Which company created the Instagram app before it was acquired by Facebook in 2012?',
    text_tr: '2012\'de Facebook tarafından satın alınmadan önce Instagram uygulamasını hangi şirket/ekip yarattı?',
    options: { A: 'Burbn, Inc.', B: 'Snap Inc.', C: 'Path Inc.', D: 'Flickr', E: 'Vine Labs' },
    options_tr: { A: 'Burbn, Inc.', B: 'Snap Inc.', C: 'Path Inc.', D: 'Flickr', E: 'Vine Labs' },
    answer: 'A',
    explanation: 'Instagram was created by Kevin Systrom and Mike Krieger under the company Burbn, Inc., launching in 2010.',
  },
  {
    id: 'tec_56',
    text: 'What is the name of the process where a website checks whether a user is a human or a bot, often using distorted text or image selection?',
    text_tr: 'Bir web sitesinin kullanıcının insan mı yoksa bot mu olduğunu genellikle bozuk metin veya görsel seçimi kullanarak kontrol ettiği sürece ne ad verilir?',
    options: { A: 'Two-factor authentication', B: 'CAPTCHA', C: 'OAuth', D: 'Firewall check', E: 'Cookie consent' },
    options_tr: { A: 'İki faktörlü kimlik doğrulama', B: 'CAPTCHA', C: 'OAuth', D: 'Güvenlik duvarı kontrolü', E: 'Çerez onayı' },
    answer: 'B',
    explanation: 'CAPTCHA stands for "Completely Automated Public Turing test to tell Computers and Humans Apart."',
  },
  {
    id: 'tec_57',
    text: 'Which company developed the Rust programming language, originally as a personal project by Graydon Hoare?',
    text_tr: 'Başlangıçta Graydon Hoare\'ın kişisel bir projesi olarak başlayan Rust programlama dilini hangi şirket destekleyip geliştirdi?',
    options: { A: 'Google', B: 'Mozilla', C: 'Microsoft', D: 'Facebook', E: 'Apple' },
    options_tr: { A: 'Google', B: 'Mozilla', C: 'Microsoft', D: 'Facebook', E: 'Apple' },
    answer: 'B',
    explanation: 'Mozilla sponsored Rust\'s development starting in 2009, and it is now widely used for systems programming.',
  },
  {
    id: 'tec_58',
    text: 'What does "PDF" stand for?',
    text_tr: '"PDF" kısaltması neyi ifade eder?',
    options: { A: 'Portable Document Format', B: 'Printed Document File', C: 'Personal Data File', D: 'Public Document Format', E: 'Print Data Format' },
    options_tr: { A: 'Taşınabilir Belge Biçimi', B: 'Basılmış Belge Dosyası', C: 'Kişisel Veri Dosyası', D: 'Genel Belge Biçimi', E: 'Yazdırma Veri Biçimi' },
    answer: 'A',
    explanation: 'PDF (Portable Document Format) was created by Adobe in 1993 to present documents consistently across platforms.',
  },
  {
    id: 'tec_59',
    text: 'Which company created the DALL-E image-generation AI model?',
    text_tr: 'DALL-E görsel üretme yapay zeka modelini hangi şirket yarattı?',
    options: { A: 'Google', B: 'Stability AI', C: 'OpenAI', D: 'Midjourney Inc.', E: 'Adobe' },
    options_tr: { A: 'Google', B: 'Stability AI', C: 'OpenAI', D: 'Midjourney Inc.', E: 'Adobe' },
    answer: 'C',
    explanation: 'OpenAI released DALL-E in 2021, generating images from text descriptions.',
  },
  {
    id: 'tec_60',
    text: 'What is the name for a software development approach that delivers small, incremental releases through repeated cycles rather than one large release?',
    text_tr: 'Tek büyük bir sürüm yerine tekrarlanan döngüler halinde küçük, artımlı sürümler sunan yazılım geliştirme yaklaşımına ne ad verilir?',
    options: { A: 'Waterfall model', B: 'Agile methodology', C: 'Spiral model', D: 'V-model', E: 'Big bang model' },
    options_tr: { A: 'Şelale (Waterfall) modeli', B: 'Çevik (Agile) metodoloji', C: 'Spiral model', D: 'V-modeli', E: 'Büyük patlama modeli' },
    answer: 'B',
    explanation: 'Agile methodologies, formalized in the 2001 Agile Manifesto, emphasize iterative development, collaboration, and flexibility.',
  },
  {
    id: 'tec_61',
    text: 'Which company manufactures the "M-series" chips (like the M1 and M2) used in modern Mac computers?',
    text_tr: 'Modern Mac bilgisayarlarda kullanılan "M serisi" çipleri (M1 ve M2 gibi) hangi şirket üretir?',
    options: { A: 'Intel', B: 'Apple', C: 'Samsung', D: 'Qualcomm', E: 'TSMC' },
    options_tr: { A: 'Intel', B: 'Apple', C: 'Samsung', D: 'Qualcomm', E: 'TSMC' },
    answer: 'B',
    explanation: 'Apple designed its own M-series ARM-based chips in-house, moving Macs away from Intel processors starting in 2020.',
  },
  {
    id: 'tec_62',
    text: 'What is the term for a security vulnerability that is unknown to the vendor and has no available patch?',
    text_tr: 'Satıcı tarafından bilinmeyen ve henüz yaması olmayan güvenlik açığına ne ad verilir?',
    options: { A: 'Zero-day vulnerability', B: 'Backdoor', C: 'Buffer overflow', D: 'SQL injection', E: 'Man-in-the-middle attack' },
    options_tr: { A: 'Sıfırıncı gün (zero-day) açığı', B: 'Arka kapı (backdoor)', C: 'Tampon taşması', D: 'SQL enjeksiyonu', E: 'Ortadaki adam saldırısı' },
    answer: 'A',
    explanation: 'A zero-day vulnerability is exploited before developers have "zero days" to fix it, making it especially dangerous.',
  },
  {
    id: 'tec_63',
    text: 'Which company developed the Unreal Engine, widely used for video games and film visual effects?',
    text_tr: 'Video oyunlarında ve film görsel efektlerinde yaygın olarak kullanılan Unreal Engine\'i hangi şirket geliştirdi?',
    options: { A: 'Valve', B: 'Epic Games', C: 'Unity Technologies', D: 'id Software', E: 'CD Projekt' },
    options_tr: { A: 'Valve', B: 'Epic Games', C: 'Unity Technologies', D: 'id Software', E: 'CD Projekt' },
    answer: 'B',
    explanation: 'Epic Games first released Unreal Engine in 1998 alongside the game Unreal, and it has become a leading engine for games and film.',
  },
  {
    id: 'tec_64',
    text: 'What does "SQL" stand for?',
    text_tr: '"SQL" kısaltması neyi ifade eder?',
    options: { A: 'Structured Query Language', B: 'Sequential Query Logic', C: 'System Query Language', D: 'Structured Question Logic', E: 'Standard Query List' },
    options_tr: { A: 'Yapılandırılmış Sorgu Dili', B: 'Sıralı Sorgu Mantığı', C: 'Sistem Sorgu Dili', D: 'Yapılandırılmış Soru Mantığı', E: 'Standart Sorgu Listesi' },
    answer: 'A',
    explanation: 'SQL (Structured Query Language) is used to manage and query data in relational databases.',
  },
  {
    id: 'tec_65',
    text: 'Which company\'s self-driving vehicle division, founded as a Google project in 2009, is named Waymo?',
    text_tr: '2009\'da bir Google projesi olarak kurulan ve Waymo adını taşıyan otonom araç bölümü hangi şirkete aittir?',
    options: { A: 'Tesla', B: 'Alphabet (Google\'s parent company)', C: 'Uber', D: 'Amazon', E: 'Apple' },
    options_tr: { A: 'Tesla', B: 'Alphabet (Google\'ın ana şirketi)', C: 'Uber', D: 'Amazon', E: 'Apple' },
    answer: 'B',
    explanation: 'Waymo began as the Google Self-Driving Car Project in 2009 and became an independent Alphabet subsidiary in 2016.',
  },
  {
    id: 'tec_66',
    text: 'What is the name for the practice of writing code to automate testing of software before it is released?',
    text_tr: 'Bir yazılım piyasaya sürülmeden önce test edilmesini otomatikleştirmek için kod yazma pratiğine ne ad verilir?',
    options: { A: 'Manual testing', B: 'Automated testing', C: 'Exploratory testing', D: 'Static analysis', E: 'User acceptance testing' },
    options_tr: { A: 'Manuel test', B: 'Otomatik test', C: 'Keşifsel test', D: 'Statik analiz', E: 'Kullanıcı kabul testi' },
    answer: 'B',
    explanation: 'Automated testing uses scripts and frameworks (e.g., Selenium, Jest, Playwright) to verify software behavior without manual effort each time.',
  },
  {
    id: 'tec_67',
    text: 'Which company created the WhatsApp messaging app before it was acquired by Facebook in 2014?',
    text_tr: '2014\'te Facebook tarafından satın alınmadan önce WhatsApp mesajlaşma uygulamasını hangi şirket/ekip kurdu?',
    options: { A: 'WhatsApp Inc.', B: 'Snap Inc.', C: 'Telegram FZ-LLC', D: 'Viber Media', E: 'Kik Interactive' },
    options_tr: { A: 'WhatsApp Inc.', B: 'Snap Inc.', C: 'Telegram FZ-LLC', D: 'Viber Media', E: 'Kik Interactive' },
    answer: 'A',
    explanation: 'WhatsApp was founded in 2009 by Brian Acton and Jan Koum, both former Yahoo employees.',
  },
  {
    id: 'tec_68',
    text: 'What does "CDN" stand for, a system that distributes web content across geographically dispersed servers?',
    text_tr: 'Web içeriğini coğrafi olarak dağılmış sunucular arasında dağıtan bir sisteme verilen "CDN" kısaltması neyi ifade eder?',
    options: { A: 'Central Data Node', B: 'Content Delivery Network', C: 'Cached Data Network', D: 'Cloud Delivery Node', E: 'Content Data Node' },
    options_tr: { A: 'Merkezi Veri Düğümü', B: 'İçerik Dağıtım Ağı', C: 'Önbelleklenmiş Veri Ağı', D: 'Bulut Dağıtım Düğümü', E: 'İçerik Veri Düğümü' },
    answer: 'B',
    explanation: 'A CDN (Content Delivery Network) caches content closer to users to reduce latency and improve load times.',
  },
  {
    id: 'tec_69',
    text: 'Which company created the first commercially successful video game console to use cartridges, the Atari 2600, released in 1977?',
    text_tr: '1977\'de piyasaya sürülen ve kartuş kullanan ilk ticari açıdan başarılı video oyunu konsolu Atari 2600\'ü hangi şirket yarattı?',
    options: { A: 'Nintendo', B: 'Sega', C: 'Atari, Inc.', D: 'Magnavox', E: 'Coleco' },
    options_tr: { A: 'Nintendo', B: 'Sega', C: 'Atari, Inc.', D: 'Magnavox', E: 'Coleco' },
    answer: 'C',
    explanation: 'The Atari 2600 popularized interchangeable game cartridges and became a home video game industry cornerstone.',
  },
  {
    id: 'tec_70',
    text: 'What is the name of the open-source, cross-platform framework created by Google for building mobile apps from a single codebase, using the Dart language?',
    text_tr: 'Google tarafından Dart dilini kullanarak tek bir kod tabanından mobil uygulama oluşturmak için yaratılan açık kaynaklı, çapraz platform çerçevesinin adı nedir?',
    options: { A: 'React Native', B: 'Xamarin', C: 'Flutter', D: 'Ionic', E: 'Cordova' },
    options_tr: { A: 'React Native', B: 'Xamarin', C: 'Flutter', D: 'Ionic', E: 'Cordova' },
    answer: 'C',
    explanation: 'Flutter, first released by Google in 2017, uses the Dart programming language to build natively compiled apps.',
  },
  {
    id: 'tec_71',
    text: 'Which company developed the Signal private messaging app, known for end-to-end encryption?',
    text_tr: 'Uçtan uca şifreleme ile bilinen Signal özel mesajlaşma uygulamasını hangi kurum geliştirdi?',
    options: { A: 'Signal Foundation', B: 'Meta', C: 'Telegram FZ-LLC', D: 'Apple', E: 'Google' },
    options_tr: { A: 'Signal Vakfı (Signal Foundation)', B: 'Meta', C: 'Telegram FZ-LLC', D: 'Apple', E: 'Google' },
    answer: 'A',
    explanation: 'Signal is developed by the nonprofit Signal Foundation and Signal Messenger LLC, co-founded by Moxie Marlinspike.',
  },
  {
    id: 'tec_72',
    text: 'What is the name for a type of computer attack that overwhelms a server with traffic from multiple sources to make it unavailable?',
    text_tr: 'Bir sunucuyu erişilemez hale getirmek için birden fazla kaynaktan trafikle boğan saldırı türüne ne ad verilir?',
    options: { A: 'SQL injection', B: 'DDoS attack (Distributed Denial of Service)', C: 'Phishing attack', D: 'Man-in-the-middle attack', E: 'Cross-site scripting' },
    options_tr: { A: 'SQL enjeksiyonu', B: 'DDoS saldırısı (Dağıtık Hizmet Reddi)', C: 'Oltalama saldırısı', D: 'Ortadaki adam saldırısı', E: 'Siteler arası betik çalıştırma' },
    answer: 'B',
    explanation: 'A DDoS attack floods a target with traffic from many compromised devices (often a botnet), overwhelming its resources.',
  },
  {
    id: 'tec_73',
    text: 'Which company created the Zoom video conferencing software?',
    text_tr: 'Zoom video konferans yazılımını hangi şirket yarattı?',
    options: { A: 'Cisco', B: 'Zoom Video Communications', C: 'Microsoft', D: 'Google', E: 'Slack Technologies' },
    options_tr: { A: 'Cisco', B: 'Zoom Video Communications', C: 'Microsoft', D: 'Google', E: 'Slack Technologies' },
    answer: 'B',
    explanation: 'Zoom was founded by Eric Yuan, a former Cisco Webex engineer, in 2011, and saw massive growth during the COVID-19 pandemic.',
  },
  {
    id: 'tec_74',
    text: 'What does "AI" stand for?',
    text_tr: '"AI" kısaltması neyi ifade eder?',
    options: { A: 'Automated Interface', B: 'Artificial Intelligence', C: 'Analytical Integration', D: 'Automated Intelligence Index', E: 'Artificial Interaction' },
    options_tr: { A: 'Otomatik Arayüz', B: 'Yapay Zeka', C: 'Analitik Entegrasyon', D: 'Otomatik Zeka Endeksi', E: 'Yapay Etkileşim' },
    answer: 'B',
    explanation: 'AI (Artificial Intelligence) refers to computer systems designed to perform tasks that typically require human intelligence.',
  },
  {
    id: 'tec_75',
    text: 'Which company created the first widely used web browser to include tabbed browsing as a standard feature?',
    text_tr: 'Sekmeli gezinmeyi standart özellik olarak içeren ilk yaygın kullanılan web tarayıcısını hangi şirket yarattı?',
    options: { A: 'Netscape (with Navigator)', B: 'Opera Software', C: 'Microsoft (with Internet Explorer)', D: 'Mozilla (with Firefox)', E: 'Google (with Chrome)' },
    options_tr: { A: 'Netscape (Navigator ile)', B: 'Opera Software', C: 'Microsoft (Internet Explorer ile)', D: 'Mozilla (Firefox ile)', E: 'Google (Chrome ile)' },
    answer: 'B',
    explanation: 'Opera introduced tabbed browsing in 2000, well before it became standard in other major browsers.',
  },
  {
    id: 'tec_76',
    text: 'What is the term for a database design principle where data is organized to minimize redundancy and dependency?',
    text_tr: 'Verinin fazlalığı ve bağımlılığı en aza indirmek üzere düzenlendiği veritabanı tasarım ilkesine ne ad verilir?',
    options: { A: 'Indexing', B: 'Normalization', C: 'Replication', D: 'Denormalization', E: 'Partitioning' },
    options_tr: { A: 'İndeksleme', B: 'Normalizasyon', C: 'Çoğaltma', D: 'Denormalizasyon', E: 'Bölümleme' },
    answer: 'B',
    explanation: 'Database normalization organizes tables and columns to reduce data duplication and improve data integrity.',
  },
  {
    id: 'tec_77',
    text: 'Which company created the Slack workplace messaging platform, originally as an internal tool for a video game company?',
    text_tr: 'Aslen bir video oyunu şirketinin dahili aracı olarak başlayan Slack iş yeri mesajlaşma platformunu hangi şirket yarattı?',
    options: { A: 'Tiny Speck', B: 'Atlassian', C: 'Salesforce', D: 'HipChat Inc.', E: 'Basecamp' },
    options_tr: { A: 'Tiny Speck', B: 'Atlassian', C: 'Salesforce', D: 'HipChat Inc.', E: 'Basecamp' },
    answer: 'A',
    explanation: 'Slack grew out of an internal communication tool built by Tiny Speck while developing the game Glitch.',
  },
  {
    id: 'tec_78',
    text: 'What does "OS" stand for in computing?',
    text_tr: 'Bilişimde "OS" kısaltması neyi ifade eder?',
    options: { A: 'Operating System', B: 'Output System', C: 'Online Server', D: 'Operational Software', E: 'Optical System' },
    options_tr: { A: 'İşletim Sistemi', B: 'Çıktı Sistemi', C: 'Çevrimiçi Sunucu', D: 'Operasyonel Yazılım', E: 'Optik Sistem' },
    answer: 'A',
    explanation: 'An operating system manages computer hardware and software resources, providing common services for programs.',
  },
  {
    id: 'tec_79',
    text: 'Which company acquired the video-sharing platform YouTube in 2006?',
    text_tr: 'Video paylaşım platformu YouTube\'u 2006\'da hangi şirket satın aldı?',
    options: { A: 'Yahoo', B: 'Microsoft', C: 'Google', D: 'AOL', E: 'Amazon' },
    options_tr: { A: 'Yahoo', B: 'Microsoft', C: 'Google', D: 'AOL', E: 'Amazon' },
    answer: 'C',
    explanation: 'Google acquired YouTube for $1.65 billion in stock in 2006, about a year and a half after its founding.',
  },
  {
    id: 'tec_80',
    text: 'What is the name for a chip design where multiple processing cores are placed on a single chip to run tasks in parallel?',
    text_tr: 'Görevleri paralel çalıştırmak için birden fazla işlem çekirdeğinin tek bir çip üzerine yerleştirildiği çip tasarımına ne ad verilir?',
    options: { A: 'Single-core processor', B: 'Multi-core processor', C: 'Microcontroller', D: 'Coprocessor', E: 'ASIC' },
    options_tr: { A: 'Tek çekirdekli işlemci', B: 'Çok çekirdekli işlemci', C: 'Mikrodenetleyici', D: 'Yardımcı işlemci', E: 'ASIC' },
    answer: 'B',
    explanation: 'Multi-core processors, common since the mid-2000s, allow simultaneous execution of multiple threads or processes.',
  },
  {
    id: 'tec_81',
    text: 'Which company created the Photoshop image-editing software?',
    text_tr: 'Photoshop görüntü düzenleme yazılımını hangi şirket yarattı?',
    options: { A: 'Corel', B: 'Adobe', C: 'Autodesk', D: 'Microsoft', E: 'GIMP Foundation' },
    options_tr: { A: 'Corel', B: 'Adobe', C: 'Autodesk', D: 'Microsoft', E: 'GIMP Vakfı' },
    answer: 'B',
    explanation: 'Photoshop was created by Thomas and John Knoll and released by Adobe in 1990.',
  },
  {
    id: 'tec_82',
    text: 'What does "VR" stand for?',
    text_tr: '"VR" kısaltması neyi ifade eder?',
    options: { A: 'Video Rendering', B: 'Virtual Reality', C: 'Visual Recognition', D: 'Vector Rendering', E: 'Virtual Recording' },
    options_tr: { A: 'Video İşleme', B: 'Sanal Gerçeklik', C: 'Görsel Tanıma', D: 'Vektör İşleme', E: 'Sanal Kayıt' },
    answer: 'B',
    explanation: 'VR (Virtual Reality) creates immersive, computer-generated simulated environments, typically experienced through a headset.',
  },
  {
    id: 'tec_83',
    text: 'Which company created the Oculus Rift VR headset before it was acquired by Facebook in 2014?',
    text_tr: '2014\'te Facebook tarafından satın alınmadan önce Oculus Rift VR başlığını hangi şirket yarattı?',
    options: { A: 'HTC', B: 'Valve Corporation', C: 'Oculus VR', D: 'Sony', E: 'Samsung' },
    options_tr: { A: 'HTC', B: 'Valve Corporation', C: 'Oculus VR', D: 'Sony', E: 'Samsung' },
    answer: 'C',
    explanation: 'Oculus VR was founded by Palmer Luckey, who ran a famous Kickstarter campaign for the Rift before Facebook acquired the company.',
  },
  {
    id: 'tec_84',
    text: 'What is the name for code that runs on a user\'s device (like a browser) rather than on a remote server?',
    text_tr: 'Uzak bir sunucu yerine kullanıcının cihazında (tarayıcı gibi) çalışan koda ne ad verilir?',
    options: { A: 'Server-side code', B: 'Client-side code', C: 'Middleware', D: 'Firmware', E: 'Backend code' },
    options_tr: { A: 'Sunucu tarafı kod', B: 'İstemci tarafı kod', C: 'Ara katman yazılımı', D: 'Bellenim (Firmware)', E: 'Arka uç kod' },
    answer: 'B',
    explanation: 'Client-side code, such as JavaScript running in a browser, executes on the user\'s own device rather than on a remote server.',
  },
  {
    id: 'tec_85',
    text: 'Which company created the TikTok app, originally launching it in China as "Douyin"?',
    text_tr: 'TikTok uygulamasını yaratan ve Çin\'de başlangıçta "Douyin" adıyla piyasaya süren şirket hangisidir?',
    options: { A: 'Tencent', B: 'ByteDance', C: 'Alibaba', D: 'Baidu', E: 'Xiaomi' },
    options_tr: { A: 'Tencent', B: 'ByteDance', C: 'Alibaba', D: 'Baidu', E: 'Xiaomi' },
    answer: 'B',
    explanation: 'ByteDance launched Douyin in China in 2016, and the international version, TikTok, launched in 2017.',
  },
  {
    id: 'tec_86',
    text: 'What does "GUI" stand for?',
    text_tr: '"GUI" kısaltması neyi ifade eder?',
    options: { A: 'Graphical User Interface', B: 'General User Instructions', C: 'Global User Index', D: 'Graphic Utility Interface', E: 'Guided User Integration' },
    options_tr: { A: 'Grafiksel Kullanıcı Arayüzü', B: 'Genel Kullanıcı Talimatları', C: 'Küresel Kullanıcı Dizini', D: 'Grafik Yardımcı Program Arayüzü', E: 'Yönlendirilmiş Kullanıcı Entegrasyonu' },
    answer: 'A',
    explanation: 'A GUI (Graphical User Interface) allows users to interact with electronic devices through visual icons rather than text commands.',
  },
  {
    id: 'tec_87',
    text: 'Which company pioneered the first commercial personal computer with a graphical user interface and mouse, the Xerox Alto (1973), though it was never sold commercially?',
    text_tr: 'Ticari olarak hiç satılmasa da grafiksel arayüz ve fare içeren ilk kişisel bilgisayar olan Xerox Alto\'yu (1973) hangi şirket öncülük etti?',
    options: { A: 'IBM', B: 'Xerox', C: 'Apple', D: 'Digital Equipment Corporation', E: 'Hewlett-Packard' },
    options_tr: { A: 'IBM', B: 'Xerox', C: 'Apple', D: 'Digital Equipment Corporation', E: 'Hewlett-Packard' },
    answer: 'B',
    explanation: 'The Xerox Alto, developed at Xerox PARC, pioneered the GUI, mouse, and Ethernet, directly inspiring Apple\'s Macintosh.',
  },
  {
    id: 'tec_88',
    text: 'What is the term for a technique that reduces a file\'s size for storage or transmission, then restores it later?',
    text_tr: 'Bir dosyanın depolama veya iletim için boyutunu küçültüp daha sonra geri yükleyen tekniğe ne ad verilir?',
    options: { A: 'Encryption', B: 'Compression', C: 'Fragmentation', D: 'Serialization', E: 'Virtualization' },
    options_tr: { A: 'Şifreleme', B: 'Sıkıştırma', C: 'Parçalanma', D: 'Serileştirme', E: 'Sanallaştırma' },
    answer: 'B',
    explanation: 'Compression algorithms (e.g., ZIP, JPEG, MP3) reduce file size by removing redundancy, either losslessly or lossily.',
  },
  {
    id: 'tec_89',
    text: 'Which company created the first widely used web-based email service, Hotmail, in 1996?',
    text_tr: '1996\'da ilk yaygın kullanılan web tabanlı e-posta hizmeti olan Hotmail\'i hangi şirket yarattı?',
    options: { A: 'Yahoo', B: 'Hotmail Corporation', C: 'Microsoft', D: 'AOL', E: 'Google' },
    options_tr: { A: 'Yahoo', B: 'Hotmail Corporation', C: 'Microsoft', D: 'AOL', E: 'Google' },
    answer: 'B',
    explanation: 'Hotmail was founded by Sabeer Bhatia and Jack Smith in 1996 and was acquired by Microsoft in 1997.',
  },
  {
    id: 'tec_90',
    text: 'What does "NFC" stand for, the short-range wireless technology used for contactless payments?',
    text_tr: 'Temassız ödemeler için kullanılan kısa menzilli kablosuz teknolojinin adı olan "NFC" kısaltması neyi ifade eder?',
    options: { A: 'Network File Control', B: 'Near Field Communication', C: 'National Frequency Code', D: 'Network Frequency Channel', E: 'Near Frequency Control' },
    options_tr: { A: 'Ağ Dosya Kontrolü', B: 'Yakın Alan İletişimi', C: 'Ulusal Frekans Kodu', D: 'Ağ Frekans Kanalı', E: 'Yakın Frekans Kontrolü' },
    answer: 'B',
    explanation: 'NFC (Near Field Communication) enables data exchange between devices within a few centimeters, used in contactless payments like Apple Pay.',
  },
  {
    id: 'tec_91',
    text: 'Which company developed the first mainstream 64-bit x86 processor architecture, AMD64, in 2003?',
    text_tr: '2003\'te ilk ana akım 64-bit x86 işlemci mimarisi olan AMD64\'ü hangi şirket geliştirdi?',
    options: { A: 'Intel', B: 'AMD', C: 'IBM', D: 'Motorola', E: 'Cyrix' },
    options_tr: { A: 'Intel', B: 'AMD', C: 'IBM', D: 'Motorola', E: 'Cyrix' },
    answer: 'B',
    explanation: 'AMD introduced the x86-64 (AMD64) architecture, which Intel later adopted as Intel 64.',
  },
  {
    id: 'tec_92',
    text: 'What is the name for software that manages, coordinates, and allocates computer hardware resources between programs?',
    text_tr: 'Bilgisayar donanım kaynaklarını programlar arasında yöneten, koordine eden ve tahsis eden yazılıma ne ad verilir?',
    options: { A: 'Firmware', B: 'Operating system kernel', C: 'Compiler', D: 'Device driver', E: 'Bootloader' },
    options_tr: { A: 'Bellenim (Firmware)', B: 'İşletim sistemi çekirdeği', C: 'Derleyici', D: 'Aygıt sürücüsü', E: 'Önyükleyici' },
    answer: 'B',
    explanation: 'The kernel is the core part of an operating system that manages hardware resources and system calls.',
  },
  {
    id: 'tec_93',
    text: 'Which company created the Discord chat and voice platform, originally aimed at gamers?',
    text_tr: 'Aslen oyunculara yönelik olarak tasarlanan Discord sohbet ve sesli iletişim platformunu hangi şirket yarattı?',
    options: { A: 'Discord Inc.', B: 'Riot Games', C: 'Valve', D: 'Twitch Interactive', E: 'Roblox Corporation' },
    options_tr: { A: 'Discord Inc.', B: 'Riot Games', C: 'Valve', D: 'Twitch Interactive', E: 'Roblox Corporation' },
    answer: 'A',
    explanation: 'Discord was launched in 2015 by Jason Citron and Stan Vishnevskiy, becoming popular beyond gaming communities.',
  },
  {
    id: 'tec_94',
    text: 'What does "ML" commonly stand for in the context of technology?',
    text_tr: 'Teknoloji bağlamında "ML" yaygın olarak neyi ifade eder?',
    options: { A: 'Multi-Layer network', B: 'Machine Learning', C: 'Managed Language', D: 'Media Library', E: 'Modular Logic' },
    options_tr: { A: 'Çok Katmanlı ağ', B: 'Makine Öğrenmesi', C: 'Yönetilen Dil', D: 'Medya Kütüphanesi', E: 'Modüler Mantık' },
    answer: 'B',
    explanation: 'Machine Learning (ML) is a subset of AI where systems learn patterns from data rather than following explicit rules.',
  },
  {
    id: 'tec_95',
    text: 'Which company launched the first reusable orbital-class rocket booster with the Falcon 9, achieving a landing in 2015?',
    text_tr: '2015\'te başarılı bir inişle ilk yeniden kullanılabilir yörünge sınıfı roket güçlendiricisini Falcon 9 ile hangi şirket fırlattı?',
    options: { A: 'Blue Origin', B: 'SpaceX', C: 'NASA', D: 'Rocket Lab', E: 'Boeing' },
    options_tr: { A: 'Blue Origin', B: 'SpaceX', C: 'NASA', D: 'Rocket Lab', E: 'Boeing' },
    answer: 'B',
    explanation: 'SpaceX landed the first stage of a Falcon 9 rocket vertically in December 2015, a milestone for reusable rocketry.',
  },
  {
    id: 'tec_96',
    text: 'What is the term for a piece of hardware or software that lets two otherwise incompatible systems communicate?',
    text_tr: 'Birbiriyle aksi takdirde uyumsuz olan iki sistemin iletişim kurmasını sağlayan donanım veya yazılım parçasına ne ad verilir?',
    options: { A: 'Compiler', B: 'Adapter/interface', C: 'Firewall', D: 'Router', E: 'Hypervisor' },
    options_tr: { A: 'Derleyici', B: 'Adaptör/arayüz', C: 'Güvenlik duvarı', D: 'Yönlendirici (Router)', E: 'Hipervizör' },
    answer: 'B',
    explanation: 'An adapter or interface layer translates between incompatible systems, protocols, or data formats.',
  },
  {
    id: 'tec_97',
    text: 'Which company created the Raspberry Pi single-board computer, originally intended to promote computer science education?',
    text_tr: 'Aslen bilgisayar bilimi eğitimini teşvik etmek amacıyla yaratılan Raspberry Pi tek kartlı bilgisayarını hangi kurum yarattı?',
    options: { A: 'Arduino LLC', B: 'Raspberry Pi Foundation', C: 'Intel', D: 'BeagleBoard.org', E: 'Adafruit Industries' },
    options_tr: { A: 'Arduino LLC', B: 'Raspberry Pi Vakfı', C: 'Intel', D: 'BeagleBoard.org', E: 'Adafruit Industries' },
    answer: 'B',
    explanation: 'The Raspberry Pi Foundation released the first Raspberry Pi in 2012 to make computing more accessible to students.',
  },
  {
    id: 'tec_98',
    text: 'What does "ETL" stand for in data engineering (Extract, ___, Load)?',
    text_tr: 'Veri mühendisliğinde "ETL" (Çıkar, ___, Yükle) kısaltmasındaki orta kelime nedir?',
    options: { A: 'Transform', B: 'Transfer', C: 'Translate', D: 'Transmit', E: 'Transpose' },
    options_tr: { A: 'Dönüştür (Transform)', B: 'Aktar (Transfer)', C: 'Çevir (Translate)', D: 'İlet (Transmit)', E: 'Devrik yap (Transpose)' },
    answer: 'A',
    explanation: 'ETL (Extract, Transform, Load) describes the process of moving data from source systems into a data warehouse.',
  },
  {
    id: 'tec_99',
    text: 'Which company developed the first mass-market laptop computer with a clamshell design, the GRiD Compass, in 1982?',
    text_tr: '1982\'de katlanır (clamshell) tasarıma sahip ilk kitlesel pazarlanan dizüstü bilgisayar olan GRiD Compass\'ı hangi şirket geliştirdi?',
    options: { A: 'Osborne Computer Corporation', B: 'GRiD Systems Corporation', C: 'Compaq', D: 'Tandy Corporation', E: 'Toshiba' },
    options_tr: { A: 'Osborne Computer Corporation', B: 'GRiD Systems Corporation', C: 'Compaq', D: 'Tandy Corporation', E: 'Toshiba' },
    answer: 'B',
    explanation: 'The GRiD Compass, designed by Bill Moggridge, established the now-standard laptop form factor and was famously used by NASA.',
  },
  {
    id: 'tec_100',
    text: 'What is the name of the messaging protocol, developed for lightweight communication, that underlies much of the Internet of Things?',
    text_tr: 'Hafif iletişim için geliştirilen ve Nesnelerin İnterneti\'nin büyük bölümünün temelini oluşturan mesajlaşma protokolünün adı nedir?',
    options: { A: 'HTTP', B: 'MQTT', C: 'FTP', D: 'SOAP', E: 'SMTP' },
    options_tr: { A: 'HTTP', B: 'MQTT', C: 'FTP', D: 'SOAP', E: 'SMTP' },
    answer: 'B',
    explanation: 'MQTT (Message Queuing Telemetry Transport) is a lightweight publish-subscribe protocol widely used for IoT devices with limited bandwidth or power.',
  },
];

module.exports = { technology };
